function helmType(PLR: player) :: number:
	if {_PLR} is wearing a leather helmet:
		return 0.25
	else if {_PLR} is wearing a chain helmet:
		return 0.55
	else if {_PLR} is wearing an iron helmet:
		return 0.75
	else if {_PLR} is wearing a gold helmet:
		return 0.25
	else if {_PLR} is wearing a diamond helmet:
		return 0.8
		
function chestType(PLR: player) :: number:
	if {_PLR} is wearing a leather chestplate:
		return 0.25
	else if {_PLR} is wearing a chain chestplate:
		return 0.55
	else if {_PLR} is wearing an iron chestplate:
		return 1
	else if {_PLR} is wearing a gold chestplate:
		return 0.5
	else if {_PLR} is wearing a diamond chestplate:
		return 2

function legType(PLR: player) :: number:
	if {_PLR} is wearing leather leggings:
		return 0.25
	else if {_PLR} is wearing chain leggings:
		return 0.55
	else if {_PLR} is wearing iron leggings:
		return 1
	else if {_PLR} is wearing gold leggings:
		return 0.5
	else if {_PLR} is wearing diamond leggings:
		return 2
		
function btType(PLR: player) :: number:
	if {_PLR} is wearing leather boots:
		return 0.25
	else if {_PLR} is wearing chain boots:
		return 0.55
	else if {_PLR} is wearing iron boots:
		return 0.75
	else if {_PLR} is wearing gold boots:
		return 0.25
	else if {_PLR} is wearing diamond boots:
		return 0.8
		
#Dodge Roll Toggle Command
command /dr <number>:
	description: Toggles your Dodge Roll on and off.
	usage: /dr
	executable by: players
	trigger:
		if arg 1 is 1:
			set {drenable.%player%} to 1
			send "<green><bold>Dodge Roll enabled! Double tap Sneak to roll backwards."
		else:
			set {drenable.%player%} to 0
			send "<green><bold>Dodge Roll disabled!"

#Dodge Roll Refresh and Double-Tap Check
every 0.5 seconds:
	loop all players:
		if {dr.%loop-player%} is 1 or 2:
			set {dr.%loop-player%} to 0

#DR = 0 - Prepped
#DR = 1 - Ready to activated
#DR = 2 - Exhausted, must recharge.
#DRInvincible - Player is rolling with invincibility

#Check Slots Function Imported From cskills.sk			
function checkSlots(PLR: player , skill: text) :: number:
	if {skillslot1.%{_PLR}%} contains "%{_skill}%":
		return 1
	else if {skillslot2.%{_PLR}%} contains "%{_skill}%":
		return 1
	else if {skillslot3.%{_PLR}%} contains "%{_skill}%":
		return 1
	else if {skillslot4.%{_PLR}%} contains "%{_skill}%":
		return 1
	else if {skillslot5.%{_PLR}%} contains "%{_skill}%":
		return 1
	else:
		return 0

#Dodge Roll
on sneak toggle:
	if {drenable.%player%} is 1:
		if player is sneaking:
			set {dr.%player%} to 1
		if {dr.%player%} is 1:
			if player is sneaking:
				set {dr.%player%} to 1
			else:
				set {_flight} to checkSlots(player,"Flight")
				if player's hunger is less than 6.5:
					send "<red><bold>Not enough hunger to Dodge Roll!" to the player
				else if {_flight} is 1:
					if {flying.%player%} is not set:
						set {flying.%player%} to 1
						set {_armour} to the player's chestplate
						set the player's chestplate to 1 elytra
						push the player upwards at speed 5
						play sound "entity.blaze.shoot" with volume 0.5 and pitch 1.5 at player
						send "<light blue>You take to the skies!"
						wait 1 second
						while player's hunger is more than 3:
							if ground state of player is true:
								exit 1 loop
							else if player is sneaking:
								exit 1 loop
							play 20 (smoke with speed 0) at player
							play 20 (snowball break with speed 0) at player
							play sound "entity.enderdragon.flap" with volume 1 and pitch 1 at player
							push the player forwards at speed 0.5
							if {_food} is not set:
								reduce the player's food level by 0.5
								set {_food} to 1
							else:
								clear {_food}
							wait 1 second
						clear {flying.%player%}
						set the player's chestplate to {_armour}
						send "<light red>Your wings grow tired..."
						play sound "entity.enderdragon.flap" with volume 1 and pitch 1 at player
				else:
					set {DRInvincible.%player%} to 1
					if the 1st line of the lore of the player's boots contains "Slot A - Long Jump":
						push the player forwards at speed 2
					else if the 1st line of the lore of the player's boots contains "Slot A - Quick Stomp":
						push the player downwards at speed 3
					else if the 1st line of the lore of the player's boots contains "Slot A - Boost Jump":
						push the player upwards at speed 2.5
					else:
						push the player backwards at speed 0.85
					play sound "entity.blaze.shoot" with volume 0.5 and pitch 1.5 at player
					loop 15 times:
						show smoke on the player
						show smoke on the player
						show snowball break on the player
						show snowball break on the player
						#if the 2nd line of the lore of the player's boots does not contain "Slot B - Pass.":
						#	if distance of any entity and the player is more than 1:
						#		if the 2nd line of the lore of the player's boots contains "Slot B - Ram.":
						#			push the entity upwards at speed 1
						#			damage the entity by 1
						#		else:
						#			set the player's speed to 0
						wait 1 tick
					set {_slotcheck.%player%} to checkSlots(player,"Light Feet")
					if {_slotcheck.%player%} is 0:
						reduce the player's food level by 0.5
					set {dr.%player%} to 2
					if {combo.%player%} is more than 6:
						add 6 to {combo.%player%}
					set {DRInvincible.%player%} to 0

#Dodge Roll Invincibility
on damage:
	if victim is a player:
		if {DRInvincible.%victim%} is 1:
			add 1 to {qptally.%victim%}
			if {qptally.%victim%} is more than 49:
				if {Quickened Pulse.%victim%} is not set:
					make victim execute command "/grantskill 0 Quickened Pulse"
			set {_slotcheck.%victim%} to checkSlots(victim,"Quickened Pulse")
			send "<green><bold>Dodged the attack!" to the victim
			play sound "item.totem.use" with volume 1 and pitch 1 at attacker for victim
			set damage to 0
			apply speed 1 to the victim for 3 seconds
			if the 1st line of the lore of the victim's boots contains "Slot A - Quickened Pulse":
				apply slowness 6 to the attacker for 3 seconds
				apply weakness 6 to the attacker for 3 seconds
				apply mining fatigue 6 to the attacker for 3 seconds
				send "<light blue><bold>Quickened Pulse activated!" to the victim
				loop 5 times:
					show smoke on the attacker
					show smoke on the attacker
					show magical critical hit on the attacker
					show magical critical hit on the attacker
				#wait 2 ticks
			else if the 1st line of the lore of the victim's boots contains "Slot A - Witch Time":
				apply slowness 6 to the attacker for 3 seconds
				apply weakness 6 to the attacker for 3 seconds
				apply mining fatigue 6 to the attacker for 3 seconds
				send "<light purple><bold>Witch Time activated!" to the victim
				set {_cheeky} to a random integer between 1 and 8
				if {_cheeky} is 1:
					send "<light purple><bold>Is that all you've got?" to the attacker
					send "<light purple><bold>Is that all you've got?" to the victim
				else if {_cheeky} is 2:
					send "<light purple><bold>Can't touch me!" to the attacker
					send "<light purple><bold>Can't touch me!" to the victim
				else if {_cheeky} is 3:
					send "<light purple><bold>Too late!" to the attacker
					send "<light purple><bold>Too late!" to the victim
				else if {_cheeky} is 4:
					send "<light purple><bold>So close!" to the attacker
					send "<light purple><bold>So close!" to the victim
				else if {_cheeky} is 5:
					send "<light purple><bold>Almost!" to the attacker
					send "<light purple><bold>Almost!" to the victim
				else if {_cheeky} is 6:
					send "<light purple><bold>Boring!" to the attacker
					send "<light purple><bold>Boring!" to the victim
				else if {_cheeky} is 7:
					send "<light purple><bold>Dreadful!" to the attacker
					send "<light purple><bold>Dreadful!" to the victim
				else if {_cheeky} is 8:
					send "<light purple><bold>Not quite!" to the attacker
					send "<light purple><bold>Not quite!" to the victim
				loop 5 times:
					show smoke on the attacker
					show smoke on the attacker
					show magical critical hit on the attacker
					show magical critical hit on the attacker
				#wait 1 tick
			else if {_slotcheck.%victim%} is 1:
				apply slowness 6 to the attacker for 3 seconds
				apply weakness 6 to the attacker for 3 seconds
				apply mining fatigue 6 to the attacker for 3 seconds
				send "<light blue><bold>Quickened Pulse activated!" to the victim
				loop 5 times:
					show smoke on the attacker
					show smoke on the attacker
					show magical critical hit on the attacker
					show magical critical hit on the attacker
				#wait 2 ticks

#Skill Activation Quotes
command /quote [<number=0>] [<text="">]:
	description: Set a custom quote to send to your victim when activating certain skills.
	usage: /quote (ID) (Quote)
	executable by: players
	trigger:
		if arg 1 is 1:
			set {skillquote1.%player%} to arg 2
			send "<yellow>Set quote 1 to '%arg 2%'!"
		else if arg 1 is 2:
			set {skillquote2.%player%} to arg 2
			send "<yellow>Set quote 2 to '%arg 2%'!"
		else if arg 1 is 3:
			set {skillquote3.%player%} to arg 2
			send "<yellow>Set quote 3 to '%arg 2%'!"
		else if arg 1 is 4:
			set {skillquote4.%player%} to arg 2
			send "<yellow>Set quote 4 to '%arg 2%'!"
		else if arg 1 is 0:
			send "<light blue>Your current quotes:"
			send "<light blue>1. %{skillquote1.%player%}%"
			send "<light blue>2. %{skillquote2.%player%}%"
			send "<light blue>3. %{skillquote3.%player%}%"
			send "<light blue>4. %{skillquote4.%player%}%"

command /sandbag:
	description: Spawn an infinite-health sandbag that tells you the amount of damage you just dealt.
	usage: /sandbag
	executable by: players
	trigger:
		spawn 1 armor stand at the player
		set the name of the last spawned entity to "<gold><bold>Sandbag"

command /sbtoggle:
	description: Toggle damaging of Sandbags
	usage: /sbtoggle
	executable by: players
	trigger:
		if {sandbagkillable.%player%} is 0:
			set {sandbagkillable.%player%} to 1
			send "Your attacks will now damage Sandbags."
		else:
			set {sandbagkillable.%player%} to 0
			send "Your attacks will no longer damage Sandbags."
	

#Define new weapon type - Lances:
on load:
	register new shaped recipe for wood shovel named "<bold>Wooden Lance" using air, any planks, air, any planks, stick, any planks, air, stick, air
	register new shaped recipe for stone shovel named "<bold>Stone Lance" using air, cobblestone, air, cobblestone, stick, cobblestone, air, stick, air
	register new shaped recipe for iron shovel named "<bold>Iron Lance" using air, iron ingot, air, iron ingot, stick, iron ingot, air, stick, air
	register new shaped recipe for gold shovel named "<bold>Golden Lance" using air, gold ingot, air, gold ingot, stick, gold ingot, air, stick, air
	register new shaped recipe for diamond shovel named "<bold>Diamond Lance" using air, diamond, air, diamond, stick, diamond, air, stick, air
#Lance damage correction
on right-click:
	if the name of the player's tool contains "<bold>Wooden Lance":
		shoot an arrow from the player
		set metadata value "JavType" of the last shot projectile to 1
		damage the player's tool by 2
	else if the name of the player's tool contains "<bold>Stone Lance":
		shoot an arrow from the player
		set metadata value "JavType" of the last shot projectile to 2
		damage the player's tool by 3
	else if the name of the player's tool contains "<bold>Iron Lance":
		shoot an arrow from the player
		set metadata value "JavType" of the last shot projectile to 3
		damage the player's tool by 4
	else if the name of the player's tool contains "<bold>Golden Lance":
		shoot an arrow from the player
		set metadata value "JavType" of the last shot projectile to 4
		damage the player's tool by 1
	else if the name of the player's tool contains "<bold>Diamond Lance":
		shoot an arrow from the player
		set metadata value "JavType" of the last shot projectile to 5
		damage the player's tool by 5

#Magically-Inclined Class Check Function
function checkClass(PLR: player) :: number:
	if {class.%{_PLR}%} is "Mage":
		return 1
	else if {class.%{_PLR}%} is "Sage":
		return 1
	else if {class.%{_PLR}%} is "Sorcerer":
		return 1
	else if {class.%{_PLR}%} is "Mage Knight":
		return 1
	else if {class.%{_PLR}%} is "Strategist":
		return 1
	else if {class.%{_PLR}%} is "Tactician":
		return 1
	else if {class.%{_PLR}%} is "Grandmaster":
		return 1
	else:
		return 0

on damage:
	if the projectile is an arrow:
		set {_JAVTYPE} to metadata value "JavType" of projectile
		if {_JAVTYPE} is 1:
			set damage to 1.5
		else if {_JAVTYPE} is 2:
			set damage to 2.5
		else if {_JAVTYPE} is 3:
			set damage to 3.5
		else if {_JAVTYPE} is 4:
			set damage to 4.5
		else if {_JAVTYPE} is 5:
			set damage to 5
	else if the name of the attacker's tool contains "<bold>Wooden Lance":
		set damage to 2
	else if the name of the attacker's tool contains "<bold>Stone Lance":
		set damage to 3
	else if the name of the attacker's tool contains "<bold>Iron Lance":
		set damage to 4
	else if the name of the attacker's tool contains "<bold>Golden Lance":
		set damage to 3
	else if the name of the attacker's tool contains "<bold>Diamond Lance":
		set damage to 5
		
#arg 1: Menu | arg 2: Shopping Cart | arg 3: Menu Layer
command /skills [<text="TopMenu">] [<text="NULL">] [<number=0>]:
	description: Browse and purchase skills.
	usage: /skills
	executable by: players
	trigger:
		if arg 1 is "TopMenu":
			open chest with 2 rows named "<gold><bold>Skills Menu" for the player
			set slot 0 of the player's current inventory to 1 red wool named "<light red><bold>A-Slot Skills"
			set slot 1 of the player's current inventory to 1 light blue wool named "<light blue><bold>B-Slot Skills"
			set slot 2 of the player's current inventory to 1 yellow wool named "<yellow><bold>C-Slot Skills"
			set slot 3 of the player's current inventory to 1 green wool named "<light green><bold>Assist Skills"
			set slot 4 of the player's current inventory to 1 purple wool named "<light purple><bold>Special Skills"
			set slot 5 of the player's current inventory to 1 anvil named "<green><bold>Weapon Refinery"
			set slot 6 of the player's current inventory to 1 diamond chestplate named "<cyan><bold>Armour Skills"
			set slot 7 of the player's current inventory to 1 storage minecart named "<purple><bold>Inherit Skills"
			set slot 8 of the player's current inventory to 1 wooden sword named "<gray><bold>Upgrade/Merge Tools"
			set slot 9 of the player's current inventory to 1 diamond sword named "<gold><bold>Holy Weapons"
			set slot 10 of the player's current inventory to 1 stone sword named "<white><bold>Repair Tools"
			#set slot 9 of the player's current inventory to 1 book named "<pink><bold>Skill Info: OFF"
			set slot 11 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is "A-Skills":
			open chest with 5 rows named "<light red><bold>Skills Menu | A-Slot Skills" for the player
			set slot 0 of the player's current inventory to 1 diamond sword named "<light red><bold>Distant Counter" with lore "Auto attacks ranged attackers.", "<light blue><bold>Melee Only"
			set slot 1 of the player's current inventory to 1 bow named "<light red><bold>Close Counter" with lore "Auto-attacks melee attackers.", "<light blue><bold>Bows Only"
			set slot 2 of the player's current inventory to 1 diamond sword named "<light red><bold>Warp Strike" with lore "Warp to the attacker when hit.", "<light blue><bold>Melee Only"
			set slot 3 of the player's current inventory to 1 iron sword named "<light red><bold>Armour Smasher" with lore "Bonus damage against armour.", "The stronger the armour, the more damage."
			set slot 4 of the player's current inventory to 1 iron sword named "<light red><bold>Fury" with lore "Attacks deal 3 more hearts of damage.", "Take 1.5 hearts of recoil damage."
			set slot 5 of the player's current inventory to 1 iron sword named "<light red><bold>Life and Death" with lore "Attacks deal 75%% more damage.", "Take 75%% more damage."
			set slot 6 of the player's current inventory to 1 iron sword named "<light red><bold>Death Blow" with lore "Grants STR +30 for 10 seconds on-hit.", "Recharge: 15 seconds"
			set slot 7 of the player's current inventory to 1 iron sword named "<light red><bold>Darting Blow" with lore "Grants SPD +30 for 10 seconds on-hit.", "Recharge: 15 seconds"
			set slot 8 of the player's current inventory to 1 iron sword named "<light red><bold>Armoured Blow" with lore "Grants DEF +30 for 10 seconds on-hit.", "Recharge: 15 seconds"
			set slot 9 of the player's current inventory to 1 iron sword named "<light red><bold>Defiant Attack" with lore "Grants Strength 4 when HP < 50%%."
			set slot 10 of the player's current inventory to 1 iron sword named "<light red><bold>Defiant Speed" with lore "Grants Swiftness 4 when HP < 50%%."
			set slot 11 of the player's current inventory to 1 iron sword named "<light red><bold>Defiant Resistance" with lore "Grants Resistance 4 when HP < 50%%."
			set slot 12 of the player's current inventory to 1 iron sword named "<light red><bold>Close Defence" with lore "Incoming melee damage reduced by 66%%."
			set slot 13 of the player's current inventory to 1 iron sword named "<light red><bold>Distant Defence" with lore "Incoming ranged damage reduced by 66%%."
			set slot 14 of the player's current inventory to 1 bow named "<light red><bold>Quick Draw" with lore "Arrows fire instantly.", "Decreases range & power.", "<Light blue><bold>Bows Only"
			set slot 15 of the player's current inventory to 1 iron sword named "<light red><bold>STR/SKL Bond" with lore "STR/SKL +40", "Must be within 10 blocks of a party member."
			set slot 16 of the player's current inventory to 1 iron sword named "<light red><bold>DEF/MAG Bond" with lore "DEF/MAG +40", "Must be within 10 blocks of a party member."
			set slot 17 of the player's current inventory to 1 iron sword named "<light red><bold>DEF/SKL Bond" with lore "DEF/SKL +40", "Must be within 10 blocks of a party member."
			set slot 18 of the player's current inventory to 1 iron sword named "<light red><bold>MAG/SKL Bond" with lore "MAG/SKL +40", "Must be within 10 blocks of a party member."
			set slot 19 of the player's current inventory to 1 iron sword named "<light red><bold>STR/MAG Bond" with lore "STR/MAG +40", "Must be within 10 blocks of a party member."
			set slot 20 of the player's current inventory to 1 iron sword named "<light red><bold>STR/DEF Bond" with lore "STR/DEF +40", "Must be within 10 blocks of a party member."
			set slot 21 of the player's current inventory to 1 iron sword named "<light red><bold>STR/SKL Solo" with lore "STR/SKL +40", "Must be at least 10 blocks away from a party member."
			set slot 22 of the player's current inventory to 1 iron sword named "<light red><bold>DEF/MAG Solo" with lore "DEF/MAG +40", "Must be at least 10 blocks away from a party member."
			set slot 23 of the player's current inventory to 1 iron sword named "<light red><bold>DEF/SKL Solo" with lore "DEF/SKL +40", "Must be at least 10 blocks away from a party member."
			set slot 24 of the player's current inventory to 1 iron sword named "<light red><bold>MAG/SKL Solo" with lore "MAG/SKL +40", "Must be at least 10 blocks away from a party member."
			set slot 25 of the player's current inventory to 1 iron sword named "<light red><bold>STR/MAG Solo" with lore "STR/MAG +40", "Must be at least 10 blocks away from a party member."
			set slot 26 of the player's current inventory to 1 iron sword named "<light red><bold>STR/DEF Solo" with lore "STR/DEF +40", "Must be at least 10 blocks away from a party member."
			set slot 27 of the player's current inventory to 1 iron sword named "<light red><bold>Sorcery Aura" with lore "Weapon calculates damage using attacker & foes MAG."
			set slot 28 of the player's current inventory to 1 iron sword named "<light red><bold>Steady Stance" with lore "Grants DEF +20 for 2 seconds when attacked."
			set slot 29 of the player's current inventory to 1 iron sword named "<light red><bold>Swift Stance" with lore "Grants SPD +20 for 2 seconds when attacked."
			set slot 30 of the player's current inventory to 1 iron sword named "<light red><bold>Warding Stance" with lore "Grants MAG +20 for 2 seconds when attacked."
			set slot 31 of the player's current inventory to 1 iron sword named "<light red><bold>Fierce Stance" with lore "Grants STR +20 for 2 seconds when attacked."
			set slot 32 of the player's current inventory to 1 iron sword named "<light red><bold>Swift Sparrow" with lore "Grants STR/SPD +20 for 7 seconds on-hit.", "Recharge: 14 seconds"
			set slot 33 of the player's current inventory to 1 iron sword named "<light red><bold>Steady Blow" with lore "Grants STR/DEF +20 for 7 seconds on-hit.", "Recharge: 14 seconds"
			set slot 34 of the player's current inventory to 1 iron sword named "<light red><bold>Power Within" with lore "Grants STR/SPD/DEF/MAG +20 while equipped.", "Drains 0.5 hearts every second."
			set slot 35 of the player's current inventory to 1 iron sword named "<light red><bold>STR Focus" with lore "On kill:", "Grants +5 STR.", "Effect stacks, and is lost after taking damage."
			set slot 36 of the player's current inventory to 1 iron sword named "<light red><bold>SPD Focus" with lore "On kill:", "Grants +5 SPD.", "Effect stacks, and is lost after taking damage."
			set slot 37 of the player's current inventory to 1 iron sword named "<light red><bold>SKL Focus" with lore "On kill:", "Grants +5 SKL.", "Effect stacks, and is lost after taking damage."
			set slot 38 of the player's current inventory to 1 iron sword named "<light red><bold>DEF Focus" with lore "On kill:", "Grants +5 DEF.", "Effect stacks, and is lost after taking damage."
			set slot 39 of the player's current inventory to 1 iron sword named "<light red><bold>MAG Focus" with lore "On kill:", "Grants +5 MAG.", "Effect stacks, and is lost after taking damage."
			set slot 40 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is "B-Skills":
			open chest with 4 rows named "<light blue><bold>Skills Menu | B-Slot Skills" for the player
			#set slot 6 of the player's current inventory to 1 iron sword named "<light blue><bold>Escape Route" with lore "N/A"
			#set slot 7 of the player's current inventory to 1 iron sword named "<light blue><bold>Wings of Mercy" with lore "N/A"
			set slot 0 of the player's current inventory to 1 iron sword named "<light blue><bold>Sabotage Attack" with lore "Inflicts Weakness 2 on the victim."
			set slot 1 of the player's current inventory to 1 iron sword named "<light blue><bold>Sabotage Defense" with lore "Increases damage dealt by 35%%."
			set slot 2 of the player's current inventory to 1 iron sword named "<light blue><bold>Sabotage Speed" with lore "Inflicts Slowness 2 on the victim."
			set slot 3 of the player's current inventory to 1 iron sword named "<light blue><bold>Poison Strike" with lore "Inflicts Wither 3 on the victim."
			set slot 4 of the player's current inventory to 1 iron sword named "<light blue><bold>Desperation" with lore "When HP <= 50%%:", "Automatically make a follow up-attack."
			set slot 5 of the player's current inventory to 1 iron sword named "<light blue><bold>Riposte" with lore "When HP > 80%%:", "Automatically make a return attack.", "Auto return attacks deal 75%% less damage."
			set slot 6 of the player's current inventory to 1 iron sword named "<light blue><bold>Brash Assault" with lore "When HP < 50%%:", "Follow-up attacks deal 2x damage.", "Grants Resistance 2 for 2 seconds (stacks)."
			set slot 7 of the player's current inventory to 1 iron sword named "<light blue><bold>Wrath" with lore "When HP <= 50%%:", "Grants SKL +30", "If C-Slot skill deals damage, increases damage of C-Slot activation by 2.5 hearts."
			set slot 8 of the player's current inventory to 1 iron sword named "<light blue><bold>Plentitude" with lore "On kill:", "Drop 1 steak at the victim.", "Heals 1 point of hunger.", "Activation chance: (30 + (MAG / 2))"
			set slot 9 of the player's current inventory to 1 iron sword named "<light blue><bold>Despoil" with lore "On kill:", "Drop Bullion at the victim.", "Bullion grants bonus money.", "Bullion (S) chance: (10 + (MAG / 2))", "Bullion (M) chance: (5 + (MAG / 2))", "Bullion (L) chance: (1 + (MAG / 2))", "Bullion (XL) chance: (MAG / 2)"
			set slot 10 of the player's current inventory to 1 iron sword named "<light blue><bold>Experience Sapper" with lore "Grants bonus EXP on-kill."
			set slot 11 of the player's current inventory to 1 iron sword named "<light blue><bold>Shield Pulse" with lore "If enemy attack triggers C-Slot special:", "Activation chance +10%%", "Reduces damage by 2.5 hearts on activation."
			set slot 12 of the player's current inventory to 1 iron sword named "<light blue><bold>Bonus Blade" with lore "Multiplies stat bonuses by 1.5x. Calculated per stat.", "EX: Player has a +40 STR Buff,", "Bonus Blade increases the bonus to +60."
			set slot 13 of the player's current inventory to 1 iron sword named "<light blue><bold>Brave Blade" with lore "Weapon attacks twice when initiating combat.", "Inflicts SPD -15.", "-3 Might (1.5 hearts)"
			set slot 14 of the player's current inventory to 1 iron sword named "<light blue><bold>Eclipse Brace" with lore "If C-Slot activation deals damage:", "Reduces enemy DEF by 30%%.", "Stacks with the effects of skills like Luna."
			set slot 15 of the player's current inventory to 1 iron sword named "<light blue><bold>Solar Brace" with lore "If C-Slot activation deals damage:", "Restores health equal to 50%% of damage dealt.", "Stacks with the effects of skills like Sol."
			set slot 16 of the player's current inventory to 1 iron sword named "<light blue><bold>Guard" with lore "When attacked:", "Inflicts SKL -30 on the attacker.", "Duration: 5 seconds", "Effect does not stack."
			set slot 16 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is "C-Skills":
			open chest with 2 rows named "<yellow><bold>Sklls Menu | C-Slot Skills" for the player
			set slot 0 of the player's current inventory to 1 iron sword named "<light yellow><bold>Hone STR" with lore "Grants +20 STR to the nearest ally within 10 blocks.", "Duration: 5 seconds"
			set slot 1 of the player's current inventory to 1 iron sword named "<light yellow><bold>Hone SPD" with lore "Grants +20 SPD to the nearest ally within 10 blocks.", "Duration: 5 seconds"
			set slot 2 of the player's current inventory to 1 iron sword named "<light yellow><bold>Hone SKL" with lore "Grants +20 SKL to the nearest ally within 10 blocks.", "Duration: 5 seconds"
			set slot 3 of the player's current inventory to 1 iron sword named "<light yellow><bold>Hone DEF" with lore "Grants +20 DEF to the nearest ally within 10 blocks.", "Duration: 5 seconds"
			set slot 4 of the player's current inventory to 1 iron sword named "<light yellow><bold>Hone MAG" with lore "Grants +20 MAG to the nearest ally within 10 blocks.", "Duration: 5 seconds"
			set slot 5 of the player's current inventory to 1 iron sword named "<light yellow><bold>Drive STR" with lore "Grants +10 STR to all allies within 10 blocks.", "Duration: 5 seconds"
			set slot 6 of the player's current inventory to 1 iron sword named "<light yellow><bold>Drive SPD" with lore "Grants +10 SPD to all allies within 10 blocks.", "Duration: 5 seconds"
			set slot 7 of the player's current inventory to 1 iron sword named "<light yellow><bold>Drive SKL" with lore "Grants +10 SKL to all allies within 10 blocks.", "Duration: 5 seconds"
			set slot 8 of the player's current inventory to 1 iron sword named "<light yellow><bold>Drive DEF" with lore "Grants +10 DEF to all allies within 10 blocks.", "Duration: 5 seconds"
			set slot 9 of the player's current inventory to 1 iron sword named "<light yellow><bold>Drive MAG" with lore "Grants +10 MAG to all allies within 10 blocks.", "Duration: 5 seconds"
			set slot 10 of the player's current inventory to 1 iron sword named "<light yellow><bold>STR Smoke" with lore "On Hit:", "Inflicts -10 STR on all foes within 10 blocks of the victim.", "Duration: 5 seconds", "Victim is excluded from the debuff."
			set slot 11 of the player's current inventory to 1 iron sword named "<light yellow><bold>SPD Smoke" with lore "On Hit:", "Inflicts -10 SPD on all foes within 10 blocks of the victim.", "Duration: 5 seconds", "Victim is excluded from the debuff."
			set slot 12 of the player's current inventory to 1 iron sword named "<light yellow><bold>SKL Smoke" with lore "On Hit:", "Inflicts -15 SKL on all foes within 10 blocks of the victim.", "Duration: 5 seconds", "Victim is excluded from the debuff."
			set slot 13 of the player's current inventory to 1 iron sword named "<light yellow><bold>DEF Smoke" with lore "On Hit:", "Inflicts -10 DEF on all foes within 10 blocks of the victim.", "Duration: 5 seconds", "Victim is excluded from the debuff."
			set slot 14 of the player's current inventory to 1 iron sword named "<light yellow><bold>MAG Smoke" with lore "On Hit:", "Inflicts -10 MAG on all foes within 10 blocks of the victim.", "Duration: 5 seconds", "Victim is excluded from the debuff."
			set slot 15 of the player's current inventory to 1 iron sword named "<light yellow><bold>Breath of Life" with lore "On Hit:", "Allies within 10 blocks heal health equal to 25%% of damage dealt.", "Excludes the attacker."
			set slot 16 of the player's current inventory to 1 iron sword named "<light yellow><bold>Savage Blow" with lore "On Hit:", "Foes within 10 blocks suffer damage equal to 25%% of damage dealt.", "Excludes the victim."
			set slot 17 of the player's current inventory to 1 iron sword named "<light yellow><bold>Pressure STR" with lore "If player's MAG > Foes MAG + 10:", "Inflicts STR -20 on foes within 10 blocks."
		
		else if arg 1 is "Specials":
			open chest with 2 rows named "<light purple><bold>Skills Menu | Special Skills" for the player
			set slot 0 of the player's current inventory to 1 iron sword named "<light purple><bold>Moonbow" with lore "Negates enemy armour bonuses.", "Reduces enemy DEF by 30%%.", "Activation chance: (SKL ^ 0.85)", "Max: 80%%"
			set slot 1 of the player's current inventory to 1 iron sword named "<light purple><bold>Luna" with lore "Negates enemy armour bonuses and adds 50%% of it to damage dealt.", "Reduces enemy DEF by 50%%.", "Activation chance: (SKL ^ 0.75)", "Max: 70%%"
			set slot 2 of the player's current inventory to 1 iron sword named "<light purple><bold>Sol" with lore "Restores HP = 75%% of damage dealt.", "Activation chance: (SKL ^ 0.7)", "Max: 70%%"
			set slot 3 of the player's current inventory to 1 iron sword named "<light purple><bold>Retribution" with lore "Adds 50%% of damage suffered to damage dealt.", "Activation chance: (SKL ^ 0.675)", "Max: 70%%."
			set slot 4 of the player's current inventory to 1 iron sword named "<light purple><bold>Pavise" with lore "Reduces melee damage suffered by 50%%.", "Activation chance: (SKL ^ 0.8)", "Max: 85%%."
			set slot 5 of the player's current inventory to 1 iron sword named "<light purple><bold>Aether" with lore "Activates both Luna and Sol at one time.", "Activation chance: (SKL ^ 0.55)", "Max: 65%%."
			set slot 6 of the player's current inventory to 1 iron sword named "<light purple><bold>Glimmer" with lore "Increases damage dealt by 50%%.", "Activation chance: (SKL ^ 0.765)", "Max: 70%%"
			set slot 7 of the player's current inventory to 1 iron sword named "<light purple><bold>Astra" with lore "Increases damage dealt by 200%%.", "Activation chance: (SKL ^ 0.65)", "Max: 50%%"
			set slot 8 of the player's current inventory to 1 iron sword named "<light purple><bold>Blazing Light" with lore "Increases damage dealt by 50%%.", "Damages all enemies within 7 blocks.", "Radius damage = 50%% of damage dealt.", "Activation chance: (SKL ^ 0.7)", "Max: 50%%"
			set slot 9 of the player's current inventory to 1 iron sword named "<light purple><bold>Ignis" with lore "Adds 50%% of attacker's DEF to damage dealt.", "Activation chance: (SKL ^ 0.7)", "Max: 50%%"
			set slot 10 of the player's current inventory to 1 iron sword named "<light purple><bold>Glacies" with lore "Adds 50%% of attacker's MAG to damage dealt.", "Activation chance: (SKL ^ 0.7)", "Max: 50%%."
			set slot 11 of the player's current inventory to 1 iron sword named "<light purple><bold>Rising Wind" with lore "Adds 50%% of attacker's SPD to damage dealt.", "Activation chance: (SKL ^ 0.7)", "Max: 50%%."
			set slot 12 of the player's current inventory to 1 iron sword named "<light purple><bold>Dragon Fang" with lore "Adds 50%% of attacker's STR to damage dealt.", "Activation chance: (SKL ^ 0.7)", "Max: 50%%."
			set slot 13 of the player's current inventory to 1 iron sword named "<light purple><bold>Galeforce" with lore "Grants Swiftness 8 and Strength 1.", "Activation chance: (SKL ^ 0.6)", "Max: 50%%.", "Recharge duration: 30 seconds."
			set slot 14 of the player's current inventory to 1 iron sword named "<light purple><bold>Aegis" with lore "Reduces ranged damage suffered by 50%%.", "Activation chance: (SKL ^ 0.8)", "Max: 85%%."
			set slot 15 of the player's current inventory to 1 iron sword named "<light purple><bold>Growing Light" with lore "Increases damage dealt by 25%%.", "Damages all enemies within 14 blocks.", "Radius damage = 50%% of damage dealt.", "Activation chance: (SKL ^ 0.7)", "Max: 50%%"
			set slot 16 of the player's current inventory to 1 iron sword named "<light purple><bold>Miracle" with lore "If foe's attack would kill:", "Nullifies foe's attack, and inflicts weakness 4 on the attacker for 3 seconds.", "Activation chance: (SKL ^ 0.5)", "Max: 50%%"
			set slot 17 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is "Assists":
			open chest with 2 rows named "<light green><bold>Skills Menu | Assist Skills" for the player
			set slot 0 of the player's current inventory to 1 diamond sword named "<light green><bold>Drag Back" with lore "Drags the victim backwards.", "<light green><bold>Melee Only"
			set slot 1 of the player's current inventory to 1 diamond sword named "<light green><bold>Hit and Run" with lore "Pushes you backwards.", "<light green><bold>Melee Only"
			set slot 2 of the player's current inventory to 1 iron sword named "<light green><bold>Reposition" with lore "Warps target behind you when right-clicked."
			set slot 3 of the player's current inventory to 1 iron sword named "<light green><bold>Swap" with lore "Swap positions with the target on right-click."
			set slot 4 of the player's current inventory to 1 iron sword named "<light green><bold>Shove" with lore "Push the target up and away on right-click."
			set slot 5 of the player's current inventory to 1 iron sword named "<light green><bold>Launcher" with lore "Launch the target upwards on right-click.", "Hold Sneak to launch alongside the target."
			set slot 6 of the player's current inventory to 1 iron sword named "<light green><bold>Fortify Health" with lore "On right-click:", "Grants Absorption 2."
			set slot 7 of the player's current inventory to 1 iron sword named "<light green><bold>Ardent Sacrifice" with lore "Heals target by 2 hearts on right-click.", "Damages user by 2 hearts."
			set slot 8 of the player's current inventory to 1 iron sword named "<light green><bold>Restore" with lore "Heals the user on right-click.", "Damages tool."
			set slot 9 of the player's current inventory to 1 iron sword named "<light green><bold>Rally Speed" with lore "Grants Swiftness 1 to target on right-click.", "Damages tool."
			set slot 10 of the player's current inventory to 1 iron sword named "<light green><bold>Rally Strength" with lore "Grants Strength 1 to target on right-click.", "Damages tool."
			set slot 11 of the player's current inventory to 1 iron sword named "<light green><bold>Rally Resistance" with lore "Grants Resistance 1 to target on right-click.", "Damages tool."
			set slot 12 of the player's current inventory to 1 iron sword named "<light green><bold>Rally Spectrum" with lore "Grants on right-click:", "Strength/Swiftness/Resistance 1 to target.", "Damages tool."
			set slot 13 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is "Armour":
			open chest with 3 rows named "<cyan><bold>Skills Menu | Armour Skills" for the player
			set slot 0 of the player's current inventory to 1 diamond boots named "<cyan><bold>Quick Stomp" with lore "Fly towards the ground.", "Negates fall damage while stomping."
			set slot 1 of the player's current inventory to 1 diamond boots named "<cyan><bold>Boost Jump" with lore "Leap into the sky."
			set slot 2 of the player's current inventory to 1 diamond boots named "<cyan><bold>Long Jump" with lore "Spring forwards a large distance."
			set slot 3 of the player's current inventory to 1 diamond boots named "<cyan><bold>Hover" with lore "Hold sneak to hover in mid-air.", "Consumes hunger while hovering."
			set slot 4 of the player's current inventory to 1 diamond boots named "<cyan><bold>Quickened Pulse" with lore "Slows down time after dodging an attack."
			set slot 5 of the player's current inventory to 1 diamond boots named "<purple><bold>Witch Time" with lore "Slows down time after dodging an attack."
			set slot 6 of the player's current inventory to 1 diamond chestplate named "<cyan><bold>Glory Kills" with lore "Unarmed kills grant:", "Strength/Resistance 1, Speed 2, Haste 4"
			set slot 7 of the player's current inventory to 1 diamond leggings named "<cyan><bold>Regeneration" with lore "Grants Regeneration 2 while equipped."
			set slot 8 of the player's current inventory to 1 diamond leggings named "<cyan><bold>Swiftness" with lore "Grants Swiftness 2 while equipped."
			set slot 9 of the player's current inventory to 1 diamond leggings named "<cyan><bold>Strength" with lore "Grants Strength 2 while equipped."
			set slot 10 of the player's current inventory to 1 diamond leggings named "<cyan><bold>Resistance" with lore "Grants Resistance 2 while equipped."
			set slot 11 of the player's current inventory to 1 diamond chestplate named "<cyan><bold>HP Up" with lore "Grants +10 HP while equipped."
			set slot 12 of the player's current inventory to 1 diamond chestplate named "<cyan><bold>STR Up" with lore "Grants +10 STR while equipped."
			set slot 13 of the player's current inventory to 1 diamond chestplate named "<cyan><bold>DEF Up" with lore "Grants +10 DEF while equipped."
			set slot 14 of the player's current inventory to 1 diamond chestplate named "<cyan><bold>SKL Up" with lore "Grants +20 SKL while equipped."
			set slot 15 of the player's current inventory to 1 diamond chestplate named "<cyan><bold>SPD Up" with lore "Grants +10 SPD while equipped."
			set slot 16 of the player's current inventory to 1 diamond chestplate named "<cyan><bold>MAG Up" with lore "Grants +10 MAG while equipped."
			#set slot 17 of the player's current inventory to 1 diamond helmet named "<cyan><bold>Burning Flames" with lore "Spawns flame particles around your helmet."
			#set slot 18 of the player's current inventory to 1 diamond helmet named "<cyan><bold>Holy Stars" with lore "Spawns sparkles and stars around your helmet."
			#set slot 19 of the player's current inventory to 1 diamond helmet named "<cyan><bold>Cloudy Skies" with lore "Spawns clouds around your helmet."
			set slot 17 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is "Inherit":
			open chest with 1 row named "<purple><Bold>Skills Menu | Inherit Skills" for the player
			set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
			set slot 2 of the player's current inventory to 1 book named "<purple><bold>Inheritee ->"
			set slot 4 of the player's current inventory to 1 magenta glazed terracotta named "<purple><bold>Passes down skills and enchantments to..."
			set slot 6 of the player's current inventory to 1 book named "<purple><bold><- Inheritor"
			set slot 8 of the player's current inventory to 1 green stained glass named "<purple><bold>Confirm Inheritance"
		else if arg 1 is "Refine":
			open chest with 1 row named "<green><bold>Skills Menu | Weapon Refinery" for the player
			set slot 0 of the player's current inventory to 1 iron sword named "<green><bold>Slaying" with lore "Adds +10%% chance to C-Slot activations."
			set slot 1 of the player's current inventory to 1 iron sword named "<green><bold>Reinforced" with lore "Increases damage dealt by 1.5 hearts."
			set slot 2 of the player's current inventory to 1 iron sword named "<green><bold>Warding" with lore "Reduces damage suffered by 1.5 hearts."
			set slot 3 of the player's current inventory to 1 iron sword named "<green><bold>Piercing" with lore "Attacks pierce all resistances.", "Includes invincibility."
			set slot 4 of the player's current inventory to 1 iron sword named "<green><bold>Koenig" with lore "If C-Slot activation deals damage:", "Increases damage dealt by 2.5 hearts."
			set slot 5 of the player's current inventory to 1 iron sword named "<green><bold>Crushing" with lore "If damage dealt > 7:", "Increases C-Slot activation chance by 33%% of damage dealt.", "Stacks, and is lost on C-Slot activation."
			set slot 6 of the player's current inventory to 1 iron sword named "<green><bold>Stylish" with lore "If combo system is enabled:", "Increases combo rating for this weapon."
			set slot 7 of the player's current inventory to 1 diamond sword named "<green><bold>Unique" with lore "Apply a unique refine to a Holy Weapon."
			set slot 8 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is "HW":
			open chest with 4 rows named "<gold><bold>Skills Menu | Holy Weapons" for the player
			set slot 0 of the player's current inventory to 1 diamond sword named "<gold><bold>Falchion" with lore "Effective against end-type monsters.", "Can deal random critical damage.", "Right-click to restore health.", "<bold>Unique Refine:", "Grants Strength/Swiftness/Resistance 1 to nearby party members.", "<light red>Requires the Lord's Blood perk."
			set slot 1 of the player's current inventory to 1 diamond sword named "<gold><bold>Binding Blade" with lore "Effective against end-type monsters.", "+4 weapon might.", "Right-click to restore health.", "<bold>Unique Refine:", "<bold>Grants Resistance 2 while equipped.", "<bold>Grants Riposte.", "<bold>Riposte counters ignite foes.", "<light red>Requires the Lord's Blood perk."
			set slot 2 of the player's current inventory to 1 diamond sword named "<gold><bold>Tyrfing" with lore "+4 weapon might.", "Reduces ranged damage suffered by 75%%.", "Grants Miracle while equipped.", "<bold>Unique Refine:", "<bold>Grants STR/DEF +40 while within 10 blocks of a party member."
			set slot 3 of the player's current inventory to 1 diamond sword named "<gold><bold>Ragnell" with lore "+6 weapon might.", "Grants Radiant Aether, a more likely to activate version of Aether.", "<bold>Unique Refine:", "<bold>+4 weapon might.", "<bold>Right-click to fire damaging shockwaves."
			set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Light Brand" with lore "Grants SKL +20 while equipped.", "Right-click to strike lightning at nearby monsters.", "Grants bonus damage = MAG / 8. Max: +7", "<bold>Unique Refine:", "<bold>Transforms the Light Brand into Leif's Blade."
			set slot 5 of the player's current inventory to 1 diamond axe named "<gold><bold>Armads" with lore "+6 weapon might.", "Grants Resistance 2 while equipped.", "<bold>Unique Refine:", "<bold>Automatically retaliate against ranged foes.", "<bold>Automatically make a follow-up attack when attacked."
			set slot 6 of the player's current inventory to 1 bow named "<gold><bold>Parthia" with lore "Reduces ranged damage suffered by 75%%.", "+2 weapon might.", "Grants Experience Sapper.", "<bold>Unique Refine:", "<bold>+6 weapon might against ranged opponents.", "<bold>Inflicts Weakness 2 to foes on-hit."
			set slot 7 of the player's current inventory to 1 iron horse armour named "<gold><bold>Super Shotgun" with lore "The double-barreled classic. Plenty of risk & plenty of reward.", "Right-click to fire.", "Left-click to reload. Costs 6 gold nuggets.", "<bold>Skills cannot be equipped on this weapon.", "<bold>This weapon cannot be refined."
			set slot 8 of the player's current inventory to 1 diamond shovel named "<gold><bold>Siegmund" with lore "+5 weapon might.", "Grants Rally Strength.", "Effective against monsters.", "<bold>Unique Refine:", "<bold>If there are more enemies than allies within 10 blocks of you:", "<bold>Automatically make a follow-up attack, and grants Strength 2.", "<light red>Requires the Lord's Blood perk."
			set slot 9 of the player's current inventory to 1 diamond sword named "<gold><bold>Sieglinde" with lore "+5 weapon might.", "Grants Rally Strength.", "Effective against monsters.", "<bold>Unique Refine:", "<bold>Rallies also apply to yourself.", "<bold>Rally skills apply in a 7-block radius.", "<light red>Requires the Lord's Blood perk."
			set slot 10 of the player's current inventory to 1 diamond sword named "<gold><bold>Durandal" with lore "+2 weapon might.", "Effective against end-type monsters.", "Imbued with the Crushing refine effect.", "<bold>Unique Refine:", "<bold>Grants Death Blow and Darting Blow."
			set slot 11 of the player's current inventory to 1 diamond shovel named "<gold><bold>Gae Bolg" with lore "Grants STR/DEF/SKL +30 while equipped.", "Grants the Guard and Vantage perks while equipped.", "Player is treated as though they are not in a party.", "<bold>Unique refine:", "<bold>Inflicts weakness 2 to foes within 10 blocks.", "<bold>Increases damage dealt by 25%%.", "<light red>Requires the Crusader's Blood perk."
			set slot 12 of the player's current inventory to 1 diamond sword named "<gold><bold>Mercurius" with lore "+3 weapon might.", "Grants Experience Sapper."
			set slot 13 of the player's current inventory to 1 diamond axe named "<gold><bold>Basilikos" with lore "+5 weapon might."
			set slot 14 of the player's current inventory to 1 diamond axe named "<gold><bold>Hauteclere" with lore "+2 weapon might.", "Grants SKL +15 while equipped."
			set slot 15 of the player's current inventory to 1 diamond sword named "<gold><bold>Mystletainn" with lore "+4 weapon might.", "Grants SKL +40 while equipped.", "If HP < 75%%, grants SKL +30. stacks with Wrath.", "<bold>Unique refine:", "<bold>Transforms the Mystletainn into the Dark Mystletainn.", "<light red>Requires the Crusader's Blood perk."
			set slot 16 of the player's current inventory to 1 diamond shovel named "<gold><bold>Fensalir" with lore "+4 weapon might.", "While within 10 blocks of a party member, grants +6 weapon might.", "<bold>Unique Refine:", "<bold>While within 10 blocks of a party member, grants STR/SKL +30.", "<light red>Requires the Lord's Blood perk."
			set slot 17 of the player's current inventory to 1 diamond sword named "<gold><bold>Folkvangr" with lore "+4 weapon might.", "While within 10 blocks of a party member, grants +6 weapon might.", "<bold>Unique Refine:", "<bold>If HP < 70%%, grants STR/DEF +40.", "<light red>Requires the Lord's Blood perk."
			set slot 18 of the player's current inventory to 1 diamond shovel named "<gold><bold>Gradivus" with lore "+4 weapon might.", "Grants Experience Sapper."
			set slot 19 of the player's current inventory to 1 diamond horse armour named "<gold><bold>Love is Blue" with lore "Right-click to fire bullets at the cost of EXP.", "Melee hits restore 5 EXP.", "<bold>Skills cannot be equipped to this weapon.", "<bold>This weapon cannot be refined."
			set slot 20 of the player's current inventory to 1 gold horse armour named "<gold><bold>Scarborough Fair" with lore "Right-click to fire bullets at the cost of EXP.", "Melee hits restore 5 EXP.", "<bold>Skills cannot be equipped to this weapon.", "<bold>This weapon cannot be refined."
			set slot 21 of the player's current inventory to 1 diamond sword named "<gold><bold>Balder Side Sword" with lore "+2 weapon might.", "Right-click to parry attacks.", "Parry has a 0.5 second cooldown."
			set slot 22 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is "Repair":
			open chest with 1 row named "<white><bold>Skills Menu | Repair Tools" for the player
			set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
			set slot 3 of the player's current inventory to 1 book named "<bold>Place item here -->"
			set slot 5 of the player's current inventory to 1 book named "<bold><-- Place item here"
			set slot 8 of the player's current inventory to 1 green glass pane named "<green><bold>Repair Tool"
		else if arg 1 is "Merge":
			open chest with 1 row named "<gray><bold>Skills Menu | Merge Tools" for the player
			set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
			set slot 2 of the player's current inventory to 1 book named "<gray><bold>Item recieving merges ->"
			set slot 4 of the player's current inventory to 1 magenta glazed terracotta named "<gray><bold>Gains bonus stats from..."
			set slot 6 of the player's current inventory to 1 book named "<gray><bold><- Item being merged (item will be lost)"
			set slot 8 of the player's current inventory to 1 green stained glass named "<gray><bold>Merge Tools"
		else if arg 1 is "Buy":
			open chest with 1 row named "<gold><bold>Skills Menu | Shopping Cart" for the player
			set slot 3 of the player's current inventory to 1 magenta glazed terracotta named "<gold><bold>Item to apply this skill to ->"
			set slot 5 of the player's current inventory to 1 magenta glazed terracotta named "<gold><bold><- Item to apply this skill to"
			set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
			set slot 1 of the player's current inventory to 1 book named "<gold><bold>Skill Info"
			set slot 8 of the player's current inventory to 1 green glass pane named "<green><bold>Purchase Skill"
			set {shoppingcart.%player%} to arg 2
			set {menulayer.%player%} to arg 3
		else if arg 1 is "hw2":
			open chest with 1 row named "<gold><bold>Holy Weapons | Inspection" for the player
			set slot 8 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
			set slot 0 of the player's current inventory to 1 anvil named "<gold><bold>Refine"
			set slot 3 of the player's current inventory to 1 emerald named "<gold><bold>Purchase Weapon"
			set slot 4 of the player's current inventory to 1 cobblestone named "<gold><bold>%arg 2%"
			set slot 5 of the player's current inventory to 1 nether star named "<gold><bold>Warp to Heroic Challenge"
			
on inventory click:
	if the name of the player's current inventory is "<gold><bold>Skills Menu":
		if the name of the clicked item is "<light red><bold>A-Slot Skills":
			make player execute command "/skills A-Skills"
			cancel event
		else if the name of the clicked item is "<light blue><bold>B-Slot Skills":
			make player execute command "/skills B-Skills"
			cancel event
		else if the name of the clicked item is "<yellow><bold>C-Slot Skills":
			make player execute command "/skills C-Skills"
			cancel event
		else if the name of the clicked item is "<light purple><bold>Special Skills":
			make player execute command "/skills Specials"
			cancel event
		else if the name of the clicked item is "<light green><bold>Assist Skills":
			make player execute command "/skills Assists"
			cancel event
		else if the name of the clicked item is "<cyan><bold>Armour Skills":
			make player execute command "/skills Armour"
			cancel event
		else if the name of the clicked item is "<purple><bold>Inherit Skills":
			make player execute command "/skills Inherit"
			cancel event
		else if the name of the clicked item is "<green><bold>Weapon Refinery":
			make player execute command "/skills Refine"
			cancel event
		else if the name of the clicked item is "<gray><bold>Upgrade/Merge Tools":
			make player execute command "/skills Merge"
			cancel event
		else if the name of the clicked item is "<gold><bold>Holy Weapons":
			make player execute command "/skills HW"
			cancel event
		else if the name of the clicked item is "<white><bold>Repair Tools":
			make player execute command "/skills Repair"
			cancel event
		else if the name of the clicked item is "<bold>Go Back":
			make player execute command "/store"
			cancel event
	else if the name of the player's current inventory is "<light red><bold>Skills Menu | A-Slot Skills":
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/skills"
			cancel event
		else if the name of the clicked item contains "<light red><bold>":
			set {_skillarg} to uncoloured name of the clicked item
			remove "<light red><bold>" from {_skillarg}
			if {SkillsHelpDisplay.%player%} is not true:
				make player execute command "/skills buy %{_skillarg}% 1"
			else:
				make player execute command "/skills info %{_skillarg}%"
			cancel event
	else if the name of the player's current inventory is "<light blue><bold>Skills Menu | B-Slot Skills":
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/skills"
			cancel event
		else if the name of the clicked item contains "<light blue><bold>":
			set {_skillarg} to uncoloured name of the clicked item
			remove "<light blue><bold>" from {_skillarg}
			if {SkillsHelpDisplay.%player%} is not true:
				make player execute command "/skills buy %{_skillarg}% 2"
			else:
				make player execute command "/skills info %{_skillarg}%"
			cancel event
	else if the name of the player's current inventory is "<yellow><bold>Skills Menu | C-Slot Skills":
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/skills"
			cancel event
		else if the name of the clicked item contains "<yellow><bold>":
			set {_skillarg} to uncoloured name of the clicked item
			remove "<yellow><bold>" from {_skillarg}
			if {SkillsHelpDisplay.%player%} is not true:
				make player execute command "/skills buy %{_skillarg}% 3"
			else:
				make player execute command "/skills info %{_skillarg}%"
			cancel event
	else if the name of the player's current inventory is "<cyan><bold>Skills Menu | Armour Skills":
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/skills"
			cancel event
		else if the name of the clicked item contains "<cyan><bold>":
			set {_skillarg} to uncoloured name of the clicked item
			remove "<cyan><bold>" from {_skillarg}
			if {SkillHelpDisplay.%player%} is not true:
				make player execute command "/skills buy %{_skillarg}% 4"
			else:
				make player execute command "/skills info %{_skillarg}%"
			cancel event
	else if the name of the player's current inventory is "<gold><bold>Skills Menu | Holy Weapons":
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/skills"
			cancel event
		else if the name of the clicked item contains "<gold><bold>":
			set {_weapon} to uncoloured name of the clicked item
			remove "<gold><bold>" from {_weapon}
			make player execute command "/skills hw2 %{_weapon}%"
			cancel event
	else if the name of the player's current inventory is "<gold><bold>Holy Weapons | Inspection":
		if the name of the clicked item is "<gold><bold>Purchase Weapon":
			set {_weapon} to uncoloured name of slot 4 of the player's current inventory
			remove "<gold><bold>" from {_weapon}
			if {_weapon} is "Basilikos":
				set {_price} to 750
			else if {_weapon} is "Mercurius":
				set {_price} to 750
			else if {_weapon} is "Hauteclere":
				set {_price} to 750
			else if {_weapon} is "Gradivus":
				set {_price} to 750
			else if {_weapon} is "Super Shotgun":
				set {_price} to 750
			else:
				set {_price} to 1000
			if the player's money is less than {_price}:
				send "<red><bold>You lack the required funds to purchase this Holy Weapon. You need %{_price}%, but only have %player's money%."
			else:
				#Things other than swords
				if {_weapon} is "Basilikos":
					set slot 4 of the player's current inventory to 1 diamond axe named "<gold><bold>Basilikos"
				else if {_weapon} is "Hauteclere":
					set slot 4 of the player's current inventory to 1 diamond axe named "<gold><bold>Hauteclere"
				else if {_weapon} is "Gradivus":
					set slot 4 of the player's current inventory to 1 diamond shovel named "<gold><bold>Gradivus"
				else if {_weapon} is "Super Shotgun":
					set slot 4 of the player's current inventory to 1 iron horse armour named "<red><bold>Super Shotgun | Clip: 2/2" with lore "<red>Left-Click to reload. Costs 6 gold nuggets per barrel. ", " <red>Right-Click to fire. Shots are less accurate at range."
				else if {_weapon} is "Fensalir":
					set slot 4 of the player's current inventory to 1 diamond shovel named "<gold><bold>Fensalir"
				else if {_weapon} is "Parthia":
					set slot 4 of the player's current inventory to 1 bow named "<gold><bold>Parthia"
				else if {_weapon} is "Siegmund":
					set slot 4 of the player's current inventory to 1 diamond shovel named "<gold><bold>Siegmund"
				else if {_weapon} is "Scarborough Fair":
					set slot 4 of the player's current inventory to 1 gold horse armor named "<light red><bold>Scarborough Fair"
				else if {_weapon} is "Love is Blue":
					set slot 4 of the player's current inventory to 1 diamond horse armor named "<light blue><bold>Love is Blue"
				else if {_weapon} is "Axtinguisher":
					set slot 4 of the player's current inventory to 1 diamond axe named "<gold><bold>Axtinguisher"
				else if {_weapon} is "Armads":
					set slot 4 of the player's current inventory to 1 diamond axe named "<gold><bold>Armads"
				else if {_weapon} is "Gae Bolg":
					set slot 4 of the player's current inventory to 1 diamond shovel named "<gold><bold>Gae Bolg"
				else:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>%{_weapon}%"
				subtract {_price} from the player's money
				send "<green><bold>Holy Weapon purchased! Current Funds: %player's money%."
			cancel event
		else if the name of the clicked item is "<bold>Go Back":
			make player execute command "/skills HW"
			cancel event
		else if the name of the clicked item is "<gold><bold>Refine":
			make player execute command "/skills refine"
			cancel event
		else if the name of the clicked item is "<gold><bold>Warp to Heroic Challenge":
			set {_name} to the name of slot 4 of the player's current inventory
			if {_name} is "<gold><bold>Falchion":
				make player execute command "/warp qp_h2"
			else if {_name} is "<gold><bold>Binding Blade":
				make player execute command "/warp qp_h1"
			else if {_name} is "<gold><bold>Mystletainn":
				make player execute command "/warp qp_h3"
			cancel event
		else if the clicked item is cobblestone:
			cancel event
	else if the name of the player's current inventory is "<purple><bold>Skills Menu | Inherit Skills":
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/skills"
			cancel event
		else:
			if the name of the clicked item is "<purple><bold>Confirm Inheritance":
				if slot 3 of the player's current inventory is not empty:
					if slot 5 of the player's current inventory is not empty:
						set {_inheritanceA-Skill} to line 1 of slot 3 of the player's current inventory's lore
						set {_inheritanceB-Skill} to line 2 of slot 3 of the player's current inventory's lore
						set {_inheritanceC-Skill} to line 3 of slot 3 of the player's current inventory's lore
						set {_inheritanceRefine} to line 4 of slot 3 of the player's current inventory's lore
						#send "%{_inheritance:A-Skill}%"
						set line 1 of slot 5 of the player's current inventory's lore to {_inheritanceA-Skill}
						set line 2 of slot 5 of the player's current inventory's lore to {_inheritanceB-Skill}
						set line 3 of slot 5 of the player's current inventory's lore to {_inheritanceC-Skill}
						set line 4 of slot 5 of the player's current inventory's lore to {_inheritanceRefine}
						set slot 3 of the player's current inventory to air
			if the name of the clicked item contains "<purple><bold>":
				cancel event
	else if the name of the player's current inventory is "<gray><bold>Skills Menu | Merge Tools":
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/skills"
			cancel event
		else:
			if the name of the clicked item contains "<gray><bold>":
				cancel event
			if the name of the clicked item is "<gray><bold>Merge Tools":
				if slot 3 of the player's current inventory is not air:	
					set {_name} to the name of slot 3 of the player's current inventory
					set {_workaround} to slot 3 of the player's current inventory
					set the name of slot 3 of the player's current inventory to "%{_workaround}%"
					if the name of slot 3 of the player's current inventory contains "Diamond":
						set {_tooltype} to "Diamond"
					else if the name of slot 3 of the player's current inventory contains "Gold":
						set {_tooltype} to "Gold"
					else if the name of slot 3 of the player's current inventory contains "Iron":
						set {_tooltype} to "Iron"
					else if the name of slot 3 of the player's current inventory contains "Quartz":
						set {_tooltype} to "Quartz"
					else:
						set {_tooltype} to "Reinforced"
					if slot 3 of the player's current inventory is a sword:
						set {_tool} to "Sword"
					else if slot 3 of the player's current inventory is a pickaxe:
						set {_tool} to "Pickaxe"
					else if slot 3 of the player's current inventory is a shovel:
						set {_tool} to "Shovel"
					else if slot 3 of the player's current inventory is an axe:
						set {_tool} to "Axe"
					else if slot 3 of the player's current inventory is a helmet:
						set {_tool} to "Helmet"
						set {_toolB} to true
					else if slot 3 of the player's current inventory is a chestplate:
						set {_tool} to "Chestplate"
						set {_toolB} to true
					else if slot 3 of the player's current inventory is a leggings:
						set {_tool} to "Leggings"
						set {_toolB} to true
					else if slot 3 of the player's current inventory is boots:
						set {_tool} to "Boots"
						set {_toolB} to true
					else if slot 3 of the player's current inventory is a fishing rod:
						set {_tool} to "Fishing Rod"
					else if slot 3 of the player's current inventory is a bow:
						set {_tool} to "Bow"
					#send "%{_tooltype}% %{_tool}% %{_toolB}%"
					if the name of slot 5 of the player's current inventory contains "<light blue>%{_tooltype}% %{_tool}% Frame":
						set slot 5 of the player's current inventory to air
						if {_tool} is "Fishing Rod":
							set {_test} to (the level of unbreaking of slot 3 of the player's current inventory + 1)
							enchant slot 3 of the player's current inventory with "unbreaking %{_test}%" parsed as enchantment type
							set {_test} to (the level of luck of the sea of slot 3 of the player's current inventory + 1)
							enchant slot 3 of the player's current inventory with "luck of the sea %{_test}%" parsed as enchantment type
							set {_test} to (the level of lure of slot 3 of the player's current inventory + 1)
							enchant slot 3 of the player's current inventory with "lure %{_test}%" parsed as enchantment type
						else if {_toolB} is true:
							if level of protection of slot 3 of the player's current inventory is less than 10:
								set {_test} to (the level of protection of slot 3 of the player's current inventory + 1)
								enchant slot 3 of the player's current inventory with "protection %{_test}%" parsed as enchantment type
							if level of fire protection of slot 3 of the player's current inventory is less than 10:
								set {_test} to (the level of fire protection of slot 3 of the player's current inventory + 1)
								enchant slot 3 of the player's current inventory with "fire protection %{_test}%" parsed as enchantment type
							if level of blast protection of slot 3 of the player's current inventory is less than 10:
								set {_test} to (the level of blast protection of slot 3 of the player's current inventory + 1)
								enchant slot 3 of the player's current inventory with "blast protection %{_test}%" parsed as enchantment type
							if {_tool} is "Helmet":
								enchant slot 3 of the player's current inventory with aqua affinity 1
								set {_test} to (the level of respiration of slot 3 of the player's current inventory + 1)
								enchant slot 3 of the player's current inventory with "respiration %{_test}%" parsed as enchantment type
							else if {_tool} is "Boots":
								set {_test} to (the level of depth strider of slot 3 of the player's current inventory + 1)
								enchant slot 3 of the player's current inventory with "depth strider %{_test}%" parsed as enchantment type
						else if {_tool} is "Bow":
							set {_test} to (the level of unbreaking of slot 3 of the player's current inventory + 1)
							enchant slot 3 of the player's current inventory with "Unbreaking %{_test}%" parsed as enchantment type
							set {_test} to (the level of power of slot 3 of the player's current inventory + 1)
							enchant slot 3 of the player's current inventory with "power %{_test}%" parsed as enchantment type
							if level of punch of slot 3 of the player's current inventory is less than 3:
								set {_test} to (the level of punch of slot 3 of the player's current inventory + 1)
								enchant slot 3 of the player's current inventory with "punch %{_test}%" parsed as enchantment type
						else if {_tool} is not "Sword":
							set {_test} to (the level of efficiency of slot 3 of the player's current inventory + 1)
							enchant slot 3 of the player's current inventory with "efficiency %{_test}%" parsed as enchantment type
							set {_test} to (the level of unbreaking of slot 3 of the player's current inventory + 1)
							enchant slot 3 of the player's current inventory with "unbreaking %{_test}%" parsed as enchantment type
							set {_test} to (the level of sharpness of slot 3 of the player's current inventory + 1)
							enchant slot 3 of the player's current inventory with "sharpness %{_test}%" parsed as enchantment type
							if level of fortune of slot 3 of the player's current inventory is not more than 5:
								set {_test} to (the level of fortune of slot 3 of the player's current inventory + 1)
								enchant slot 3 of the player's current inventory with "fortune %{_test}%" parsed as enchantment type
						else:
							set {_test} to (the level of sharpness of slot 3 of the player's current inventory + 1)
							enchant slot 3 of the player's current inventory with "Sharpness %{_test}%" parsed as enchantment type
							set {_test} to (the level of unbreaking of slot 3 of the player's current inventory + 1)
							enchant slot 3 of the player's current inventory with "Unbreaking %{_test}%" parsed as enchantment type
							set {_test} to (the level of looting of slot 3 of the player's current inventory + 1)
							enchant slot 3 of the player's current inventory with "looting %{_test}%" parsed as enchantment type
						set the name of slot 3 of the player's current inventory to "%{_name}%"
				cancel event
	else if the name of the player's current inventory is "<green><bold>Skills Menu | Weapon Refinery":
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/skills"
			cancel event
		else if the name of the clicked item contains "<green><bold>":
			set {_skillarg} to uncoloured name of the clicked item
			remove "<green><bold>" from {_skillarg}
			make player execute command "/skills buy %{_skillarg}% 5"
			cancel event
	else if the name of the player's current inventory is "<white><bold>Skills Menu | Repair Tools":
		if the name of the clicked item is "<green><bold>Repair Tool":
			set {_cashreq} to the damage value of slot 4 of the player's current inventory
			if line 3 of slot 4 of the player's current inventory's lore contains "Mercurius":
				set {_cashreq} to 500
				set {_merc} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Tyrfing":
				set {_cashreq} to 750
				set {_tyr} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Binding Blade":
				set {_cashreq} to 750
				set {_bind} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Falchion":
				set {_cashreq} to 750
				set {_falc} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Ragnell":
				set {_cashreq} to 750
				set {_ragn} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Armads":
				set {_cashreq} to 750
				set {_arma} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Parthia":
				set {_cashreq} to 750
				set {_part} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Light Brand":
				set {_cashreq} to 500
				set {_ligh} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Leif's Blade":
				set {_cashreq} to 750
				set {_leif} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Siegmund":
				set {_cashreq} to 750
				set {_siegm} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Sieglinde":
				set {_cashreq} to 750
				set {_siegl} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Durandal":
				set {_cashreq} to 500
				set {_dura} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Blazing Durandal":
				set {_cashreq} to 750
				set {_bdur} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Gae Bolg":
				set {_cashreq} to 750
				set {_gaeb} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Gradivus":
				set {_cashreq} to 500
				set {_grad} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Hauteclere":
				set {_cashreq} to 500
				set {_haut} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Folkvangr":
				set {_cashreq} to 750
				set {_folk} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Fensalir":
				set {_cashreq} to 750
				set {_fens} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Basilikos":
				set {_cashreq} to 500
				set {_basi} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Mystletainn":
				set {_cashreq} to 750
				set {_myst} to 1
			else if line 3 of slot 4 of the player's current inventory's lore contains "Dark Mystletainn":
				set {_cashreq} to 750
				set {_dmys} to 1
			if {_cashreq} is less than the player's money:
				if {_merc} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Mercurius"
				else if {_tyr} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Tyrfing"
				else if {_bind} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Binding Blade"
				else if {_falc} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Falchion"
				else if {_ragn} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Ragnell"
				else if {_arma} is 1:
					set slot 4 of the player's current inventory to 1 diamond axe named "<gold><bold>Armads"
				else if {_part} is 1:
					set slot 4 of the player's current inventory to 1 bow named "<gold><bold>Parthia"
				else if {_ligh} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Light Brand"
				else if {_leif} is 1:
					set slot 4 of the player's current inventory to 1 gold sword named "<gold><bold>Leif's Blade"
				else if {_siegm} is 1:
					set slot 4 of the player's current inventory to 1 diamond shovel named "<gold><bold>Siegmund"
				else if {_siegl} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Sieglinde"
				else if {_dura} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Durandal"
				else if {_bdur} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Blazing Durandal"
				else if {_gaeb} is 1:
					set slot 4 of the player's current inventory to 1 diamond shovel named "<gold><bold>Gae Bolg"
				else if {_grad} is 1:
					set slot 4 of the player's current inventory to 1 diamond shovel named "<gold><bold>Gradivus"
				else if {_haut} is 1:
					set slot 4 of the player's current inventory to 1 diamond axe named "<gold><bold>Hauteclere"
				else if {_folk} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Folkvangr"
				else if {_fens} is 1:
					set slot 4 of the player's current inventory to 1 diamond shovel named "<gold><bold>Fensalir"
				else if {_basi} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Basilikos"
				else if {_myst} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Mystletainn"
				else if {_dmys} is 1:
					set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Dark Mystletainn"
				else:
					repair slot 4 of the player's current inventory
				set the player's money to (player's money - {_cashreq})
				send "<light green>Transaction complete. New balance: $%player's money%."
				cancel event
			else:
				send "<light red>Not enough money!"
			cancel event
		else if the name of the clicked item is "<bold>Go Back":
			make player execute command "/skills"
			cancel event
	else if the name of the player's current inventory is "<gold><bold>Skills Menu | Shopping Cart":
		if the name of the clicked item is "<bold>Go Back":
			if slot 4 of the player's current inventory is air:
				if {menulayer.%player%} is 1:
					make player execute command "/skills A-Skills"
				else if {menulayer.%player%} is 2:
					make player execute command "/skills B-Skills"
				else if {menulayer.%player%} is 3:
					make player execute command "/skills C-Skills"
				else if {menulayer.%player%} is 4:
					make player execute command "/skills Armour"
				else if {menulayer.%player%} is 5:
					make player execute command "/skills Refine"
			else:
				cancel event
				send "<red>Remove your tool from the purchase window before exiting!"
		else if the name of the clicked item is "<green><bold>Purchase Skill":
			if {menulayer.%player%} is 5:
				make player execute command "/refine %{shoppingcart.%player%}%"
			else:
				send "%{shoppingcart.%player%}%"
				make player execute command "/skill %{shoppingcart.%player%}%"
			cancel event
		else if the name of the clicked item is "<gold><bold>Skill Info":
			make player execute command "/skillhelp %{shoppingcart.%player%}% 1"
			cancel event
		else if the name of the clicked item contains "<gold><bold>Item to apply this skill to ->":
			cancel event
		else if the name of the clicked item contains "<gold><bold><- Item to apply this skill to":
			cancel event
			

command /skill <text> [<number=0>]:
	description: Helper Function for /skills
	usage: /skill (skill)
	executable by: players
	trigger:
		set {_cash} to player's money
		if arg 2 is 0:
			if arg 1 contains "Distant Counter":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Distant Counter"
					remove 200 from the player's balance
			else if arg 1 contains "Close Counter":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Close Counter"
					remove 200 from the player's balance
			else if arg 1 contains "Quick Draw":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Quick Draw"
					remove 200 from the player's balance
			else if arg 1 contains "Warp Strike":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Warp Strike"
					remove 150 from the player's balance
			else if arg 1 contains "Skill Breaker":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Skill Breaker"
					remove 150 from the player's balance
			else if arg 1 contains "Armour Smasher":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Armour Smasher"
					remove 150 from the player's balance
			else if arg 1 contains "Sorcery Aura":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Sorcery Aura"
					remove 150 from the player's balance
			else if arg 1 contains "Drag Back":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Drag Back"
					remove 150 from the player's balance
			else if arg 1 contains "Hit and Run":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Hit and Run"
					remove 150 from the player's balance
			else if arg 1 contains "Ardent Sacrifice":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Ardent Sacrifice"
					remove 150 from the player's balance
			else if arg 1 contains "Restore":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Restore"
					remove 150 from the player's balance
			else if arg 1 contains "Wrath":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Wrath"
					remove 200 from the player's balance
			else if arg 1 contains "Stomp":
				if {_cash} is less than 100:
					send "<red><bold>You lack the required funds to purchase this skill. You need $100, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Stomp"
					remove 100 from the player's balance
			else if arg 1 contains "Reposition":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Reposition"
					remove 150 from the player's balance
			else if arg 1 contains "Swap":
				if {_cash} is less than 100:
					send "<red><bold>You lack the required funds to purchase this skill. You need $100, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Swap"
					remove 100 from the player's balance
			else if arg 1 contains "Rally Speed":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Rally Speed"
					remove 200 from the player's balance
			else if arg 1 contains "Rally Strength":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Rally Strength"
					remove 200 from the player's balance
			else if arg 1 contains "Rally Resistance":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Rally Resistance"
					remove 200 from the player's balance
			else if arg 1 contains "Rally Spectrum":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Rally Spectrum"
					remove 200 from the player's balance
			else if arg 1 contains "Shove":
				if {_cash} is less than 100:
					send "<red><bold>You lack the required funds to purchase this skill. You need $100, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Shove"
					remove 100 from the player's balance
			else if arg 1 contains "Launcher":
				if {_cash} is less than 100:
					send "<red><bold>You lack the required funds to purchase this skill. You need $100, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Launcher"
					remove 100 from the player's balance
			else if arg 1 contains "Experience Sapper":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Experience Sapper"
					remove 150 from the player's balance
			else if arg 1 contains "Plentitude":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Plentitude"
					remove 150 from the player's balance
			else if arg 1 contains "Despoil":
				if {_cash} is less than 250:
					send "<red><bold>You lack the required funds to purchase this skill. You need $250, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Despoil"
					remove 250 from the player's balance
			else if arg 1 contains "Moonbow":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Moonbow"
					remove 150 from the player's balance
			else if arg 1 contains "Luna":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Luna"
					remove 150 from the player's balance
			else if arg 1 contains "Glimmer":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Glimmer"
					remove 150 from the player's balance
			else if arg 1 contains "Astra":
				if {_cash} is less than 250:
					send "<red><bold>You lack the required funds to purchase this skill. You need $250, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Astra"
					remove 250 from the player's balance
			else if arg 1 contains "Blazing Light":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Blazing Light"
					remove 200 from the player's balance
			else if arg 1 contains "Growing Light":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Growing Light"
					remove 200 from the player's balance
			else if arg 1 contains "Glacies":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Glacies"
					remove 150 from the player's balance
			else if arg 1 contains "Ignis":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Ignis"
					remove 150 from the player's balance
			else if arg 1 contains "Rising Wind":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Rising Wind"
					remove 150 from the player's balance
			else if arg 1 contains "Dragon Fang":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Dragon Fang"
					remove 150 from the player's balance
			else if arg 1 contains "Miracle":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Miracle"
					remove 200 from the player's balance
			else if arg 1 contains "Galeforce":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Galeforce"
					remove 200 from the player's balance
			else if arg 1 is "Sol":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Sol"
					remove 150 from the player's balance
			else if arg 1 contains "Retribution":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Retribution"
					remove 150 from the player's balance
			else if arg 1 contains "Pavise":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Pavise"
					remove 150 from the player's balance
			else if arg 1 contains "Aegis":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Aegis"
					remove 150 from the player's balance
			else if arg 1 contains "Aether":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 3 of slot 4 of the player's current inventory's lore to "Special - Aether"
					remove 200 from the player's balance
			else if arg 1 contains "Long Jump":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Long Jump"
					remove 150 from the player's balance
			else if arg 1 contains "Quick Stomp":
				if {_cash} is less than 100:
					send "<red><bold>You lack the required funds to purchase this skill. You need $100, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Quick Stomp"
					remove 100 from the player's balance
			else if arg 1 contains "TriangleAdept":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Triangle Adept"
					remove 200 from the player's balance
			else if arg 1 contains "Wings of Mercy":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Wings of Mercy"
					remove 200 from the player's balance
			else if arg 1 contains "Escape Route":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Escape Route"
					remove 200 from the player's balance
			else if arg 1 contains "Triangle Breaker":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Triangle Breaker"
					remove 200 from the player's balance
			else if arg 1 contains "Boost Jump":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Boost Jump"
					remove 150 from the player's balance
			else if arg 1 contains "Quickened Pulse":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Quickened Pulse"
					remove 200 from the player's balance
			else if arg 1 contains "Witch Time":
				if {_cash} is less than 150:
					set {_cash} to {_cash} * 100
					send "<red><bold>You lack the required funds to purchase this skill. You need 20000 Halos, but you only have {_cash} Halos."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Witch Time"
					remove 200 from the player's balance
			else if arg 1 contains "Hover":
				if {_cash} is less than 350:
					set {_cash} to {_cash} * 100
					send "<red><bold>You lack the required funds to purchase this skill. You need $350, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Hover"
					remove 200 from the player's balance
			else if arg 1 contains "Glory Kill":
				if {_cash} is less than 150:
					send "<red><bold>NOT ENOUGH BLOOD! RIP AND TEAR UNTIL IT IS DONE! (You need $150 for this skill.)"
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Glory Kills"
					remove 150 from the player's balance
					send "<red><bold>They are rage; brutal... without mercy. But you..."
					wait 3 seconds
					send "<red><bold>You will be worse."
					wait 3 seconds
					send "<red><bold>Rip and tear until it is done."
					wait 3 seconds
			else if arg 1 contains "Regeneration":
				if slot 4 of the player's current inventory is leggings:
					if {_cash} is less than 150:
						send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
					else:
						set line 1 of slot 4 of the player's current inventory's lore to "Skill: Regeneration"
						remove 150 from the player's balance
						send "Success!" to the player
			else if arg 1 contains "Swiftness":
				if slot 4 of the player's current inventory is leggings:
					if {_cash} is less than 150:
						send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
					else:
						set line 1 of slot 4 of the player's current inventory's lore to "Skill: Swiftness"
						remove 150 from the player's balance
						send "Success!" to the player
			else if arg 1 contains "Strength":
				if slot 4 of the player's current inventory is leggings:
					if {_cash} is less than 150:
						send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
					else:
						set line 1 of slot 4 of the player's current inventory's lore to "Skill: Strength"
						remove 150 from the player's balance
						send "Success!" to the player
			else if arg 1 contains "Resistance":
				if slot 4 of the player's current inventory is leggings:
					if {_cash} is less than 150:
						send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
					else:
						set line 1 of slot 4 of the player's current inventory's lore to "Skill: Resistance"
						remove 150 from the player's balance
						send "Success!" to the player
			else if arg 1 contains "HP Up":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Skill: HP Up"
					remove 200 from the player's balance
			else if arg 1 contains "STR Up":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Skill: STR Up"
					remove 150 from the player's balance
			else if arg 1 contains "SKL Up":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Skill: SKL Up"
					remove 150 from the player's balance
			else if arg 1 contains "SPD Up":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Skill: SPD Up"
					remove 150 from the player's balance
			else if arg 1 contains "MAG Up":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Skill: MAG Up"
					remove 150 from the player's balance
			else if arg 1 contains "DEF Up":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Skill: DEF Up"
					remove 150 from the player's balance
			else if arg 1 contains "Fury":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Fury"
					remove 150 from the player's balance
			else if arg 1 contains "Life and Death":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Life and Death"
					remove 150 from the player's balance
			else if arg 1 contains "Death Blow":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Death Blow"
					remove 150 from the player's balance
			else if arg 1 contains "Darting Blow":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Darting Blow"
					remove 150 from the player's balance
			else if arg 1 contains "Armoured Blow":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Armoured Blow"
					remove 150 from the player's balance
			else if arg 1 contains "Defiant Attack":
				if {_cash} is less than 250:
					send "<red><bold>You lack the required funds to purchase this skill. You need $250, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Defiant Attack"
					remove 250 from the player's balance
			else if arg 1 contains "Defiant Speed":
				if {_cash} is less than 250:
					send "<red><bold>You lack the required funds to purchase this skill. You need $250, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Defiant Speed"
					remove 250 from the player's balance
			else if arg 1 contains "Defiant Resistance":
				if {_cash} is less than 250:
					send "<red><bold>You lack the required funds to purchase this skill. You need $250, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Defiant Resistance"
					remove 250 from the player's balance
			else if arg 1 contains "Seal Attack":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Seal Attack"
					remove 150 from the player's balance
			else if arg 1 contains "Seal Speed":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Seal Speed"
					remove 150 from the player's balance
			else if arg 1 is "Seal Defense":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Seal Defense"
					remove 150 from the player's balance
			else if arg 1 contains "Poison Strike":
				if {_cash} is less than 350:
					send "<red><bold>You lack the required funds to purchase this skill. You need $350, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Poison Strike"
					remove 350 from the player's balance
			else if arg 1 contains "Close Defence":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Close Defence"
					remove 150 from the player's balance
			else if arg 1 contains "Distant Defence":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Distant Defence"
					remove 150 from the player's balance
			else if arg 1 contains "STR/SKL Bond":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - STR/SKL Bond"
					remove 150 from the player's balance
			else if arg 1 contains "DEF/MAG Bond":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - DEF/MAG Bond"
					remove 150 from the player's balance
			else if arg 1 contains "DEF/SKL Bond":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - DEF/SKL Bond"
					remove 150 from the player's balance
			else if arg 1 contains "MAG/SKL Bond":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - MAG/SKL Bond"
					remove 150 from the player's balance
			else if arg 1 contains "STR/DEF Bond":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - STR/DEF Bond"
					remove 150 from the player's balance
			else if arg 1 contains "STR/MAG Solo":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - STR/MAG Solo"
					remove 150 from the player's balance
			else if arg 1 contains "STR/SKL Solo":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - STR/SKL Solo"
					remove 150 from the player's balance
			else if arg 1 contains "DEF/MAG Solo":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - DEF/MAG Solo"
					remove 150 from the player's balance
			else if arg 1 contains "DEF/SKL Solo":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - DEF/SKL Solo"
					remove 150 from the player's balance
			else if arg 1 contains "MAG/SKL Solo":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - MAG/SKL Solo"
					remove 150 from the player's balance
			else if arg 1 contains "STR/MAG Solo":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - STR/MAG Solo"
					remove 150 from the player's balance
			else if arg 1 contains "STR/DEF Solo":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - STR/DEF Solo"
					remove 150 from the player's balance
			else if arg 1 contains "Desperation":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Desperation"
					remove 150 from the player's balance
			else if arg 1 contains "Shield Pulse":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Shield Pulse"
					remove 150 from the player's balance
			else if arg 1 contains "Brash Assault":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Brash Assault"
					remove 150 from the player's balance
			else if arg 1 contains "Riposte":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Riposte"
					remove 150 from the player's balance
			else if arg 1 contains "FortifyAllyHealth":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Fortify Ally Health"
					remove 200 from the player's balance
			else if arg 1 contains "Fortify Health":
				if {_cash} is less than 200:
					send "<red><bold>You lack the required funds to purchase this skill. You need $200, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Fortify Health"
					remove 200 from the player's balance
			else if arg 1 contains "Bonus Blade":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Bonus Blade"
					remove 150 from the player's balance
			else if arg 1 contains "Brave Blade":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Brave Blade"
					remove 150 from the player's balance
			else if arg 1 contains "Power Within":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Power Within"
					remove 150 from the player's balance
			else if arg 1 contains "Steady Stance":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Steady Stance"
					remove 150 from the player's balance
			else if arg 1 contains "Swift Stance":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Swift Stance"
					remove 150 from the player's balance
			else if arg 1 contains "Warding Stance":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Warding Stance"
					remove 150 from the player's balance
			else if arg 1 contains "Fierce Stance":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Fierce Stance"
					remove 150 from the player's balance
			else if arg 1 contains "Swift Sparrow":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Swift Sparrow"
					remove 150 from the player's balance
			else if arg 1 contains "Steady Blow":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 1 of slot 4 of the player's current inventory's lore to "Slot A - Steady Blow"
					remove 150 from the player's balance
			else if arg 1 contains "Eclipse Brace":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Eclipse Brace"
					remove 150 from the player's balance
			else if arg 1 contains "Solar Brace":
				if {_cash} is less than 150:
					send "<red><bold>You lack the required funds to purchase this skill. You need $150, but you only have %player's money%."
				else:
					set line 2 of slot 4 of the player's current inventory's lore to "Slot B - Solar Brace"
					remove 150 from the player's balance
			if the player's balance is less than {_cash}:
				send "<green>Success!"
			else:
				send "<red><bold>The skill you specified was invalid!"

#Weapon Refinery
command /refine [<text="help">]:
	description: Refine weapons to give them bonus effects.
	usage: /refine (type)
	executable by: players
	trigger:
		set {_cash.%player%} to the player's money
		if arg 1 is "help":
			send "<bold>List of Weapon Refines:"
			send "- Slaying: Add +10 to special activation chance"
			send "- Reinforced: Add 1.5 hearts of damage to your attacks."
			send "- Warding: Reduce incoming damage by 1.5 hearts."
			send "- Piercing: Ignore enemy damage deductions (armour, potions, etc..), but only deal 3/4 damage."
			send "- Koenig: Add 2.5 hearts of damage whenever you activate a special."
			send "- Crushing: Dealing over 9 hearts of damage increases your special activation chance by 1/3 of the damage you dealt. Stacks, and is reset on special activation."
			send "- Stylish: Combo scores are easier to increase."
		if the player's held item is tool:
			if {_cash.%player%} is less than 300:
				send "<red><bold>You lack the required funds to refine this weapon. | Required Funds: $300 | Your Funds: %player's money%"
			else if arg 1 is "Slaying":
				set line 4 of slot 4 of the player's current inventory's lore to "<green><bold>Refined: Slaying"
				if line 4 of slot 4 of the player's current inventory's lore contains "<green><bold>Refined: Slaying":
					remove 300 from the player's money
					send "<light green><bold>Sucessfully refined this weapon. | Your Funds: %player's money%"
				else:
					send "<light red><bold>Could not refine your weapon. You have not been charged. | Your Funds: %player's money%"
			else if arg 1 is "Reinforced":
				set line 4 of slot 4 of the player's current inventory's lore to "<red><bold>Refined: Reinforced"
				if line 4 of slot 4 of the player's current inventory's lore contains "<red><bold>Refined: Reinforced":
					remove 300 from the player's money
					send "<light green><bold>Sucessfully refined this weapon. | Your Funds: %player's money%"
				else:
					send "<light red><bold>Could not refine your weapon. You have not been charged. | Your Funds: %player's money%"
			else if arg 1 is "Crushing":
				set line 4 of slot 4 of the player's current inventory's lore to "<purple><bold>Refined: Crushing"
				if line 4 of slot 4 of the player's current inventory's lore contains "<purple><bold>Refined: Crushing":
					remove 300 from the player's money
					send "<light green><bold>Sucessfully refined this weapon. | Your Funds: %player's money%"
				else:
					send "<light red><bold>Could not refine your weapon. You have not been charged. | Your Funds: %player's money%"
			else if arg 1 is "Warding":
				set line 4 of slot 4 of the player's current inventory's lore to "<light blue><bold>Refined: Warding"
				if line 4 of slot 4 of the player's current inventory's lore contains "<light blue><bold>Refined: Warding":
					remove 300 from the player's money
					send "<light green><bold>Sucessfully refined this weapon. | Your Funds: %player's money%"
				else:
					send "<light red><bold>Could not refine your weapon. You have not been charged. | Your Funds: %player's money%"
			else if arg 1 is "Piercing":
				set line 4 of slot 4 of the player's current inventory's lore to "<light red><bold>Refined: Piercing"
				if line 4 of slot 4 of the player's current inventory's lore contains "<light red><bold>Refined: Piercing":
					remove 300 from the player's money
					send "<light green><bold>Sucessfully refined this weapon. | Your Funds: %player's money%"
				else:
					send "<light red><bold>Could not refine your weapon. You have not been charged. | Your Funds: %player's money%"
			else if arg 1 is "Koenig":
				set line 4 of slot 4 of the player's current inventory's lore to "<gold><bold>Refined: Koenig"
				if line 4 of slot 4 of the player's current inventory's lore contains "<gold><bold>Refined: Koenig":
					remove 300 from the player's money
					send "<light green><bold>Sucessfully refined this weapon. | Your Funds: %player's money%"
				else:
					send "<light red><bold>Could not refine your weapon. You have not been charged. | Your Funds: %player's money%"
			else if arg 1 is "Stylish":
				set line 4 of slot 4 of the player's current inventory's lore to "<gold><bold>Refined: Stylish"
				if line 4 of slot 4 of the player's current inventory's lore contains "<gold><bold>Refined: Stylish":
					remove 300 from the player's money
					send "<light green><bold>Sucessfully refined this weapon. | Your Funds: %player's money%"
				else:
					send "<light red><bold>Could not refine your weapon. You have not been charged. | Your Funds: %player's money%"
			else if arg 1 is "Unique":
				set line 4 of slot 4 of the player's current inventory's lore to "<white><bold>Refined: Unique"
				if line 4 of slot 4 of the player's current inventory's lore contains "<white><bold>Refined: Unique":
					remove 300 from the player's money
					send "<light green><bold>Sucessfully refined this weapon. | Your Funds: %player's money%"
				else:
					send "<light red><bold>Could not refine your weapon. You have not been charged. | Your Funds: %player's money%"
			else:
				send "<light red>Could not understand your command. Try again, and check that you are using a valid argument."

#Skill Definitions Start Here

#Periodicals
every 5 seconds:
	loop all players:
		#Leggings Skills
		if the lore of the loop-player's leggings contains "Regeneration":
			apply regeneration 2 to loop-player for 5 seconds
		else if the lore of the loop-player's leggings contains "Strength":
			apply strength 2 to loop-player for 5 seconds
		else if the lore of the loop-player's leggings contains "Swiftness":
			apply swiftness 2 to loop-player for 5 seconds
		else if the lore of the loop-player's leggings contains "Resistance":
			apply resistance 2 to loop-player for 5 seconds
		#Chestplate Skills - Stat Increases
		#HP Up
		if the lore of the loop-player's chestplate contains "HP Up":
			if {skillhpUp.%loop-player%} is not set:
				set {skillhpUp.%loop-player%} to true
				add 10 to {hpbuff.%loop-player%}
				set the loop-player's maximum health to (({hp.%loop-player%} + {hpbuff.%loop-player%}) / 2)
		else:
			if {skillhpUp.%loop-player%} is true:
				clear {skillhpUp.%loop-player%}
				subtract 10 from {hpbuff.%loop-player%}
				set the loop-player's maximum health to (({hp.%loop-player%} + {hpbuff.%loop-player%}) / 2)
		#STR Up
		if the lore of the loop-player's chestplate contains "STR Up":
			if {skillstrUp.%loop-player%} is not set:
				set {skillstrUp.%loop-player%} to true
				add 10 to {strbuff.%loop-player%}
		else:
			if {skillstrUp.%loop-player%} is set:
				clear {skillstrUp.%loop-player%}
				subtract 10 from {strbuff.%loop-player%}
		#SKL Up
		if the lore of the loop-player's chestplate contains "SKL Up":
			if {skillsklUp.%loop-player%} is not set:
				set {skillsklUp.%loop-player%} to true
				add 20 to {sklbuff.%loop-player%}
		else:
			if {skillsklUp.%loop-player%} is true:
				clear {skillsklUp.%loop-player%}
				subtract 20 from {sklbuff.%loop-player%}
		#SPD Up
		if the lore of the loop-player's chestplate contains "SPD Up":
			if {skillspdUp.%loop-player%} is not set:
				set {skillspdUp.%loop-player%} to true
				add 10 to {spdbuff.%loop-player%}
		else if {skillspdUp.%loop-player%} is true:
			clear {skillspdUp.%loop-player%}
			subtract 10 from {spdbuff.%loop-player%}
		#MAG Up
		if the lore of the loop-player's chestplate contains "MAG Up":
			if {skillmagUp.%loop-player%} is not set:
				set {skillmagUp.%loop-player%} to true
				add 10 to {magbuff.%loop-player%}
		else if {skillmagUp.%loop-player%} is true:
			clear {skillmagUp.%loop-player%}
			subtract 10 from {magbuff.%loop-player%}
		#DEF Up
		if the lore of the loop-player's chestplate contains "DEF Up":
			if {skilldefUp.%loop-player%} is not set:
				set {skilldefUp.%loop-player%} to true
				add 10 to {defbuff.%loop-player%}
		else if {skilldefUp.%loop-player%} is true:
			clear {skilldefUp.%loop-player%}
			subtract 10 from {defbuff.%loop-player%}
			

every 1.5 seconds:
	#Power Within
	loop all players:
		if the 1st line of the lore of loop-player's tool contains "Slot A - Power Within":
			damage loop-player by 0.5 with fake cause fall
			add 20 to {strbuff.%loop-player%}
			add 20 to {defbuff.%loop-player%}
			add 20 to {spdbuff.%loop-player%}
			add 20 to {sklbuff.%loop-player%}
			add 20 to {resbuff.%loop-player%}
			wait 1 second
			subtract 20 from {strbuff.%loop-player%}
			subtract 20 from {defbuff.%loop-player%}
			subtract 20 from {spdbuff.%loop-player%}
			subtract 20 from {sklbuff.%loop-player%}
			subtract 20 from {resbuff.%loop-player%}
		if the 2nd line of the lore of loop-player's tool contains "Slot B - Brave Blade":
			subtract 15 from {spdbuff.%loop-player%}
			wait 1 second
			add 15 to {spdbuff.%loop-player%}

#Blows
on damage:
	#Darting Blow
	if 1st line of the lore of attacker's tool contains "Slot A - Darting Blow":
		if {DBCD.%attacker%} is not true:
			add 30 to {spdbuff.%attacker%}
			set {DBCD.%attacker%} to true
			wait 10 seconds
			subtract 30 from {spdbuff.%attacker%}
			send "<bold>Darting Blow wore off!" to the attacker
			wait 5 seconds
			clear {DBCD.%attacker%}
			send "<bold>Darting Blow ready!" to the attacker
	#Armoured Blow
	if 1st line of the lore of attacker's tool contains "Slot A - Armoured Blow":
		if {ABCD.%attacker%} is not true:
			add 30 to {defbuff.%attacker%}
			set {ABCD.%attacker%} to true
			wait 10 seconds
			subtract 30 from {defbuff.%attacker%}
			send "<bold>Armoured Blow wore off!" to the attacker
			wait 5 seconds
			clear {ABCD.%attacker%}
			send "<bold>Armoured Blow ready!" to the attacker
	#Death Blow
	if 1st line of the lore of attacker's tool contains "Slot A - Death Blow":
		if {DBCD.%attacker%} is not true:
			add 30 to {strbuff.%attacker%}
			set {DBCD.%attacker%} to true
			wait 10 seconds
			subtract 30 from {strbuff.%attacker%}
			send "<bold>Death Blow wore off!" to the attacker
			wait 5 seconds
			clear {DBCD.%attacker%}
			send "<bold>Death Blow ready!" to the attacker
	#Steady Blow
	if 1st line of the lore of attacker's tool is "Slot A - Steady Blow":
		if {SteadyBlow.%attacker%} is not true:
			add 20 to {strbuff.%attacker%}
			add 20 to {defbuff.%attacker%}
			set {SteadyBlow.%attacker%} to true
			wait 7 seconds
			subtract 20 from {strbuff.%attacker%}
			subtract 20 from {defbuff.%attacker%}
			send "<bold>Steady Blow wore off!" to the attacker
			wait 7 seconds
			clear {SteadyBlow.%attacker%}
			send "<bold>Steady Blow ready!" to the attacker
	#Swift Sparrow
	if 1st line of the lore of attacker's tool contains "Slot A - Swift Sparrow":
		if {SwiftSparrow.%attacker%} is not true:
			add 20 to {spdbuff.%attacker%}
			add 20 to {strbuff.%attacker%}
			set {SwiftSparrow.%attacker%} to true
			wait 7 seconds
			subtract 20 from {spdbuff.%attacker%}
			subtract 20 from {strbuff.%attacker%}
			send "<bold>Swift Sparrow wore off!" to the attacker
			wait 7 seconds
			clear {SwiftSparrow.%attacker%}
			send "<bold>Swift Sparrow ready!" to the attacker
			
#Stances
on damage:
	#Steady Stance
	if the 1st line of the lore of the victim's tool is "Slot A - Steady Stance":
		if {steadystance.%victim%} is not set:
			set {steadystance.%victim%} to true
			add 20 to {defbuff.%victim%}
			wait 2 seconds
			subtract 20 from {defbuff.%victim%}
			clear {steadystance.%victim%}
	#Swift Stance
	if the 1st line of the lore of the victim's tool contains "Slot A - Swift Stance":
		if {swiftstance.%victim%} is not set:
			add 20 to {spdbuff.%victim%}
			set {swiftstance.%victim%} to true
			wait 2 second
			subtract 20 from {spdbuff.%victim%}
			clear {swiftstance.%victim%}
	#Warding Stance
	if the 1st line of the lore of the victim's tool contains "Slot A - Warding Stance":
		if {wardingstance.%victim%} is not set:
			set {wardingstance.%victim%} to true
			add 20 to {resbuff.%victim%}
			wait 2 second
			subtract 20 from {resbuff.%victim%}
			clear {wardingstance.%victim%}
	#Fierce Stance
	if the 1st line of the lore of the victim's tool contains "Slot A - Fierce Stance":
		if {fiercestance.%victim%} is not set:
			add 20 to {strbuff.%victim%}
			set {fiercestance.%victim%} to true
			wait 2 second
			subtract 20 from {strbuff.%victim%}
			clear {fiercestance.%victim%}
			
#Seals
on damage:
	#Seal Attack
	if the 2nd line of the lore of the attacker's tool contains "Slot B - Seal Attack":
		remove weakness from the victim
		apply weakness 2 to the victim for 5 seconds
	#Seal Speed
	if the 2nd line of the lore of the attacker's tool contains "Slot B - Seal Speed":
		remove slowness from the victim
		apply slowness 2 to the victim for 5 seconds
	#Poison Strike
	if the 2nd line of the lore of the attacker's tool contains "Slot B - Poison Strike":
		remove wither from the victim
		apply wither 3 to the victim for 5 seconds

on damage:
	#Bonds
	if the 1st line of the lore of the attacker's tool contains "Bond":
		if {party.%attacker%} is set:
			loop all players in radius 10 of the attacker:
				if {party.%loop-player%} is {party.%attacker%}:
					set {_bondOK} to 1
					exit 1 loop
		if {_bondOK} is 1:
			if the 1st line of the lore of the attacker's tool contains "STR":
				add 40 to {strbuff.%attacker%}
				wait 1 second
				subtract 40 from {strbuff.%attacker%}
			else if the 1st line of the lore of the attacker's tool contains "DEF":
				add 40 to {defbuff.%attacker%}
				wait 1 second
				subtract 40 from {defbuff.%attacker%}
			else if the 1st line of the lore of the attacker's tool contains "SKL":
				add 40 to {sklbuff.%attacker%}
				wait 1 second
				subtract 40 from {sklbuff.%attacker%}
			else if the 1st line of the lore of the attacker's tool contains "MAG":
				add 40 to {resbuff.%attacker%}
				wait 1 second
				subtract 40 from {resbuff.%attacker%}
	#Solos
	if the 1st line of the lore of the attacker's tool contains "Solo":
		if {party.%attacker%} is not set:
			set {_soloOK} to 1
		else:
			loop all players in radius 10 of the attacker:
				if {party.%loop-player%} is {party.%attacker%}:
					set {_playerFound} to 1
					exit 1 loop
			if {_playerFound} is not 1:
				set {_soloOK} to 1
			if {_soloOK} is 1:
				if the 1st line of the lore of the attacker's tool contains "STR":
					add 40 to {strbuff.%attacker%}
					wait 1 second
					subtract 40 from {strbuff.%attacker%}
				else if the 1st line of the lore of the attacker's tool contains "DEF":
					add 40 to {defbuff.%attacker%}
					wait 1 second
					subtract 40 from {defbuff.%attacker%}
				else if the 1st line of the lore of the attacker's tool contains "SKL":
					add 40 to {sklbuff.%attacker%}
					wait 1 second
					subtract 40 from {sklbuff.%attacker%}
				else if the 1st line of the lore of the attacker's tool contains "MAG":
					add 40 to {resbuff.%attacker%}
					wait 1 second
					subtract 40 from {resbuff.%attacker%}

#Skill Effects	
on damage:
	#Refines
	if the 6th line of the lore of the attacker's tool contains "<red><bold>Refined: Reinforced":
		set damage to damage + 1.5
	if the 6th line of the lore of the victim's tool contains "<light blue><bold>Refined: Warding":
		if damage cause is attack:
			set damage to damage - 1.5
		else if projectile exists:
			set damage to damage - 1.5
	if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
		if damage is more than 7:
			add damage * 0.33 to {crushing.%attacker%}
			if {crushing.%attacker%} is more than 25:
				set {crushing.%attacker%} to 25
	if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Stylish":
		add damage / 2 to {combo.%attacker%}
	#Brave Blade
	if the 2nd line of the lore of the attacker's tool contains "Slot B - Brave Blade":
		set damage to ((damage - 1.5) * 2)
	#Close Defence
	if damage cause is attack:
		loop monsters in radius 4 of the victim:
			attacker exists
			set {_CD} to true
		if 1st line of the lore of victim's tool contains "Slot A - Close Defence":
			if {_CD} is true:
				set damage to damage * 0.44
				show magical critical hit on the victim
		if the 1st line of the lore of victim's tool contains "Slot A - Close Counter":
			if {_CD} is true:
				damage the attacker by 2 hearts with fake cause attack
				push the attacker backwards at speed 0.75
				damage the victim's tool by 10
	#Distant Defence
	else if projectile exists:
		loop entities in radius 4 of the victim:
			entity exists
			set {_noDC} to true
		if 1st line of the lore of victim's tool contains "Slot A - Distant Defence":
			set damage to damage * 0.44
			show magical critical hit on the victim
		else if 1st line of the lore of the victim's tool contains "Slot A - Distant Counter":
			if {_noDC} is false:
				damage the attacker by damage * 0.5
	#Brash Assault
	if the 2nd line of the lore of the attacker's tool contains "Slot B - Brash Assault":
		if the attacker's health is less than (attacker's maximum health * 0.5):
			if {BA.%attacker%} is 1:
				set damage to damage * 2
				apply resistance 2 to the attacker for 2 seconds
				clear {BA.%attacker%}
			else:
				set {BA.%attacker%} to 1
	#Desperation
	if the 2nd line of the lore of the attacker's tool contains "Slot B - Desperation":
		if the attacker's health is less than or equal to (attacker's maximum health * 0.5):
			damage the victim by damage
			push the victim upwards at speed 0.25
			push the victim backwards at speed 1
			send "<light blue>Desperation active!" to the attacker
	#Armour Smasher
	if the 1st line of the lore of the attacker's tool contains "Slot A - Armour Smasher":
		set {_bonusdamage} to helmType(victim)
		add chestType(victim) to {_bonusdamage}
		add legType(victim) to {_bonusdamage}
		add btType(victim) to {_bonusdamage}
		add {_bonusdamage} to damage
	#Riposte
	if the 2nd line of the lore of the victim's tool contains "Slot B - Riposte":
		if the victim's health is more than (victim's maximum health * 0.8):
			loop all entities in radius 4 of the victim:
				if loop-entity is attacker:
					set {_cc} to 1
			if {_cc} is 1:
				damage the attacker by damage * 0.25
				push the attacker upwards at speed 0.25
				push the attacker backwards at speed 0.5
	#Warp Strike
	if the 1st line of the lore of victim's tool contains "Slot A - Warp Strike.":
		apply resistance 10 to the victim for 3 seconds
		teleport the victim to the attacker
		damage the attacker by 0.5 hearts
		damage the victim's tool by 5
	#Seal Defense
	if the 2nd line of the lore of the attacker's tool contains "Slot B - Seal Defense":
		set damage to damage * 1.35
	#Life and Death
	if the 1st line of the lore of attacker's tool contains "Slot A - Life and Death":
		set damage to damage * 1.75
	if the 1st line of the lore of victim's tool contains "Slot A - Life and Death":
		set damage to damage * 1.75
	#Fury 3
	if the 1st line of the lore of attacker's tool contains "Slot A - Fury":
		set damage to damage+3
		damage the attacker by 1.5 heart with fake cause attack
	#Drag Back
	if the 2nd line of the lore of attacker's tool contains "Slot B - Drag Back":
		push the attacker backwards at speed 0.75
		push the victim forwards at speed 0.75
	#Hit and Run
	if the 2nd line of the lore of attacker's tool contains "Slot B - Hit and Run":
		push the attacker backwards at speed 1
		damage the attacker's tool by 1

on damage:
	set {_perk} to checkSlots(victim,"Guard")
	if {_perk} is 1:
		subtract 50 from {sklbuff.%attacker%}
	#Bonus Blade
	if the 2nd line of the lore of the attacker's tool contains "Slot B - Bonus Blade":
		set {_oldSTR} to {strbuff.%attacker%}
		set {_oldDEF} to {defbuff.%attacker%}
		set {_oldSPD} to {spdbuff.%attacker%}
		set {_oldMAG} to {resbuff.%attacker%}
		set {_oldSKL} to {sklbuff.%attacker%}
		set {strbuff.%attacker%} to {strbuff.%attacker%} * 1.5
		set {defbuff.%attacker%} to {defbuff.%attacker%} * 1.5
		set {spdbuff.%attacker%} to {spdbuff.%attacker%} * 1.5
		set {resbuff.%attacker%} to {resbuff.%attacker%} * 1.5
		set {sklbuff.%attacker%} to {sklbuff.%attacker%} * 1.5
		set {_BB.%attacker%} to true
	if the 2nd line of the lore of the victim's tool contains "Slot B - Bonus Blade":
		set {_oldSTR.%victim%} to {strbuff.%victim%}
		set {_oldDEF.%victim%} to {defbuff.%victim%}
		set {_oldSPD.%victim%} to {spdbuff.%victim%}
		set {_oldres.%victim%} to {resbuff.%victim%}
		set {_oldSKL.%victim%} to {sklbuff.%victim%}
		set {strbuff.%victim%} to {strbuff.%victim%} * 1.5
		set {defbuff.%victim%} to {defbuff.%victim%} * 1.5
		set {spdbuff.%victim%} to {spdbuff.%victim%} * 1.5
		set {resbuff.%victim%} to {resbuff.%victim%} * 1.5
		set {sklbuff.%victim%} to {sklbuff.%victim%} * 1.5
		set {_bb.%victim%} to true
	#Astra
	if the 5th line of the lore of attacker's tool contains "Special - Astra":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%} * 0.8) ^ 0.65
		if {_level} is greater than 50:
			set {_level} to 50
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			set damage to damage * 3
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			clear {crushing.%attacker%}
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<gold>Astra was activated!" to attacker
			play 60 (nether portal break with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "entity.zombie_villager.cure" with volume 0.5 and pitch 1 at victim for attacker
	#Glimmer
	if the 5th line of the lore of attacker's tool contains "Special - Glimmer":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.765
		if {_level} is more than 70:
			set {_level} to 70
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			set damage to damage * 1.5
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			clear {crushing.%attacker%}
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<gold>Glimmer was activated!" to attacker
			play 30 (nether portal break with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "entity.zombie_villager.cure" with volume 0.25 and pitch 1.5 at victim for attacker
	#Blazing Light
	if the 5th line of the lore of attacker's tool contains "Special - Blazing Light":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.7
		if {_level} is more than 50:
			set {_level} to 50
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			set damage to damage + (damage / 2)
			loop all monsters in radius 7 of the victim:
				if loop-monster is not the attacker:
					send "<gold>%loop-entity% hit for %damage%!" to the attacker
					strike lightning effect at the loop-monster
					damage the loop-entity by damage
			clear {crushing.%attacker%}
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<gold>Blazing Light was activated!" to attacker
			play 60 (firework spark with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "entity.zombie_villager.cure" with volume 0.25 and pitch 1.5 at victim for attacker
	#Growing Light
	if the 5th line of the lore of attacker's tool contains "Special - Growing Light":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.7
		if {_level} is more than 50:
			set {_level} to 50
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			set damage to damage + (damage / 4)
			loop all monsters in radius 14 of the victim:
				if loop-monster is not the attacker:
					send "<gold>%loop-entity% hit for %damage%!" to the attacker
					strike lightning effect at the loop-monster
					damage the loop-entity by damage / 2
			clear {crushing.%attacker%}
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<gold>Blazing Light was activated!" to attacker
			play 30 (firework spark with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "entity.zombie_villager.cure" with volume 0.25 and pitch 1.5 at victim for attacker
	#Luna
	if the 5th line of the lore of attacker's tool contains "Special - Luna":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.75
		if {_level} is more than 70:
			set {_level} to 70
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			set {_bonusDamage} to helmType(victim)
			add chestType(victim) to {_bonusdamage}
			add legType(victim) to {_bonusdamage}
			add btType(victim) to {_bonusdamage}
			set {_bonusdamage} to {_bonusdamage} * 1.5
			set damage to damage + {_bonusdamage}
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			clear {crushing.%attacker%}
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<gold>Luna was activated!" to attacker
			play 40 (cloud with speed 1) at the victim
			play 40 (ender signal with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "entity.zombie_villager.cure" with volume 0.25 and pitch 1.5 at victim for attacker
	#Moonbow
	if the 5th line of the lore of attacker's tool contains "Special - Moonbow":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.85
		if {_level} is more than 80:
			set {_level} to 80
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			set {_bonusDamage} to helmType(victim)
			add chestType(victim) to {_bonusdamage}
			add legType(victim) to {_bonusdamage}
			add btType(victim) to {_bonusdamage}
			set damage to damage + {_bonusdamage}
			set {_moonbowDEF} to ({def.%victim%} + {defbuff.%victim%} * 0.7)
			subtract {_moonbowDEF} from {defbuff.%victim%}
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			clear {crushing.%attacker%}
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<gold>Moonbow was activated!" to attacker
			play 20 (cloud with speed 1) at the victim
			play 20 (ender signal with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "entity.zombie_villager.cure" with volume 0.25 and pitch 1.5 at victim for attacker
	#Sol
	if the 5th line of the lore of attacker's tool contains "Special - Sol":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.7
		if {_level} is greater than 70:
			set {_level} to 70
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			heal the attacker by damage * 0.75
			clear {crushing.%attacker%}
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<gold>Sol was activated!" to attacker
			play 40 (heart with speed 1) at the attacker
			show 40 (yellow wool break with speed 1) at the attacker
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "entity.player.levelup" with volume 0.5 and pitch 0.75 at victim for attacker
	#Aether
	if the 5th line of the lore of attacker's tool contains "Special - Aether":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.55
		if {_level} is greater than 65:
			set {_level} to 65
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			set {_bonusDamage} to helmType(victim)
			add chestType(victim) to {_bonusdamage}
			add legType(victim) to {_bonusdamage}
			add btType(victim) to {_bonusdamage}
			set {_bonusdamage} to {_bonusdamage} * 1.5
			set damage to damage + {_bonusdamage}
			set {_lunaDEF} to ({def.%victim%} + {defbuff.%victim%} * 0.5)
			subtract {_lunaDEF} from {defbuff.%victim%}
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			heal the attacker by damage * 0.75
			clear {crushing.%attacker%}
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<gold>Aether was activated!" to attacker
			play 50 (heart with speed 1) at the attacker
			play 50 (yellow wool break with speed 1) at the attacker
			play 50 (cloud with speed 1) at the victim
			play 50 (ender signal with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "item.totem.use" with volume 0.5 and pitch 1 at victim for attacker
			play sound "entity.player.levelup" with volume 0.5 and pitch 0.75 at victim for attacker
	#Retribution
	if the 5th line of the lore of attacker's tool contains "Special - Retribution":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.675
		if {_level} is greater than 70%:
			set {_level} to 70
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			set damage to damage + (abs(the health of the attacker - the max health of the attacker) * 0.5)
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			clear {crushing.%attacker%}
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<gold>Retribution was activated!" to attacker
			play 60 (red wool break with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "entity.zombie_villager.cure" with volume 0.25 and pitch 1.5 at victim for attacker
	#Pavise
	if the 5th line of the lore of victim's tool contains "Special - Pavise":
		set {_level} to ({skl.%victim%} + {sklbuff.%victim%}) ^ 0.8
		if the 2nd line of the lore of the victim's tool contains "Shield Pulse":
			add 10 to {_level}
		if {_level} is greater than 85:
			set {_level} to 85
		if the 6th line of the lore of the victim's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the victim's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%victim%} to {_level}
		loop all entities in radius 5 of the victim:
			if loop-entity is attacker:
				set {_AT} to 1
				exit 1 loop
		if {_AT} is 1:
			chance of {_level}%:
				set damage to damage * 0.5
				if the 6th line of the lore of the victim's tool contains "<bold>Refined: Koenig.":
					set damage to damage - 1
				if the 1st line of the lore of the victim's tool contains "Slot B - Shield Pulse":
					set damage to damage - 2.5
				clear {crushing.%attacker%}
				send "<gold>Pavise was activated!" to victim
				play 60 (crit with speed 1) at the victim
				if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
					set {_LB} to true
					set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
					subtract {_lunarnull} from {defbuff.%victim%}
				else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
					heal the attacker by (damage * 0.5)
				play sound "item.totem.use" with volume 0.5 and pitch 0.5 at victim for attacker
	#Aegis
	if the 5th line of the lore of victim's tool contains "Special - Aegis":
		set {_level} to ({skl.%victim%} + {sklbuff.%victim%}) ^ 0.8
		if the 2nd line of the lore of the victim's tool contains "Shield Pulse":
			add 10 to {_level}
		if {_level} is greater than 85:
			set {_level} to 85
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		if projectile exists:
			chance of {_level}%:
				clear {crushing.%attacker%}
				set damage to damage * 0.5
				if the 6th line of lore of the victim's tool contains "<bold>Refined: Koenig.":
					set damage to damage - 1
				if the 1st line of the lore of the victim's tool contains "Slot B - Shield Pulse":
					set damage to damage - 2.5
				send "<gold>Aegis was activated!" to victim
				play 60 (crit with speed 1) at the victim
				if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
					set {_LB} to true
					set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
					subtract {_lunarnull} from {defbuff.%victim%}
				else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
					heal the attacker by (damage * 0.5)
				play sound "item.totem.use" with volume 0.5 and pitch 0.5 at victim for attacker
	#Ignis
	if the 5th line of the lore of attacker's tool contains "Special - Ignis":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.7
		if {_level} is greater than 50:
			set {_level} to 50
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			set damage to damage + (({def.%attacker%} / 2) ^ 0.8)
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			clear {crushing.%attacker%}
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<gold>Ignis was activated!" to attacker
			play 60 (mobspawner flames with speed 1) at the victim
			play 60 (lava pop with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "item.totem.use" with volume 0.5 and pitch 2 at victim for attacker
	#Dragon Fang
	if the 5th line of the lore of attacker's tool contains "Special - Dragon Fang":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.7
		if {_level} is greater than 50:
			set {_level} to 50
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			set damage to damage + (({str.%attacker%} / 2) ^ 0.8)
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			clear {crushing.%attacker%}
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<gold>Dragon Fang was activated!" to attacker
			play 60 (purple wool break with speed 1) at the victim
			play 60 (dust of netherrack with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "item.totem.use" with volume 0.5 and pitch 2 at victim for attacker
	#Glacies
	if the 5th line of the lore of attacker's tool contains "Special - Glacies":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.7
		if {_level} is greater than 50:
			set {_level} to 50
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			set damage to damage + (({res.%attacker%} / 2) ^ 0.8)
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			clear {crushing.%attacker%}
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<gold>Glacies was activated!" to attacker
			play 60 (ice break with speed 1) at the victim
			play 60 (snowball break with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "item.totem.use" with volume 0.5 and pitch 2 at victim for attacker
	#Rising Wind
	if the 5th line of the lore of attacker's tool contains "Special - Rising Wind":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.7
		if {_level} is greater than 50:
			set {_level} to 50
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			set damage to damage + (({spd.%attacker%} / 2) ^ 0.8)
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			clear {crushing.%attacker%}
			send "<gold>Rising Wind was activated!" to attacker
			play 60 (happy villager with speed 1) at the victim
			play 60 (tall grass break with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "item.totem.use" with volume 0.5 and pitch 2 at victim for attacker
	#Radiant Aether
	if the name of the attacker's tool contains "<gold><bold>Ragnell":
		set {_skill} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.65
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_skill} to {_skill} + 10
		else if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_skill}
		if {_skill} is greater than 65:
			set {_skill} to 65
		chance of {_skill}%:
			set {_bonusDamage} to helmType(victim)
			add chestType(victim) to {_bonusdamage}
			add legType(victim) to {_bonusdamage}
			add btType(victim) to {_bonusdamage}
			set {_bonusdamage} to {_bonusdamage} * 1.5
			set damage to damage + {_bonusdamage}
			set {_lunaDEF} to ({def.%victim%} + {defbuff.%victim%} * 0.5)
			subtract {_lunaDEF} from {defbuff.%victim%}
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Wrath":
				set damage to damage + 2.5
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			heal the attacker by damage * 0.5
			set {_rng} to a random integer between 1 and 4
			if {_rng} is 1:
				make attacker say "%{skillquote1.%attacker%}%"
			else if {_rng} is 2:
				make attacker say "%{skillquote2.%attacker%}%"
			else if {_rng} is 3:
				make attacker say "%{skillquote3.%attacker%}%"
			else if {_rng} is 4:
				make attacker say "%{skillquote4.%attacker%}%"
			send "<light blue><bold>Radiant Aether was activated!" to attacker
			play 40 (heart with speed 1) at the attacker
			play 40 (yellow wool break with speed 1) at the attacker
			play 40 (cloud with speed 1) at the victim
			play 40 (ender signal with speed 1) at the victim
			play 80 (magic crit with speed 1) at the victim
			if the 2nd line of the lore of the attacker's tool contains "Slot B - Eclipse Brace":
				set {_LB} to true
				set {_lunarnull} to (({def.%victim%} + {defbuff.%victim%}) * 0.3)
				subtract {_lunarnull} from {defbuff.%victim%}
			else if the 2nd line of the lore of the attacker's tool contains "Slot B - Solar Brace":
				heal the attacker by (damage * 0.5)
			play sound "item.totem.use" with volume 0.25 and pitch 0.5 at victim for attacker
			strike lightning effect at the victim
	#Strength & Defence calculations
	set {_magical} to metadata value "SPELL" of projectile
	if the 1st line of the lore of the attacker's tool contains "Slot A - Sorcery Aura":
		set {_magical} to 1
	if {class.%attacker%} is "Dragonborn":
		set {_magical} to 1
	else if {class.%attacker%} is "Manakete":
		set {_magical} to 1
	else if {class.%attacker%} is "Divine Dragon":
		set {_magical} to 1
	if {_magical} is 1:
		set damage to damage + ((({res.%attacker%} + {resbuff.%attacker%}) / 5)) - ((({res.%victim%} + {resbuff.%victim%}) / 5))
	if projectile exists:
		#broadcast "Projectile!"
		if {def.%victim%} is not set:
			set damage to damage + (((({str.%attacker%} + {strbuff.%attacker%}) / 5)))
		else if {str.%attacker%} is not set:
			set damage to damage - ((({def.%victim%} + {defbuff.%victim%}) / 5))
		else:
			set damage to damage + (((({str.%attacker%} + {strbuff.%attacker%}) / 5)) - ((({def.%victim%} + {defbuff.%victim%}) / 5)))
		if {spd.%victim%} is not set:
			if ({spd.%attacker%} + {spdbuff.%attacker%}) is more than 29:
				set damage to damage * 2
				send "<light green>Outsped the defender and doubled!" to the attacker
				send "<light red>%attacker% outsped you and doubled!" to the victim
		else:
			if ({spd.%attacker%} + {spdbuff.%attacker%}) is more than ({spd.%victim%} + {spdbuff.%victim%} + 15):
				set damage to damage * 2
				send "<light green>Outsped the defender and doubled!" to the attacker
				send "<light red>%attacker% outsped you and doubled!" to the victim
	if damage cause is attack:
		if {def.%victim%} is not set:
			set damage to damage + (((({str.%attacker%} + {strbuff.%attacker%}) / 5)))
		else if {str.%attacker%} is not set:
			set damage to damage - ((({def.%victim%} + {defbuff.%victim%}) / 5))
		else:
			set damage to damage + (((({str.%attacker%} + {strbuff.%attacker%}) / 5)) - ((({def.%victim%} + {defbuff.%victim%}) / 5)))
		if {spd.%victim%} is not set:
			if ({spd.%attacker%} + {spdbuff.%attacker%}) is more than 29:
				set damage to damage * 2
				send "<light green>Outsped the defender and doubled!" to the attacker
				send "<light red>%attacker% outsped you and doubled!" to the victim
		else:
			if ({spd.%attacker%} + {spdbuff.%attacker%}) is more than ({spd.%victim%} + {spdbuff.%victim%} + 15):
				set damage to damage * 2
				send "<light green>Outsped the defender and doubled!" to the attacker
				send "<light red>%attacker% outsped you and doubled!" to the victim
	if damage is less than 0:
		set damage to 0.5
	if {_lunaDEF} is set:
		add {_lunaDEF} to {defbuff.%victim%}
	if {_moonbowDEF} is set:
		add {_moonbowDEF} to {defbuff.%victim%}
	if the 6th line of the lore of the attacker's tool contains "<light red><bold>Refined: Piercing":
		set {_bypassdamage.%attacker%} to damage
		cancel event
		damage the victim by {_bypassdamage.%attacker%} * 0.75
		push the victim backwards at speed 0.75
		damage the attacker's tool by 1
	if {_LB} is true:
		add {_lunarnull} to {defbuff.%victim%}
	if {_perk} is 1:
		add 50 to {sklbuff.%attacker%}
	if damage is less than victim's health:
		send action bar "<bold>%victim% | HP: %victim's health - damage% / %victim's maximum health% | Damage Dealt: %damage%" to the attacker
	else:
		send action bar "<gold><bold>%victim%<reset><bold> | HP: <gold><bold>0 / %victim's maximum health%<reset><bold> | Damage Dealt: %damage% | <gold><bold>Overkill: %abs(victim's health - damage)%" to the attacker
	#Galeforce
	if the 5th line of the lore of attacker's tool contains "Special - Galeforce":
		set {_level} to ({skl.%attacker%} + {sklbuff.%attacker%}) ^ 0.6
		if {_level} is more than 50:
			set {_level} to 50
		if the 6th line of the lore of the attacker's tool contains "<green><bold>Refined: Slaying":
			set {_level} to {_level} + 10
		if the 6th line of the lore of the attacker's tool contains "<purple><bold>Refined: Crushing":
			add {crushing.%attacker%} to {_level}
		chance of {_level}%:
			apply swiftness 8 to the attacker for 30 seconds
			apply strength 1 to the attacker for 30 seconds
			subtract 100 from {sklbuff.%attacker%}
			if the 6th line of the lore of the attacker's tool contains "<gold><bold>Refined: Koenig":
				set damage to damage + 2.5
			clear {crushing.%attacker%}
			send "<gold>Galeforce was activated!" to attacker
			show witch spell on the victim
			play sound "entity.zombie_villager.cure" with volume 0.25 and pitch 1.5 at victim for attacker
			wait 30 seconds
			add 100 to {sklbuff.%attacker%}
	if {_bb.%victim%} is true:
		set {strbuff.%victim%} to {_oldstr.%victim%}
		set {defbuff.%victim%} to {_olddef.%victim%}
		set {spdbuff.%victim%} to {_oldspd.%victim%}
		set {resbuff.%victim%} to {_oldres.%victim%}
		set {sklbuff.%victim%} to {_oldskl.%victim%}
	if {_bb.%attacker%} is true:
		set {strbuff.%attacker%} to {_oldstr}
		set {defbuff.%attacker%} to {_olddef}
		set {spdbuff.%attacker%} to {_oldspd}
		set {resbuff.%attacker%} to {_oldmag}
		set {sklbuff.%attacker%} to {_oldskl}

on right click:
	#Fortify Health
	if the 2nd line of the lore of player's tool contains "Slot B - Fortify Health":
		apply absorption 2 to the player for 75 seconds
		damage player's tool by 75
	#Restore
	if the 2nd line of the lore of player's tool contains "Slot B - Restore":
		apply regeneration 3 to the player for 2 seconds
		damage player's tool by 15
	#Wings of Mercy
	if the 2nd line of the lore of the player's tool contains "Slot B - Wings of Mercy":
		set {_health} to {support.%player%}'s health
		if {_health} is less than {support.%player%}'s maximum health / 2:
			teleport the player to {support.%player%}
			send "%player% has arrived with Wings of Mercy!" to {support.%player%}
			set {_sklcheck.%player%} to checkSlots(player,"Everlasting Bond")
			if {_sklcheck.%player%} is 1:
				send "Everlasting Bond granted you STR/DEF +15 for 10 seconds!" to the player
				add 15 to {strbuff.%player%}
				add 15 to {defbuff.%player%}
				wait 10 seconds
				subtract 15 from {strbuff.%player%}
				subtract 15 from {strbuff.%player%}
		else if {bleedout.%{support.%player%}%} is 1:
			teleport the player to {support.%player%}
			send "%player% has arrived with Wings of Mercy!" to {support.%player%}
			set {_sklcheck.%player%} to checkSlots(player,"Everlasting Bond")
			if {_sklcheck.%player%} is 1:
				send "Everlasting Bond granted you STR/DEF +15 for 10 seconds!" to the player
				add 15 to {strbuff.%player%}
				add 15 to {defbuff.%player%}
				wait 10 seconds
				subtract 15 from {strbuff.%player%}
				subtract 15 from {strbuff.%player%}
		else:
			send "<red>HP Threshold not met!" to the player
	#Escape Route
	if the 2nd line of the lore of the player's tool contains "Slot B - Escape Route":
		if player's health is less than (player's maximum health / 2):
			teleport the player to {support.%player%}
			set {_slot} to checkSlots(player,"Everlasting Bond")
			if {_slot} is 1:
				add 15 to {strbuff.%{support.%player%}%}
				add 15 to {defbuff.%{support.%player%}%}
				send "%player%'s Everlasting Bond granted you STR/DEF +15 for 10 seconds!" to {support.%player%}
				wait 10 seconds
				subtract 15 from {strbuff.%{support.%player%}%}
				subtract 15 from {defbuff.%{support.%player%}%}
			send "%player% has arrived with Escape Route!" to {support.%player%}
		else if {bleedout.%player%} is 1:
			teleport the player to {support.%player%}
			set {_slot} to checkSlots(player,"Everlasting Bond")
			if {_slot} is 1:
				add 15 to {strbuff.%{support.%player%}%}
				add 15 to {defbuff.%{support.%player%}%}
				send "%player%'s Everlasting Bond granted you STR/DEF +15 for 10 seconds!" to {support.%player%}
				wait 10 seconds
				subtract 15 from {strbuff.%{support.%player%}%}
				subtract 15 from {defbuff.%{support.%player%}%}
			send "%player% has arrived with Escape Route" to {support.%player%}
		else:
			send "<red>HP Threshold not met!" to the player
			

on right click on an entity:
	#Rally Speed
	if the 2nd line of the lore of player's tool contains "Slot B - Rally Speed":
		apply speed 1 to the target for 60 seconds
		damage the player's tool by 10
	#Rally Strength
	else if the 2nd line of the lore of player's tool contains "Slot B - Rally Strength":
		apply strength 1 to the target for 60 seconds
		damage the player's tool by 10
	#Rally Defence
	else if the 2nd line of the lore of player's tool contains "Slot B - Rally Defence":
		apply resistance 1 to the target for 60 seconds
		damage the player's tool by 10
	#Rally Spectrum
	else if the 2nd line of the lore of player's tool contains "Slot B - Rally Spectrum":
		apply resistance 1 to the target for 60 seconds
		apply strength 1 to the target for 60 seconds
		apply speed 1 to the target for 60 seconds
		damage the player's tool by 30	
	#Shove
	else if the 2nd line of the lore of player's tool contains "Slot B - Shove":
		push the target backwards at speed 0.5
		push the target upwards at speed 0.5
		damage the player's tool by 1
		if {combo.%player%} is more than 6:
			add 5 to {combo.%player%}
	#Launcher
	else if the 2nd line of the lore of player's tool contains "Slot B - Launcher":
		damage the target by 1
		push the target upwards at speed 1.5
		if player is sneaking:
			push the player upwards at speed 1.5
		damage the player's tool by 1
		add 10 to {combo.%player%}
	#Ardent Sacrifice
	else if the 2nd line of the lore of player's tool contains "Slot B - Ardent Sacrifice":
		heal the target by 4 hearts
		damage the player by 4 hearts
		make target say "%{healedQuote.%target%}%"
	#Swap
	else if the 2nd line of the lore of player's tool contains "Slot B - Swap":
		teleport the player to the target
		push the player forwards at speed 0.5
		push the target backwards at speed 0.5
	#Stomp
	else if the 2nd line of the lore of the player's tool contains "Slot B - Stomp":
		push the target downwards at speed 3
		if {combo.%player%} is more than 6:
			add 6 to {combo.%player%}
	#Reposition
	else if the 2nd line of the lore of the player's tool contains "Slot B - Reposition":
		teleport the target to the player
		push the target backwards at speed 1

#Defiant Skills
on heal:
	if player's health is less than (player's max health * 0.5):
		if the 1st line of the lore of the player's tool contains "Slot A - Defiant Attack":
			remove strength from the player
			apply strength 4 to the player for 90 seconds
			show mob spawner flames on the player
			set {defiantbuff.%player%} to 1
		if the 1st line of the lore of the player's tool contains "Slot A - Defiant Speed":
			remove speed from the player
			apply speed 4 to the player for 90 seconds
			show mob spawner flames on the player
			set {defiantbuff.%player%} to 1
		if the 1st line of the lore of the player's tool contains "Slot A - Defiant Resistance":
			remove resistance from the player
			apply resistance 4 to the player for 90 seconds
			show mob spawner flames on the player
			set {defiantbuff.%player%} to 1
		else if the 2nd line of the lore of the player's tool contains "Slot B - Wrath":
			set {wrathbuff.%player%} to 1
			show mob spawner flames on the player
	else if {defiantbuff.%player%} is 1:
		remove strength from the player
		remove speed from the player
		remove resistance from the player
		send "<light red>Defiant Skill bonus deactivated!" to the player
		set {defiantbuff.%player%} to 0
	else if {wrathbuff.%player%} is 1:
		subtract 30 from {sklbuff.%player%}
		set {wrathbuff.%player%} to 0
		send "<light red>Wrath bonus deactivated!" to the player
	

on damage of a player:
	if (victim's health - final damage) is less than or equal to (victim's max health * 0.5):
		if {defiantbuff.%victim%} is not 1:
			if the 1st line of the lore of the victim's tool contains "Slot A - Defiant Attack":
				remove strength from the victim
				apply strength 4 to the victim for 90 seconds
				show mob spawner flames on the victim
				set {defiantbuff.%victim%} to 1
				send "<yellow>Defiant Attack bonus now active!" to the victim
			if the 1st line of the lore of the victim's tool contains "Slot A - Defiant Speed":
				remove speed from the victim
				apply speed 4 to the victim for 90 seconds
				show mob spawner flames on the victim
				set {defiantbuff.%victim%} to 1
				send "<yellow>Defiant Speed bonus now active!" to the victim
			if the 1st line of the lore of the victim's tool contains "Slot A - Defiant Resistance":
				remove resistance from the victim
				apply resistance 4 to the victim for 90 seconds
				show mob spawner flames on the victim
				set {defiantbuff.%victim%} to 1
				send "<yellow>Defiant Resistance bonus now active!" to the victim
		if {wrathbuff.%victim%} is not 1:
			if the 2nd line of the lore of the victim's tool contains "Slot B - Wrath":
				add 30 to {sklbuff.%victim%}
				show mob spawner flames on the victim
				set {wrathbuff.%victim%} to 1
				send "<yellow>Wrath is now active!" to the victim

#Misc
on death:
	#Glory Kill
	if the attacker is a player:
		if the 1st line of the lore of the attacker's chestplate contains "Slot A - Glory Kills":
			if the attacker's held item is empty:
				remove speed from the attacker
				remove haste from the attacker
				remove resistance from the attacker
				remove strength from the attacker
				wait a tick
				heal the attacker by 1
				increase the attacker's food level by 1
				apply speed 2 to the attacker for 6 seconds
				apply haste 4 to the attacker for 6 seconds
				apply resistance 1 to the attacker for 6 seconds
				apply strength 1 to the attacker for 6 seconds
				send "<red><bold>GLORY KILL!" to the attacker
				play sound "entity.generic.explode" with volume 1 and pitch 1 at victim for attacker
				play 60 (red wool break with speed 2) at the victim
#Experience Sapper
on death of a monster:
	if attacker is player:
		if the 2nd line of the lore of the attacker's tool contains "Slot B - Experience Sapper":
			set {_xp} to ceil(attacker's level ^ 1.05)
			make console execute command "/xp %{_xp}% %attacker%"
			send "<light green>Gained a bonus %{_xp}% experience!" to the attacker
		#Plentitude
		else if the 2nd line of the lore of the attacker's tool contains "Slot B - Plentitude":
			chance of (30 + ({res.%attacker%} / 2))%:
				drop 1 steak at the victim
				increase the player's food level by 1
				send "<yellow>Plentitude activated!" to the attacker
		#Despoil
		else if the 2nd line of the lore of the attacker's tool contains "Slot B - Despoil":
			chance of (10 + ({res.%attacker%} / 2))%:
				give paper named "<light green><bold>Bullion (S)" with lore "<white>Right-click to gain $25!" to the attacker
			chance of (5 + ({res.%attacker%} / 2))%:
				give paper named "<light green><bold>Bullion (M)" with lore "<white>Right-click to gain $50!" to the attacker
			chance of (1 + ({res.%attacker%} / 2))%:
				give paper named "<light green><bold>Bullion (L)" with lore "<white>Right-click to gain $75!" to the attacker
			chance of ({res.%attacker%} / 2)%:
				give paper named "<light green><bold>Bullion (XL)" with lore "<white>Right-click to gain $100!" to the attacker
			
#Quick Draw
on right click with bow:
	if the 1st line of the lore of the player's tool contains "Slot A - Quick Draw":
		if the player has an arrow:
			make the player shoot an arrow at speed 1.25
			remove 1 arrow from the player
			damage the player's tool by 1
			play sound "block.dispenser.launch" with volume 1 and pitch 1 at the player
		else:
			cancel event
		
on damage:
	#Sandbag
	if the name of the victim contains "<gold><bold>Sandbag":
		if {sandbagkillable.%attacker%} is 0:
			set {_finaldamage.%attacker%} to final damage
			send "<light blue>Damage dealt that hit: %{_finaldamage.%attacker%}% hearts" to the attacker
			cancel event