command /cheats <text>:
	trigger:
		if arg 1 is "unlockallthings":
			finishQuest(player,"Knights of Silgrid","")
			finishQuest(player,"Days of Training","")
			finishQuest(player,"Proving Grounds","")
			finishQuest(player,"Home Sweet Home","")
			finishQuest(player,"A Scarred Land","")
			finishQuest(player,"A History Lesson","")
			finishQuest(player,"Seeking the Light","")
			finishQuest(player,"Greats Guide You","")
			finishQuest(player,"Journey to Nifl","")
			finishQuest(player,"A Lord's Worth","")
			finishQuest(player,"Awakening","")
			finishQuest(player,"Liberation","")
			finishQuest(player,"A Deadly Test of Might","")
			finishQuest(player,"Revelations","")
			finishQuest(player,"A Hero's Destiny","")
			finishQuest(player,"Land of Shadow","")
			finishQuest(player,"Inheritors of Light","")
			finishQuest(player,"Light and Shadow","")
			finishQuest(player,"Legacy","")
			finishQuest(player,"A Villager's Request","")
			finishQuest(player,"Invisible Ties","")
			finishQuest(player,"Fuel for the Fire","")
			finishQuest(player,"Monster Hunt","")
			finishQuest(player,"Path of the Greats","")
			finishQuest(player,"The Wizard of House Silgrid","")
			finishQuest(player,"Legend in the Making","")
			finishQuest(player,"Search and Destroy","")
			finishQuest(player,"A Hero Rises","")
			finishQuest(player,"Breaking the Ice","")
			#set {generation.%player%} to 2
			set {unlockedClasses.%player%::Dragonborn} to true
			set {unlockedClasses.%player%::Gunslinger} to true
			set {unlockedClasses.%player%::Devil Hunter} to true
			set {unlockedClasses.%player%::Survivor} to true
			set {unlockedClasses.%player%::Summoner} to true
			set {unlockedClasses.%player%::Strategist} to true
			set {unlockedClasses.%player%::Trickster} to true
			set {unlockedClasses.%player%::Keeper} to true
			set {unlockedClasses.%player%::Charlatan} to true
			set {unlockedClasses.%player%::Poet} to true
			set {unlockedClasses.%player%::Outlaw} to true
			set {unlockedClasses.%player%::Conjurer} to true
			set {unlockedClasses.%player%::Troubador} to true
			set {mqComplete.%player%} to true
			send formatted "<gold>All items unlocked!"
		else if arg 1 is "unlockallclasses":
			set {unlockedClasses.%player%::Dragonborn} to true
			set {unlockedClasses.%player%::Gunslinger} to true
			set {unlockedClasses.%player%::Devil Hunter} to true
			set {unlockedClasses.%player%::Survivor} to true
			set {unlockedClasses.%player%::Summoner} to true
			set {unlockedClasses.%player%::Strategist} to true
			set {unlockedClasses.%player%::Trickster} to true
			set {unlockedClasses.%player%::Keeper} to true
			set {unlockedClasses.%player%::Charlatan} to true
			set {unlockedClasses.%player%::Poet} to true
			set {unlockedClasses.%player%::Outlaw} to true
			set {unlockedClasses.%player%::Conjurer} to true
			set {unlockedClasses.%player%::Troubador} to true
			send formatted "<gold>All classes now available!"
		else if arg 1 is "unlockgen1":
			finishQuest(player,"Legend in the Making","")
			finishQuest(player,"Search and Destroy","")
			finishQuest(player,"A Hero Rises","")
			finishQuest(player,"Breaking the Ice","")
		#else if arg 1 is "idkfa":
		#	set {weaponranks.%player%::swords} to "<gold><bold>SS"
		#	set {weaponranks.%player%::lances} to "<gold><bold>SS"
		#	set {weaponranks.%player%::axes} to "<gold><bold>SS"
		#	set {weaponranks.%player%::bows} to "<gold><bold>SS"
		#	set {weaponranks.%player%::magic} to "<gold><bold>SS"
		#	set {weaponranks.%player%::staves} to "<gold><bold>SS"
		#	set {weaponrank.%player%::swords} to 999999
		#	set {weaponrank.%player%::lances} to 999999
		#	set {weaponrank.%player%::axes} to 999999
		#	set {weaponrank.%player%::bows} to 999999
		#	set {weaponrank.%player%::magic} to 999999
		#	set {weaponrank.%player%::staves} to 9999999
		#	send formatted "<gold>All weapons can now be wielded!"
		else if arg 1 is "rosebud":
			add 1000 to the player's balance
			send formatted "<gold>$1000 obtained!"
		else if arg 1 is "gearup":
			give 1 iron sword to the player
			give 1 iron helmet to the player
			give 1 iron chestplate to the player
			give 1 iron leggings to the player
			give 1 iron boots to the player
			give 1 bow to the player
			give 64 arrow to the player
			send formatted "<gold>Ready for adventure!"
		else if arg 1 is "diamondlife":
			give 1 diamond sword of sharpness 10 to the player
			give 1 diamond helmet of protection 10 to the player
			give 1 diamond chestplate of protection 10 to the player
			give 1 diamond leggings of protection 10 to the player
			give 1 diamond boots of protection 10 to the player
			give 1 bow of power 10 to the player
			give 64 arrow to the player
			send formatted "<gold>Cover me in diamond!"
		else if arg 1 is "blingbling":
			open chest inventory with 2 rows named "<gold><bold>Select a ring." for the player
			set slot 0 of the player's current inventory to 1 music disc far with name "<light green><bold>Life Ring" with lore "<white>While in your inventory:", "<light green>Recover 10%% of your max HP every 15 seconds."
			set slot 1 of the player's current inventory to 1 music disc wait named "<light blue><bold>Elite Ring" with lore "<white>While in your inventory:", "<light blue>Gain bonus experience for slaying monsters."
			set slot 2 of the player's current inventory to 1 music disc 13 named "<yellow><bold>Thief Ring" with lore "<white>While in your inventory:", "<yellow>Slain monsters have a chance to drop extra money."
			set slot 3 of the player's current inventory to 1 music disc mall named "<light purple><bold>Return Ring" with lore "<white>While in your inventory:", "<light purple>Teleport to a custom location.", "<light purple>Hold Sneak and Right-click to set the warp destination.", "<light purple>Right-click without sneaking to warp."
			set slot 4 of the player's current inventory to 1 music disc wait named "<light cyan><bold>Speed Ring" with lore "<white>While in your inventory:", "<light cyan>Grants Swiftness 2."
			set slot 5 of the player's current inventory to 1 music disc chirp named "<light red><bold>Power Ring" with lore "<white>While in your inventory:", "<light green>Grants Strength 2."
			set slot 6 of the player's current inventory to 1 music disc strad named "<white><bold>Shield Ring" with lore "<white>While in your inventory:", "<white>Grants Resistance 2."
			set slot 7 of the player's current inventory to 1 music disc 13 named "<orange><bold>Prayer Ring" with lore "<white>While in your inventory:", "<orange>Attacks while below 50%% health will always be critical hits."
			set slot 8 of the player's current inventory to 1 music disc cat named "<green><bold>Pursuit Ring" with lore "<white>While in your inventory:", "<green>Automatically perform a follow-up attack in combat.", "<green>Auto follow-ups deal 50%% less damage."
		#else if arg 1 is "inamerica":
		#	set {perdiff.%player%} to "Thracian"
		#	send formatted "<light green>Personal Difficulty increased to Thracian!"
		#	send formatted "<light yellow>On Thracian difficulty, your attacks have a chance to miss based on your SPD and SKL."
		#	send formatted "<light yellow>Lunatic damage multipliers are also active."
		else if arg 1 is "thedarksoulsofminecraftservers":
			give 1 diamond sword named "<gold><bold>Estoc" with lore "<light red><bold>Slot A - Power Within", "<light blue><bold>Slot B - Bonus Blade", "<light yellow><bold>Slot C - Bold Fighter", "<light green><bold>Assist - Stinger", "<light purple><bold>Special - Dragon Fang", "<light red><bold>Refined - Reinforced", "<white>Grants bonus damage equal to 25%% of your STR.", "<white>Nullifies foe's bonuses granted by armour." to the player
			send "<light green><bold>Obtained <reset><gold><bold>Estoc<reset><light green><bold>!" to the player
		else if arg 1 is "sigurd":
			set {t_overrideGauge.%player%} to 100
			set bossbar "override.%player's uuid%" progress to {t_overrideGauge.%player%}
		else if arg 1 is "gimmetrickperks":
			set {perkTreeXP.Trickster.%player%::Trickster_TREE_01} to 99999
			set {perkTreeXP.Trickster.%player%::Trickster_TREE_02} to 99999
			set {perkTreeXP.Trickster.%player%::Trickster_TREE_03} to 99999
			set {perkTreeXP.Trickster.%player%::Global} to 99999
			send "<gold>All trickster perks are now unlocked."
		else if arg 1 is "bookworm":
			set {perkTreeXP.Mercenary.%player%::Fortitude} to 99999
			set {perkTreeXP.Mercenary.%player%::Camraderie} to 99999
			set {perkTreeXP.Mercenary.%player%::Courage} to 99999
			set {perkTreeXP.Mercenary.%player%::Global} to 99999
			set {perkTreeXP.Knight.%player%::Reliability} to 99999
			set {perkTreeXP.Knight.%player%::Perserverance} to 99999
			set {perkTreeXP.Knight.%player%::Pessimism} to 99999
			set {perkTreeXP.Knight.%player%::Global} to 99999
			set {perkTreeXP.Bladesman.%player%::Intuition} to 99999
			set {perkTreeXP.Bladesman.%player%::Zeal} to 99999
			set {perkTreeXP.Bladesman.%player%::Daring} to 99999
			set {perkTreeXP.Bladesman.%player%::Global} to 99999
			set {perkTreeXP.Fighter.%player%::Heroism} to 99999
			set {perkTreeXP.Fighter.%player%::Flexibility} to 99999
			set {perkTreeXP.Fighter.%player%::Confidence} to 99999
			set {perkTreeXP.Fighter.%player%::Global} to 99999
			set {perkTreeXP.Mage.%player%::Serenity} to 99999
			set {perkTreeXP.Mage.%player%::Wisdom} to 99999
			set {perkTreeXP.Mage.%player%::Diligence} to 99999
			set {perkTreeXP.Mage.%player%::Global} to 99999
			set {perkTreeXP.Cleric.%player%::Loyalty} to 99999
			set {perkTreeXP.Cleric.%player%::Pacifism} to 99999
			set {perkTreeXP.Cleric.%player%::Hypocrisy} to 99999
			set {perkTreeXP.Cleric.%player%::Global} to 99999
			set {perkTreeXP.Archer.%player%::Recitence} to 99999
			set {perkTreeXP.Archer.%player%::Prudence} to 99999
			set {perkTreeXP.Archer.%player%::Spirit} to 99999
			set {perkTreeXP.Archer.%player%::Global} to 99999
			set {perkTreeXP.Cavalier.%player%::Enthusiasm} to 99999
			set {perkTreeXP.Cavalier.%player%::Adeptness} to 99999
			set {perkTreeXP.Cavalier.%player%::Steadfastness} to 99999
			set {perkTreeXP.Cavalier.%player%::Global} to 99999
			set {perkTreeXP.Devil Hunter.%player%::Confidence} to 99999
			set {perkTreeXP.Devil Hunter.%player%::Stoicism} to 99999
			set {perkTreeXP.Devil Hunter.%player%::Impulsiveness} to 99999
			set {perkTreeXP.Devil Hunter.%player%::Global} to 99999
			set {perkTreeXP.Gunslinger.%player%::GUNSLINGER_TREE_01} to 99999
			set {perkTreeXP.Gunslinger.%player%::GUNSLINGER_TREE_02} to 99999
			set {perkTreeXP.Gunslinger.%player%::GUNSLINGER_TREE_03} to 99999
			set {perkTreeXP.Gunslinger.%player%::Global} to 99999
			set {perkTreeXP.Strategist.%player%::STRATEGIST_TREE_01} to 99999
			set {perkTreeXP.Strategist.%player%::STRATEGIST_TREE_02} to 99999
			set {perkTreeXP.Strategist.%player%::STRATEGIST_TREE_03} to 99999
			set {perkTreeXP.Strategist.%player%::Global} to 99999
			set {perkTreeXP.Survivor.%player%::SURVIVOR_TREE_01} to 99999
			set {perkTreeXP.Survivor.%player%::SURVIVOR_TREE_02} to 99999
			set {perkTreeXP.Survivor.%player%::SURVIVOR_TREE_03} to 99999
			set {perkTreeXP.Survivor.%player%::Global} to 99999
			set {perkTreeXP.Charlatan.%player%::Illumination} to 99999
			set {perkTreeXP.Charlatan.%player%::Experimentation} to 99999
			set {perkTreeXP.Charlatan.%player%::Condemnation} to 99999
			set {perkTreeXP.Charlatan.%player%::Global} to 99999
			set {perkTreeXP.Troubador.%player%::Adeptness} to 99999
			set {perkTreeXP.Troubador.%player%::Faithfulness} to 99999
			set {perkTreeXP.Troubador.%player%::Versatility} to 99999
			set {perkTreeXP.Troubador.%player%::Global} to 99999
			set {perkTreeXP.Outlaw.%player%::Secrecy} to 99999
			set {perkTreeXP.Outlaw.%player%::Lawlessness} to 99999
			set {perkTreeXP.Outlaw.%player%::Mercilessness} to 99999
			set {perkTreeXP.Outlaw.%player%::Global} to 99999
			set {perkTreeXP.Conjurer.%player%::Vendetta} to 99999
			set {perkTreeXP.Conjurer.%player%::Wisdom} to 99999
			set {perkTreeXP.Conjurer.%player%::Chaos} to 99999
			set {perkTreeXP.Conjurer.%player%::Global} to 99999	
			set {perkTreeXP.Poet.%player%::Rythm} to 99999
			set {perkTreeXP.Poet.%player%::Tempo} to 99999
			set {perkTreeXP.Poet.%player%::Melody} to 99999
			set {perkTreeXP.Poet.%player%::Global} to 99999
			set {perkTreeXP.Keeper.%player%::Deflection} to 99999
			set {perkTreeXP.Keeper.%player%::Perserverance} to 99999
			set {perkTreeXP.Keeper.%player%::Protection} to 99999
			set {perkTreeXP.Keeper.%player%::Global} to 99999			
			set {perkTreeXP.Trickster.%player%::Trickster_TREE_01} to 99999
			set {perkTreeXP.Trickster.%player%::Trickster_TREE_02} to 99999
			set {perkTreeXP.Trickster.%player%::Trickster_TREE_03} to 99999
			set {perkTreeXP.Trickster.%player%::Global} to 99999
			send "<gold>All class perk trees are now unlocked."
		else:
			send formatted "<light red>Your code was not recognized."
		