function humanoidEquipmentHandler(MOB: entity, LVL: number, RANGE: number):
	if {_RANGE} is 0:
		chance of ({_LVL} + 100)%:
			set {_MOB}'s tool to 1 wooden sword
		chance of ({_LVL} + 70)%:
			set {_MOB}'s tool to 1 stone sword
		chance of ({_LVL} + 30)%:
			set {_MOB}'s tool to 1 iron sword
		chance of ({_LVL} + 10)%:
			set {_MOB}'s tool to 1 diamond sword
	else if {_RANGE} is 1:
		set {_MOB}'s tool to 1 bow
		chance of ({_LVL} + 70)%:
			enchant {_MOB}'s tool with power 1
		chance of ({_LVL} + 40)%:
			enchant {_MOB}'s tool with power 2
		chance of ({_LVL} + 20)%:
			enchant {_MOB}'s tool with power 3
			enchant {_MOB}'s tool with punch 1
		chance of ({_LVL} + 5)%:
			enchant {_MOB}'s tool with power 4
			enchant {_MOB}'s tool with punch 2
	chance of ({_LVL} ^ 0.9)%:
		set line 1 of {_MOB}'s tool's lore to getASlotSkill({_RANGE})
	chance of ({_LVL} ^ 0.8)%:
		set line 2 of {_MOB}'s tool's lore to getBSlotSkill({_RANGE})
	chance of ({_LVL} ^ 0.8)%:
		set line 3 of {_MOB}'s tool's lore to getCSlotSkill({_RANGE})
	chance of ({_LVL} ^ 0.8)%:
		set line 4 of {_MOB}'s tool's lore to getAssistSlotSkill({_RANGE})
	chance of ({_LVL} ^ 0.7)%:
		set line 5 of {_MOB}'s tool's lore to getSpecialSlotSkill({_RANGE})
	chance of ({_LVL} ^ 0.65)%:
		set line 6 of {_MOB}'s tool's lore to getRefineSlotSkill({_RANGE})
		
function getASlotSkill(RANGE: number) :: text:
	set {_RN} to a random integer from 1 to 42
	if {_RN} is 1:
		if {_RANGE} is 0:
			return "<light red><bold>Slot A - Distant Counter"
		else:
			return "<light red><bold>Slot A - Close Counter"
	else if {_RN} is 2:
		if {_RANGE} is 0:
			return "<light red><bold>Slot A - Warp Strike"
		else:
			return "<light red><bold>Slot A - Quick Draw"
	else if {_RN} is 3:
		return "<light red><bold>Slot A - Armour Smasher"
	else if {_RN} is 4:
		return "<light red><bold>Slot A - Fury"
	else if {_RN} is 5:
		return "<light red><bold>Slot A - Life and Death"
	else if {_RN} is 6:
		return "<light red><bold>Slot A - Death Blow"
	else if {_RN} is 7:
		return "<light red><bold>Slot A - Darting Blow"
	else if {_RN} is 8:
		return "<light red><bold>Slot A - Armoured Blow"
	else if {_RN} is 9:
		return "<light red><bold>Slot A - Defiant Attack"
	else if {_RN} is 10:
		return "<light red><bold>Slot A - Defiant Speed"
	else if {_RN} is 11:
		return "<light red><bold>Slot A - Defiant Resistance"
	else if {_RN} is 12:
		return "<light red><bold>Slot A - Close Defence"
	else if {_RN} is 13:
		return "<light red><bold>Slot A - Distant Defence"
	else if {_RN} is 14:
		return "<light red><bold>Slot A - STR/SKL Bond"
	else if {_RN} is 15:
		return "<light red><bold>Slot A - DEF/MAG Bond"
	else if {_RN} is 16:
		return "<light red><bold>Slot A - DEF/SKL Bond"
	else if {_RN} is 17:
		return "<light red><bold>Slot A - MAG/SKL Bond"
	else if {_RN} is 18:
		return "<light red><bold>Slot A - STR/MAG Bond"
	else if {_RN} is 19:
		return "<light red><bold>Slot A - STR/DEF Bond"
	else if {_RN} is 20:
		return "<light red><bold>Slot A - STR/SKL Solo"
	else if {_RN} is 21:
		return "<light red><bold>Slot A - DEF/MAG Solo"
	else if {_RN} is 22:
		return "<light red><bold>Slot A - DEF/SKL Solo"
	else if {_RN} is 23:
		return "<light red><bold>Slot A - MAG/SKL Solo"
	else if {_RN} is 24:
		return "<light red><bold>Slot A - STR/MAG Solo"
	else if {_RN} is 25:
		return "<light red><bold>Slot A - STR/DEF Solo"
	else if {_RN} is 26:
		return "<light red><bold>Slot A - Sorcery Aura"
	else if {_RN} is 27:
		return "<light red><bold>Slot A - Steady Stance"
	else if {_RN} is 28:
		return "<light red><bold>Slot A - Fierce Stance"
	else if {_RN} is 29:
		return "<light red><bold>Slot A - Warding Stance"
	else if {_RN} is 30:
		return "<light red><bold>Slot A - Swift Stance"
	else if {_RN} is 31:
		return "<light red><bold>Slot A - Swift Sparrow"
	else if {_RN} is 32:
		return "<light red><bold>Slot A - Steady Blow"
	else if {_RN} is 33:
		return "<light red><bold>Slot A - Power Within"
	else if {_RN} is 34:
		return "<light red><bold>Slot A - STR Focus"
	else if {_RN} is 35:
		return "<light red><bold>Slot A - DEF Focus"
	else if {_RN} is 36:
		return "<light red><bold>Slot A - SKL Focus"
	else if {_RN} is 37:
		return "<light red><bold>Slot A - DEF Focus"
	else if {_RN} is 38:
		return "<light red><bold>Slot A - MAG Focus"
	else if {_RN} is 39:
		return "<light red><bold>Slot A - Warding Blow"
	else if {_RN} is 40:
		return "<light red><bold>Slot A - Mirror Force"
	else if {_RN} is 41:
		return "<light red><bold>Slot A - Flashing Blade"
	else if {_RN} is 42:
		return "<light red><bold>Slot A - Heavy Blade"
		
function getBSlotSkill(RANGE: number) :: text:
	set {_RN} to a random integer from 1 to 28
	if {_RN} is 1:
		return "<light blue><bold>Slot B - Sabotage Attack"
	else if {_RN} is 2:
		return "<light blue><bold>Slot B - Sabotage Defense"
	else if {_RN} is 3:
		return "<light blue><bold>Slot B - Sabotage Speed"
	else if {_RN} is 4:
		return "<light blue><bold>Slot B - Poison Strike"
	else if {_RN} is 5:
		return "<light blue><bold>Slot B - Desperation"
	else if {_RN} is 6:
		return "<light blue><bold>Slot B - Riposte"
	else if {_RN} is 7:
		return "<light blue><bold>Slot B - Brash Assault"
	else if {_RN} is 8:
		return "<light blue><bold>Slot B - Wrath"
	else if {_RN} is 9:
		return "<light blue><bold>Slot B - Plenitude"
	else if {_RN} is 10:
		return "<light blue><bold>Slot B - Experience Sapper"
	else if {_RN} is 11:
		return "<light blue><bold>Slot B - Shield Pulse"
	else if {_RN} is 12:
		return "<light blue><bold>Slot B - Bonus Blade"
	else if {_RN} is 13:
		return "<light blue><bold>Slot B - Brave Blade"
	else if {_RN} is 14:
		return "<light blue><bold>Slot B - Eclipse Brace"
	else if {_RN} is 15:
		return "<light blue><bold>Slot B - Solar Brace"
	else if {_RN} is 16:
		return "<light blue><bold>Slot B - Guard"
	else if {_RN} is 17:
		return "<light blue><bold>Slot B - Special Spiral"
	else if {_RN} is 18:
		return "<light blue><bold>Slot B - Mystic Boost"
	else if {_RN} is 19:
		return "<light blue><bold>Slot B - Windsweep"
	else if {_RN} is 20:
		return "<light blue><bold>Slot B - Flame Boost"
	else if {_RN} is 21:
		return "<light blue><bold>Slot B - Earth Boost"
	else if {_RN} is 22:
		return "<light blue><bold>Slot B - Aqua Boost"
	else if {_RN} is 23:
		return "<light blue><bold>Slot B - Vantage"
	else if {_RN} is 24:
		return "<light blue><bold>Slot B - Seal SPD/SKL"
	else if {_RN} is 25:
		return "<light blue><bold>Slot B - Seal DEF/MAG"
	else if {_RN} is 26:
		return "<light blue><bold>Slot B - Despoil"
	else if {_RN} is 27:
		return "<light blue><bold>Slot B - Escape Route"
	else if {_RN} is 28:
		return "<light blue><bold>Slot B - Wings of Mercy"
		
function getCSlotSkill(RANGE: number) :: text:
	set {_RN} to a random integet from 1 to 32
	if {_RN} is 1:
		return "<light yellow><bold>Slot C - Hone STR"
	else if {_RN} is 2:
		return "<light yellow><bold>Slot C - Hone SPD"
	else if {_RN} is 3:
		return "<light yellow><bold>Slot C - Hone SKL"
	else if {_RN} is 4:
		return "<light yellow><bold>Slot C - Hone DEF"
	else if {_RN} is 5:
		return "<light yellow><bold>Slot C - Hone MAG"
	else if {_RN} is 6:
		return "<light yellow><bold>Slot C - Drive STR"
	else if {_RN} is 7:
		return "<light yellow><bold>Slot C - Drive SPD"
	else if {_RN} is 8:
		return "<light yellow><bold>Slot C - Drive SKL"
	else if {_RN} is 9:
		return "<light yellow><bold>Slot C - Drive DEF"
	else if {_RN} is 10:
		return "<light yellow><bold>Slot C - Drive MAG"
	else if {_RN} is 11:
		return "<light yellow><bold>Slot C - STR Smoke"
	else if {_RN} is 12:
		return "<light yellow><bold>Slot C - DEF Smoke"
	else if {_RN} is 13:
		return "<light yellow><bold>Slot C - SPD Smoke"
	else if {_RN} is 14:
		return "<light yellow><bold>Slot C - SKL Smoke"
	else if {_RN} is 15:
		return "<light yellow><bold>Slot C - MAG Smoke"
	else if {_RN} is 16:
		return "<light yellow><bold>Slot C - Breath of Life"
	else if {_RN} is 17:
		return "<light yellow><bold>Slot C - Savage Blow"
	else if {_RN} is 18:
		return "<light yellow><bold>Slot C - Pressure STR"
	else if {_RN} is 19:
		return "<light yellow><bold>Slot C - Pressure SPD"
	else if {_RN} is 20:
		return "<light yellow><bold>Slot C - Pressure SKL"
	else if {_RN} is 21:
		return "<light yellow><bold>Slot C - Pressure DEF"
	else if {_RN} is 22:
		return "<light yellow><bold>Slot C - Pressure MAG"
	else if {_RN} is 23:
		return "<light yellow><bold>Slot C - STR Authority"
	else if {_RN} is 24:
		return "<light yellow><bold>Slot C - DEF Authority"
	else if {_RN} is 25:
		return "<light yellow><bold>Slot C - SPD Authority"
	else if {_RN} is 26:
		return "<light yellow><bold>Slot C - SKL Authority"
	else if {_RN} is 27:
		return "<light yellow><bold>Slot C - MAG Authority"
	else if {_RN} is 28:
		return "<light yellow><bold>Slot C - Gravity"
	else if {_RN} is 29:
		return "<light yellow><bold>Slot C - Bold Fighter"
	else if {_RN} is 30:
		return "<light yellow><bold>Slot C - Fear"
	else if {_RN} is 31:
		return "<light yellow><bold>Slot C - Restrict"
	else if {_RN} is 32:
		return "<light yellow><bold>Slot C - Blowback"
		
function getAssistSlotSkill(RANGE: number) :: text:
	set {_RN} to a random integer from 1 to 18
	if {_RN} is 1:
		if {_RANGE} is 0:
			return "<light green><bold>Assist - Drag Back"
		else:
			return "<light green><bold>Assist - Ethreal Grip"
	else if {_RN} is 2:
		if {_RANGE} is 0:
			return "<light green><bold>Assist - Hit and Run"
		else:
			return "<light green><bold>Assist - Ethreal Grip"
	else if {_RN} is 3:
		return "<light green><bold>Assist - Reposition"
	else if {_RN} is 4:
		return "<light green><bold>Assist - Swap"
	else if {_RN} is 5:
		return "<light green><bold>Assist - Shove"
	else if {_RN} is 6:
		return "<light green><bold>Assist - Launcher"
	else if {_RN} is 7:
		return "<light green><bold>Assist - Fortify Health"
	else if {_RN} is 8:
		return "<light green><bold>Assist - Ardent Sacrifice"
	else if {_RN} is 9:
		return "<light green><bold>Assist - Restore"
	else if {_RN} is 10:
		return "<light green><bold>Assist - Rally Speed"
	else if {_RN} is 11:
		return "<light green><bold>Assist - Rally Strength"
	else if {_RN} is 12:
		return "<light green><bold>Assist - Rally Resistance"
	else if {_RN} is 13:
		return "<light green><bold>Assist - Rally Spectrum"
	else if {_RN} is 14:
		return "<light green><bold>Assist - Stinger"
	else if {_RN} is 15:
		return "<light green><bold>Assist - Capture"
	else if {_RN} is 16:
		return "<light green><bold>Assist - Smite"
	else if {_RN} is 17:
		return "<light green><bold>Assist - Taunt"
	else if {_RN} is 18:
		return "<light green><bold>Assist - MAX-Taunt"
		
function getSpecialSlotSkill(RANGE: number) :: text:
	set {_RN} to a random integer from 1 to 18
	if {_RN} is 1:
		return "<light purple><bold>Special - Moonbow"
	else if {_RN} is 2:
		return "<light purple><bold>Special - Luna"
	else if {_RN} is 3:
		return "<light purple><bold>Special - Sol"
	else if {_RN} is 4:
		return "<light purple><bold>Special - Retribution"
	else if {_RN} is 5:
		return "<light purple><bold>Special - Pavise"
	else if {_RN} is 6:
		return "<light purple><bold>Special - Aether"
	else if {_RN} is 7:
		return "<light purple><bold>Special - Glimmer"
	else if {_RN} is 8:
		return "<light purple><bold>Special - Astra"
	else if {_RN} is 9:
		return "<light purple><bold>Special - Blazing Light"
	else if {_RN} is 10:
		return "<light purple><bold>Special - Ignis"
	else if {_RN} is 11:
		return "<light purple><bold>Special - Glacies"
	else if {_RN} is 12:
		return "<light purple><bold>Special - Rising Wind"
	else if {_RN} is 13:
		return "<light purple><bold>Special - Dragon Fang"
	else if {_RN} is 14:
		return "<light purple><bold>Special - Galeforce"
	else if {_RN} is 15:
		return "<light purple><bold>Special - Aegis"
	else if {_RN} is 16:
		return "<light purple><bold>Special - Growing Light"
	else if {_RN} is 17:
		return "<light purple><bold>Special - Miracle"
	else if {_RN} is 18:
		return "<light purple><bold>Special - Subdue"
		
function getRefineSlotSkill(RANGE: number) :: text:
	set {_RN} to a random integer from 1 to 7
	if {_RN} is 1:
		return "<green><bold>Refined: Slaying"
	else if {_RN} is 2:
		return "<red><bold>Refined: Reinforced"
	else if {_RN} is 3:
		return "<purple><bold>Refined: Crushing"
	else if {_RN} is 4:
		return "<light blue><bold>Refined: Warding"
	else if {_RN} is 5:
		return "<light red><bold>Refined: Piercing"
	else if {_RN} is 6:
		return "<gold><bold>Refined: Koenig"
	else if {_RN} is 7:
		return "<gold><bold>Refined: Stylish"
	

command /fe <number> <number>:
	description: Summon a fallen hero.
	trigger:
		set {_name} to arg 1
		if {_name} is set:
			if {_name} is 1:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Hero of Prophecy: Alm"
				set {t_str.%{_deadlord}%} to 85
				set {t_def.%{_deadlord}%} to 55
				set {t_spd.%{_deadlord}%} to 65
				set {skl.%{_deadlord}%} to 120
				set {t_res.%{_deadlord}%} to 30
				set the maximum health of {_deadlord} to 80
				set {lvl.%{_deadlord}%} to 90
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Falchion" with lore "Slot A - Armour Smasher", "Slot B - Brave Blade", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Luna", "<red><bold>Refined: Reinforced"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Lord"
				set {skillslot1.%{_deadlord}%} to "Double Lion"
				set {skillslot2.%{_deadlord}%} to "Lord's Blood"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 2:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Young Lion: Roy"
				set {t_str.%{_deadlord}%} to 65
				set {t_def.%{_deadlord}%} to 70
				set {t_spd.%{_deadlord}%} to 55
				set {skl.%{_deadlord}%} to 80
				set {t_res.%{_deadlord}%} to 85
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 85
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Binding Blade" with lore "<light red><bold>Slot A - Close Defence", "<light blue><bold>Slot B - Sabotage Attack", "<light yellow><bold>Slot C - Pressure STR", "<light green><bold>Assist - Reposition", "<light purple><bold>Special - Dragon Fang", "<bold>Refined: Unique"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Lord"
				set {skillslot1.%{_deadlord}%} to "Distant Defence"
				set {skillslot2.%{_deadlord}%} to "Sword Specialist"
				set {skillslot3.%{_deadlord}%} to "Lord's Blood"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 3:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Scarlett Sword: Navarre"
				apply swiftness 4 to the entity for 999 days
				set {t_str.%{_deadlord}%} to 120
				set {t_def.%{_deadlord}%} to 29
				set {t_spd.%{_deadlord}%} to 160
				set {skl.%{_deadlord}%} to 175
				set {t_res.%{_deadlord}%} to 25
				set {lvl.%{_deadlord}%} to 75
				set the maximum health of {_deadlord} to 60
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<red><bold>Scarlett Sword" with lore "<light red><bold>Slot A - Armour Smasher", "<light blue><bold>Slot B - Desperation", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - Rally Speed", "<light purple><bold>Special - Galeforce", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to leather helmet of protection 5
				set {_deadlord}'s chestplate to leather chestplate of protection 5
				set {_deadlord}'s leggings to leather leggings of protection 5
				set {_deadlord}'s boots to leather boots of protection 5
				set {class.%{_deadlord}%} to "Swordmaster"
				set {skillslot1.%{_deadlord}%} to "Vantage"
				set {skillslot2.%{_deadlord}%} to "Sword Specialist"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 4:
				spawn 1 skeleton at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Altean Sniper: Jeorge"
				apply swiftness 4 to the entity for 999 days
				set {t_str.%{_deadlord}%} to 120
				set {t_def.%{_deadlord}%} to 10
				set {t_spd.%{_deadlord}%} to 120
				set {skl.%{_deadlord}%} to 175
				set {t_res.%{_deadlord}%} to 10
				set {lvl.%{_deadlord}%} to 75
				set the maximum health of {_deadlord} to 70
				set {_deadlord}'s tool to bow of power 5 named "<gold><bold>Parthia" with lore "<light red><bold>Slot A - Close Counter", "<light blue><bold>Slot B - Sabotage Speed", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - None", "<light purple><bold>Special - Moonbow", "<bold>Refined: Unique"
				set {_deadlord}'s helmet to gold helmet of protection 4
				set {_deadlord}'s chestplate to gold chestplate of protection 4
				set {_deadlord}'s leggings to gold leggings of protection 4
				set {_deadlord}'s boots to gold boots of protection 4
				set {class.%{_deadlord}%} to "Sniper"
				set {skillslot1.%{_deadlord}%} to "Distant Defence"
				set {skillslot2.%{_deadlord}%} to "Heavy Draw"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 5:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Chosen Undead: Skiddlezz"
				set {t_str.%{_deadlord}%} to 120
				set {t_def.%{_deadlord}%} to 255
				set {t_spd.%{_deadlord}%} to 100
				set {skl.%{_deadlord}%} to 90
				set {t_res.%{_deadlord}%} to 100
				set {lvl.%{_deadlord}%} to 150
				set the maximum health of {_deadlord} to 135
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Balder Side Sword" with lore "<light red><bold>Slot A - Close Defence", "<light blue><bold>Slot B - Riposte", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Ignis", "<bold>Refined: Unique"
				set {_deadlord}'s helmet to diamond helmet 
				set {_deadlord}'s chestplate to diamond chestplate 
				set {_deadlord}'s leggings to diamond leggings 
				set {_deadlord}'s boots to diamond boots 
				set {class.%{_deadlord}%} to "Chieftain"
				set {skillslot1.%{_deadlord}%} to "Distant Defence"
				set {skillslot2.%{_deadlord}%} to "Axe Specialist"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 6:
				spawn 1 zombie at the entity
				set the name of the last spawned entity to "<light red>Holy Knight: Sigurd"
				set {_deadlord} to the last spawned entity
				spawn 1 horse at the entity
				apply swiftness 3 to the last spawned entity
				apply resistance 3 to the last spawned entity
				set {t_str.%{_deadlord}%} to 95
				set {t_def.%{_deadlord}%} to 60
				set {t_spd.%{_deadlord}%} to 55
				set {skl.%{_deadlord}%} to 85
				set {t_res.%{_deadlord}%} to 30
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 90
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Divine Tyrfing" with lore "<light red><bold>Slot A - Distant Counter", "<light blue><bold>Slot B - Eclipse Brace", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Luna", "<bold>Refined: Koenig"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Crusader"
				set {skillslot1.%{_deadlord}%} to "Crusader's Ward"
				set {skillslot2.%{_deadlord}%} to "Sword Specialist"
				set {skillslot3.%{_deadlord}%} to "Crusader's Blood"
				set {skillslot4.%{_deadlord}%} to "Lord's Blood"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 7:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Divine Dragon: Tiki"
				set {t_str.%{_deadlord}%} to 30
				set {t_def.%{_deadlord}%} to 100
				set {t_spd.%{_deadlord}%} to 60
				set {skl.%{_deadlord}%} to 80
				set {t_res.%{_deadlord}%} to 120
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 70
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<orange><bold>Flametounge" with lore "<light red><bold>Slot A - Distant Counter", "<light blue><bold>Slot B - Sabotage Speed", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Glacies", "<bold>Refined: Warding"
				set {_deadlord}'s helmet to diamond helmet 
				set {_deadlord}'s chestplate to diamond chestplate 
				set {_deadlord}'s leggings to diamond leggings 
				set {_deadlord}'s boots to diamond boots 
				set {class.%{_deadlord}%} to "Divine Dragon"
				set {skillslot1.%{_deadlord}%} to "Draconic Rage"
				set {skillslot2.%{_deadlord}%} to "Brazen Spectrum"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 8:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				apply swiftness 6 to the last spawned entity for 999 days
				set the name of the last spawned entity to "<red><bold>Lord of the Damned: Alstair"
				set {t_str.%{_deadlord}%} to 570
				set {t_def.%{_deadlord}%} to 570
				set {t_spd.%{_deadlord}%} to 230
				set {skl.%{_deadlord}%} to 595
				set {t_res.%{_deadlord}%} to 910
				set {lvl.%{_deadlord}%} to 750
				set the maximum health of {_deadlord} to 190
				set {_deadlord}'s tool to diamond sword of sharpness 8 named "<gold><bold>Death's Caress" with lore "Slot A - Distant Counter", "Slot B - Desperation", "Slot C - Glacies", "<purple><bold>Refined: Crushing", "<White>A terrifying blade of unkown origin.", "<white>", "The diamond core seems to pulse with demonic energy.", "<white>None who have met the undead terror have lived to tell the tale..."
				set {_deadlord}'s helmet to diamond helmet 
				set {_deadlord}'s chestplate to diamond chestplate 
				set {_deadlord}'s leggings to diamond leggings 
				set {_deadlord}'s boots to diamond boots 
				set {class.%{_deadlord}%} to "Lord"
				set {skillslot1.%{_deadlord}%} to "Double Lion"
				set {skillslot2.%{_deadlord}%} to "Crusader's Ward"
				set {skillslot3.%{_deadlord}%} to "Brazen Spectrum"
				set {skillslot4.%{_deadlord}%} to "Draconic Rage"
				set {skillslot5.%{_deadlord}%} to "Miracle"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 9:
				spawn 1 zombie at the entity
				set the name of the last spawned entity to "<light red>Thunder's Sword: Reinhardt"
				set {_deadlord} to the last spawned entity
				spawn 1 horse at the entity
				apply swiftness 3 to the last spawned entity
				apply resistance 3 to the last spawned entity
				set {t_str.%{_deadlord}%} to 85
				set {t_def.%{_deadlord}%} to 65
				set {t_spd.%{_deadlord}%} to 35
				set {skl.%{_deadlord}%} to 80
				set {t_res.%{_deadlord}%} to 65
				set {lvl.%{_deadlord}%} to 80
				set the maximum health of {_deadlord} to 80
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Meisterschwert" with lore "<light red><bold>Slot A - Distant Counter", "<light blue><bold>Slot B - Shield Pulse", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Pavise", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Mage Knight"
				set {skillslot1.%{_deadlord}%} to "Brazen Spectrum"
				set {skillslot2.%{_deadlord}%} to "Brazen STR"
				set {skillslot3.%{_deadlord}%} to "Brazen DEF"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 10:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Blazing Tactician: Lukas"
				set {t_str.%{_deadlord}%} to 65
				set {t_def.%{_deadlord}%} to 65
				set {t_spd.%{_deadlord}%} to 65
				set {skl.%{_deadlord}%} to 65
				set {t_res.%{_deadlord}%} to 65
				set {lvl.%{_deadlord}%} to 80
				set the maximum health of {_deadlord} to 85
				set {_deadlord}'s tool to diamond sword of sharpness 5, fire aspect 1 and knockback 2 named "<yellow><bold>The Grandmaster" with lore "<light red><bold>Slot A - Defiant Resistance", "<light blue><bold>Slot B - Wrath", "<light yellow><bold>Slot C - Pressure STR", "<light green><bold>Assist - Rally Attack", "<light purple><bold>Special - Moonbow", "<bold>Refined: Koenig"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Grandmaster"
				set {skillslot1.%{_deadlord}%} to "Brazen Spectrum"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 11:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Kindled Spirit: Katarina"
				set {t_str.%{_deadlord}%} to 40
				set {t_def.%{_deadlord}%} to 65
				set {t_spd.%{_deadlord}%} to 80
				set {skl.%{_deadlord}%} to 60
				set {t_res.%{_deadlord}%} to 125
				set {lvl.%{_deadlord}%} to 80
				set the maximum health of {_deadlord} to 70
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<teal><bold>Dragon's Talons" with lore "<light red><bold>Slot A - Warding Stance", "<light blue><bold>Slot B - Bonus Blade", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - Hit and Run", "<light purple><bold>Special - Ignis", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to chainmail helmet of protection 6
				set {_deadlord}'s chestplate to chainmail chestplate of protection 6
				set {_deadlord}'s leggings to chainmail leggings of protection 6
				set {_deadlord}'s boots to chainmail boots of protection 6
				set {class.%{_deadlord}%} to "Dragonborn"
				set {skillslot1.%{_deadlord}%} to "Draconic Rage"
				set {skillslot2.%{_deadlord}%} to "Brazen MAG"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 12:
				spawn 1 skeleton at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Warrior Priestess: Celica"
				set {t_str.%{_deadlord}%} to 45
				set {t_def.%{_deadlord}%} to 45
				set {t_spd.%{_deadlord}%} to 65
				set {skl.%{_deadlord}%} to 80
				set {t_res.%{_deadlord}%} to 100
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 60
				set {_deadlord}'s tool to bow of power 7 and punch 2 named "<gold><bold>Ragnarok" with lore "<light red><bold>Slot A - Sorcery Blade", "<light blue><bold>Slot B - Bonus Blade", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - None", "<light purple><bold>Special - Growing Light", "<bold>Refined: Slaying"
				set {_deadlord}'s chestplate to leather chestplate of protection 5
				set {_deadlord}'s leggings to leather leggings of protection 5
				set {_deadlord}'s boots to leather boots of protection 5
				set {class.%{_deadlord}%} to "Sorcerer"
				set {skillslot1.%{_deadlord}%} to "Brazen MAG"
				set {skillslot2.%{_deadlord}%} to "Brazen SPD"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 13:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Young Light: Leif"
				set {t_str.%{_deadlord}%} to 50
				set {t_def.%{_deadlord}%} to 75
				set {t_spd.%{_deadlord}%} to 115
				set {skl.%{_deadlord}%} to 135
				set {t_res.%{_deadlord}%} to 75
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 65
				set {_deadlord}'s tool to gold sword of sharpness 10 and unbreaking 10 named "<gold><bold>Light Brand" with lore "<light red><bold>Slot A - Sorcery Aura", "<light blue><bold>Slot B - Wrath", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - None", "<light purple><bold>Special - Blazing Light", "<bold>Refined: Reinforced"
				set {_deadlord}'s helmet to gold helmet of protection 5
				set {_deadlord}'s chestplate to gold chestplate of protection 5
				set {_deadlord}'s leggings to gold leggings of protection 5
				set {_deadlord}'s boots to gold boots of protection 5
				set {class.%{_deadlord}%} to "Junior Lord"
				set {skillslot1.%{_deadlord}%} to "Brazen MAG"
				set {skillslot2.%{_deadlord}%} to "Crushing Offense"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 14:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Scion of Light: Seliph"
				set {t_str.%{_deadlord}%} to 65
				set {t_def.%{_deadlord}%} to 100
				set {t_spd.%{_deadlord}%} to 45
				set {skl.%{_deadlord}%} to 55
				set {t_res.%{_deadlord}%} to 45
				set {lvl.%{_deadlord}%} to 75
				set the maximum health of {_deadlord} to 65
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Tyrfing" with lore "<light red><bold>Slot A - Distant Defence", "<light blue><bold>Slot B - Brash Assault", "<light yellow><bold>Slot C - STR Smoke", "<light green><bold>Assist - Shove", "<light purple><bold>Special - Ignis", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to diamond helmet of protection 3
				set {_deadlord}'s chestplate to diamond chestplate of protection 3
				set {_deadlord}'s leggings to diamond leggings of projectile protection 3
				set {_deadlord}'s boots to diamond boots of projectile protection 3
				set {class.%{_deadlord}%} to "Junior Lord"
				set {skillslot1.%{_deadlord}%} to "Crusader's Ward"
				set {skillslot2.%{_deadlord}%} to "Brazen DEF"
				set {skillslot3.%{_deadlord}%} to "Crusader's Blood"
				set {skillslot4.%{_deadlord}%} to "Lord's Blood"
				set {skillslot5.%{_deadlord}%} to "Steady Breath"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 15:
				spawn 1 zombie at the entity
				set the name of the last spawned entity to "<light red>Lionheart: Eldigan"
				set {_deadlord} to the last spawned entity
				spawn 1 horse at the entity
				apply swiftness 3 to the last spawned entity
				apply resistance 3 to the last spawned entity
				set {t_str.%{_deadlord}%} to 75
				set {t_def.%{_deadlord}%} to 65
				set {t_spd.%{_deadlord}%} to 60
				set {skl.%{_deadlord}%} to 75
				set {t_res.%{_deadlord}%} to 40
				set {lvl.%{_deadlord}%} to 75
				set the maximum health of {_deadlord} to 70
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Mystletainn" with lore "<light red><bold>Slot A - Fury", "<light blue><bold>Slot B - Sabotage Defense", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - None", "<light purple><bold>Special - Retribution", "<bold>Refined: Unique"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Crusader"
				set {skillslot1.%{_deadlord}%} to "Brazen SKL"
				set {skillslot2.%{_deadlord}%} to "Brazen STR"
				set {skillslot3.%{_deadlord}%} to "Crusader's Blood"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 16:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Peerless Fighter: Raven"
				set {t_str.%{_deadlord}%} to 100
				set {t_def.%{_deadlord}%} to 35
				set {t_spd.%{_deadlord}%} to 135
				set {skl.%{_deadlord}%} to 100
				set {t_res.%{_deadlord}%} to 10
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 60
				set {_deadlord}'s tool to diamond axe of sharpness 5 named "<gold><bold>Basilikos" with lore "<light red><bold>Slot A - Life and Death", "<light blue><bold>Slot B - Sabotage Defense", "<light yellow><bold>Slot C - None", "<light green><bold>Assist - None", "<light purple><bold>Special - Rising Wind", "<bold>Refined: Crushing"
				set {_deadlord}'s helmet to chainmail helmet of protection 6
				set {_deadlord}'s chestplate to chainmail chestplate of protection 6
				set {_deadlord}'s leggings to chainmail leggings of protection 6
				set {_deadlord}'s boots to chainmail boots of protection 6
				set {class.%{_deadlord}%} to "Barbarian"
				set {skillslot1.%{_deadlord}%} to "Crushing Offense"
				set {skillslot2.%{_deadlord}%} to "Brazen STR"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 17:
				spawn 1 skeleton at the entity
				set the name of the last spawned entity to "<light red>Thunder's Fist: Reinhardt"
				set {_deadlord} to the last spawned entity
				spawn 1 horse at the entity
				apply swiftness 3 to the last spawned entity
				apply resistance 3 to the last spawned entity
				make {_deadlord} ride the last spawned entity
				set {t_str.%{_deadlord}%} to 55
				set {t_def.%{_deadlord}%} to 55
				set {t_spd.%{_deadlord}%} to 20
				set {skl.%{_deadlord}%} to 55
				set {t_res.%{_deadlord}%} to 80
				set {lvl.%{_deadlord}%} to 80
				set the maximum health of {_deadlord} to 40
				set {_deadlord}'s tool to bow of power 5 and punch 2 named "<gold><bold>Dire Thunder" with lore "<light red><bold>Slot A - Sorcery Aura", "<light blue><bold>Slot B - Eclipse Brace", "<light yellow><bold>Slot C - None", "<light green><bold>Assist - None", "<light purple><bold>Special - Moonbow", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to leather helmet of protection 5
				set {_deadlord}'s chestplate to diamond chestplate of protection 2
				set {_deadlord}'s leggings to leather leggings of protection 5
				set {_deadlord}'s boots to leather boots of protection 5
				set {class.%{_deadlord}%} to "Mage Knight"
				set {skillslot1.%{_deadlord}%} to "Distant Defence"
				set {skillslot2.%{_deadlord}%} to "Brazen MAG"
				set {skillslot3.%{_deadlord}%} to "Brazen Spectrum"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 18:
				spawn 1 skeleton at the entity
				set the name of the last spawned entity to "<red><bold>Undead Rider: Barakov"
				spawn 1 skeleton horse at the entity
				apply swiftness 3 to the last spawned entity
				apply resistance 3 to the last spawned entity
				make {_deadlord} ride the last spawned entity
				set {_deadlord} to the last spawned entity
				set {t_str.%{_deadlord}%} to 225
				set {t_def.%{_deadlord}%} to 180
				set {t_spd.%{_deadlord}%} to 100
				set {skl.%{_deadlord}%} to 95
				set {t_res.%{_deadlord}%} to 180
				set {lvl.%{_deadlord}%} to 250
				set the maximum health of {_deadlord} to 80
				set {_deadlord}'s tool to bow of power 7 named "<gold><bold>Barakov" with lore "Slot A - Armour Smasher", "Slot B - Poison Strike", "Slot C - Retribution", "<green><bold>Refined: Slaying", "<white>A bow infused with darkness.", "<white>Entrusted to only Alstair's most trusted companions."
				set {_deadlord}'s helmet to diamond helmet 
				set {_deadlord}'s chestplate to diamond chestplate 
				set {_deadlord}'s leggings to diamond leggings 
				set {_deadlord}'s boots to diamond boots 
				set {class.%{_deadlord}%} to "Paladin"
				set {skillslot1.%{_deadlord}%} to "Crusader's Ward"
				set {skillslot2.%{_deadlord}%} to "Brazen STR"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 19:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Hero of Yore: Marth"
				set {t_str.%{_deadlord}%} to 150
				set {t_def.%{_deadlord}%} to 150
				set {t_spd.%{_deadlord}%} to 150
				set {skl.%{_deadlord}%} to 150
				set {t_res.%{_deadlord}%} to 150
				set {lvl.%{_deadlord}%} to 120
				set the maximum health of {_deadlord} to 100
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Falchion" with lore "<light red><bold>Slot A - Armour Smasher", "<light blue><bold>Slot B - Desperation", "<light yellow><bold>Slot C - Pressure STR", "<light green><bold>Assist - Rally Spectrum", "<light purple><bold>Special - Growing Light", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to gold helmet of projectile protection 10 and unbreaking 10
				set {_deadlord}'s chestplate to diamond chestplate of protection 10 and unbreaking 10
				set {_deadlord}'s leggings to diamond leggings of protection 10 and unbreaking 10
				set {_deadlord}'s boots to diamond boots of protection 10 and unbreaking 10
				set {class.%{_deadlord}%} to "Lord"
				set {skillslot1.%{_deadlord}%} to "Lord's Blood"
				set {skillslot2.%{_deadlord}%} to "Brazen Spectrum"
				set {skillslot3.%{_deadlord}%} to "Crushing Offense"
				set {skillslot4.%{_deadlord}%} to "Vantage"
				set {skillslot5.%{_deadlord}%} to "Brazen STR"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 20:
				spawn 1 skeleton at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Shadowed Sniper: Clarisse"
				set {t_str.%{_deadlord}%} to 80
				set {t_def.%{_deadlord}%} to 30
				set {t_spd.%{_deadlord}%} to 65
				set {skl.%{_deadlord}%} to 55
				set {t_res.%{_deadlord}%} to 25
				set {lvl.%{_deadlord}%} to 60
				set the maximum health of {_deadlord} to 45
				set {_deadlord}'s tool to bow of power 5 named "<white><bold>Clarisse's Bow" with lore "<light red><bold>Slot A - Life and Death", "<light blue><bold>Slot B - Poison Strike", "<light yellow><bold>Slot C - None", "<light green><bold>Assist - None", "<light purple><bold>Special - Glimmer", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to leather helmet of protection 4
				set {_deadlord}'s chestplate to leather chestplate of protection 4
				set {_deadlord}'s leggings to leather leggings of protection 4
				set {_deadlord}'s boots to leather boots of protection 4
				set {class.%{_deadlord}%} to "Sniper"
				set {skillslot1.%{_deadlord}%} to "Heavy Draw"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 21:
				spawn 1 skeleton at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Forest's Breeze: Jamke"
				set {t_str.%{_deadlord}%} to 115
				set {t_def.%{_deadlord}%} to 65
				set {t_spd.%{_deadlord}%} to 55
				set {skl.%{_deadlord}%} to 75
				set {t_res.%{_deadlord}%} to 65
				set {lvl.%{_deadlord}%} to 75
				set the maximum health of {_deadlord} to 60
				set {_deadlord}'s tool to bow of power 5 named "<white><bold>Slaying Bow" with lore "<light red><bold>Slot A - Armour Smasher", "<light blue><bold>Slot B - Wrath", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - None", "<light purple><bold>Special - Astra", "<bold>Refined: Slaying"
				set {_deadlord}'s chestplate to leather chestplate of protection 5
				set {_deadlord}'s leggings to diamond leggings of protection 3
				set {_deadlord}'s boots to diamond boots of protection 3
				set {class.%{_deadlord}%} to "Sniper"
				set {skillslot1.%{_deadlord}%} to "Crushing Offense"
				set {skillslot2.%{_deadlord}%} to "Heavy Draw"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 22:
				spawn 1 skeleton at the entity
				apply swiftness 4 to the last spawned entity for 999 days
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Wind's Call: Lewyn"
				set {t_str.%{_deadlord}%} to 25
				set {t_def.%{_deadlord}%} to 25
				set {t_spd.%{_deadlord}%} to 150
				set {skl.%{_deadlord}%} to 75
				set {t_res.%{_deadlord}%} to 125
				set {lvl.%{_deadlord}%} to 95
				set the maximum health of {_deadlord} to 55
				set {_deadlord}'s tool to bow of power 10 named "<gold><bold>Forseti" with lore "<light red><bold>Slot A - Sorcery Aura", "<light blue><bold>Slot B - Desperation", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - None", "<light purple><bold>Special - Rising Wind", "<bold>Refined: Slaying"
				set {_deadlord}'s chestplate to leather chestplate of protection 5
				set {_deadlord}'s leggings to iron leggings of protection 3
				set {_deadlord}'s boots to iron boots of protection 3
				set {class.%{_deadlord}%} to "Sorcerer"
				set {skillslot1.%{_deadlord}%} to "Distant Defense"
				set {skillslot2.%{_deadlord}%} to "Heavy Draw"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 23:
				spawn 1 skeleton at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Kindly Priest: Wrys"
				set {t_str.%{_deadlord}%} to 66
				set {t_def.%{_deadlord}%} to 35
				set {t_spd.%{_deadlord}%} to 25
				set {skl.%{_deadlord}%} to 65
				set {t_res.%{_deadlord}%} to 80
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 70
				set {_deadlord}'s tool to bow of power 5 named "<white><bold>Slow" with lore "<light red><bold>Slot A - Close Counter", "<light blue><bold>Slot B - Sabotage Speed", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Restore", "<light purple><bold>Special - Glacies", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to leather helmet of protection 5
				set {_deadlord}'s chestplate to leather chestplate of protection 5
				set {_deadlord}'s leggings to leather leggings of protection 5
				set {_deadlord}'s boots to leather boots of protection 5
				set {class.%{_deadlord}%} to "Sage"
				set {skillslot1.%{_deadlord}%} to "Wrathful Staff"
				set {skillslot2.%{_deadlord}%} to "Brazen STR"
				set {skillslot3.%{_deadlord}%} to "Miracle"
				set {skillslot4.%{_deadlord}%} to "Distant Defence"
				set {skillslot5.%{_deadlord}%} to "Ranged Specialist"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 24:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Vanguard Legend: Ike"
				set {t_str.%{_deadlord}%} to 135
				set {t_def.%{_deadlord}%} to 80
				set {t_spd.%{_deadlord}%} to 65
				set {skl.%{_deadlord}%} to 80
				set {t_res.%{_deadlord}%} to 45
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 75
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Ragnell" with lore "<light red><bold>Slot A - Fierce Stance", "<light blue><bold>Slot B - Solar Brace", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Shove", "<light purple><bold>Special - Sol", "<bold>Refined: Unique"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Hero"
				set {skillslot1.%{_deadlord}%} to "Crushing Offense"
				set {skillslot2.%{_deadlord}%} to "Vantage"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 25:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Lance of Legend: Finn"
				set {t_str.%{_deadlord}%} to 72
				set {t_def.%{_deadlord}%} to 60
				set {t_spd.%{_deadlord}%} to 100
				set {skl.%{_deadlord}%} to 70
				set {t_res.%{_deadlord}%} to 34
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 75
				set {_deadlord}'s tool to diamond shovel of sharpness 7 named "<white><bold>Diamond Lance" with lore "<light red><bold>Slot A - Life and Death", "<light blue><bold>Slot B - Brave Blade", "<light yellow><bold>Slot C - Breath of Life", "<light green><bold>Assist - Reposition", "<light purple><bold>Special - Luna", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to diamond helmet of protection 3
				set {_deadlord}'s chestplate to diamond chestplate of protection 3
				set {_deadlord}'s leggings to diamond leggings of protection 3
				set {_deadlord}'s boots to diamond boots of protection 3
				set {class.%{_deadlord}%} to "Lord"
				set {skillslot1.%{_deadlord}%} to "Double Lion"
				set {skillslot2.%{_deadlord}%} to "Crushing Offense"
				set {skillslot3.%{_deadlord}%} to "Miracle"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 26:
				spawn 1 zombie at the entity
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Strong and Tough: Arden"
				set {t_str.%{_deadlord}%} to 80
				set {t_def.%{_deadlord}%} to 160
				set {t_spd.%{_deadlord}%} to 15
				set {skl.%{_deadlord}%} to 45
				set {t_res.%{_deadlord}%} to 15
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 90
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<bold>Slaying Edge" with lore "<light red><bold>Slot A - Steady Stance", "<light blue><bold>Slot B - Eclipse Brace", "<light yellow><bold>Slot C - DEF Smoke", "<light green><bold>Assist - None", "<light purple><bold>Special - Ignis", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to diamond helmet of protection 5
				set {_deadlord}'s chestplate to diamond chestplate of protection 5
				set {_deadlord}'s leggings to diamond leggings of protection 5
				set {_deadlord}'s boots to diamond boots of protection 5
				set {class.%{_deadlord}%} to "Chieftain"
				set {skillslot1.%{_deadlord}%} to "Unbreakable"
				set {skillslot2.%{_deadlord}%} to "Guard"
				set {skillslot3.%{_deadlord}%} to "Brazen STR"
				set {skillslot4.%{_deadlord}%} to "Brazen DEF"
				set {isBoss.%{_deadlord}%} to true
			heal {_deadlord} by 999
		if arg 2 is 1:
			loop all players in radius 256 of {_deadlord}:
				add {lvl.%loop-player%} to {_lvlbal}
				add 1 to {_players}
			set {_lvlbal} to ({_lvlbal} / {_players})
			if {_lvlbal} is less than {lvl.%{_deadlord}%}:
				set {_balance} to abs({_lvlbal} - {lvl.%{_deadlord}%})
				loop {_balance} times:
					subtract 1 from {t_str.%{_deadlord}%}
					subtract 1 from {t_def.%{_deadlord}%}
					subtract 1 from {t_spd.%{_deadlord}%}
					subtract 1 from {skl.%{_deadlord}%}
					subtract 1 from {t_res.%{_deadlord}%}
					subtract 0.5 from the maximum health of {_deadlord}
					subtract 1 from {lvl.%{_deadlord}%}
			else if {_lvlbal} is more than {lvl.%{_deadlord}%}:
				set {_balance} to ({_lvlbal} - {lvl.%{_deadlord}%})
				loop {_balance} times:
					add 1 to {t_str.%{_deadlord}%}
					add 1 to {t_def.%{_deadlord}%}
					add 1 to {t_spd.%{_deadlord}%}
					add 1 to {skl.%{_deadlord}%}
					add 1 to {t_res.%{_deadlord}%}
					add 0.5 to the maximum health of {_deadlord}
					add 1 to {lvl.%{_deadlord}%}
			if the maximum health of {_deadlord} is less than 20:
				set the maximum health of {_deadlord} to 20
			if {t_spd.%{_deadlord}%} is more than 125:
				apply swiftness 5 to {_deadlord} for 1 day
			else if {t_spd.%{_deadlord}%} is more than 100:
				apply swiftness 4 to {_deadlord} for 1 day
			else if {t_spd.%{_deadlord}%} is more than 75:
				apply swiftness 3 to {_deadlord} for 1 day
			else if {t_spd.%{_deadlord}%} is more than 50:
				apply swiftness 2 to {_deadlord} for 1 day
			else if {t_spd.%{_deadlord}%} is more than 25:
				apply swiftness 1 to {_deadlord} for 1 day
			heal {_deadlord} by 999
			set {_loc} to location of block at the last spawned entity
			broadcast "<light red>Coordinates: %{_loc}%"
			broadcast "<light red>Level: %{lvl.%{_deadlord}%}%"
			broadcast "<light red>Weapon: %{_deadlord}'s tool%"			


#Spawned monsters scale to players with classes.
on spawn of a monster:
	if entity is alive:
		if entity's world is not "Salindrum":
			set {_modifier} to 20
			if the entity's world is "GenOne":
				set {_modifier} to 0
			if the entity's world is "Alstair":
				add 55 to {_modifier}
			else if the entity's world is "Alstair_Nether":
				add 55 to {_modifier}
			else if the entity's world is "Alstair_End":
				subtract 1 from {_modifier}
			chance of 1%:
				chance of {_modifier}%:
					broadcast "<light red>A fallen hero has arisen..."
					set {_name} to a random integer from 1 to 26
					set {_loc} to location of block at entity
					if {_name} is 1:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Hero of Prophecy: Alm"
						set {str.%{_deadlord}%} to 85
						set {def.%{_deadlord}%} to 55
						set {spd.%{_deadlord}%} to 65
						set {skl.%{_deadlord}%} to 120
						set {res.%{_deadlord}%} to 30
						set the maximum health of {_deadlord} to 80
						set {lvl.%{_deadlord}%} to 90
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Falchion" with lore "Slot A - Armour Smasher", "Slot B - Brave Blade", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Luna", "<red><bold>Refined: Reinforced"
						set {_deadlord}'s helmet to diamond helmet of protection 4
						set {_deadlord}'s chestplate to diamond chestplate of protection 4
						set {_deadlord}'s leggings to diamond leggings of protection 4
						set {_deadlord}'s boots to diamond boots of protection 4
						set {class.%{_deadlord}%} to "Lord"
						set {skillslot1.%{_deadlord}%} to "Double Lion"
						set {skillslot2.%{_deadlord}%} to "Lord's Blood"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 2:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Young Lion: Roy"
						set {str.%{_deadlord}%} to 65
						set {def.%{_deadlord}%} to 70
						set {spd.%{_deadlord}%} to 55
						set {skl.%{_deadlord}%} to 80
						set {res.%{_deadlord}%} to 85
						set {lvl.%{_deadlord}%} to 90
						set the maximum health of {_deadlord} to 85
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Binding Blade" with lore "<light red><bold>Slot A - Close Defence", "<light blue><bold>Slot B - Sabotage Attack", "<light yellow><bold>Slot C - Pressure STR", "<light green><bold>Assist - Reposition", "<light purple><bold>Special - Dragon Fang", "<bold>Refined: Unique"
						set {_deadlord}'s helmet to diamond helmet of protection 4
						set {_deadlord}'s chestplate to diamond chestplate of protection 4
						set {_deadlord}'s leggings to diamond leggings of protection 4
						set {_deadlord}'s boots to diamond boots of protection 4
						set {class.%{_deadlord}%} to "Lord"
						set {skillslot1.%{_deadlord}%} to "Distant Defence"
						set {skillslot2.%{_deadlord}%} to "Sword Specialist"
						set {skillslot3.%{_deadlord}%} to "Lord's Blood"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 3:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Scarlett Sword: Navarre"
						apply swiftness 4 to the entity for 999 days
						set {str.%{_deadlord}%} to 120
						set {def.%{_deadlord}%} to 29
						set {spd.%{_deadlord}%} to 160
						set {skl.%{_deadlord}%} to 175
						set {res.%{_deadlord}%} to 25
						set {lvl.%{_deadlord}%} to 75
						set the maximum health of {_deadlord} to 60
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<red><bold>Scarlett Sword" with lore "<light red><bold>Slot A - Armour Smasher", "<light blue><bold>Slot B - Desperation", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - Rally Speed", "<light purple><bold>Special - Galeforce", "<bold>Refined: Slaying"
						set {_deadlord}'s helmet to leather helmet of protection 5
						set {_deadlord}'s chestplate to leather chestplate of protection 5
						set {_deadlord}'s leggings to leather leggings of protection 5
						set {_deadlord}'s boots to leather boots of protection 5
						set {class.%{_deadlord}%} to "Swordmaster"
						set {skillslot1.%{_deadlord}%} to "Vantage"
						set {skillslot2.%{_deadlord}%} to "Sword Specialist"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 4:
						spawn 1 skeleton at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Altean Sniper: Jeorge"
						apply swiftness 4 to the entity for 999 days
						set {str.%{_deadlord}%} to 120
						set {def.%{_deadlord}%} to 10
						set {spd.%{_deadlord}%} to 120
						set {skl.%{_deadlord}%} to 175
						set {res.%{_deadlord}%} to 10
						set {lvl.%{_deadlord}%} to 75
						set the maximum health of {_deadlord} to 70
						set {_deadlord}'s tool to bow of power 5 named "<gold><bold>Parthia" with lore "<light red><bold>Slot A - Close Counter", "<light blue><bold>Slot B - Sabotage Speed", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - None", "<light purple><bold>Special - Moonbow", "<bold>Refined: Unique"
						set {_deadlord}'s helmet to gold helmet of protection 4
						set {_deadlord}'s chestplate to gold chestplate of protection 4
						set {_deadlord}'s leggings to gold leggings of protection 4
						set {_deadlord}'s boots to gold boots of protection 4
						set {class.%{_deadlord}%} to "Sniper"
						set {skillslot1.%{_deadlord}%} to "Distant Defence"
						set {skillslot2.%{_deadlord}%} to "Heavy Draw"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 5:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Chosen Undead: Skiddlezz"
						set {str.%{_deadlord}%} to 120
						set {def.%{_deadlord}%} to 255
						set {spd.%{_deadlord}%} to 100
						set {skl.%{_deadlord}%} to 90
						set {res.%{_deadlord}%} to 100
						set {lvl.%{_deadlord}%} to 150
						set the maximum health of {_deadlord} to 135
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Balder Side Sword" with lore "<light red><bold>Slot A - Close Defence", "<light blue><bold>Slot B - Riposte", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Ignis", "<bold>Refined: Unique"
						set {_deadlord}'s helmet to diamond helmet 
						set {_deadlord}'s chestplate to diamond chestplate 
						set {_deadlord}'s leggings to diamond leggings 
						set {_deadlord}'s boots to diamond boots 
						set {class.%{_deadlord}%} to "Chieftain"
						set {skillslot1.%{_deadlord}%} to "Distant Defence"
						set {skillslot2.%{_deadlord}%} to "Axe Specialist"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 6:
						spawn 1 zombie at the entity
						set the name of the last spawned entity to "<light red>Holy Knight: Sigurd"
						set {_deadlord} to the last spawned entity
						spawn 1 horse at the entity
						apply swiftness 3 to the last spawned entity
						apply resistance 3 to the last spawned entity
						set {str.%{_deadlord}%} to 95
						set {def.%{_deadlord}%} to 60
						set {spd.%{_deadlord}%} to 55
						set {skl.%{_deadlord}%} to 85
						set {res.%{_deadlord}%} to 30
						set {lvl.%{_deadlord}%} to 90
						set the maximum health of {_deadlord} to 90
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Divine Tyrfing" with lore "<light red><bold>Slot A - Distant Counter", "<light blue><bold>Slot B - Eclipse Brace", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Luna", "<bold>Refined: Koenig"
						set {_deadlord}'s helmet to diamond helmet of protection 4
						set {_deadlord}'s chestplate to diamond chestplate of protection 4
						set {_deadlord}'s leggings to diamond leggings of protection 4
						set {_deadlord}'s boots to diamond boots of protection 4
						set {class.%{_deadlord}%} to "Crusader"
						set {skillslot1.%{_deadlord}%} to "Crusader's Ward"
						set {skillslot2.%{_deadlord}%} to "Sword Specialist"
						set {skillslot3.%{_deadlord}%} to "Crusader's Blood"
						set {skillslot4.%{_deadlord}%} to "Lord's Blood"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 7:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Divine Dragon: Tiki"
						set {str.%{_deadlord}%} to 30
						set {def.%{_deadlord}%} to 100
						set {spd.%{_deadlord}%} to 60
						set {skl.%{_deadlord}%} to 80
						set {res.%{_deadlord}%} to 120
						set {lvl.%{_deadlord}%} to 90
						set the maximum health of {_deadlord} to 70
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<orange><bold>Flametounge" with lore "<light red><bold>Slot A - Distant Counter", "<light blue><bold>Slot B - Sabotage Speed", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Glacies", "<bold>Refined: Warding"
						set {_deadlord}'s helmet to diamond helmet 
						set {_deadlord}'s chestplate to diamond chestplate 
						set {_deadlord}'s leggings to diamond leggings 
						set {_deadlord}'s boots to diamond boots 
						set {class.%{_deadlord}%} to "Divine Dragon"
						set {skillslot1.%{_deadlord}%} to "Draconic Rage"
						set {skillslot2.%{_deadlord}%} to "Brazen Spectrum"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 8:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						apply swiftness 6 to the last spawned entity for 999 days
						set the name of the last spawned entity to "<red><bold>Obsidian Knight: Alstair"
						set {str.%{_deadlord}%} to 80
						set {def.%{_deadlord}%} to 77
						set {spd.%{_deadlord}%} to 55
						set {skl.%{_deadlord}%} to 80
						set {res.%{_deadlord}%} to 59
						set {lvl.%{_deadlord}%} to 80
						set the maximum health of {_deadlord} to 190
						set {_deadlord}'s tool to diamond sword of sharpness 8 named "<gold><bold>Niur" with lore "Slot A - Distant Counter", "Slot B - Desperation", "Slot C - Pressure DEF","<light green><bold>Assist - None", "<light purple><bold>Special - Dragon Fang", "<purple><bold>Refined: Crushing"
						set {_deadlord}'s helmet to leather helmet of protection 10 dyed black
						set {_deadlord}'s chestplate to leather chestplate of protection 10 dyed black
						set {_deadlord}'s leggings to leather leggings of protection 10 dyed black
						set {_deadlord}'s boots to leather leggings of protection 10 dyed black
						set {class.%{_deadlord}%} to "Lord"
						set {skillslot1.%{_deadlord}%} to "Double Lion"
						set {skillslot3.%{_deadlord}%} to "Brazen Spectrum"
						set {skillslot4.%{_deadlord}%} to "Brazen STR"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 9:
						spawn 1 zombie at the entity
						set the name of the last spawned entity to "<light red>Thunder's Sword: Reinhardt"
						set {_deadlord} to the last spawned entity
						spawn 1 horse at the entity
						apply swiftness 3 to the last spawned entity
						apply resistance 3 to the last spawned entity
						set {str.%{_deadlord}%} to 85
						set {def.%{_deadlord}%} to 65
						set {spd.%{_deadlord}%} to 35
						set {skl.%{_deadlord}%} to 80
						set {res.%{_deadlord}%} to 65
						set {lvl.%{_deadlord}%} to 80
						set the maximum health of {_deadlord} to 80
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Meisterschwert" with lore "<light red><bold>Slot A - Distant Counter", "<light blue><bold>Slot B - Shield Pulse", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Pavise", "<bold>Refined: Slaying"
						set {_deadlord}'s helmet to diamond helmet of protection 4
						set {_deadlord}'s chestplate to diamond chestplate of protection 4
						set {_deadlord}'s leggings to diamond leggings of protection 4
						set {_deadlord}'s boots to diamond boots of protection 4
						set {class.%{_deadlord}%} to "Mage Knight"
						set {skillslot1.%{_deadlord}%} to "Brazen Spectrum"
						set {skillslot2.%{_deadlord}%} to "Brazen STR"
						set {skillslot3.%{_deadlord}%} to "Brazen DEF"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 10:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Blazing Lord: Cinder"
						set {str.%{_deadlord}%} to 70
						set {def.%{_deadlord}%} to 70
						set {spd.%{_deadlord}%} to 70
						set {skl.%{_deadlord}%} to 70
						set {res.%{_deadlord}%} to 70
						set {lvl.%{_deadlord}%} to 80
						set the maximum health of {_deadlord} to 85
						set {_deadlord}'s tool to diamond sword of sharpness 5, fire aspect 1 and knockback 2 named "<yellow><bold>The Grandmaster" with lore "<light red><bold>Slot A - Close Defence", "<light blue><bold>Slot B - Eclipse Brace", "<light yellow><bold>Slot C - Pressure STR", "<light green><bold>Assist - Rally Attack", "<light purple><bold>Special - Moonbow", "<bold>Refined: Koenig"
						set {_deadlord}'s helmet to diamond helmet of protection 4
						set {_deadlord}'s chestplate to diamond chestplate of protection 4
						set {_deadlord}'s leggings to diamond leggings of protection 4
						set {_deadlord}'s boots to diamond boots of protection 4
						set {class.%{_deadlord}%} to "Grandmaster"
						set {skillslot1.%{_deadlord}%} to "Brazen Spectrum"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 11:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Kindled Spirit: Katarina"
						set {str.%{_deadlord}%} to 40
						set {def.%{_deadlord}%} to 65
						set {spd.%{_deadlord}%} to 80
						set {skl.%{_deadlord}%} to 60
						set {res.%{_deadlord}%} to 125
						set {lvl.%{_deadlord}%} to 80
						set the maximum health of {_deadlord} to 70
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<teal><bold>Dragon's Talons" with lore "<light red><bold>Slot A - Warding Stance", "<light blue><bold>Slot B - Bonus Blade", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - Hit and Run", "<light purple><bold>Special - Ignis", "<bold>Refined: Slaying"
						set {_deadlord}'s helmet to chainmail helmet of protection 6
						set {_deadlord}'s chestplate to chainmail chestplate of protection 6
						set {_deadlord}'s leggings to chainmail leggings of protection 6
						set {_deadlord}'s boots to chainmail boots of protection 6
						set {class.%{_deadlord}%} to "Dragonborn"
						set {skillslot1.%{_deadlord}%} to "Draconic Rage"
						set {skillslot2.%{_deadlord}%} to "Brazen MAG"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 12:
						spawn 1 skeleton at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Warrior Priestess: Celica"
						set {str.%{_deadlord}%} to 45
						set {def.%{_deadlord}%} to 45
						set {spd.%{_deadlord}%} to 65
						set {skl.%{_deadlord}%} to 80
						set {res.%{_deadlord}%} to 100
						set {lvl.%{_deadlord}%} to 90
						set the maximum health of {_deadlord} to 60
						set {_deadlord}'s tool to bow of power 7 and punch 2 named "<gold><bold>Ragnarok" with lore "<light red><bold>Slot A - Sorcery Blade", "<light blue><bold>Slot B - Bonus Blade", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - None", "<light purple><bold>Special - Growing Light", "<bold>Refined: Slaying"
						set {_deadlord}'s chestplate to leather chestplate of protection 5
						set {_deadlord}'s leggings to leather leggings of protection 5
						set {_deadlord}'s boots to leather boots of protection 5
						set {class.%{_deadlord}%} to "Sorcerer"
						set {skillslot1.%{_deadlord}%} to "Brazen MAG"
						set {skillslot2.%{_deadlord}%} to "Brazen SPD"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 13:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Young Light: Leif"
						set {str.%{_deadlord}%} to 50
						set {def.%{_deadlord}%} to 75
						set {spd.%{_deadlord}%} to 115
						set {skl.%{_deadlord}%} to 135
						set {res.%{_deadlord}%} to 75
						set {lvl.%{_deadlord}%} to 90
						set the maximum health of {_deadlord} to 65
						set {_deadlord}'s tool to gold sword of sharpness 10 and unbreaking 10 named "<gold><bold>Light Brand" with lore "<light red><bold>Slot A - Sorcery Aura", "<light blue><bold>Slot B - Wrath", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - None", "<light purple><bold>Special - Blazing Light", "<bold>Refined: Reinforced"
						set {_deadlord}'s helmet to gold helmet of protection 5
						set {_deadlord}'s chestplate to gold chestplate of protection 5
						set {_deadlord}'s leggings to gold leggings of protection 5
						set {_deadlord}'s boots to gold boots of protection 5
						set {class.%{_deadlord}%} to "Junior Lord"
						set {skillslot1.%{_deadlord}%} to "Brazen MAG"
						set {skillslot2.%{_deadlord}%} to "Crushing Offense"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 14:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Scion of Light: Seliph"
						set {str.%{_deadlord}%} to 65
						set {def.%{_deadlord}%} to 100
						set {spd.%{_deadlord}%} to 45
						set {skl.%{_deadlord}%} to 55
						set {res.%{_deadlord}%} to 45
						set {lvl.%{_deadlord}%} to 75
						set the maximum health of {_deadlord} to 65
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Tyrfing" with lore "<light red><bold>Slot A - Distant Defence", "<light blue><bold>Slot B - Brash Assault", "<light yellow><bold>Slot C - STR Smoke", "<light green><bold>Assist - Shove", "<light purple><bold>Special - Ignis", "<bold>Refined: Slaying"
						set {_deadlord}'s helmet to diamond helmet of protection 3
						set {_deadlord}'s chestplate to diamond chestplate of protection 3
						set {_deadlord}'s leggings to diamond leggings of projectile protection 3
						set {_deadlord}'s boots to diamond boots of projectile protection 3
						set {class.%{_deadlord}%} to "Junior Lord"
						set {skillslot1.%{_deadlord}%} to "Crusader's Ward"
						set {skillslot2.%{_deadlord}%} to "Brazen DEF"
						set {skillslot3.%{_deadlord}%} to "Crusader's Blood"
						set {skillslot4.%{_deadlord}%} to "Lord's Blood"
						set {skillslot5.%{_deadlord}%} to "Steady Breath"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 15:
						spawn 1 zombie at the entity
						set the name of the last spawned entity to "<light red>Lionheart: Eldigan"
						set {_deadlord} to the last spawned entity
						spawn 1 horse at the entity
						apply swiftness 3 to the last spawned entity
						apply resistance 3 to the last spawned entity
						set {str.%{_deadlord}%} to 75
						set {def.%{_deadlord}%} to 65
						set {spd.%{_deadlord}%} to 60
						set {skl.%{_deadlord}%} to 75
						set {res.%{_deadlord}%} to 40
						set {lvl.%{_deadlord}%} to 75
						set the maximum health of {_deadlord} to 70
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Mystletainn" with lore "<light red><bold>Slot A - Fury", "<light blue><bold>Slot B - Sabotage Defense", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - None", "<light purple><bold>Special - Retribution", "<bold>Refined: Unique"
						set {_deadlord}'s helmet to diamond helmet of protection 4
						set {_deadlord}'s chestplate to diamond chestplate of protection 4
						set {_deadlord}'s leggings to diamond leggings of protection 4
						set {_deadlord}'s boots to diamond boots of protection 4
						set {class.%{_deadlord}%} to "Crusader"
						set {skillslot1.%{_deadlord}%} to "Brazen SKL"
						set {skillslot2.%{_deadlord}%} to "Brazen STR"
						set {skillslot3.%{_deadlord}%} to "Crusader's Blood"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 16:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Peerless Fighter: Raven"
						set {str.%{_deadlord}%} to 100
						set {def.%{_deadlord}%} to 35
						set {spd.%{_deadlord}%} to 135
						set {skl.%{_deadlord}%} to 100
						set {res.%{_deadlord}%} to 10
						set {lvl.%{_deadlord}%} to 90
						set the maximum health of {_deadlord} to 60
						set {_deadlord}'s tool to diamond axe of sharpness 5 named "<gold><bold>Basilikos" with lore "<light red><bold>Slot A - Life and Death", "<light blue><bold>Slot B - Sabotage Defense", "<light yellow><bold>Slot C - None", "<light green><bold>Assist - None", "<light purple><bold>Special - Rising Wind", "<bold>Refined: Crushing"
						set {_deadlord}'s helmet to chainmail helmet of protection 6
						set {_deadlord}'s chestplate to chainmail chestplate of protection 6
						set {_deadlord}'s leggings to chainmail leggings of protection 6
						set {_deadlord}'s boots to chainmail boots of protection 6
						set {class.%{_deadlord}%} to "Barbarian"
						set {skillslot1.%{_deadlord}%} to "Crushing Offense"
						set {skillslot2.%{_deadlord}%} to "Brazen STR"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 17:
						spawn 1 zombie at the entity
						set the name of the last spawned entity to "<light red>Thunder's Fist: Reinhardt"
						set {_deadlord} to the last spawned entity
						spawn 1 horse at the entity
						apply swiftness 3 to the last spawned entity
						apply resistance 3 to the last spawned entity
						make {_deadlord} ride the last spawned entity
						set {str.%{_deadlord}%} to 55
						set {def.%{_deadlord}%} to 55
						set {spd.%{_deadlord}%} to 20
						set {skl.%{_deadlord}%} to 55
						set {res.%{_deadlord}%} to 80
						set {lvl.%{_deadlord}%} to 80
						set the maximum health of {_deadlord} to 40
						set {_deadlord}'s tool to bow of power 5 and punch 2 named "<gold><bold>Dire Thunder" with lore "<light red><bold>Slot A - Sorcery Aura", "<light blue><bold>Slot B - Eclipse Brace", "<light yellow><bold>Slot C - None", "<light green><bold>Assist - None", "<light purple><bold>Special - Moonbow", "<bold>Refined: Slaying"
						set {_deadlord}'s helmet to leather helmet of protection 5
						set {_deadlord}'s chestplate to diamond chestplate of protection 2
						set {_deadlord}'s leggings to leather leggings of protection 5
						set {_deadlord}'s boots to leather boots of protection 5
						set {class.%{_deadlord}%} to "Mage Knight"
						set {skillslot1.%{_deadlord}%} to "Distant Defence"
						set {skillslot2.%{_deadlord}%} to "Brazen MAG"
						set {skillslot3.%{_deadlord}%} to "Brazen Spectrum"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 18:
						spawn 1 skeleton at the entity
						set the name of the last spawned entity to "<red><bold>Undead Rider: Barakov"
						spawn 1 skeleton horse at the entity
						apply swiftness 3 to the last spawned entity
						apply resistance 3 to the last spawned entity
						make {_deadlord} ride the last spawned entity
						set {_deadlord} to the last spawned entity
						set {str.%{_deadlord}%} to 225
						set {def.%{_deadlord}%} to 180
						set {spd.%{_deadlord}%} to 100
						set {skl.%{_deadlord}%} to 95
						set {res.%{_deadlord}%} to 180
						set {lvl.%{_deadlord}%} to 250
						set the maximum health of {_deadlord} to 80
						set {_deadlord}'s tool to bow of power 7 named "<gold><bold>Barakov" with lore "Slot A - Armour Smasher", "Slot B - Poison Strike", "Slot C - Retribution", "<green><bold>Refined: Slaying", "<white>A bow infused with darkness.", "<white>Entrusted to only Alstair's most trusted companions."
						set {_deadlord}'s helmet to diamond helmet 
						set {_deadlord}'s chestplate to diamond chestplate 
						set {_deadlord}'s leggings to diamond leggings 
						set {_deadlord}'s boots to diamond boots 
						set {class.%{_deadlord}%} to "Paladin"
						set {skillslot1.%{_deadlord}%} to "Crusader's Ward"
						set {skillslot2.%{_deadlord}%} to "Brazen STR"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 19:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Hero of Yore: Marth"
						set {str.%{_deadlord}%} to 150
						set {def.%{_deadlord}%} to 150
						set {spd.%{_deadlord}%} to 150
						set {skl.%{_deadlord}%} to 150
						set {res.%{_deadlord}%} to 150
						set {lvl.%{_deadlord}%} to 150
						set the maximum health of {_deadlord} to 100
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Falchion" with lore "<light red><bold>Slot A - Armour Smasher", "<light blue><bold>Slot B - Desperation", "<light yellow><bold>Slot C - Pressure STR", "<light green><bold>Assist - Rally Spectrum", "<light purple><bold>Special - Growing Light", "<bold>Refined: Slaying"
						set {_deadlord}'s helmet to gold helmet of protection 10 and unbreaking 15
						set {_deadlord}'s chestplate to diamond chestplate of protection 10 and unbreaking 10
						set {_deadlord}'s leggings to diamond leggings of protection 10 and unbreaking 10
						set {_deadlord}'s boots to diamond boots of protection 10 and unbreaking 10
						set {class.%{_deadlord}%} to "Lord"
						set {skillslot1.%{_deadlord}%} to "Lord's Blood"
						set {skillslot2.%{_deadlord}%} to "Brazen Spectrum"
						set {skillslot3.%{_deadlord}%} to "Crushing Offense"
						set {skillslot4.%{_deadlord}%} to "Vantage"
						set {skillslot5.%{_deadlord}%} to "Brazen STR"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 20:
						spawn 1 skeleton at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Shadowed Sniper: Clarisse"
						set {str.%{_deadlord}%} to 80
						set {def.%{_deadlord}%} to 30
						set {spd.%{_deadlord}%} to 65
						set {skl.%{_deadlord}%} to 55
						set {res.%{_deadlord}%} to 25
						set {lvl.%{_deadlord}%} to 60
						set the maximum health of {_deadlord} to 45
						set {_deadlord}'s tool to bow of power 5 named "<white><bold>Clarisse's Bow" with lore "<light red><bold>Slot A - Life and Death", "<light blue><bold>Slot B - Poison Strike", "<light yellow><bold>Slot C - None", "<light green><bold>Assist - None", "<light purple><bold>Special - Glimmer", "<bold>Refined: Slaying"
						set {_deadlord}'s helmet to leather helmet of protection 4
						set {_deadlord}'s chestplate to leather chestplate of protection 4
						set {_deadlord}'s leggings to leather leggings of protection 4
						set {_deadlord}'s boots to leather boots of protection 4
						set {class.%{_deadlord}%} to "Sniper"
						set {skillslot1.%{_deadlord}%} to "Heavy Draw"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 21:
						spawn 1 skeleton at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Forest's Breeze: Jamke"
						set {str.%{_deadlord}%} to 115
						set {def.%{_deadlord}%} to 65
						set {spd.%{_deadlord}%} to 55
						set {skl.%{_deadlord}%} to 75
						set {res.%{_deadlord}%} to 65
						set {lvl.%{_deadlord}%} to 75
						set the maximum health of {_deadlord} to 60
						set {_deadlord}'s tool to bow of power 5 named "<white><bold>Slaying Bow" with lore "<light red><bold>Slot A - Armour Smasher", "<light blue><bold>Slot B - Wrath", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - None", "<light purple><bold>Special - Astra", "<bold>Refined: Slaying"
						set {_deadlord}'s chestplate to leather chestplate of protection 5
						set {_deadlord}'s leggings to diamond leggings of protection 3
						set {_deadlord}'s boots to diamond boots of protection 3
						set {class.%{_deadlord}%} to "Sniper"
						set {skillslot1.%{_deadlord}%} to "Crushing Offense"
						set {skillslot2.%{_deadlord}%} to "Heavy Draw"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 22:
						spawn 1 skeleton at the entity
						apply swiftness 4 to the last spawned entity for 999 days
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Wind's Call: Lewyn"
						set {str.%{_deadlord}%} to 25
						set {def.%{_deadlord}%} to 25
						set {spd.%{_deadlord}%} to 150
						set {skl.%{_deadlord}%} to 75
						set {res.%{_deadlord}%} to 125
						set {lvl.%{_deadlord}%} to 95
						set the maximum health of {_deadlord} to 55
						set {_deadlord}'s tool to bow of power 10 named "<gold><bold>Forseti" with lore "<light red><bold>Slot A - Sorcery Aura", "<light blue><bold>Slot B - Desperation", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - None", "<light purple><bold>Special - Rising Wind", "<bold>Refined: Slaying"
						set {_deadlord}'s chestplate to leather chestplate of protection 5
						set {_deadlord}'s leggings to iron leggings of protection 3
						set {_deadlord}'s boots to iron boots of protection 3
						set {class.%{_deadlord}%} to "Sorcerer"
						set {skillslot1.%{_deadlord}%} to "Distant Defense"
						set {skillslot2.%{_deadlord}%} to "Heavy Draw"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 23:
						spawn 1 skeleton at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Kindly Priest: Wrys"
						set {str.%{_deadlord}%} to 66
						set {def.%{_deadlord}%} to 35
						set {spd.%{_deadlord}%} to 25
						set {skl.%{_deadlord}%} to 65
						set {res.%{_deadlord}%} to 80
						set {lvl.%{_deadlord}%} to 90
						set the maximum health of {_deadlord} to 70
						set {_deadlord}'s tool to bow of power 5 named "<white><bold>Slow" with lore "<light red><bold>Slot A - Close Counter", "<light blue><bold>Slot B - Sabotage Speed", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Restore", "<light purple><bold>Special - Glacies", "<bold>Refined: Slaying"
						set {_deadlord}'s helmet to leather helmet of protection 5
						set {_deadlord}'s chestplate to leather chestplate of protection 5
						set {_deadlord}'s leggings to leather leggings of protection 5
						set {_deadlord}'s boots to leather boots of protection 5
						set {class.%{_deadlord}%} to "Sage"
						set {skillslot1.%{_deadlord}%} to "Wrathful Staff"
						set {skillslot2.%{_deadlord}%} to "Brazen STR"
						set {skillslot3.%{_deadlord}%} to "Miracle"
						set {skillslot4.%{_deadlord}%} to "Distant Defence"
						set {skillslot5.%{_deadlord}%} to "Ranged Specialist"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 24:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Vanguard Legend: Ike"
						set {str.%{_deadlord}%} to 135
						set {def.%{_deadlord}%} to 80
						set {spd.%{_deadlord}%} to 65
						set {skl.%{_deadlord}%} to 80
						set {res.%{_deadlord}%} to 45
						set {lvl.%{_deadlord}%} to 90
						set the maximum health of {_deadlord} to 75
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Ragnell" with lore "<light red><bold>Slot A - Fierce Stance", "<light blue><bold>Slot B - Solar Brace", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Shove", "<light purple><bold>Special - Sol", "<bold>Refined: Unique"
						set {_deadlord}'s helmet to diamond helmet of protection 4
						set {_deadlord}'s chestplate to diamond chestplate of protection 4
						set {_deadlord}'s leggings to diamond leggings of protection 4
						set {_deadlord}'s boots to diamond boots of protection 4
						set {class.%{_deadlord}%} to "Hero"
						set {skillslot1.%{_deadlord}%} to "Crushing Offense"
						set {skillslot2.%{_deadlord}%} to "Vantage"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 25:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Lance of Legend: Finn"
						set {str.%{_deadlord}%} to 72
						set {def.%{_deadlord}%} to 60
						set {spd.%{_deadlord}%} to 100
						set {skl.%{_deadlord}%} to 70
						set {res.%{_deadlord}%} to 34
						set {lvl.%{_deadlord}%} to 90
						set the maximum health of {_deadlord} to 75
						set {_deadlord}'s tool to diamond shovel of sharpness 7 named "<white><bold>Diamond Lance" with lore "<light red><bold>Slot A - Life and Death", "<light blue><bold>Slot B - Brave Blade", "<light yellow><bold>Slot C - Breath of Life", "<light green><bold>Assist - Reposition", "<light purple><bold>Special - Luna", "<bold>Refined: Slaying"
						set {_deadlord}'s helmet to diamond helmet of protection 3
						set {_deadlord}'s chestplate to diamond chestplate of protection 3
						set {_deadlord}'s leggings to diamond leggings of protection 3
						set {_deadlord}'s boots to diamond boots of protection 3
						set {class.%{_deadlord}%} to "Lord"
						set {skillslot1.%{_deadlord}%} to "Double Lion"
						set {skillslot2.%{_deadlord}%} to "Crushing Offense"
						set {skillslot3.%{_deadlord}%} to "Miracle"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 26:
						spawn 1 zombie at the entity
						set {_deadlord} to the last spawned entity
						set the name of the last spawned entity to "<light red>Strong and Tough: Arden"
						set {str.%{_deadlord}%} to 80
						set {def.%{_deadlord}%} to 160
						set {spd.%{_deadlord}%} to 15
						set {skl.%{_deadlord}%} to 45
						set {res.%{_deadlord}%} to 15
						set {lvl.%{_deadlord}%} to 90
						set the maximum health of {_deadlord} to 90
						set {_deadlord}'s tool to diamond sword of sharpness 5 named "<bold>Slaying Edge" with lore "<light red><bold>Slot A - Steady Stance", "<light blue><bold>Slot B - Eclipse Brace", "<light yellow><bold>Slot C - DEF Smoke", "<light green><bold>Assist - None", "<light purple><bold>Special - Ignis", "<bold>Refined: Slaying"
						set {_deadlord}'s helmet to diamond helmet of protection 5
						set {_deadlord}'s chestplate to diamond chestplate of protection 5
						set {_deadlord}'s leggings to diamond leggings of protection 5
						set {_deadlord}'s boots to diamond boots of protection 5
						set {class.%{_deadlord}%} to "Chieftain"
						set {skillslot1.%{_deadlord}%} to "Unbreakable"
						set {skillslot2.%{_deadlord}%} to "Guard"
						set {skillslot3.%{_deadlord}%} to "Brazen STR"
						set {skillslot4.%{_deadlord}%} to "Brazen DEF"
						set {isBoss.%{_deadlord}%} to true
					else if {_name} is 27:
						spawn 1 skeleton at the entity
						set the name of the last spawned entity to "<light purple>Cantor"
						set {str.%{_deadlord}%} to 0
						set {def.%{_deadlord}%} to 0
						set {spd.%{_deadlord}%} to 0
						set {skl.%{_deadlord}%} to 0
						set {res.%{_deadlord}%} to 0
						set {lvl.%{_deadlord}%} to 60
						set the maximum health of {_deadlord} to 90
						set {_deadlord}'s tool to bow of power 3 named "<purple>Nosferatu" with lore "<light red><bold>Slot A - Sorcery Aura", "<light blue><bold>Slot B - Mystic Boost", "<light yellow><bold>Slot C - Gravity", "<light green><bold>Assist - None", "<light purple><bold>Special - Sol", "<bold>Refined: Slaying"
						set {_deadlord}'s helmet to diamond helmet of protection 5
						set {_deadlord}'s chestplate to diamond chestplate of protection 5
						set {_deadlord}'s leggings to diamond leggings of protection 5
						set {_deadlord}'s boots to diamond boots of protection 5
					set {_lvlbal} to 0
					loop all players in radius 256 of {_deadlord}:
						if loop-player is not npc:
							add {lvl.%loop-player%} to {_lvlbal}
							add ({promoted.%loop-player%} * 10) to {_lvlbal}
							add 1 to {_players}
					set {_lvlbal} to ({_lvlbal} / {_players}) + 10
					if {_lvlbal} is less than {lvl.%{_deadlord}%}:
						if {_lvlbal} is not 0:
							set {_balance} to abs({_lvlbal} - {lvl.%{_deadlord}%})
							loop {_balance} times:
								subtract 1 from {str.%{_deadlord}%}
								subtract 1 from {def.%{_deadlord}%}
								subtract 1 from {spd.%{_deadlord}%}
								subtract 1 from {skl.%{_deadlord}%}
								subtract 1 from {res.%{_deadlord}%}
								subtract 0.5 from the maximum health of {_deadlord}
								subtract 1 from {lvl.%{_deadlord}%}
					else if {_lvlbal} is more than {lvl.%{_deadlord}%}:
						set {_balance} to ({_lvlbal} - {lvl.%{_deadlord}%})
						loop {_balance} times:
							add 1 to {str.%{_deadlord}%}
							add 1 to {def.%{_deadlord}%}
							add 1 to {spd.%{_deadlord}%}
							add 1 to {skl.%{_deadlord}%}
							add 1 to {res.%{_deadlord}%}
							add 0.5 to the maximum health of {_deadlord}
							add 1 to {lvl.%{_deadlord}%}
					if the maximum health of {_deadlord} is less than 20:
						set the maximum health of {_deadlord} to 20
					if {spd.%{_deadlord}%} is more than 125:
						apply swiftness 5 to {_deadlord} for 1 day
					else if {spd.%{_deadlord}%} is more than 100:
						apply swiftness 4 to {_deadlord} for 1 day
					else if {spd.%{_deadlord}%} is more than 75:
						apply swiftness 3 to {_deadlord} for 1 day
					else if {spd.%{_deadlord}%} is more than 50:
						apply swiftness 2 to {_deadlord} for 1 day
					else if {spd.%{_deadlord}%} is more than 25:
						apply swiftness 1 to {_deadlord} for 1 day
					heal {_deadlord} by 999
					set {_loc} to location of block at the last spawned entity
					broadcast "<light red>Coordinates: %{_loc}%"
					broadcast "<light red>Level: %{lvl.%{_deadlord}%}%"
					broadcast "<light red>Weapon: %{_deadlord}'s tool%"
		if {_deadlord} is not set:
			if entity's world is "Alstair":
				loop all players in world "Alstair":
					if loop-player is not npc:
						add {lvl.%loop-player%} + 10 to {_moblvl}
						add ({promoted.%loop-player%} * 10) to {_moblvl}
						add 1 to {_players}
				set {_moblvl} to ({_moblvl} / {_players})
				set {_max} to {_moblvl} + 30
				set {_balancer} to {_moblvl}
				set {_moblvl} to a random integer from 1 to {_max}
				add floor({_balancer} / 2) to {_moblvl}
			else if entity's world is "Alstair_Nether":
				loop all players in world "Alstair_Nether":
					if loop-player is not npc:
						add {lvl.%loop-player%} to {_moblvl}
						add ({promoted.%loop-player%} * 10) to {_moblvl}
						add 1 to {_players}
				set {_moblvl} to ({_moblvl} / {_players})
				set {_max} to {_moblvl} + 30
				set {_balancer} to {_moblvl}
				set {_moblvl} to a random integer from 1 to {_max}
				add floor({_balancer} / 2) to {_moblvl}
			else if entity's world is "Alstair_End":
				loop all players in world "Alstair_End":
					if loop-player is not npc:
						add {lvl.%loop-player%} + 15 to {_moblvl}
						add ({promoted.%loop-player%} * 10) to {_moblvl}
						add 1 to {_players}
				set {_moblvl} to ({_moblvl} / {_players})
				set {_max} to {_moblvl} + 45
				set {_balancer} to {_moblvl}
				set {_moblvl} to a random integer from 1 to {_max}
				add floor({_balancer} / 2) to {_moblvl}
			else if entity's world is "adventure":
				loop all players in world "adventure":
					if loop-player is not npc:
						add {lvl.%loop-player%} + 5 to {_moblvl}
						add ({promoted.%loop-player%} * 10) to {_moblvl}
						add 1 to {_players}
				set {_moblvl} to ({_moblvl} / {_players})
				set {_max} to {_moblvl} + 15
				if {_max} is less than 0:
					set {_max} to 1
				set {_balancer} to {_moblvl} + 5
				set {_moblvl} to a random integer from 1 to {_max}
				add floor({_balancer} / 2) to {_moblvl}
			else if entity's world is "adventure_nether":
				loop all players in world "adventure_nether":
					if loop-player is not npc:
						add {lvl.%loop-player%} + 5 to {_moblvl}
						add ({promoted.%loop-player%} * 10) to {_moblvl}
						add 1 to {_players}
				set {_moblvl} to ({_moblvl} / {_players})
				set {_max} to {_moblvl} + 15
				set {_balancer} to {_moblvl}
				set {_moblvl} to a random integer from 1 to {_max}
				add floor({_balancer} / 2) to {_moblvl}
			else if entity's world is "adventure_the_end":
				loop all players in world "adventure_the_end":
					if loop-player is not npc:
						add {lvl.%loop-player%} + 5 to {_moblvl}
						add ({promoted.%loop-player%} * 10) to {_moblvl}
						add 1 to {_players}
				set {_moblvl} to ({_moblvl} / {_players})
				set {_max} to {_moblvl} + 15
				set {_balancer} to {_moblvl}
				set {_moblvl} to a random integer from 1 to {_max}
				add floor({_balancer} / 2) to {_moblvl}
			else if entity's world is "GenOne":
				loop all players in world "GenOne":
					if loop-player is not npc:
						add {lvl.%loop-player%} to {_moblvl}
						add ({promoted.%loop-player%} * 10) to {_moblvl}
						add 1 to {_players}
				set {_moblvl} to ({_moblvl} / {_players})
				set {_max} to {_moblvl} + 15
				if {_max} is less than 0:
					set {_max} to 1
				set {_balancer} to {_moblvl} - 5
				set {_moblvl} to a random integer from 1 to {_max}
				add floor({_balancer} / 2) to {_moblvl}
			if {_moblvl} is more than {_max}:
				set {_moblvl} to {_max}
			set {_moblvl} to floor({_moblvl})
			loop {_moblvl} times:
				#add 1 to {t_str.%entity%}
				chance of 80%:
					add 1 to {t_str.%entity%}
					chance of 35%:
						add 1 to {t_str.%entity%}
				#add 1 to {t_def.%entity%}
				chance of 65%:
					add 1 to {t_def.%entity%}
					chance of 25%:
						add 1 to {t_def.%entity%}
				#add 1 to {t_spd.%entity%}
				chance of 60%:
					add 1 to {t_spd.%entity%}
					chance of 20%:
						add 1 to {t_spd.%entity%}
				#add 1 to {t_skl.%entity%}
				chance of 70%:
					add 1 to {t_skl.%entity%}
					chance of 40%:
						add 1 to {t_skl.%entity%}
				#add 1 to {t_res.%entity%}
				chance of 65%:
					add 1 to {t_res.%entity%}
					chance of 25%:
						add 1 to {t_res.%entity%}
				add 0.5 to the entity's maximum health
				chance of 80%:
					add 0.5 to the entity's maximum health
					chance of 30%:
						add 0.5 to the entity's maximum health
			set {t_lvl.%entity%} to {_moblvl}
			heal the entity by 999
			if the entity's maximum health is more than 1000:
				chance of 25%:
					set the entity's maximum health to 500
					set the entity's name to "<gold>Treasure %entity%"
					apply weakness 4 to the entity for 1 hour
					apply swiftness 4 to the entity for 1 hour
					set the entity's helmet to gold helmet of protection 4
					set the entity's chestplate to gold chestplate of protection 4
					set the entity's leggings to gold leggings of protection 4
					set the entity's boots to gold boots of protection 4
					if entity is a zombie:
						set the entity's tool to gold sword of looting 5 named "<gold>Fortune Sword" with lore "<light red><bold>Slot A - None", "<light blue><bold>Slot B - Despoil"
					else if entity is a skeleton:
						set the entity's tool to bow of looting 5 named "<gold>Fortune Bow" with lore "<light red><bold>Slot A - None", "<light blue><bold>Slot B - Despoil"
					loop all players:
						send "<gold>A %entity's name% has appeared!" to loop-player
						set {_loc} to location of block at the entity
						send "<gold>Coordinates: %{_loc}%" to loop-player
				else:
					chance of 75%:
						cancel event
					else:
						loop 19 times:
							if entity is zombie:
								spawn 1 zombie at the entity
							else if entity is skeleton:
								spawn 1 skeleton at the entity
							else if entity is spider:
								spawn 1 spider at the entity
							else if entity is creeper:
								spawn 1 creeper at the entity
							else if entity is zombie pigman:
								spawn 1 zombie pigman at the entity
							else if entity is enderman:
								spawn 1 enderman at the entity
						loop all players:
							send "<light purple>A %entity% horde approaches!" to loop-player
							set {_loc} to location of block at the entity
							send "<light purple>Coordinates: %{_loc}%" to loop-player
			if {_deadlord} is not set:
				if entity is zombie:
					humanoidEquipmentHandler(entity,{t_lvl.%entity%},0)
					if {t_lvl.%entity%} is more than 20:
						chance of (({t_lvl.%entity%} / 4) - 19)%:
							set metadata value "isMimic" of the entity to 1
						else:
							chance of (({t_lvl.%entity%} / 4) - 29)%:
								set metadata value "isMalediction" of the entity to 1
							else:
								chance of (({t_lvl.%entity%} / 4) - 49)%:
									set metadata value "isRegret" of the entity to 1
								else:
									chance of (({t_lvl.%entity%} / 4) - 89)%:
										set metadata value "isZPurgia" of the entity to 1
				else if entity is skeleton:
					humanoidEquipmentHandler(entity,{t_lvl.%entity%},1)
					if {t_lvl.%entity%} is more than 20:
						chance of (({t_lvl.%entity%} / 4) - 19)%:
							set metadata value "isMimic" of the entity to 1
						else:
							chance of (({t_lvl.%entity%} / 4) - 29)%:
								set metadata value "isMalediction" of the entity to 1
							else:
								chance of (({t_lvl.%entity%} / 4) - 49)%:
									set metadata value "isEnrapture" of the entity to 1
								else:
									chance of (({t_lvl.%entity%} / 4) - 89)%:
										set metadata value "isSPurgia" of the entity to 1
				else if entity is creeper:
					if {t_lvl.%entity%} is more than 20:
						chance of (({t_lvl.%entity%} / 4) - 19)%:
							set metadata value "isSkulker" of the entity to 1
						else:
							chance of (({t_lvl.%entity%} / 4) - 29)%:
								set metadata value "isStalker" of the entity to 1
							else:
								chance of (({t_lvl.%entity%} / 4) - 49)%:
									set metadata value "isMalediction" of the entity to 1
								else:
									chance of (({t_lvl.%entity%} / 4) - 89)%:
										set metadata value "isCPurgia" of the entity to 1
				else if entity is spider:
					if {t_lvl.%entity%} is more than 20:
						chance of (({t_lvl.%entity%} / 4) - 19)%:
							set metadata value "isVenomSpider" of the entity to 1
						else:
							chance of (({t_lvl.%entity%} / 4) - 29)%:
								set metadata value "isShadow" of the entity to 1
							else:
								chance of (({t_lvl.%entity%} / 4) - 49)%:
									set metadata value "isMalediction" of the entity to 1
				else if entity is zombie pigman:
					humanoidEquipmentHandler(entity,{t_lvl.%entity%},0)
					if {t_lvl.%entity%} is more than 20:
						chance of (({t_lvl.%entity%} / 4) - 19)%:
							set metadata value "isMimic" of the entity to 1
						else:
							chance of (({t_lvl.%entity%} / 4) - 29)%:
								set metadata value "isMalediction" of the entity to 1
							else:
								chance of (({t_lvl.%entity%} / 4) - 49)%:
									set metadata value "isRegret" of the entity to 1
								else:
									chance of (({t_lvl.%entity%} / 4) - 89)%:
										set metadata value "isZPPurgia" of the entity to 1
				
					
		
on spawn of ender dragon:
	if entity's world is "Alstair_End":
		set {t_str.%entity%} to 90
		set {t_def.%entity%} to 90
		set {t_spd.%entity%} to 90
		set {t_skl.%entity%} to 90
		set {t_res.%entity%} to 90
		loop all players in world:
			add {lvl.%loop-player%} to {_moblvl}
			add 1 to {_players}
		set {_balance} to 100 - ({_moblvl} / {_players})
		if {_balance} is less than 1:
			set {_balance} to abs({_balance} + 15)
			loop {_balance} times:
				add 1 to {t_str.%entity%}
				add 1 to {t_def.%entity%}
				add 1 to {t_spd.%entity%}
				add 1 to {t_skl.%entity%}
				add 1 to {t_res.%entity%}
				add 3 to the entity's maximum health
		heal the entity by 9999
		set {isBoss.%entity%} to true
		set the entity's name to "<light red>Yied"
		apply strength 3 to the last spawned entity for 1 day
		apply swiftness 3 to the last spawned entity for 1 day
		apply resistance 3 to the last spawned entity for 1 day
		set {_temp} to the entity's maximum health
		set the entity's maximum health to {_temp} * 2
		heal the entity by 9000
		broadcast "<light red>An ancient foe awakens..."
		broadcast "<light red>Level: %100 + {_balance}%"
		broadcast "<light red>STR/SPD/DEF/MAG/SKL: %{t_str.%entity%}%"
		spawn 1 zombie at location at 25, 68, -5
		set {_deadlord} to the last spawned entity
		apply swiftness 6 to the last spawned entity for 999 days
		set the name of the last spawned entity to "<red><bold>Risen Lord: Helmund"
		set {t_str.%{_deadlord}%} to 90
		set {t_def.%{_deadlord}%} to 90
		set {t_spd.%{_deadlord}%} to 90
		set {t_skl.%{_deadlord}%} to 90
		set {t_res.%{_deadlord}%} to 90
		set {t_lvl.%{_deadlord}%} to 90
		set the maximum health of {_deadlord} to 240
		set {_deadlord}'s tool to diamond sword of sharpness 10 named "<gold><bold>Undying Oath" with lore "<light red><bold>Slot A - Deathly Duel", "<light blue><bold>Slot B - Wrath", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Fortify Health", "<light purple><bold>Special - Retribution", "<light cyan><bold>Refined: Warding", "<white>A terrifying blade of unkown origin.", "<white>The diamond core seems to pulse with demonic energy.", "<white>None who have met the undead terror have lived to tell the tale..."
		set {_deadlord}'s helmet to diamond helmet of protection 10
		set {_deadlord}'s chestplate to diamond chestplate of protection 10
		set {_deadlord}'s leggings to diamond leggings of protection 10
		set {_deadlord}'s boots to diamond boots of protection 10
		set {t_class.%{_deadlord}%} to "Lord"
		set {skillslot1.%{_deadlord}%} to "Double Lion"
		set {skillslot2.%{_deadlord}%} to "Crusader's Ward"
		set {skillslot3.%{_deadlord}%} to "Vantage"
		set {skillslot4.%{_deadlord}%} to "Draconic Rage"
		set {skillslot5.%{_deadlord}%} to "Miracle"
		set {isBoss.%{_deadlord}%} to true
		apply swiftness 3 to {_deadlord}
		if {_balance} is less than 1:
			set {_balance} to abs({_balance} + 15)
			loop {_balance} times:
				add 1 to {t_str.%{_deadlord}%}
				add 1 to {t_def.%{_deadlord}%}
				add 1 to {t_spd.%{_deadlord}%}
				add 1 to {t_skl.%{_deadlord}%}
				add 1 to {t_res.%{_deadlord}%}
				add 2 to {_deadlord}'s maximum health
		heal the entity by 9999
		set {alstairBossBarHealth::tmp} to new boss bar
		loop all players in world "Alstair_End":
			add loop-player to {alstairBossBarHealth::*}
		set {_bossbar} to {alstairBossBarHealth::tmp}
		set title of bossbar {_bossbar} to "<red><bold>Lord Alstair"
		set progress of bossbar {_bossbar} to 1
		show boss bar {_bossbar}
		broadcast "<light red>Helmund's army approaches..."
		loop 10 times:
			#broadcast "<light red>A fallen hero has arisen..."
			set {_name} to a random integer from 1 to 26
			set {_loc} to location of block at entity
			if {_name} is 1:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Hero of Prophecy: Alm"
				set {t_str.%{_deadlord}%} to 85
				set {t_def.%{_deadlord}%} to 55
				set {t_spd.%{_deadlord}%} to 65
				set {skl.%{_deadlord}%} to 120
				set {t_res.%{_deadlord}%} to 30
				set the maximum health of {_deadlord} to 80
				set {lvl.%{_deadlord}%} to 90
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Falchion" with lore "Slot A - Armour Smasher", "Slot B - Brave Blade", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Luna", "<red><bold>Refined: Reinforced"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Lord"
				set {skillslot1.%{_deadlord}%} to "Double Lion"
				set {skillslot2.%{_deadlord}%} to "Lord's Blood"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 2:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Young Lion: Roy"
				set {t_str.%{_deadlord}%} to 65
				set {t_def.%{_deadlord}%} to 70
				set {t_spd.%{_deadlord}%} to 55
				set {skl.%{_deadlord}%} to 80
				set {t_res.%{_deadlord}%} to 85
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 85
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Binding Blade" with lore "<light red><bold>Slot A - Close Defence", "<light blue><bold>Slot B - Sabotage Attack", "<light yellow><bold>Slot C - Pressure STR", "<light green><bold>Assist - Reposition", "<light purple><bold>Special - Dragon Fang", "<bold>Refined: Unique"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Lord"
				set {skillslot1.%{_deadlord}%} to "Distant Defence"
				set {skillslot2.%{_deadlord}%} to "Sword Specialist"
				set {skillslot3.%{_deadlord}%} to "Lord's Blood"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 3:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Scarlett Sword: Navarre"
				apply swiftness 4 to the entity for 999 days
				set {t_str.%{_deadlord}%} to 120
				set {t_def.%{_deadlord}%} to 29
				set {t_spd.%{_deadlord}%} to 160
				set {skl.%{_deadlord}%} to 175
				set {t_res.%{_deadlord}%} to 25
				set {lvl.%{_deadlord}%} to 75
				set the maximum health of {_deadlord} to 60
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<red><bold>Scarlett Sword" with lore "<light red><bold>Slot A - Armour Smasher", "<light blue><bold>Slot B - Desperation", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - Rally Speed", "<light purple><bold>Special - Galeforce", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to leather helmet of protection 5
				set {_deadlord}'s chestplate to leather chestplate of protection 5
				set {_deadlord}'s leggings to leather leggings of protection 5
				set {_deadlord}'s boots to leather boots of protection 5
				set {class.%{_deadlord}%} to "Swordmaster"
				set {skillslot1.%{_deadlord}%} to "Vantage"
				set {skillslot2.%{_deadlord}%} to "Sword Specialist"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 4:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Altean Sniper: Jeorge"
				apply swiftness 4 to the entity for 999 days
				set {t_str.%{_deadlord}%} to 120
				set {t_def.%{_deadlord}%} to 10
				set {t_spd.%{_deadlord}%} to 120
				set {skl.%{_deadlord}%} to 175
				set {t_res.%{_deadlord}%} to 10
				set {lvl.%{_deadlord}%} to 75
				set the maximum health of {_deadlord} to 70
				set {_deadlord}'s tool to bow of power 5 named "<gold><bold>Parthia" with lore "<light red><bold>Slot A - Close Counter", "<light blue><bold>Slot B - Sabotage Speed", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - None", "<light purple><bold>Special - Moonbow", "<bold>Refined: Unique"
				set {_deadlord}'s helmet to gold helmet of protection 4
				set {_deadlord}'s chestplate to gold chestplate of protection 4
				set {_deadlord}'s leggings to gold leggings of protection 4
				set {_deadlord}'s boots to gold boots of protection 4
				set {class.%{_deadlord}%} to "Sniper"
				set {skillslot1.%{_deadlord}%} to "Distant Defence"
				set {skillslot2.%{_deadlord}%} to "Heavy Draw"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 5:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Chosen Undead: Skiddlezz"
				set {t_str.%{_deadlord}%} to 120
				set {t_def.%{_deadlord}%} to 255
				set {t_spd.%{_deadlord}%} to 100
				set {skl.%{_deadlord}%} to 90
				set {t_res.%{_deadlord}%} to 100
				set {lvl.%{_deadlord}%} to 150
				set the maximum health of {_deadlord} to 135
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Balder Side Sword" with lore "<light red><bold>Slot A - Close Defence", "<light blue><bold>Slot B - Riposte", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Ignis", "<bold>Refined: Unique"
				set {_deadlord}'s helmet to diamond helmet 
				set {_deadlord}'s chestplate to diamond chestplate 
				set {_deadlord}'s leggings to diamond leggings 
				set {_deadlord}'s boots to diamond boots 
				set {class.%{_deadlord}%} to "Chieftain"
				set {skillslot1.%{_deadlord}%} to "Distant Defence"
				set {skillslot2.%{_deadlord}%} to "Axe Specialist"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 6:
				spawn 1 zombie at location at 25, 68, -5
				set the name of the last spawned entity to "<light red>Holy Knight: Sigurd"
				set {_deadlord} to the last spawned entity
				spawn 1 horse at the entity
				apply swiftness 3 to the last spawned entity
				apply resistance 3 to the last spawned entity
				set {t_str.%{_deadlord}%} to 95
				set {t_def.%{_deadlord}%} to 60
				set {t_spd.%{_deadlord}%} to 55
				set {skl.%{_deadlord}%} to 85
				set {t_res.%{_deadlord}%} to 30
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 90
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Divine Tyrfing" with lore "<light red><bold>Slot A - Distant Counter", "<light blue><bold>Slot B - Eclipse Brace", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Luna", "<bold>Refined: Koenig"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Crusader"
				set {skillslot1.%{_deadlord}%} to "Crusader's Ward"
				set {skillslot2.%{_deadlord}%} to "Sword Specialist"
				set {skillslot3.%{_deadlord}%} to "Crusader's Blood"
				set {skillslot4.%{_deadlord}%} to "Lord's Blood"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 7:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Divine Dragon: Tiki"
				set {t_str.%{_deadlord}%} to 30
				set {t_def.%{_deadlord}%} to 100
				set {t_spd.%{_deadlord}%} to 60
				set {skl.%{_deadlord}%} to 80
				set {t_res.%{_deadlord}%} to 120
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 70
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<orange><bold>Flametounge" with lore "<light red><bold>Slot A - Distant Counter", "<light blue><bold>Slot B - Sabotage Speed", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Glacies", "<bold>Refined: Warding"
				set {_deadlord}'s helmet to diamond helmet 
				set {_deadlord}'s chestplate to diamond chestplate 
				set {_deadlord}'s leggings to diamond leggings 
				set {_deadlord}'s boots to diamond boots 
				set {class.%{_deadlord}%} to "Divine Dragon"
				set {skillslot1.%{_deadlord}%} to "Draconic Rage"
				set {skillslot2.%{_deadlord}%} to "Brazen Spectrum"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 8:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Hero of Prophecy: Alm"
				set {t_str.%{_deadlord}%} to 85
				set {t_def.%{_deadlord}%} to 55
				set {t_spd.%{_deadlord}%} to 65
				set {skl.%{_deadlord}%} to 120
				set {t_res.%{_deadlord}%} to 30
				set the maximum health of {_deadlord} to 80
				set {lvl.%{_deadlord}%} to 90
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Falchion" with lore "Slot A - Armour Smasher", "Slot B - Brave Blade", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Luna", "<red><bold>Refined: Reinforced"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Lord"
				set {skillslot1.%{_deadlord}%} to "Double Lion"
				set {skillslot2.%{_deadlord}%} to "Lord's Blood"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 9:
				spawn 1 zombie at location at 25, 68, -5
				set the name of the last spawned entity to "<light red>Thunder's Sword: Reinhardt"
				set {_deadlord} to the last spawned entity
				spawn 1 horse at the entity
				apply swiftness 3 to the last spawned entity
				apply resistance 3 to the last spawned entity
				set {t_str.%{_deadlord}%} to 85
				set {t_def.%{_deadlord}%} to 65
				set {t_spd.%{_deadlord}%} to 35
				set {skl.%{_deadlord}%} to 80
				set {t_res.%{_deadlord}%} to 65
				set {lvl.%{_deadlord}%} to 80
				set the maximum health of {_deadlord} to 80
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Meisterschwert" with lore "<light red><bold>Slot A - Distant Counter", "<light blue><bold>Slot B - Shield Pulse", "<light yellow><bold>Slot C - STR Authority", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Pavise", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Mage Knight"
				set {skillslot1.%{_deadlord}%} to "Brazen Spectrum"
				set {skillslot2.%{_deadlord}%} to "Brazen STR"
				set {skillslot3.%{_deadlord}%} to "Brazen DEF"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 10:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Blazing Tactician: Lukas"
				set {t_str.%{_deadlord}%} to 65
				set {t_def.%{_deadlord}%} to 65
				set {t_spd.%{_deadlord}%} to 65
				set {skl.%{_deadlord}%} to 65
				set {t_res.%{_deadlord}%} to 65
				set {lvl.%{_deadlord}%} to 80
				set the maximum health of {_deadlord} to 85
				set {_deadlord}'s tool to diamond sword of sharpness 5, fire aspect 1 and knockback 2 named "<yellow><bold>The Grandmaster" with lore "<light red><bold>Slot A - Defiant Resistance", "<light blue><bold>Slot B - Wrath", "<light yellow><bold>Slot C - Pressure STR", "<light green><bold>Assist - Rally Attack", "<light purple><bold>Special - Moonbow", "<bold>Refined: Koenig"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Grandmaster"
				set {skillslot1.%{_deadlord}%} to "Brazen Spectrum"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 11:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Kindled Spirit: Katarina"
				set {t_str.%{_deadlord}%} to 40
				set {t_def.%{_deadlord}%} to 65
				set {t_spd.%{_deadlord}%} to 80
				set {skl.%{_deadlord}%} to 60
				set {t_res.%{_deadlord}%} to 125
				set {lvl.%{_deadlord}%} to 80
				set the maximum health of {_deadlord} to 70
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<teal><bold>Dragon's Talons" with lore "<light red><bold>Slot A - Warding Stance", "<light blue><bold>Slot B - Bonus Blade", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - Hit and Run", "<light purple><bold>Special - Ignis", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to chainmail helmet of protection 6
				set {_deadlord}'s chestplate to chainmail chestplate of protection 6
				set {_deadlord}'s leggings to chainmail leggings of protection 6
				set {_deadlord}'s boots to chainmail boots of protection 6
				set {class.%{_deadlord}%} to "Dragonborn"
				set {skillslot1.%{_deadlord}%} to "Draconic Rage"
				set {skillslot2.%{_deadlord}%} to "Brazen MAG"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 12:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Warrior Priestess: Celica"
				set {t_str.%{_deadlord}%} to 45
				set {t_def.%{_deadlord}%} to 45
				set {t_spd.%{_deadlord}%} to 65
				set {skl.%{_deadlord}%} to 80
				set {t_res.%{_deadlord}%} to 100
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 60
				set {_deadlord}'s tool to bow of power 7 and punch 2 named "<gold><bold>Ragnarok" with lore "<light red><bold>Slot A - Sorcery Blade", "<light blue><bold>Slot B - Bonus Blade", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - None", "<light purple><bold>Special - Growing Light", "<bold>Refined: Slaying"
				set {_deadlord}'s chestplate to leather chestplate of protection 5
				set {_deadlord}'s leggings to leather leggings of protection 5
				set {_deadlord}'s boots to leather boots of protection 5
				set {class.%{_deadlord}%} to "Sorcerer"
				set {skillslot1.%{_deadlord}%} to "Brazen MAG"
				set {skillslot2.%{_deadlord}%} to "Brazen SPD"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 13:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Young Light: Leif"
				set {t_str.%{_deadlord}%} to 50
				set {t_def.%{_deadlord}%} to 75
				set {t_spd.%{_deadlord}%} to 115
				set {skl.%{_deadlord}%} to 135
				set {t_res.%{_deadlord}%} to 75
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 65
				set {_deadlord}'s tool to gold sword of sharpness 10 and unbreaking 10 named "<gold><bold>Light Brand" with lore "<light red><bold>Slot A - Sorcery Aura", "<light blue><bold>Slot B - Wrath", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - None", "<light purple><bold>Special - Blazing Light", "<bold>Refined: Reinforced"
				set {_deadlord}'s helmet to gold helmet of protection 5
				set {_deadlord}'s chestplate to gold chestplate of protection 5
				set {_deadlord}'s leggings to gold leggings of protection 5
				set {_deadlord}'s boots to gold boots of protection 5
				set {class.%{_deadlord}%} to "Junior Lord"
				set {skillslot1.%{_deadlord}%} to "Brazen MAG"
				set {skillslot2.%{_deadlord}%} to "Crushing Offense"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 14:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Scion of Light: Seliph"
				set {t_str.%{_deadlord}%} to 65
				set {t_def.%{_deadlord}%} to 100
				set {t_spd.%{_deadlord}%} to 45
				set {skl.%{_deadlord}%} to 55
				set {t_res.%{_deadlord}%} to 45
				set {lvl.%{_deadlord}%} to 75
				set the maximum health of {_deadlord} to 65
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Tyrfing" with lore "<light red><bold>Slot A - Distant Defence", "<light blue><bold>Slot B - Brash Assault", "<light yellow><bold>Slot C - STR Smoke", "<light green><bold>Assist - Shove", "<light purple><bold>Special - Ignis", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to diamond helmet of protection 3
				set {_deadlord}'s chestplate to diamond chestplate of protection 3
				set {_deadlord}'s leggings to diamond leggings of projectile protection 3
				set {_deadlord}'s boots to diamond boots of projectile protection 3
				set {class.%{_deadlord}%} to "Junior Lord"
				set {skillslot1.%{_deadlord}%} to "Crusader's Ward"
				set {skillslot2.%{_deadlord}%} to "Brazen DEF"
				set {skillslot3.%{_deadlord}%} to "Crusader's Blood"
				set {skillslot4.%{_deadlord}%} to "Lord's Blood"
				set {skillslot5.%{_deadlord}%} to "Steady Breath"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 15:
				spawn 1 zombie at location at 25, 68, -5
				set the name of the last spawned entity to "<light red>Lionheart: Eldigan"
				set {_deadlord} to the last spawned entity
				spawn 1 horse at the entity
				apply swiftness 3 to the last spawned entity
				apply resistance 3 to the last spawned entity
				set {t_str.%{_deadlord}%} to 75
				set {t_def.%{_deadlord}%} to 65
				set {t_spd.%{_deadlord}%} to 60
				set {skl.%{_deadlord}%} to 75
				set {t_res.%{_deadlord}%} to 40
				set {lvl.%{_deadlord}%} to 75
				set the maximum health of {_deadlord} to 70
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Mystletainn" with lore "<light red><bold>Slot A - Fury", "<light blue><bold>Slot B - Sabotage Defense", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - None", "<light purple><bold>Special - Retribution", "<bold>Refined: Unique"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Crusader"
				set {skillslot1.%{_deadlord}%} to "Brazen SKL"
				set {skillslot2.%{_deadlord}%} to "Brazen STR"
				set {skillslot3.%{_deadlord}%} to "Crusader's Blood"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 16:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Peerless Fighter: Raven"
				set {t_str.%{_deadlord}%} to 100
				set {t_def.%{_deadlord}%} to 35
				set {t_spd.%{_deadlord}%} to 135
				set {skl.%{_deadlord}%} to 100
				set {t_res.%{_deadlord}%} to 10
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 60
				set {_deadlord}'s tool to diamond axe of sharpness 5 named "<gold><bold>Basilikos" with lore "<light red><bold>Slot A - Life and Death", "<light blue><bold>Slot B - Sabotage Defense", "<light yellow><bold>Slot C - None", "<light green><bold>Assist - None", "<light purple><bold>Special - Rising Wind", "<bold>Refined: Crushing"
				set {_deadlord}'s helmet to chainmail helmet of protection 6
				set {_deadlord}'s chestplate to chainmail chestplate of protection 6
				set {_deadlord}'s leggings to chainmail leggings of protection 6
				set {_deadlord}'s boots to chainmail boots of protection 6
				set {class.%{_deadlord}%} to "Barbarian"
				set {skillslot1.%{_deadlord}%} to "Crushing Offense"
				set {skillslot2.%{_deadlord}%} to "Brazen STR"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 17:
				spawn 1 zombie at location at 25, 68, -5
				set the name of the last spawned entity to "<light red>Thunder's Fist: Reinhardt"
				set {_deadlord} to the last spawned entity
				spawn 1 horse at the entity
				apply swiftness 3 to the last spawned entity
				apply resistance 3 to the last spawned entity
				make {_deadlord} ride the last spawned entity
				set {t_str.%{_deadlord}%} to 55
				set {t_def.%{_deadlord}%} to 55
				set {t_spd.%{_deadlord}%} to 20
				set {skl.%{_deadlord}%} to 55
				set {t_res.%{_deadlord}%} to 80
				set {lvl.%{_deadlord}%} to 80
				set the maximum health of {_deadlord} to 40
				set {_deadlord}'s tool to bow of power 5 and punch 2 named "<gold><bold>Dire Thunder" with lore "<light red><bold>Slot A - Sorcery Aura", "<light blue><bold>Slot B - Eclipse Brace", "<light yellow><bold>Slot C - None", "<light green><bold>Assist - None", "<light purple><bold>Special - Moonbow", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to leather helmet of protection 5
				set {_deadlord}'s chestplate to diamond chestplate of protection 2
				set {_deadlord}'s leggings to leather leggings of protection 5
				set {_deadlord}'s boots to leather boots of protection 5
				set {class.%{_deadlord}%} to "Mage Knight"
				set {skillslot1.%{_deadlord}%} to "Distant Defence"
				set {skillslot2.%{_deadlord}%} to "Brazen MAG"
				set {skillslot3.%{_deadlord}%} to "Brazen Spectrum"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 18:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Hero of Prophecy: Alm"
				set {t_str.%{_deadlord}%} to 85
				set {t_def.%{_deadlord}%} to 55
				set {t_spd.%{_deadlord}%} to 65
				set {skl.%{_deadlord}%} to 120
				set {t_res.%{_deadlord}%} to 30
				set the maximum health of {_deadlord} to 80
				set {lvl.%{_deadlord}%} to 90
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Falchion" with lore "Slot A - Armour Smasher", "Slot B - Brave Blade", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Luna", "<red><bold>Refined: Reinforced"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Lord"
				set {skillslot1.%{_deadlord}%} to "Double Lion"
				set {skillslot2.%{_deadlord}%} to "Lord's Blood"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 19:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Hero of Yore: Marth"
				set {t_str.%{_deadlord}%} to 150
				set {t_def.%{_deadlord}%} to 150
				set {t_spd.%{_deadlord}%} to 150
				set {skl.%{_deadlord}%} to 150
				set {t_res.%{_deadlord}%} to 150
				set {lvl.%{_deadlord}%} to 120
				set the maximum health of {_deadlord} to 100
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Falchion" with lore "<light red><bold>Slot A - Armour Smasher", "<light blue><bold>Slot B - Desperation", "<light yellow><bold>Slot C - Pressure STR", "<light green><bold>Assist - Rally Spectrum", "<light purple><bold>Special - Growing Light", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to gold helmet of protection 10 and unbreaking 15
				set {_deadlord}'s chestplate to diamond chestplate of protection 10 and unbreaking 10
				set {_deadlord}'s leggings to diamond leggings of protection 10 and unbreaking 10
				set {_deadlord}'s boots to diamond boots of protection 10 and unbreaking 10
				set {class.%{_deadlord}%} to "Lord"
				set {skillslot1.%{_deadlord}%} to "Lord's Blood"
				set {skillslot2.%{_deadlord}%} to "Brazen Spectrum"
				set {skillslot3.%{_deadlord}%} to "Crushing Offense"
				set {skillslot4.%{_deadlord}%} to "Vantage"
				set {skillslot5.%{_deadlord}%} to "Brazen STR"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 20:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Shadowed Sniper: Clarisse"
				set {t_str.%{_deadlord}%} to 80
				set {t_def.%{_deadlord}%} to 30
				set {t_spd.%{_deadlord}%} to 65
				set {skl.%{_deadlord}%} to 55
				set {t_res.%{_deadlord}%} to 25
				set {lvl.%{_deadlord}%} to 60
				set the maximum health of {_deadlord} to 45
				set {_deadlord}'s tool to bow of power 5 named "<white><bold>Clarisse's Bow" with lore "<light red><bold>Slot A - Life and Death", "<light blue><bold>Slot B - Poison Strike", "<light yellow><bold>Slot C - None", "<light green><bold>Assist - None", "<light purple><bold>Special - Glimmer", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to leather helmet of protection 4
				set {_deadlord}'s chestplate to leather chestplate of protection 4
				set {_deadlord}'s leggings to leather leggings of protection 4
				set {_deadlord}'s boots to leather boots of protection 4
				set {class.%{_deadlord}%} to "Sniper"
				set {skillslot1.%{_deadlord}%} to "Heavy Draw"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 21:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Forest's Breeze: Jamke"
				set {t_str.%{_deadlord}%} to 115
				set {t_def.%{_deadlord}%} to 65
				set {t_spd.%{_deadlord}%} to 55
				set {skl.%{_deadlord}%} to 75
				set {t_res.%{_deadlord}%} to 65
				set {lvl.%{_deadlord}%} to 75
				set the maximum health of {_deadlord} to 60
				set {_deadlord}'s tool to bow of power 5 named "<white><bold>Slaying Bow" with lore "<light red><bold>Slot A - Armour Smasher", "<light blue><bold>Slot B - Wrath", "<light yellow><bold>Slot C - Savage Blow", "<light green><bold>Assist - None", "<light purple><bold>Special - Astra", "<bold>Refined: Slaying"
				set {_deadlord}'s chestplate to leather chestplate of protection 5
				set {_deadlord}'s leggings to diamond leggings of protection 3
				set {_deadlord}'s boots to diamond boots of protection 3
				set {class.%{_deadlord}%} to "Sniper"
				set {skillslot1.%{_deadlord}%} to "Crushing Offense"
				set {skillslot2.%{_deadlord}%} to "Heavy Draw"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 22:
				spawn 1 zombie at location at 25, 68, -5
				apply swiftness 4 to the last spawned entity for 999 days
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Wind's Call: Lewyn"
				set {t_str.%{_deadlord}%} to 25
				set {t_def.%{_deadlord}%} to 25
				set {t_spd.%{_deadlord}%} to 150
				set {skl.%{_deadlord}%} to 75
				set {t_res.%{_deadlord}%} to 125
				set {lvl.%{_deadlord}%} to 95
				set the maximum health of {_deadlord} to 55
				set {_deadlord}'s tool to bow of power 10 named "<gold><bold>Forseti" with lore "<light red><bold>Slot A - Sorcery Aura", "<light blue><bold>Slot B - Desperation", "<light yellow><bold>Slot C - Pressure MAG", "<light green><bold>Assist - None", "<light purple><bold>Special - Rising Wind", "<bold>Refined: Slaying"
				set {_deadlord}'s chestplate to leather chestplate of protection 5
				set {_deadlord}'s leggings to iron leggings of protection 3
				set {_deadlord}'s boots to iron boots of protection 3
				set {class.%{_deadlord}%} to "Sorcerer"
				set {skillslot1.%{_deadlord}%} to "Distant Defense"
				set {skillslot2.%{_deadlord}%} to "Heavy Draw"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 23:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Kindly Priest: Wrys"
				set {t_str.%{_deadlord}%} to 66
				set {t_def.%{_deadlord}%} to 35
				set {t_spd.%{_deadlord}%} to 25
				set {skl.%{_deadlord}%} to 65
				set {t_res.%{_deadlord}%} to 80
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 70
				set {_deadlord}'s tool to bow of power 5 named "<white><bold>Slow" with lore "<light red><bold>Slot A - Close Counter", "<light blue><bold>Slot B - Sabotage Speed", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Restore", "<light purple><bold>Special - Glacies", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to leather helmet of protection 5
				set {_deadlord}'s chestplate to leather chestplate of protection 5
				set {_deadlord}'s leggings to leather leggings of protection 5
				set {_deadlord}'s boots to leather boots of protection 5
				set {class.%{_deadlord}%} to "Sage"
				set {skillslot1.%{_deadlord}%} to "Wrathful Staff"
				set {skillslot2.%{_deadlord}%} to "Brazen STR"
				set {skillslot3.%{_deadlord}%} to "Miracle"
				set {skillslot4.%{_deadlord}%} to "Distant Defence"
				set {skillslot5.%{_deadlord}%} to "Ranged Specialist"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 24:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Vanguard Legend: Ike"
				set {t_str.%{_deadlord}%} to 135
				set {t_def.%{_deadlord}%} to 80
				set {t_spd.%{_deadlord}%} to 65
				set {skl.%{_deadlord}%} to 80
				set {t_res.%{_deadlord}%} to 45
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 75
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<gold><bold>Ragnell" with lore "<light red><bold>Slot A - Fierce Stance", "<light blue><bold>Slot B - Solar Brace", "<light yellow><bold>Slot C - Pressure DEF", "<light green><bold>Assist - Shove", "<light purple><bold>Special - Sol", "<bold>Refined: Unique"
				set {_deadlord}'s helmet to diamond helmet of protection 4
				set {_deadlord}'s chestplate to diamond chestplate of protection 4
				set {_deadlord}'s leggings to diamond leggings of protection 4
				set {_deadlord}'s boots to diamond boots of protection 4
				set {class.%{_deadlord}%} to "Hero"
				set {skillslot1.%{_deadlord}%} to "Crushing Offense"
				set {skillslot2.%{_deadlord}%} to "Vantage"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 25:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Lance of Legend: Finn"
				set {t_str.%{_deadlord}%} to 72
				set {t_def.%{_deadlord}%} to 60
				set {t_spd.%{_deadlord}%} to 100
				set {skl.%{_deadlord}%} to 70
				set {t_res.%{_deadlord}%} to 34
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 75
				set {_deadlord}'s tool to diamond shovel of sharpness 7 named "<white><bold>Diamond Lance" with lore "<light red><bold>Slot A - Life and Death", "<light blue><bold>Slot B - Brave Blade", "<light yellow><bold>Slot C - Breath of Life", "<light green><bold>Assist - Reposition", "<light purple><bold>Special - Luna", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to diamond helmet of protection 3
				set {_deadlord}'s chestplate to diamond chestplate of protection 3
				set {_deadlord}'s leggings to diamond leggings of protection 3
				set {_deadlord}'s boots to diamond boots of protection 3
				set {class.%{_deadlord}%} to "Lord"
				set {skillslot1.%{_deadlord}%} to "Double Lion"
				set {skillslot2.%{_deadlord}%} to "Crushing Offense"
				set {skillslot3.%{_deadlord}%} to "Miracle"
				set {isBoss.%{_deadlord}%} to true
			else if {_name} is 26:
				spawn 1 zombie at location at 25, 68, -5
				set {_deadlord} to the last spawned entity
				set the name of the last spawned entity to "<light red>Strong and Tough: Arden"
				set {t_str.%{_deadlord}%} to 80
				set {t_def.%{_deadlord}%} to 160
				set {t_spd.%{_deadlord}%} to 15
				set {skl.%{_deadlord}%} to 45
				set {t_res.%{_deadlord}%} to 15
				set {lvl.%{_deadlord}%} to 90
				set the maximum health of {_deadlord} to 90
				set {_deadlord}'s tool to diamond sword of sharpness 5 named "<bold>Slaying Edge" with lore "<light red><bold>Slot A - Steady Stance", "<light blue><bold>Slot B - Eclipse Brace", "<light yellow><bold>Slot C - DEF Smoke", "<light green><bold>Assist - None", "<light purple><bold>Special - Ignis", "<bold>Refined: Slaying"
				set {_deadlord}'s helmet to diamond helmet of protection 5
				set {_deadlord}'s chestplate to diamond chestplate of protection 5
				set {_deadlord}'s leggings to diamond leggings of protection 5
				set {_deadlord}'s boots to diamond boots of protection 5
				set {class.%{_deadlord}%} to "Chieftain"
				set {skillslot1.%{_deadlord}%} to "Unbreakable"
				set {skillslot2.%{_deadlord}%} to "Guard"
				set {skillslot3.%{_deadlord}%} to "Brazen STR"
				set {skillslot4.%{_deadlord}%} to "Brazen DEF"
				set {isBoss.%{_deadlord}%} to true
			set {_lvlbal} to 0
			loop all players in radius 256 of {_deadlord}:
				add {lvl.%loop-player%} to {_lvlbal}
				add 1 to {_players}
			set {_lvlbal} to ({_lvlbal} / {_players}) + 10
			if {_lvlbal} is less than {lvl.%{_deadlord}%}:
				if {_lvlbal} is not 0:
					set {_balance} to abs({_lvlbal} - {lvl.%{_deadlord}%})
					loop {_balance} times:
						subtract 1 from {t_str.%{_deadlord}%}
						subtract 1 from {t_def.%{_deadlord}%}
						subtract 1 from {t_spd.%{_deadlord}%}
						subtract 1 from {t_skl.%{_deadlord}%}
						subtract 1 from {t_res.%{_deadlord}%}
						subtract 0.5 from the maximum health of {_deadlord}
						subtract 1 from {lvl.%{_deadlord}%}
			else if {_lvlbal} is more than {lvl.%{_deadlord}%}:
				set {_balance} to ({_lvlbal} - {lvl.%{_deadlord}%})
				loop {_balance} times:
					add 1 to {t_str.%{_deadlord}%}
					add 1 to {t_def.%{_deadlord}%}
					add 1 to {t_spd.%{_deadlord}%}
					add 1 to {skl.%{_deadlord}%}
					add 1 to {t_res.%{_deadlord}%}
					add 1 to the maximum health of {_deadlord}
					add 1 to {lvl.%{_deadlord}%}
			if the maximum health of {_deadlord} is less than 20:
				set the maximum health of {_deadlord} to 20
			if {t_spd.%{_deadlord}%} is more than 125:
				apply swiftness 5 to {_deadlord} for 1 day
			else if {t_spd.%{_deadlord}%} is more than 100:
				apply swiftness 4 to {_deadlord} for 1 day
			else if {t_spd.%{_deadlord}%} is more than 75:
				apply swiftness 3 to {_deadlord} for 1 day
			else if {t_spd.%{_deadlord}%} is more than 50:
				apply swiftness 2 to {_deadlord} for 1 day
			else if {t_spd.%{_deadlord}%} is more than 25:
				apply swiftness 1 to {_deadlord} for 1 day
			heal {_deadlord} by 9999

on damage of a zombie:
	if the name of the victim contains "Alstair":
		set {_bossbar} to new boss bar
		add attacker to {_bossbar}
		set title of bossbar {_bossbar} to "<red><bold>Fallen General: Helmund"
		set {_health} to health of victim / max health of victim - 0.1
		set progress of bossbar {_bossbar} to {_health}
		show boss bar {_bossbar}
		set the visibility of bossbar {_bossbar} to true

on damage:
	if the 1st line of the lore of the attacker's tool contains "Deathly Duel":
		set {_bonusDamage} to helmType(victim)
		add chestType(victim) to {_bonusdamage}
		add legType(victim) to {_bonusdamage}
		add btType(victim) to {_bonusdamage}
		set {_bonusdamage} to {_bonusdamage} * 1.5
		set damage to damage + {_bonusdamage}
		apply strength 2 to the attacker for 5 seconds
		
		
#End Credits routine
on player portal:
	if the player's world is "Alstair_End":
		cancel event
		make player execute command "/spawn"
		wait 3 seconds
		send title "<gold>And so, Helmund's attempt to conquer" with subtitle "<gold>the continent of Silgrund was defeated once more." to the player for 4.5 seconds with fade in 0.5 seconds and fade out 0.5 seconds
		wait 5.5 seconds
		send title "<gold>Lord Kiln extended his gratitude towards %player's tablist name%" with subtitle "<gold>and the rest of their allies for saving his realm." to the player for 4.5 seconds with fade in 0.5 seconds and fade out 0.5 seconds
		wait 5.5 seconds
		send title "<gold>A grand feast was held for the motley crew of heroes," with subtitle "<gold>who would come to be known as the Crusaders of Silgrund." to the player for 4.5 seconds with fade in 0.5 seconds and fade out 0.5 seconds
		wait 5.5 seconds
		send title "<gold>A shrine would later be erected" with subtitle "<gold>for the Crusaders, ensuring that their memory would last through the ages." to the player for 4.5 seconds with fade in 0.5 seconds and fade out 0.5 seconds
		wait 5.5 seconds
		send title "<gold>Not much is known about the Crusaders" with subtitle "<gold>after their battle with Helmund." to the player for 4.5 seconds with fade in 0.5 seconds and fade out 0.5 seconds
		wait 5.5 seconds
		send title "<gold>Some say they ventured off" with subtitle "<gold>towards new lands, seeking greater challenges." to the player for 3.5 seconds with fade in 0.5 seconds and fade out 0.5 seconds
		wait 4.5 seconds
		send title "<gold>Others claim they sealed their legendary weapons" with subtitle "<gold>away, and vanished without a trace." to the player for 3.5 seconds with fade in 0.5 seconds and fade out 0.5 seconds
		wait 4.5 seconds
		send title "<gold>Only one thing is known for certain:" with subtitle "<gold><bold>The Crusaders of Silgrund had exceeded all hopes and become truly legendary heroes." to the player for 4 seconds with fade in 0.5 seconds and fade out 0.5 seconds
		wait 5 seconds
		send title "<gold>Their legend would be retold for generations," with subtitle "<gold>Inspiring hope for all just as the Great Heroes had done long ago." to the player for 4 seconds with fade in 0.5 seconds and fade out 0.5 seconds
		wait 5 seconds
		send title "<gold>Rest well, %player's tablist name%." to the player for 1.5 seconds with fade in 0.5 seconds and fade out 0.5 seconds
		wait 2.5 seconds
		send title "<gold>Your journey has finally come to an end." to the player for 2 seconds with fade in 0.5 seconds and fade out 1.5 seconds
		wait 4 seconds
		send title "<light cyan><bold>THE CRUSADERS OF SILGRUND" with subtitle "<light cyan>Produced and hosted by Flamecrest Games." to the player for 6 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 6.5 seconds
		send title "<light cyan>Lead Developer: IAmTheMostWanted" with subtitle "<light cyan>Programming: IAmTheMostWanted" to the player for 3.5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 4 seconds
		send title "<light cyan>Skill/Perk Creation: IAmTheMostWanted,Skiddlezz" with subtitle "<light cyan>Skill/Perk Balancing: IAmTheMostWanted,Skiddlezz,rockgraham101" to the player for 3.5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 4 seconds
		send title "<light cyan>Story: IAmTheMostWanted, Skiddlezz" with subtitle "<light cyan>World Concepts: Skiddlezz" to the player for 3.5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 4 seconds
		send title "<light cyan>Map Design: IAmTheMostWanted,Skiddlezz," with subtitle "<light cyan>rockgraham101,AngelDog626,ButterMonsta,coolkid <gold>...and you!" to the player for 3.5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 4 seconds
		send title "<light cyan>Quality Assurance: IAmTheMostWanted,Skiddlezz," with subtitle "<light cyan>rockgraham101,AngelDog626,ButterMonsta,coolkid,NavalSaucer899" to the player for 3.5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 4 seconds
		send title "<light cyan>Special Thanks: Spigot Team, Shouzou Kaga" with subtitle "<light cyan><bold>And all of the plugin developers who made this crazy project possible." to the player for 4 seconds with fade in 0.25 seconds and fade out 1.25 seconds
		wait 5.5 seconds
		send title "<gold>%player's tablist name%, <gold>the level %{lvl.%player%}% %{class.%player%}%:" with subtitle "<gold>Final Stat Total: %{bst.%player%}%" to the player for 2.5 seconds with fade in 0.75 seconds and fade out 0.25 seconds
		wait 3.5 seconds
		send title "<gold>Combat Victories: %{kills.%player%}%" with subtitle "<gold>Deaths: %{deaths.%player%}%" to the player for 3 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 3 seconds
		send title "<gold>Most damage dealt in one hit: %{highestdamage.%player%}%" with subtitle "<gold>Most damage suffered in one hit: %{highestsuffered.%player%}%" to the player for 3 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 3.5 seconds
		send title "<gold>Perks Unlocked: %{skillstotal.%player%}%" with subtitle "<gold>Times Reclassed: %{reclassed.%player%}%" to the player for 3 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 3.5 seconds
		if {perdiff.%player%} is 0:
			set {_diff} to "<green>Relaxed"
		else if {perdiff.%player%} is 1:
			set {_diff} to "<light green>Easy"
		else if {perdiff.%player%} is 2:
			set {_diff} to "Normal"
		else if {perdiff.%player%} is 3:
			set {_diff} to "<light red>Hard"
		else if {perdiff.%player%} is 4:
			set {_diff} to "<light purple>Lunatic"
		else if {perdiff.%player%} is 5:
			set {_diff} to "<purple><bold>Infernal"
		else if {perdiff.%player%} is 6:
			set {_diff} to "<light yellow>Thracian"
		else if {perdiff.%player%} is 7:
			set {_diff} to "<light yellow><bold>Lunatic (Thracian)"
		else if {perdiff.%player%} is 8:
			set {_diff} to "<gold><bold>Infernal (Thracian)"
		send title "<gold>Promotion Tier: %{promoted.%player%}%" with subtitle "<gold>Difficulty: %{_diff}%" to the player for 3 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 3.5 seconds
		send title "<gold>Blocks Mined: %{blocksmined.%player%}%" with subtitle "<gold>Tools Broken: %{toolbreaktally.%player%}%" to the player for 3 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 3.5 seconds
		send title "<gold>Fall Damage Suffered: %{slfalltotal.%player%}%" with subtitle "<gold>Total Funds: %player's money%" to the player for 3 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 4.25 seconds
		send title "<gold>---===Character Rankings===---" to the player for 3 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 3.5 seconds
		if {kills.%player%} is more than 500:
			set {_killrank} to "<gold><bold>S"
			give 1 nether star named "<gold><bold>Crest of Valor" with lore "<gold>Awarded to heroes with exemplary combat prowess.", "<white>Grants Strength 4 while in your inventory." to the player
		else if {kills.%player%} is more than 400:
			set {_killrank} to "A"
		else if {kills.%player%} is more than 300:
			set {_killrank} to "B"
		else if {kills.%player%} is more than 200:
			set {_killrank} to "C"
		else if {kills.%player%} is more than 100:
			set {_killrank} to "D"
		else:
			set {_killrank} to "E"
		if {deaths.%player%} is less than or equal to 3:
			set {_survival} to "<gold><bold>S"
			give 1 nether star named "<gold><bold>Crest of Resilience" with lore "<gold>Awarded to heroes with unparalleled vitality.", "<white>Grants Regeneration 4 while in your inventory." to the player
		else if {deaths.%player%} is less than or equal to 5:
			set {_survival} to "A"
		else if {deaths.%player%} is less than or equal to 7:
			set {_survival} to "B"
		else if {deaths.%player%} is less than or equal to 9:
			set {_survival} to "C"
		else if {deaths.%player%} is less than or equal to 12:
			set {_survival} to "D"
		else:
			set {_survival} to "E"
		send title "Combat: %{_killrank}%" with subtitle "Survival: %{_survival}%" to the player for 3.5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 4 seconds
		if {lvl.%player%} is more than 150:
			set {_funds} to "<gold><bold>S"
			give 1 nether star named "<gold><bold>Crest of Mastery" with lore "<gold>Awarded to heroes with peerless experience.", "<white>Grants 2x experience while in your inventory." to the player
		else if {lvl.%player%} is more than 120:
			set {_funds} to "A"
		else if {lvl.%player%} is more than 90:
			set {_funds} to "B"
		else if {lvl.%player%} is more than 60:
			set {_funds} to "C"
		else if {lvl.%player%} is more than 30:
			set {_funds} to "D"
		else:
			set {_funds} to "E"
		if {hoursplayed.%player%} is less than 10:
			set {_tactics} to "<gold><bold>S"
			give 1 nether star named "<gold><bold>Crest of Wisdom" with lore "<gold>Awarded to heroes with unmatched tactics.", "<white>Grants <gold>[Spectrum Tactic]<white> while in your inventory.", "<gold>[Spectrum Tactic]<white>: Grants +25 to all stats if number of players with that class in range <= 3.", "<white>Buffs apply in a 10 block radius. Targets all allies (includes skill wielder)." to the player
		else if {hoursplayed.%player%} is less than 15:
			set {_tactics} to "A"
		else if {hoursplayed.%player%} is less than 20:
			set {_tactics} to "B"
		else if {hoursplayed.%player%} is less than 25:
			set {_tactics} to "C"
		else if {hoursplayed.%player%} is less than 30:
			set {_tactics} to "D"
		else:
			set {_tactics} to "E"
		send title "Experience: %{_funds}%" with subtitle "Tactics: %{_tactics}%" to the player for 3.5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
		wait 4 seconds
		send title "Final Ranks:" with subtitle "%{_killrank}% <reset>%{_survival}% <reset>%{_funds}% <reset>%{_tactics}%" to the player for 5 seconds with fade in 1 seconds and fade out 1 seconds
		wait 7 seconds
		if {_killrank} is "<gold><bold>S":
			if {_survival} is "<gold><bold>S":
				if {_funds} is "<gold><bold>S":
					if {_tactics} is "<gold><bold>S":
						play sound "entity.player.levelup" with volume 1 and pitch 0.5 at player for player
						play mob spawner flames at the player
						strike lightning effect at the player
						give 1 diamond sword of unbreaking 100, sharpness 15, looting 10, smite 10, fire aspect 3 named "<gold><bold>Legend's Resonance" with lore "<light red><bold>Slot A - Deathly Duel", "<light blue><bold>Slot B - Wrath", "<light yellow><bold>Slot C - Breath of Life", "<light green><bold>Assist - Swap", "<light purple><bold>Special - Aether", "<light blue><bold>Refined: Warding", "<white>A mythical sword that presents itself only to true heroes.", "<white>The blade shines with a divine light, piercing darkness and igniting the flames of hope." to the player
						send title "<light yellow>Achieved S rank in all categories!" with subtitle "<gold><bold>You are a truly legendary hero! You have been granted a special reward." to the player for 5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
						make player say "%{maxLevelQuote.%player%}%"
						wait 5.5 seconds
		send title "<gold><bold>THANK YOU FOR PLAYING!" with subtitle "<gold><bold>You may continue your adventures with this character, or start a new journey with /char new." to the player for 5 seconds with fade in 0.5 seconds and fade out 1 second
		play sound "entity.player.levelup" with volume 1 and pitch 1 at player for player
		
		
	