command /forceTimedRNG:
	trigger:
		send "<light yellow>Timed RNG has been instanced."
		set {toddRNG} to true
		set {radiantQuestsRNG.%player%} to true
	
on damage:
	if citizen id of the victim is set:
		if victim's name is "Todd":
			set {toddRNG} to true
			set damage to 0
			
on load:
	execute console command "/time set 6:00am"

command /bs-shop [<number=1>]:
	trigger:
		set {_discountFactor} to ({abilities.%player%::Barter} / 20)
		if {_discountFactor} is less than 0.5:
			set {_discountFactor} to 0.5
		else if {_discountFactor} is more than 2:
			set {_discountFactor} to ({_discountFactor} ^ 0.8)
			if {_discountFactor} is less than 2:
				set {_discountFactor} to 2
		if {traits.%player%::Physician} is true:
			set {_discountFactor} to {_discountFactor} * 0.8
		if arg 1 is 1:
			open chest inventory with 2 rows named "<gold>Blacksmith" for the player
			set slot 0 of the player's current inventory to 1 leather helmet with lore "<white>Cost:", "%24 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 leather chestplate with lore "<white>Cost:", "%40 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 leather leggings with lore "<white>Cost:", "%34 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 leather boots with lore "<white>Cost:", "%20 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 wooden sword with lore "<white>Cost:", "%10 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 wooden axe with lore "<white>Cost:", "%16 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 wooden pickaxe with lore "<white>Cost:", "%16 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 wooden shovel with lore "<white>Cost:", "%8 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 wooden hoe with lore "<white>Cost:", "%12 / {_discountFactor}%"
			set slot 9 of the player's current inventory to 1 anvil named "<yellow><bold>Upgrade Equipment" with lore "<white>Enhance your equipment with various skills."
			set slot 17 of the player's current inventory to 1 light green glass pane named "<light green>Go to Page 2"
		else if arg 1 is 2:
			open chest inventory with 2 rows named "<gold>Blacksmith" for the player
			set slot 0 of the player's current inventory to 1 chain helmet with lore "<white>Cost:", "%40 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 chain chestplate with lore "<white>Cost:", "%64 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 chain leggings with lore "<white>Cost:", "%56 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 chain boots with lore "<white>Cost:", "%32 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 stone sword with lore "<white>Cost:", "%14 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 stone axe with lore "<white>Cost:", "%20 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 stone pickaxe with lore "<white>Cost:", "%20 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 stone shovel with lore "<white>Cost:", "%10 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 stone hoe with lore "<white>Cost:", "%16 / {_discountFactor}%"
			set slot 16 of the player's current inventory to 1 red glass pane named "<light red>Go to Page 1"
			set slot 17 of the player's current inventory to 1 light green glass pane named "<light green>Go to Page 3"
		else if arg 1 is 3:
			open chest inventory with 2 rows named "<gold>Blacksmith" for the player
			set slot 0 of the player's current inventory to 1 iron helmet with lore "<white>Cost:", "%300 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 iron chestplate with lore "<white>Cost:", "%480 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 iron leggings with lore "<white>Cost:", "%420 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 iron boots with lore "<white>Cost:", "%240 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 iron sword with lore "<white>Cost:", "%120 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 iron axe with lore "<white>Cost:", "%180 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 iron pickaxe with lore "<white>Cost:", "%180 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 iron shovel with lore "<white>Cost:", "%180 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 iron hoe with lore "<white>Cost:", "%120 / {_discountFactor}%"
			set slot 9 of the player's current inventory to 1 bow with lore "<white>Cost:", "%120 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 16 arrow with lore "<white>Cost:", "%96 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 8 iron ingot with lore "<white>Cost:", "%480 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 8 gold ingot with lore "<white>Cost:", "%640 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 1 golden sword of power 1 named "<orange>Special Blade" with lore "<white>Cost:", "%200 / {_discountFactor}%", "<white>Use to guarantee activation of your Special skill on your next attack."
			set slot 16 of the player's current inventory to 1 red glass pane named "<light red>Go to Page 2"
			set slot 17 of the player's current inventory to 1 light green glass pane named "<light green>Go to Page 4"
		else if arg 1 is 4:
			open chest inventory with 3 rows named "<gold>Blacksmith" for the player
			set slot 0 of the player's current inventory to 1 iron helmet of protection 2 named "<light blue>Steel Helmet" with lore "<white>Cost:", "%450 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 iron chestplate of protection 2 named "<light blue>Steel Chestplate" with lore "<white>Cost:", "%720 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 iron leggings of protection 2 named "<light blue>Steel Leggings" with lore "<white>Cost:", "%630 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 iron boots of protection 2 named "<light blue>Steel Boots" with lore "<white>Cost:", "%360 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 iron sword of sharpness 2 named "<light blue>Steel Sword" with lore "<white>Cost:", "%270 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 iron axe of sharpness 2, efficiency 2 named "<light blue>Steel Axe" with lore "<white>Cost:", "%270 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 iron pickaxe of efficiency 2 named "<light blue>Steel Pickaxe" with lore "<white>Cost:", "%270 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 iron shovel of efficiency 2 named "<light blue>Steel Shovel" with lore "<white>Cost:", "%270 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 iron hoe of unbreaking 2 named "<light blue>Steel Hoe" with lore "<white>Cost:", "%270 / {_discountFactor}%"
			set slot 9 of the player's current inventory to 1 bow of power 2 named "<light blue>Steel Bow" with lore "<white>Cost:", "%180 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 gold helmet with lore "<white>Cost:", "%300 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 1 gold chestplate with lore "<white>Cost:", "%480 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 1 gold leggings with lore "<white>Cost:", "%420 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 1 gold boots with lore "<white>Cost:", "%240 / {_discountFactor}%"
			set slot 14 of the player's current inventory to 1 gold sword with lore "<white>Cost:", "%120 / {_discountFactor}%"
			set slot 15 of the player's current inventory to 1 gold axe with lore "<white>Cost:", "%180 / {_discountFactor}%"
			set slot 16 of the player's current inventory to 1 gold pickaxe with lore "<white>Cost:", "%180 / {_discountFactor}%"
			set slot 17 of the player's current inventory to 1 gold shovel with lore "<white>Cost:", "%180 / {_discountFactor}%"
			set slot 18 of the player's current inventory to 1 gold hoe with lore "<white>Cost:", "%120 / {_discountFactor}%"
			set slot 19 of the player's current inventory to 1 bow of power 3 named "<light blue>Golden Bow" with lore "<white>Cost:", "%240 / {_discountFactor}%"
			set slot 20 of the player's current inventory to 1 anvil of power 1 named "<gold>Portable Smithy" with lore "<white>Cost:", "%360 / {_discountFactor}%", "<white>Right-click while held to access a smithy at any time."
			set slot 21 of the player's current inventory to 1 anvil of power 1 named "<orange>Restoration Kit" with lore "<white>Cost:", "%3000 / {_discountFactor}%", "<white>Use to repair all items in your inventory back to full durability."
			set slot 25 of the player's current inventory to 1 red glass pane named "<light red>Go to Page 3"
			set slot 26 of the player's current inventory to 1 light green glass pane named "<light green>Go to Page 5"
		else if arg 1 is 5:
			open chest inventory with 2 rows named "<gold>Blacksmith" for the player
			set slot 0 of the player's current inventory to 1 iron helmet of protection 5 named "<light blue>Silver Helmet" with lore "<white>Cost:", "%750 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 iron chestplate of protection 5 named "<light blue>Silver Chestplate" with lore "<white>Cost:", "%1200 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 iron leggings of protection 5 named "<light blue>Silver Leggings" with lore "<white>Cost:", "%1050 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 iron boots of protection 5 named "<light blue>Silver Boots" with lore "<white>Cost:", "%600 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 iron sword of sharpness 5 named "<light blue>Silver Sword" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 iron axe of sharpness 5, efficiency 5 named "<light blue>Silver Axe" with lore "<white>Cost:", "%470 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 iron pickaxe of efficiency 5 named "<light blue>Silver Pickaxe" with lore "<white>Cost:", "%470 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 iron shovel of efficiency 5 named "<light blue>Silver Shovel" with lore "<white>Cost:", "%470 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 iron hoe of unbreaking 5 named "<light blue>Silver Hoe" with lore "<white>Cost:", "%470 / {_discountFactor}%"
			set slot 9 of the player's current inventory to 1 bow of power 5 named "<light blue>Silver Bow" with lore "<white>Cost:", "%700 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 8 iron ingot named "<light blue>Tempered Iron" with lore "<white>Cost:", "%4320 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 8 gold ingot named "<light blue>Tempered Gold" with lore "<white>Cost:", "%5760 / {_discountFactor}%"
			set slot 16 of the player's current inventory to 1 red glass pane named "<light red>Go to Page 4"
			set slot 17 of the player's current inventory to 1 light green glass pane named "<light green>Go to Page 6"
		else if arg 1 is 6:
			open chest inventory with 2 rows named "<gold>Blacksmith" for the player
			set slot 0 of the player's current inventory to 1 diamond helmet with lore "<white>Cost:", "%1000 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 diamond chestplate with lore "<white>Cost:", "%1600 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 diamond leggings with lore "<white>Cost:", "%1400 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 diamond boots with lore "<white>Cost:", "%800 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 diamond sword with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 diamond axe with lore "<white>Cost:", "%600 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 diamond pickaxe with lore "<white>Cost:", "%600 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 diamond shovel with lore "<white>Cost:", "%600 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 diamond hoe with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 9 of the player's current inventory to 4 diamond with lore "<white>Cost:", "%800 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 4 diamond named "<light blue>Tempered Diamond" with lore "<white>Cost:", "%7200 / {_discountFactor}%"
			set slot 17 of the player's current inventory to 1 red glass pane named "<light red>Go to Page 5"

command /butchershop:
	trigger:
		set {_discountFactor} to ({abilities.%player%::Barter} / 20)
		if {_discountFactor} is less than 0.5:
			set {_discountFactor} to 0.5
		else if {_discountFactor} is more than 2:
			set {_discountFactor} to ({_discountFactor} ^ 0.8)
			if {_discountFactor} is less than 2:
				set {_discountFactor} to 2
		if {traits.%player%::Physician} is true:
			set {_discountFactor} to {_discountFactor} * 0.8
		open chest inventory with 1 row named "<gold>Butcher" for the player
		set slot 0 of the player's current inventory to 4 cooked beef with lore "<white>Cost:", "%48 / {_discountFactor}%"
		set slot 1 of the player's current inventory to 4 cooked porkchop with lore "<white>Cost:", "%48 / {_discountFactor}%"
		set slot 2 of the player's current inventory to 4 leather with lore "<white>Cost:", "%20 / {_discountFactor}%"
		set slot 3 of the player's current inventory to 3 wool with lore "<white>Cost:", "%18 / {_discountFactor}%"
		set slot 4 of the player's current inventory to 1 iron axe of looting 2 named "<light blue>Butcher's Axe" with lore "<white>Cost:", "%280 / {_discountFactor}%"
			
command /tradershop [<number=1>]:
	trigger:
		set {_discountFactor} to ({abilities.%player%::Barter} / 20)
		if {_discountFactor} is less than 0.5:
			set {_discountFactor} to 0.5
		else if {_discountFactor} is more than 2:
			set {_discountFactor} to ({_discountFactor} ^ 0.8)
			if {_discountFactor} is less than 2:
				set {_discountFactor} to 2
		if {traits.%player%::Physician} is true:
			set {_discountFactor} to {_discountFactor} * 0.8
		open chest inventory with 6 rows named "<gold>Trader" for the player
		set slot 0 of the player's current inventory to 1 workbench with lore "<white>Cost:", "%16 / {_discountFactor}%"
		set slot 1 of the player's current inventory to 1 furnace with lore "<white>Cost:", "%40 / {_discountFactor}%"
		set slot 2 of the player's current inventory to 16 oak log with lore "<white>Cost:", "%128 / {_discountFactor}%"
		set slot 3 of the player's current inventory to 16 birch log with lore "<white>Cost:", "%128 / {_discountFactor}%"
		set slot 4 of the player's current inventory to 16 spruce log with lore "<white>Cost:", "%128 / {_discountFactor}%"
		set slot 5 of the player's current inventory to 16 jungle log with lore "<white>Cost:", "%128 / {_discountFactor}%"
		set slot 6 of the player's current inventory to 16 acacia log with lore "<white>Cost:", "%128 / {_discountFactor}%"
		set slot 7 of the player's current inventory to 16 dark oak log with lore "<white>Cost:", "%128 / {_discountFactor}%"
		set slot 8 of the player's current inventory to 8 ladder with lore "<white>Cost:", "%48 / {_discountFactor}%"
		set slot 9 of the player's current inventory to 1 chest with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 10 of the player's current inventory to 1 flint and steel with lore "<white>Cost:", "%40 / {_discountFactor}%"
		set slot 11 of the player's current inventory to 32 torch with lore "<white>Cost:", "%48 / {_discountFactor}%"
		set slot 12 of the player's current inventory to 6 glass with lore "<white>Cost:", "%30 / {_discountFactor}%"
		set slot 13 of the player's current inventory to 4 white wool with lore "<white>Cost:", "%32 / {_discountFactor}%"
		set slot 14 of the player's current inventory to 1 fishing rod with lore "<white>Cost:", "%48 / {_discountFactor}%"
		set slot 15 of the player's current inventory to 1 compass with lore "<white>Cost:", "%40 / {_discountFactor}%"
		set slot 16 of the player's current inventory to 1 white bed with lore "<white>Cost:", "%32 / {_discountFactor}%"
		set slot 17 of the player's current inventory to 1 empty map with lore "<white>Cost:", "%40 / {_discountFactor}%"
		set slot 18 of the player's current inventory to 3 sugar cane with lore "<white>Cost:", "%18 / {_discountFactor}%"
		set slot 19 of the player's current inventory to 1 name tag with lore "<white>Cost:", "%20 / {_discountFactor}%"
		set slot 20 of the player's current inventory to 1 lead with lore "<white>Cost:", "%16 / {_discountFactor}%"
		set slot 21 of the player's current inventory to 1 painting with lore "<white>Cost:", "%30 / {_discountFactor}%"
		set slot 22 of the player's current inventory to 1 piston with lore "<white>Cost:", "%80 / {_discountFactor}%"
		set slot 23 of the player's current inventory to 1 slimeball with lore "<white>Cost:", "%30 / {_discountFactor}%"
		set slot 24 of the player's current inventory to 8 redstone dust with lore "<white>Cost:", "%80 / {_discountFactor}%"
		set slot 25 of the player's current inventory to 2 redstone repeater with lore "<white>Cost:", "%80 / {_discountFactor}%"
		set slot 26 of the player's current inventory to 4 redstone torch with lore "<white>Cost:", "%48 / {_discountFactor}%"
		set slot 27 of the player's current inventory to 1 dispenser with lore "<white>Cost:", "%80 / {_discountFactor}%"
		set slot 28 of the player's current inventory to 4 tnt with lore "<white>Cost:", "%160 / {_discountFactor}%"
		set slot 29 of the player's current inventory to 1 redstone lamp with lore "<white>Cost:", "%40 / {_discountFactor}%"
		set slot 30 of the player's current inventory to 1 jukebox with lore "<white>Cost:", "%40 / {_discountFactor}%"
		set slot 31 of the player's current inventory to 1 music disc cat with lore "<white>Cost:", "%90 / {_discountFactor}%"
		set slot 32 of the player's current inventory to 1 music disc wait with lore "<white>Cost:", "%90 / {_discountFactor}%"
		set slot 33 of the player's current inventory to 1 saddle with lore "<white>Cost:", "%40 / {_discountFactor}%"
		set slot 34 of the player's current inventory to 1 book named "<gold>Journal" with lore "<white>Cost:", "%10 / {_discountFactor}%", "<white>A rugged journal good for keeping notes."
		set slot 35 of the player's current inventory to 1 sponge with lore "<white>Cost:", "%40 / {_discountFactor}%"
		set slot 36 of the player's current inventory to 4 gunpowder with lore "<white>Cost:", "%32 / {_discountFactor}%"
		set slot 37 of the player's current inventory to 1 nether star named "<gold>Blacksmith Summoner" with lore "<white>Cost:", "%400 / {_discountFactor}%", "<white>Start up a Smithy anywhere in the world.", "<white>Right-Click to use and spawn a Blacksmith NPC."
		set slot 38 of the player's current inventory to 1 nether star named "<gold>Trader Summoner" with lore "<white>Cost:", "%600 / {_discountFactor}%", "<white>Start up a Trading Post anywhere in the world.", "<white>Right-Click to use and spawn a Trader NPC."
		set slot 39 of the player's current inventory to 1 nether star named "<gold>Innkeeper Summoner" with lore "<white>Cost:", "%200 / {_discountFactor}%", "<white>Start up an Inn anywhere in the world.", "<white>Right-Click to use and spawn an Innkeeper NPC."
		set slot 40 of the player's current inventory to 1 nether star named "<gold>Enchanter Summoner" with lore "<white>Cost:", "%400 / {_discountFactor}%", "<white>Start up a Enchantry anywhere in the world.", "<white>Right-Click to use and spawn an Enchanter NPC."
		set slot 41 of the player's current inventory to 1 nether star named "<gold><bold>Warrior's Proof" with lore "<white>Cost:", "%300 / {_discountFactor}%", "<white>Use to promote to a higher class.", "<white>This extends the level cap by 20 and increases your stat caps."
		set slot 42 of the player's current inventory to 1 nether star named "<gold><bold>Trainee's Enrollment" with lore "<white>Cost:", "%100 / {_discountFactor}%", "<white>Use to change your class.", "<white>You keep all learned perks, items, etc..."
		set slot 43 of the player's current inventory to 1 nether star named "<gold><bold>Soul Crystal" with lore "<white>Cost:", "%750 / {_discountFactor}%", "<white>Use to enter New Game+.", "<white>Starts creation of a new character while keeping all learned perks."
		#Block half-breeds from special offers because the shopkeeper is racist
		if {holyBlood.%player%::D'al Versain} is not 1:
			if {abilities.%player%::Speech} is more than 35:
				set slot 44 of the player's current inventory to 2 bookshelf with lore "<white>Cost:", "%70 / {_discountFactor}%"
				set slot 45 of the player's current inventory to 8 lapis item with lore "<white>Cost:", "%80 / {_discountFactor}%"
				set slot 46 of the player's current inventory to 1 chest named "<gold>Portable Trader" with lore "<white>Cost:", "%100 / {_discountFactor}%", "<white>Lets you open the trader's shop from anywhere in the world."
			if {abilities.%player%::Speech} is more than 55:
				set slot 47 of the player's current inventory to 1 elytra with lore "<white>Cost:", "%135 / {_discountFactor}%"
				set slot 48 of the player's current inventory to 1 purple shulker box with lore "<white>Cost:", "%80 / {_discountFactor}%"
				set slot 49 of the player's current inventory to 1 enchanting table with lore "<white>Cost:", "%140 / {_discountFactor}%"
			if {abilities.%player%::Speech} is more than 70:
				set slot 50 of the player's current inventory to 1 book named "<gold>Perk Manual: Expert Negotiator" with nbt "{perkManualType:""Expert_Negotiator""}" with lore "<white>Cost:", "%200 / {_discountFactor}%", "<white>Use to unlock the perk Expert Negotiator."
				set slot 51 of the player's current inventory to 1 book named "<gold>Perk Manual: Air Hike" with nbt "{perkManualType:""Air Hike""}" with lore "<white>Cost:", "%200 / {_discountFactor}%", "<white>Use to unlock the perk Air Hike."
				set slot 52 of the player's current inventory to 1 book named "<gold>Perk Manual: Paragon" with nbt "{perkManualType:Paragon}" with lore "<white>Cost:", "%200 / {_discountFactor}%", "<white>Use to unlock the perk Paragon."
				set slot 53 of the player's current inventory to 1 book named "<gold>Perk Manual: Optimism" with nbt "{perkManualType:Optimism}" with lore "<white>Cost:", "%200 / {_discountFactor}%", "<white>Use to unlock the perk Optimism."
				set slot 54 of the player's current inventory to 1 book named "<gold>Perk Manual: Pessimism" with nbt "{perkManualType:Pessimism}" with lore "<white>Cost:", "%200 / {_discountFactor}%", "<white>Use to unlock the perk Pessimism."

command /weaponshop [<number=0>]:
	trigger:
		set {_discountFactor} to ({abilities.%player%::Barter} / 120)
		if {_discountFactor} is less than 0.2:
			set {_discountFactor} to 0.2
		else if {_discountFactor} is more than 1:
			set {_discountFactor} to ({_discountFactor} ^ 0.8)
			if {_discountFactor} is less than 1:
				set {_discountFactor} to 1
		if {traits.%player%::Physician} is true:
			set {_discountFactor} to {_discountFactor} * 0.8
		if arg 1 is 0:
			open chest inventory with 2 rows named "<gold>Weapon Smith" for the player
			set slot 0 of the player's current inventory to 1 iron sword named "<gold>Basic Weapons" with lore "<white>Purchase standard-issue, craftable weapons here."
			set slot 1 of the player's current inventory to 1 diamond sword named "<gold>Slaying Weapons" with lore "<white>Purchase an evolved Slaying weapon.", "<white>Slaying weapons have innate +10%% Special skill chance,", "<white>and each merge adds a bonus +1%% Special chance."
			set slot 2 of the player's current inventory to 1 diamond axe named "<gold>Reinforced Weapons" with lore "<white>Purchase an evolved Reinforced weapon.", "<white>Reinforced weapons have +3 might and 10%% higher damage,", "<white>and each merge adds +2 extra might."
			set slot 3 of the player's current inventory to 1 diamond shovel named "<gold>Warding Weapons" with lore "<white>Purchase an evolved Warding weapon.", "<white>Warding weapons reduce enemy weapon might by -3", "<white>and reduce damage taken by 10%% during combat.", "<white>Each merge reduces enemy weapon might by 1."
			set slot 4 of the player's current inventory to 1 diamond hoe named "<gold>Crushing Weapons" with lore "<white>Purchase an evolved Crushing weapon.", "<white>Crushing weapons grant Special Acceleration based on damage dealt.", "<white>Each merge boosts the Special Acceleration bonus."
			set slot 5 of the player's current inventory to 1 arrow named "<gold>Piercing Weapons" with lore "<white>Purchase an evolved Piercing weapon.", "<white>Piercing weapons nullify all damage reduction.", "<white>Each merge boosts damage dealt based on foe's equipped armour."
			set slot 6 of the player's current inventory to 1 diamond sword named "<gold>Koenig Weapons" with lore "<white>Purchase an evolved Koenig weapon.", "<white>Koenig weapons boosts damage dealt when a Special skill activates", "<white>by 7.5 hearts, and each merge", "<white>adds +2 extra damage."
			set slot 7 of the player's current inventory to 1 chest named "<gold>Weapon Frames" with lore "<white>Frames are used to add +1 merge to your weapons.", "<white>Each merge bolsters the weapon's damage or bonus effect if present."
			set slot 8 of the player's current inventory to 1 ender chest named "<gold>Netherite Weapon Frames" with lore "<white>Frames for upgrading Netherite weapons.", "<white>The merge process behaves differently for Netherite,", "<white>as each merge increases the effect of the refine", "<white>equipped to the weapon by 10%%.", "<white>Netherite tools cannot evolve to Sacred Treasures."
		else if arg 1 is 1:
			open chest inventory with 3 rows named "<gold>Weapon Smith | Basic Weapons" for the player
			#Iron weapons
			set slot 0 of the player's current inventory to 1 iron sword with lore "<white>Cost:", "%120 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 iron axe with lore "<white>Cost:", "%120 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 iron shovel named "<bold>Iron Lance" with nbt "{LanceType:2}" with lore "<white>Cost:", "%120 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 iron hoe named "<bold>Iron Gauntlets" with nbt "{GauntletType:2}" with lore "<white>Cost:", "%120 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 64 arrow named "<bold>Iron Dagger" with nbt "{DaggerType:2}" with lore "<white>Cost:", "%60 / {_discountFactor}%"
			#Gold weapons
			set slot 9 of the player's current inventory to 1 golden sword with lore "<white>Cost:", "%60 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 golden axe with lore "<white>Cost:", "%60 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 1 golden shovel named "<bold>Golden Lance" with nbt "{LanceType:3}" with lore "<white>Cost:", "%60 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 1 golden hoe named "<bold>Golden Gauntlets" with nbt "{GauntletType:3}" with lore "<white>Cost:", "%60 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 64 arrow named "<bold>Golden Dagger" with nbt "{DaggerType:3}" with lore "<white>Cost:", "%30 / {_discountFactor}%"
			#Diamond weapons
			set slot 18 of the player's current inventory to 1 diamond sword with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 19 of the player's current inventory to 1 diamond axe with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 20 of the player's current inventory to 1 diamond shovel named "<bold>Diamond Lance" with nbt "{LanceType:4}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 21 of the player's current inventory to 1 diamond hoe named "<bold>Diamond Gauntlets" with nbt "{GauntletType:4}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 22 of the player's current inventory to 64 arrow named "<bold>Diamond Dagger" with nbt "{DaggerType:4}" with lore "<white>Cost:", "%200 / {_discountFactor}%"
			set slot 26 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is 2:
			open chest inventory with 2 rows named "<gold>Weapon Smith | Slaying Weapons" for the player
			#Iron weapons
			set slot 0 of the player's current inventory to 1 iron sword named "<light blue>Iron Slaying Edge [+0]" with nbt "{bakedRefine:0,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 iron axe named "<light blue>Iron Slaying Axe [+0]" with nbt "{bakedRefine:0,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 iron shovel named "<light blue>Iron Slaying Lance [+0]" with nbt "{bakedRefine:0,mergeCount:0,LanceType:2}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 iron hoe named "<light blue>Iron Slaying Gaunlets [+0]" with nbt "{bakedRefine:0,mergeCount:0,GauntletType:2}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 64 arrow named "<light blue>Iron Slaying Dagger [+0]" with nbt "{bakedRefine:0,mergeCount:0,DaggerType:2}" with lore "<white>Cost:", "%200 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 bow named "<light blue>Slaying Bow [+0]" with nbt "{bakedRefine:0,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			#Diamond weapons
			set slot 9 of the player's current inventory to 1 diamond sword named "<light blue>Diamond Slaying Edge [+0]" with nbt "{bakedRefine:0,mergeCount:0}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 diamond axe named "<light blue>Diamond Slaying Axe [+0]" with nbt "{bakedRefine:0,mergeCount:0}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 1 diamond shovel named "<light blue>Diamond Slaying Lance [+0]" with nbt "{bakedRefine:0,mergeCount:0,LanceType:4}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 1 diamond hoe named "<light blue>Diamond Slaying Gaunlets [+0]" with nbt "{bakedRefine:0,mergeCount:0,GauntletType:4}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 64 arrow named "<light blue>Diamond Slaying Dagger [+0]" with nbt "{bakedRefine:0,mergeCount:0,DaggerType:4}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 17 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is 3:
			open chest inventory with 2 rows named "<gold>Weapon Smith | Reinforced Weapons" for the player
			#Iron weapons
			set slot 0 of the player's current inventory to 1 iron sword named "<light blue>Iron Reforged Blade [+0]" with nbt "{bakedRefine:1,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 iron axe named "<light blue>Iron Reforged Axe [+0]" with nbt "{bakedRefine:1,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 iron shovel named "<light blue>Iron Reforged Lance [+0]" with nbt "{bakedRefine:1,mergeCount:0,LanceType:2}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 iron hoe named "<light blue>Iron Reforged Gaunlets [+0]" with nbt "{bakedRefine:1,mergeCount:0,GauntletType:2}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 64 arrow named "<light blue>Iron Reforged Dagger [+0]" with nbt "{bakedRefine:1,mergeCount:0,DaggerType:2}" with lore "<white>Cost:", "%200 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 bow named "<light blue>Reforged Bow [+0]" with nbt "{bakedRefine:1,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			#Diamond weapons
			set slot 9 of the player's current inventory to 1 diamond sword named "<light blue>Diamond Reforged Blade [+0]" with nbt "{bakedRefine:1,mergeCount:0}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 diamond axe named "<light blue>Diamond Reforged Axe [+0]" with nbt "{bakedRefine:1,mergeCount:0}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 1 diamond shovel named "<light blue>Diamond Reforged Lance [+0]" with nbt "{bakedRefine:1,mergeCount:0,LanceType:4}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 1 diamond hoe named "<light blue>Diamond Reforged Gaunlets [+0]" with nbt "{bakedRefine:1,mergeCount:0,GauntletType:4}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 64 arrow named "<light blue>Diamond Reforged Dagger [+0]" with nbt "{bakedRefine:1,mergeCount:0,DaggerType:4}" with lore "<white>Cost:", "%500 / {_discountFactor}%"
			set slot 17 of the player's current inventory to 1 red glass pane named "<bold>Go Back"	
		else if arg 1 is 4:
			open chest inventory with 2 rows named "<gold>Weapon Smith | Warding Weapons" for the player
			#Iron weapons
			set slot 0 of the player's current inventory to 1 iron sword named "<light blue>Iron Barrier Blade [+0]" with nbt "{bakedRefine:2,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 iron axe named "<light blue>Iron Barrier Axe [+0]" with nbt "{bakedRefine:2,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 iron shovel named "<light blue>Iron Barrier Lance [+0]" with nbt "{bakedRefine:2,mergeCount:0,LanceType:2}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 iron hoe named "<light blue>Iron Barrier Gaunlets [+0]" with nbt "{bakedRefine:2,mergeCount:0,GauntletType:2}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 64 arrow named "<light blue>Iron Barrier Dagger [+0]" with nbt "{bakedRefine:2,mergeCount:0,DaggerType:2}" with lore "<white>Cost:", "%200 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 bow named "<light blue>Barrier Bow [+0]" with nbt "{bakedRefine:2,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			#Diamond weapons
			set slot 9 of the player's current inventory to 1 diamond sword named "<light blue>Diamond Barrier Blade [+0]" with nbt "{bakedRefine:2,mergeCount:0}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 diamond axe named "<light blue>Diamond Barrier Axe [+0]" with nbt "{bakedRefine:2,mergeCount:0}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 1 diamond shovel named "<light blue>Diamond Barrier Lance [+0]" with nbt "{bakedRefine:2,mergeCount:0,LanceType:4}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 1 diamond hoe named "<light blue>Diamond Barrier Gaunlets [+0]" with nbt "{bakedRefine:2,mergeCount:0,GauntletType:4}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 64 arrow named "<light blue>Diamond Barrier Dagger [+0]" with nbt "{bakedRefine:2,mergeCount:0,DaggerType:4}" with lore "<white>Cost:", "%500 / {_discountFactor}%"
			set slot 17 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is 5:
			open chest inventory with 2 rows named "<gold>Weapon Smith | Crushing Weapons" for the player
			#Iron weapons
			set slot 0 of the player's current inventory to 1 iron sword named "<light blue>Iron Greatsword [+0]" with nbt "{bakedRefine:5,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 iron axe named "<light blue>Iron Greataxe [+0]" with nbt "{bakedRefine:5,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 iron shovel named "<light blue>Iron Pike [+0]" with nbt "{bakedRefine:5,mergeCount:0,LanceType:2}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 iron hoe named "<light blue>Iron Heavy Gaunlets [+0]" with nbt "{bakedRefine:5,mergeCount:0,GauntletType:2}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 64 arrow named "<light blue>Iron Heavy Dagger [+0]" with nbt "{bakedRefine:5,mergeCount:0,DaggerType:2}" with lore "<white>Cost:", "%200 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 bow named "<light blue>Heavy Bow [+0]" with nbt "{bakedRefine:5,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			#Diamond weapons
			set slot 9 of the player's current inventory to 1 diamond sword named "<light blue>Diamond Greatsword [+0]" with nbt "{bakedRefine:5,mergeCount:0}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 diamond axe named "<light blue>Diamond Greataxe [+0]" with nbt "{bakedRefine:5,mergeCount:0}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 1 diamond shovel named "<light blue>Diamond Pike [+0]" with nbt "{bakedRefine:5,mergeCount:0,LanceType:4}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 1 diamond hoe named "<light blue>Diamond Heavy Gaunlets [+0]" with nbt "{bakedRefine:5,mergeCount:0,GauntletType:4}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 64 arrow named "<light blue>Diamond Heavy Dagger [+0]" with nbt "{bakedRefine:5,mergeCount:0,DaggerType:4}" with lore "<white>Cost:", "%500 / {_discountFactor}%"
			set slot 17 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is 6:
			open chest inventory with 2 rows named "<gold>Weapon Smith | Piercing Weapons" for the player
			#Iron weapons
			set slot 0 of the player's current inventory to 1 iron sword named "<light blue>Iron Armoursmasher [+0]" with nbt "{bakedRefine:3,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 iron axe named "<light blue>Iron Hammer [+0]" with nbt "{bakedRefine:3,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 iron shovel named "<light blue>Iron Shieldreaver [+0]" with nbt "{bakedRefine:3,mergeCount:0,LanceType:2}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 iron hoe named "<light blue>Iron Mailcrusher [+0]" with nbt "{bakedRefine:3,mergeCount:0,GauntletType:2}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 64 arrow named "<light blue>Iron Barbed Dagger [+0]" with nbt "{bakedRefine:3,mergeCount:0,DaggerType:2}" with lore "<white>Cost:", "%200 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 bow named "<light blue>Lunar Arc [+0]" with nbt "{bakedRefine:3,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			#Diamond weapons
			set slot 9 of the player's current inventory to 1 diamond sword named "<light blue>Diamond Armoursmasher [+0]" with nbt "{bakedRefine:3,mergeCount:0}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 diamond axe named "<light blue>Diamond Hammer [+0]" with nbt "{bakedRefine:3,mergeCount:0}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 1 diamond shovel named "<light blue>Diamond Shieldreaver [+0]" with nbt "{bakedRefine:3,mergeCount:0,LanceType:4}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 1 diamond hoe named "<light blue>Diamond Mailcrusher [+0]" with nbt "{bakedRefine:3,mergeCount:0,GauntletType:4}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 64 arrow named "<light blue>Diamond Barbed Dagger [+0]" with nbt "{bakedRefine:3,mergeCount:0,DaggerType:4}" with lore "<white>Cost:", "%500 / {_discountFactor}%"
			set slot 17 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is 7:
			open chest inventory with 2 rows named "<gold>Weapon Smith | Koenig Weapons" for the player
			#Iron weapons
			set slot 0 of the player's current inventory to 1 iron sword named "<light blue>Iron King Sword [+0]" with nbt "{bakedRefine:4,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 iron axe named "<light blue>Iron King Axe [+0]" with nbt "{bakedRefine:4,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 iron shovel named "<light blue>Iron King Lance [+0]" with nbt "{bakedRefine:4,mergeCount:0,LanceType:2}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 iron hoe named "<light blue>Iron King Gaunlets [+0]" with nbt "{bakedRefine:4,mergeCount:0,GauntletType:2}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 64 arrow named "<light blue>Iron King Dagger [+0]" with nbt "{bakedRefine:4,mergeCount:0,DaggerType:2}" with lore "<white>Cost:", "%200 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 bow named "<light blue>King Bow [+0]" with nbt "{bakedRefine:4,mergeCount:0}" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			#Diamond weapons
			set slot 9 of the player's current inventory to 1 diamond sword named "<light blue>Diamond King Sword [+0]" with nbt "{bakedRefine:4,mergeCount:0}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 diamond axe named "<light blue>Diamond King Axe [+0]" with nbt "{bakedRefine:4,mergeCount:0}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 1 diamond shovel named "<light blue>Diamond King Lance [+0]" with nbt "{bakedRefine:4,mergeCount:0,LanceType:4}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 1 diamond hoe named "<light blue>Diamond King Gaunlets [+0]" with nbt "{bakedRefine:4,mergeCount:0,GauntletType:4}" with lore "<white>Cost:", "%900 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 64 arrow named "<light blue>Diamond King Dagger [+0]" with nbt "{bakedRefine:4,mergeCount:0,DaggerType:4}" with lore "<white>Cost:", "%500 / {_discountFactor}%"
			set slot 17 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		else if arg 1 is 8:
			open chest inventory with 6 rows named "<gold>Weapon Smith | Weapon Frames" for the player
			#Tempered frames
			set slot 0 of the player's current inventory to 1 wooden sword named "<light blue>Tempered Iron Sword Frame" with nbt "{frameType:0,upgradeTier:0,oreType:0}" with lore "<white>Cost:", "%50 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 wooden axe named "<light blue>Tempered Iron Axe Frame" with nbt "{frameType:1,upgradeTier:0,oreType:0}" with lore "<white>Cost:", "%50 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 wooden shovel named "<light blue>Tempered Iron Lance Frame" with nbt "{frameType:2,upgradeTier:0,oreType:0}" with lore "<white>Cost:", "%50 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 bow named "<light blue>Tempered Bow Frame" with nbt "{frameType:3,upgradeTier:0,oreType:0}" with lore "<white>Cost:", "%50 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 wooden hoe named "<light blue>Tempered Iron Gauntlets Frame" with nbt "{frameType:4,upgradeTier:0,oreType:0}" with lore "<white>Cost:", "%50 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 arrow named "<light blue>Tempered Iron Dagger Frame" with nbt "{frameType:5,upgradeTier:0,oreType:0}" with lore "<white>Cost:", "%50 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 blaze rod named "<light blue>Tempered Wand Frame" with nbt "{frameType:8,upgradeTier:0,oreType:0}" with lore "<white>Cost:", "%50 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 book named "<light blue>Tempered Tome Frame" with nbt "{frameType:6,upgradeTier:0,oreType:0}" with lore "<white>Cost:", "%50 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 iron horse armor named "<light blue>Tempered Firearm Frame" with nbt "{frameType:7,upgradeTier:0,oreType:0}" with lore "<white>Cost:", "%50 / {_discountFactor}%"
			#Diamond Tempered
			set slot 9 of the player's current inventory to 1 wooden sword named "<light blue>Tempered Diamond Sword Frame" with nbt "{frameType:0,upgradeTier:0,oreType:2}" with lore "<white>Cost:", "%100 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 wooden axe named "<light blue>Tempered Diamond Axe Frame" with nbt "{frameType:1,upgradeTier:0,oreType:2}" with lore "<white>Cost:", "%100 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 1 wooden shovel named "<light blue>Tempered Diamond Lance Frame" with nbt "{frameType:2,upgradeTier:0,oreType:2}" with lore "<white>Cost:", "%100 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 1 wooden hoe named "<light blue>Tempered Diamond Gauntlets Frame" with nbt "{frameType:4,upgradeTier:0,oreType:2}" with lore "<white>Cost:", "%100 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 1 arrow named "<light blue>Tempered Diamond Dagger Frame" with nbt "{frameType:5,upgradeTier:0,oreType:2}" with lore "<white>Cost:", "%100 / {_discountFactor}%"
			#Weapon Casts
			set slot 18 of the player's current inventory to 1 bucket named "<light blue>Slaying-Weapon Cast" with nbt "{castType:0}" with lore "<white>Cost:", "%50 / {_discountFactor}%", "<white>Upgrades a +10 basic weapon to a Slaying weapon."
			set slot 19 of the player's current inventory to 1 bucket named "<light blue>Reinforced-Weapon Cast" with nbt "{castType:1}" with lore "<white>Cost:", "%50 / {_discountFactor}%", "<white>Upgrades a +10 basic weapon to a Reinforced weapon."
			set slot 20 of the player's current inventory to 1 bucket named "<light blue>Warding-Weapon Cast" with nbt "{castType:2}" with lore "<white>Cost:", "%50 / {_discountFactor}%", "<white>Upgrades a +10 basic weapon to a Warding weapon."
			set slot 21 of the player's current inventory to 1 bucket named "<light blue>Piercing-Weapon Cast" with nbt "{castType:3}" with lore "<white>Cost:", "%50 / {_discountFactor}%", "<white>Upgrades a +10 basic weapon to a Piercing weapon."
			set slot 22 of the player's current inventory to 1 bucket named "<light blue>Koenig-Weapon Cast" with nbt "{castType:4}" with lore "<white>Cost:", "%50 / {_discountFactor}%", "<white>Upgrades a +10 basic weapon to a Koenig weapon."
			set slot 23 of the player's current inventory to 1 bucket named "<light blue>Crushing-Weapon Cast" with nbt "{castType:5}" with lore "<white>Cost:", "%50 / {_discountFactor}%", "<white>Upgrades a +10 basic weapon to a Crushing weapon."
			#Forged frames
			set slot 27 of the player's current inventory to 1 wooden sword named "<light blue>Forged Iron Sword Frame" with nbt "{frameType:0,upgradeTier:1,oreType:0}" with lore "<white>Cost:", "%125 / {_discountFactor}%"
			set slot 28 of the player's current inventory to 1 wooden axe named "<light blue>Forged Iron Axe Frame" with nbt "{frameType:1,upgradeTier:1,oreType:0}" with lore "<white>Cost:", "%125 / {_discountFactor}%"
			set slot 29 of the player's current inventory to 1 wooden shovel named "<light blue>Forged Iron Lance Frame" with nbt "{frameType:2,upgradeTier:1,oreType:0}" with lore "<white>Cost:", "%125 / {_discountFactor}%"
			set slot 30 of the player's current inventory to 1 bow named "<light blue>Forged Bow Frame" with nbt "{frameType:3,upgradeTier:1,oreType:0}" with lore "<white>Cost:", "%125 / {_discountFactor}%"
			set slot 31 of the player's current inventory to 1 wooden hoe named "<light blue>Forged Iron Gauntlets Frame" with nbt "{frameType:4,upgradeTier:1,oreType:0}" with lore "<white>Cost:", "%125 / {_discountFactor}%"
			set slot 32 of the player's current inventory to 1 arrow named "<light blue>Forged Iron Dagger Frame" with nbt "{frameType:5,upgradeTier:1,oreType:0}" with lore "<white>Cost:", "%125 / {_discountFactor}%"
			set slot 32 of the player's current inventory to 1 blaze rod named "<light blue>Forged Wand Frame" with nbt "{frameType:8,upgradeTier:1,oreType:0}" with lore "<white>Cost:", "%125 / {_discountFactor}%"
			set slot 32 of the player's current inventory to 1 book named "<light blue>Forged Tome Frame" with nbt "{frameType:6,upgradeTier:1,oreType:0}" with lore "<white>Cost:", "%125 / {_discountFactor}%"
			set slot 32 of the player's current inventory to 1 iron horse armor named "<light blue>Forged Firearm Frame" with nbt "{frameType:7,upgradeTier:1,oreType:0}" with lore "<white>Cost:", "%125 / {_discountFactor}%"
			#Diamond Forged
			set slot 36 of the player's current inventory to 1 wooden sword named "<light blue>Forged Diamond Sword Frame" with nbt "{frameType:0,upgradeTier:1,oreType:2}" with lore "<white>Cost:", "%200 / {_discountFactor}%"
			set slot 37 of the player's current inventory to 1 wooden axe named "<light blue>Forged Diamond Axe Frame" with nbt "{frameType:1,upgradeTier:1,oreType:2}" with lore "<white>Cost:", "%200 / {_discountFactor}%"
			set slot 38 of the player's current inventory to 1 wooden shovel named "<light blue>Forged Diamond Lance Frame" with nbt "{frameType:2,upgradeTier:1,oreType:2}" with lore "<white>Cost:", "%200 / {_discountFactor}%"
			set slot 39 of the player's current inventory to 1 wooden hoe named "<light blue>Forged Diamond Gauntlets Frame" with nbt "{frameType:4,upgradeTier:1,oreType:2}" with lore "<white>Cost:", "%200 / {_discountFactor}%"
			set slot 40 of the player's current inventory to 1 arrow named "<light blue>Forged Diamond Dagger Frame" with nbt "{frameType:5,upgradeTier:1,oreType:2}" with lore "<white>Cost:", "%200 / {_discountFactor}%"
			#Sacred Treasure
			set slot 45 of the player's current inventory to 1 nether star named "<gold>Mythic Cast" with nbt "{frameType:0,upgradeTier:1,oreType:776}" with lore "<white>Cost:", "%2500 / {_discountFactor}%", "<italics>Upgrades a Diamond +10 evolved weapon even further."
			set slot 46 of the player's current inventory to 1 wooden sword named "<light blue>Purified Diamond Weapon Frame" with nbt "{frameType:0,upgradeTier:2,oreType:2}" with lore "<white>Cost:", "%2500 / {_discountFactor}%", "<italics>Adds a merge to any mythic weapon."
			set slot 53 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		#Netherite
		else if arg 1 is 9:
			#Tempered
			set slot 0 of the player's current inventory to 1 wooden sword named "<light blue>Tempered Netherite Sword Frame" with nbt "{frameType:0,upgradeTier:0,oreType:3}" with lore "<white>Cost:", "%175 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 wooden axe named "<light blue>Tempered Netherite Axe Frame" with nbt "{frameType:1,upgradeTier:0,oreType:3}" with lore "<white>Cost:", "%175 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 wooden shovel named "<light blue>Tempered Netherite Lance Frame" with nbt "{frameType:2,upgradeTier:0,oreType:3}" with lore "<white>Cost:", "%175 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 wooden hoe named "<light blue>Tempered Netherite Gauntlets Frame" with nbt "{frameType:4,upgradeTier:0,oreType:3}" with lore "<white>Cost:", "%175 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 arrow named "<light blue>Tempered Netherite Dagger Frame" with nbt "{frameType:5,upgradeTier:0,oreType:3}" with lore "<white>Cost:", "%175 / {_discountFactor}%"
			#Weapon Casts
			set slot 9 of the player's current inventory to 1 bucket named "<light blue>Slaying-Weapon Cast" with nbt "{castType:0}" with lore "<white>Cost:", "%50 / {_discountFactor}%", "<white>Upgrades a +10 basic weapon to a Slaying weapon."
			set slot 10 of the player's current inventory to 1 bucket named "<light blue>Reinforced-Weapon Cast" with nbt "{castType:1}" with lore "<white>Cost:", "%50 / {_discountFactor}%", "<white>Upgrades a +10 basic weapon to a Reinforced weapon."
			set slot 11 of the player's current inventory to 1 bucket named "<light blue>Warding-Weapon Cast" with nbt "{castType:2}" with lore "<white>Cost:", "%50 / {_discountFactor}%", "<white>Upgrades a +10 basic weapon to a Warding weapon."
			set slot 12 of the player's current inventory to 1 bucket named "<light blue>Piercing-Weapon Cast" with nbt "{castType:3}" with lore "<white>Cost:", "%50 / {_discountFactor}%", "<white>Upgrades a +10 basic weapon to a Piercing weapon."
			set slot 13 of the player's current inventory to 1 bucket named "<light blue>Koenig-Weapon Cast" with nbt "{castType:4}" with lore "<white>Cost:", "%50 / {_discountFactor}%", "<white>Upgrades a +10 basic weapon to a Koenig weapon."
			set slot 14 of the player's current inventory to 1 bucket named "<light blue>Crushing-Weapon Cast" with nbt "{castType:5}" with lore "<white>Cost:", "%50 / {_discountFactor}%", "<white>Upgrades a +10 basic weapon to a Crushing weapon."
			#Forged
			set slot 18 of the player's current inventory to 1 wooden sword named "<light blue>Forged Diamond Sword Frame" with nbt "{frameType:0,upgradeTier:1,oreType:3}" with lore "<white>Cost:", "%325 / {_discountFactor}%"
			set slot 19 of the player's current inventory to 1 wooden axe named "<light blue>Forged Diamond Axe Frame" with nbt "{frameType:1,upgradeTier:1,oreType:3}" with lore "<white>Cost:", "%325 / {_discountFactor}%"
			set slot 20 of the player's current inventory to 1 wooden shovel named "<light blue>Forged Diamond Lance Frame" with nbt "{frameType:2,upgradeTier:1,oreType:3}" with lore "<white>Cost:", "%325 / {_discountFactor}%"
			set slot 21 of the player's current inventory to 1 wooden hoe named "<light blue>Forged Diamond Gauntlets Frame" with nbt "{frameType:4,upgradeTier:1,oreType:3}" with lore "<white>Cost:", "%325 / {_discountFactor}%"
			set slot 22 of the player's current inventory to 1 arrow named "<light blue>Forged Diamond Dagger Frame" with nbt "{frameType:5,upgradeTier:1,oreType:3}" with lore "<white>Cost:", "%325 / {_discountFactor}%"
			set slot 26 of the player's current inventory to 1 red glass pane named "<bold>Go Back"			

command /toddshop:
	trigger:
		set {_discountFactor} to ({abilities.%player%::Barter} / 20)
		if {_discountFactor} is less than 0.5:
			set {_discountFactor} to 0.5
		else if {_discountFactor} is more than 2:
			set {_discountFactor} to ({_discountFactor} ^ 0.8)
			if {_discountFactor} is less than 2:
				set {_discountFactor} to 2
		if {traits.%player%::Physician} is true:
			set {_discountFactor} to {_discountFactor} * 0.8
		if {toddRNG} is set:
			set {toddInventory} to a random integer from 1 to 3
			clear {toddRNG}
		open chest inventory with 2 rows named "<gold>Todd's General Goods" for the player
		if {toddInventory} is 1:
			set slot 0 of the player's current inventory to 1 tnt named "<white>Workbench" with lore "<white>Cost:", "%32 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 redstone block named "<white>Furnace" with lore "<white>Cost:", "%80 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 32 cobblestone with lore "<white>Cost:", "%192 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 32 oak log with lore "<white>Cost:", "%256 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 iron sword of sharpness 2 named "<white>Nordic Greatsword" with lore "<white>Cost:", "%130 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 32 arrow with lore "<white>Cost:", "%128 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 stone pickaxe of looting 3 named "<white>Notched Pickaxe" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 iron helmet of protection 2 named "<white>Nordic Helmet" with lore "<white>Cost:", "%400 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 leather chestplate of protection 2 named "<white>Reinforced Leather Armour" with lore "<white>Cost:", "%160 / {_discountFactor}%"
			set slot 9 of the player's current inventory to 1 music disc cat named "<light green><bold>Recover Ring" with lore "<white>Cost:", "%4000 / {_discountFactor}%", "<gold>Restores 50%% of your maximum HP every 15 seconds."
			set slot 10 of the player's current inventory to 1 music disc strad named "<white><bold>Shield Ring" with lore "<white>Cost:", "%1200 / {_discountFactor}%", "<gold>Grants Resistance 2 while in your inventory."
		else if {toddInventory} is 2:
			set slot 0 of the player's current inventory to 1 tnt named "<white>Workbench" with lore "<white>Cost:", "%32 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 redstone block named "<white>Furnace" with lore "<white>Cost:", "%80 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 32 granite with lore "<white>Cost:", "%192 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 32 birch log with lore "<white>Cost:", "%256 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 iron sword with lore "<white>Cost:", "%120 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 16 arrow with lore "<white>Cost:", "%128 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 iron pickaxe of fortune 3 named "<white>Lucky's Pickaxe" with lore "<white>Cost:", "%700 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 iron leggings of protection 2 named "<white>Skyforge Leggings" with lore "<white>Cost:", "%350 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 leather boots of protection 2 named "<white>Reinforced Leather Boots" with lore "<white>Cost:", "%80 / {_discountFactor}%"
			set slot 9 of the player's current inventory to 64 torches with lore "<white>Cost:", "%128 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 iron sword of smite 3 named "<white>Iron Sword of Purging" with lore "<white>Cost:", "%400 / {_discountFactor}%"
		else:
			set slot 0 of the player's current inventory to 1 tnt named "<white>Workbench" with lore "<white>Cost:", "%32 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 redstone block named "<white>Furnace" with lore "<white>Cost:", "%80 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 32 andesite with lore "<white>Cost:", "%192 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 32 jungle log with lore "<white>Cost:", "%256 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 iron shovel named "<bold>Iron Lance" with lore "<white>Cost:", "%180 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 64 arrow with lore "<white>Cost:", "%256 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 iron pickaxe of unbreaking 2, efficiency 1 named "<white>Steel Pickaxe" with lore "<white>Cost:", "%220 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 iron chestplate of protection 1 named "<white>Steel Chestplate" with lore "<white>Cost:", "%420 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 leather chestplate of unbreaking 3 named "<white>Leather Chestplate of Strength" with lore "<white>Cost:", "%750 / {_discountFactor}%"
			set slot 9 of the player's current inventory to 64 torches with lore "<white>Cost:", "%128 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 iron sword of smite 3 named "<white>Iron Sword of Purging" with lore "<white>Cost:", "%400 / {_discountFactor}%"

command /hwbuy <text> [<text="NULL">]:
	trigger:
		if arg 1 is "HW":
			open chest inventory with 6 rows named "<gold><bold>Sacred Treasures" for the player
			set slot 0 of the player's current inventory to 1 diamond sword named "<gold><bold>Falchion" with lore "<white>Grants increased damage the farther away you are from your foe during combat.", "<white>Deals effective damage to end-type foes.", "<light green>Unique Refine:", "<light green>Grants STR/MAG/SPD/LCK/DEF/RES +4 to allies within 15 blocks during combat.", "<white>Weapon Ability: +30"
			set slot 1 of the player's current inventory to 1 diamond sword named "<gold><bold>Binding Blade" with lore "<white>+4 weapon might.", "<white>Grants DEF/RES +4 while equipped.", "<white>Deals effective damage to end-type foes.", "<light green>Unique Refine:", "<light green>Reduces damage suffered by 20%% during combat.", "<light green>Grants <light blue>[Quick Riposte]<light green>.", "<light blue>[Quick Riposte]: <white>Automatically counter-attack foes during combat.", "<white>Quick Riposte's effect only activates if foe is in range.", "<white>Weapon Ability: +30"
			set slot 2 of the player's current inventory to 1 diamond sword named "<gold><bold>Tyrfing" with lore "<white>+4 weapon might.", "<white>Reduces ranged damage suffered by 25%%.", "<white>Grants <light purple>[Miracle]<white>.", "<light green>Unique Refine:", "<light green>Grants RES +10, SPD/LCK +5.", "<light purple>[Miracle]: <white>Nullifies foe's attack if it would kill the player during combat.", "<white>Activation chance: (SKL * 0.5)", "<white>Max: 50%%", "<white>Weapon Ability: +30"
			set slot 3 of the player's current inventory to 1 diamond sword named "<gold><bold>Ragnell" with lore "<white>+8 weapon might.", "<white>Grants <light purple>[Radiant Aether].", "<light green>Unique Refine:", "<light green>+4 weapon might (+12 total).", "<light green>Grants <light red>[Distant Counter]<light green>.", "<light red>[Distant Counter]: <white>Counter-attack ranged foes automatically when hit.", "<light purple>[Radiant Aether]: <white>Activate Luna and Sol in one strike.", "<white>Exclusive to Ragnell.", "<white>Weapon Ability: +65"
			set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Light Brand" with lore "<white>+2 weapon might.", "<white>Grants LCK +10 while equipped.", "<white>Damage from this weapon is calculated using the", "<white>lower of the foe's DEF or MAG, and, if targeting MAG,", "<white>treats the player's MAG as their STR during damage calculation.", "<light green>Unique Refine:", "<light green>Accelerates Special activation (+10%% activation chance).", "<light green>Grants <light red>[Armour Smasher]<light green>.", "<white>Weapon Ability: +45"
			set slot 5 of the player's current inventory to 1 diamond axe named "<gold><bold>Armads" with lore "<white>+6 weapon might.", "<white>Grants <light red>[Distant Counter]<white>.", "<light green>Unique Refine:", "<light green>Reduces damage from ranged attacks by 40%%.", "<light green>Grants <light blue>[Quick Riposte]<light green>.", "<light red>[Distant Counter]: <white>Counter-attack ranged foes automatically when hit.", "<light blue>[Quick Riposte]: <white>Automatically counter-attack foes during combat.", "<white>Riposte's effect only activates if foe is in range.", "<white>Weapon Ability: +50"
			set slot 6 of the player's current inventory to 1 bow named "<gold><bold>Parthia" with lore "<white>+3 weapon might.", "<white>Reduces ranged damage suffered by 20%%.", "<white>Grants <light blue>[Experience Sapper]<white>.", "<light green>Unique Refine:", "<light green>+10 weapon might against ranged opponents.", "<light green>Inflicts Slowness/Weakness 2 on foe after combat.", "<white>Weapon Ability: +30"
			set slot 7 of the player's current inventory to 1 iron horse armour named "<gold><bold>Super Shotgun" with lore "<white>The double-barreled classic. Plenty of risk & plenty of reward.", "<white>Right-click to fire.", "<white>Left-click to reload. Costs 6 gold nuggets.", "<white>Weapon Ability: +65"
			set slot 8 of the player's current inventory to 1 diamond shovel named "<gold><bold>Siegmund" with lore "<white>+5 weapon might.", "<white>Grants <light green>[Rally Strength]<white>.", "<light green>Unique Refine:", "<light green>If number of foes >= number of allies within 10 blocks:", "<light green>Weapon attacks twice during combat.", "<light green>[Rally Strength]: <white>Grants Strength 2 to allies when right-clicked.", "<white>Weapon Ability: +40"
			set slot 9 of the player's current inventory to 1 diamond sword named "<gold><bold>Sieglinde" with lore "<white>+5 weapon might.", "<white>Grants <light green>[Rally Strength]<white>.", "<light green>Unique Refine:", "<light green>Rallies also apply to yourself.", "<light green>Rally skills and perks apply in a 7-block radius.", "<light green>[Rally Strength]: <white>Grants Strength 2 to allies when right-clicked.", "<white>Weapon Ability: +30"
			set slot 10 of the player's current inventory to 1 diamond sword named "<gold><bold>Durandal" with lore "<white>+4 weapon might.", "<white>Grants <gold>[Crushing]<white>.", "<light green>Unique Refine:", "<light green>Accelerates Special activation (+10%% activation chance).", "<light green>Grants <light red>[Sturdy Impact]<light green>.", "<gold>[Crushing]: <white>Accelerates Special activation based on damage dealt.", "<white>Minimum of 7 damage dealt required to activate effect.", "<white>Weapon Ability: +40"
			set slot 11 of the player's current inventory to 1 diamond shovel named "<gold><bold>Gae Bolg" with lore "<white>Grants STR/DEF/SKL +4 while equipped.", "<white>Grants <light blue>[Guard]<white>.", "<light blue>[Guard]: <white>Inflicts SKL -50 on foe during combat.", "<white>Weapon Ability: +30"
			set slot 12 of the player's current inventory to 1 diamond sword named "<gold><bold>Mercurius" with lore "<white>+3 weapon might.", "<white>Grants <light blue>[Experience Sapper]<white>.", "<light blue>[Experience Sapper]: <white>Increases EXP awarded for defeating foes.", "<white>Weapon Ability: +19"
			set slot 13 of the player's current inventory to 1 diamond axe named "<gold><bold>Basilikos" with lore "<white>+6 weapon might.", "<light green>Unique Refine:", "<light green>Increases damage dealt and suffered during combat by 50%%.", "<light red>Weapon Ability: +23"
			set slot 14 of the player's current inventory to 1 diamond axe named "<gold><bold>Hauteclere" with lore "<white>+3 weapon might.", "<white>Grants LCK +10 while equipped.", "<white>Accelerates Special skill activation (+15%% activation chance).", "<light green>Unique Refine:", "<light green>Accelerates Special trigger (+5%% activation chance).", "<light green>If Special activates, increases damage dealt by 5 hearts.", "<white>Weapon Ability: +50"
			set slot 15 of the player's current inventory to 1 diamond sword named "<gold><bold>Mystletainn" with lore "<white>+4 weapon might.", "<white>Grants LCK +10 while equipped.", "<white>If HP < 75%%, grants LCK +10, and deals +5 damage when Special activates.", "<light green>Unique refine:", "<light green>Grants <light red>[Fury]<light green>.", "<white>Weapon Ability: +50"
			set slot 16 of the player's current inventory to 1 diamond shovel named "<gold><bold>Fensalir" with lore "<white>+4 weapon might.", "<white>While within 10 blocks of a party member, grants +8 weapon might.", "<light green>Unique Refine:", "<light green>While within 15 blocks of a party member, grants STR/SKL +7 during combat.", "<white>Weapon Ability: +30"
			set slot 17 of the player's current inventory to 1 diamond sword named "<gold><bold>Folkvangr" with lore "<white>+4 weapon might.", "<white>While within 10 blocks of a party member, grants +8 weapon might.", "<light green>Unique Refine:", "<light green>If HP < 70%%, grants STR/DEF +7.", "<white>Weapon Ability: +30"
			set slot 18 of the player's current inventory to 1 diamond shovel named "<gold><bold>Gradivus" with lore "<white>+4 weapon might.", "<white>Grants <light blue>[Experience Sapper]<white>.", "<light blue>[Experience Sapper]: <white>Increases EXP awarded for defeating foes.", "<white>Weapon Ability: +19"
			#set slot 19 of the player's current inventory to 1 diamond horse armour named "<gold><bold>Love is Blue" with lore "<white>Right-click to fire bullets at the cost of EXP.", "Melee hits restore 5 EXP.", "<bold>Skills cannot be equipped to this weapon.", "<bold>This weapon cannot be refined."
			#set slot 20 of the player's current inventory to 1 gold horse armour named "<gold><bold>Scarborough Fair" with lore "<white>Right-click to fire bullets at the cost of EXP.", "Melee hits restore 5 EXP.", "<bold>Skills cannot be equipped to this weapon.", "<bold>This weapon cannot be refined."
			set slot 19 of the player's current inventory to 1 diamond sword named "<gold><bold>Balder Side Sword" with lore "<white>+4 weapon might.", "<white>Right-click to parry attacks.", "<white>Parry has a 0.5 second cooldown.", "<light green>Unique Refine:", "<light green>Grants STR/DEF +7 when attacked.", "<white>Weapon Ability: +30"
			set slot 20 of the player's current inventory to 1 bow named "<gold><bold>Fujin Yumi" with lore "<white>Grants MAG/RES +10 while equipped.", "<white>Grants <light red>[Close Counter]<white>.", "<light green>Unique Refine:", "<light green>Holding sneak and firing an arrow teleports you to where it lands.", "<light red>[Close Counter]: <white>Automatically counter-attacks melee foes during combat.", "<white>Weapon Ability: +35"
			set slot 21 of the player's current inventory to 1 diamond sword named "<gold><bold>Blessed Sword" with lore "<white>Reduces damage suffered by 1.5 hearts during combat.", "<white>Deals 2x damage to monsters.", "<white>Grants <light blue>[Plenitude]<white>.", "<light green>Unique Refine:", "<light green>Grants Regeneration 2 while equipped.", "<light green>Nullifies negative potion effects.", "<light blue>[Plenitude]: <white>Restores hunger and randomly drops steak when a foe is defeated.", "<white>Weapon Ability: +60"
			set slot 22 of the player's current inventory to 1 diamond axe named "<gold><bold>Devil Axe" with lore "<white>+3 weapon might.", "<white>Grants <light red>[Fury]<white>.", "<white>Inflicts Wither 4 on foe after combat.", "<light green>Unique Refine:", "<light green>Grants <light red>[Fury]<light green> and <light blue>[Wrath]<light green>.", "<white>Weapon Ability: +60"
			set slot 23 of the player's current inventory to 1 diamond shovel named "<gold><bold>Crusader's Lance" with lore "<white>+8 weapon might.", "<white>Can be thrown for no durability cost.", "<white>Reduces damage suffered by 15%% during combat.", "<light green>Unique Refine:", "<light green>Reduces damage suffered by 15%% during combat.", "<light green>Boosts damage dealt by 20%% while above 80%% HP.", "<white>Weapon Ability: +60"
			set slot 24 of the player's current inventory to 1 bow named "<gold><bold>Lunar Bow" with lore "<white>+3 weapon might.", "<white>Grants <light purple>[Luna]<white>.", "<light green>Unique Refine:", "<light green>If Special activates, increases damage by 20%% of the player's SPD.", "<light green>Calculates damage using the lower of foe's DEF or MAG.", "<white>Weapon Ability: +60"
			set slot 25 of the player's current inventory to 1 diamond shovel named "<gold><bold>Rex Hasta" with lore "<white>Increases damage dealt by Special activations by 5 hearts.", "<light green>Unique Refine:", "<light green>Grants <light blue>[Wrath]<light green>.", "<light green>If Special skill activates, boosts damage dealt by 25%%.", "<white>Weapon Ability: +40"
			set slot 26 of the player's current inventory to 1 diamond sword named "<gold><bold>Meisterschwert" with lore "<white>Grants <light blue>[Brave Blade]<white>.", "<light green>Unique Refine:", "<light green>Grants SPD +5 while equipped.", "<light green>Grants <light blue>[Quick Riposte]<light green>.", "<white>Weapon Ability: +40"
			set slot 27 of the player's current inventory to 1 book named "<gold><bold>Dire Thunder" with lore "<white>Grants <light blue>[Brave Blade]<white>.", "<light green>Unique Refine:", "<light green>Grants SPD +5 while equipped.", "<light green>Grants <light blue>[Quick Riposte]<light green>.", "<white>Weapon Ability: +40"
			set slot 28 of the player's current inventory to 1 diamond shovel named "<gold><bold>Rhomphaia" with lore "<white>Deals bonus damage equal to 25%% of the player's SPD.", "<white>Weapon Ability: +60"
			set slot 29 of the player's current inventory to 1 diamond sword named "<gold><bold>Alondite" with lore "<white>Grants <gold>[Nihl]<white>.", "<white>Grants <light purple>[Eclipse]<white>.", "<light purple>[Eclipse]: <white>Pierces armour and reduces foe's DEF/MAG by 80%%.", "<white>Activation chance: (LCK ^ 0.65) | Max: 50%%.", "<gold>[Nihl]:", "<white>Disables foe's skills and perks that guarantee counter-attacks and prevent player's follow-up attacks.", "<white>Weapon Ability: +100"
			set slot 30 of the player's current inventory to 1 bow named "<gold><bold>Guard Bow" with lore "<white>Reduces damage suffered by 1.5 hearts.", "<white>Weapon Ability: +19"
			set slot 31 of the player's current inventory to 1 bow named "<gold><bold>Brave Bow" with lore "<white>Inflicts SPD -5.", "<white>-3 weapon might.", "<white>Weapon attacks twice during combat.", "<white>Weapon Ability: +24"
			set slot 32 of the player's current inventory to 1 diamond axe named "<gold><bold>Tomahawk" with lore "<white>Grants <gold>[Distant Counter]<white>.", "<gold>[Distant Counter]<white>: Automatically retaliate against ranged opponents.", "<white>Weapon Ability: +19"
			set slot 33 of the player's current inventory to 1 diamond shovel named "<gold><bold>Javelin" with lore "<white>Grants <gold>[Distant Counter]<white>.", "<gold>[Distant Counter]<white>: Automatically retaliate against ranged opponents.", "<white>Weapon Ability: +19"
			set slot 34 of the player's current inventory to 1 diamond sword named "<gold><bold>Tornado Blade" with lore "<white>Grants <gold>[Distant Counter]<white>.", "<gold>[Distant Counter]<white>: Automatically retaliate against ranged opponents.", "<white>Weapon Ability: +19"
			set slot 35 of the player's current inventory to 1 diamond shovel named "<gold><bold>Swift-Winds Lance" with lore "<white>Grants <gold>[Sweeper]<white>.", "<white>If player initiates combat, grants STR/SPD +4 during combat.", "<light green>Unique Refine:", "<light green>If any ally within 15 blocks shares the wielder's class:", "<light green>Grants STR/SPD +12.", "<gold>[Sweeper]<white>: Disables player & foe's skills that guarantee counter-attacks during combat.", "<white>Weapon Ability: +35"
			set slot 36 of the player's current inventory to 1 diamond sword named "<gold><bold>Kindled-Fire Sword" with lore "<white>Grants <light blue>[Brave Blade]<white>.", "<white>If player's HP >= foe's HP -3:", "<white>Grants STR/DEF +7 during combat.", "<light green>Unique Refine:", "<light green>If any ally within 15 blocks shares the wielder's class:", "<light green>Grants STR/DEF +12.",  "<white>Weapon Ability: +35"
			#set slot 37 of the player's current inventory to 1 diamond axe named "<gold><bold>Axtinguisher" with lore "<white>+50%% damage against burning targets.", "<white>-50%% damage against non-burning targets."
			set slot 37 of the player's current inventory to 1 diamond sword named "<gold><bold>Yamato" with lore "<white>+3 weapon might.", "<white>Grants <light blue><bold>[Judgement Cut]<reset><white>.", "<light blue><bold>[Judgement Cut]:<reset><white> Sneak and right-click to activate.", "<white>Gain power by holding sneak, then unleash it by standing up.", "<white>Targets all foes within 20 blocks. Damage based on charge time.", "<white>Weapon Ability: +100"
			set slot 38 of the player's current inventory to 1 bow named "<gold><bold>Bow of Aresha" with lore "<white>If player's DEF >= Foe's DEF +5:", "<white>Grants STR/DEF +X,", "<white>Where X = (Player's DEF - [foe's DEF + 5])", "<white>(Maximum bonus of +15 to each stat.)", "<white>Weapon Ability: +60"
			set slot 39 of the player's current inventory to 1 diamond sword named "<gold><bold>Rebellion" with lore "<white>Hold Sneak and Right-click to change this weapon's active Style.", "<white>Right-click to use the active Style's ability.", "<light red>Trickster: Dash forwards invincibily.", "<orange>Swordmaster: Launch enemies into the air.", "<light green>Gunslinger: Fire damaging shockwaves from the sword.", "<light blue>Royalguard: Block an attack and add the blocked damage to your next attack.", "<white>Weapon Ability: +50"
			set slot 40 of the player's current inventory to 1 diamond axe named "<gold><bold>Daybreak Axe" with lore "<white>Grants MAG +10 while equipped.", "<white>Restores 3 hearts of health after damage calculation.", "<light green>Unique Refine:", "<light green>Restores health equal to 25%% of damage dealt during combat.", "<light green>If a Special skill activates and deals damage:", "<light green>Restores health equal to 30%% of damage dealt.", "<white>Weapon Ability: +60"
			set slot 41 of the player's current inventory to 1 iron horse armour named "<gold><bold>Martin Mil-4 Automatic" with lore "<white>Sneak + right click a wall to take cover behind it.", "<white>While in cover, restores 0.5 HP/s", "<white>Firing your weapon while in cover will blind-fire over it, if it is less than 2.5 blocks tall.", "<italics>What happened here was out of my control.", "<white>Weapon Ability: +70"
		else if arg 1 is "hw2":
			set {_discountFactor} to ({abilities.%player%::Barter} / 20)
			if {_discountFactor} is less than 0.5:
				set {_discountFactor} to 0.5
			else if {_discountFactor} is more than 2:
				set {_discountFactor} to ({_discountFactor} ^ 0.8)
				if {_discountFactor} is less than 2:
					set {_discountFactor} to 2
			if {traits.%player%::Physician} is true:
				set {_discountFactor} to {_discountFactor} * 0.8
			open chest inventory with 1 row named "<gold><bold>Sacred Treasures | Inspection" for the player
			set {_weapon} to uncoloured name of slot 4 of the player's current inventory
			remove "<gold><bold>" from {_weapon}
			if {_weapon} is "Basilikos":
				set {_price} to 750
			else if {_weapon} is "Mercurius":
				set {_price} to 750
			else if {_weapon} is "Hauteclere":
				set {_price} to 750
			else if {_weapon} is "Gradivus":
				set {_price} to 750
			else if {_weapon} is "Super Shotgun":
				set {_price} to 750
			else:
				set {_price} to 1000
			set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
			set slot 8 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
			set slot 3 of the player's current inventory to 1 emerald named "<gold><bold>Summon Weapon" with lore "<white>Price: %{_price}%"
			set slot 4 of the player's current inventory to 1 cobblestone named "<gold><bold>%arg 2%"
			#set slot 5 of the player's current inventory to 1 nether star named "<gold><bold>Warp to Heroic Challenge"
			
command /tavernshop:
	trigger:
		set {_discountFactor} to ({abilities.%player%::Barter} / 20)
		if {_discountFactor} is less than 0.5:
			set {_discountFactor} to 0.5
		else if {_discountFactor} is more than 2:
			set {_discountFactor} to ({_discountFactor} ^ 0.8)
			if {_discountFactor} is less than 2:
				set {_discountFactor} to 2
		if {traits.%player%::Physician} is true:
			set {_discountFactor} to {_discountFactor} * 0.8
		open chest inventory with 2 rows named "<gold>Innkeeper" for the player
		set slot 0 of the player's current inventory to 4 cooked beef with lore "<white>Cost:", "%32 / {_discountFactor}%"
		set slot 1 of the player's current inventory to 4 cooked porkchop with lore "<white>Cost:", "%32 / {_discountFactor}%"
		set slot 2 of the player's current inventory to 2 apple with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 3 of the player's current inventory to 1 potion of healing with lore "<white>Cost:", "%15 / {_discountFactor}%"
		set slot 4 of the player's current inventory to 1 green dye named "<light green><bold>Sacred Herb" with lore "<white>Cost:", "%100 / {_discountFactor}%", "<white>Restores 6 HP when used from your inventory."
		set slot 5 of the player's current inventory to 1 green dye named "<green><bold>Baked Herb" with lore "<white>Cost:", "%125 / {_discountFactor}%", "<white>Restores 3 HP and 3 Hunger when eaten."
		set slot 6 of the player's current inventory to 1 white bed named "<light blue><bold>Rest" with lore "<white>Cost:", "%48 / {_discountFactor}%", "<white><italics>Rest at this inn to restore all health and hunger."
		set slot 7 of the player's current inventory to 1 yellow dye named "<light yellow><bold>Golden Herb" with lore "<white>Cost:", "%200 / {_discountFactor}%", "<white>Restores 12 HP when used from your inventory."
		set slot 8 of the player's current inventory to 1 yellow dye named "<yellow><bold>Baked Golden Herb" with lore "<white>Cost:", "%240 / {_discountFactor}%", "<white>Restores 6 HP and 6 Hunger when used from your inventory."
	
command /farmershop:
	trigger:
		set {_discountFactor} to ({abilities.%player%::Barter} / 20)
		if {_discountFactor} is less than 0.5:
			set {_discountFactor} to 0.5
		else if {_discountFactor} is more than 2:
			set {_discountFactor} to ({_discountFactor} ^ 0.8)
			if {_discountFactor} is less than 2:
				set {_discountFactor} to 2
		if {traits.%player%::Physician} is true:
			set {_discountFactor} to {_discountFactor} * 0.8
		open chest inventory with 2 rows named "<gold>Farmer's Market" for the player
		set slot 0 of the player's current inventory to 4 wheat seeds named "Wheat Seeds" with lore "<white>Cost:", "%8 / {_discountFactor}%"
		set slot 1 of the player's current inventory to 2 melon seeds with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 2 of the player's current inventory to 2 pumpkin seeds with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 3 of the player's current inventory to 8 beetroot seeds with lore "<white>Cost:", "%8 / {_discountFactor}%"
		set slot 4 of the player's current inventory to 6 bone meal with lore "<white>Cost:", "%36 / {_discountFactor}%"
		set slot 5 of the player's current inventory to 1 bucket with lore "<white>Cost:", "%60 / {_discountFactor}%"
		set slot 6 of the player's current inventory to 1 cow spawn egg with lore "<white>Cost:", "%110 / {_discountFactor}%"
		set slot 7 of the player's current inventory to 1 chicken spawn egg with lore "<white>Cost:", "%70 / {_discountFactor}%"
		set slot 8 of the player's current inventory to 1 pig spawn egg with lore "<white>Cost:", "%90 / {_discountFactor}%"
		set slot 9 of the player's current inventory to 1 horse spawn egg with lore "<white>Cost:", "%60 / {_discountFactor}%"
		set slot 10 of the player's current inventory to 1 rabbit spawn egg with lore "<white>Cost:", "%50 / {_discountFactor}%"
		
	
command /serositabarkeep:
	trigger:
		set {_discountFactor} to ({abilities.%player%::Barter} / 20)
		if {_discountFactor} is less than 0.5:
			set {_discountFactor} to 0.5
		else if {_discountFactor} is more than 2:
			set {_discountFactor} to ({_discountFactor} ^ 0.8)
			if {_discountFactor} is less than 2:
				set {_discountFactor} to 2
		if {traits.%player%::Physician} is true:
			set {_discountFactor} to {_discountFactor} * 0.8
		open chest inventory with 2 rows named "<gold>Serosita Barkeep" for the player
		set slot 0 of the player's current inventory to 4 cooked beef with lore "<white>Cost:", "%48 / {_discountFactor}%"
		set slot 1 of the player's current inventory to 4 cooked porkchop with lore "<white>Cost:", "%48 / {_discountFactor}%"
		set slot 2 of the player's current inventory to 2 apple with lore "<white>Cost:", "%20 / {_discountFactor}%"
		set slot 3 of the player's current inventory to 1 potion of healing with lore "<white>Cost:", "%50 / {_discountFactor}%"
		set slot 4 of the player's current inventory to 1 green dye named "<light green><bold>Sacred Herb" with lore "<white>Cost:", "%100 / {_discountFactor}%", "<white>Restores 6 HP when used from your inventory."
		set slot 5 of the player's current inventory to 1 green dye named "<green><bold>Baked Herb" with lore "<white>Cost:", "%125 / {_discountFactor}%", "<white>Restores 3 HP and 3 Hunger when eaten."
		set slot 6 of the player's current inventory to 1 potion of level 2 healing named "<light yellow>Serosita Glistening Wine" with lore "<white>Cost:", "%80 / {_discountFactor}%", "<white>A popular wine sold by the Serosita Brewery.", "<white>It boasts healing capabilities."
		set slot 7 of the player's current inventory to 1 potion of extended strength named "<light yellow>Serosita Flametounge Brandy" with lore "<white>Cost:", "%60 / {_discountFactor}%", "<white>Widely popular brandy produced by the Serosita Brewery.", "<white>Invigorating and refreshing."
		if {quests.%player%::Legend in the Making} is 999:
			set slot 6 of the player's current inventory to 1 yellow dye named "<light yellow><bold>Golden Herb" with lore "<white>Cost:", "%200 / {_discountFactor}%", "<white>Restores 12 HP when used from your inventory."
			set slot 7 of the player's current inventory to 1 yellow dye named "<yellow><bold>Baked Golden Herb" with lore "<white>Cost:", "%240 / {_discountFactor}%", "<white>Restores 6 HP and 6 Hunger when used from your inventory."
			
command /tailorshop:
	trigger:
		set {_discountFactor} to ({abilities.%player%::Barter} / 20)
		if {_discountFactor} is less than 0.5:
			set {_discountFactor} to 0.5
		else if {_discountFactor} is more than 2:
			set {_discountFactor} to ({_discountFactor} ^ 0.8)
			if {_discountFactor} is less than 2:
				set {_discountFactor} to 2
		if {traits.%player%::Physician} is true:
			set {_discountFactor} to {_discountFactor} * 0.8
		open chest inventory with 3 rows named "<gold>Tailor" for the player
		set slot 0 of the player's current inventory to 1 ink sac with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 1 of the player's current inventory to 1 gray dye with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 2 of the player's current inventory to 1 light gray dye with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 3 of the player's current inventory to 1 bone meal with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 4 of the player's current inventory to 1 red dye with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 5 of the player's current inventory to 1 pink dye with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 6 of the player's current inventory to 1 purple dye with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 7 of the player's current inventory to 1 green dye with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 8 of the player's current inventory to 1 lime dye with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 9 of the player's current inventory to 1 cocoa beans with lore "<white>Cost:", "%20 / {_discountFactor}%"
		set slot 10 of the player's current inventory to 1 yellow dye with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 11 of the player's current inventory to 1 lapis lazuli with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 12 of the player's current inventory to 1 light blue dye with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 13 of the player's current inventory to 1 cyan dye with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 14 of the player's current inventory to 1 magenta dye with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 15 of the player's current inventory to 1 orange dye with lore "<white>Cost:", "%10 / {_discountFactor}%"
		set slot 18 of the player's current inventory to 1 leather helmet with lore "<white>Cost:", "%24 / {_discountFactor}%"
		set slot 19 of the player's current inventory to 1 leather chestplate with lore "<white>Cost:", "%40 / {_discountFactor}%"
		set slot 20 of the player's current inventory to 1 leather leggings with lore "<white>Cost:", "%34 / {_discountFactor}%"
		set slot 21 of the player's current inventory to 1 leather boots with lore "<white>Cost:", "%20 / {_discountFactor}%"
		
command /enchantershop [<number=1>]:
	trigger:
		set {_discountFactor} to ({abilities.%player%::Barter} / 50)
		if {_discountFactor} is less than 0.1:
			set {_discountFactor} to 0.1
		else if {_discountFactor} is more than 2:
			set {_discountFactor} to ({_discountFactor} ^ 0.8)
			if {_discountFactor} is less than 2:
				set {_discountFactor} to 2
		add 2 to {_discountFactor}
		if {traits.%player%::Physician} is true:
			set {_discountFactor} to {_discountFactor} * 0.8
		if arg 1 is 1:
			open chest inventory with 4 rows named "<gold>Enchanter - Tier 1" for the player
			set slot 0 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:34,lvl:1}]}" named "<gold>Unbreaking I" with lore "%250 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:0,lvl:1}]}" named "<gold>Protection I" with lore "%200 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:1,lvl:1}]}" named "<gold>Fire Protection I" with lore "%200 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:3,lvl:1}]}" named "<gold>Blast Protection I" with lore "%200 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:4,lvl:1}]}" named "<gold>Projectile Protection I" with lore "%200 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:2,lvl:1}]}" named "<gold>Feather Falling I" with lore "%100 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:5,lvl:1}]}" named "<gold>Respiration I" with lore "%100 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:6,lvl:1}]}" named "<gold>Aqua Affinity" with lore "%150 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:8,lvl:1}]}" named "<gold>Depth Strider I" with lore "%100 / {_discountFactor}%"
			set slot 9 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:7,lvl:1}]}" named "<gold>Thorns I" with lore "%250 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:16,lvl:1}]}" named "<gold>Sharpness I" with lore "%200 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:17,lvl:1}]}" named "<gold>Smite I" with lore "%200 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:18,lvl:1}]}" named "<gold>Bane of Arthropods I" with lore "%150 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:19,lvl:1}]}" named "<gold>Knockback I" with lore "%200 / {_discountFactor}%"
			set slot 14 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:20,lvl:1}]}" named "<gold>Fire Aspect I" with lore "%200 / {_discountFactor}%"
			set slot 15 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:21,lvl:1}]}" named "<gold>Looting I" with lore "%250 / {_discountFactor}%"
			set slot 16 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:48,lvl:1}]}" named "<gold>Power I" with lore "%200 / {_discountFactor}%"
			set slot 17 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:49,lvl:1}]}" named "<gold>Punch I" with lore "%200 / {_discountFactor}%"
			set slot 18 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:50,lvl:1}]}" named "<gold>Flame" with lore "%200 / {_discountFactor}%"
			set slot 19 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:51,lvl:1}]}" named "<gold>Infinity" with lore "%750 / {_discountFactor}%"
			set slot 20 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:32,lvl:1}]}" named "<gold>Efficiency I" with lore "%200 / {_discountFactor}%"
			set slot 21 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:33,lvl:1}]}" named "<gold>Silk Touch" with lore "%400 / {_discountFactor}%"
			set slot 22 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:35,lvl:1}]}" named "<gold>Fortune I" with lore "%250 / {_discountFactor}%"
			set slot 23 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:61,lvl:1}]}" named "<gold>Luck of the Sea I" with lore "%200 / {_discountFactor}%"
			set slot 24 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:62,lvl:1}]}" named "<gold>Lure I" with lore "%100 / {_discountFactor}%"
			set slot 26 of the player's current inventory to 1 green glass pane named "<bold>Tier 2 Enchantments"
			set slot 35 of the player's current inventory to 1 book named "<gold>Help:" with lore "<white>If your Enchanting ability x10 is higher than the displayed price,", "<white>You can purchase that enchantment book at no cost."
		else if arg 1 is 2:
			open chest inventory with 3 rows named "<gold>Enchanter - Tier 2" for the player
			set slot 0 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:34,lvl:2}]}" named "<gold>Unbreaking II" with lore "%500 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:0,lvl:2}]}" named "<gold>Protection II" with lore "%400 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:1,lvl:2}]}" named "<gold>Fire Protection II" with lore "%400 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:3,lvl:2}]}" named "<gold>Blast Protection II" with lore "%400 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:4,lvl:2}]}" named "<gold>Projectile Protection II" with lore "%400 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:2,lvl:2}]}" named "<gold>Feather Falling II" with lore "%200 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:5,lvl:2}]}" named "<gold>Respiration II" with lore "%200 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:8,lvl:2}]}" named "<gold>Depth Strider II" with lore "%200 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:7,lvl:2}]}" named "<gold>Thorns II" with lore "%500 / {_discountFactor}%"
			set slot 9 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:16,lvl:2}]}" named "<gold>Sharpness II" with lore "%400 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:17,lvl:2}]}" named "<gold>Smite II" with lore "%400 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:18,lvl:2}]}" named "<gold>Bane of Arthropods II" with lore "%300 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:19,lvl:2}]}" named "<gold>Knockback II" with lore "%400 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:20,lvl:2}]}" named "<gold>Fire Aspect II" with lore "%400 / {_discountFactor}%"
			set slot 14 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:21,lvl:2}]}" named "<gold>Looting II" with lore "%500 / {_discountFactor}%"
			set slot 15 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:48,lvl:2}]}" named "<gold>Power II" with lore "%400 / {_discountFactor}%"
			set slot 16 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:49,lvl:2}]}" named "<gold>Punch II" with lore "%400 / {_discountFactor}%"
			set slot 17 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:32,lvl:2}]}" named "<gold>Efficiency II" with lore "%400 / {_discountFactor}%"
			set slot 18 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:35,lvl:2}]}" named "<gold>Fortune II" with lore "%500 / {_discountFactor}%"
			set slot 19 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:61,lvl:2}]}" named "<gold>Luck of the Sea II" with lore "%400 / {_discountFactor}%"
			set slot 20 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:62,lvl:2}]}" named "<gold>Lure II" with lore "%200 / {_discountFactor}%"
			set slot 25 of the player's current inventory to 1 red glass pane named "<bold>Tier 1 Enchantments"
			set slot 26 of the player's current inventory to 1 green glass pane named "<bold>Tier 3 Enchantments"
		else if arg 1 is 3:
			open chest inventory with 3 rows named "<gold>Enchanter - Tier 3" for the player
			set slot 0 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:34,lvl:3}]}" named "<gold>Unbreaking III" with lore "%750 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:0,lvl:3}]}" named "<gold>Protection III" with lore "%600 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:1,lvl:3}]}" named "<gold>Fire Protection III" with lore "%600 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:3,lvl:3}]}" named "<gold>Blast Protection III" with lore "%600 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:4,lvl:3}]}" named "<gold>Projectile Protection III" with lore "%600 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:2,lvl:3}]}" named "<gold>Feather Falling III" with lore "%300 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:5,lvl:3}]}" named "<gold>Respiration III" with lore "%300 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:8,lvl:3}]}" named "<gold>Depth Strider III" with lore "%300 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:7,lvl:3}]}" named "<gold>Thorns III" with lore "%750 / {_discountFactor}%"
			set slot 9 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:16,lvl:3}]}" named "<gold>Sharpness III" with lore "%600 / {_discountFactor}%"
			set slot 10 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:17,lvl:3}]}" named "<gold>Smite III" with lore "%600 / {_discountFactor}%"
			set slot 11 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:18,lvl:3}]}" named "<gold>Bane of Arthropods III" with lore "%450 / {_discountFactor}%"
			set slot 12 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:21,lvl:3}]}" named "<gold>Looting III" with lore "%750 / {_discountFactor}%"
			set slot 13 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:48,lvl:3}]}" named "<gold>Power III" with lore "%600 / {_discountFactor}%"
			set slot 14 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:32,lvl:3}]}" named "<gold>Efficiency III" with lore "%600 / {_discountFactor}%"
			set slot 15 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:35,lvl:3}]}" named "<gold>Fortune III" with lore "%750 / {_discountFactor}%"
			set slot 16 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:61,lvl:3}]}" named "<gold>Luck of the Sea III" with lore "%600 / {_discountFactor}%"
			set slot 17 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:62,lvl:3}]}" named "<gold>Lure III" with lore "%300 / {_discountFactor}%"
			set slot 25 of the player's current inventory to 1 red glass pane named "<bold>Tier 2 Enchantments"
			set slot 26 of the player's current inventory to 1 green glass pane named "<bold>Tier 4 Enchantments"
		else if arg 1 is 4:
			open chest inventory with 2 rows named "<gold>Enchanter - Tier 4" for the player
			set slot 0 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:0,lvl:4}]}" named "<gold>Protection IV" with lore "%800 / {_discountFactor}%"
			set slot 1 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:1,lvl:4}]}" named "<gold>Fire Protection IV" with lore "%800 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:3,lvl:4}]}" named "<gold>Blast Protection IV" with lore "%800 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:4,lvl:4}]}" named "<gold>Projectile Protection IV" with lore "%800 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:2,lvl:4}]}" named "<gold>Feather Falling IV" with lore "%400 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:16,lvl:4}]}" named "<gold>Sharpness IV" with lore "%800 / {_discountFactor}%"
			set slot 6 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:17,lvl:4}]}" named "<gold>Smite IV" with lore "%800 / {_discountFactor}%"
			set slot 7 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:18,lvl:4}]}" named "<gold>Bane of Arthropods IV" with lore "%600 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:48,lvl:4}]}" named "<gold>Power IV" with lore "%800 / {_discountFactor}%"
			set slot 9 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:32,lvl:4}]}" named "<gold>Efficiency IV" with lore "%800 / {_discountFactor}%"
			set slot 16 of the player's current inventory to 1 red glass pane named "<bold>Tier 3 Enchantments"
			set slot 17 of the player's current inventory to 1 green glass pane named "<bold>Tier 5 Enchantments"
		else if arg 1 is 5:
			open chest inventory with 1 rows named "<gold>Enchanter - Tier 5" for the player
			set slot 1 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:16,lvl:5}]}" named "<gold>Sharpness V" with lore "%1000 / {_discountFactor}%"
			set slot 2 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:17,lvl:5}]}" named "<gold>Smite V" with lore "%1000 / {_discountFactor}%"
			set slot 3 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:18,lvl:5}]}" named "<gold>Bane of Arthropods V" with lore "%750 / {_discountFactor}%"
			set slot 4 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:48,lvl:5}]}" named "<gold>Power V" with lore "%1000 / {_discountFactor}%"
			set slot 5 of the player's current inventory to 1 enchanted book with nbt "{StoredEnchantments:[{id:32,lvl:5}]}" named "<gold>Efficiency V" with lore "%1000 / {_discountFactor}%"
			set slot 8 of the player's current inventory to 1 red glass pane named "<bold>Tier 4 Enchantments"
		
command /peddlershop:
	trigger:
		open chest inventory with 1 row named "<gold>Trader - Sell Items" for the player
		set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Exit" with lore "<white>Exit the current menu."
		set slot 1 of the player's current inventory to 1 dirt named "<white>Place item to sell in the empty slot."
		set slot 2 of the player's current inventory to 1 dirt named "<white>Place item to sell in the empty slot."
		set slot 3 of the player's current inventory to 1 dirt named "<white>Place item to sell in the empty slot."
		#Item to sell goes in slot 4
		set slot 5 of the player's current inventory to 1 dirt named "<white>Place item to sell in the empty slot."
		set slot 6 of the player's current inventory to 1 dirt named "<white>Place item to sell in the empty slot."
		set slot 7 of the player's current inventory to 1 dirt named "<white>Place item to sell in the empty slot."
		set slot 8 of the player's current inventory to 1 barrier named "<light red>Appraise Item" with lore "<white>Place the item you wish to sell in the empty slot,", "<white>then click this button to see what it sells for."
		
command /curateshop:
	trigger:
		set {_discountFactor} to ({abilities.%player%::Barter} / 40)
		if {_discountFactor} is less than 0.7:
			set {_discountFactor} to 0.7
		else if {_discountFactor} is more than 2:
			set {_discountFactor} to ({_discountFactor} ^ 0.8)
			if {_discountFactor} is less than 2:
				set {_discountFactor} to 2
		if {traits.%player%::Physician} is true:
			set {_discountFactor} to {_discountFactor} * 0.8
		open chest inventory with 4 rows named "<gold>Curate" for the player
		set slot 0 of the player's current inventory to 1 green dye named "<light green><bold>Sacred Herb" with lore "<white>Cost:", "%100 / {_discountFactor}%", "<white>A medicinal herb used to heal wounds.","<white>Right-click to restore 6 hearts.","<white>Can also be picked up off the ground to restore 3 hearts if wounded."
		set slot 1 of the player's current inventory to 1 green dye named "<green><bold>Baked Herb" with lore "<white>Cost:", "%125 / {_discountFactor}%", "<white>Restores 3 HP and 3 Hunger when eaten."
		set slot 2 of the player's current inventory to 1 yellow dye named "<light yellow><bold>Golden Herb" with lore "<white>Cost:", "%200 / {_discountFactor}%", "<white>Restores 12 HP when used from your inventory."
		set slot 3 of the player's current inventory to 1 yellow dye named "<yellow><bold>Baked Golden Herb" with lore "<white>Cost:", "%240 / {_discountFactor}%", "<white>Restores 6 HP and 6 Hunger when used from your inventory."
		set slot 4 of the player's current inventory to 1 red dye named "<red><bold>Red Herb" with lore "<white>Cost:", "%600 / {_discountFactor}%", "<white>Instantly revives you when you enter bleedout. Consumed automatically."
		set slot 5 of the player's current inventory to 1 splash potion of healing named "<gold>Holy Water" with lore "<white>Cost:", "%900 / {_discountFactor}%", "<white>Powerful reagent that heavily damages nearby monsters."
		set slot 6 of the player's current inventory to 1 splash potion of healing named "<gold>Sparkling Water" with lore "<white>Cost:", "%350 / {_discountFactor}%", "<white>Highly effective healing brew that benefits yourself all allies nearby."
		set slot 7 of the player's current inventory to 1 golden carrot named "<gold>War Horn" with lore "<white>Cost:", "%180 / {_discountFactor}%", "<white>Grants yourself and nearby allies Strength/Swiftness 4 and +10%% special activation chance."
		set slot 8 of the player's current inventory to 1 golden sword named "<gold>Special Blade" with lore "<white>Cost:", "%120 / {_discountFactor}%", "<white>Grants 100%% Special activation chance for your next 3 combats."
		set slot 9 of the player's current inventory to 1 potion of healing named "<gold>Elixir of Life" with lore "<white>Cost:", "%350 / {_discountFactor}%", "<white>Fully restores health when consumed."
		set slot 10 of the player's current inventory to 1 splash potion of slowness named "<gold>Bottled Blizzard" with lore "<white>Cost:", "%175 / {_discountFactor}%", "<white>Freezes nearby foes, preventing them from moving or attacking."
		set slot 11 of the player's current inventory to 1 nether star named "<gold>Untouchable" with lore "<white>Cost:", "%1200 / {_discountFactor}%", "<white>Grants temporary invulnerability when consumed."
		set slot 12 of the player's current inventory to 1 sugar named "<gold>Ability Powder" with lore "<white>Cost:", "%1000 / {_discountFactor}%", "<white>Grants +9 Ability Points when consumed."
		set slot 13 of the player's current inventory to 1 sugar named "<gold>Holy Robe" with lore "<white>Cost:", "%1500 / {_discountFactor}%", "<white>Increases your HP by +5 when consumed."
		set slot 14 of the player's current inventory to 1 sugar named "<gold>Energy Drop" with lore "<white>Cost:", "%1500 / {_discountFactor}%", "<white>Increases your STR by +5 when consumed."
		set slot 15 of the player's current inventory to 1 sugar named "<gold>Spirit Dust" with lore "<white>Cost:", "%1500 / {_discountFactor}%", "<white>Increases your MAG by +5 when consumed."
		set slot 16 of the player's current inventory to 1 sugar named "<gold>Speedwing" with lore "<white>Cost:", "%1500 / {_discountFactor}%", "<white>Increases your SPD by +5 when consumed."
		set slot 17 of the player's current inventory to 1 sugar named "<gold>Focus Drop" with lore "<white>Cost:", "%1500 / {_discountFactor}%", "<white>Increases your LCK by +5 when consumed."
		set slot 18 of the player's current inventory to 1 sugar named "<gold>Charm Bracelet" with lore "<white>Cost:", "%1500 / {_discountFactor}%", "<white>Increases your CHR by +5 when consumed."
		set slot 19 of the player's current inventory to 1 sugar named "<gold>Dragonshield" with lore "<white>Cost:", "%1500 / {_discountFactor}%", "<white>Increases your DEF by +5 when consumed."
		set slot 20 of the player's current inventory to 1 sugar named "<gold>Seraph Robe" with lore "<white>Cost:", "%1500 / {_discountFactor}%", "<white>Increases your RES by +5 when consumed."
		#
		set slot 21 of the player's current inventory to 1 sugar named "<gold>Quintessence" with lore "<white>Cost:", "%3000 / {_discountFactor}%", "<white>Increases your HP cap by +5 when consumed."
		set slot 22 of the player's current inventory to 1 sugar named "<gold>Power Charm" with lore "<white>Cost:", "%3000 / {_discountFactor}%", "<white>Increases your STR cap by +5 when consumed."
		set slot 23 of the player's current inventory to 1 sugar named "<gold>Ancient Tome" with lore "<white>Cost:", "%3000 / {_discountFactor}%", "<white>Increases your MAG cap by +5 when consumed."
		set slot 24 of the player's current inventory to 1 sugar named "<gold>Gust Charm" with lore "<white>Cost:", "%3000 / {_discountFactor}%", "<white>Increases your SPD cap by +5 when consumed."
		set slot 25 of the player's current inventory to 1 sugar named "<gold>Charmed Dice" with lore "<white>Cost:", "%3000 / {_discountFactor}%", "<white>Increases your LCK cap by +5 when consumed."
		set slot 26 of the player's current inventory to 1 sugar named "<gold>Bard's Tounge" with lore "<white>Cost:", "%3000 / {_discountFactor}%", "<white>Increases your CHR cap by +5 when consumed."
		set slot 27 of the player's current inventory to 1 sugar named "<gold>Sacred Cowl" with lore "<white>Cost:", "%3000 / {_discountFactor}%", "<white>Increases your DEF cap by +5 when consumed."
		set slot 28 of the player's current inventory to 1 sugar named "<gold>Ice Mirror" with lore "<white>Cost:", "%3000 / {_discountFactor}%", "<white>Increases your RES cap by +5 when consumed."
	
command /curateheal:
	trigger:
		set {_cost} to (player's maximum health - player's health) * 2
		if {_cost} is less than or equal to player's money:
			heal the player by player's maximum health
			apply absorption 10 to the player for 1 day
			subtract {_cost} from player's money
			set {_sklchk} to checkSlots(player,"Expert Negotiator")
			if {_sklchk} is 1:
				add ({_cost} * 0.1) to the player's balance

command /jewelershop:
	trigger:
		set {_discountFactor} to ({abilities.%player%::Barter} / 80)
		if {_discountFactor} is less than 0.5:
			set {_discountFactor} to 0.5
		else if {_discountFactor} is more than 2:
			set {_discountFactor} to ({_discountFactor} ^ 0.8)
			if {_discountFactor} is less than 2:
				set {_discountFactor} to 2
		if {traits.%player%::Physician} is true:
			set {_discountFactor} to {_discountFactor} * 0.8
		open chest inventory with 2 rows named "<gold>Jeweler" for the player
		set slot 0 of the player's current inventory to 1 music disc far named "<light green><bold>Life Ring" with lore "<white>Cost:", "%1200 / {_discountFactor}%", "<white>While in your inventory:", "<light green>Recover 10%% of your max HP every 15 seconds."
		set slot 1 of the player's current inventory to 1 music disc wait named "<light blue><bold>Elite Ring" with lore "<white>Cost:", "%1200 / {_discountFactor}%", "<white>While in your inventory:", "<light blue>Gain bonus experience for slaying monsters."
		set slot 2 of the player's current inventory to 1 music disc 13 named "<yellow><bold>Thief Ring" with lore "<white>Cost:", "%1200 / {_discountFactor}%", "<white>While in your inventory:", "<yellow>Slain monsters have a chance to drop extra money."
		set slot 3 of the player's current inventory to 1 music disc mall named "<light purple><bold>Return Ring" with lore "<white>Cost:", "%1200 / {_discountFactor}%", "<white>While in your inventory:", "<light purple>Teleport to a custom location.", "<light purple>Hold Sneak and Right-click to set the warp destination.", "<light purple>Right-click without sneaking to warp."
		set slot 4 of the player's current inventory to 1 music disc wait named "<light cyan><bold>Speed Ring" with lore "<white>Cost:", "%1200 / {_discountFactor}%", "<white>While in your inventory:", "<light cyan>Grants Swiftness 2."
		set slot 5 of the player's current inventory to 1 music disc chirp named "<light red><bold>Power Ring" with lore "<white>Cost:", "%1200 / {_discountFactor}%", "<white>While in your inventory:", "<light red>Grants Strength 2."
		set slot 6 of the player's current inventory to 1 music disc strad named "<white><bold>Shield Ring" with lore "<white>Cost:", "%1200 / {_discountFactor}%", "<white>While in your inventory:", "<white>Grants Resistance 2."
		set slot 7 of the player's current inventory to 1 music disc 13 named "<orange><bold>Prayer Ring" with lore "<white>Cost:", "%1200 / {_discountFactor}%", "<white>While in your inventory:", "<orange>Attacks while below 50%% health will always be critical hits."
		set slot 8 of the player's current inventory to 1 music disc cat named "<green><bold>Pursuit Ring" with lore "<white>Cost:", "%1200 / {_discountFactor}%", "<white>While in your inventory:", "<green>Boosts damage by 40%% if initiating combat with HP >= 70%%."
		set slot 9 of the player's current inventory to 1 music disc far named "<light green><bold>Recover Ring" with lore "<white>Cost:", "%1200 / {_discountFactor}%", "<white>While in your inventory:", "<light green>Recover 50%% of your max HP every 15 seconds."
		set slot 10 of the player's current inventory to 1 nether star named "<gold><bold>Crest of Valor" with lore "<white>Cost:", "%8000 / {_discountFactor}%", "<white>While in your inventory:", "<light green>Grants Strength 4."
		set slot 11 of the player's current inventory to 1 music disc far named "<gold><bold>Crest of Resilience" with lore "<white>Cost:", "%8000 / {_discountFactor}%", "<white>While in your inventory:", "<light green>Grants Resistance 4."
		
on inventory click:
	#Peddler
	if the name of the player's current inventory is "<gold>Trader - Sell Items":
		if the name of the clicked item is "<white>Place item to sell in the empty slot.":
			cancel event
		else if the name of the clicked item is "<bold>Exit":
			close the player's inventory
		else if the name of the clicked item is "<light red>Appraise Item":
			cancel event
		else if the name of the clicked item is "<light green>Sell Item":
			if slot 4 of the player's current inventory is not air:
				cancel event
				set {_discountFactor} to ({abilities.%player%::Barter} / 50)
				if {_discountFactor} is less than 0.1:
					set {_discountFactor} to 0.1
				else if {_discountFactor} is more than 2:
					set {_discountFactor} to ({_discountFactor} ^ 0.8)
					if {_discountFactor} is less than 2:
						set {_discountFactor} to 2
				#Sell prices
				if slot 4 of the player's current inventory is sugar:
					set {_sellPrice} to 0.33 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is gunpowder:
					set {_sellPrice} to 0.33 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is glowstone dust:
					set {_sellPrice} to 0.33 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is paper:
					set {_sellPrice} to 0.33 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is cobblestone:
					set {_sellPrice} to 0.1 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is dirt:
					set {_sellPrice} to 0.05 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is iron ingot:
					set {_sellPrice} to 5 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is gold ingot:
					set {_sellPrice} to 11.5 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is emerald:
					set {_sellPrice} to 24 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is diamond:
					set {_sellPrice} to 30 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is redstone dust:
					set {_sellPrice} to 0.5 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is lapis item:
					set {_sellPrice} to 0.5 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is rotten flesh:
					set {_sellPrice} to 0.1 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is bone:
					set {_sellPrice} to 0.1 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if slot 4 of the player's current inventory is copper ingot:
					set {_sellPrice} to 0.5 * (number of slot 4 of the player's current inventory in the player's current inventory)
				else if max durability of slot 4 of the player's current inventory is not 0:
					set {_sellPrice} to (max durability of slot 4 of the player's current inventory / 5) * ((max durability of slot 4 of the player's current inventory - durability of slot 4 of the player's current inventory) / max durability of slot 4 of the player's current inventory)
				else:
					set {_sellPrice} to 0.05 * (number of slot 4 of the player's current inventory in the player's current inventory)
				#Apply Barter bonus
				set {_sellPrice} to {_sellPrice} * {_discountFactor}
				set slot 4 of the player's current inventory to air
				add {_sellPrice} to the player's money
				send formatted "<light green>Sold for %{_sellPrice}%G. Total gold: %player's money%" to the player
		if slot 4 of the player's current inventory is not air:
			set {_discountFactor} to ({abilities.%player%::Barter} / 50)
			if {_discountFactor} is less than 0.1:
				set {_discountFactor} to 0.1
			else if {_discountFactor} is more than 2:
				set {_discountFactor} to ({_discountFactor} ^ 0.8)
				if {_discountFactor} is less than 2:
					set {_discountFactor} to 2
			#Sell prices
			if slot 4 of the player's current inventory is sugar:
				set {_sellPrice} to 0.33 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is gunpowder:
				set {_sellPrice} to 0.33 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is glowstone dust:
				set {_sellPrice} to 0.33 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is paper:
				set {_sellPrice} to 0.33 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is cobblestone:
				set {_sellPrice} to 0.1 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is dirt:
				set {_sellPrice} to 0.05 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is iron ingot:
				set {_sellPrice} to 5 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is gold ingot:
				set {_sellPrice} to 11.5 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is emerald:
				set {_sellPrice} to 24 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is diamond:
				set {_sellPrice} to 30 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is redstone dust:
				set {_sellPrice} to 0.5 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is lapis item:
				set {_sellPrice} to 0.5 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is rotten flesh:
				set {_sellPrice} to 0.1 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is bone:
				set {_sellPrice} to 0.1 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if slot 4 of the player's current inventory is any log:
				set {_sellPrice} to 0.5 * (number of slot 4 of the player's current inventory in the player's current inventory)
			else if max durability of slot 4 of the player's current inventory is not 0:
				set {_sellPrice} to (max durability of slot 4 of the player's current inventory / 5) * ((max durability of slot 4 of the player's current inventory - durability of slot 4 of the player's current inventory) / max durability of slot 4 of the player's current inventory)
			else:
				set {_sellPrice} to 0.05 * (number of slot 4 of the player's current inventory in the player's current inventory)
			#Apply Barter bonus
			set {_sellPrice} to {_sellPrice} * {_discountFactor}
			set slot 8 of the player's current inventory to 1 green glass pane named "<light green>Sell Item" with lore "<white>Sell this item for: %{_sellPrice}%"	
		else if slot 4 of the player's current inventory is air:
			set slot 8 of the player's current inventory to 1 barrier named "<light red>Appraise Item" with lore "<white>Place the item you wish to sell in the empty slot,", "<white>then click this button to see what it sells for."
	#Jerome Repair
	if the name of the player's current inventory is "<gold>Repair Tools":
		if the name of the clicked item is "<green><bold>Repair Tool":
			set {_cashreq} to (the damage value of slot 4 of the player's current inventory / {_discountFactor})
			if {_cashreq} is less than or equal to the player's money:
				repair slot 4 of the player's current inventory
				set the player's money to (player's money - {_cashreq})
				set {_sklchk} to checkSlots(player,"Expert Negotiator")
				if {_sklchk} is 1:
					add ({_cashreq} * 0.1) to the player's balance
				send formatted "<light green>Transaction complete. New balance: $%player's money%."
				cancel event
			else:
				send formatted "<light red>Not enough money!"
			cancel event
		else if the name of the clicked item is "<bold>Exit":
			cancel event
			teleport the player to the player
	#Blacksmiths
	if the name of the player's current inventory is "<gold>Blacksmith":
		cancel event
		if the name of the clicked item contains "Go to Page 1":
			make player execute command "/bs-shop 1"
		else if the name of the clicked item contains "Go to Page 2":
			make player execute command "/bs-shop 2"
		else if the name of the clicked item contains "Go to Page 3":
			make player execute command "/bs-shop 3"
		else if the name of the clicked item contains "Go to Page 4":
			make player execute command "/bs-shop 4"
		else if the name of the clicked item contains "Go to Page 5":
			make player execute command "/bs-shop 5"
		else if the name of the clicked item contains "Go to Page 6":
			make player execute command "/bs-shop 6"
		else if the name of the clicked item contains "Upgrade Equipment":
			make player execute command "/buyToolSkills 0 1"
		else:
			set {_cost} to the 2nd line of the lore of the clicked item parsed as number
			if {_cost} is less than or equal to player's money:
				if {_cost} is set:
					set {_item} to the clicked item
					clear the lore of {_item}
					give {_item} to the player
					subtract {_cost} from player's money
					set {_sklchk} to checkSlots(player,"Expert Negotiator")
					if {_sklchk} is 1:
						add ({_cost} * 0.1) to the player's balance
					send formatted "<light green>Purchased that item for %{_cost}% gold. New balance: %player's money%"
	#Weapon Smiths
	if the name of the player's current inventory contains "<gold>Weapon Smith":
		cancel event
		if the name of the clicked item contains "Basic Weapons":
			make player execute command "/weaponshop 1"
		else if the name of the clicked item contains "Slaying Weapons":
			make player execute command "/weaponshop 2"
		else if the name of the clicked item contains "Reinforced Weapons":
			make player execute command "/weaponshop 3"
		else if the name of the clicked item contains "Warding Weapons":
			make player execute command "/weaponshop 4"
		else if the name of the clicked item contains "Crushing Weapons":
			make player execute command "/weaponshop 5"
		else if the name of the clicked item contains "Piercing Weapons":
			make player execute command "/weaponshop 6"
		else if the name of the clicked item contains "Koenig Weapons":
			make player execute command "/weaponshop 7"
		else if the name of the clicked item contains "Netherite Weapon Frames":
			make player execute command "/weaponshop 9"
		else if the name of the clicked item contains "Weapon Frames":
			make player execute command "/weaponshop 8"
		else if the name of the clicked item contains "Go Back":
			make player execute command "/weaponshop 0"
		else:
			set {_cost} to the 2nd line of the lore of the clicked item parsed as number
			if {_cost} is less than or equal to player's money:
				if {_cost} is set:
					set {_item} to the clicked item
					clear the lore of {_item}
					give {_item} to the player
					subtract {_cost} from player's money
					set {_sklchk} to checkSlots(player,"Expert Negotiator")
					if {_sklchk} is 1:
						add ({_cost} * 0.1) to the player's balance
					send formatted "<light green>Purchased that item for %{_cost}% gold. New balance: %player's money%"
	#Enchanters
	else if the name of the player's current inventory contains "<gold>Enchanter":
		cancel event
		set {_cost} to the 1st line of the lore of the clicked item parsed as number
		if the name of the clicked item is "<bold>Tier 1 Enchantments":
			make player execute command "/enchantershop 1"
		else if the name of the clicked item is "<bold>Tier 2 Enchantments":
			make player execute command "/enchantershop 2"
		else if the name of the clicked item is "<bold>Tier 3 Enchantments":
			make player execute command "/enchantershop 3"
		else if the name of the clicked item is "<bold>Tier 4 Enchantments":
			make player execute command "/enchantershop 4"
		else if the name of the clicked item is "<bold>Tier 5 Enchantments":
			make player execute command "/enchantershop 5"
		if {_cost} is less than or equal to ({abilities.%player%::Enchanting} * 10):
			set {_item} to the clicked item
			clear the lore of {_item}
			give {_item} to the player
			send formatted "<light green>Purchased enchantment book for free due to your Enchanting ability."			
		else if {_cost} is less than or equal to player's money:
			if {_cost} is set:
				set {_item} to the clicked item
				clear the lore of {_item}
				give {_item} to the player
				subtract {_cost} from player's money
				set {_sklchk} to checkSlots(player,"Expert Negotiator")
				if {_sklchk} is 1:
					add ({_cost} * 0.1) to the player's balance
				send formatted "<light green>Purchased that item for %{_cost}% gold. New balance: %player's money%"
	#Traders
	else if the name of the player's current inventory is "<gold>Trader":
		cancel event
		set {_cost} to the 2nd line of the lore of the clicked item parsed as number
		if {_cost} is less than or equal to player's money:
			if {_cost} is set:
				set {_item} to the clicked item
				clear the lore of {_item}
				give {_item} to the player
				subtract {_cost} from player's money
				set {_sklchk} to checkSlots(player,"Expert Negotiator")
				if {_sklchk} is 1:
					add ({_cost} * 0.1) to the player's balance
				send formatted "<light green>Purchased that item for %{_cost}% gold. New balance: %player's money%"
	#Curates
	else if the name of the player's current inventory is "<gold>Curate":
		cancel event
		set {_cost} to the 2nd line of the lore of the clicked item parsed as number
		if {_cost} is less than or equal to player's money:
			if {_cost} is set:
				set {_item} to the clicked item
				clear the lore of {_item}
				give {_item} to the player
				subtract {_cost} from player's money
				set {_sklchk} to checkSlots(player,"Expert Negotiator")
				if {_sklchk} is 1:
					add ({_cost} * 0.1) to the player's balance
				send formatted "<light green>Purchased that item for %{_cost}% gold. New balance: %player's money%"
	#Jeweler
	else if the name of the player's current inventory is "<gold>Jeweler":
		cancel event
		set {_cost} to the 2nd line of the lore of the clicked item parsed as number
		if {_cost} is less than or equal to player's money:
			if {_cost} is set:
				set {_item} to the clicked item
				clear the lore of {_item}
				give {_item} to the player
				subtract {_cost} from player's money
				set {_sklchk} to checkSlots(player,"Expert Negotiator")
				if {_sklchk} is 1:
					add ({_cost} * 0.1) to the player's balance
				send formatted "<light green>Purchased that item for %{_cost}% gold. New balance: %player's money%"
	#Serosita Barkeep
	else if the name of the player's current inventory is "<gold>Serosita Barkeep":
		cancel event
		set {_cost} to the 2nd line of the lore of the clicked item parsed as number
		if {_cost} is less than or equal to player's money:
			if {_cost} is set:
				set {_item} to the clicked item
				clear line 1 of the lore of {_item}
				clear line 2 of the lore of {_item}
				give {_item} to the player
				subtract {_cost} from player's money
				set {_sklchk} to checkSlots(player,"Expert Negotiator")
				if {_sklchk} is 1:
					add ({_cost} * 0.1) to the player's balance
				send formatted "<light green>Purchased that item for %{_cost}% gold. New balance: %player's money%"
	#Tailor
	else if the name of the player's current inventory is "<gold>Tailor":
		cancel event
		set {_cost} to the 2nd line of the lore of the clicked item parsed as number
		if {_cost} is less than or equal to player's money:
			if {_cost} is set:
				set {_item} to the clicked item
				clear line 1 of the lore of {_item}
				clear line 2 of the lore of {_item}
				give {_item} to the player
				subtract {_cost} from player's money
				set {_sklchk} to checkSlots(player,"Expert Negotiator")
				if {_sklchk} is 1:
					add ({_cost} * 0.1) to the player's balance
				send formatted "<light green>Purchased that item for %{_cost}% gold. New balance: %player's money%"
	#Butcher
	else if the name of the player's current inventory is "<gold>Butcher":
		cancel event
		set {_cost} to the 2nd line of the lore of the clicked item parsed as number
		if {_cost} is less than or equal to player's money:
			if {_cost} is set:
				set {_item} to the clicked item
				clear line 1 of the lore of {_item}
				clear line 2 of the lore of {_item}
				give {_item} to the player
				subtract {_cost} from player's money
				set {_sklchk} to checkSlots(player,"Expert Negotiator")
				if {_sklchk} is 1:
					add ({_cost} * 0.1) to the player's balance
				send formatted "<light green>Purchased that item for %{_cost}% gold. New balance: %player's money%"
	#Farmer
	else if the name of the player's current inventory is "<gold>Farmer's Market":
		cancel event
		set {_cost} to the 2nd line of the lore of the clicked item parsed as number
		if {_cost} is less than or equal to player's money:
			if {_cost} is set:
				set {_item} to the clicked item
				clear line 1 of the lore of {_item}
				clear line 2 of the lore of {_item}
				give {_item} to the player
				subtract {_cost} from player's money
				set {_sklchk} to checkSlots(player,"Expert Negotiator")
				if {_sklchk} is 1:
					add ({_cost} * 0.1) to the player's balance
				send formatted "<light green>Purchased that item for %{_cost}% gold. New balance: %player's money%"
	#Innkeepers
	else if the name of the player's current inventory is "<gold>Innkeeper":
		cancel event
		set {_cost} to the 2nd line of the lore of the clicked item parsed as number
		if {_cost} is less than or equal to player's money:
			if {_cost} is set:
				if the name of the clicked item is not "<light blue><bold>Rest":
					set {_item} to the clicked item
					clear line 1 of the lore of {_item}
					clear line 2 of the lore of {_item}
					give {_item} to the player
					subtract {_cost} from player's money
					set {_sklchk} to checkSlots(player,"Expert Negotiator")
					if {_sklchk} is 1:
						add ({_cost} * 0.1) to the player's balance
					send formatted "<light green>Purchased that item for %{_cost}% gold. New balance: %player's money%"
				else:
					subtract {_cost} from player's money
					set {_sklchk} to checkSlots(player,"Expert Negotiator")
					if {_sklchk} is 1:
						add ({_cost} * 0.1) to the player's balance
					heal the player by 999 hearts
					increase the player's food level by 10
					send formatted "<light green>Rested at the inn for %{_cost}% gold. New balance: %player's money%"
	#Todd's Shop
	else if the name of the player's current inventory is "<gold>Todd's General Goods":
		cancel event
		set {_cost} to the 2nd line of the lore of the clicked item parsed as number
		if {_cost} is less than or equal to player's money:
			if {_cost} is set:
				set {_item} to the clicked item
				clear line 1 of the lore of {_item}
				clear line 2 of the lore of {_item}
				give {_item} to the player
				subtract {_cost} from player's money
				set {_sklchk} to checkSlots(player,"Expert Negotiator")
				if {_sklchk} is 1:
					add ({_cost} * 0.1) to the player's balance
				send formatted "<light green>Purchased that item for %{_cost}% gold. New balance: %player's money%"
	#Player Finder
	else if the name of the player's current inventory is "<blue>Online Players":
		cancel event
		if the clicked item is iron block:
			if the clicked item's name is set:
				set {_playerName} to the name of the clicked item
				set {_playerName} to decolorize({_playerName})
				set {_playerName} to {_playerName} parsed as player
				make player execute command "/friends add %{_playerName}%"
	#Radiant Quests
	else if the name of the player's current inventory is "<gold>Available Quests":
		if the 4th line of the lore of the clicked item contains "Click to accept this quest":
			send "<light yellow>Quest accepted!" to the player
			play sound "ui.button.click" with volume 1 and pitch 1
			set {radiantQuest.%player%.%index of the event-slot + 1%::Completion} to 1
			make player execute command "/questmaster quests oldview"
		else if the 5th line of the lore of the clicked item contains "<light red>Click to drop this quest.":
			send "<light red>Quest dropped!" to the player
			play sound "ui.button.click" with volume 1 and pitch 1
			clear {radiantQuest.%player%.%index of the event-slot + 1%::Completion}
			make player execute command "/questmaster quests oldview"
		else if the 5th line of the lore of the clicked item contains "<light green>Click to turn in this quest":
			send "<light green>Quest complete!" to the player
			play sound "ui.button.click" with volume 1 and pitch 1
			if {radiantQuest.%player%.%index of the event-slot +1%::Type} is 0:
				remove "%{radiantQuest.%player%.%index of the event-slot +1%::Amount}% %{radiantQuest.%player%.%index of the event-slot +1%::Target}%" parsed as item type from the player
				send formatted "<light yellow>%{radiantQuest.%player%.%index of the event-slot +1%::Amount}% %{radiantQuest.%player%.%index of the event-slot +1%::Target}% lost."
			set {radiantQuest.%player%.%index of the event-slot + 1%::Completion} to 999
			add {radiantQuest.%player%.%index of the event-slot +1%::GoldReward} to the player's balance
			send "<gold>+%{radiantQuest.%player%.%index of the event-slot +1%::GoldReward}% Gold earned!"
			send "<gold>+%{radiantQuest.%player%.%index of the event-slot +1%::EXPReward}% EXP earned!"
			make server execute command "/xp give %player% %{radiantQuest.%player%.%index of the event-slot +1%::EXPReward}%"
			#set {_xp} to floor({radiantQuest.%player%.%index of the event-slot +1%::EXPReward} / 2)
			addClassXP(player,{radiantQuest.%player%.%index of the event-slot +1%::EXPReward})
			make player execute command "/questmaster quests oldview"
		cancel event
	#XP Bottler
	else if the name of the player's current inventory is "<gold>Experience Bottler":
		if the name of the clicked item is "<light green>Bottle 1 XP Level":
			if player's level is more than 0:
				make player execute command "/xp -1l"
				give 1 water bottle of power 1 named "<light blue>Bottled Experience" with lore "<white>A bottle of raw magical energy.", "<white>Consume it with right-click.", "<white>Grants 1 XP level when consumed." to the player
				play sound "ui.button.click" with volume 1 and pitch 1
		else if the name of the clicked item is "<orange>Bottle 5 XP Levels":
			if player's level is more than 4:
				make player execute command "/xp -5l"
				give 1 water bottle of power 5 named "<light blue>Large Bottle of Experience" with lore "<white>A hefty bottle of magical energy.", "<white>Consume it with right-click.", "<white>Grants 5 XP levels when consumed." to the player
				play sound "ui.button.click" with volume 1 and pitch 1
		else if the name of the clicked item is "<yellow>Bottle 10 XP Levels":
			if player's level is more than 9:
				make player execute command "/xp -10l"
				give 1 water bottle of power 10 named "<light blue>Massive Bottle of Experience" with lore "<white>An incredibly weighty bottle of magical energy.", "<white>Consume it with right-click.", "<white>Grants 10 XP levels when consumed." to the player
				play sound "ui.button.click" with volume 1 and pitch 1
		else if the name of the clicked item is "<light green>Convert 15 XP Levels to 1 Class Level":
			if player's level is more than 15:
				make player execute command "/xp -15l"
				give 1 water bottle of power 1 named "<light blue>Packaged Class XP" with lore "<white>An enchanted bottle filled with knowledge.", "<white>Consume it with right-click.", "<white>Raises your Class Level by 1 when consumed." to the player
				play sound "ui.button.click" with volume 1 and pitch 1
		else if the name of the clicked item is "<orange>Convert 30 XP Levels to 2 Class Levels":
			if player's level is more than 29:
				make player execute command "/xp -30l"
				give 1 water bottle of power 2 named "<light blue>Large Package of Class XP" with lore "<white>A weighty bottle filled with knowledge.", "<white>Consume it with right-click.", "<white>Raises your Class Level by 2 when consumed." to the player
				play sound "ui.button.click" with volume 1 and pitch 1
		else if the name of the clicked item is "<yellow>Convert 60 XP Levels to 4 Class Levels":
			if player's level is more than 59:
				make player execute command "/xp -60l"
				give 1 water bottle of power 2 named "<light blue>Massive Package of Class XP" with lore "<white>A massive bottle filled to the brim with knowledge.", "<white>Consume it with right-click.", "<white>Raises your Class Level by 4 when consumed." to the player
				play sound "ui.button.click" with volume 1 and pitch 1
		cancel event
	#Sacred Treasures
	else if the name of the player's current inventory is "<gold><bold>Sacred Treasures":
		if the name of the clicked item contains "<gold><bold>":
			set {_weapon} to uncoloured name of the clicked item
			remove "<gold><bold>" from {_weapon}
			make player execute command "/hwbuy hw2 %{_weapon}%"
			cancel event
	else if the name of the player's current inventory is "<gold><bold>Sacred Treasures | Inspection":
		if the name of the clicked item is "<gold><bold>Summon Weapon":
			set {_weapon} to uncoloured name of slot 4 of the player's current inventory
			remove "<gold><bold>" from {_weapon}
			if {_weapon} is "Basilikos":
				set {_price} to 1500
			else if {_weapon} is "Mercurius":
				set {_price} to 1500
			else if {_weapon} is "Hauteclere":
				set {_price} to 1500
			else if {_weapon} is "Gradivus":
				set {_price} to 1500
			else if {_weapon} is "Super Shotgun":
				set {_price} to 1500
			else:
				set {_price} to 2000
			if the player's money is less than {_price}:
				send formatted "<red><bold>You lack the required funds to purchase this Sacred Treasure. You need %{_price}%, but only have %player's money%."
			else:
				#Things other than swords
				if {_weapon} is "Basilikos":
					set slot 4 of the player's current inventory to 1 stone axe named "<light blue><bold>Broken Axe" with lore "<white>A broken axe unfit for combat.", "<white>This is all that remains of the Basilikos."
				else if {_weapon} is "Hauteclere":
					set slot 4 of the player's current inventory to 1 stone axe named "<light blue><bold>Broken Axe" with lore "<white>A broken axe unfit for combat.", "<white>This is all that remains of the Hauteclere."
				else if {_weapon} is "Gradivus":
					set slot 4 of the player's current inventory to 1 stone shovel named "<light blue><bold>Broken Lance" with lore "<white>A broken lance unfit for combat.", "<white>This is all that remains of the Gradivus."
				else if {_weapon} is "Super Shotgun":
					set slot 4 of the player's current inventory to 1 iron horse armour named "<red><bold>Super Shotgun | Clip: 2/2" with lore "<red>Left-Click to reload. Costs 6 gold nuggets per barrel. ", " <red>Right-Click to fire. Shots are less accurate at range."
				else if {_weapon} is "Fensalir":
					set slot 4 of the player's current inventory to 1 stone shovel named "<light blue><bold>Broken Lance" with lore "<white>A broken lance unfit for combat.", "<white>This is all that remains of the Fensalir."
				else if {_weapon} is "Parthia":
					set slot 4 of the player's current inventory to 1 bow named "<light blue><bold>Broken Bow" with lore "<white>A broken bow unfit for combat.", "<white>This is all that remains of Parthia."
				else if {_weapon} is "Siegmund":
					set slot 4 of the player's current inventory to 1 stone shovel named "<light blue><bold>Broken Lance" with lore "<white>A broken lance unfit for combat.", "<white>This is all that remains of Siegmund."
				else if {_weapon} is "Scarborough Fair":
					set slot 4 of the player's current inventory to 1 gold horse armor named "<light red><bold>Scarborough Fair"
				else if {_weapon} is "Love is Blue":
					set slot 4 of the player's current inventory to 1 diamond horse armor named "<light blue><bold>Love is Blue"
				else if {_weapon} is "Axtinguisher":
					set slot 4 of the player's current inventory to 1 stone axe named "<light blue><bold>Broken Axe" with lore "<white>A broken axe unfit for combat.", "<white>This is all that remains of the Axtinguisher."
				else if {_weapon} is "Armads":
					set slot 4 of the player's current inventory to 1 stone axe named "<light blue><bold>Broken Axe" with lore "<white>A broken axe unfit for combat.", "<white>This is all that remains of Armads."
				else if {_weapon} is "Gae Bolg":
					set slot 4 of the player's current inventory to 1 stone shovel named "<light blue><bold>Broken Lance" with lore "<white>A broken lance unfit for combat.", "<white>This is all that remains of the Gae Bolg."
				else if {_weapon} is "Fujin Yumi":
					set slot 4 of the player's current inventory to 1 bow named "<light blue><bold>Broken Bow" with lore "<white>A broken bow unfit for combat.", "<white>This is all that remains of the Fujin Yumi."
				else if {_weapon} is "Crusader's Lance":
					set slot 4 of the player's current inventory to 1 stone shovel named "<light blue><bold>Broken Lance" with lore "<white>A broken lance unfit for combat.", "<white>This is all that remains of the Crusader's Lance."
				else if {_weapon} is "Devil Axe":
					set slot 4 of the player's current inventory to 1 stone axe named "<light blue><bold>Broken Axe" with lore "<white>A broken axe unfit for combat.", "<white>This is all that remains of the Devil Axe."
				else if {_weapon} is "Dire Thunder":
					set slot 4 of the player's current inventory to 1 book named "<light blue><bold>Broken Tome" with lore "<white>An old tome sapped of magic.", "<white>The spell Dire Thunder used to be present."
				else if {_weapon} is "Rhomphaia":
					set slot 4 of the player's current inventory to 1 stone shovel named "<light blue><bold>Broken Lance" with lore "<white>A broken lance unfit for combat.", "<white>This is all that remains of the Rhomphaia."
				else if {_weapon} is "Rex Hasta":
					set slot 4 of the player's current inventory to 1 stone shovel named "<light blue><bold>Broken Lance" with lore "<white>A broken lance unfit for combat.", "<white>This is all that remains of the Rex Hasta."
				else if {_weapon} is "Lunar Bow":
					set slot 4 of the player's current inventory to 1 bow named "<light blue><bold>Broken Bow" with lore "<white>A broken bow unfit for combat.", "<white>This is all that remains of the Lunar Bow."
				else if {_weapon} is "Guard Bow":
					set slot 4 of the player's current inventory to 1 bow named "<light blue><bold>Broken Bow" with lore "<white>A broken bow unfit for combat.", "<white>This is all that remains of the Guard Bow."
				else if {_weapon} is "Brave Bow":
					set slot 4 of the player's current inventory to 1 bow named "<light blue><bold>Broken Bow" with lore "<white>A broken bow unfit for combat.", "<white>This is all that remains of the Brave Bow."
				else if {_weapon} is "Tomahawk":
					set slot 4 of the player's current inventory to 1 stone axe named "<light blue><bold>Broken Axe" with lore "<white>A rusted axe unfit for combat.", "<white>This used to be a Tomahawk in a previous life."
				else if {_weapon} is "Javelin":
					set slot 4 of the player's current inventory to 1 stone shovel named "<light blue><bold>Broken Lance" with lore "<white>A broken lance unfit for combat.", "<white>It's an old throwing Javelin, once popular among soldiers many years ago."
				else if {_weapon} is "Swift-Winds Lance":
					set slot 4 of the player's current inventory to 1 stone shovel named "<light blue><bold>Broken Lance" with lore "<white>A broken lance unfit for combat.", "<white>This is all that remains of the Swift-Winds Lance."
				else if {_weapon} is "Devil Axe":
					set slot 4 of the player's current inventory to 1 stone axe named "<light blue><bold>Broken Axe" with lore "<white>A broken axe unfit for combat.", "<white>This is all that remains of the Devil Axe."
				#Swords
				else:
					set slot 4 of the player's current inventory to 1 stone sword named "<light blue><bold>Broken Sword" with lore "<white>A broken sword unfit for combat.", "<white>This is all that remains of %{_weapon}%."
				subtract {_price} from the player's money
				set {_sklchk} to checkSlots(player,"Expert Negotiator")
				if {_sklchk} is 1:
					add ({_price} * 0.1) to the player's balance
				send formatted "<green><bold>Weapon purchased! Current Funds: %player's money%."
			cancel event
		else if the name of the clicked item contains "Go Back":
			cancel event
			make player execute command "/hwbuy HW"
		else if the name of the clicked item is "<gold><bold>Warp to Heroic Challenge":
			set {_name} to the name of slot 4 of the player's current inventory
			if {_name} is "<gold><bold>Falchion":
				make player execute command "/warp qp_h2"
			else if {_name} is "<gold><bold>Binding Blade":
				make player execute command "/warp qp_h1"
			else if {_name} is "<gold><bold>Mystletainn":
				make player execute command "/warp qp_h3"
			cancel event
		else if the clicked item is cobblestone:
			cancel event
	
#Gen 2 - Jerome	
command /jeromefix:
	trigger:
		open chest inventory with 1 row named "<gold>Repair Tools" for the player
		set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Exit"
		set slot 3 of the player's current inventory to 1 book named "<bold>Place item here -->"
		set slot 5 of the player's current inventory to 1 book named "<bold><-- Place item here"
		set slot 8 of the player's current inventory to 1 green glass pane named "<green><bold>Repair Tool"
		
#NPC-less inns
on right click on a sign:
	if the 1st line of the event-block is "[Inn]":
		set {_cost} to line 2 of the event-block parsed as number
		if {_cost} is less than player's money:
			heal the player by 999 hearts
			increase the player's food level by 10
			subtract {_cost} from the player's money 
			set {_sklchk} to checkSlots(player,"Expert Negotiator")
			if {_sklchk} is 1:
				add ({_cost} * 0.1) to the player's balance
			send formatted "<light green>Rested at the inn for %{_cost}% gold. New balance: %player's money%"

#Player Finder
command /listplayers:
	trigger:
		open chest inventory with 6 rows named "<blue>Online Players" for the player
		set {_opIcons} to 0
		loop all players:
			loop {friendsList.%player%::*}:
				if loop-player is loop-value-2:
					if {party.%player%} is {party.%loop-value-2%}:
						set slot {_opIcons} of the player's current inventory to 1 gold block named "<white>%loop-value-2%" with lore "<white>Playing as: %loop-value-2's tablist name%", "<white>Location: %loop-value-2's location%", "<light green>This player is in your group.", "<white>This player is on your friends list."
					else:
						set slot {_opIcons} of the player's current inventory to 1 gold block named "<white>%loop-value-2%" with lore "<white>Playing as: %loop-value-2's tablist name%", "<white>Location: %loop-value-2's location%", "<white>This player is on your friends list."
					set {_skipIconRender} to true
					exit 1 loop
			if {_skipIconRender} is not set:
				if loop-player is not the player:
					if {party.%player%} is {party.%loop-player%}:
						set slot {_opIcons} of the player's current inventory to 1 iron block named "<white>%loop-value%" with lore "<white>Playing as: %loop-value's tablist name%", "<light green>This player is in your group.", "<white>Click to send a friend request to this player."
					else:
						set slot {_opIcons} of the player's current inventory to 1 iron block named "<white>%loop-value%" with lore "<white>Playing as: %loop-value's tablist name%", "<white>Click to send a friend request to this player."
				else:
					set slot {_opIcons} of the player's current inventory to 1 diamond block named "<white>%loop-value%" with lore "<white>Playing as: %loop-value's tablist name%", "<white>This is you!"
			else:
				clear {_skipIconRender}
			add 1 to {_opIcons}
			
#Radiant Quest Hunting Handler
on death:
	if citizen id of the attacker is not set:
		loop {radiantQuestsOnOffer.%attacker%} times:
			if "%victim%" is "%{radiantQuest.%attacker%.%loop-value%::Target}%":
				if {radiantQuest.%attacker%.%loop-value%::Completion} is not 999:
					if {radiantQuest.%attacker%.%loop-value%::Completion} is set:
						add 1 to {radiantQuest.%attacker%.%loop-value%::Completion}
						if {radiantQuest.%attacker%.%loop-value%::Completion} is equal to ({radiantQuest.%attacker%.%loop-value%::Amount} + 1):
							set {radiantQuest.%attacker%.%loop-value%::Completion} to 999
							send "<light yellow>Hunting quest completed!" to the attacker
							send "<gold>+%{radiantQuest.%attacker%.%loop-value%::GoldReward}% Gold earned!" to the attacker
							send "<gold>+%{radiantQuest.%attacker%.%loop-value%::EXPReward}% EXP earned!" to the attacker
							add {radiantQuest.%attacker%.%loop-value%::GoldReward} to the attacker's balance
							make server execute command "/xp give %attacker% %{radiantQuest.%attacker%.%loop-value%::EXPReward}%"
							play sound "entity.player.levelup" with volume 1 and pitch 0.75 at attacker for attacker
							play sound "entity.fireworkrocket.twinkle" with volume 1 and pitch 1.5 at attacker for attacker
							play 30 (firework spark with speed 1) at attacker
							play 30 (snow shovel with speed 1) at attacker
						else:
							send title "" with subtitle "Hunting quest progress: %{radiantQuest.%attacker%.%loop-value%::Completion} - 1% / %{radiantQuest.%attacker%.%loop-value%::Amount}%" to the attacker for 2.5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
							play sound "entity.player.levelup" with volume 0.25 and pitch 1.5 at attacker for attacker
							play 5 (firework spark with speed 1) at attacker
							play 5 (snow shovel with speed 1) at attacker
			else if {radiantQuest.%attacker%.%loop-value%::Target} is "of any monster":
				if {radiantQuest.%attacker%.%loop-value%::Completion} is not 999:
					if {radiantQuest.%attacker%.%loop-value%::Completion} is set:
						add 1 to {radiantQuest.%attacker%.%loop-value%::Completion}
						if {radiantQuest.%attacker%.%loop-value%::Completion} is equal to ({radiantQuest.%attacker%.%loop-value%::Amount} + 1):
							set {radiantQuest.%attacker%.%loop-value%::Completion} to 999
							send "<light yellow>Hunting quest completed!" to the attacker
							send "<gold>+%{radiantQuest.%attacker%.%loop-value%::GoldReward}% Gold earned!" to the attacker
							send "<gold>+%{radiantQuest.%attacker%.%loop-value%::EXPReward}% EXP earned!" to the attacker
							add {radiantQuest.%attacker%.%loop-value%::GoldReward} to the attacker's balance
							make server execute command "/xp give %attacker% %{radiantQuest.%attacker%.%loop-value%::EXPReward}%"
							play sound "entity.player.levelup" with volume 1 and pitch 0.75 at attacker for attacker
							play sound "entity.fireworkrocket.twinkle" with volume 1 and pitch 1.5 at attacker for attacker
							play 30 (firework spark with speed 1) at attacker
							play 30 (snow shovel with speed 1) at attacker
						else:
							send title "" with subtitle "Hunting quest progress: %{radiantQuest.%attacker%.%loop-value%::Completion} - 1% / %{radiantQuest.%attacker%.%loop-value%::Amount}%" to the attacker for 2.5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
							play sound "entity.player.levelup" with volume 0.25 and pitch 1.5 at attacker for attacker
							play 5 (firework spark with speed 1) at attacker
							play 5 (snow shovel with speed 1) at attacker		
				
			
#{radiantQuestsOnOffer} - Number of all currently generated Radiant Quests available. Set a loop with this variable as the number of repetitions to be able to loop through all generated Radiant Quests.
#{radiantQuest.x::*} - Information relating to the Radian Quest with ID (x).
#Legal list index values:
#Completion: The Radiant Quest's current progress, following the same formula as normal quests. Used when assigned to a player.
#Type: What type of Radiant Quest it is, defined above the generator.
#Amount: How much of a particular task needs to be done. (EX: A "Retrive Lapis" Radiant Quest would set this to the amount of Lapis that needs to be retrieved.)
#Recipient: Who to return this Radiant Quest to (if applicable). Used for delivery missions.
#Target: The item/foe targeted by this Radiant Quest. Set to an item for Retrieve Item Quests, and an entity type for Hunting quests. Set to "ALL" for Hunting quests to track all kills. Can be combined with "Recipient" to target a particular NPC or player.
#GoldReward: The amount of gold to be given to the player once the Radiant Quest is complete.
#ItemReward: An item to be given to the player once the Radiant Quest is complete.
#EXPReward: Amount of EXP to be given to the player once the Radiant Quest is complete.
command /questmaster <text> <text>:
	trigger:
		if arg 1 is "drop":
			send formatted "<light blue>Questmaster: Are you sure you want to drop that %arg 2% job?"
			wait 2 seconds
			send formatted "<run command:/questmaster dropConfirm %arg 2%><light red>1 - Drop the %arg 2% job (click here)."
		else if arg 1 is "dropConfirm":
			send formatted "<light blue>Questmaster: Alright, then. I'll drop that job for you."
			wait 2 seconds
			send formatted "<light blue>Questmaster: Anything else you need?"
			clear {radiantQuests.%player%::%arg 2%}
			wait 2 seconds
			send formatted "<gold>1 - What jobs are on offer?"
			if {radiantQuests.%player%::*} is set:
				set {_jobID} to 2 
				loop {radiantQuests.%player%::*}:
					send formatted "<run command:/questmaster drop %loop-index%><light red>%{_jobID}% - I want to drop my %loop-index% job."
		else if arg 1 is "quests":
			if arg 2 is "oldview":
				clear {radiantQuestsRNG.%player%}
				make player execute command "/questmaster quests view"
			if {radiantQuestsRNG.%player%} is true:
				clear {radiantQuestsRNG.%player%}
				set {radiantQuestsOnOffer.%player%} to a random integer from 3 to 18
				loop {radiantQuestsOnOffer.%player%} times:
					#Radiant Quest types:
					#0 - Retrieve Item
					#1 - Slay Monster(s)
					#2 - Sell Equipment
					#3 - Defeat Target
					#4 - Deliver Item
					#Only generate types that are actually coded.
					clear {radiantQuest.%player%.%loop-value%::Completion}
					set {radiantQuest.%player%.%loop-value%::Type} to a random integer from 0 to 1
					if {radiantQuest.%player%.%loop-value%::Type} is 0:
						#What sort of item should this quest target?
						set {_ItemType} to a random integer from 0 to 15
						#Seed item amount to retrieve, influenced by the player's level.
						set {_itemAmount} to a random integer from 3 to {lvl.%player%} * 1.5
						set {radiantQuest.%player%.%loop-value%::Amount} to {_itemAmount}
						#Sugar Cane
						if {_itemType} is 0:
							set {radiantQuest.%player%.%loop-value%::Target} to "sugar cane"
							#Replace the 1 here with the base value of that item. Sugar cane is 3G in the Trader's store, so for balancing we'll set this to 1.
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (1 * {_itemAmount}) * 4 to (1 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (0.15 * {_itemAmount}) * 4 to (0.35 * {_itemAmount} + {lvl.%player%}) * 4
						#Coal
						else if {_itemType} is 1:
							set {radiantQuest.%player%.%loop-value%::Target} to "coal"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (2.5 * {_itemAmount}) * 4 to (2.5 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (1 * {_itemAmount}) * 4 to (1 * {_itemAmount} + {lvl.%player%}) * 4
						#Iron Ingots
						else if {_itemType} is 2:
							set {radiantQuest.%player%.%loop-value%::Target} to "iron ingots"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (5 * {_itemAmount}) * 4 to (5 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (2 * {_itemAmount}) * 4 to (2 * {_itemAmount} + {lvl.%player%}) * 4
						#Gold Ingots
						else if {_itemType} is 3:
							set {radiantQuest.%player%.%loop-value%::Target} to "gold ingots"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (9 * {_itemAmount}) * 4 to (9 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (3 * {_itemAmount}) * 4 to (3 * {_itemAmount} + {lvl.%player%}) * 4
						#Lapis Lazuli 
						else if {_itemType} is 4:
							set {radiantQuest.%player%.%loop-value%::Target} to "lapis"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (2 * {_itemAmount}) * 4 to (2 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (1.2 * {_itemAmount}) * 4 to (1.2 * {_itemAmount} + {lvl.%player%}) * 4
						#Redstone Dust
						else if {_itemType} is 5:
							set {radiantQuest.%player%.%loop-value%::Target} to "redstone dust"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (2 * {_itemAmount}) * 4 to (2 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (1.2 * {_itemAmount}) * 4 to (1.2 * {_itemAmount} + {lvl.%player%}) * 4
						#Emerald
						else if {_itemType} is 6:
							set {radiantQuest.%player%.%loop-value%::Target} to "emeralds"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (30 * {_itemAmount}) * 4 to (30 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (5 * {_itemAmount}) * 4 to (5 * {_itemAmount} + {lvl.%player%}) * 4
						#Diamond
						else if {_itemType} is 7:
							set {radiantQuest.%player%.%loop-value%::Target} to "diamonds"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (40 * {_itemAmount}) * 4 to (40 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (10 * {_itemAmount}) * 4 to (10 * {_itemAmount} + {lvl.%player%}) * 4
						#Flint
						else if {_itemType} is 8:
							set {radiantQuest.%player%.%loop-value%::Target} to "flint"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (2.5 * {_itemAmount}) * 4 to (2.5 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (1 * {_itemAmount}) * 4 to (1.25 * {_itemAmount} + {lvl.%player%}) * 4
						#Gunpowder
						else if {_itemType} is 9:
							set {radiantQuest.%player%.%loop-value%::Target} to "gunpowder"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (3 * {_itemAmount}) * 4 to (3 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (1 * {_itemAmount}) * 4 to (1.25 * {_itemAmount} + {lvl.%player%}) * 4
						#Bricks (item)
						else if {_itemType} is 10:
							set {radiantQuest.%player%.%loop-value%::Target} to "brick"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (1.25 * {_itemAmount}) * 4 to (1.25 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (0.25 * {_itemAmount}) * 4 to (0.35 * {_itemAmount} + {lvl.%player%}) * 4
						#Wood Logs
						else if {_itemType} is 11:
							set {radiantQuest.%player%.%loop-value%::Target} to "any log"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (1.5 * {_itemAmount}) * 4 to (1.5 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (0.25 * {_itemAmount}) * 4 to (0.35 * {_itemAmount} + {lvl.%player%}) * 4
						#Dirt
						else if {_itemType} is 12:
							set {radiantQuest.%player%.%loop-value%::Target} to "dirt"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (0.25 * {_itemAmount}) * 4 to (0.25 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (0.01 * {_itemAmount}) * 4 to (0.05 * {_itemAmount} + {lvl.%player%}) * 4
						#Cobblestone
						else if {_itemType} is 13:
							set {radiantQuest.%player%.%loop-value%::Target} to "cobblestone"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (0.5 * {_itemAmount}) * 4 to (0.5 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (0.1 * {_itemAmount}) * 4 to (0.2 * {_itemAmount} + {lvl.%player%}) * 4
						#Glass
						else if {_itemType} is 14:
							set {radiantQuest.%player%.%loop-value%::Target} to "glass block"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (2.5 * {_itemAmount}) * 4 to (2.5 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (0.75 * {_itemAmount}) * 4 to (1 * {_itemAmount} + {lvl.%player%}) * 4
						#Wool
						else if {_itemType} is 15:
							set {radiantQuest.%player%.%loop-value%::Target} to "any wool"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (2 * {_itemAmount}) * 4 to (2 * {_itemAmount} + {lvl.%player%}) * 4
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (0.5 * {_itemAmount}) * 4 to (0.75 * {_itemAmount} + {lvl.%player%}) * 4
					#Slay Monsters
					else if {radiantQuest.%player%.%loop-value%::Type} is 1:
						set {_monsterType} to a random integer from 0 to 12
						set {_mobAmount} to random integer from ceil({lvl.%player%} / 4) to floor({lvl.%player%} * 0.75)
						if {_mobAmount} is more than 12:
							set {_mobAmount} to 12
						if {_monsterType} is more than 6:
							if {_monsterType} is less than 11:
								set {_mobAmount} to ceil({_mobAmount} / 2)
						set {radiantQuest.%player%.%loop-value%::Amount} to {_mobAmount}
						#Zombies
						if {_monsterType} is 1:
							set {radiantQuest.%player%.%loop-value%::Target} to "zombie" parsed as entity type
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (5 * {_mobAmount}) * 4 to (8 * {_mobAmount}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (6.5 * {_mobAmount}) * 4 to (9 * {_mobAmount}) * 4
						#Skeletons
						if {_monsterType} is 2:
							set {radiantQuest.%player%.%loop-value%::Target} to "skeleton" parsed as entity type
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (5 * {_mobAmount}) * 4 to (8 * {_mobAmount}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (6.5 * {_mobAmount}) * 4 to (9 * {_mobAmount}) * 4
						#Spiders
						if {_monsterType} is 3:
							set {radiantQuest.%player%.%loop-value%::Target} to "spider" parsed as entity type
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (5 * {_mobAmount}) * 4 to (8 * {_mobAmount}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (6.5 * {_mobAmount}) * 4 to (9 * {_mobAmount}) * 4
						#Creepers
						if {_monsterType} is 4:
							set {radiantQuest.%player%.%loop-value%::Target} to "creeper" parsed as entity type
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (5 * {_mobAmount}) * 4 to (8 * {_mobAmount}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (6.5 * {_mobAmount}) * 4 to (9 * {_mobAmount}) * 4
						#Witch
						if {_monsterType} is 5:
							set {radiantQuest.%player%.%loop-value%::Target} to "witch" parsed as entity type
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (7 * {_mobAmount}) * 4 to (12 * {_mobAmount}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (8.5 * {_mobAmount}) * 4 to (14 * {_mobAmount}) * 4
						#Slime
						if {_monsterType} is 6:
							set {radiantQuest.%player%.%loop-value%::Target} to "slime" parsed as entity type
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (7 * {_mobAmount}) * 4 to (12 * {_mobAmount}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (8.5 * {_mobAmount}) * 4 to (14 * {_mobAmount}) * 4
						#Cow
						if {_monsterType} is 7:
							set {radiantQuest.%player%.%loop-value%::Target} to "cow" parsed as entity type
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (1.5 * {_mobAmount}) * 4 to (2.5 * {_mobAmount}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (1.15 * {_mobAmount}) * 4 to (2 * {_mobAmount}) * 4
						#Chicken
						if {_monsterType} is 8:
							set {radiantQuest.%player%.%loop-value%::Target} to "chicken" parsed as entity type
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (1.5 * {_mobAmount}) * 4 to (2.5 * {_mobAmount}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (1.15 * {_mobAmount}) * 4 to (2 * {_mobAmount}) * 4
						#Pig
						if {_monsterType} is 9:
							set {radiantQuest.%player%.%loop-value%::Target} to "pig" parsed as entity type
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (1.5 * {_mobAmount}) * 4 to (2.5 * {_mobAmount}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (1.15 * {_mobAmount}) * 4 to (2 * {_mobAmount}) * 4
						#Sheep
						if {_monsterType} is 10:
							set {radiantQuest.%player%.%loop-value%::Target} to "sheep" parsed as entity type
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (1.5 * {_mobAmount}) * 4 to (2.5 * {_mobAmount}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (1.15 * {_mobAmount}) * 4 to (2 * {_mobAmount}) * 4
						#Cave Spider
						if {_monsterType} is 11:
							set {radiantQuest.%player%.%loop-value%::Target} to "cave spider" parsed as entity type
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (7 * {_mobAmount}) * 4 to (12 * {_mobAmount}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (8.5 * {_mobAmount}) * 4 to (14 * {_mobAmount}) * 4
						#Any Monster
						if {_monsterType} is 12:
							set {radiantQuest.%player%.%loop-value%::Target} to "of any monster"
							set {radiantQuest.%player%.%loop-value%::GoldReward} to a random integer from (3.5 * {_mobAmount}) * 4 to (7 * {_mobAmount}) * 4
							set {radiantQuest.%player%.%loop-value%::EXPReward} to a random integer from (2.5 * {_mobAmount}) * 4 to (4 * {_mobAmount}) * 4
						set {radiantQuest.%player%.%loop-value%::EXPReward} to ceil({radiantQuest.%player%.%loop-value%::EXPReward} / 10)
			open chest inventory with 2 rows named "<gold>Available Quests" for the player
			loop {radiantQuestsOnOffer.%player%} times:
				if {radiantQuest.%player%.%loop-value%::Type} is 0:
					if {radiantQuest.%player%.%loop-value%::Completion} is not set:
						set slot (loop-value - 1) of the player's current inventory to 1 chest named "<light yellow>Retrieve %{radiantQuest.%player%.%loop-value%::Amount}% %{radiantQuest.%player%.%loop-value%::Target}%." with lore "<white>Reward:", "<white>%{radiantQuest.%player%.%loop-value%::GoldReward}% gold", "<white>%{radiantQuest.%player%.%loop-value%::EXPReward}% EXP", "<light yellow>Click to accept this quest."
					else if {radiantQuest.%player%.%loop-value%::Completion} is not 999:
						if player has "%{radiantQuest.%player%.%loop-value%::Amount}% %{radiantQuest.%player%.%loop-value%::Target}%" parsed as item type:
							set slot (loop-value - 1) of the player's current inventory to 1 gold block named "<gold>Retrieve %{radiantQuest.%player%.%loop-value%::Amount}% %{radiantQuest.%player%.%loop-value%::Target}%." with lore "<white>Reward:", "<white>%{radiantQuest.%player%.%loop-value%::GoldReward}% gold", "<white>%{radiantQuest.%player%.%loop-value%::EXPReward}% EXP", "<light blue>This quest is in progress.", "<light green>Click to turn in this quest! (Requested items will be lost.)"
						else:
							set slot (loop-value - 1) of the player's current inventory to 1 lapis block named "<light blue>Retrieve %{radiantQuest.%player%.%loop-value%::Amount}% %{radiantQuest.%player%.%loop-value%::Target}%." with lore "<white>Reward:", "<white>%{radiantQuest.%player%.%loop-value%::GoldReward}% gold", "<white>%{radiantQuest.%player%.%loop-value%::EXPReward}% EXP", "<light blue>This quest is in progress.", "<light red>Click to drop this quest."
					else:
						set slot (loop-value - 1) of the player's current inventory to 1 emerald block named "<light blue>Retrieve %{radiantQuest.%player%.%loop-value%::Amount}% %{radiantQuest.%player%.%loop-value%::Target}%." with lore "<white>Reward:", "<white>%{radiantQuest.%player%.%loop-value%::GoldReward}% gold", "<light green>This quest is complete!"
				else if {radiantQuest.%player%.%loop-value%::Type} is 1:
					if {radiantQuest.%player%.%loop-value%::Completion} is not set:
						set slot (loop-value - 1) of the player's current inventory to 1 rotten flesh named "<light yellow>Hunt %{radiantQuest.%player%.%loop-value%::Amount}% %{radiantQuest.%player%.%loop-value%::Target}%." with lore "<white>Rewards:", "<white>%{radiantQuest.%player%.%loop-value%::GoldReward}% gold", "<white>%{radiantQuest.%player%.%loop-value%::EXPReward}% EXP", "<light yellow>Click to accept this quest."
					else if {radiantQuest.%player%.%loop-value%::Completion} is not 999:
						set slot (loop-value - 1) of the player's current inventory to 1 lapis block named "<light blue>Hunt %{radiantQuest.%player%.%loop-value%::Amount}% %{radiantQuest.%player%.%loop-value%::Target}%." with lore "<white>Rewards:", "<white>%{radiantQuest.%player%.%loop-value%::GoldReward}% gold", "<white>%{radiantQuest.%player%.%loop-value%::EXPReward}% EXP", "<light blue>Progress: %{radiantQuest.%player%.%loop-value%::Completion} - 1% targets slain.", "<light red>Click to drop this quest."
					else:
						set slot (loop-value - 1) of the player's current inventory to 1 emerald block named "<light green>Hunt %{radiantQuest.%player%.%loop-value%::Amount}% %{radiantQuest.%player%.%loop-value%::Target}%." with lore "<white>Rewards:", "<white>%{radiantQuest.%player%.%loop-value%::GoldReward}% gold", "<white>%{radiantQuest.%player%.%loop-value%::EXPReward}% EXP", "<light green>This quest is complete!"

#Experience Bottler
command /xpbottler:
	trigger:
		open chest inventory with 1 row named "<gold>Experience Bottler" for the player
		set slot 0 of the player's current inventory to 1 light green wool named "<light green>Bottle 1 XP Level"
		set slot 1 of the player's current inventory to 1 orange wool named "<orange>Bottle 5 XP Levels"
		set slot 2 of the player's current inventory to 1 yellow wool named "<yellow>Bottle 10 XP Levels"
		set slot 3 of the player's current inventory to 1 book named "<gold>How To Use" with lore "<white>Click a button to manage your XP level.", "<white>The buttons convert the experience used for enchanting to consumable bottles.", "<white>Converted bottles will be placed into your inventory."
		set slot 4 of the player's current inventory to 1 light green wool named "<light green>Convert 15 XP Levels to 1 Class Level"
		set slot 5 of the player's current inventory to 1 orange wool named "<orange>Convert 30 XP Levels to 2 Class Levels"
		set slot 6 of the player's current inventory to 1 yellow wool named "<yellow>Convert 60 XP Levels to 4 Class Levels"

#Portable Stations
on right click with anvil:
	if the name of the player's tool is "<gold>Portable Smithy":
		make player execute command "/buyToolSkills 0 1"
	else if the name of the player's tool is "<gold>Portable Weaponsmith":
		make player execute command "/weaponshop 0"
		
on right click with end portal frame:
	if the name of the player's tool is "<gold>Ore Converter":
		make player execute command "/oreconverter 0"
	else if the name of the player's tool is "<gold>Sacred Forge":
		make player execute command "/hwbuy hw"
		
on right click with bed:
	if the name of the player's tool is "<gold>Portable Inn":
		make player execute command "/tavernshop"
		
on right click with chest:
	if the name of the player's tool is "<gold>Portable Trader":
		make player execute command "/tradershop"
	else if the name of the player's tool is "<gold>Portable Tailor":
		make player execute command "/tailorshop"
	else if the name of the player's tool is "<gold>Portable Banker":
		make player execute command "/cvault open"
		
on right click with enchanting table:
	if the name of the player's tool is "<gold>Portable Enchanter":
		make player execute command "/enchantershop"
	else if the name of the player's tool is "<gold>Ancient Enchanter":
		make player execute command "/portableawaken"

on right click with brewing stand:
	if the name of the player's tool is "<gold>Portable Spell Inscriber":
		make player execute command "/spells 1"
	else if the name of the player's tool is "<gold>Portable Brewery":
		make player execute command "/serositabarkeep"
	else if the name of the player's tool is "<gold>Experience Bottler":
		make player execute command "/xpbottler"
		
on consume:
	if the name of the player's tool is "<light blue>Bottled Experience":
		make player execute command "/xp 1l"
		send "<light blue>Consumed the Bottled Experience and gained 1 XP level."
	else if the name of the player's tool is "<light blue>Large Bottle of Experience":
		make player execute command "/xp 5l"
		send "<light blue>Consumed the Large Bottle of Experience and gained 5 XP levels."
	else if the name of the player's tool is "<light blue>Massive Bottle of Experience":
		make player execute command "/xp 10l"
		send "<light blue>Consumed the Large Bottle of Experience and gained 10 XP levels."
	else if the name of the player's tool contains "Class XP":
		if {lvl.%player%} is less than {lvlcap.%player%}:
			set {_playerLVL} to getPromotionCompensatedClassLevel(player)
			set {_cXP} to (ceil((({_playerLVL} + ({_playerLVL} ^ 2)) / (1 + ({promoted.%{_PLR}%} - 1))) + 10)) - {classXP.%player%}
			if the name of the player's tool is "<light blue>Packaged Class XP":
				addClassXP(player,{_cXP})
				send "<light blue>Consumed the Packaged Class XP and gained 1 Class Level."
			else if the name of the player's tool is "<light blue>Large Package of Class XP":
				loop 2 times:
					addClassXP(player,{_cXP})
				send "<light blue>Consumed the Large Package of Experience and gained 2 Class Levels."
			else if the name of the player's tool is "<light blue>Massive Package of Class XP":
				loop 4 times:
					addClassXP(player,{_cXP})
				send "<light blue>Consumed the Massive Package of Experience and gained 4 Class Levels."
		else:
			send "<light red>Using this wouldn't benefit you right now."
			cancel event
		
on place:
	if the name of the player's tool is "<gold>Portable Smithy":
		cancel event
	else if the name of the player's tool is "<gold>Portable Spell Inscriber":
		cancel event
	else if the name of the player's tool is "<gold>Portable Brewery":
		cancel event
	else if the name of the player's tool is "<gold>Portable Enchanter":
		cancel event
	else if the name of the player's tool is "<gold>Portable Trader":
		cancel event
	else if the name of the player's tool is "<gold>Portable Tailor":
		cancel event
	else if the name of the player's tool is "<gold>Portable Inn":
		cancel event
	else if the name of the player's tool is "<gold>Experience Bottler":
		cancel event
	else if the name of the player's tool is "<gold>Ore Converter":
		cancel event
	else if the name of the player's tool is "<gold>Ancient Enchanter":
		cancel event
	else if the name of the player's tool is "<gold>Sacred Forge":
		cancel event
	else if the name of the player's tool is "<gold>Portable Banker":
		cancel event
	else if the name of the player's tool is "<gold>Portable Weaponsmith":
		cancel event

#Misc NPCs				
on right click on a player:
	#Player Finder
	if target's name is "Player Finder":
		make player execute command "/listplayers"
	#Questmaster
	else if target's name is "Questmaster":
		if {radiantQuestsRNG.%player%} is set:
			loop {radiantQuestsOnOffer.%player%} times:
				if {radiantQuest.%player%.%loop-value%::Completion} is set:
					if {radiantQuest.%player%.%loop-value%::Completion} is not 999:
						send formatted "<light blue>Questmaster: <white>I just got a new batch of jobs in, but it looks like you're still working on some older ones. If you want, I can hold those jobs for you." to the player
						wait 3 seconds
						send formatted "<run command:/questmaster quests oldview><gold>1 - Hold those jobs for me." to the player
						send formatted "<run command:/questmaster quests view><gold>2 - What new jobs are on offer? (This will fail any active jobs!)" to the player
						set {_skipText} to true
						exit 1 loop
			if {_skipText} is not set:
				send formatted "<light blue>Questmaster: <white>Just got a new batch of jobs in today." to the player
				wait 2 seconds
				send formatted "<run command:/questmaster quests view><gold>1 - What jobs are on offer?" to the player
		else:
			send formatted "<light blue>Questmaster: <white>Plenty of jobs still on the board." to the player
			wait 2 seconds
			send formatted "<run command:/questmaster quests view><gold>1 - What jobs are on offer?" to the player
	#Tailor
	else if target's name is "Tailor":
		send formatted "<light blue>Tailor: <white>If you need some clothes dyed, then you've come to the right place." to the player
		wait 2 seconds
		send formatted "<run command:/tailorshop><gold>1 - What do you have for sale?" to the player