#Quest Progress
#Not Set - Locked
#1 - Incomplete
#999 - Complete
#998 - Failed

function getHelmet(PLR: player) :: number:
	if {_PLR} is wearing a leather helmet:
		return 1
	else if {_PLR} is wearing a chain helmet:
		return 2
	else if {_PLR} is wearing an iron helmet:
		return 3
	else if {_PLR} is wearing a gold helmet:
		return 4
	else if {_PLR} is wearing a diamond helmet:
		return 5
		
function getChestplate(PLR: player) :: number:
	if {_PLR} is wearing a leather chestplate:
		return 1
	else if {_PLR} is wearing a chain chestplate:
		return 2
	else if {_PLR} is wearing an iron chestplate:
		return 3
	else if {_PLR} is wearing a gold chestplate:
		return 4
	else if {_PLR} is wearing a diamond chestplate:
		return 5

function getLeggings(PLR: player) :: number:
	if {_PLR} is wearing leather leggings:
		return 1
	else if {_PLR} is wearing chain leggings:
		return 2
	else if {_PLR} is wearing iron leggings:
		return 3
	else if {_PLR} is wearing gold leggings:
		return 4
	else if {_PLR} is wearing diamond leggings:
		return 5
		
function getBoots(PLR: player) :: number:
	if {_PLR} is wearing leather boots:
		return 1
	else if {_PLR} is wearing chain boots:
		return 2
	else if {_PLR} is wearing iron boots:
		return 3
	else if {_PLR} is wearing gold boots:
		return 4
	else if {_PLR} is wearing diamond boots:
		return 5

function startQuest(PLR: player , QUEST: text , DESC: text):
	set {quests.%{_PLR}%::%{_QUEST}%} to 1
	send title "<white><bold>New Quest: %{_QUEST}%" with subtitle "%{_DESC}%" to {_PLR} for 5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
	play sound "entity.fireworkrocket.launch" with volume 0.75 and pitch 1 at {_PLR} for {_PLR}
	play sound "entity.fireworkrocket.twinkle" with volume 0.4 and pitch 1.5 at {_PLR} for {_PLR}
	play sound "entity.player.levelup" with volume 1 and pitch 1 at {_PLR} for {_PLR}
	play 60 (firework spark with speed 1) at {_PLR}
	play 60 (snow shovel with speed 1) at {_PLR}

function setQuestProgress(PLR: player , QUEST: text , STAGE: number, INFO: text):
	set {quests.%{_PLR}%::%{_QUEST}%} to {_STAGE}
	send title "" with subtitle "%{_INFO}%" to {_PLR} for 2.5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
	play sound "entity.player.levelup" with volume 0.5 and pitch 1.5 at {_PLR} for {_PLR}
	play sound "entity.fireworkrocket.twinkle" with volume 0.4 and pitch 1.5 at {_PLR} for {_PLR}
	play 10 (firework spark with speed 1) at {_PLR}
	play 10 (snow shovel with speed 1) at {_PLR}
	
function finishQuest(PLR: player , QUEST: text , DESC: text):
	set {quests.%{_PLR}%::%{_QUEST}%} to 999
	send title "<gold><bold>Quest Complete: %{_QUEST}%" with subtitle "%{_DESC}%" to {_PLR} for 5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
	play sound "entity.player.levelup" with volume 1 and pitch 0.75 at {_PLR} for {_PLR}
	play sound "entity.fireworkrocket.twinkle" with volume 1 and pitch 1.5 at {_PLR} for {_PLR}
	play 60 (firework spark with speed 1) at {_PLR}
	play 60 (snow shovel with speed 1) at {_PLR}
	
function failQuest(PLR: player , QUEST: text , DESC: text):
	set {quests.%{_PLR}%::%{_QUEST}%} to 998
	send title "<light red><bold>Quest Failed: %{_QUEST}%" with subtitle "%{_DESC}%" to {_PLR} for 5 seconds with fade in 0.25 seconds and fade out 0.25 seconds
	play 60 (red wool break with speed 1) at {_PLR}
	show mob spawner flames on {_PLR}
	
#Calculates the player's preferred/best weapon using their weapon ranks.
function bestWeapon(PLR: player) :: number:
	if ({weaponrank.%{_PLR}%::swords} + {weaponrank.%{_PLR}%::lances} + {weaponrank.%{_PLR}%::bows} + {weaponrank.%{_PLR}%::magic} + {weaponrank.%{_PLR}%::staves}) is more than ({weaponrank.%{_PLR}%::axes} + {weaponrank.%{_PLR}%::lances} + {weaponrank.%{_PLR}%::bows} + {weaponrank.%{_PLR}%::magic} + {weaponrank.%{_PLR}%::staves}):
		return 1
	else if ({weaponrank.%{_PLR}%::axes} + {weaponrank.%{_PLR}%::lances} + {weaponrank.%{_PLR}%::bows} + {weaponrank.%{_PLR}%::magic} + {weaponrank.%{_PLR}%::staves}) is more than ({weaponrank.%{_PLR}%::swords} + {weaponrank.%{_PLR}%::lances} + {weaponrank.%{_PLR}%::bows} + {weaponrank.%{_PLR}%::magic} + {weaponrank.%{_PLR}%::staves}):
		return 2
	else if ({weaponrank.%{_PLR}%::lances} + {weaponrank.%{_PLR}%::swords} + {weaponrank.%{_PLR}%::bows} + {weaponrank.%{_PLR}%::magic} + {weaponrank.%{_PLR}%::staves}) is more than ({weaponrank.%{_PLR}%::axes} + {weaponrank.%{_PLR}%::swords} + {weaponrank.%{_PLR}%::bows} + {weaponrank.%{_PLR}%::magic} + {weaponrank.%{_PLR}%::staves}):
		return 3
	else if ({weaponrank.%{_PLR}%::bows} + {weaponrank.%{_PLR}%::lances} + {weaponrank.%{_PLR}%::swords} + {weaponrank.%{_PLR}%::magic} + {weaponrank.%{_PLR}%::staves}) is more than ({weaponrank.%{_PLR}%::axes} + {weaponrank.%{_PLR}%::lances} + {weaponrank.%{_PLR}%::swords} + {weaponrank.%{_PLR}%::magic} + {weaponrank.%{_PLR}%::staves}):
		return 4
	else if ({weaponrank.%{_PLR}%::magic} + {weaponrank.%{_PLR}%::lances} + {weaponrank.%{_PLR}%::bows} + {weaponrank.%{_PLR}%::swords} + {weaponrank.%{_PLR}%::staves}) is more than ({weaponrank.%{_PLR}%::axes} + {weaponrank.%{_PLR}%::lances} + {weaponrank.%{_PLR}%::bows} + {weaponrank.%{_PLR}%::swords} + {weaponrank.%{_PLR}%::staves}):
		return 5
	else if ({weaponrank.%{_PLR}%::staves} + {weaponrank.%{_PLR}%::lances} + {weaponrank.%{_PLR}%::bows} + {weaponrank.%{_PLR}%::magic} + {weaponrank.%{_PLR}%::swords}) is more than ({weaponrank.%{_PLR}%::axes} + {weaponrank.%{_PLR}%::lances} + {weaponrank.%{_PLR}%::bows} + {weaponrank.%{_PLR}%::magic} + {weaponrank.%{_PLR}%::swords}):
		return 6
	
command /setupcheck:
	trigger:
		if {quests.%player%::New Arrival} is not 999:
			teleport the player to location at 433, 64, 263 in world "adventure"
			send "<light red>You need to finish registering before you're allowed into Silgrid. Talk to Validar at the desk for more information."
	
on damage of a player:
	if victim is npc:
		if the name of the victim contains "Combat Trainer":
			if {quests.%attacker%::Days of Training} is 2:
				cancel event
				send "<light blue>%victim's name%: ...Good thing you came here for training. You swing that thing around like it's a stick." to the attacker
				wait 5 seconds
				send "<light blue>%victim's name%: Well, that one's simple to fix. Just keep practicing with your weapon, and your skills will improve. To make it simple for everyone, the Knights get a Weapon Rank for each weapon type they use. Since you're just starting, you're going to have an ""E"" rank. The more you use a specific weapon type, the better the rank you'll get." to the attacker
				wait 10 seconds
				if {drenable.%attacker%} is 1:
					send "<light blue>%victim's name%: Now, let's see if you can do a Dodge Roll. All you need to do to roll is start sneaking twice in a row. Do it fast or else you won't be able to roll." to the attacker
					setQuestProgress(attacker,"Days of Training",3,"Perform a Dodge Roll by double-tapping your ""Sneak"" key (SHIFT by default).")
				else:
					send "<light blue>%victim's name%: ...It says here in your registration that you're not going to be doing any Dodge Rolling. Your mistake. I'd go get that fixed later, Dodge Rolling will save your life if you bother to learn it." to the attacker
					wait 6 seconds
					send "<light blue>%victim's name%: Now I suppose we're going to have to talk about perks. You'll get these after leveling up or by getting a Promotion, and with one equipped you'll be able to enhance your abilities." to the attacker
					wait 5 seconds
					make attacker execute command "/xp 1l"
					send "<light blue>%victim's name%: Your practice should've earned you an extra level. Go ahead and equip your new HP +5 perk by using /perks." to the attacker
					setQuestProgress(attacker,"Days of Training",4,"Equip the HP +5 perk by using /perks.")
		else if the name of the victim is "Lord Kiln":
			cancel event
		
on death of a monster:
	if {quests.%attacker%::Proving Grounds} is not 999:
		if {quests.%attacker%::Proving Grounds} is not 998:
			if {quests.%attacker%::Proving Grounds} is set:
				setQuestProgress(attacker,"Proving Grounds",{quests.%attacker%::Proving Grounds} + 1,"%{quests.%attacker%::Proving Grounds}%/10 monsters slain.")
				if {quests.%attacker%::Proving Grounds} is 11:
					finishQuest(attacker,"Proving Grounds","")
					wait 6 seconds
					startQuest(attacker,"Home Sweet Home","Settle down and build a home using the resources nearby.")
	else if {quests.%attacker%::Path of the Greats} is not 999:
		if {quests.%attacker%::Path of the Greats} is more than 1:
			if the 1st line of the lore of the attacker's tool contains "Slot A - ":
				setQuestProgress(attacker,"Path of the Greats",{quests.%attacker%::Path of the Greats} + 1,"%{quests.%attacker%::Path of the Greats} - 2%/10 monsters slain using weapon skills.")
			if {quests.%attacker%::Path of the Greats} is 12:
				finishQuest(attacker,"Path of the Greats","Weapon Skills are now unlocked at all blacksmiths.")
	else if {quests.%attacker%::Liberation} is not 999:
		if {quests.%attacker%::Liberation} is set:
			if the name of the attacker's tool contains "<gold><bold>":
				setQuestProgress(attacker,"Liberation",{quests.%attacker%::Liberation} + 1,"%{quests.%attacker%::Liberation} - 1%/30 monsters slain using Holy Weapons.")
			if {quests.%attacker%::Liberation} is 31:
				finishQuest(attacker,"Liberation","+5 XP Levels")
				wait 6 seconds
				make attacker execute command "/xp 5l"
				wait 10 seconds
				send "<light yellow>Cinder: Impressed, %attacker's tablist name%<reset><light yellow>? My weapons are the finest you'll ever lay hands on." to the attacker
				wait 5 seconds
				send "<light yellow>Cinder: ..." to the attacker
				wait 1.5 seconds
				damage the attacker by 0.5
				send "<light yellow>Cinder: Sorry about that prick, I needed some energy for a chat. Scouts have just come back from the Yied Desert. Reports say there's a large number of undead thralls coming from Summoner's Sword, one of the old fortresses Alstair constructed. Kiln says we should clear it out and look for something to point us towards whoever's leading this undead invasion." to the attacker
				startQuest(attacker,"A Deadly Test of Might","Investigate Summoner's Sword inside the Yied Desert.")
				wait 8 seconds
				send "<light yellow>Cinder: Before you go running off, you should think about taking a trip to Alstair's old castle: House Aideen. It's out past Colony 5." to the attacker
				wait 5 seconds
				send "<light yellow>Cinder: There should be a set of rings buried there that will help you. And if you ask me, I think you'll need them. I've got a bad feeling about what we'll find inside Summoner's Sword." to the attacker
	else if {quests.%attacker%::Invisible Ties} is more than 4:
		if {kilnRecruitable.%attacker%} is not set:
			if {quests.%attacker%::Invisible Ties} is less than 54:
				add 1 to {quests.%attacker%::Invisible Ties}
				if {quests.%attacker%::Invisible Ties} is 54:
					send "<light blue>Lord Kiln: %attacker's tablist name%<reset><light blue>... I want to express my gratitude towards you. You've done so much for me and my people." to the attacker
					wait 6 seconds
					send "<light blue>Lord Kiln: Thanks to you, I've gained confidence in myself. Enough to lead my kingdom without doubts." to the attacker
					wait 6 seconds
					send "<light blue>Lord Kiln: You've become far more than just one of my knights, %attacker's tablist name%<reset><light blue>. You've become my closest friend." to the attacker
					wait 6 seconds
					send "<light blue>Lord Kiln: I will follow you wherever you go, if you desire. The bonds we share... they will never be broken." to the attacker
					wait 6 seconds
					send "<light blue>Lord Kiln: Here is to a bright future for our country. Our people gifted this to me as thanks for our heroics, but I have little use for gold at the moment. You deserve it far more than I do." to the attacker
					wait 6.5 seconds
					send "<green>2,000 gold obtained!" to the attacker
					add 2000 to the attacker's balance
					send "<light blue>Lord Kiln: May we live long and healthy lives, %attacker's tablist name%<reset><light blue>." to the attacker
					finishQuest(player,"Invisible Ties","")
	if {quests.%attacker%::Monster Hunt} is set:
		if {quests.%attacker%::Monster Hunt} is less than or equal to {MHTarget.%attacker%}:
			setQuestProgress(attacker,"Monster Hunt",{quests.%attacker%::Monster Hunt} + 1,"%{quests.%attacker%::Monster Hunt}%/%{MHTarget.%attacker%}% monsters slain.")
			if {quests.%attacker%::Monster Hunt} is more than {MHTarget.%attacker%}:
				finishQuest(attacker,"Monster Hunt","%{MHTarget.%attacker%} * 5% gold obtained.")
				add ({MHTarget.%player%} * 5) to the attacker's balance
			
every 1 minecraft hour:
	set time in world "Alstair" to 24:00
	loop all players:
		if {quests.%loop-player%::Home Sweet Home} is not 999:
			if {quests.%loop-player%::Home Sweet Home} is not 998:
				if {quests.%loop-player%::Home Sweet Home} is set:
					add 1 to {quests.%loop-player%::Home Sweet Home}
					if {quests.%loop-player%::Home Sweet Home} is 22:
						finishQuest(loop-player,"Home Sweet Home","")
						wait 6 seconds
						startQuest(loop-player,"A Scarred Land","Return to House Silgrid, and talk to Lord Kiln.")

command /quests-alw <number>:
	trigger:
		if {quests.%player%::A Lord's Worth} is 1:
			if arg 1 is 1:
				send "<light yellow>Cinder: ...We are here..."
				wait 3 seconds
				send "<light yellow>Cinder: ...Find... my room... perform... an Awakening..."
				wait 4 seconds
				setQuestProgress(player,"A Lord's Worth",2,"Find Cinder's room, and perform an Awakening.")
			
command /quests-magicshrine [<number=0>]:
	trigger:
		if arg 1 is 0:
			if {quests.%player%::Journey to Nifl} is 1:
				loop all items in the player's inventory:
					if the name of the loop-item contains "Unusual":
						send "<gold>Nothing seems to be happening... Maybe I should try placing something else inside the slot."
						set {_flag} to 1
				if {_flag} is not set:
					strike lightning effect at the player
					send "<light yellow>???: ...Hmm...? Who...is there?"
					wait 3 seconds
					setQuestProgress(player,"Journey to Nifl",1,"Take the gemstone from the shrine.")
					send "<run command:/quests-magicshrine 1><gold>1 - Er... %player's tablist name%<reset><gold>?"
		else if arg 1 is 1:
			send "<light yellow>???: ...%player's tablist name%<reset><gold>?"
			wait 3 seconds
			send "<light yellow>???: ...How are you... speaking to me... %player's tablist name%<reset><light yellow>?"
			wait 4 seconds
			send "<run command:/quests-magicshrine 2><gold>1 - ...Through a gemstone?"
			send "<run command:/quests-magicshrine 3><gold>2 - ...Using my voice?"
		else if arg 1 is 3:
			send "<light yellow>???: ...You are funny... reminds me of... a friend..."
			wait 4 seconds
			send "<light yellow>???: ...But I must know... how are we speaking...?"
			wait 4 seconds
			send "<run command:/quests-magicshrine 2><gold>1 - Through a gemstone."
		else if arg 1 is 2:
			send "<light yellow>???: ...A gemstone... I... remember..."
			wait 3 seconds
			send "<light yellow>???: ...Our connection... the magic... is weak..."
			wait 4 seconds
			send "<light yellow>???: ...House Silgrid... take us there... strengthen the connection..."
			wait 4 seconds
			send "<run command:/quests-magicshrine 4><gold>1 - How do you know about House Silgrid?"
			send "<run command:/quests-magicshrine 5><gold>2 - ...Who are you exactly?"
		else if arg 1 is 4:
			send "<light yellow>???: ...House Silgrid... it is... my castle..."
			wait 3 seconds
			send "<light yellow>???: ...Haha... Do you know... who I am...?"
			wait 3 seconds
			send "<run command:/quests-magicshrine 5><gold>1 - ...No."
		else if arg 1 is 5:
			send "<light yellow>???: ...I am... the Blazing Lord..."
			wait 3.5 seconds
			send "<light yellow>Cinder: ...I am... Cinder."
			wait 3.5 seconds
			send "<light yellow>Cinder: ...Our connection... grows weaker... take us to... House Silgrid..."
			wait 4 seconds
			send "<light yellow>Cinder: ...There... we may restore my power... so I may... help your cause..."
			finishQuest(player,"Journey to Nifl","")
			wait 6 seconds
			send "<light yellow>Cinder: ...Hidden entrance... beneath the moat... take us there..."
			wait 4 seconds
			loop all items in the player's inventory:
				if the name of the loop-item contains "Unusual":
					set the 3rd line of the lore of the loop-item to "<white>It's pointing towards House Silgrid."
					set the 4th line of the lore of the loop-item to "<white>I need to check beneath the castle's moat for a hidden entrance."
			startQuest(player,"A Lord's Worth","Find the hidden entrance to House Silgrid with the gemstone.")

command /conv-na <number>:
	trigger:
		if arg 1 is 1:
			send "<light blue>Validar: Oh, great. Thanks for making my life harder for me, I REALLY do appreciate it."
			wait 5 seconds
			send "<light blue>Validar: *sigh*... Now I get to show you the ""wonders of registration"". I get paid to say that."
			wait 4 seconds
			send "<light blue>Validar: Here, take this survey for me and let me know when you're done. After you finish I can give you an ID and you can go on your way."
			wait 5 seconds
			send "<run command:/fsetup><gold>Click here to begin registration."
			
command /quests-hwget <number>:
	trigger:
		if {quests.%player%::Seeking the Light} is 2:
			setQuestProgress(player,"Seeking the Light",3,"Return to Lord Kiln with the Holy Weapon.")
		if arg 1 is 1:
			give 1 stone sword of unbreaking 100 named "<light blue><bold>Broken Sword" with lore "<white>A rusty sword unfit for combat.", "<white>Supposedly, this is what remains of the Binding Blade." to the player
		else if arg 1 is 2:
			give 1 stone sword of unbreaking 100 named "<light blue><bold>Broken Sword" with lore "<white>A rusty sword unfit for combat.", "<white>The handle design implies it is the remains of the Falchion." to the player
		else if arg 1 is 3:
			give 1 stone sword of unbreaking 100 named "<light blue><bold>Broken Sword" with lore "<white>A rusty sword unfit for combat.", "<white>This might be what remains of the Mystletainn." to the player
	
command /train <text>:
	trigger:
		if player's balance is more than or equal to 100:
			if arg 1 is "swords":
				add 100 to {weaponrank.%player%::Swords}
			else if arg 1 is "axes":
				add 100 to {weaponrank.%player%::Axes}
			else if arg 1 is "lances":
				add 100 to {weaponrank.%player%::Lances}
			else if arg 1 is "bows":
				add 100 to {weaponrank.%player%::Bows}
			else if arg 1 is "magic":
				add 100 to {weaponrank.%player%::Magic}
			subtract 200 from the player's balance
			send "<light green>Training successful! New balance: %player's money%"
		else if arg 1 is "staves":
			if player's balance is more than or equal to 75:
				add 10 to {weaponrank.%player%::Staves}
			else:
				send "<light red>You need at least $75 to train."
		else:
			send "<light red>You need at least $100 to train."
		
command /conv-ggy <number>:
	trigger:
		if {quests.%player%::Greats Guide You} is 2:
			if arg 1 is 1:
				send "<light blue>Lord Kiln: ...So be it, then."
				wait 2.5 seconds
				send "<light blue>Lord Kiln: It seems we have exhausted the hopes of utilizing the Holy Weapons."
				wait 4 seconds
				send "<light blue>Lord Kiln: Forgive me for sending you on this journey. I should have understood its futility."
				wait 4 seconds
				send "<light blue>Lord Kiln: I will not force you to continue researching the weapons. Continue of your own volition, though I believe they are a lost cause."
				wait 5 seconds
				send "<light blue>Lord Kiln: Unfortunately, our reserves are drying up due to the undead menace. This is all I can afford to spare you currently."
				send "<green>200 gold obtained!"
				add 200 to the player's balance
				wait 5 seconds
				send "<light blue>Lord Kiln: Should I need your aid once again, I will call you back here. For now, however, do as you wish."
				finishQuest(player,"Greats Guide You","")
				wait 60 seconds
				send "<green>You feel something shifting around inside your pocket..."
				wait 5 seconds
				send "<green>The gemstone from the Heroes' Guild is moving about on its own. It's acting as though it were a compass..."
				wait 5 seconds
				loop all items in the player's inventory:
					if the name of the loop-item contains "Unusual":
						set the 3rd line of the lore of the loop-item to "<white>It's pointing towards these coordinates:"
						set the 4th line of the lore of the loop-item to "<white>-802, 71, 323"
				startQuest(player,"Journey to Nifl","Follow the gemstone's directions.")
				
command /sheal:
	trigger:
		heal the player by the player's maximum health
		remove {_cashreq} from the player's money
		
command /debugstartquest <text>:
	trigger:
		startQuest(player,arg 1,"Quest initiated via a debug command.")
				
command /qstart:
	trigger:
		if {quests.%player%::New Arrival} is 1:
			send "<run command:/cosmetics><gold>Click here to begin setting-up your character's cosmetics. This is optional."
			wait 5 seconds
			setQuestProgress(player,"New Arrival",2,"Tell Validar that you've finished registering.")
		else:
			finishQuest(player,"New Arrival","You've completed registration and can now explore freely.")
			wait 6 seconds
			startQuest(player,"Days of Training","Report to the training grounds for combat practice.")
					
command /conv-invt <number>:
	trigger:
		if arg 1 is 1:
			startQuest(player,"Invisible Ties","")
			send "<light blue>Lord Kiln: I appreciate your use of formalities, but you may simply call me Kiln if you wish."
			wait 2 seconds
			send "<light blue>Lord Kiln: I must get my mind away from the invasion, at least for a short while. I understand that may be the last thing you would like to hear from me currently, but it is the truth."
			wait 4 seconds
			send "<light blue>Lord Kiln: ...I'm not quite sure what to talk about with you. I typically give orders instead of starting conversations. Would you happen to have an idea of what we may talk about?"
			wait 2 seconds
			send "<run command:/conv-invt 3><gold>1 - The castle garden is beautiful."
			send "<run command:/conv-invt 9><gold>2 - You don't seem to fight much at all. Is there a reason for that?"
		else if arg 1 is 3:
			send "<light blue>Lord Kiln: It is, isn't it? When I first took over the title of Lord, that entire area was just empty land."
			wait 2.5 seconds
			send "<light blue>Lord Kiln: I always loved the scenery of the forests nearby... Leaves waving in the wind, rivers snaking through the land... It puts me at ease."
			wait 3 seconds
			send "<light blue>Lord Kiln: Listen to me, becoming sentimental over simple plants and water... I must not sound much like a Lord at all after that."
			wait 3 seconds
			send "<run command:/conv-invt 4><gold>1 - You're just as much of a lord as your father was."
			send "<run command:/conv-invt 6><gold>2 - Of course. Who's ever heard of a lord who prefers sitting in his garden rather than ruling his kingdom?"
		else if arg 1 is 4:
			send "<light blue>Lord Kiln: Come now, just because you are one of my Knights doesn't mean you have to shower me with praise at every turn. I am perfectly willing to take criticism."
			wait 3.5 seconds
			send "<light blue>Lord Kiln: My father was far more worthy of the title of Lord than I ever will be. I could regale you on all of his accomplishments during his reign, but we would be here for hours on end."
			wait 4 seconds
			send "<light blue>Lord Kiln: Father's only shortcoming was that his reign was far too short for how great he was. I could never be even half the man he was..."
			wait 4 seconds
			send "<run command:/conv-invt 5><gold>1 - That's not true. You still have plenty of time to become a great Lord yourself."
			send "<run command:/conv-invt 6><gold>2 - What happened to your father?"
		else if arg 1 is 5:
			send "<light blue>Lord Kiln: %player's tablist name%,<reset><light blue> have you heard of any other lords that prefer planting gardens rather than fighting for his people? Instead of charging into battle alongside my countrymen, I wallow here in self-pity and anxiety. I am no match for my father's greatness, and it's unlikely I ever will be."
			wait 5.5 seconds
			send "<light blue>Lord Kiln: *sigh*... If my father were yet alive, he would have stopped these undead invaders in their tracks."
			wait 3 seconds
			send "<light blue>Lord Kiln: I miss him, %player's tablist name%<reset><light blue>. I truly do. If he were here, he would know what to do about this war of ours."
			wait 3 seconds
			send "<light blue>Lord Kiln: ...Here we are, talking about this blasted war again. Though, talking with you has made me feel somewhat more... relieved? I am not sure how to describe it. Thank you."
			wait 3.5 seconds
			send "<light blue>Lord Kiln: Here. I would like you to have this. Consider it a thanks for your assistance, and go forth on your journey with my blessings."
			wait 3.5 seconds
			set {_reward} to bestWeapon(player)
			if {_reward} is 1:
				give 1 iron sword of sharpness 3 named "<light blue>Silver Sword" with lore "<light red><bold>Slot A - Empty", "<light blue><bold>Slot B - Empty", "<light yellow><bold>Slot C - Empty", "<light green><bold>Assist - Empty", "<light purple><bold>Special - Empty", "<white><bold>Refine - Unrefined", "<white>A rather expensive sword typically handed out as a rare gift from a lord.", "<white>This one has come from Lord Kiln of House Silgrid." to the player
				send "<green>Silver Sword obtained!"
			else if {_reward} is 2:
				give 1 iron axe of sharpness 3 named "<light blue>Silver Axe" with lore "<light red><bold>Slot A - Empty", "<light blue><bold>Slot B - Empty", "<light yellow><bold>Slot C - Empty", "<light green><bold>Assist - Empty", "<light purple><bold>Special - Empty", "<white><bold>Refine - Unrefined", "<white>A rather expensive axe typically handed out as a rare gift from a lord.", "<white>This one has come from Lord Kiln of House Silgrid." to the player
				send "<green>Silver Axe obtained!"
			else if {_reward} is 3:
				give 1 iron shovel of sharpness 4 named "<light blue>Brave Lance" with lore "<light red><bold>Slot A - Empty", "<light blue><bold>Slot B - Brave Blade", "<light yellow><bold>Slot C - Empty", "<light green><bold>Assist - Empty", "<light purple><bold>Special - Empty", "<white><bold>Refine - Unrefined", "<white>A special lance that trades attack power for unparalleled speed." to the player
				send "<green>Brave Lance obtained!"
			else:
				add 175 to the player's balance
				send "<green>175 gold obtained!"
			setQuestProgress(player,"Invisible Ties",2,"Lord Kiln will remember this conversation.")
		else if arg 1 is 6:
			send "<light blue>Lord Kiln: You would be correct. My father, Zacharias, was far more deserving of the title of Lord. Why, with one slash of a blade, he could halt this undead invasion in its tracks."
			wait 3 seconds
			send "<light blue>Lord Kiln: Though I have tried, I have been unable to even come close to matching his strength."
			wait 3 seconds
			send "<light blue>Lord Kiln: It is... humiliating, to say the least. A descendant of the Blazing Lord can't even use a sword to save his life, let alone wield his family's Holy Weapon..."
			wait 3 seconds
			send "<run command:/conv-invt 7><gold>1 - Wait, you have a Holy Weapon here in the castle?!"
			send "<run command:/conv-invt 8><gold>2 - You can't wield Cinder's Holy Weapon?"
		else if arg 1 is 7:
			send "<light blue>Lord Kiln: Correct. Cinder's personal weapon, the Cobalt Blade, still resides here in the castle."
			wait 2.5 seconds
			send "<light blue>Lord Kiln: There's no use in trying to wield it. It turns heavy as a boulder the moment one's hand touches the blade. I have almost snapped my arm in two trying to pick the blade up..."
			wait 3.5 seconds
			send "<light blue>Lord Kiln: I imagine this is most likely the last thing you want to hear at a time like this, but it is the truth."
			wait 3.5 seconds
			send "<light blue>Lord Kiln: ...Here we are, talking about this blasted war again. Though, talking with you has made me feel somewhat more... relieved? I am not sure how to describe it. Thank you."
			wait 3.5 seconds
			send "<light blue>Lord Kiln: Here. I would like you to have this. Consider it a thanks for your assistance, and go forth on your journey with my blessings."
			wait 3.5 seconds
			set {_reward} to bestWeapon(player)
			if {_reward} is 1:
				give 1 iron sword of sharpness 3 named "<light blue>Silver Sword" with lore "<light red><bold>Slot A - Empty", "<light blue><bold>Slot B - Empty", "<light yellow><bold>Slot C - Empty", "<light green><bold>Assist - Empty", "<light purple><bold>Special - Empty", "<white><bold>Refine - Unrefined", "<white>A rather expensive sword typically handed out as a rare gift from a lord.", "<white>This one has come from Lord Kiln of House Silgrid." to the player
				send "<green>Silver Sword obtained!"
			else if {_reward} is 2:
				give 1 iron axe of sharpness 3 named "<light blue>Silver Axe" with lore "<light red><bold>Slot A - Empty", "<light blue><bold>Slot B - Empty", "<light yellow><bold>Slot C - Empty", "<light green><bold>Assist - Empty", "<light purple><bold>Special - Empty", "<white><bold>Refine - Unrefined", "<white>A rather expensive axe typically handed out as a rare gift from a lord.", "<white>This one has come from Lord Kiln of House Silgrid." to the player
				send "<green>Silver Axe obtained!"
			else if {_reward} is 3:
				give 1 iron shovel of sharpness 4 named "<light blue>Brave Lance" with lore "<light red><bold>Slot A - Empty", "<light blue><bold>Slot B - Brave Blade", "<light yellow><bold>Slot C - Empty", "<light green><bold>Assist - Empty", "<light purple><bold>Special - Empty", "<white><bold>Refine - Unrefined", "<white>A special lance that trades attack power for unparalleled speed." to the player
				send "<green>Brave Lance obtained!"
			else:
				add 175 to the player's balance
				send "<green>175 gold obtained!"
			setQuestProgress(player,"Invisible Ties",2,"Lord Kiln will remember this conversation.")
		else if arg 1 is 8:
			send "<light blue>Lord Kiln: This is true, and it pains me to no end. My father was able to wield it, and to great effect."
			wait 2.5 seconds
			send "<light blue>Lord Kiln: I try not to admit this to anyone, however. It is embarassing to the utmost degree to have a family heirloom outright reject me as blatantly as the Cobalt Blade has."
			wait 2.5 seconds
			send "<light blue>Lord Kiln: I imagine hearing that a Holy Weapon resides in this castle with no-one able to wield it is overwhelmingly frustrating to hear. Forgive me, for I am unworthy of wielding the blade and aiding your mission."
			wait 3.5 seconds
			send "<light blue>Lord Kiln: Perhaps if I were only stronger, more worthy of being a true Lord, I could join you with the might of the Cobalt Blade. Alas, as fate would have it, I am doomed to wallow in shame inside this castle."
			wait 3.5 seconds
			send "<light blue>Lord Kiln: ...Here we are, talking about this blasted war again. Though, talking with you has made me feel somewhat more... relieved? I am not sure how to describe it. Thank you."
			wait 3.5 seconds
			send "<light blue>Lord Kiln: Here. I would like you to have this. Consider it a thanks for your assistance, and go forth on your journey with my blessings."
			wait 3.5 seconds
			set {_reward} to bestWeapon(player)
			if {_reward} is 1:
				give 1 iron sword of sharpness 3 named "<light blue>Silver Sword" with lore "<light red><bold>Slot A - Empty", "<light blue><bold>Slot B - Empty", "<light yellow><bold>Slot C - Empty", "<light green><bold>Assist - Empty", "<light purple><bold>Special - Empty", "<white><bold>Refine - Unrefined", "<white>A rather expensive sword typically handed out as a rare gift from a lord.", "<white>This one has come from Lord Kiln of House Silgrid." to the player
				send "<green>Silver Sword obtained!"
			else if {_reward} is 2:
				give 1 iron axe of sharpness 3 named "<light blue>Silver Axe" with lore "<light red><bold>Slot A - Empty", "<light blue><bold>Slot B - Empty", "<light yellow><bold>Slot C - Empty", "<light green><bold>Assist - Empty", "<light purple><bold>Special - Empty", "<white><bold>Refine - Unrefined", "<white>A rather expensive axe typically handed out as a rare gift from a lord.", "<white>This one has come from Lord Kiln of House Silgrid." to the player
				send "<green>Silver Axe obtained!"
			else if {_reward} is 3:
				give 1 iron shovel of sharpness 4 named "<light blue>Brave Lance" with lore "<light red><bold>Slot A - Empty", "<light blue><bold>Slot B - Brave Blade", "<light yellow><bold>Slot C - Empty", "<light green><bold>Assist - Empty", "<light purple><bold>Special - Empty", "<white><bold>Refine - Unrefined", "<white>A special lance that trades attack power for unparalleled speed." to the player
				send "<green>Brave Lance obtained!"
			else:
				add 175 to the player's balance
				send "<green>175 gold obtained!"
			setQuestProgress(player,"Invisible Ties",2,"Lord Kiln will remember this conversation.")
		else if arg 1 is 9:
			send "<light blue>Lord Kiln: ..."
			wait 3 seconds
			send "<run command:/conv-invt 10><gold>1 - ...Milord?"
			send "<run command:/conv-invt 3><gold>2 - ...The garden is lovely."
		else if arg 1 is 10:
			send "<light blue>Lord Kiln: ...Forgive my rudeness. Combat is a rather sore subject for me."
			wait 3 seconds
			send "<light blue>Lord Kiln: Truth be told, I absolutely loathe any sort of fighting. I understand this is terrible to hear from your Lord, but it is the truth."
			wait 4.5 seconds
			send "<light blue>Lord Kiln: Ever since I was a boy, fighting always been frustrating for me. It took years for me to even understand how to wield a sword. Where as my father and Cinder became legendary rulers using their natural talents in combat, I can hardly swing a sword without it dinking off even the lightest of armour."
			wait 3 seconds
			send "<light blue>Lord Kiln: Magic was even more of an issue. After seeing my utter failure to even hold a sword, Zacharias hired a tutor to instruct me in all sorts of magic spells and enchantments. I really think all it did was make me even more confused and frustrated than I already was."
			wait 3.5 seconds
			send "<light blue>Lord Kiln: No matter how hard I have trained, I still feel as weak as a child in battle. It frustrates me to no end."
			wait 3.5 seconds
			send "<light blue>Lord Kiln: It seems I am cursed in terms of combat ability. I feel nigh useless, sitting here in the castle and watching my people suffer. Why, if I were half as strong as my father, I could have ended this war and saved countless lives."
			wait 3.5 seconds
			send "<light blue>Lord Kiln: I feel ashamed of myself. I feel... unworthy of being a Lord. A descendent of Cinder, and the son of the great king Zacharias, can't even wield a sword to save his life. What a great ruler I am..."
			wait 4 seconds
			send "<light blue>Lord Kiln: ...Excuse me, %player's tablist name%<reset><light blue>. I allowed myself to become far too heated just now. As fate would have it, the one aspect I inherited from my father is his fiery disposition rather than any of his combat talents."
			wait 4.5 seconds
			send "<light blue>Lord Kiln: Are there any other questions you have for me?"
			wait 2.5 seconds
			send "<run command:/conv-invt 7><gold>1 - What about your family's Cobalt Blade? Isn't it still here in the castle?"
			send "<run command:/conv-invt 4><gold>3 - Don't be so hard on yourself. You're only human, you can't be perfect."
			send "<run command:/conv-invt 11><gold>4 - I think now is a good place to stop."
		else if arg 1 is 11:
			send "<light blue>Lord Kiln: Agreed. I am sorry for lashing out at you."
			wait 2.5 seconds
			send "<light blue>Lord Kiln: Though, I must admit that I feel somewhat more relieved having talked to someone about it. Thank you."
			wait 3.5 seconds
			send "<light blue>Lord Kiln: Here. I would like you to have this. Consider it an apology for my rude behavior, and go forth on your journey with my blessings."
			wait 3.5 seconds
			set {_reward} to bestWeapon(player)
			if {_reward} is 1:
				give 1 iron sword of sharpness 3 named "<light blue>Silver Sword" with lore "<light red><bold>Slot A - Empty", "<light blue><bold>Slot B - Empty", "<light yellow><bold>Slot C - Empty", "<light green><bold>Assist - Empty", "<light purple><bold>Special - Empty", "<white><bold>Refine - Unrefined", "<white>A rather expensive sword typically handed out as a rare gift from a lord.", "<white>This one has come from Lord Kiln of House Silgrid." to the player
				send "<green>Silver Sword obtained!"
			else if {_reward} is 2:
				give 1 iron axe of sharpness 3 named "<light blue>Silver Axe" with lore "<light red><bold>Slot A - Empty", "<light blue><bold>Slot B - Empty", "<light yellow><bold>Slot C - Empty", "<light green><bold>Assist - Empty", "<light purple><bold>Special - Empty", "<white><bold>Refine - Unrefined", "<white>A rather expensive axe typically handed out as a rare gift from a lord.", "<white>This one has come from Lord Kiln of House Silgrid." to the player
				send "<green>Silver Axe obtained!"
			else if {_reward} is 3:
				give 1 iron shovel of sharpness 4 named "<light blue>Brave Lance" with lore "<light red><bold>Slot A - Empty", "<light blue><bold>Slot B - Brave Blade", "<light yellow><bold>Slot C - Empty", "<light green><bold>Assist - Empty", "<light purple><bold>Special - Empty", "<white><bold>Refine - Unrefined", "<white>A special lance that trades attack power for unparalleled speed." to the player
				send "<green>Brave Lance obtained!"
			else:
				add 175 to the player's balance
				send "<green>175 gold obtained!"
			setQuestProgress(player,"Invisible Ties",2,"Lord Kiln will remember this conversation.")
		else if arg 1 is 12:
			if {quests.%player%::Invisible Ties} is 2:
				send "<light blue>Lord Kiln: ...I've just been wondering about what Cinder told me. About the Cobalt Blade."
				wait 4.5 seconds
			else:
				send "<light blue>Lord Kiln: I must admit something to you... I lied to Cinder about being able to wield the Cobalt Blade."
				wait 4.5 seconds
				send "<light blue>Lord Kiln: I've never been able to wield it... It shames me to this day, that I can't wield my family's own Holy Weapon."
				wait 4.5 seconds
			send "<light blue>Lord Kiln: When I was younger, my father would tell me all sorts of stories about his battles with that sword at his side."
			wait 4.5 seconds
			send "<light blue>Lord Kiln: But I'm not able to wield the sword. If the Cobalt Blade followed the same rules as the other Holy Weapons, anyone of Cinder's bloodline would be able to wield it..."
			wait 6 seconds
			send "<light blue>Lord Kiln: ...Was my father a liar? What reason would he have for lying to me about the sword? It just doesn't make sense..."
			wait 4.5 seconds
			send "<run command:/conv-invt 13><gold>1 - Maybe he didn't want you to know the truth."
		else if arg 1 is 13:
			send "<light blue>Lord Kiln: But, why would he make so much of an effort to conceal it? He told everyone the same stories of valor and heroics... Why would he lie to so many people?"
			wait 6.5 seconds
			send "<run command:/conv-invt 14><gold>1 - Maybe he was as ashamed as you are about it?"
			send "<run command:/conv-invt 14><gold>2 - Maybe he was afraid of being seen as weak."
		else if arg 1 is 14:
			send "<light blue>Lord Kiln: Maybe... Maybe you're right. Father was Cinder's first heir, after all. If the people knew that he was unable to wield Cinder's Cobalt Blade, there's no telling how much of an uproar there would have been."
			wait 6 seconds
			send "<light blue>Lord Kiln: The people would have questioned so much about him... Questioning if he was even Cinder's son. If he was worthy of inheriting the throne."
			wait 6 seconds
			send "<light blue>Lord Kiln: I understand now. Father and I have more in common than I thought... Once again you've proven to be more than just a knight, %player's tablist name%<reset><light blue>... You're a true friend."
			wait 6 seconds
			send "<light blue>Lord Kiln: I might not be as strong of a fighter as my father, nor as talented as Cinder... But if I work hard, I might become more like them."
			wait 5 seconds
			send "<light blue>Lord Kiln: I promise that I will work even harder to be more worthy of the throne I inherited. One day, I will be worthy of being called the Lord of House Silgrid."
			setQuestProgress(player,"Invisible Ties",3,"Lord Kiln will remember this conversation.")
		else if arg 1 is 15:
			setQuestProgress(player,"Invisible Ties",5,"Lord Kiln may now follow you on your journey. Use /follower for more information.")
			send "<gold><bold>NOTICE: For gameplay reasons, a duplicate copy of Lord Kiln will remain at the castle for other players to complete quests. Please understand that this is not a bug, and is instead an intended feature."
			wait 7 seconds
			make player execute command "/npc sel 374"
			make player execute command "/npc copy"
			make player execute command "/npc tphere"
			make player execute command "/sentinel guard %player%"
			loop 10 times:
				send " "
			send "<light blue>Lord Kiln: I am ready for combat. If you would like me to begin accompanying you, please tell me."
			wait 6 seconds
			make player execute command "/follower recruit ""Lord Kiln"""
			
command /recruitkiln:
	trigger:
		make player execute command "/npc sel 374"
		make player execute command "/npc copy"
		make player execute command "/npc tphere"
		make player execute command "/sentinel guard %player%"
		send "<light blue>Lord Kiln: I am ready for combat. If you would like me to begin accompanying you, please tell me."
		make player execute command "/follower recruit ""Lord Kiln"""
			
command /scarland <number>:
	description: A Scarred Land quest dialouge tree
	trigger:
		if {quests.%player%::A Scarred Land} is 1:
			if arg 1 is 1:
				send "<light cyan>Lord Kiln: Thank you, %player's tablist name%<reset><light cyan>. Here, take this boat with you. It will help you cross the sea safely."
				give 1 oak boat to the player
				send "<gold>Boat gained!"
				wait 3 seconds
				setQuestProgress(player,"A Scarred Land",2,"Investigate the Northern Isles.")
				send "<light cyan>Lord Kiln: Good luck, %player's tablist name%<reset><light cyan>. May the Great Heroes light your path."
			else if arg 1 is 2:
				send "<light cyan>Lord Kiln: Forgive my sternness, but you would do best to remember that you are a Knight of Silgrid. You serve your house and your lord before yourself. Investigate the Northern Isles and report to me when you have confirmed the state of its people."
				wait 4 seconds
				send "<light cyan>Lord Kiln: ...I suppose you will also need some sort of encouragement. Here, 50 gold pieces for your trouble."
				add 50 to the player's balance
				send "<gold>$50 gained!"
				wait 2 seconds
				setQuestProgress(player,"A Scarred Land",2,"Investigate the Northern Isles.")
				send "<light cyan>Lord Kiln: Good luck, %player's tablist name%<reset><light cyan>. May the Great Heroes light your path."
		else if {quests.%player%::A Scarred Land} is 3:
			if arg 1 is 3:
				send "<light cyan>Lord Kiln: This... is grave news. Our forces are already spread thin as it is. How could we even begin to protect the Isles when we can hardly guard our own land?"
				wait 5 seconds
				send "<light cyan>Lord Kiln: I must figure this out on my own. Thank your for assisting me, %player's tablist name%<reset><light cyan>. Here is some gold for your efforts."
				wait 2.5 seconds
				add 100 to the player's balance
				send "<gold>$100 gained!"
				wait 2.5 seconds
				send "<light cyan>Lord Kiln: Before you return home, there is something else I must ask of you. I understand that you are new to these lands, and you may not be fully familiar with its history. There is a book in the Great Library that should help you learn about Silgrund, I believe it's called ""The Legends of Silgrund"". I advise you read it when you have a chance."
				wait 10 seconds
				startQuest(player,"A History Lesson","Find the book titled ""Legends of Silgrund"" inside the Great Library.")
				wait 6 seconds
				finishQuest(player,"A Scarred Land","+1 XP Level gained.")
				wait 6 seconds
				make player execute command "/xp 1l"
				
				
#final boss killed
command /chelmundkilled:
	trigger:
		send "UNFINISHED"
					
command /easternisles <number>:
	description: The Northern Isles quest dialouge tree
	trigger:
		if {quests.%player%::A Scarred Land} is 2:
			if arg 1 is 1:
				send "<light cyan>It's good to meet you, %player's tablist name%<reset><light cyan>! It's an honor to meet a Knight of Silgrid like yourself. Anyways, we're not doing too well out here. Our village is attacked by terrible monsters every night, and we can barely afford to keep our guards armed." to the player
				wait 7 seconds
				send "<light cyan>We think the cause might be related to this strange structure that suddenly appeared nearby. It looks like a boulder, but there's terrible groans coming out of it during the day. Hey, since you're a Knight of Silgrid, do you think you could take a look at it for us? We'll be sure to scrounge up a reward for you." to the player
				wait 7 seconds
				send "<run command:/easternisles 4><gold>1- Of course. It is my duty as a knight to aid the people. I'll see what I can do about this strange boulder." to the player
				send "<run command:/easternisles 5><gold>2- I'm incredibly busy right now. I'll be sure to investigate it as soon as I can." to the player
			else if arg 1 is 2:
				send "<light cyan>It's good to meet you, %player's tablist name%<reset><light cyan>! Anyways, we're not doing too well out here. Our village is attacked by terrible monsters every night, and we can barely afford to keep our guards armed." to the player
				wait 4 seconds
				send "<light cyan>We think the cause might be related to this strange structure that suddenly appeared nearby. It looks like a boulder, but there's terrible groans coming out of it during the day. Hey, if Lord Kiln sent you, then you must be one of his knights! Do you think you could take a look at that boulder for us? We'll be sure to scrounge up a reward for you." to the player
				wait 4 seconds
				send "<run command:/easternisles 4><gold>1- Sure. I'll see what I can do about this strange boulder." to the player
				send "<run command:/easternisles 5><gold>2- I'm busy right now. I'll investigate it later when I have the time." to the player
			else if arg 1 is 3:
				send "<light cyan>Hey, no need to be rude! I was just saying. Anyways, we're not doing too well out here. Our village is attacked by terrible monsters every night, and we can barely afford to keep our guards armed." to the player
				wait 3 seconds
				send "<light cyan>We think the cause might be related to this strange structure that suddenly appeared nearby. It looks like a boulder, but there's terrible groans coming out of it during the day. Hey, if Lord Kiln sent you, then you must be a knight! Do you think you could take a look at that boulder for us? We'll be sure to scrounge up a reward for you." to the player
				wait 4 seconds
				send "<run command:/easternisles 4><gold>1- Fine. I'll see what I can do about this strange boulder." to the player
				send "<run command:/easternisles 6><gold>2- I'm busy. Find someone else to fix your problem for you." to the player
			else if arg 1 is 4:
				send "<light cyan>Thank you! We're in your debt. Head to the edge of town, and you'll find the boulder. You can't miss it." to the player
				setQuestProgress(player,"A Scarred Land",3,"Return to Lord Kiln with the information about Colony 9.")
				wait 3 seconds
				startQuest(player,"A Villager's Request","Investigate the boulder on the outskirts of Colony 9.")
			else if arg 1 is 5:
				send "<light cyan>Oh. I was hoping you could've helped out, seeing as you're a Knight of Silgrid and all. We'll see if we can do something about it on our own, but if you ever want to help just head to the edge of town to find the boulder." to the player
				setQuestProgress(player,"A Scarred Land",3,"Return to Lord Kiln with the information about Colony 9.")
				wait 3 seconds
				startQuest(player,"A Villager's Request","Investigate the boulder on the outskirts of Colony 9.")
			else if arg 1 is 6:
				send "<light cyan>What's with the attitude? I hope Lord Kiln gives you a punch to the gut when you come back to him. We'll fix the problem on our own." to the player
				setQuestProgress(player,"A Scarred Land",3,"Return to Lord Kiln with information about Colony 9.")
				wait 3 seconds
				failQuest(player,"A Villager's Request","You angered the residents of Colony 9. Investigating the boulder won't do any good now.")
				
command /conv-avr <number>:
	trigger:
		if {quests.%player%::A Villager's Request} is 2:
			if arg 1 is 1:
				send "<light cyan>A summoning table? That's strange... Now I'm just left wondering how all of that got there in the first place. Thank you for your help. I know this isn't much, but the colony came together to make this for you." to the player
			else if arg 1 is 2:
				send "<light cyan>Really? I guess that boulder really was the source of the monsters. You deserve a great reward for your hard work. Here, take this."
			else if arg 1 is 3:
				send "<light cyan>One of the sources? The problems just never end out here, do they? Anyways, you've been a great help for us out here. We've made this for you: It's not much, but we hope it'll be useful to you."
			wait 5 seconds
			set {_reward} to bestWeapon(player)
			if {_reward} is 1:
				send "<green>Steel Sword obtained!" to the player
				give 1 iron sword of sharpness 1 named "<light cyan>Steel Sword" to the player
			else if {_reward} is 2:
				send "<green>Steel War Axe obtained!" to the player
				give 1 iron axe of sharpness 1 named "<light cyan>Steel War Axe" to the player
			else if {_reward} is 3:
				send "<green>Steel Lance obtained!" to the player
				give 1 iron shovel of sharpness 1 named "<light cyan>Steel Lance" to the player
			else if {_reward} is 4:
				send "<green>Steel Bow obtained!" to the player
				give 1 bow of power 1 named "<light cyan>Steel Bow" to the player
			else if {_reward} is 5:
				send "<green>Elthunder tome obtained!" to the player
				give 1 book named "<light yellow>Elthunder" with lore "","","","","","","<white>Right-click to cast the spell Elthunder.","<white>Uses left:","120" to the player
			else if {_reward} is 6:
				send "<green>Imbue staff obtained!" to the player
				give 1 iron hoe named "<light yellow>Imbue" with lore "<white>Right-click to restore an ally's health." to the player
			wait 1.5 seconds
			finishQuest(player,"A Villager's Request","")
			
command /conv-fftf <number>:
	trigger:
		if {quests.%player%::Fuel for the Fire} is not set:
			if arg 1 is 1:
				send "<light cyan>The refineries take a large amount of fuel to run, and with all of the monsters running around it's becoming hard to send and receive shipments. Without enough fuel, I'll have to close down the refinery for good."
				wait 4 seconds
				send "<run command:/conv-fftf 2><gold>1 - Maybe I can help with that." to the player
				send "<run command:/conv-fftf 3><gold>2 - That's a shame." to the player
			else if arg 1 is 2:
				send "<light cyan>You think so? I was supposed to recieve a shipment from Colony 6, but I can only assume they were ambushed and got lost. The Dark Forest close to the desert is no doubt filled with monsters. I would start your search there."
				startQuest(player,"Fuel for the Fire","Find the shipment from Colony 6.")
				wait 5 seconds
				send "<light cyan>The shipment should've included a large lump of coal and hardened magma, if that can help you find it." to the player
			else if arg 1 is 3:
				send "<light cyan>Aye, it is. I'm hoping that once these monsters are dealt with things can get back to normal." to the player
		else if {quests.%player%::Fuel for the Fire} is not 999:
			if arg 1 is 4:
				send "<light cyan>I figured as much. That's a shame, I was looking forward to that shipment."
				wait 3.5 seconds
				send "<light cyan>Though, if you're ever in the mines and come across some fuel, I would pay a good price for it."
				wait 3.5 seconds
				setQuestProgress(player,"Fuel for the Fire",3,"Find 64 Coal and 16 Magma Blocks for the refinery.")
			else if arg 1 is 5:
				send "<light cyan>You... you really did find the fuel? By the Greats, this is wonderful news. I'll reopen the refinery as soon as I can. Here, some gold for your trouble."
				remove 64 coal from the player's inventory
				remove 16 magma block from the player's inventory
				wait 4 seconds
				add 175 to the player's balance
				send "<gold>175 gold obtained!"
				finishQuest(player,"Fuel for the Fire","The Weapon Refinery is now available.")
				
command /conv-stl <number>:
	trigger:
		if {quests.%player%::Seeking the Light} is 1:
			if arg 1 is 1:
				send "<light cyan>Riis: The Holy Weapons of Silgrund... There have never been finer pieces of steel ever made. What do you wish to know about them?"
				wait 3 seconds
				send "<run command:/conv-stl 3><gold>1 - I'm searching for the lost Holy Weapons, I think we can use them to fight back against the monster outbreak. Do you know where I can find one?"
				send "<run command:/conv-stl 5><gold>2 - Who made the Holy Weapons?"
				send "<run command:/conv-stl 4><gold>3 - What made the Holy Weapons so special?"
			else if arg 1 is 3:
				send "<light cyan>Riis: Now hold your horses there, young one. I can't just tell anyone where a Holy Weapon might be. I need some form of proof that you're searching for them for the right reason."
				wait 5 seconds
				send "<run command:/conv-stl 2><gold>I'm a Knight of Silgrid. Lord Kiln and I are searching for a way to stop the monster outbreak, and we think the Holy Weapons are what we need."
				send "<run command:/conv-stl 2><gold>I'm on an urgent mission from Lord Kiln of House Silgrid. We need to find the Holy Weapons to stop the monster outbreak."
			else if arg 1 is 5:
				send "<light cyan>Riis: Ah, I believe you're asking about Cinder. He used to rule Gallia, with the people referring to him as the Blazing Lord due to his fondness for fire magic."
				wait 4 seconds
				send "<light cyan>Riis: Long ago, Helmund from the shadowed lands of Elrid attempted to invade our realm with an army of necromancers at his side."
				wait 4 seconds
				send "<light cyan>Riis: After learning of the loss of his dear friend Alstair at Helmund's hands, Cinder used all of his magical prowess to forge the Holy Weapons."
				wait 4 seconds
				send "<light cyan>Riis: Unfortunately, the effort of creating the Holy Weapons would take Cinder's life. The weapons would go on to be used to drive back Helmund's forces and seal away Elrid."
				wait 4 seconds
				send "<light cyan>Riis: Cinder's son, Zacharias, would go on to prove himself worthy of inheriting his father's throne. Some would argue that his abilities with a sword were almost as great as Alstair himself."
				wait 4 seconds
				send "<light cyan>Riis: The same cannot be said for his son Kiln, however. Don't tell him I said that, but it's the truth: he'll never be fit for combat."
				wait 4 seconds
				send "<run command:/conv-stl 3><gold>1 - Thank you for the information. Do you know where one of the Holy Weapons might be?"
				send "<run command:/conv-stl 4><gold>2 - What made the Holy Weapons so special?"
			else if arg 1 is 4:
				send "<light blue>Riis: The Holy Weapons had incredibly powerful enchantments placed upon them by Cinder, the Blazing Lord."
				wait 4 seconds
				send "<light blue>Riis: These enchantments were far from anything one could muster at an enchantment table. No, these weapons were capable of shattering the sky in a single strike."
				wait 4 seconds
				send "<light blue>Riis: It's impossible to tell exactly what made them powerful, as each weapon was tailored to its wielder."
				wait 4 seconds
				send "<light blue>Riis: Additionally, each weapon was soulbound to its original wielder. Though if one were to have either the talent or the appropriate blood flowing through them, they would most likely be able to wield one of the weapons."
				wait 4 seconds
				send "<run command:/conv-stl 3><gold>1 - Thank you for the information. Do you know where one of the Holy Weapons might be?"
				send "<run command:/conv-stl 5><gold>2 - Who made the Holy Weapons?"
			else if arg 1 is 2:
				send "<light cyan>Riis: Lord Kiln... yes, I remember delivering the few Holy Weapons we still had the location of to his castle."
				wait 3.5 seconds
				send "<light cyan>Riis: I assume that since you're asking about their location, that means they've been stolen."
				wait 3 seconds
				send "<light cyan>Riis: Fortunately for you and Lord Kiln, there's a group of thieves who made a big show about taking over an old castle with what they claim is one of the lost weapons."
				wait 4 seconds
				send "<light cyan>Riis: I believe he's situated somewhere in the Yied Desert. If you hurry, you may be able to reclaim the weapon he stole. That is, if it is even a real Holy Weapon."
				setQuestProgress(player,"Seeking the Light",2,"Find the thieves holding a Holy Weapon inside the Yied Desert.")
		else if {quests.%player%::Seeking the Light} is 3:
			if arg 1 is 6:
				send "<light blue>Lord Kiln: It's true... all of grandfather's enchantments are gone... Even he has faded into history..."
				wait 4.5 seconds
				send "<light blue>Lord Kiln: ..."
				wait 2 seconds
				send "<light blue>Lord Kiln: I have one more idea. The Heroes' Guild. The Great Heroes once trained there before joining Cinder's army. You might be able to find something to revive Mystletainn there."
				wait 4.5 seconds
				send "<light blue>Lord Kiln: You must hurry. We can't afford to lose any more time. You can find the Heroes' Guild near the outskirts of Colony 5, in the Northern Isles."
				startQuest(player,"Greats Guide You","Search the Heroes' Guild near Colony 5 for anything you can use to revive the Holy Weapons.")
				wait 6 seconds
				finishQuest(player,"Seeking the Light","")
				
command /conv-aap <number>:
	trigger:
		if {quests.%player%::An Apprentice's Plight} is not set:
			if arg 1 is 1:
				send "<light blue>Jerome: I'm supposed to be making a set of iron tools for Galdur. The only problem is, I've almost used up all of my metal trying to make the perfect set of tools for him."
				wait 4.5 seconds
				send "<light blue>Jerome: *sigh*... I need this job. If I can't get these tools made, then Galdur will fire me for sure. And the last thing I want to do is join the Colony Guard with all of the monsters running around."
				wait 5.5 seconds
				send "<run command:/conv-aap 3><gold>1 - Is there some way I can help you?"
				send "<run command:/conv-aap 2><gold>2 - Good luck. It sounds like you need it."
			else if arg 1 is 2:
				send "<light blue>Jerome: Thank you. Now please, try not to bother me again. I have to focus..."
			else if arg 1 is 3:
				send "<light blue>Jerome: Well, there is one way. If you can bring me some spare materials, it should give me enough leeway to get these tools made to perfection."
				wait 3.5 seconds
				send "<light blue>Jerome: 14 iron ingots and 11 sticks should be enough. I would fetch them myself, but if Galdur sees me running off he'll suspect something's up."
				startQuest(player,"An Apprentice's Plight","Bring 14 iron ingots and 11 sticks to Jerome.")
				wait 3.5 seconds
				send "<light blue>Jerome: Good luck, I'm counting on you."
			else if arg 1 is 4:
				send "<light blue>Jerome: Thanks. I'm going to need it if I want to keep this job."
		else if arg 1 is 5:
			send "<light blue>Jerome: Come on, don't leave me hanging like this! I just need 14 iron ingots and 11 sticks."
		else if arg 1 is 6:
			send "<light blue>Jerome: Oh, thank you! I might actually keep my job now. Here, this was my pay for last week, but I think you deserve it now."
			send "<light red>14 iron ingots and 11 sticks lost."
			remove 14 iron ingots from the player's inventory
			remove 11 sticks from the player's inventory
			wait 1 seconds
			send "<light green>175 gold obtained!"
			finishQuest(player,"An Apprentice's Plight","+175 gold and 2 XP levels obtained.")
			wait 6 seconds
			make player execute command "/xp 2l"
			wait 6 seconds
			send "<light blue>Jerome: Oh, if you're ever in town and need something repaired, I'd be willing to give you a discount to do it. It's the least I can do for you."
		else if arg 1 is 7:
			send "<light blue>Jerome: Yes, actually. That last bit of iron went a long way towards winning over that old smith."
			wait 3 seconds
			send "<light blue>Jerome: Thanks again for helping me. You saved me from getting sent off to guard duty, and got me a raise to boot!"
			
command /conv-potg <number>:
	trigger:
		if {quests.%player%::Path of the Greats} is 1:
			if arg 1 is 1:
				send "<light cyan>Jorund: Lord Kiln... Haven't heard that name in a long while."
				wait 3 seconds
				send "<light cyan>Jorund: I don't know why he thinks I can teach you to wield a Holy Weapon, but I suppose if you've come all the way here I can at least teach you something."
				wait 4 seconds
				send "<light cyan>Jorund: Now most trainers will tell you to spend all day whacking a training dummy to improve your swordplay. The truth is, you need to learn how to use your weapon's skills to succeed."
				wait 5.5 seconds
				loop all items in the player's inventory:
					if the lore of the loop-item contains "Slot":
						set {_skills} to 1
						set {_weapon} to the name of the loop-item
				if {_skills} is 1:
					send "<light cyan>Jorund: Looks like your %{_weapon}%<reset><light cyan> already has some skills on it. Good, that will make things easier for us."
					wait 3 seconds
				send "<light cyan>Jorund: Every weapon can have a set of Skills on it: An A,B,C,Assist, Special, and Refine."
				wait 4.5 seconds
				send "<light cyan>Jorund: A-Slot skills are your main abilities. Death Blow, Armour Smashers, and the like determine the main trait of your weapon."
				wait 5.5 seconds
				send "<light cyan>Jorund: B-Slot skills augment your weapon with smaller effects. Wrath, for example, will boost the power of your Special skills when you're backed into a corner."
				wait 5.5 seconds
				send "<light cyan>Jorund: C-Slot skills help you strengthen allies and weaken your foes. If you're adept enough in magic, then picking a weakening skill like Pressure STR will be a good choice."
				wait 6 seconds
				send "<light cyan>Jorund: Assist skills help command your allies during battle, either with positioning skills or stat buffs."
				wait 6 seconds
				send "<light cyan>Jorund: Now Special skills are the most fun. They give you a large boost in damage, or reduce the damage you take in battle. The only downside is that they can be unreliable, and not activate when you need them to."
				wait 6.5 seconds
				send "<light cyan>Jorund: Last, we have refines. You can get these from a weapon refinery, a blacksmith can help you with that. With a refine, you can further increase your weapon's abilities with small adjustments, like more damage or accelerating your Special activation."
				wait 6.5 seconds
				if {_skills} is 1:
					send "<light cyan>Jorund: Since you've got a weapon with skills on it already, I'll give you a combat manual to apply a new skill to it. This one is called Death Blow, it'll increase your strength when you start combat."
					wait 3.5 seconds
					send "<gold>Combat Manual (Death Blow) obtained!"
					give 1 book named "<light red>Combat Manual" with lore "<light red><bold>Slot A - Death Blow" to the player
					setQuestProgress(player,"Path of the Greats",2,"Slay 10 monsters using a weapon with Skills equipped.")
					wait 1 second
					send "<light cyan>Go out and see what you can do with your skills. Come back when you've killed some monsters."
				else:
					send "<light cyan>Since you don't have a weapon with any skills on it, I'll let you have one of mine... If you pay, of course."
					wait 3.5 seconds
					send "<run command:/conv-potg 2><gold>1 - I'll buy the weapon. (100 gold)"
					send "<run command:/conv-potg 3><gold>2 - I'll pass."
			else if arg 1 is 2:
				send "<light cyan>Jorund: Good doing business with you. Here's the sword."
				wait 2 seconds
				send "<gold>100 gold lost."
				send "<gold>Iron Sword (Death Blow) obtained."
				give 1 iron sword named "<light blue>Iron Sword" with lore "<light red><bold>Slot A - Death Blow" to the player
				wait 2 seconds
				setQuestProgress(player,"Path of the Greats",2,"Slay 10 monsters using a weapon with Skills equipped.")
				send "<light cyan>Go ahead and see what you can do with it. The A Skill on this sword is called Death Blow, it'll boost your strength when you start combat."
			
command /quests-buyhw <number>:
	trigger:
		if arg 1 is 1:
			send "<light blue>Bramimund: Yes, I believe I am. Why are you asking me this?"
			wait 3 seconds
			send "<light yellow>Cinder: Greetings, Bramimund. You may not recognize my voice, but I am Cinder, the one you know as the Blazing Lord."
			wait 5 seconds
			send "<light blue>Bramimund: Where did that come from? Are you playing some sort of trick on me?"
			wait 4 seconds
			send "<light yellow>Cinder: This is no trick, I assure you. My friend %player's tablist name%<reset><light yellow> needs your assistance in tracking down my weapons."
			wait 6 seconds
			send "<light blue>Bramimund: I don't care what you've come here for. You've interrupted my studies to play petty tricks on me. Now, go awa-"
			wait 4.5 seconds
			strike lightning effect at the player
			send "<light yellow>Cinder: That would be unwise of you, Bramimund. A shame, I was hoping the one to succeed my title as the land's greatest sorcerer would more highly value the words of his superior."
			wait 7 seconds
			send "<light blue>Bramimund: Fine. What do you want my help for?"
			wait 3 seconds
			send "<light yellow>Cinder: I need someone with enough magical power that they can locate my weapons. I believe your people call them the Holy Weapons now, no?"
			wait 6 seconds
			send "<light yellow>Cinder: I will teach you everything you need to know to locate whatever weapons %player's tablist name%<reset><light yellow> needs. All you must do is provide him your aid."
			wait 6 seconds
			send "<light blue>Bramimund: ...Very well. Show me whatever it is you have to teach, Cinder. Though I cannot guarantee I will help-"
			wait 5 seconds
			strike lightning effect at the player
			send "<light yellow>Cinder: So much resistance... %player's tablist name%<reset><light yellow>, I'm becoming frustrated with this man. Not even the idea of tutoring from the greatest sorcerer in history can tempt this bag of skin and bones. Perhaps we could dispose of him and search elsewhere?"
			wait 7.5 seconds
			send "<light blue>Bramimund: Fine, fine! I'll help the two of you. All I ask is that I be compensated for this."
			wait 4 seconds
			send "<light yellow>Cinder: Excellent. I'm certain that the two of you can determine what the appropriate compensation will be on your own. Now, allow me to instruct the old man so he'll be useful for once..."
			finishQuest(player,"The Wizard of House Silgrid","Bramimund can now summon depleted Holy Weapons for you... for a fee.")

command /conv-dot <number>:
	trigger:
		if arg 1 is 1:
			failQuest(player,"Days of Training","You skipped your training. Knowledge is power, and you've refused to gain it.")
			failQuest(player,"Home Sweet Home","Unfortunately for you, Lord Kiln doesn't give handouts to the homeless.")
			failQuest(player,"Proving Grounds","You really shouldn't even be able to see this.")
			startQuest(player,"A Scarred Land","")
			send "<light cyan>Lord Kiln: Ah, eager to start, are we? Excellent. It has been a long while since the Knights have had someone of your eagerness join us."
			wait 4.5 seconds
			send "<light cyan>Lord Kiln: I'm certain you already know by now, but recently these lands have been terrorized by undead monsters. While we are managing to stave off their attacks, I fear that our allies in the north may not be as well off."
			wait 6 seconds
			send "<light cyan>Lord Kiln: Ever since their leader, the Obsidian Knight Alstair, was slain, the Northern Isles have been in complete disarray. Silgrid depends upon the resources there, however, and if we were to lose our allies in the Northern Isles it would spell great trouble for the citizens here in the Southern Plains."
			wait 7.5 seconds
			send "<light cyan>Lord Kiln: Thus begins your role in this dilemma. Sail to the Northern Isles, and locate Colony 9. Once you find it, ask her residents of their current state of affairs. Then, return the information to me."
			wait 6.5 seconds
			send "<run command:/scarland 1><gold>1 - Understood. I'll make my way there right now."
			send "<run command:/scarland 2><gold>2 - I feel as though my skills would be better applied in combat. Maybe consider hiring a courier."
			
			
on right click on an entity:
	if the target is npc:
		#
		#Lord Kiln
		if the name of the target contains "Kiln":
			if {quests.%player%::Days of Training} is 1:
				send "<light cyan>Lord Kiln: Oh, pardon me. Are you one of the new recruits?" to the player
				wait 3 seconds
				send "<run command:/conv-dot 1><gold>1 - Yes, and I'm ready to serve you. Do you have any missions for me, milord? (Skips tutorial quests)" to the player
				send "<run command:/conv-dot 2><gold>2 - Yes, but I seem to be lost. Could you point me towards the training grounds?" to the player
			if {quests.%player%::A Scarred Land} is not 999:
				if {quests.%player%::A Scarred Land} is 1:
					send "<light cyan>Lord Kiln: Ah, <reset>%player's tablist name%<reset><light cyan>! There you are. Come, I must speak with you urgently." to the player
					wait 3.25 seconds
					send "<light cyan>Lord Kiln: I'm certain that you are aware by now how aggressive the undead menace has become." to the player
					wait 3.5 seconds
					send "<light cyan>Lord Kiln: Their forces grow stronger by the day, and now I fear for the lives of not just those inside this castle, but of our allies in the north." to the player
					wait 3.75 seconds
					send "<light cyan>Lord Kiln: Forgive me for the short notice, but it seems I am in need of your help already." to the player
					wait 3 seconds
					send "<light cyan>Lord Kiln: Sail to the Northern Isles and find out how the people fare. An orange lighthouse will mark your arrival." to the player
					wait 3.5 seconds
					send "<run command:/scarland 1><gold>1 - Understood." to the player
					send "<run command:/scarland 2><gold>2 - I'm busy right now. Is there someone else who can go instead?" to the player
				else if {quests.%player%::A Scarred Land} is 2:
					send "<light cyan>Lord Kiln: Please, you must hurry to the Northern Isles." to the player
				else if {quests.%player%::A Scarred Land} is 3:
					send "<light cyan>Lord Kiln: %player's tablist name%<reset><light cyan>! You've returned! Tell me, how are the people of the Northern Isles?" to the player
					wait 2 seconds
					send "<run command:/scarland 3><gold>1 - I stumbled upon a place called Colony 9. A villager said their settlement is being attacked by the same monsters near House Silgrid." to the player
			else if {quests.%player%::A History Lesson} is 1:
				send "<light cyan>Lord Kiln: Are you having trouble finding the book? I understand. The Great Library can be very overwhelming. Try the bookshelves near the window you see as you climb the central staircase." to the player
			else if {quests.%player%::A History Lesson} is 2:
				send "<light cyan>Lord Kiln: Ah, %player's tablist name%<reset><light cyan>. What is that I can help you with?" to the player
				wait 3.5 seconds
				send "%player's tablist name%: <reset><gold>I've read the Legends of Silgrund. I want to find the Holy Weapons to try and stop the monsters that are popping up everywhere." to the player
				wait 4.5 seconds
				send "<light cyan>Lord Kiln: The Holy Weapons of Silgrund? I'm sorry, %player's tablist name%<reset><light cyan>, but I'm afraid they've been lost to the ages." to the player
				wait 4 seconds
				send "%player's tablist name%: <reset><gold>How? I thought the weapons were moved to the castle years ago." to the player
				wait 4 seconds
				send "<light cyan>Lord Kiln: They were. But unfortunately thieves have raided the caskets in search of the weapons on multiple occasions. If any of the weapons are left, they are not the ones the Great Heroes used long ago." to the player
				wait 5 seconds
				send "<light cyan>Lord Kiln: ...but I know better than to shoo you away when you have that fire in your eyes. I can see that you're very passionate about finding the Holy Weapons. Admittedly, I too would be interested in seeing how they could be used to stop this undead menace terrorizing our lands." to the player
				wait 5 seconds
				send "<light cyan>Seek a man named Riis in the Northern Isles, inside Colony 6. If anyone should know of the weapons' whereabouts, it would be him." to the player
				wait 5 seconds
				finishQuest(player,"A History Lesson","")
				wait 6 seconds
				startQuest(player,"Seeking the Light","Ask Riis of the Northern Isles about the locations of the Holy Weapons.")
			else if {quests.%player%::Seeking the Light} is 1:
				send "<light cyan>Lord Kiln: Riis was one of the sages who oversaw the delivery of the Holy Weapons to the castle. If anyone should know where they are, it would be him." to the player
			else if {quests.%player%::Seeking the Light} is 2:
				send "<light cyan>Lord Kiln: The Yied Desert? Be careful, %player's name%<reset><light cyan>. You'll never find a more wretched hive of scum and thievery than what's contained inside those dunes." to the player
			else if {quests.%player%::Seeking the Light} is 3:
				send "<light cyan>Lord Kiln: %player's tablist name%<reset><light blue>... You've found one of the weapons?" to the player
				wait 3 seconds
				send "<run command:/conv-stl 6><gold>1 - I've recovered Mystletainn, but it doesn't seem to have any of the enchantments it had in the history books." to the player
			else if {quests.%player%::Greats Guide You} is 2:
				send "<light blue>Lord Kiln: You've returned, and that grim look upon your face tells me the news is grave." to the player
				wait 4.5 seconds
				send "<run command:/conv-ggy 1><gold>1 - Apart from this gemstone, I couldn't find anything inside the Guild." to the player
			else if {quests.%player%::Path of the Greats} is not set:
				if {quests.%player%::Seeking the Light} is 999:
					send "<light blue>Lord Kiln: %player's tablist name%<reset><light blue>, I must speak with you immediately." to the player
					wait 2.5 seconds
					send "<light blue>Lord Kiln: I understand that you are busy researching the Holy Weapons. However, ny advisor has notified me of a man named Jorund residing in Nifl that may help you unlock the weapon's power." to the player
					wait 3.5 seconds
					send "<light blue>Lord Kiln: You must meet with him as soon as you can. Go now, posthaste! We haven't a second to lose!" to the player
					startQuest(player,"Path of the Greats","Locate Jorund inside Nifl.")
			else if {quests.%player%::Awakening} is 2:
				send "<light blue>Lord Kiln: Ah, %player's tablist name%<reset><light blue>, what is that I can help..." to the player
				wait 4 seconds
				send "<light blue>Lord Kiln: ...Is that...? I... I don't believe it... Mystletainn..." to the player
				wait 4 seconds
				send "<light yellow>Cinder: Hahaha... Even after all this time, those weapons of mine still drop jaws to the floor. This feeling never gets old." to the player
				wait 5 seconds
				send "<light blue>Lord Kiln: ...%player's tablist name%<reset><light blue>? Who was that?" to the player
				wait 3 seconds
				send "<light yellow>Cinder: Your grandfather." to the player
				wait 3 seconds
				send "<light blue>Lord Kiln: ...Grandfather? L-Lord Cinder?!" to the player
				wait 3 seconds
				send "<light yellow>Cinder: Correct, Kiln. It's an honor to finally meet one of my heirs." to the player
				wait 3.5 seconds
				send "<light blue>Lord Kiln: I... I don't know what to say..." to the player
				wait 3.5 seconds
				send "<light yellow>Cinder: I have a question for you, Kiln." to the player
				wait 3.5 seconds
				send "<light blue>Lord Kiln: What is it, grandfather?" to the player
				wait 3.5 seconds
				send "<light yellow>Cinder: First, don't call me that. I have a name for a reason." to the player
				wait 3.5 seconds
				send "<light yellow>Cinder: Second, do you still have the Cobalt Blade?" to the player
				wait 3.5 seconds
				send "<light blue>Lord Kiln: Of course! It's still in your old room." to the player
				wait 3.5 seconds
				send "<light yellow>Cinder: Are you able to wield it?" to the player
				wait 3.5 seconds
				send "<light blue>Lord Kiln: ..." to the player
				wait 2 seconds
				if {quests.%player%::Invisible Ties} is 2:
					send "<light blue>Lord Kiln: %player's tablist name%<reset><light blue>... I should tell him the truth, shouldn't I?" to the player
					wait 4.5 seconds
					send "<light blue>Lord Kiln: No, Cinder... It turns heavy as a rock the moment my hand touches the handle. Forgive me, grandfather... I am unworthy of the blade." to the player
					wait 6 seconds
					send "<light yellow>Cinder: The only thing you should ask me to forgive is calling me grandfather again." to the player
					wait 4 seconds
					send "<light yellow>Cinder: I'll let you in on a secret, Kiln: That blade is locked to me alone. No-one will be able to wield it now." to the player
					wait 5 seconds
					send "<light blue>Lord Kiln: But that's not possible! Zacharias told me so many stories about his deeds with that sword... He wouldn't lie to me. He wouldn't!" to the player
					wait 6 seconds
					send "<light yellow>Cinder: It sounds like your old man was a little liar then. I made sure that blade would only work in my hands. Whatever your father told you, it's not true." to the player
					wait 6 seconds
					send "<light blue>Lord Kiln: Father... a liar? I... I don't..." to the player
					wait 5 seconds
					send "<light yellow>Cinder: ...Well, I'd say that went swimmingly. Now, %player's tablist name%<reset><light yellow>, why don't we go clean my lands of these undead corpses?" to the player
					finishQuest(player,"Awakening","")
					wait 6 seconds
					startQuest(player,"Liberation","Slay 30 monsters using a Holy Weapon.")
				else:
					send "<light blue>Lord Kiln: Of course I can. Any true heir of yours would be able to wield it." to the player
					wait 4.5 seconds
					set {quests.%player%::Invisible Ties} to 3
					send "<light yellow>Cinder: ...Very well. Then I suppose you won't have any trouble helping %player's tablist name%<reset><light yellow> start cleaning up those monsters from Elrid." to the player
					wait 5.5 seconds
					send "<light blue>Lord Kiln: Of course, Cinder. I will help as much as I can..." to the player
					wait 4.5 seconds
					send "<light yellow>Cinder: Well, I'd say that went swimmingly. Now, %player's tablist name%<reset><light yellow>, why don't we go clean my lands of these undead corpses?" to the player
					finishQuest(player,"Awakening","")
					wait 6 seconds
					startQuest(player,"Liberation","Slay 30 monsters using a Holy Weapon.")
			else if {quests.%player%::Threads of Fate} is 1:
				send "<light cyan>Lord Kiln: Ah, %player's tablist name%<reset><light cyan>. What news have you and Cinder brought from Summoner's Sword?" to the player
				wait 3.5 seconds
				send "<light cyan>Lord Kiln: ...I see. My grandfather's spirit is no longer with us... There was much I had hoped to learn from him, but alas." to the player
				wait 6.5 seconds
				send "<light cyan>Lord Kiln: And now, to make matters worse, we know there is a larger entity behind these thrall attacks. There's little chance it could have origins in our lands however, necromancy and other such fell magic has long since died across the realm." to the player
				wait 8.5 seconds
				send "<light cyan>Lord Kiln: Hmm... %player's tablist name%<reset><light cyan>, what did those portal remnants look like? ...A washed-out yellow with green highlights..? But that's the same design of the Elridian portals from the history books..." to the player
				wait 7.5 seconds
				send "<light cyan>Lord Kiln: Then that must mean... Greats help us all..." to the player
				wait 3.5 seconds
				send "<light cyan>Lord Kiln: The Sacred Seal has been broken. Elrid... has been freed." to the player
				wait 4 seconds
				send "<run command:/conv-ahd 1><gold>1 - Elrid?" to the player
				send "<run command:/conv-ahd 2><gold>2 - Is there a way to restore the seal?" to the player
				send "<run command:/conv-ahd 3><gold>3 - ...What should we do now, then?" to the player
			else if {quests.%player%::Threads of Fate} is 2:
				send "<light cyan>Lord Kiln: How may I assist you, %player's tablist name%<reset><light cyan>?" to the player
				wait 3 seconds
				send "<run command:/conv-ahd 4><gold>1 - Can you tell me more about your plan?" to the player
				send "<run command:/conv-ahd 5><gold>2 - I've made my decision." to the player
			else:
				if {quests.%player%::Seeking the Light} is 999:
					if {quests.%player%::Invisible Ties} is not set:
						send "<light cyan>Lord Kiln: Oh, %player's tablist name%<reset><light cyan>. Are you busy currently?" to the player
						wait 1.5 seconds
						send "<run command:/conv-invt 1><gold>1 - No, milord. What do you need?" to the player
						send "<run command:/conv-invt 2><gold>2 - I'm very busy." to the player
				else if {quests.%player%::Liberation} is set:
					if {quests.%player%::Invisible Ties} is less than 4:
						send "<light cyan>Lord Kiln: ...All of the stories father used to tell me... Were they all lies...?" to the player
						wait 4 seconds
						send "<run command:/conv-invt 12><gold>1 - Are you alright, Milord?" to the player
					else if {kilnRecruitable.%player%} is true:						
						send "<light cyan>Lord Kiln: Ah, %player's tablist name%<reset><light blue>! If you need another blade at your side, I am here for you." to the player
						send "<run command:/recruitkiln><gold>1 - Follow me. I need your help." to the player
				else:
					set {_rng} to a random integer from 1 to 5
					if {_rng} is 1:
						send "<light cyan>Lord Kiln: Greetings, %player's tablist name%<reset><light cyan>." to the player
					else if {_rng} is 2:
						send "<light cyan>Lord Kiln: Have you visited the Great Library, %player's tablist name%<reset><light cyan>? It's the most well-stocked library in all of Silgrund." to the player
					else if {_rng} is 3:
						send "<light cyan>Lord Kiln: ...Oh? What do you need?" to the player
					else if {_rng} is 4:
						send "<light cyan>Lord Kiln: Ah, %player's tablist name%<reset><light cyan>! I trust the day has found you well." to the player
					else if {_rng} is 5:
						send "<light cyan>Lord Kiln: I could always use more capable knights. If you encounter anyone you believe would be of use to us, please bring them here." to the player
		
		#Bramimund
		if the name of the target is "Bramimund":
			if {quests.%player%::Awakening} is not set:
				send "<light blue>Bramimund: I would love to stop and chat, but I'm very busy right now. Come back another time." to the player
			else if {quests.%player%::The Wizard of House Silgrid} is 1:
				send "<light blue>Bramimund: Yes, what is it now?" to the player
				wait 3 seconds
				send "<run command:/quests-buyhw 1><gold>1 - I understand you're the High Wizard here?" to the player
			else:
				send "<light blue>Bramimund: Oh, it's you again. I'm assuming you need a Holy Weapon summoned?" to the player
				wait 2 seconds
				send "<run command:/hwbuy HW><gold>1 - I need some Holy Weapons." to the player

		#Combat Instructor
		if the name of the target contains "Combat Trainer":
			if {quests.%player%::Days of Training} is 1:
				send "<light blue>%target's name%: So, you finally made it. Good, we can start your training right now." to the player
				wait 3.5 seconds
				send "<light blue>%target's name%: Let's start with the basics, then. Go ahead and let me see how you handle a weapon. Strike me." to the player
				setQuestProgress(player,"Days of Training",2,"Strike the combat instructor with your weapon.")
			else:
				send "<light blue>%target's name%: Need some training?" to the player
				wait 2 seconds
				send "<run command:/train swords><gold>1 - I need training in swords. (+100 pts for $100)" to the player
				send "<run command:/train axes><gold>2 - I need training in axes. (+100 pts for $100)" to the player
				send "<run command:/train lances><gold>3 - I need training in lances. (+100 pts for $100)" to the player
				send "<run command:/train bows><gold>4 - I need training in bows. (+100 pts for $100)" to the player
		#Magic Tutor
		if the name of the target contains "Magic Tutor":
			send "<light blue>%target's name%: Greetings. Are you interested in some magic lessons? Or perhaps you're interested in some of my tomes?" to the player
			wait 2 seconds
			send "<run command:/train magic><gold>1 - I need training in magic. (+100 pts for $100)" to the player
			send "<run command:/mag-shop><gold>2 - Do you have any tomes for sale?" to the player
		#Curate
		if the name of the target contains "Curate":
			send "<light blue>%target's name%: Hello, young one. What can a humble curate help you with today?" to the player
			wait 2 seconds
			set {_cashreq} to ceil(abs(the player's health - the player's maximum health) * 2.5)
			send "<run command:/train staves><gold>1 - I need training in staves. (+10 pts for $75)" to the player
			send "<run command:/staff-shop><gold>2 - Do you have any staves for sale?" to the player
			if {_cashreq} is less than or equal to player's money:
				send "<run command:/sheal><gold>3 - I need healing. (Cost: %{_cashreq}%)" to the player
		#Validar
		if the name of the target contains "Validar":
			if {quests.%player%::New Arrival} is 1:
				send "<light blue>Validar: Oh, goody. More new arrivals. You got a passport?" to the player
				wait 2.5 seconds
				send "<light yellow>Text in gold indicates a dialouge option. Click it to say that line of dialouge and interact with the world." to the player
				wait 4 seconds
				send "<run command:/conv-na 1><gold>1 - I don't have one..." to the player
			else if {quests.%player%::New Arrival} is 2:
				send "<light blue>Validar: All done, eh? Alright, I'll trade you this ID for your registration papers." to the player
				wait 4 seconds
				give 1 book named "<gold>Quest Log" with lore "<white>Right-click to view your quest log." to the player
				send "<light blue>Validar: Give me a moment to look over your registration. If you need to correct anything on here, come back to me and ask." to the player
				wait 5.5 seconds
				send "<light blue>Validar: ...Here to be a knight, are you? Well, look at that; I've got slightly more respect for you now." to the player
				wait 4 seconds
				send "<light blue>Validar: Head for the training grounds right in front of House Silgrid. There's a combat instructor there waiting on the batch of new recruits. I'm guessin' that includes you." to the player
				make player execute command "/qstart"
			else:
				send "<light blue>Validar: Oh. You're back. Let me guess, something's wrong with your registration?" to the player
				wait 3 seconds
				send "<run command:/fsetup><gold>1 - I need to change some things on my registration." to the player
		#
		#C9 Citizens
		if the name of the target is "Colony 9 Citizen":
			if {quests.%player%::A Scarred Land} is 2:
				send "<light cyan>%target's name%: Oh, hello! I don't think I've seen you before." to the player
				wait 1 second
				send "<run command:/easternisles 1><gold>1 - Greetings. I am %player's tablist name%<reset><run command:/easternisles 1><gold>,a Knight of Silgrid. Lord Kiln wishes to know the state of your people." to the player
				send "<run command:/easternisles 2><gold>2 - I am %player's tablist name%<reset><run command:/easternisles 2><gold>. Lord Kiln of House Silgrid wants to know how your people fare." to the player
				send "<run command:/easternisles 3><gold>3 - And you won't see me again. I'm on a mission from Lord Kiln of Silgrid, he wants to know how your people fare." to the player
			else if {quests.%player%::A Villager's Request} is 1:
				send "<light cyan>%target's name%: Remember, it's the boulder just on the edge of town, somewhere near that rotted tower." to the player
			else if {quests.%player%::A Villager's Request} is 2:
				send "<light cyan>%target's name%: You've returned! Did you find out something about that boulder?" to the player
				wait 3 seconds
				send "<run command:/conv-avr 1><gold>1 - There was some sort of summoning table inside a dungeon there. I crushed the crystal inside of it, and it seemed to have stopped working." to the player
				send "<run command:/conv-avr 2><gold>2 - I've stopped your monster problem. I think I deserve a reward." to the player
				send "<run command:/conv-avr 3><gold>3 - I destroyed one of the sources of the monsters attacking your colony. They won't be bothering you anymore." to the player
			else:
				set {_rng} to a random integer from 1 to 6
				if {_rng} is 1:
					send "<light cyan>%target's name%: Hello." to the player
				else if {_rng} is 2:
					send "<light cyan>%target's name%: Hi there." to the player
				else if {_rng} is 3:
					send "<light cyan>%target's name%: ...Oh, Hello." to the player
				else if {_rng} is 4:
					send "<light cyan>%target's name%: We might not be the largest colony, or the most advanced, or... Hm. We're just a colony I suppose." to the player
				else if {_rng} is 5:
					send "<light cyan>%target's name%: Stories say that old tower over there used to be an outpost for Alstair when he was still king of the Northern Isles. Guess Helmund didn't want it to stay up when he came through." to the player
				else if {_rng} is 6:
					send "<light cyan>%target's name%: There's a group of thieves holed up in the castles nearby. Their leader even took the name of one of the Great Heroes! Can you imagine being that full of yourself?" to the player
		#
		#Blacksmiths
		if the name of the target contains "Blacksmith":
			if {quests.%player%::Fuel for the Fire} is not set:
				send "<light cyan>%target's name%: Need a weapon smithed up? Just as long as you don't need anything refined, I can get it done." to the player
				wait 3.5 seconds
				send "<run command:/conv-fftf 1><gold>1 - What's wrong with the refinery? Has something happened?" to the player
				send "<run command:/bs-shop><gold>2 - I just need some tools." to the player
				send "<run command:/store><gold>3 - I just need repairs." to the player
			else if {quests.%player%::Fuel for the Fire} is 2:
				send "<light cyan>%target's name%: So you've returned. Did you find that shipment?" to the player
				wait 3.5 seconds
				send "<run command:/conv-fftf 4><gold>1 - I found the shipment, but everything inside was missing." to the player
				if player has 64 coal:
					set {_coal} to 1
				if player has 16 magma block:
					set {_magma} to 1
				if {_coal} is 1:
					if {_magma} is 1:
						send "<run command:/conv-fftf 5><gold>2 - Here's your shipment. (Give 64 Coal & 16 Magma Blocks)" to the player
			else:
				set {_rng} to a random integer from 1 to 3
				if {_rng} is 1:
					send "<light cyan>%target's name%: Need something forged?" to the player
				else if {_rng} is 2:
					send "<light cyan>%target's name%: I've got the best steel in the whole land." to the player
				else if {_rng} is 3:
					send "<light cyan>%target's name%: Blades, picks... Whatever you need, I can forge it." to the player
				wait 1 seconds
				send "<run command:/bs-shop><gold>1 - What do you have for sale?" to the player
				send "<run command:/skills><gold>2 - What do you have for sale? (Repair/Upgrade Tools)" to the player
				if {quests.%player%::Fuel for the Fire} is 3:
					if player has 64 coal:
						set {_coal} to 1
					if player has 16 magma block:
						set {_magma} to 1
					if {_coal} is 1:
						if {_magma} is 1:
							send "<run command:/conv-fftf 5><gold>2 - Here's your shipment. (Give 64 Coal & 16 Magma Blocks)" to the player
		#
		#Jerome
		if the name of the target is "Jerome":
			if {quests.%player%::An Apprentice's Plight} is not set:
				send "<light blue>%target's name%: I can't talk right now. I'm trying to not get fired from the smithy." to the player
				wait 2.5 seconds
				send "<run command:/conv-aap 1><gold>1 - What's wrong?" to the player
				send "<run command:/conv-aap 2><gold>2 - Sorry. I'll leave you to it." to the player
			else if {quests.%player%::An Apprentice's Plight} is 1:
				send "<light blue>Jerome: You're back! Have you gotten those materials for me?" to the player
				wait 2.5 seconds
				send "<run command:/conv-aap 5><gold>1 - Not yet..." to the player
				if player has 14 iron ingot:
					if player has 11 stick:
						send "<run command:/conv-aap 6><gold>2 - Here you go. (Give 14 iron ingots & 11 sticks)" to the player
			else:
				send "<light blue>Jerome: Hey. You need me to fix a tool for you?" to the player
				wait 2.5 seconds
				send "<run command:/jeromefix><gold>1 - I need some repairs." to the player
				send "<run command:/conv-aap 7><gold>2 - Still have your job?" to the player
		#
		#Riis
		if the name of the target is "Riis":
			send "<light cyan>Greetings, young one. How may a humble curate help you today?" to the player
			wait 1.5 seconds
			send "<run command:/conv-stl 1><gold>1 - Are you the sage named Riis? I'd like to ask you about the Holy Weapons of Silgrund." to the player
			if {quests.%player%::Seeking the Light} is 1:
				send "<run command:/conv-stl 2><gold>2 - I'm on a quest from Lord Kiln. He said you might know something about where the Holy Weapons of Silgrund are." to the player
				send "<run command:/conv-stl 3><gold>3 - I need information on the Holy Weapons. Do you know where they are?" to the player
		#
		#Jorund
		if the name of the target is "Jorund":
			if {quests.%player%::Path of the Greats} is 1:
				send "<light cyan>%target's name%: Haven't seen you around here before." to the player
				wait 2 seconds
				send "<run command:/conv-potg 1><gold>1 - I am %player's tablist name%<reset><run command:/conv-potg 1><gold>, a Knight of Silgrid. Lord Kiln has sent me to you for training so that I may be worthy of wielding the Holy Weapons." to the player
			else if {quests.%player%::Path of the Greats} is 999:
				send "<light cyan>Jorund: You know, I could help put some Skills on whatever weapons you want... for a fee. Look, I can't make much of a living inside this icebox without charging a fee for everything." to the player
				wait 2.5 seconds
				send "<run command:/skills><gold>1 - What skills do you have for sale?" to the player
			else:
				send "<light cyan>Jorund: Remember: play to your weapon's strengths. If you've got a lot of skills that depend on you starting the battle, make sure you get in there and land the first strike." to the player
		#
		#Traders
		if the name of the target is "Trader":
			set {_rng} to a random integer from 1 to 3
			if {_rng} is 1:
				send "<light cyan>%target's name%: Greetings, traveller! Interested in any of my fine goods?" to the player
			else if {_rng} is 2:
				send "<light cyan>%target's name%: Welcome, welcome, %player's name%<reset><light cyan>! Everything you see in my shop is for sale!" to the player
			else:
				send "<light cyan>My prices are the lowest in all of Silgrund! You won't find a better deal elsewhere!" to the player
			wait 2 seconds
			send "<run command:/tradershop><gold>1 - What do you have for sale?" to the player
		#
		#Todd Howard
		if the name of the target is "Todd":
			set {_rng} to a random integer from 1 to 3
			if {_rng} is 1:
				send "<light cyan>Todd: Welcome to the shop. Our prices are fair, and our wares just work." to the player
			else if {_rng} is 2:
				send "<light cyan>Todd: All of my products have four times the utility of our competitors." to the player
			else:
				send "<light cyan>Todd: If you see it in my shop, you can buy it. Everything's for sale, and it just works." to the player
			wait 2 seconds
			send "<run command:/toddshop><gold>1 - What do you have for sale?" to the player
			
		#
		#Guards
		if the name of the target contains "Guard":
			set {_rng} to a random integer from 1 to 20
			if {_rng} is 1:
				send "<light cyan>%target's name%: Staying safe, %player's tablist name%<reset><light cyan>?" to the player
			else if {_rng} is 2:
				send "<light cyan>%target's name%: The city's safe with us." to the player
			else if {_rng} is 3:
				send "<light cyan>%target's name%: Tired, %player's tablist name%<reset><light cyan>? Stop by the inn and rest. I'm sure a knight such as yourself could use it." to the player
			else if {_rng} is 4:
				send "<light cyan>%target's name%: These monsters are becoming a real menace." to the player
			else if {_rng} is 5:
				send "<light cyan>%target's name%: These old swords they give us are dull as a rock. Wish I had the money to have it refined..." to the player
			else if {_rng} is 6:
				send "<light cyan>%target's name%: How do you do, %player's tablist name%?" to the player
			else if {_rng} is 7:
				send "<light cyan>%target's name%: Not much happens around here. Except for the occasional zombie horde." to the player
			else if {_rng} is 8:
				send "<light cyan>%target's name%: Have you heard the tale of the Great Heroes? Legends say they wielded weapons capable of shattering the earth in one strike. Wish I could see one with my own eyes." to the player
			else if {_rng} is 9:
				send "<light cyan>%target's name%: This ratty old armour is barely better than a carpet. By the Greats, I wish they'd give us something better to save us from these monstrosities running amok." to the player
			else if {_rng} is 10:
				set {_armour} to getHelmet(player)
				add getChestplate(player) to {_armour}
				add getLeggings(player) to {_armour}
				add getBoots(player) to {_armour}
				if {_armour} is 20:
					send "<light cyan>%target's name%: By the Greats, that's one expensive set of armour." to the player
				else if {_armour} is 16:
					send "<light cyan>%target's name%: Favor the gold armour, eh? 'Heard it's good for enchanting, but it's a bit more than what my pay can afford." to the player
				else if {_armour} is 12:
					send "<light cyan>%target's name%: Nothing wrong with a sturdy set of iron armour. Good metal 'll keep you safe from just about everything." to the player
				else if {_armour} is 8: 
					send "<light cyan>%target's name%: That chainmail is decent enough, but it's not going to save you when it counts." to the player
				else if {_armour} is 4:
					send "<light cyan>%target's name%: Leather armour? By the Greats, find a blacksmith and buy yourself some real armour." to the player
				else if {_armour} is not set:
					send "<light cyan>%target's name%: No armour? Are you mad?! Find a blacksmith and buy some armour before you get yourself killed." to the player
				else:
					send "<light cyan>%target's name%: All that mixing armour is going to get for you is a large lump of gold wasted on repairs. Swallow your pride and spend some gold for a full set." to the player
			else if {_rng} is 11:
				if the name of the player's tool contains "<gold><bold>":
					send "<light cyan>%target's name%: By the Greats, that isn't... It is, isn't it? You can wield %name of the player's tool%<reset><light cyan>! I never thought I'd see the day..." to the player
				else if the player's tool is not air:
					send "<light cyan>%target's name%: A <reset>%name of the player's tool%<reset><light cyan> is fair enough, but it'll never compare to the Holy Weapons of the Great Heroes. Now those are the real weapons." to the player
				else:
					send "<light cyan>%target's name%: If you're in need of a weapon, you can never go wrong with an iron sword."
			else if {_rng} is 12:
				if {weaponrank.%player%::swords} is more than or equal to 15000:
					send "<light cyan>%target's name%: Funny, I just heard a tale of a legendary swordsman with your name at the tavern. Think that's a coincidence?" to the player
				else if {weaponrank.%player%::swords} is more than or equal to 7500:
					send "<light cyan>%target's name%: I envy your skill with the sword, %player's tablist name%<reset><light cyan>. Think you could give me a lesson or two?" to the player
				else if {weaponrank.%player%::swords} is more than or equal to 3750:
					send "<light cyan>%target's name%: Hey, %player's tablist name%<reset><light cyan>, think I could spar against your blade sometime?" to the player
				else if {weaponrank.%player%::swords} is more than or equal to 1875:
					send "<light cyan>%target's name%: I wouldn't worry too much about finding a sparring partner, %player's tablist name%<reset><light cyan>. With all the monsters roaming around out here, there's free training dummies everywhere." to the player
				else if {weaponrank.%player%::swords} is more than or equal to 900:
					send "<light cyan>%target's name%: Your swordsmanship needs some practice, %player's tablist name%<reset><light cyan>. I get nervous watching you flail around with that thing." to the player
				else:
					send "<light cyan>%target's name%: I'm surprised that a Knight of Silgrid can't use a sword to save his life. Lord Kiln's training regimen has gone soft." to the player
			else if {_rng} is 13:
				if {weaponrank.%player%::lances} is more than or equal to 15000:
					send "<light cyan>%target's name%: The townsfolk call you the second coming of the Great Hero Quan. Hard to believe anyone but him could make a lance look as powerful as a sword." to the player
				else if {weaponrank.%player%::lances} is more than or equal to 7500:
					send "<light cyan>%target's name%: I always thought lances were just a weapon for farmers. That is, until you came along." to the player
				else if {weaponrank.%player%::lances} is more than or equal to 3750:
					send "<light cyan>%target's name%: One of the Great Heroes, Quan, used to use a lance. Is he your inspiration?" to the player
				else if {weaponrank.%player%::lances} is more than or equal to 1875:
					send "<light cyan>%target's name%: You're serious about training with a lance? That's surprising, I'd have figured everyone had picked up the sword instead." to the player
				else if {weaponrank.%player%::lances} is more than or equal to 900:
					send "<light cyan>%target's name%: So you've swung a lance around a few times, eh? That's more than most people these days." to the player
				else:
					send "<light cyan>%target's name%: Those dinky lances are better served tilling the ground than being a weapon for soldiers." to the player
			else if {_rng} is 14:
				if {weaponrank.%player%::axes} is more than or equal to 15000:
					send "<light cyan>%target's name%: I don't know how you did it, but you've got entire fields of monsters running at the mere sight of your axe. If the Great Hero Hector were still around, he'd be proud." to the player
				else if {weaponrank.%player%::axes} is more than or equal to 7500:
					send "<light cyan>%target's name%: Looks like those old war axes are worth something after all. Hah, who would've thought I'd be the one saying that?" to the player
				else if {weaponrank.%player%::axes} is more than or equal to 3750:
					send "<light cyan>%target's name%: Hey, woodcutter, why don't you bring me something for the fire? Hahaha!" to the player
				else if {weaponrank.%player%::axes} is more than or equal to 1875: 
					send "<light cyan>%target's name%: I don't care what you say, those war axes aren't worth the metal they're made out of." to the player
				else if {weaponrank.%player%::axes} is more than or equal to 900:
					send "<light cyan>%target's name%: I can't tell if you're trying to be a woodcutter, or if you're seriously trying to use an axe as a weapon." to the player
				else:
					send "<light cyan>%target's name%: War axes are as pointless as they are big. Who's going to need all that power when they've already been cut open by a broadsword?" to the player
			else if {_rng} is 15:
				if {weaponrank.%player%::magic} is more than or equal to 15000:
					send "<light cyan>%target's name%: There's been whispers around the town... That you have the blood of Reinhardt, the great Mage Knight, flowing through you... Are those rumors true?" to the player
				else if {weaponrank.%player%::magic} is more than or equal to 7500:
					send "<light cyan>%target's name%: You're a real wizard, you know that? Never seen anyone with your talent in magic before." to the player
				else if {weaponrank.%player%::magic} is more than or equal to 3750:
					send "<light cyan>%target's name%: You're not half bad with those spells of yours. Got more brains than I do to understand all of 'em." to the player
				else if {weaponrank.%player%::magic} is more than or equal to 1875:
					send "<light cyan>%target's name%: Careful where you cast that magic. I don't want to get set ablaze by some sort of experiment." to the player
				else if {weaponrank.%player%::magic} is more than or equal to 900:
					send "<light cyan>%target's name%: So, you can cast a few spells. What do you do with them, light your campfire?" to the player
				else:
					send "<light cyan>%target's name%: Never could understand those magic wands and tomes. Enchantments make my head spin as it is." to the player
			else if {_rng} is 16:
				if {weaponrank.%player%::bows} is more than or equal to 15000:
					send "<light cyan>%target's name%: I used to think it was just folly, but now I'm the one telling stories about your skills with a bow! Haha, Jeorge the Sniper would be proud of you %player's tablist name%<reset><light cyan>!" to the player
				else if {weaponrank.%player%::bows} is more than or equal to 7500:
					send "<light cyan>%target's name%: I have to admit, your skills with a bow are really something. I've never seen someone as accurate as you." to the player
				else if {weaponrank.%player%::bows} is more than or equal to 3750:
					send "<light cyan>%target's name%: You think you're good with a bow? The old Hero Jeorge would make you think twice before saying that again." to the player
				else if {weaponrank.%player%::bows} is more than or equal to 1875:
					send "<light cyan>%target's name%: Heard the other guards talk about your skills with a bow. As for me? I'm not impressed." to the player
				else if {weaponrank.%player%::bows} is more than or equal to 900:
					send "<light cyan>%target's name%: So you're trying out the bow, eh? Good luck, those strings are as flimsy as they look." to the player
				else:
					send "<light cyan>%target's name%: I always hated bow knights. Cowardly whelps can't even come out and fight like a real knight." to the player
			else if {_rng} is 17:
				if {weaponrank.%player%::staves} is more than or equal to 15000:
					send "<light cyan>%target's name%: Not many can say they're as good with a staff as old Wrys. Good to know there's still some out there who can match his skills." to the player
				else if {weaponrank.%player%::staves} is more than or equal to 7500:
					send "<light cyan>%target's name%: If I didn't know better, I'd have thought you and your staff were some sort of guardian angel!" to the player
				else if {weaponrank.%player%::staves} is more than or equal to 3750:
					send "<light cyan>%target's name%: I've seen your work with that staff. Think you could come and patch up some of our wounded?" to the player
				else if {weaponrank.%player%::staves} is more than or equal to 1875:
					send "<light cyan>%target's name%: Careful with some of those advanced staves. I've heard horror stories of simple patch jobs going wrong..." to the player
				else if {weaponrank.%player%::staves} is more than or equal to 900:
					send "<light cyan>%target's name%: Heading down the path of the cleric? The world could use more people like you." to the player
				else:
					send "<light cyan>%target's name%: This land could use more clerics. A good healer is hard to come by these days." to the player
			else if {_rng} is 18:
				send "<light cyan>%target's name%: Hope that I can have legends told about me in the future..." to the player
			else if {_rng} is 19:
				send "<light cyan>%target's name%: I'd heard some of the old Holy Weapons ended up in House Silgrid, but they seem to have gone missing..." to the player
			else if {_rng} is 20:
				send "<light cyan>%target's name%: May the Greats watch over your battles, %player's tablist name%<reset><light cyan>." to the player
		#
		#Hunters
		else if the name of the target contains "Hunter":
			if {quests.%player%::Monster Hunt} is not set:
				send "<light blue>Up for some monster hunting? These lands could always use a bit of thinning out." to the player
				wait 2 seconds
				send "<run command:/starthunt><gold>1 - Sure. Let's get going." to the player
			else if {quests.%player%::Monster Hunt} is 999:
				send "<light blue>Back for another round, eh? No problem for me. These monsters are due for a killin'." to the player
				wait 2 seconds
				send "<run command:/starthunt><gold>1 - I'm ready for another hunt." to the player

command /conv-ahd <number>:
	trigger:
		if {quests.%player%::Threads of Fate} is 1:
			if arg 1 is 1:
				send "<light cyan>Lord Kiln: Elrid was our foe in the last war. The lands of Elrid are cloaked in eternal shadow, providing a breeding ground for all manner of fell magic."
				wait 6 seconds
				send "<light cyan>Lord Kiln: Their leader, Helmund, attempted to invade Silgrund many years ago, which prompted the creation of the Holy Weapons and thus the birth of the Great Heroes."
				wait 6 seconds
				send "<light cyan>Lord Kiln: Helmund was eventually slain, and his forces were driven back to Elrid. Afterwards, the Great Heroes used the power of the Holy Weapons to create a barrier separating our world from theirs: The Sacred Seal."
				wait 6.5 seconds
				send "<light cyan>Lord Kiln: If the Sacred Seal has truly been broken, then that must mean Elridian forces are attempting another invasion. To be blunt, we cannot fight them on our land. Our fortresses and outposts have either been demolished from the previous war or besieged by theives. We have no resources to fight another war of a scale such as this."
				wait 9.5 seconds
				send "<light cyan>Lord Kiln: I'm afraid the end is near. Our troops are exhausted and of low morale from the persistent attacks of the Elridian thralls. We have no troops, no fortifications, an empty armoury, and no gold to restore any of them to fighting condition. It would take a true miracle to save Silgrund now."
				wait 7 seconds
				send "<run command:/conv-ahd 2><gold>1 - What if there was some way we could restore the seal?"
			else if arg 1 is 2:
				send "<light cyan>Lord Kiln: Restore the seal? %player's tablist name%<reset><light cyan>, it took the entirety of the Great Heroes to place it there to begin with. Restoring the seal would be a gargantuan task in our current state."
				wait 6 seconds
				send "<light cyan>Lord Kiln: With Cinder under Elridian control, our last flame of hope has been extinguished... Silgrund, it seems, is doomed to fall."
			else if arg 1 is 3:
				send "<light cyan>Lord Kiln: If the Sacred Seal has truly been broken, then that must mean Elridian forces are attempting another invasion. To be blunt, we cannot fight them on our land. Our fortresses and outposts have either been demolished from the previous war or besieged by theives. We have no resources to fight another war of a scale such as this."
				wait 9.5 seconds
				send "<light cyan>Lord Kiln: I'm afraid the end is near. Our troops are exhausted and of low morale from the persistent attacks of the Elridian thralls. We have no troops, no fortifications, an empty armoury, and no gold to restore any of them to fighting condition. It would take a true miracle to save Silgrund now."
			else if arg 1 is 4:
				send "<light cyan>Lord Kiln:"
				
command /adom-boss:
	trigger:
		if {quests.%player%::A Deadly Test of Might} is 1:
			set {bossbar.%player%::Master Necromancer} to new boss bar
			add player to {bossbar.%player%::Master Necromancer}
			set the title of bossbar {bossbar.%player%::Master Necromancer} to "<light red><bold>Master Necromancer"
			spawn 1 zombie at location 1077, 3, -375 in world "adventure"
			set the name of the last spawned entity to "<light red><bold>Master Necromancer"
			set {_deadlord} to the last spawned entity
			set {t_str.%{_deadlord}%} to 105
			set {t_def.%{_deadlord}%} to 90
			set {t_spd.%{_deadlord}%} to 75
			set {skl.%{_deadlord}%} to 94
			set {t_res.%{_deadlord}%} to 135
			set {lvl.%{_deadlord}%} to 65
			set the maximum health of {_deadlord} to 125
			set {_deadlord}'s tool to diamond sword of sharpness 7, fire aspect 2 named "<gold><bold>Light Brand" with lore "<light red><bold>Slot A - Distant Counter", "<light blue><bold>Slot B - Shield Pulse", "<light yellow><bold>Slot C - Pressure STR", "<light green><bold>Assist - Capture", "<light purple><bold>Special - Pavise", "<white><bold>Refined: Unique"
			set {_deadlord}'s helmet to diamond helmet of protection 4
			set {_deadlord}'s chestplate to diamond chestplate of protection 4
			set {_deadlord}'s leggings to diamond leggings of protection 4
			set {_deadlord}'s boots to diamond boots of protection 4
			set {class.%{_deadlord}%} to "Sorcerer"
			set {skillslot1.%{_deadlord}%} to "Guard"
			set {skillslot2.%{_deadlord}%} to "Unbreakable"
			set {skillslot3.%{_deadlord}%} to "M_Brazen Spectrum"
			set {skillslot4.%{_deadlord}%} to "Sword Specialist"
			set {skillslot5.%{_deadlord}%} to "Miracle"
			set {isBoss.%{_deadlord}%} to true
			set {_lvlbal} to 0
			loop all players in radius 256 of {_deadlord}:
				if loop-player is not npc:
					add {lvl.%loop-player%} to {_lvlbal}
					add 1 to {_players}
			set {_lvlbal} to ({_lvlbal} / {_players}) + 10
			if {_lvlbal} is less than {lvl.%{_deadlord}%}:
				if {_lvlbal} is not 0:
					set {_balance} to abs({_lvlbal} - {lvl.%{_deadlord}%})
					loop {_balance} times:
						subtract 1 from {t_str.%{_deadlord}%}
						subtract 1 from {t_def.%{_deadlord}%}
						subtract 1 from {t_spd.%{_deadlord}%}
						subtract 1 from {skl.%{_deadlord}%}
						subtract 1 from {t_res.%{_deadlord}%}
						subtract 0.5 from the maximum health of {_deadlord}
						subtract 1 from {lvl.%{_deadlord}%}
			else if {_lvlbal} is more than {lvl.%{_deadlord}%}:
				set {_balance} to ({_lvlbal} - {lvl.%{_deadlord}%})
				loop {_balance} times:
					add 1 to {t_str.%{_deadlord}%}
					add 1 to {t_def.%{_deadlord}%}
					add 1 to {t_spd.%{_deadlord}%}
					add 1 to {skl.%{_deadlord}%}
					add 1 to {t_res.%{_deadlord}%}
					add 0.5 to the maximum health of {_deadlord}
					add 1 to {lvl.%{_deadlord}%}
			if the maximum health of {_deadlord} is less than 20:
				set the maximum health of {_deadlord} to 20
			if {t_spd.%{_deadlord}%} is more than 125:
				apply swiftness 5 to {_deadlord} for 1 day
			else if {t_spd.%{_deadlord}%} is more than 100:
				apply swiftness 4 to {_deadlord} for 1 day
			else if {t_spd.%{_deadlord}%} is more than 75:
				apply swiftness 3 to {_deadlord} for 1 day
			else if {t_spd.%{_deadlord}%} is more than 50:
				apply swiftness 2 to {_deadlord} for 1 day
			else if {t_spd.%{_deadlord}%} is more than 25:
				apply swiftness 1 to {_deadlord} for 1 day
			heal {_deadlord} by 999
		else:
			teleport the player to location at (1077, 60, -364) in world "adventure"
			send "<light red>A strange magical energy is preventing you from falling inside the cavern."
			
on damage of a zombie:
	if victim's name is "<light red><bold>Master Necromancer":
		set {_health} to (victim's health / victim's maximum health - 0.1)
		set progress of bossbar {bossbar.%attacker%::Master Necromancer} to {_health}
		show boss bar {bossbar.%attacker%::Master Necromancer}
		if victim's health is victim's maximum health:
			heal the victim by 999
			push the attacker backwards at speed 5
			apply resistance 5 to the victim for 2 seconds
			strike lightning at the victim
			loop all players in radius 50 of the victim:
				send "<light red>Master Necromancer: <white>Did you really think I came here alone? Now, you will become my next puppet, fool!" to loop-player
			while victim is alive:
				loop 6 times:
					add 1 to {_spawns}
					if {_spawns} is more than 3:
						spawn 1 skeleton at the victim
						set {_deadlord} to the last spawned entity
						set {_deadlord}'s tool to bow of power 3
					else:
						spawn 1 zombie at the victim
						set {_deadlord} to the last spawned entity
						set {_deadlord}'s tool to iron sword of sharpness 4
					play 15 (smoke with speed 1) at {_deadlord}
					play 15 (spell with speed 1) at {_deadlord}
					play 15 (lava pop with speed 1) at {_deadlord}
					set the name of {_deadlord} to "<light red>Necromancer's Thrall"
					set the last spawned entity's helmet to iron helmet
					set the last spawned entity's chestplate to iron chestplate
					set the last spawned entity's leggings to iron leggings
					set the last spawned entity's boots to iron boots
					set {t_str.%{_deadlord}%} to 40
					set {t_def.%{_deadlord}%} to 40
					set {t_spd.%{_deadlord}%} to 25
					set {skl.%{_deadlord}%} to 30
					set {t_res.%{_deadlord}%} to 25
					set {_deadlord}'s maximum health to 40
					set {lvl.%{_deadlord}%} to 40
					apply swiftness 2 to {_deadlord} for 1 hour
					loop all players in radius 256 of {_deadlord}:
						if loop-player is not npc:
							add {lvl.%loop-player%} to {_lvlbal}
							add ({promoted.%loop-player%} * 10) to {_lvlbal}
							add 1 to {_players}
					set {_lvlbal} to ({_lvlbal} / {_players}) + 10
					if {_lvlbal} is less than {lvl.%{_deadlord}%}:
						if {_lvlbal} is not 0:
							set {_balance} to abs({_lvlbal} - {lvl.%{_deadlord}%})
							loop {_balance} times:
								subtract 1 from {t_str.%{_deadlord}%}
								subtract 1 from {t_def.%{_deadlord}%}
								subtract 1 from {t_spd.%{_deadlord}%}
								subtract 1 from {skl.%{_deadlord}%}
								subtract 1 from {t_res.%{_deadlord}%}
								subtract 0.5 from the maximum health of {_deadlord}
								subtract 1 from {lvl.%{_deadlord}%}
					else if {_lvlbal} is more than {lvl.%{_deadlord}%}:
						set {_balance} to ({_lvlbal} - {lvl.%{_deadlord}%})
						loop {_balance} times:
							add 1 to {t_str.%{_deadlord}%}
							add 1 to {t_def.%{_deadlord}%}
							add 1 to {t_spd.%{_deadlord}%}
							add 1 to {skl.%{_deadlord}%}
							add 1 to {t_res.%{_deadlord}%}
							add 0.5 to the maximum health of {_deadlord}
							add 1 to {lvl.%{_deadlord}%}
				wait 45 seconds
		
command /adom-win:
	trigger:
		if {quests.%player%::A Deadly Test of Might} is not 999:
			send "<light red>The Necromancer's fell magic is preventing you from escaping!"
			teleport the player to location at (1077, 3, -375) in world "adventure"
			strike lightning effect at the player
		
on death of a monster:
	if the name of the victim is "<light red><bold>Master Necromancer":
		play 60 (smoke with speed 1) at the victim
		play 60 (cloud with speed 1) at the victim
		play sound "entity.enderman.teleport" with volume 0.7 and pitch 1.5 at the attacker for the attacker
		send "<light red>Master Necromancer: This is not the end... far from it..." to the attacker
		strike lightning effect at the victim
		wait 2 seconds
		send "<light red>Master Necromancer: Is that... Cinder's presence I detect? Hahaha... he will make an excellent soldier for His Greatness..." to the attacker
		if {quests.%attacker%::A Deadly Test of Might} is 1:
			finishQuest(attacker,"A Deadly Test of Might","The Thief Ring was recovered from the necromancer's body.")
			drop 1 music disc 13 named "<yellow><bold>Thief Ring" with lore "<white>While in your inventory:", "<yellow>Slain monsters have a chance to drop extra money." at the victim
			wait 8 seconds
			send "<light yellow>Cinder: ...excellent soldier? What was he blabbering about?" to the attacker
			wait 5 seconds
			strike lightning effect at the attacker
			heal the attacker by 999
			apply poison 4 to the attacker for 60 seconds
			apply blindness 1 to the attacker for 60 seconds
			apply nausea 1 to the attacker for 60 seconds
			send "<light yellow>Cinder: ...Ngh! Something's.... not right...!" to the attacker
			wait 3 seconds
			send "<light yellow>Cinder: ...%attacker's tablist name%<reset><light yellow>... You need to... get back to Lord Kiln..." to the attacker
			wait 3 seconds
			send "<light yellow>Cinder: ...It seems... my time here... has come to an end..." to the attacker
			wait 4.5 seconds
			send "<light yellow>Cinder: ...here... last ounce... of strength... you must... hurry...." to the attacker
			cure the attacker of poison
			remove blindness from the attacker
			remove nausea from the attacker
			apply regeneration 4 to the attacker for 5 seconds
			play 60 (heart with speed 1) at the attacker
			wait 5 seconds
			send "<gold>The gemstone falls quiet..." to the attacker
			loop all items in the attacker's inventory:
				if the name of the loop-item is "<light yellow>Cinder's Gemstone":
					play 100 (smoke with speed 1) at the attacker
					play sound "block.lava.extinguish" with volume 1 and pitch 1 at the attacker for the attacker
					enchant the loop-item with power 1
					set the 1st line of the lore of the loop-item to "<white>The remains of Cinder's gemstone after his capture."
					set the 2nd line of the lore of the loop-item to "<white>While performing Awakenings is still possible, any attempts to communicate with Cinder are useless."
					exit 1 loop
			startQuest(attacker,"Threads of Fate","Report to Kiln.")

command /starthunt:
	trigger:
		set {MHTarget.%player%} to ceil({lvl.%player%} / 2)
		startQuest(player,"Monster Hunt","Kill %{MHTarget.%player%}% monsters.")
		
on inventory click:
	if the name of the player's current inventory is "<gold>Quest Log":
		cancel event
		
on inventory close:
	if {quests.%player%::Greats Guide You} is 1:
		wait 1 tick
		loop all items in the player's inventory:
			if the name of the loop-item contains "<light red>Unusual":
				setQuestProgress(player,"Greats Guide You",2,"Return with the gemstone to Lord Kiln.")
				exit 1 loop

		
on inventory open:
	wait 1 tick
	if the name of the player's current inventory is "<gold>Refinery Shipment":
		if {quests.%player%::Fuel for the Fire} is 1:
			setQuestProgress(player,"Fuel for the Fire",2,"Return the news about the shipment, or find the refinery's fuel yourself.")
		
on right click with nether star:
	if the name of the event-item is "<gold>Summoning Crystal":
		if {quests.%player%::A Villager's Request} is 1:
			delete player's held item
			play 40 (glowstone block break with speed 1) at the player
			play 40 (glass break with speed 1) at the player
			play sound "block.glass.break" with volume 0.5 and pitch 1.5 at the player for the player
			send "<gold>The summoning crystal shatters in your hand, spreading shards of glass and what you can only assume is some sort of... magical goop, onto the ground." to the player
			setQuestProgress(player,"A Villager's Request",2,"Return to the citizens of Colony 9.")
		
on right click with written book:
	if the name of the event-item is "<gold>The Legends of Silgrund":
		if {quests.%player%::A History Lesson} is not 999:
			if {quests.%player%::A History Lesson} is 1:
				setQuestProgress(player,"A History Lesson",2,"Ask Lord Kiln about the Holy Weapons of Silgrund.")
		
command /quests <number>:
	trigger:
		if arg 1 is 2:
			open chest with 5 rows named "<gold>Quest Log | Generation 2" for the player
			set slot 0 of the player's current inventory to 1 book named "<light blue>Main Quests:"
			#A Scarred Land
			if {quests.%player%::A Scarred Land} is 999:
				set slot 5 of the player's current inventory to 1 emerald block named "<green>A Scarred Land" with lore "<white>Lord Kiln advised me on the undead menace,", "<white>and asked if I could find out how the people of the", "<white>Northern Isles fared. I returned the dire information to Lord Kiln, and it seemed", "<white>to have made him very agitated. Something tells me it's not just the state of the Isles upsetting him."
			else if {quests.%player%::A Scarred Land} is 1:
				set slot 5 of the player's current inventory to 1 lapis block named "<light blue>A Scarred Land" with lore "<white>I've been summoned to House Silgrid to meet", "<white>with Lord Kiln posthaste."
			else if {quests.%player%::A Scarred Land} is 3:
				set slot 5 of the player's current inventory to 1 lapis block named "<light blue>A Scarred Land" with lore "<white>I arrived at the Northern Isles, and", "<white>stumbled on a place known as Colony 9.", "<white>A villager informed me that monsters have been spreading", "<white>though their settlement just as they have spread at House Silgrid.", "<white>I need to return this information to Lord Kiln immediately."
			else if {quests.%player%::A Scarred Land} is 2:
				set slot 5 of the player's current inventory to 1 lapis block named "<light blue>A Scarred Land" with lore "<white>Lord Kiln has asked me to travel to the Northern Isles,", "<white>and ask its inhabitants how they fare.", "<white>An orange lighthouse should mark where I need to go."
			else:
				set slot 5 of the player's current inventory to 1 redstone block named "<light red>A Scarred Land" with lore "<white>Complete ""Home Sweet Home"" to unlock."
			#A History Lesson
			if {quests.%player%::A History Lesson} is 999:
				set slot 6 of the player's current inventory to 1 emerald block named "<green>A History Lesson" with lore "<white>I read the book Lord Kiln recommended to me.", "<white>It seems that the history of Silgrund is richer than I thought.", "<white>Of particular note is the existence of Holy Weapons:", "<white>Sacred weapons imbued with immense power.", "<white>I should ask Lord Kiln for more information."
			else if {quests.%player%::A History Lesson} is 2:
				set slot 6 of the player's current inventory to 1 lapis block named "<light blue>Living Legends" with lore "<white>I read ""The Legends of Silgrund"", an anonymous account of the land's history.", "<white>I should ask Lord Kiln about the Holy Weapons of Silgrund.", "<white>If they truly exist, then they could help stop the monsters' onslaught."
			else if {quests.%player%::A History Lesson} is 1:
				set slot 6 of the player's current inventory to 1 lapis block named "<light blue>A History Lesson" with lore "<white>Lord Kiln advised me to visit the Great Library.", "<white>He recommended the book ""The Legends of Silgrund""."
			else:
				set slot 6 of the player's current inventory to 1 redstone block named "<light red>A History Lesson" with lore "<white>Complete ""A Scarred Land"" to unlock."
			#Seeking the Light
			if {quests.%player%::Seeking the Light} is 999:
				set slot 7 of the player's current inventory to 1 emerald block named "<green>Seeking the Light" with lore "<white>I ventured to Colony 6, and found a man named Riis.", "<white>He lead me to a thief's hideout, where I recovered the Binding Blade.", "<white>I've returned the blade to Lord Kiln, but it seems as though all the power has left the weapon."
			else if {quests.%player%::Seeking the Light} is 3:
				set slot 7 of the player's current inventory to 1 lapis block named "<light blue>Seeking the Light" with lore "<white>I entered the hideout and recovered what was left", "<white>of the Mystletainn. I need to return it to Lord Kiln as soon as I can."
			else if {quests.%player%::Seeking the Light} is 2:
				set slot 7 of the player's current inventory to 1 lapis block named "<light blue>Seeking the Light" with lore "<white>I found Riis hiding with other refugees from Colony 6.", "<white>He gave me the location of a thief's hideout.", "<white>There, I might find the Binding Blade, one of the lost Holy Weapons."
			else if {quests.%player%::Seeking the Light} is 1:
				set slot 7 of the player's current inventory to 1 lapis block named "<light blue>Seeking the Light" with lore "<white>Lord Kiln said to find a man named Riis in Colony 6", "<white>if I want to find the lost Holy Weapons of Silgrund.", "<white>I can find him in the Northern Isles."
			else:
				set slot 7 of the player's current inventory to 1 redstone block named "<light red>Seeking the Light" with lore "<white>Complete ""A History Lesson"" to unlock."
			#Greats Guide You
			if {quests.%player%::Greats Guide You} is 999:
				set slot 8 of the player's current inventory to 1 emerald block named "<green>Greats Guide You" with lore "<white>There was a strange gemstone inside the Heroes' Guild, but I otherwise found nothing that could help us revive Mystletainn.", "<white>Lord Kiln and I are out of ideas."
			else if {quests.%player%::Greats Guide You} is 2:
				set slot 8 of the player's current inventory to 1 lapis block named "<light blue>Greats Guide You" with lore "<white>Apart from a strange gemstone, I couldn't find anything inside the Heroes' Guild.", "<white>Lord Kiln might be interested in the gemstone, so I should return it to him as soon as I can." 
			else if {quests.%player%::Greats Guide You} is 1:
				set slot 8 of the player's current inventory to 1 lapis block named "<light blue>Greats Guide You" with lore "<white>Lord Kiln has tasked me with traveling to the Heroes' Guild, where some of the Great Heroes once trained.", "<white>He theorizes that I might be able to find something there that can restore Mystletainn."
			else:
				set slot 8 of the player's current inventory to 1 redstone block named "<light red>Greats Guide You" with lore "<white>Complete ""Seeking the Light"" to unlock."
			#Journey to Nifl
			if {quests.%player%::Journey to Nifl} is 999:
				set slot 9 of the player's current inventory to 1 emerald block named "<green>Journey to Nifl" with lore "<white>The gemstone from the Heroes' Guild led me to a shrine deep inside Nifl.", "<white>The gemstone slotted into a crevice inside the shrine, and summoned some sort of magical energy.", "<white>It seems I can use the gemstone to communicate with the soul of Cinder,", "<white>The first Lord of Silgrund."
			else if {quests.%player%::Journey to Nifl} is 2:
				set slot 9 of the player's current inventory to 1 lapis block named "<light blue>Journey to Nifl" with lore "<white>Following the gemstone recovered from the Heroes' Guild,", "<white>I've been lead to a shrine deep inside the ice plains of Nifl.", "<white>There's a crevice inside the shrine that the gemstone seems to be a perfect fit for."
			else if {quests.%player%::Journey to Nifl} is 1:
				set slot 9 of the player's current inventory to 1 lapis block named "<light blue>Journey to Nifl" with lore "<white>The gemstone from the Heroes' Guild has started moving on its own.", "<white>I wonder what it's pointing to?"
			else:
				set slot 9 of the player's current inventory to 1 redstone block named "<light red>Journey to Nifl" with lore "<white>Complete ""Greats Guide You"" to unlock."
			#A Lord's Worth
			if {quests.%player%::A Lord's Worth} is 999:
				set slot 10 of the player's current inventory to 1 emerald block named "<green>A Lord's Worth" with lore "<white>Communicating through the gemstone,", "<white>Cinder led me to the basement of House Silgrid.", "<white>Here, I should be able to revive Mystletainn using Cinder's help."
			else if {quests.%player%::A Lord's Worth} is 2:
				set slot 10 of the player's current inventory to 1 lapis block named "<light blue>A Lord's Worth" with lore "<white>Cinder has lead me to the basement of House Silgrid,", "<white>where the ancient Mage Knights once studied and trained.", "<white>I need to find a conduit to charge the gemstone."
			else if {quests.%player%::A Lord's Worth} is 1:
				set slot 10 of the player's current inventory to 1 lapis block named "<light blue>A Lord's Worth" with lore "<white>The Blazing Lord, Cinder, has asked me to find a secret entrance to House Silgrid.", "<white>He wants to ""strengthen our connection"" there... whatever that means."
			else:
				set slot 10 of the player's current inventory to 1 redstone block named "<light red>A Lord's Worth" with lore "<white>Complete ""Journey to Nifl"" to unlock."
			#Awakening
			if {quests.%player%::Awakening} is 999:
				set slot 11 of the player's current inventory to 1 emerald block named "<green>Awakening" with lore "<white>Using Cinder's notes and my own energy,", "<white>I've revived Mystletainn.", "<white>Now I can revive the Holy Weapons and end the war once and for all."
			else if {quests.%player%::Awakening} is 2:
				set slot 11 of the player's current inventory to 1 lapis block named "<light blue>Awakening" with lore "<white>The Awakening was successful.", "<white>We have a true Holy Weapon in our possession.", "<white>Lord Kiln will be overjoyed to see it..."
			else if {quests.%player%::Awakening} is 1:
				set slot 11 of the player's current inventory to 1 lapis block named "<light blue>Awakening" with lore "<white>Cinder's notes have taught me the enchantments I need to revive Holy Weapons.", "<white>However, the energy it will take to do so is massive.", "<white>I need to be certain I can withstand the Rite of Awakening before trying to revive a Holy Weapon."
			else:
				set slot 11 of the player's current inventory to 1 redstone block named "<light red>Awakening" with lore "<white>Complete ""A Lord's Worth"" to unlock."
			#Liberation
			if {quests.%player%::Liberation} is 999:
				set slot 12 of the player's current inventory to 1 emerald block named "<green>Liberation" with lore "<white>I've managed to drive back a large number of monsters encroaching on Silgrund.", "<white>The Holy Weapons' power seems to be preventing the terrors from resurrecting."
			else if {quests.%player%::Liberation} is set:
				set slot 12 of the player's current inventory to 1 lapis block named "<light blue>Liberation" with lore "<white>With the power of the Holy Weapons, I can start driving back the undead horde.", "<white>Monsters slain: %{quests.%player%::Liberation} - 1%/30"
			else:
				set slot 12 of the player's current inventory to 1 redstone block named "<light red>Liberation" with lore "<white>Complete ""Awakening"" to unlock."
			#A Deadly Test of Might
			if {quests.%player%::A Deadly Test of Might} is 999:
				set slot 13 of the player's current inventory to 1 emerald block named "<green>A Deadly Test of Might" with lore "<white>I managed to defeat the fell necromancer established inside Summoner's Sword.", "<white>Unfortunately, Cinder was captured by the necromancer as he fled from the fortress.", "<white>Lord Kiln and I are the only ones left."
			else if {quests.%player%::A Deadly Test of Might} is 1:
				set slot 13 of the player's current inventory to 1 lapis block named "<light blue>A Deadly Test of Might" with lore "<white>Scouts from House Silgrid report that a large number of the undead are coming from Summoner's Sword, an old fortress from the days of the Great Heroes.", "<white>I need to eliminate the source of the monsters, and gather information on the root of this war if possible."
			else:
				set slot 13 of the player's current inventory to 1 redstone block named "<light red>A Deadly Test of Might" with lore "<white>Complete ""Liberation"" to unlock."
			#Threads of Fate
			if {quests.%player%::Threads of Fate} is 999:
				set slot 14 of the player's current inventory to 1 emerald block named "<green>Threads of Fate" with lore "<white>I've made it through ""The End"" and have arrived in Elrid, the land of eternal shadow.", "<white>I need to track down the source of the undead army and seal Elrid away for good."
			else if {quests.%player%::Threads of Fate} is 3:
				set slot 14 of the player's current inventory to 1 lapis block named "<light blue>Threads of Fate" with lore "<white>I've made it to ""The End"", but now I have the Dragon to worry about.", "<white>May the Greats light my path."
			else if {quests.%player%::Threads of Fate} is 2:
				set slot 14 of the player's current inventory to 1 lapis block named "<light blue>Threads of Fate" with lore "<white>Lord Kiln and Cinder have deduced that the ones responsible for the invasion hail from Elrid, the land of eternal shadow.", "<white>While it was originally sealed away by the Great Heroes, the seal seems to have been undone somehow.", "<white>I now need to storm the lands of Elrid with the power of the Holy Weapons in order to seal Elrid away once and for all.", "<white>I need to locate one of the old Strongholds, where I can find a portal to ""The End"", a gateway world separating Silgrund and Elrid."
			else if {quests.%player%::Threads of Fate} is 1:
				set slot 14 of the player's current inventory to 1 lapis block named "<light blue>Threads of Fate" with lore "<white>I've cleansed Summoner's Sword of the necromancer's fell magic.", "<white>Now, to return to Lord Kiln and chart our next course of action."
			else:
				set slot 14 of the player's current inventory to 1 redstone block named "<light red>Threads of Fate" with lore "<white>Complete ""A Deadly Test of Might"" to unlock."
			#Land of Shadow
			if {quests.%player%::Land of Shadow} is 999:
				set slot 15 of the player's current inventory to 1 emerald block named "<green>Land of Shadow" with lore "<white>I've found Salkaar Castle, where the leader of the undead army resides.", "<white>Now I must storm the castle and seal away this land once and for all."
			else if {quests.%player%::Land of Shadow} is 3:
				set slot 15 of the player's current inventory to 1 lapis block named "<light blue>Land of Shadow" with lore "<white>The corrupted Holy Weapon I picked up from one of the Fallen Heroes", "<white>showed me a vision of an imposing castle.", "<white>This castle must be the source of the undead."
			else if {quests.%player%::Land of Shadow} is 2:
				set slot 15 of the player's current inventory to 1 lapis block named "<light blue>Land of Shadow" with lore "<white>Cinder's gemstone has stopped working.", "<white>I need to find Salkaar Castle on my own."
			else if {quests.%player%::Land of Shadow} is 1:
				set slot 15 of the player's current inventory to 1 lapis block named "<light blue>Land of Shadow" with lore "<white>I've entered Elrid, the land of shadow.", "<white>I need to figure out where the leader of the undead is hiding.", "<white>But... where should I start looking?"
			else:
				set slot 15 of the player's current inventory to 1 redstone block named "<light red>Land of Shadow" with lore "<white>Complete ""Threads of Fate"" to unlock."
			#Inheritors of Light
			if {quests.%player%::Inheritors of Light} is 999:
				set slot 16 of the player's current inventory to 1 emerald block named "<green>Inheritors of Light" with lore "<white>Lord Cinder and Lord Alstair have been put back to rest.", "<white>Now, I must march to the throne room and see who's behind the invasion of Silgrund."
			else if {quests.%player%::Inheritors of Light} is 3:
				set slot 16 of the player's current inventory to 1 lapis block named "<light blue>Inheritors of Light" with lore "<white>Lord Alstair has been put back to rest.", "<white>Now I must defeat Cinder."
			else if {quests.%player%::Inheritors of Light} is 2:
				set slot 16 of the player's current inventory to 1 lapis block named "<light blue>Inheritors of Light" with lore "<white>Lord Cinder has been put back to rest.", "<white>Now I must defeat Alstair."
			else if {quests.%player%::Inheritors of Light} is 1:
				set slot 16 of the player's current inventory to 1 lapis block named "<light blue>Inheritors of Light" with lore "<white>The first Lords Cinder and Alstair have been resurrected through necromancy.", "<white>If the undead invasion is to be stopped, they must be slain."
			else:
				set slot 16 of the player's current inventory to 1 redstone block named "<light red>Inheritors of Light" with lore "<white>Complete ""Land of Shadow"" to unlock."
			#Light and Shadow
			if {quests.%player%::Light and Shadow} is 999:
				if {quests.%player%::Light and Shadow} is not set:
					set slot 17 of the player's current inventory to 1 emerald block named "<green>Light and Shadow" with lore "<white>The undead invasion has been stopped, but", "<white>Helmund escaped before I could land the killing blow.", "<white>While Silgrund should be at peace for many years now,", "<white>I can always return with more strength to try and chase after Helmund."
				else:
					set slot 17 of the player's current inventory to 1 emerald block named "<green>Light and Shadow" with lore "<white>The undead invasion has been stopped, but", "<white>Helmund escaped before I could land the killing blow.", "<white>The energy of the Great Heroes has given me enough strength to break", "<white>the magical barrier preventing me from chasing after Helmund.", "<white>It's time to finish what Cinder and my ancestor started."
			else if {quests.%player%::Light and Shadow} is 1:
				set slot 17 of the player's current inventory to 1 lapis block named "<light blue>Light and Shadow" with lore "<white>I entered the throne room and encountered the resurrected Helmund.", "<white>It's time to finish this, once and for all."
			else:
				set slot 17 of the player's current inventory to 1 redstone block named "<light red>Light and Shadow" with lore "<white>Complete ""Inheritors of Light"" to unlock."
			#Legacy
			if {quests.%player%::Legacy} is 999:
				set slot 18 of the player's current inventory to 1 emerald block named "<green>Legacy" with lore "<white>Helmund has been defeated, and Elrid has been sealed away for good.", "<white>Now, the Great Heroes can finally rest.", "<white>Lord Kiln says he wants to chat with me when I return home."
			else if {quests.%player%::Legacy} is 1:
				set slot 18 of the player's current inventory to 1 lapis block named "<light blue>Legacy" with lore "<white>I've chased Helmund to ""The End"".", "<white>He's resurrected all of the Great Heroes in a desperate bid to survive.", "<white>With the Holy Weapons at my side, I should have the strength to prevail."
			else:
				set slot 18 of the player's current inventory to 1 obsidian block named "<red>???" with lore "<white>This quest is unavailable."
			#Side Quests
			set slot 18 of the player's current inventory to 1 book named "<light blue>Side Quests:"
			#A Villager's Request
			if {quests.%player%::A Villager's Request} is 999:
				set slot 19 of the player's current inventory to 1 emerald block named "<green>A Villager's Request" with lore "<white>I investigated the strange boulder near Colony 9.", "<white>There, I found a small dungeon containing some sort of summoning rune.", "<white>The residents of Colony 9 were incredibly grateful for my help."
			else if {quests.%player%::A Villager's Request} is 998:
				set slot 19 of the player's current inventory to 1 obsidian named "<red>A Villager's Request" with lore "<white>My rudeness towards the villagers of Colony 9", "<white>has prevented me from investigating the strange boulder.", "<white>It won't do any good to go poking around there anymore."
			else if {quests.%player%::A Villager's Request} is 2:
				set slot 19 of the player's current inventory to 1 lapis block named "<light blue>A Villager's Request" with lore "<white>I found the source of the monsters inside the boulder and destroyed it.", "<white>I should inform the residents of Colony 9 that the summoning crystal has been destroyed."
			else if {quests.%player%::A Villager's Request} is 1:
				set slot 19 of the player's current inventory to 1 lapis block named "<light blue>A Villager's Request" with lore "<white>A resident of Colony 9 has asked me to investigate a strange boulder nearby."
			else:
				set slot 19 of the player's current inventory to 1 redstone block named "<light red>A Villager's Request" with lore "<white>Offer to ease a colonist's troubles."
			#Invisible Ties
			if {quests.%player%::Invisible Ties} is 999:
				set slot 20 of the player's current inventory to 1 emerald block named "<green>Invisible Ties" with lore "<white>Lord Kiln and I have become very close friends.", "<white>We now share a bond stronger than steel."
			else if {quests.%player%::Invisible Ties} is set:
				set slot 20 of the player's current inventory to 1 lapis block named "<light blue>Invisible Ties" with lore "<white>Lord Kiln seems to be making an effort to know me personally.", "<white>Who am I to deny his friendship?"
			else:
				set slot 20 of the player's current inventory to 1 redstone block named "<light red>Invisible Ties" with lore "<white>Ask Lord Kiln about his day."
			#Fuel for the Fire
			if {quests.%player%::Fuel for the Fire} is 999:
				set slot 21 of the player's current inventory to 1 emerald block named "<green>Fuel for the Fire" with lore "<white>I've returned the fuel needed for the refinery.", "<white>Now I can have my weapons refined and upgraded."
			else if {quests.%player%::Fuel for the Fire} is 3:
				set slot 21 of the player's current inventory to 1 lapis block named "<light blue>Fuel for the Fire" with lore "<white>I need to bring back 64 pieces of coal, and 16 blocks of magma to the blacksmith.", "<white>With the fuel, the blacksmith can reopen the weapon refinery."
			else if {quests.%player%::Fuel for the Fire} is 2:
				set slot 21 of the player's current inventory to 1 lapis block named "<light blue>Fuel for the Fire" with lore "<white>I found the shipment from Colony 6.", "<white>Unfortunately, all of the fuel is missing.", "<white>I can try and find fuel on my own, or tell the blacksmith about the shipment."
			else if {quests.%player%::Fuel for the Fire} is 1:
				set slot 21 of the player's current inventory to 1 lapis block named "<light blue>Fuel for the Fire" with lore "<white>A local blacksmith needs fuel to power the weapon refinery.", "<white>He's missing a shipment from Colony 6, which most likely got lost in the Dark Woods."
			else:
				set slot 21 of the player's current inventory to 1 redstone block named "<light red>Fuel for the Fire" with lore "<white>Ask a blacksmith about his forge."
			#Monster Hunt radiant quest
			if {quests.%player%::Monster Hunt} is 999:
				set slot 22 of the player's current inventory to 1 emerald block named "<green>Monster Hunt" with lore "<white>I've slain some of the monsters terrorizing the land to aid the people."
			else if {quests.%player%::Monster Hunt} is set:
				set slot 22 of the player's current inventory to 1 lapis block named "<light blue>Monster Hunt" with lore "<white>I need to slay some monsters to help the people of Silgrund.", "<white>Monsters slain: %{quests.%player%::Monster Hunt} - 1%/%{MHTarget.%player%}%"
			else:
				set slot 22 of the player's current inventory to 1 redstone block named "<light red>Monster Hunt" with lore "<white>Offer to go on a monster hunt."
			#Path of the Greats
			if {quests.%player%::Path of the Greats} is 999:
				set slot 23 of the player's current inventory to 1 emerald block named "<green>Path of the Greats" with lore "<white>A trainer from Nifl instructed me in Weapon Skills.", "<white>Now, I can have my weapons upgraded with all sorts of abilities if I take them to a blacksmith."
			else if {quests.%player%::Path of the Greats} is more than 1:
				set slot 23 of the player's current inventory to 1 lapis block named "<light blue>Path of the Greats" with lore "<white>Jorund instructed me in Weapon Skills.", "<white>I need to test them out by slaying monsters using them.", "<white>Monsters slain: %{quests.%player%::Path of the Greats} - 2%/10"
			else if {quests.%player%::Path of the Greats} is 1:
				set slot 23 of the player's current inventory to 1 lapis block named "<light blue>Path of the Greats" with lore "<white>Lord Kiln says that I'll need more training if I want to be worthy of wielding a Holy Weapon.", "<white>He's directed me towards a trainer, Jorund, in Nifl to learn how to use special Weapon Skills."
			else:
				set slot 23 of the player's current inventory to 1 redstone block named "<light red>Path of the Greats" with lore "<white>Speak with Galar after ""Seeking the Light""."
			#The Wizard of House Silgrid
			if {quests.%player%::The Wizard of House Silgrid} is 999:
				set slot 24 of the player's current inventory to 1 emerald block named "<green>The Wizard of House Silgrid" with lore "<white>After some persuasion by Cinder, Bramimund will summon Holy Weapons for me.", "<white>I can find him in the rightmost tower of House Silgrid."
			else if {quests.%player%::The Wizard of House Silgrid} is 1:
				set slot 24 of the player's current inventory to 1 lapis block named "<light blue>The Wizard of House Silgrid" with lore "<white>Cinder claims we need a Grand Wizard to help us find the rest of the Holy Weapons.", "<white>I remember reading about Bramimund, House Silgrid's wizard, before travelling here."
			else:
				set slot 24 of the player's current inventory to 1 redstone block named "<light red>The Wizard of House Silgrid" with lore "<white>Perform an Awakening."
			#An Apprentice's Plight
			if {quests.%player%::An Apprentice's Plight} is 999:
				set slot 25 of the player's current inventory to 1 emerald block named "<green>An Apprentice's Plight" with lore "<white>I helped a blacksmith's apprentice in Colony 8 with smithing a sword.", "<white>He's offered to repair my gear for a discount in return for my help."
			else if {quests.%player%::An Apprentice's Plight} is 1:
				set slot 25 of the player's current inventory to 1 lapis block named "<light blue>An Apprentice's Plight" with lore "<white>A local blacksmith's apprentice in Colony 8 is having trouble with his exam.", "<white>The apprentice needs 14 iron ingots, and 11 sticks to make the set of tools he needs to pass his exam."
			else:
				set slot 25 of the player's current inventory to 1 redstone block named "<light red>An Apprentice's Plight" with lore "<white>Visit the smithy at Colony 8."
			#The Enchanter
			if {quests.%player%::The Enchanter} is 999:
				set slot 26 of the player's current inventory to 1 emerald block named "<green>The Enchanter" with lore "<white>I helped Tim, an enchanter from the Northern Isles, build a new magic wand.", "<white>I can now buy enchanted books from him."
			else if {quests.%player%::The Enchanter} is 1:
				set slot 26 of the player's current inventory to 1 lapis block named "<light blue>The Enchanter" with lore "<white>I've met Tim, an enchanter from Colony 8.", "<white>After losing his magic wand, Tim has retired to the inn and started to drink away his sorrows.", "<white>If I bring a new magic wand to him, he'd be very grateful."
			else:
				set slot 26 of the player's current inventory to 1 redstone block named "<light red>The Enchanter" with lore "<white>Visit the inn at Colony 8."
			#The Dusty Palace
			if {quests.%player%::The Dusty Palace} is 999:
				set slot 27 of the player's current inventory to 1 emerald block named "<green>The Dusty Palace" with lore "<white>I excavated the palace inside the Yied Desert.", "<white>It turned out to be a large maze buried deep underground, guarding a tomb.", "<white>While there wasn't a Holy Weapon inside, there was plenty of expensive gemstones to go around.", "<white>I can't say if taking it is the right idea..."
			else if {quests.%player%::The Dusty Palace} is 2:
				set slot 27 of the player's current inventory to 1 lapis block named "<light blue>The Dusty Palace" with lore "<white>The temple from the rumor is real, and I've managed to find a way inside.", "<white>Unfortunately, said entrance was a large hole in the top of the temple.", "<white>I need to find the way out, but the hallways seem to have no end to them..."
			else if {quests.%player%::The Dusty Palace} is 1:
				set slot 27 of the player's current inventory to 1 lapis block named "<light blue>The Dusty Palace" with lore "<white>The innkeeper at Colony 7 told me a rumor relating to a temple in the area.", "<white>Supposedly, one of the Holy Weapons was sealed away inside.", "<white>This could be a huge help towards freeing Silgrund."
			else:
				set slot 27 of the player's current inventory to 1 redstone block named "<light red>The Dusty Palace" with lore "<white>Ask an innkeeper for the latest gossip."
			#A Helping Hand
			if {quests.%player%::A Helping Hand} is 999:
				set slot 28 of the player's current inventory to 1 emerald block named "<green>A Helping Hand" with lore "<white>I donated some supplies to the refugees of Colony 6.", "<white>They were very grateful, and will welcome any additional aid I can give them."
			else if {quests.%player%::A Helping Hand} is 1:
				set slot 28 of the player's current inventory to 1 lapis block named "<light blue>A Helping Hand" with lore "<white>The refugees from Colony 6 are in need of supplies.", "<white>Some basic building materials, like cobblestone and oak wood, should help them."
			else:
				set slot 28 of the player's current inventory to 1 redstone block named "<light red>A Helping Hand" with lore "<white>Speak to a group of refugees."
			#
			#Devils Never Cry
			if {quests.%player%::Devils Never Cry} is 999:
				set slot 29 of the player's current inventory to 1 emerald block named "<green>Devils Never Cry" with lore "<white>I helped a devil hunter named Tony Redgrave rescue his nephew Daniel Stuart from the depths of Harbindul.", "<white>Afterwards, the two vanished without a trace; but not before gifting me a set of weapons named ""Ebony and Ivory""."
			else if {quests.%player%::Devils Never Cry} is 1:
				set slot 29 of the player's current inventory to 1 lapis block named "<light blue>Devils Never Cry" with lore "<white>I found a mercenary named Tony Redgrave near the entrance to Harbindul.", "<white>One of his relatives, Daniel Stuart, dove into Harbindul in a personal crusade against the monsters there.", "<white>He's begrudgingly accepted my aid to rescue Daniel."
			else:
				set slot 29 of the player's current inventory to 1 redstone block named "<light red>Devils Never Cry" with lore "<white>Locate a mysterious, red-coated mercenary."
			#Requiem for the Brave
			if {quests.%player%::Requiem for the Brave} is 999:
				set slot 30 of the player's current inventory to 1 emerald block named "<green>Requiem for the Brave" with lore "<white>I've destroyed the heart of Harbindul, and freed the souls of the Mage Knights of Silgrid."
			else if {quests.%player%::Requiem for the Brave} is 1:
				set slot 30 of the player's current inventory to 1 lapis block named "<light blue>Requiem for the Brave"
			else:
				set slot 30 of the player's current inventory to 1 redstone block named "<light red>Requiem for the Brave" with lore "<white>Speak with Kiln's assistant after being promoted."
			#Previous Generation
			set slot 44 of the player's current inventory to 1 compass named "<white>Generation 1 Quests", "<white>You can view, but no longer complete these quests."
		else:
			open chest with 5 rows named "<gold>Quest Log" for the player
			#New Arrival
			if {quests.%player%::New Arrival} is 999:
				set slot 1 of the player's current inventory to 1 emerald block named "<green>New Arrival" with lore "<white>I've finished applying as a Knight.", "<white>I should head to the training grounds for my examination."
			else if {quests.%player%::New Arrival} is 1:
				set slot 1 of the player's current inventory to 1 lapis block named "<light blue>New Arrival" with lore "<white>After a long journey to House Aideen, I'm almost ready to become a Knight.", "<white>All I need to do now is complete my application."
			#Days of Training
			if {quests.%player%::Days of Training} is 999:
				set slot 2 of the player's current inventory to 1 emerald block named "<green>Days of Training" with lore "<white>I've completed my training, and now feel more confident in my combat skills."
			else if {quests.%player%::Days of Training} is 1:
				set slot 2 of the player's current inventory to 1 lapis block named "<light blue>Days of Training" with lore "<white>I should report to the training grounds for my evaluation.", "<white>They should be on the top floor of the castle."
			else if {quests.%player%::Days of Training} is 998:
				set slot 2 of the player's current inventory to 1 obsidian named "<red>Days of Training" with lore "<white>I decided to skip my training and aid Alstair as soon as I could."
			else:
				set slot 2 of the player's current inventory to 1 redstone block named "<light red>Days of Training" with lore "<white>Complete ""New Arrival"" to unlock."
			#Proving Grounds
			if {quests.%player%::Proving Grounds} is 999:
				set slot 3 of the player's current inventory to 1 emerald block named "<green>Proving Grounds" with lore "<white>I've slain the monsters hiding near the castle,", "<white>and proven my worth to Lord Alstair."
			else if {quests.%player%::Proving Grounds} is 998:
				set slot 3 of the player's current inventory to 1 obsidian named "<red>Proving Grounds" with lore "<white>Lord Alstair has allowed me to focus on other tasks instead of slaying monsters nearby."
			else if {quests.%player%::Proving Grounds} is set:
				set slot 3 of the player's current inventory to 1 lapis block named "<light blue>Proving Grounds" with lore "<white>Lord Alstair has tasked me with slaying monsters near the castle.", "<white>Monsters slain: %{quests.%player%::Proving Grounds} - 1%/10"
			else:
				set slot 3 of the player's current inventory to 1 redstone block named "<light red>Proving Grounds" with lore "<white>Complete ""Days of Training"" to unlock."
			#Thoughts to a Friend
			if {quests.%player%::Thoughts to a Friend} is 999:
				set slot 4 of the player's current inventory to 1 emerald block named "<green>Thoughts to a Friend" with lore "<white>I successfully delivered Alstair's letter,", "<white>and assisted Lord Cinder in saving a nearby village.", "<white>I've earned the favor of both lords now, it seems."
			else if {quests.%player%::Thoughts to a Friend} is 2:
				set slot 4 of the player's current inventory to 1 lapis block named "<light blue>Thoughts to a Friend" with lore "<white>I've arrived at House Silgrid, and delivered Alstair's letter.", "<white>Before I could leave, however, a nearby village has come under attack.", "<white>Cinder is rallying the troops to assist the village, and he has asked for my help as well."
			else if {quests.%player%::Thoughts to a Friend} is 1:
				set slot 4 of the player's current inventory to 1 lapis block named "<light blue>Thoughts to a Friend" with lore "<white>Alstair has sent me to Cinder's castle in Gallia to deliver a letter.", "<white>While not the most glamourous assignment, Alstair's orders are clear."
			else:
				set slot 4 of the player's current inventory to 1 redstone block named "<light red>Thoughts to a Friend" with lore "<white>Complete ""Proving Grounds"" to unlock."
			#The Time to Act
			if {quests.%player%::The Time to Act} is 999:
				set slot 4 of the player's current inventory to 1 emerald block named "<green>The Time to Act" with lore "<white>I've dispatched the monster threat, and Grann is safe once again.", "<white>I should get some rest and head home."
			else if {quests.%player%::The Time to Act} is 2:
				set slot 4 of the player's current inventory to 1 lapis block named "<light blue>The Time to Act" with lore "<white>Monsters are ambushing the town!", "<white>Now is the time to demonstrate the might of the Knights of Aideen!."
			else if {quests.%player%::The Time to Act} is 1:
				set slot 4 of the player's current inventory to 1 lapis block named "<light blue>The Time to Act" with lore "<white>After a long day of travel and battle, it's time to return home.", "<white>There should be an inn to rest at inside Grann, located inside the dark forest."
			else:
				set slot 4 of the player's current inventory to 1 redstone block named "<light red>The Time to Act" with lore "<white>Complete ""Thoughts to a Friend"" to unlock."

on right click with book:
	if the name of the event-item is "<gold>Journal":
		if {generation.%player%} is 1:
			make player execute command "/quests 1"
		else:
			make player execute command "/quests 2"
	else if the name of the event-item is "<gold>Quest Log":
		if {generation.%player%} is 1:
			make player execute command "/quests 1"
		else:
			make player execute command "/quests 2"