#
command /salindrum:
	aliases: /void, /training, /testroom, /sd
	trigger:
		if {sd.rewarp.%player%} is set:
			open chest inventory with 2 rows named "<red>Salindrum Configuration" for the player
			set slot 0 of the player's current inventory to 1 nether star named "<gold>Exit Salindrum" with lore "<white>Click to exit the training mode."
			set slot 1 of the player's current inventory to 1 zombie spawn egg named "<white>Spawn Monsters" with lore "<white>Generate a variety of monsters to practice with."
			set slot 2 of the player's current inventory to 1 iron sword named "<white>Test Skills" with lore "<white>Equip any unlocked skills for free."
			set slot 3 of the player's current inventory to 1 diamond sword named "<white>Test Sacred Treasures" with lore "<white>Try out one of the Sacred Treasures."
			set slot 8 of the player's current inventory to 1 tnt named "<white>Reset Session" with lore "<white>Resets the session back to when you entered."
			set slot 7 of the player's current inventory to 1 totem of undying named "<white>Damage Modifiers" with lore "<white>Fine-tune how much damage you take from and deal to foes."
			set slot 4 of the player's current inventory to 1 anvil named "<white>Fix Equipment" with lore "<white>Click to repair any damaged items in your inventory."
			set slot 5 of the player's current inventory to 1 chest named "<white>Supply Crate" with lore "<white>Borrow weapons and ammo here."
			if {sd.nohunger.%player%} is true:
				set slot 6 of the player's current inventory to 1 steak named "<white>Infinite Hunger: ON" with lore "<white>Your hunger bar won't decrease.", "<white>Click to toggle."
			else:
				set slot 6 of the player's current inventory to 1 rotten flesh named "<white>Infinite Hunger: OFF" with lore "<white>Your hunger bar will decrease normally.", "<white>Click to toggle."
			set slot 9 of the player's current inventory to 1 workbench named "<white>Combat Calculator" with lore "<white>Run a variety of calculations on your weapons."
			if {sd.infabilities.%player%} is true:
				set slot 10 of the player's current inventory to 1 iron chestplate named "<white>Max Abilities: ON" with lore "<white>You can wield any weapon with no penalty.", "<white>Click to toggle."
			else:
				set slot 10 of the player's current inventory to 1 iron chestplate named "<white>Max Abilities: OFF" with lore "<white>Your weapon abilities are unchanged.", "<white>Click to toggle."
		else:
			open chest inventory with 2 rows named "<red>Select a room." for the player
			set {_roomnum} to 0
			loop {sd::*}:
				add 1 to {_roomnum}
				if loop-value is not 0:
					set slot ({_roomnum} - 1) of the player's current inventory to 1 redstone block named "<red>Room %{_roomnum}%" with lore "<white>Occupant: %{sd::Room %{_roomnum}%}%"
				else:
					set slot ({_roomnum} - 1) of the player's current inventory to 1 lapis block named "Room %{_roomnum}%" with lore "<white>Empty Room"
				
command /sdsupplies:
	trigger:
		open chest inventory with 4 rows named "<red>Supply Crate" for the player
		set slot 0 of the player's current inventory to 1 wooden sword of unbreaking 100
		set slot 1 of the player's current inventory to 1 stone sword of unbreaking 100
		set slot 2 of the player's current inventory to 1 iron sword of unbreaking 100
		set slot 3 of the player's current inventory to 1 gold sword of unbreaking 100
		set slot 4 of the player's current inventory to 1 diamond sword of unbreaking 100
		set slot 5 of the player's current inventory to 1 wooden axe of unbreaking 100
		set slot 6 of the player's current inventory to 1 stone axe of unbreaking 100
		set slot 7 of the player's current inventory to 1 iron axe of unbreaking 100
		set slot 8 of the player's current inventory to 1 gold axe of unbreaking 100
		set slot 9 of the player's current inventory to 1 diamond axe of unbreaking 100
		set slot 10 of the player's current inventory to 1 wooden shovel of unbreaking 100 named "<bold>Wooden Lance"
		set slot 11 of the player's current inventory to 1 stone shovel of unbreaking 100 named "<bold>Stone Lance"
		set slot 12 of the player's current inventory to 1 iron shovel of unbreaking 100 named "<bold>Iron Lance"
		set slot 13 of the player's current inventory to 1 gold shovel of unbreaking 100 named "<bold>Golden Lance"
		set slot 14 of the player's current inventory to 1 diamond shovel of unbreaking 100 named "<bold>Diamond Lance"
		set slot 15 of the player's current inventory to 1 bow of unbreaking 100
		set slot 16 of the player's current inventory to 1 iron horse armor named "<light gray>Flintlock Pistol" with lore "<white>Slot A - Empty", "<white>Slot B - Empty", "<white>Slot C - Empty", "<white>Assist - Empty", "<white>Special - Empty", "<white>Refine - N/A", "<white><bold>Clip (MAX: 1):", "1"
		set slot 17 of the player's current inventory to 1 iron horse armor named "<light gray>Iron Musket" with lore "<white>Slot A - Empty", "<white>Slot B - Empty", "<white>Slot C - Empty", "<white>Assist - Empty", "<white>Special - Empty", "<white>Refine - N/A", "<white><bold>Clip (MAX: 1):", "1"
		set slot 18 of the player's current inventory to 1 iron horse armor named "<light gray>Iron Pistol" with lore "<white>Slot A - Empty", "<white>Slot B - Empty", "<white>Slot C - Empty", "<white>Assist - Empty", "<white>Special - Empty", "<white>Refine - N/A", "<white><bold>Clip (MAX: 8):", "8"
		set slot 19 of the player's current inventory to 1 iron horse armor named "<light gray>Redstone Repeater" with lore "<white>Slot A - Empty", "<white>Slot B - Empty", "<white>Slot C - Empty", "<white>Assist - Empty", "<white>Special - Empty", "<white>Refine - N/A", "<white><bold>Clip (MAX: 30):", "30"
		set slot 20 of the player's current inventory to 1 iron horse armor named "<light gray>E-45s" with lore "<white>Slot A - Empty", "<white>Slot B - Empty", "<white>Slot C - Empty", "<white>Assist - Empty", "<white>Special - Empty", "<white>Refine - N/A", "<white><bold>Clip (MAX: 18):", "18"
		set slot 21 of the player's current inventory to 1 golden horse armor named "<light gray>Redgrave Sawn-Off" with lore "<white>Slot A - Empty", "<white>Slot B - Empty", "<white>Slot C - Empty", "<white>Assist - Empty", "<white>Special - Empty", "<white>Refine - N/A", "<white><bold>Clip (MAX: 5):", "5"
		set slot 22 of the player's current inventory to 64 arrow
		set slot 23 of the player's current inventory to 64 arrow
		set slot 24 of the player's current inventory to 64 iron nugget
		set slot 25 of the player's current inventory to 64 iron nugget
		set slot 26 of the player's current inventory to 64 gold nugget
		set slot 27 of the player's current inventory to 64 gold nugget
		set slot 28 of the player's current inventory to 64 gunpowder
		set slot 29 of the player's current inventory to 64 gunpowder
		set slot 34 of the player's current inventory to 1 chest named "<bold>Restock Supply Crate"
		set slot 35 of the player's current inventory to 1 red glass pane named "<bold>Go Back"

command /sdmults:
	trigger:
		open chest inventory with 2 rows named "<red>Damage Modifiers" for the player
		set slot 4 of the player's current inventory to 1 iron sword named "<light green>Damage Dealt" with lore "<white>Current Modifier: %{sd.outgoingmult.%player%}%x"
		set slot 3 of the player's current inventory to 1 red glass pane named "<light red>Decrease Damage Dealt by 0.1x"
		set slot 5 of the player's current inventory to 1 light green glass pane named "<light green>Increase Damage Dealt by 0.1x"
		set slot 13 of the player's current inventory to 1 iron chestplate named "<light red>Damage Taken" with lore "<white>Current Modifier: %{sd.incomingmult.%player%}%x"
		set slot 12 of the player's current inventory to 1 red glass pane named "<light red>Decrease Damage Taken by 0.1x"
		set slot 14 of the player's current inventory to 1 light green glass pane named "<light green>Increase Damage Taken by 0.1x"
		set slot 17 of the player's current inventory to 1 hopper named "<light yellow>Reset Damage Taken Multiplier"
		set slot 8 of the player's current inventory to 1 hopper named "<light yellow>Reset Damage Dealt Multiplier"
		set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		set slot 9 of the player's current inventory to 1 red glass pane named "<bold>Go Back"

command /sdcalcs:
	trigger:
		open chest inventory with 2 rows named "<red>Calculator" for the player
		set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		set slot 9 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		set slot 4 of the player's current inventory to 1 purple wool named "<gold>Special Odds" with lore "<white>Special Skill: %{sd.calcSpecial.%player%}%", "<white>Base Activation Chance: %{sd.calcOdds.%player%}%", "<white>Highest Possible Chance: %{sd.calcMaxOdds.%player%}%", "<white>SKL Needed To Cap: %{sd.calcMaxSKL.%player%}%", "<white>Critical Chance: %{sd.calcCritChance.%player%}%", "<white>Max Unbuffed Crit Chance: %{sd.calcMaxCritChance.%player%}%"
		set slot 5 of the player's current inventory to 1 splash potion of harming named "<gold>Damage Output" with lore "<white>Base Damage: %{sd.calcBaseDamage.%player%}%", "<white>With Skills & No Special: %{sd.calcSkillsDamage.%player%}%", "<white>With Skills & Special: %{sd.calcSpecialDamage.%player%}%", "<white>Maximum Damage Possible (With Double): %{sd.calcMaxDamage.%player%}%", "<white>Can Double Foes Below: %{sd.calcPlayerDoubleRange.%player%}% SPD", "<white>Foes Double From: %{sd.calcFoeDoubleRange.%player%}%+ SPD"
		set slot 13 of the player's current inventory to 1 book named "<gold>How to Use" with lore "<white>Click a weapon to add it to the calculator.", "<white>Click the "Calculate" button to view detailed info on your weapon.", "<white>Damage assumes foe has no equipment, and is a player.", "<white>Bows are assumed to deal a base damage of 3.5."
		set slot 8 of the player's current inventory to 1 workbench named "<gold>Calculate" with lore "<white>Click to run calculations on the selected weapon."
command /sdsetup <number> <number> <number> <number>:
	trigger:
		set {sd.room %arg 1%} to location at (arg 2, arg 3, arg 4) in world "Salindrum"
		set {sd::room %arg 1%} to 0
		send "<light green>Set Room %arg 1% coordinates to %arg 2%, %arg 3%, %arg 4%."
		
command /sdmonsters:
	trigger:
		open chest inventory with 6 rows named "<red>Spawn Monsters" for the player
		set slot 0 of the player's current inventory to 1 zombie spawn egg named "<white>Zombie" with lore "<white>An innocent soul reawakened via fell magic.", "<white>They move slowly, but have high attack power.", "<white>Occasionally, they can pick up fallen weapons and armour."
		set slot 1 of the player's current inventory to 1 skeleton spawn egg named "<white>Skeleton" with lore "<white>An innocent soul reawakened via fell magic.", "<white>The flesh has completely rotted, leaving nothing but an exposed skeleton.", "<white>Scrappy but fragile, skeletons prefer bows to harass their victims at range."
		set slot 2 of the player's current inventory to 1 spider spawn egg named "<white>Spider" with lore "<white>One of many beasts summonable by dark mages.", "<white>Spiders move quickly and can climb walls, but lack in damage output."
		set slot 3 of the player's current inventory to 1 creeper spawn egg named "<white>Creeper" with lore "<white>A rather odd beast summonable by dark mages.", "<white>Singling out their target, they rush in and detonate themselves for massive damage.", "<white>They can become supercharged via lightning."
		set slot 4 of the player's current inventory to 1 husk spawn egg named "<white>Husk" with lore "<white>The dusty remains of a deserted wanderer.", "<white>Their corrosive bites can pierce through armour and poison victims."
		set slot 5 of the player's current inventory to 1 witch spawn egg named "<white>Witch" with lore "<white>A dark mage from Elrid.", "<white>They choose to battle indirectly, utilizing various potions."
		set slot 6 of the player's current inventory to 1 enderman spawn egg named "<white>Enderman" with lore "<white>A shadowy creature born of "The End".", "<white>They possess teleportation capabilities, and strike using vicious magical attacks."
		set slot 7 of the player's current inventory to 1 cave spider spawn egg named "<white>Cave Spider" with lore "<white>A rarer version of the Spider.", "<white>These smaller spiders are much faster and can poison unsuspecting adventurers."
		set slot 8 of the player's current inventory to 1 evoker spawn egg named "<white>Evoker" with lore "<white>A summonder from Elrid.", "<white>They utilize various spells to attack, and are capable of summoning familiars for assistance."
		set slot 9 of the player's current inventory to 1 vex spawn egg named "<white>Vex" with lore "<white>Weak summonable familiars.", "<white>These maligned spirits fly about and attack as a pack.", "<white>Their weak nature makes them easy to dispel with sweeping attacks."
		set slot 10 of the player's current inventory to 1 vindicator spawn egg named "<white>Vindicator" with lore "<white>Axe-wielding infantry from Elrid.", "<white>Their skills are second to none; adventurers must exercise extreme caution in their presence."
		set slot 11 of the player's current inventory to 1 slime spawn egg named "<white>Slime" with lore "<white>A weak familiar.", "<white>They attack by hopping into and absorbing their targets.", "<white>After dying, Slimes split into multiple smaller copies."
		set slot 12 of the player's current inventory to 1 stray spawn egg named "<white>Stray" with lore "<white>Icey remains of a Nifilian bow knight.", "<white>Their frosted arrows freeze those unlucky enough to be struck."
		set slot 13 of the player's current inventory to 1 zombie spawn egg of power 1 named "<white>Zombie Mimic" with lore "<white>An incredibly dangerous variety of Zombie.", "<white>When struck, these thralls take on the likeness of their aggressor; increasing their strength to match."
		set slot 14 of the player's current inventory to 1 skeleton spawn egg of power 1 named "<white>Skeleton Mimic" with lore "<white>An incredibly dangerous variety of Skeleton.", "<white>When struck, these thralls take on the likeness of their aggressor; increasing their strength to match."
		set slot 15 of the player's current inventory to 1 creeper spawn egg of power 1 named "<white>Skulker" with lore "<white>A faster and more explosive variant of the Creeper."
		set slot 16 of the player's current inventory to 1 spider spawn egg of power 1 named "<white>Venom Spider" with lore "<white>A highly venomous type of spider.", "<white>Unlike their cave-dwelling bretheren, these spiders' poison is strong enough to kill."
		set slot 17 of the player's current inventory to 1 husk spawn egg of power 3 named "<white>Malediction" with lore "<white>An incredibly rare foe that can generate multiple copies of itself when in a pinch."
		set slot 18 of the player's current inventory to 1 stray spawn egg of power 3 named "<white>Enrapture" with lore "<white>Dangerous variation of the Skeleton that binds foes in place with fell magic.", "<white>Their arrows are to be avoided at all costs."
		set slot 19 of the player's current inventory to 1 spider spawn egg of power 3 named "<white>Shadow" with lore "<white>A powerful beast that has escaped from its master's control.", "<white>They can render themselves invisible in order to attack their prey."
		set slot 20 of the player's current inventory to 1 zombie spawn egg of power 5 named "<white>Regret" with lore "<white>An Elridian dark mage capable of creating thralls.", "<white>They periodically summon Zombies and Skeletons to aid them in combat."
		set slot 21 of the player's current inventory to 1 witch spawn egg of power 5 named "<white>Fury" with lore "<white>A spellcaster that has mastered the art of summoning.", "<white>They can generate an unlimited number of Blazes to assist them.", "<white>The power they wield is unstable, however, and when control is lost they will explode violently."
		set slot 22 of the player's current inventory to 1 creeper spawn egg of power 5 named "<white>Stalker" with lore "<white>A horribly volatile variation of the Creeper with tremendous explosive power.", "<white>Only one hit is required to set off its village-clearing explosion."
		set slot 23 of the player's current inventory to 1 wither skeleton spawn egg named "<white>Wither Skeleton" with lore "<white>Charred remains of one of the Grand Wizards' protectors.", "<white>With no master to control them, they wander Harbindul in search of salvation.", "<white>Their rusted blades inflict terrible poisons upon any who touch them."
		set slot 24 of the player's current inventory to 1 blaze spawn egg named "<white>Blaze" with lore "<white>A flame summon born from the fires of Harbindul.", "<white>They are able to fly and launch fireballs at their targets."
		set slot 25 of the player's current inventory to 1 zombie pigman spawn egg named "<white>Zombie Pigman" with lore "<white>Livestock corrupted by the fires of Harbindul.", "<white>Operating solely upon instinct, their wild and savage blows are a force to be feared.", "<white>Curiously, they have a strong love for gold."
		set slot 26 of the player's current inventory to 1 zombie spawn egg of power 7 named "<white>Zombie Purgia" with lore "<white>Powerful thralls on the brink of escape from their masters.", "<white>Retaining their abilities from their past life, these Zombies possess highly advanced tactics.", "<white>They can release blasts of energy to knock away foes, at the cost of their own health."
		set slot 27 of the player's current inventory to 1 skeleton spawn egg of power 7 named "<white>Skeleton Purgia" with lore "<white>Powerful thralls on the brink of escape from their masters.", "<white>Skeleton Purgias are born from only the strongest of bow-wielding knights.", "<white>Their arrows are strong enough to pierce directly through armour and severly wound whoever becomes their victim."
		set slot 28 of the player's current inventory to 1 creeper spawn egg of power 7 named "<white>Creeper Purgia" with lore "<white>One of the many Purgia-class thralls from Elrid.", "<white>Their explosions leave a debilitating aura that weakens all who come in contact with it."
		set slot 29 of the player's current inventory to 1 zombie pigman spawn egg of power 7 named "<white>Pigman Purgia" with lore "<white>Resurrected corruptions from Harbindul.", "<white>The massive amount of magical energy used to maintain this thrall grant it immesurable strength.", "<white>It is easily identifiable via its solid-gold armour.", "<white>Their flaming bodies ignite all who come in contact with them."
		set slot 30 of the player's current inventory to 1 evoker spawn egg of power 7 named "<white>Purgia Invoker" with lore "<white>One of Elrid's finest necromancers.", "<white>Able to summon a multitude of Purgia to assist in battle.", "<white>Purgia Invokers may attempt to drain the life force of their foes in a pinch.", "<white>Rumors claim they are not past turning their powers against themselves if it means ensuring victory."
		set slot 31 of the player's current inventory to 1 zombie spawn egg of power 8 named "<white>Crusader Purgia" with lore "<white>A diamond-clad thrall with superb combat prowess.", "<white>This particular Purgia acts independently of its master, almost as if it's not a thrall at all...", "<white>They possess the abilities of all other Purgia combined."
		set slot 34 of the player's current inventory to 1 zombie spawn egg of power 10 named "<red><bold>Fallen Hero" with lore "<white>The defiled corpse of one of the Great Heroes.", "<white>Wielding corrupted variants of their signature weapons, these fell thralls have only one command: kill all who defy the Leader's desires.", "<white>Battles against these thralls are to be avoided at all costs."
		set slot 32 of the player's current inventory to 1 zombie spawn egg of fortune 5 named "<gold>Treasure Zombie" with lore "<white>A rather quirky summon comprised of various treasures.", "<white>Their attacks are very weak, but being made of solid gold grants them great durability."
		set slot 33 of the player's current inventory to 1 skeleton spawn egg of fortune 5 named "<gold>Treasure Skeleton" with lore "<white>A rather quirky summon comprised of various treasures.", "<white>Their attacks are very weak, but being made of solid gold grants them great durability."
		if {sd.dolevelscaling.%player%} is true:
			set slot 52 of the player's current inventory to 1 lapis block named "<light blue>Level Scaling" with lore "<white>Monsters summoned will scale to your level.", "<white>Click to disable."
		else:
			set slot 52 of the player's current inventory to 1 redstone block named "<light red>Level Scaling" with lore "<white>Monsters summoned will NOT scale to your level.", "<white>Click to enable."
		set slot 51 of the player's current inventory to 1 book named "<white>Summoning Info:" with lore "<white>Summoned monsters will appear at this room's spawn point.", "<white>Only one monster can be summoned at once.", "<white>You will not recieve XP and money for defeating summoned monsters."
		set slot 53 of the player's current inventory to 1 red glass pane named "<white>Salindrum Menu"

command /sdhw <number>:
	trigger:
		if arg 1 is 9:
			open chest inventory with 1 row named "<red><bold>Salindrum - Select Weapon Class" for the player
			set slot 0 of the player's current inventory to 1 iron sword named "<gold>Swords"
			set slot 1 of the player's current inventory to 1 iron axe named "<gold>Axes"
			set slot 2 of the player's current inventory to 1 iron shovel named "<gold>Lances"
			set slot 3 of the player's current inventory to 1 bow named "<gold>Bows"
			set slot 4 of the player's current inventory to 1 arrow named "<gold>Daggers"
			set slot 5 of the player's current inventory to 1 iron hoe named "<gold>Gauntlets"
		else:
			open chest inventory with 6 rows named "<red><bold>Salindrum - Sacred Treasures" for the player
			#Swords
			if arg 1 is 0:
				set slot 0 of the player's current inventory to 1 diamond sword named "<gold><bold>Falchion" with nbt "{bakedRefine:776,sacredTreasureID:0}" with lore "<white>Grants increased damage the farther away you are from your foe during combat.", "<white>Deals effective damage to end-type foes.", "<light green>Unique Refine:", "<light green>Grants STR/MAG/SPD/LCK/DEF/RES +4 to allies within 15 blocks during combat.", "<white>Weapon Ability: +30"
				set slot 1 of the player's current inventory to 1 diamond sword named "<gold><bold>Binding Blade" with nbt "{bakedRefine:776,sacredTreasureID:1}" with lore "<white>+4 weapon might.", "<white>If foe initiates combat, grants DEF/RES +6 during that combat.", "<white>Deals effective damage to end-type foes.", "<light green>Unique Refine:", "<light green>Reduces damage suffered by 20%% during combat.", "<light green>Grants <light blue>[Quick Riposte]<light green>.", "<light blue>[Quick Riposte]: <white>Automatically counter-attack foes during combat.", "<white>Quick Riposte's effect only activates if foe is in range.", "<white>Weapon Ability: +30"
				set slot 2 of the player's current inventory to 1 diamond sword named "<gold><bold>Tyrfing" with nbt "{bakedRefine:776,sacredTreasureID:2}" with lore "<white>+4 weapon might.", "<white>Reduces ranged damage suffered by 25%%.", "<white>Grants <light purple>[Miracle]<white>.", "<light green>Unique Refine:", "<light green>Grants MAG/RES +10, SPD/LCK +5 during combat.", "<light purple>[Miracle]: <white>Nullifies foe's attack if it would kill the player during combat.", "<white>Activation chance: (LCK * 0.5)", "<white>Max: 50%%", "<white>Weapon Ability: +30"
				set slot 3 of the player's current inventory to 1 diamond sword named "<gold><bold>Ragnell" with nbt "{bakedRefine:776,sacredTreasureID:3}" with lore "<white>+8 weapon might.", "<white>Grants <light purple>[Radiant Aether].", "<light green>Unique Refine:", "<light green>+4 weapon might (+12 total).", "<light green>Grants <light red>[Distant Counter]<light green>.", "<light red>[Distant Counter]: <white>Counter-attack ranged foes automatically when hit.", "<light purple>[Radiant Aether]: <white>Activate Luna and Sol in one strike.", "<white>Exclusive to Ragnell.", "<white>Weapon Ability: +65"
				set slot 4 of the player's current inventory to 1 diamond sword named "<gold><bold>Light Brand" with nbt "{bakedRefine:776,sacredTreasureID:4}" with lore "<white>+2 weapon might.", "<white>Grants LCK +10 during combat.", "<white>Damage from this weapon is calculated using the", "<white>lower of the foe's DEF or RES, and, if targeting RES,", "<white>treats the player's MAG as their STR during damage calculation.", "<light green>Unique Refine:", "<light green>If foe's HP = 100%% at start of combat:", "<light green>Grants STR/MAG/SPD/DEF +4 and <light red>[Armour Smasher]<light green>.", "<white>Weapon Ability: +45"
				set slot 5 of the player's current inventory to 1 diamond sword named "<gold><bold>Mystletainn" with nbt "{bakedRefine:776,sacredTreasureID:5}" with lore "<white>+4 weapon might.", "<white>Grants LCK +10 during combat.", "<white>If HP < 70%%, grants LCK +10, and deals +5 damage when Special activates.", "<light green>Unique refine:", "<light green>Grants <light red>[Fury]<light green> during combat.", "<white>Weapon Ability: +50"
				set slot 6 of the player's current inventory to 1 diamond sword named "<gold><bold>Tornado Blade" with nbt "{bakedRefine:776,sacredTreasureID:6}" with lore "<white>Grants <gold>[Distant Counter]<white>.", "<gold>[Distant Counter]<white>: Automatically retaliate against ranged opponents.", "<white>Weapon Ability: +19"
				set slot 7 of the player's current inventory to 1 diamond sword named "<gold><bold>Kindled-Fire Sword" with nbt "{bakedRefine:776,sacredTreasureID:7}" with lore "<white>Grants <light blue>[Brave Blade]<white>.", "<white>If player's HP >= foe's HP -3:", "<white>Grants STR/DEF +7 during combat.", "<light green>Unique Refine:", "<light green>If any ally within 15 blocks shares the wielder's class:", "<light green>Grants STR/DEF +12.",  "<white>Weapon Ability: +35"
				set slot 8 of the player's current inventory to 1 diamond sword named "<gold><bold>Monado" with nbt "{bakedRefine:776,sacredTreasureID:40}" with lore "<white>When this weapon triggers a Finishing Blow,", "<white>the Monado Arts gauge is filled by 1/3.", "<white>When the Monado Arts gague is full, right-click with the Monado Art you want to use.", "<white>Enchant: Grants STR/MAG +10 to party for 10 seconds.", "<white>Buster: Grants STR/MAG +20 through next action (player only).", "<white>Speed: Grants SPD/LCK +10 to party for 10 seconds.", "<white>Shield: Grants DEF/RES +10 for 10 seconds.", "<white>Eater: Inflicts STR/MAG/DEF/RES -10 on foes within 10 blocks through next action.", "<white>Weapon Ability: +60"
				set slot 9 of the player's current inventory to 1 diamond sword named "<gold><bold>Yamato" with nbt "{bakedRefine:776,sacredTreasureID:41}" with lore "<white>Sneak + Right-Click to use Judgement Cut,", "<white>which attacks the nearest foe within 8 blocks with magical damage.", "<white>Judgement Cut triggers instantly when airborne.", "<white>If in Devil Trigger state, upgrades Judgement Cut into", "Judgement Cut End, which heavily damages all foes within 15 blocks.", "<white>Using Judgement Cut End immediately drains the DT gauge.", "<white>Weapon Ability: +60"
			#Axes
			else if arg 1 is 1:
				set slot 0 of the player's current inventory to 1 diamond axe named "<gold><bold>Armads" with nbt "{bakedRefine:776,sacredTreasureID:8}" with lore "<white>+6 weapon might.", "<white>Grants <light red>[Distant Counter]<white>.", "<light green>Unique Refine:", "<light green>Reduces damage from ranged attacks by 40%%.", "<light green>Grants <light blue>[Quick Riposte]<light green>.", "<light red>[Distant Counter]: <white>Counter-attack ranged foes automatically when hit.", "<light blue>[Quick Riposte]: <white>Automatically counter-attack foes during combat.", "<white>Riposte's effect only activates if foe is in range.", "<white>Weapon Ability: +50"
				set slot 1 of the player's current inventory to 1 diamond axe named "<gold><bold>Basilikos" with nbt "{bakedRefine:776,sacredTreasureID:9}" with lore "<white>+9 weapon might.", "<white>Grants STR/SPD +7, inflicts DEF/RES -5 during combat.", "<light green>Unique Refine:", "<light green>Increases damage dealt and suffered during combat by 50%%.", "<light red>Weapon Ability: +23"
				set slot 2 of the player's current inventory to 1 diamond axe named "<gold><bold>Hauteclere" with nbt "{bakedRefine:776,sacredTreasureID:10}" with lore "<white>+3 weapon might.", "<white>Grants LCK +10 while equipped.", "<white>Accelerates Special skill activation (+15%% activation chance).", "<light green>Unique Refine:", "<light green>Accelerates Special trigger (+5%% activation chance).", "<light green>If Special activates, increases damage dealt by 2.5 hearts.", "<white>Weapon Ability: +50"
				set slot 3 of the player's current inventory to 1 diamond axe named "<gold><bold>Tomahawk" with nbt "{bakedRefine:776,sacredTreasureID:11}" with lore "<white>Grants <gold>[Distant Counter]<white>.", "<gold>[Distant Counter]<white>: Automatically retaliate against ranged opponents.", "<white>Weapon Ability: +19"
				set slot 4 of the player's current inventory to 1 diamond axe named "<gold><bold>Daybreak" with nbt "{bakedRefine:776,sacredTreasureID:12}" with lore "<white>Grants DEF/RES +4 during combat.", "<white>When initiating combat, restores 6 HP.", "<light green>Unique Refine:", "<light green>Restores health equal to 25%% of damage dealt during combat.", "<light green>If a Special skill activates and deals damage:", "<light green>Restores health equal to 30%% of damage dealt.", "<white>Weapon Ability: +60"
				set slot 5 of the player's current inventory to 1 diamond axe named "<gold><bold>Goddess's Axe" with nbt "{bakedRefine:776,sacredTreasureID:13}" with lore "<white>Grants STR/DEF +4 during combat.", "<white>Inflicts SPD/RES -4 during combat.", "<white>Grants <light blue>[Brave Blade]<reset> during combat.", "<light green>Unique Refine:", "<light green>If player's HP <= 75%% and foe initiates combat:", "<light green>Player counter-attacks automatically before foe's attack.", "<light green>Foe must be using a melee weapon, or player must have Counter equipped.", "<white>Weapon Ability: +50"
				set slot 6 of the player's current inventory to 1 diamond axe named "<gold><bold>Arthur's Axe" with nbt "{bakedRefine:776,sacredTreasureID:14}" with lore "<white>Boosts Critical Dodge chance by 35%% during combat.", "<white>Raises Critical Miss chance by 20%% during combat.", "<white>If player initiates combat and does not Critically Miss,", "<white>boosts damage dealt by 15%% and grants DEF/RES +7 through player's next action.", "<white>If foe initiates combat and player Critically Dodges,", "<white>grants STR/SPD/LCK +7 through player's next action.", "<white>Weapon Ability: +50"
			#Lances
			else if arg 1 is 2:
				set slot 0 of the player's current inventory to 1 diamond shovel named "<gold><bold>Siegmund" with nbt "{bakedRefine:776,sacredTreasureID:15}" with lore "<white>+5 weapon might.", "<white>Grants <light green>[Rally Strength]<white>.", "<light green>Unique Refine:", "<light green>If number of foes >= number of allies within 10 blocks:", "<light green>Weapon attacks twice during combat.", "<light green>[Rally Strength]: <white>Grants Strength 2 to allies when right-clicked.", "<white>Weapon Ability: +40"
				set slot 1 of the player's current inventory to 1 diamond shovel named "<gold><bold>Gae Bolg" with nbt "{bakedRefine:776,sacredTreasureID:16}" with lore "<white>Grants STR/DEF/SKL +4 during combat.", "<white>Grants <light blue>[Guard]<white>.", "<light blue>[Guard]: <white>Inflicts LCK -50 on foe during combat.", "<white>Weapon Ability: +30"
				set slot 2 of the player's current inventory to 1 diamond shovel named "<gold><bold>Gradivus" with nbt "{bakedRefine:776,sacredTreasureID:17}" with lore "<white>+4 weapon might.", "<white>Grants <light blue>[Experience Sapper]<white>.", "<light blue>[Experience Sapper]: <white>Increases EXP awarded for defeating foes.", "<white>Weapon Ability: +19"
				set slot 3 of the player's current inventory to 1 diamond shovel named "<gold><bold>Rex Hasta" with nbt "{bakedRefine:776,sacredTreasureID:18}" with lore "<white>Increases damage dealt by Special activations by 10 hearts.", "<light green>Unique Refine:", "<light green>Grants <light blue>[Wrath]<light green>.", "<light green>If Special skill activates, boosts damage dealt by 25%%.", "<white>Weapon Ability: +40"
				set slot 4 of the player's current inventory to 1 diamond shovel named "<gold><bold>Rhomphaia" with nbt "{bakedRefine:776,sacredTreasureID:19}" with lore "<white>Deals bonus damage equal to 25%% of the player's SPD.", "<white>Weapon Ability: +60"
				set slot 5 of the player's current inventory to 1 diamond shovel named "<gold><bold>Javelin" with nbt "{bakedRefine:776,sacredTreasureID:20}" with lore "<white>Grants <gold>[Distant Counter]<white>.", "<gold>[Distant Counter]<white>: Automatically retaliate against ranged opponents.", "<white>Weapon Ability: +19"
				set slot 6 of the player's current inventory to 1 diamond shovel named "<gold><bold>Swift-Winds Lance" with nbt "{bakedRefine:776,sacredTreasureID:21}" with lore "<white>Grants <gold>[Sweeper]<white>.", "<white>If player initiates combat, grants STR/SPD +4 during combat.", "<light green>Unique Refine:", "<light green>If any ally within 15 blocks shares the wielder's class:", "<light green>Grants STR/SPD +12.", "<gold>[Sweeper]<white>: Disables player & foe's skills that guarantee counter-attacks during combat.", "<white>Weapon Ability: +35"
			#Bows
			else if arg 1 is 3:
				set slot 0 of the player's current inventory to 1 bow named "<gold><bold>Parthia" with nbt "{bakedRefine:776,sacredTreasureID:22}" with lore "<white>+3 weapon might.", "<white>Reduces ranged damage suffered by 20%%.", "<white>Grants <light blue>[Experience Sapper]<white>.", "<light green>Unique Refine:", "<light green>+10 weapon might against ranged opponents.", "<light green>Inflicts Slowness/Weakness 2 on foe after combat.", "<white>Weapon Ability: +30"
				set slot 1 of the player's current inventory to 1 iron horse armour named "<gold><bold>Super Shotgun" with nbt "{bakedRefine:776,sacredTreasureID:23}" with lore "<white>The double-barreled classic. Plenty of risk & plenty of reward.", "<white>Right-click to fire.", "<white>Left-click to reload. Costs 6 gold nuggets.", "<white>Weapon Ability: +65"
				set slot 2 of the player's current inventory to 1 bow named "<gold><bold>Fujin Yumi" with nbt "{bakedRefine:776,sacredTreasureID:24}" with lore "<white>Grants MAG/RES +10 while equipped.", "<white>Grants <light red>[Close Counter]<white>.", "<light green>Unique Refine:", "<light green>Holding sneak and firing an arrow teleports you to where it lands.", "<light red>[Close Counter]: <white>Automatically counter-attacks melee foes during combat.", "<white>Weapon Ability: +35"
				set slot 3 of the player's current inventory to 1 bow named "<gold><bold>Guard Bow" with nbt "{bakedRefine:776,sacredTreasureID:25}" with lore "<white>Reduces damage suffered by 25%% during combat.", "<white>Inflicts LCK -30 on player and foe during combat.", "<white>Weapon Ability: +19"
				set slot 4 of the player's current inventory to 1 bow named "<gold><bold>Brave Bow" with nbt "{bakedRefine:776,sacredTreasureID:26}" with lore "<white>Inflicts SPD -5.", "<white>Weapon attacks twice during combat.", "<white>Inflicts STR/DEF -4 on foe during combat.", "<white>Weapon Ability: +24"
				set slot 5 of the player's current inventory to 1 bow named "<gold><bold>Bow of Aresha" with nbt "{bakedRefine:776,sacredTreasureID:27}" with lore "<white>If player's DEF >= Foe's DEF +5:", "<white>Grants STR/DEF +X,", "<white>Where X = (Player's DEF - [foe's DEF + 5])", "<white>(Maximum bonus of +15 to each stat.)", "<white>Weapon Ability: +60"
				set slot 6 of the player's current inventory to 1 iron horse armour named "<gold><bold>Martin Mil-4 Automatic" with nbt "{bakedRefine:776,sacredTreasureID:39}" with lore "<white>Sneak + right click a wall to take cover behind it.", "<white>While in cover, restores 0.5 HP/s", "<white>Firing your weapon while in cover will blind-fire over it, if it is less than 2.5 blocks tall.", "<italics>What happened here was out of my control.", "<white>Weapon Ability: +70"
			#Gauntlets
			else if arg 1 is 4:
				set slot 0 of the player's current inventory to 1 diamond hoe named "<gold><bold>Vajra-Mushti" with nbt "{bakedRefine:776,sacredTreasureID:28,GauntletType:Vajra-Mushti}" with lore "<white>If player's HP = 100%% and player initiates combat:", "<white>Inflicts STR/MAG/DEF/RES -6 on foe during combat, and", "<white>nullifies foe's armour bonuses.", "<white>Weapon Ability: +60"
				set slot 1 of the player's current inventory to 1 diamond hoe named "<gold><bold>Aura Knuckles" with nbt "{bakedRefine:776,sacredTreasureID:29,GauntletType:AuraKnuckles}" with lore "<white>Grants SPD +5.", "<white>This weapon deals Magical damage instead of physical damage.", "<white>Weapon Ability: +23"
				set slot 2 of the player's current inventory to 1 diamond hoe named "<gold><bold>Hell Razers" with nbt "{bakedRefine:776,sacredTreasureID:30,GauntletType:HellRazers}" with lore "<white>Inflicts SPD -10 during combat.", "<white>If player initiates combat, grants STR/DEF +7 during combat, and", "<white>if foe's HP >= 70%%, grants an additional STR/DEF +7.", "<white>Weapon Ability: +60"
				set slot 3 of the player's current inventory to 1 diamond hoe named "<gold><bold>Dragon Claws" with nbt "{bakedRefine:776,sacredTreasureID:31,GauntletType:DragonClaws}" with lore "<white>Cursed by an ancient dragon.", "<white>Wearing these Gauntlets temporarily transforms you into the Dragonborn race,", "<white>or, if already a Dragonborn, grants infinite Soul Gauge while equipped.", "<white>Weapon Ability: +40"
				set slot 4 of the player's current inventory to 1 diamond hoe named "<gold><bold>Sky Piercer" with nbt "{bakedRefine:776,sacredTreasureID:32,GauntletType:SkyPiercer}" with lore "<white>Grants SPD/LCK +6.", "<white>Inflicts STR -10.", "<white>If player initiates combat, grants a guaranteed follow-up attack.", "<white>Weapon Ability: +60"
			#Daggers
			else if arg 1 is 5:
				set slot 0 of the player's current inventory to 64 arrow named "<gold><bold>Peshkatz" with nbt "{bakedRefine:776,sacredTreasureID:33,daggerType:4}" with lore "<white>Accelerates Special activation (+10%% activation chance).", "<white>If player initiates combat and has HP >= 70%%:", "<white>Grants STR/SPD/LCK/DEF/RES +5 through next action,", "<white>and inflicts STR/SPD -5 on foe through their next action.", "<white>Weapon Ability: +50"
				set slot 1 of the player's current inventory to 64 arrow named "<gold><bold>Smoke Dagger" with nbt "{bakedRefine:776,sacredTreasureID:34,daggerType:4}" with lore "<white>After combat, if player attacked:", "<white>Inflicts STR/SPD/LCK/DEF/RES -7 on foe through their next action.", "<white>This effect stacks with <gold>[Dagger 7]<reset><white>.", "<white>Weapon Ability: +24"
				set slot 2 of the player's current inventory to 64 arrow named "<gold><bold>Kard" with nbt "{bakedRefine:776,sacredTreasureID:35,daggerType:4}" with lore "<white>Accelerates Special activation (+30%% activation chance).", "<white>Inflicts STR/SPD/DEF/RES -9 during combat.", "<white>Weapon Ability: +60"
				set slot 3 of the player's current inventory to 64 arrow named "<gold><bold>Assasin's Dagger" with nbt "{bakedRefine:776,sacredTreasureID:36,daggerType:4}" with lore "<white>Nullifies foe's skills that guarantee counter-attacks during combat.", "<white>If player triggers a Special skill during combat,", "<white>boosts damage dealt by 30%%, and", "<white>inflicts <light blue>[Poison 5]<white>on foe.", "<white>Weapon Ability: +40"
				set slot 4 of the player's current inventory to 64 arrow named "<gold><bold>Loyalist's Dagger" with nbt "{bakedRefine:776,sacredTreasureID:37,daggerType:4}" with lore "<white>During combat, if player is within 20 block of any ally:", "<white>Grants STR/SPD/LCK/DEF/RES +4,", "<white>and player attacks twice.", "<white>Weapon Ability: +40"
				set slot 5 of the player's current inventory to 64 arrow named "<gold><bold>Cutlaseer" with nbt "{bakedRefine:776,sacredTreasureID:38,daggerType:4}" with lore "<white>+6 weapon might.", "<white>If number of foes within 15 blocks > number of allies within 15 blocks + 1:", "<white>Grants STR/SPD +7 during combat and boost Special odds by +15%%.", "<white>Can be thrown with no cost, but does not inflict <gold>[Dagger 7]<white> when thrown.", "<white>Weapon Ability: +43"

on spawn of a slime:
	if entity's world is "Salindrum":
		cancel event

on death of a monster:
	if victim's world is "Salindrum":
		wait 1 tick
		loop dropped items in radius 1 of the victim:
			kill the loop-entity

on experience spawn:
	if world is "Salindrum":
		cancel event
		
on food bar change:
	if {sd.nohunger.%player%} is true:
		increase the player's food level by 10
		
on inventory click:
	#Room Selector
	if the name of the player's current inventory is "<red>Select a room.":
		cancel event
		if the clicked item is lapis block:
			set {sd.rewarp.%player%} to location of block at player
			set {sdroom.%player%} to uncolored name of the clicked item
			set {sdcash.%player%} to player's balance
			set {sd.outgoingmult.%player%} to 1
			set {sd.incomingmult.%player%} to 1
			send "%{sdcash.%player%}%"
			add 100000 to the player's balance
			teleport the player to {sd.%{sdroom.%player%}%}
			set {sd::%{sdroom.%player%}%} to player's tablist name
			send "<light blue>Entered Salindrum."
			make player execute command "/salindrum"
			loop all items in the player's inventory:
				add loop-item to {sditems.%player%::*}
	#General Config Menu
	else if the name of the player's current inventory is "<red>Salindrum Configuration":
		cancel event
		if the name of the clicked item is "<gold>Exit Salindrum":
			teleport the player to {sd.rewarp.%player%}
			set the player's balance to {sdcash.%player%}
			clear {sdcash.%player%}
			send "%player's balance%"
			loop all monsters in radius 50 of the player:
				kill the loop-monster
			loop all items in the player's inventory:
				remove loop-item from the player
			set {_item} to 0
			loop {sditems.%player%::*}:
				if loop-value is helmet:
					set the player's helmet to loop-value
				else if loop-value is chestplate:
					set the player's chestplate to loop-value
				else if loop-value is leggings:
					set player's leggings to loop-value
				else if loop-value is boots:
					set player's boots to loop-value
				else if player has enough space for loop-value:
					add loop-value to the player's inventory
				else:
					drop loop-value at the player
			clear {sd.nohunger.%player%}
			clear {sd.invuln.%player%}
			clear {sditems.%player%::*}
			clear {sd.rewarp.%player%}
			set {sd::%{sdroom.%player%}%} to 0
			if {sd.infabilities.%player%} is set:
				clear {sd.infabilities.%player%}
				set {abilities.%player%::Traditional Weapons} to {sd_abilityBackup.%player%::Traditional Weapons}
				set {abilities.%player%::Magical Weapons} to {sd_abilityBackup.%player%::Magical Weapons}
				set {abilities.%player%::Guns} to {sd_abilityBackup.%player%::Guns}
			send "<light blue>Exited Salindrum."
		else if the name of the clicked item contains "Infinite Hunger":
			if {sd.nohunger.%player%} is not set:
				set {sd.nohunger.%player%} to true
			else:
				clear {sd.nohunger.%player%}
			make player execute command "/sd"
		else if the name of the clicked item contains "Max Abilities":
			if {sd.infabilities.%player%} is not set:
				set {sd.infabilities.%player%} to true
				set {sd_abilityBackup.%player%::Traditional Weapons} to {abilities.%player%::Traditional Weapons}
				set {sd_abilityBackup.%player%::Magical Weapons} to {abilities.%player%::Magical Weapons}
				set {sd_abilityBackup.%player%::Guns} to {abilities.%player%::Guns}
				set {abilities.%player%::Traditional Weapons} to 999
				set {abilities.%player%::Magical Weapons} to 999
				set {abilities.%player%::Guns} to 999
			else:
				clear {sd.infabilities.%player%}
				set {abilities.%player%::Traditional Weapons} to {sd_abilityBackup.%player%::Traditional Weapons}
				set {abilities.%player%::Magical Weapons} to {sd_abilityBackup.%player%::Magical Weapons}
				set {abilities.%player%::Guns} to {sd_abilityBackup.%player%::Guns}
			make player execute command "/sd"
		else if the name of the clicked item contains "Damage Modifiers":
			make player execute command "/sdmults"
		else if the name of the clicked item contains "Fix Equipment":
			make player execute command "/fix all"
		else if the name of the clicked item contains "Supply Crate":
			make player execute command "/sdsupplies"
		else if the name of the clicked item is "<white>Spawn Monsters":
			make player execute command "/sdmonsters"
		else if the name of the clicked item is "<white>Test Skills":
			make player execute command "/buyToolSkills 0 0"
		else if the name of the clicked item is "<white>Test Sacred Treasures":
			make player execute command "/sdhw 9"
		else if the name of the clicked item is "<white>Combat Calculator":
			make player execute command "/sdcalcs"
		else if the name of the clicked item is "<white>Reset Session":
			loop all monsters in radius 50 of the player:
				kill the loop-monster
			loop all items in the player's inventory:
				remove loop-item from the player
			set {_item} to 0
			loop {sditems.%player%::*}:
				if loop-value is helmet:
					set the player's helmet to loop-value
				else if loop-value is chestplate:
					set the player's chestplate to loop-value
				else if loop-value is leggings:
					set player's leggings to loop-value
				else if loop-value is boots:
					set player's boots to loop-value
				else if player has enough space for loop-value:
					add loop-value to the player's inventory
				else:
					drop loop-value at the player
			teleport the player to {sd.%{sdroom.%player%}%}
	#Sacred Treasures
	else if the name of the player's current inventory is "<red><bold>Salindrum - Sacred Treasures":
		cancel event
		if the name of the clicked item contains "<gold><bold>":
			give clicked item to the player
	#Sacred Treasures Weapon Type Select
	else if the name of the player's current inventory is "<red><bold>Salindrum - Select Weapon Class":
		cancel event
		if the name of the clicked item contains "Swords":
			make player execute command "/sdhw 0"
		else if the name of the clicked item contains "Axes":
			make player execute command "/sdhw 1"
		else if the name of the clicked item contains "Lances":
			make player execute command "/sdhw 2"
		else if the name of the clicked item contains "Bows":
			make player execute command "/sdhw 3"
		else if the name of the clicked item contains "Gauntlets":
			make player execute command "/sdhw 4"
		else if the name of the clicked item contains "Daggers":
			make player execute command "/sdhw 5"
	#Damage Modifiers
	else if the name of the player's current inventory is "<red>Damage Modifiers":
		cancel event
		if the name of the clicked item is "<light green>Increase Damage Dealt by 0.1x":
			add 0.1 to {sd.outgoingmult.%player%}
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			set slot 4 of the player's current inventory to 1 iron sword named "<light green>Damage Dealt" with lore "<white>Current Modifier: %{sd.outgoingmult.%player%}%x"
		else if the name of the clicked item is "<light green>Increase Damage Taken by 0.1x":
			add 0.1 to {sd.incomingmult.%player%}
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			set slot 13 of the player's current inventory to 1 iron chestplate named "<light red>Damage Taken" with lore "<white>Current Modifier: %{sd.incomingmult.%player%}%x"
		else if the name of the clicked item is "<light red>Decrease Damage Dealt by 0.1x":
			subtract 0.1 from {sd.outgoingmult.%player%}
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			set slot 4 of the player's current inventory to 1 iron sword named "<light green>Damage Dealt" with lore "<white>Current Modifier: %{sd.outgoingmult.%player%}%x"
		else if the name of the clicked item is "<light red>Decrease Damage Taken by 0.1x":
			subtract 0.1 from {sd.incomingmult.%player%}
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			set slot 13 of the player's current inventory to 1 iron chestplate named "<light red>Damage Taken" with lore "<white>Current Modifier: %{sd.incomingmult.%player%}%x"
		else if the name of the clicked item is "<light yellow>Reset Damage Taken Multiplier":
			set {sd.incomingmult.%player%} to 1
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			set slot 13 of the player's current inventory to 1 iron chestplate named "<light red>Damage Taken" with lore "<white>Current Modifier: %{sd.incomingmult.%player%}%x"
		else if the name of the clicked item is "<light yellow>Reset Damage Dealt Multiplier":
			set {sd.outgoingmult.%player%} to 1
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			set slot 4 of the player's current inventory to 1 iron sword named "<light green>Damage Dealt" with lore "<white>Current Modifier: %{sd.outgoingmult.%player%}%x"
		else if the name of the clicked item is "<bold>Go Back":
			make player execute command "/sd"
	#Supply Crate
	else if the name of the player's current inventory is "<red>Supply Crate":
		if the name of the clicked item contains "Go Back":
			cancel event
			make player execute command "/sd"
		else if the name of the clicked item contains "Restock Supply Crate":
			cancel event
			make player execute command "/sdsupplies"
	#Calculator
	else if the name of the player's current inventory is "<red>Calculator":
		if the name of the clicked item contains "Go Back":
			cancel event
			make player execute command "/sd"
		else if the name of the clicked item is "<gold>Special Odds":
			cancel event
		else if the name of the clicked item is "<gold>Damage Output":
			cancel event
		else if the name of the clicked item is "<gold>How to Use":
			cancel event
		else if the name of the clicked item is "<gold>Weapon Special Odds":
			cancel event
		else if the name of the clicked item is "<gold>Calculate":
			cancel event
			make player execute command "/runBattleSimulation"
			set slot 4 of the player's current inventory to 1 purple wool named "<gold>Special Odds" with lore "<white>Special Skill: %{sd.calcSpecial.%player%}%", "<white>Base Activation Chance: %{sd.calcOdds.%player%}%", "<white>Highest Possible Chance: %{sd.calcMaxOdds.%player%}%", "<white>SKL Needed To Cap: %{sd.calcMaxSKL.%player%}%", "<white>Critical Chance: %{sd.calcCritChance.%player%}%", "<white>Max Unbuffed Crit Chance: %{sd.calcMaxCritChance.%player%}%"
			set slot 5 of the player's current inventory to 1 splash potion of harming named "<gold>Damage Output" with lore "<white>Base Damage: %{sd.calcBaseDamage.%player%}%", "<white>With Skills & No Special: %{sd.calcSkillsDamage.%player%}%", "<white>With Skills & Special: %{sd.calcSpecialDamage.%player%}%", "<white>Maximum Damage Possible (With Double): %{sd.calcMaxDamage.%player%}%", "<white>Can Double Foes Below: %{sd.calcPlayerDoubleRange.%player%}% SPD", "<white>Foes Double From: %{sd.calcFoeDoubleRange.%player%}%+ SPD"
			if {sd.calcWeaponSpecial.%player%} is set:
				set slot 14 of the player's current inventory to 1 iron block named "<gold>Weapon Special Odds" with lore "<white>Special Skill: %{sd.calcWeaponSpecial.%player%}%", "<white>Base Activation Chance: %{sd.calcWeaponOdds.%player%}%", "<white>Highest Possible Chance: %{sd.calcWeaponMaxOdds.%player%}%", "<white>SKL Needed To Cap: %{sd.calcMAXWeaponSKL.%player%}%"
			else:
				set slot 14 of the player's current inventory to air
		else if slot 17 of the player's current inventory is not the clicked item:
			if the clicked item is not air:
				cancel event
				set slot 17 of the player's current inventory to the clicked item
				remove the clicked item from the player
		else if clicked item is not air:
			cancel event
			give clicked item to the player
			remove the clicked item from the player's current inventory
	#Spawn Monsters
	else if the name of the player's current inventory is "<red>Spawn Monsters":
		cancel event
		if the name of the clicked item is "<white>Salindrum Menu":
			make player execute command "/salindrum"
		else if the name of the clicked item is "<light red>Level Scaling":
			set {sd.dolevelscaling.%player%} to true
			set slot 52 of the player's current inventory to 1 lapis block named "<light blue>Level Scaling" with lore "<white>Monsters summoned will scale to your level.", "<white>Click to disable."
		else if the name of the clicked item is "<light blue>Level Scaling":
			clear {sd.dolevelscaling.%player%}
			set slot 52 of the player's current inventory to 1 redstone block named "<light red>Level Scaling" with lore "<white>Monsters summoned will NOT scale to your level.", "<white>Click to enable."
		else if the name of the clicked item is "<white>Zombie":
			spawn 1 zombie at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Skeleton":
			spawn 1 skeleton at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Spider":
			spawn 1 spider at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Creeper":
			spawn 1 creeper at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Husk":
			spawn 1 husk at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Witch":
			spawn 1 witch at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Enderman":
			spawn 1 enderman at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Cave Spider":
			spawn 1 cave spider at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Evoker":
			spawn 1 evoker at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Vex":
			spawn 1 vex at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Vindicator":
			spawn 1 vindicator at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Slime":
			spawn 1 slime at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Stray":
			spawn 1 stray at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Zombie Mimic":
			spawn 1 zombie at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<white>Mimic"
			set metadata value "isMimic" of the last spawned entity to 1
			set {_generic} to true
		else if the name of the clicked item is "<white>Skeleton Mimic":
			spawn 1 skeleton at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<white>Mimic"
			set metadata value "isMimic" of the last spawned entity to 1
			set {_generic} to true
		else if the name of the clicked item is "<white>Skulker":
			spawn 1 creeper at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<white>Skulker"
			set metadata value "isSkulker" of the last spawned entity to 1
			set {_generic} to true
		else if the name of the clicked item is "<white>Venom Spider":
			spawn 1 spider at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<white>Venom Spider"
			set metadata value "isVenomSpider" of the last spawned entity to 1
			set {_generic} to true
		else if the name of the clicked item is "<white>Malediction":
			spawn 1 husk at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<white>Malediction"
			set metadata value "isMalediction" of the last spawned entity to 1
			set {_generic} to true
		else if the name of the clicked item is "<white>Enrapture":
			spawn 1 stray at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<white>Enrapture"
			set metadata value "isEnrapture" of the last spawned entity to 1
			set {_generic} to true
		else if the name of the clicked item is "<white>Shadow":
			spawn 1 spider at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<white>Shadow"
			set metadata value "isShadow" of the last spawned entity to 1
			set {_generic} to true
			apply invisibility 1 to the last spawned entity for 1 day
			apply swiftness 2 to the last spawned entity for 1 day
			apply strength 1 to the last spawned entity for 1 day
		else if the name of the clicked item is "<white>Regret":
			spawn 1 zombie at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<white>Regret"
			set metadata value "isRegret" of the last spawned entity to 1
			set the last spawned entity's helmet to leather helmet of protection 3
			dye the last spawned entity's helmet gray
			set the last spawned entity's chestplate to leather chestplate of protection 3
			dye the last spawned entity's chestplate gray
			set the last spawned entity's leggings to leather leggings of protection 3
			dye the last spawned entity's leggings gray
			set the last spawned entity's boots to leather boots of protection 3
			dye the last spawned entity's boots gray
			set {_generic} to true
		else if the name of the clicked item is "<white>Fury":
			spawn 1 witch at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<white>Fury"
			set metadata value "isFury" of the last spawned entity to 1
			apply resistance 1 to the last spawned entity for 1 day
			apply fire resistance 1 to the last spawned entity for 1 day
			set {_generic} to true
		else if the name of the clicked item is "<white>Stalker":
			spawn 1 creeper at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<white>Stalker"
			set metadata value "isStalker" of the last spawned entity to 1
			apply swiftness 4 to the last spawned entity for 1 day
			set {_generic} to true
		else if the name of the clicked item is "<white>Wither Skeleton":
			spawn 1 wither skeleton at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Blaze":
			spawn 1 blaze at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Zombie Pigman":
			spawn 1 zombie pigman at {sd.%{sdroom.%player%}%}
			set {_generic} to true
		else if the name of the clicked item is "<white>Zombie Purgia":
			spawn 1 zombie at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<light red>Zombie Purgia"
			set metadata value "isZPurgia" of the last spawned entity to 1
			set {_generic} to true
		else if the name of the clicked item is "<white>Skeleton Purgia":
			spawn 1 skeleton at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<light red>Skeleton Purgia"
			set metadata value "isSPurgia" of the last spawned entity to 1
			set {_generic} to true
		else if the name of the clicked item is "<white>Creeper Purgia":
			spawn 1 creeper at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<light red>Creeper Purgia"
			set metadata value "isCPurgia" of the last spawned entity to 1
			set {_generic} to true
		else if the name of the clicked item is "<white>Pigman Purgia":
			spawn 1 zombie pigman at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<light red>Pigman Purgia"
			set metadata value "isZPPurgia" of the last spawned entity to 1
			set the last spawned entity's helmet to gold helmet of protection 5
			set the last spawned entity's chestplate to gold chestplate of protection 5
			set the last spawned entity's leggings to gold leggings of protection 5
			set the last spawned entity's boots to gold boots of protection 5
			set the last spawned entity's tool to gold sword of sharpness 10 named "<gold>Golden Blade"
			set {_generic} to true
		else if the name of the clicked item is "<white>Purgia Invoker":
			spawn 1 evoker at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<light red>Purgia Invoker"
			set metadata value "isIPurgia" of the last spawned entity to 1
			set {_generic} to true
		else if the name of the clicked item is "<white>Crusader Purgia":
			spawn 1 zombie at {sd.%{sdroom.%player%}%}
			set the name of the last spawned entity to "<red>Crusader Purgia"
			set metadata value "isZPurgia" of the last spawned entity to 1
			set metadata value "isSPurgia" of the last spawned entity to 1
			set metadata value "isCPurgia" of the last spawned entity to 1
			set metadata value "isZPPurgia" of the last spawned entity to 1
			set the last spawned entity's helmet to diamond helmet of protection 5
			set the last spawned entity's chestplate to diamond chestplate of protection 5
			set the last spawned entity's leggings to diamond leggings of protection 5
			set the last spawned entity's boots to diamond boots of protection 5
			set the last spawned entity's tool to diamond sword of sharpness 5 named "<gold>Diamond Blade"
			set {_generic} to true
		else if the name of the clicked item is "<gold>Treasure Zombie":
			spawn 1 zombie at {sd.%{sdroom.%player%}%}
			apply weakness 4 to the last spawned entity for 1 day
			apply swiftness 4 to the last spawned entity for 1 day
			set the last spawned entity's helmet to gold helmet of protection 5
			set the last spawned entity's chestplate to gold chestplate of protection 5
			set the last spawned entity's leggings to gold leggings of protection 5
			set the last spawned entity's boots to gold boots of protection 5
			set the last spawned entity's tool to gold sword of looting 5 named "<gold>Fortune Sword" with lore "<light red><bold>Slot A - None", "<light blue><bold>Slot B - Despoil"
			set {_generic} to true
		else if the name of the clicked item is "<gold>Treasure Skeleton":
			spawn 1 skeleton at {sd.%{sdroom.%player%}%}
			apply weakness 4 to the last spawned entity for 1 day
			apply swiftness 4 to the last spawned entity for 1 day
			set the last spawned entity's helmet to gold helmet of protection 5
			set the last spawned entity's chestplate to gold chestplate of protection 5
			set the last spawned entity's leggings to gold leggings of protection 5
			set the last spawned entity's boots to gold boots of protection 5
			set the last spawned entity's tool to bow of looting 5 named "<gold>Fortune Bow" with lore "<light red><bold>Slot A - None", "<light blue><bold>Slot B - Despoil"
			set {_generic} to true
		if {_generic} is set:
			if {sd.dolevelscaling.%player%} is true:
				set {_moblvl} to 1
				add {lvl.%player%} to {_moblvl}
				add ({promoted.%player%} * 15) to {_moblvl}
				set {_mob} to the last spawned entity
				loop {_moblvl} times:
					#add 1 to {t_str.%entity%}
					chance of 80%:
						add 1 to {t_str.%{_mob}%}
					#add 1 to {t_def.%entity%}
					chance of 50%:
						add 1 to {t_def.%{_mob}%}
					#add 1 to {t_spd.%entity%}
					chance of 60%:
						add 1 to {t_spd.%{_mob}%}
					#add 1 to {t_skl.%entity%}
					chance of 70%:
						add 1 to {t_skl.%{_mob}%}
					#add 1 to {t_res.%entity%}
					chance of 50%:
						add 1 to {t_res.%{_mob}%}
					#add 0.5 to the entity's maximum health
					chance of 80%:
						add 0.5 to {_mob}'s maximum health
				set {t_lvl.%{_mob}%} to {_moblvl}
				heal {_mob} by 9999
				
every 0.1 seconds:
	loop all players:
		if {sd.nohunger.%loop-player%} is true:
			increase the loop-player's food level by 10
			
function simulateSpecial(PLR: player, PCT: number, CAP: number) :: number:
	set {_specialOdds} to floor((({skl.%{_PLR}%} + {sklbuff.%{_PLR}%}) * {_PCT}) ^ 0.95)
	if {_specialOdds} is more than {_CAP}:
		set {_specialOdds} to {_CAP}
	return {_specialOdds}
	
function simulateSpecialOvercharge(PLR: player, CSH: number, EXP: number, CAP: number) :: number:
	set {_specialOddsOvercharge} to ({sklcap.%{_PLR}%} ^ {_EXP})
	if {_specialOddsOvercharge} is more than {_CAP}:
		set {_specialOddsOvercharge} to {_CAP}
	if the 6th line of the lore of slot 17 of {_PLR}'s current inventory contains "Slaying":
		add 10 to {_specialOddsOvercharge}
	if the name of slot 17 of {_PLR}'s current inventory is "<gold><bold>Rex Hasta":
		if the 6th line of the lore of slot 17 of {_PLR}'s current inventory contains "Unique":
			add 20 to {_specialOddsOvercharge}
	else if the name of slot 17 of {_PLR}'s current inventory is "<gold><bold>Hauteclere":
		if the 6th line of the lore of slot 17 of {_PLR}'s current inventory contains "Unique":
			add 20 to {_specialOddsOvercharge}
	if the 2nd line of the lore of slot 17 of {_PLR}'s current inventory contains "Wrath":
		add ({_PLR}'s maximum health / 2) to {_specialOddsOvercharge}
	add {_CSH} to {_specialOddsOvercharge}
	return {_specialOddsOvercharge}
			
#Battle Simulator
command /runBattleSimulation:
	trigger:
		#Initialize Variables
		set {_damage} to 0
		clear {sd.calcWeaponSpecial.%player%}
		clear {sd.calcWeaponOdds.%player%}
		clear {sd.calcWeaponMaxOdds.%Player%}
		clear {sd.calcSpecialDmage.%player%}
		clear {sd.calcOdds.%player%}
		clear {sd.calcMaxOdds.%player%}
		clear {sd.calcSpecial.%player%}
		#Base Weapon Damage
		#Swords
		if slot 17 of the player's current inventory is a wooden sword:
			set {_damage} to 2
		else if slot 17 of the player's current inventory is a stone sword:
			set {_damage} to 2.5
		else if slot 17 of the player's current inventory is an iron sword:
			set {_damage} to 3
		else if slot 17 of the player's current inventory is a diamond sword:
			set {_damage} to 4.5
		else if slot 17 of the player's current inventory is a golden sword:
			set {_damage} to 2.5
		#Axes
		else if slot 17 of the player's current inventory is a wooden axe:
			set {_damage} to 3.5
		else if slot 17 of the player's current inventory is a stone axe:
			set {_damage} to 4.5
		else if slot 17 of the player's current inventory is an iron axe:
			set {_damage} to 4.5
		else if slot 17 of the player's current inventory is a diamond axe:
			set {_damage} to 4.5
		else if slot 17 of the player's current inventory is a golden axe:
			set {_damage} to 3.5
		#Lances
		else if slot 17 of the player's current inventory is a wooden shovel:
			set {_damage} to 1.5
		else if slot 17 of the player's current inventory is a stone shovel:
			set {_damage} to 2
		else if slot 17 of the player's current inventory is an iron shovel:
			set {_damage} to 2.5
		else if slot 17 of the player's current inventory is a diamond shovel:
			set {_damage} to 3.5
		else if slot 17 of the player's current inventory is a golden shovel:
			set {_damage} to 2
		if level of sharpness of slot 17 of the player's current inventory is more than or equal to 1:
			add (0.25 + (0.25 * level of sharpness of slot 17 of the player's current inventory)) to {_damage}
		#Bows
		else if slot 17 of the player's current inventory is a bow:
			set {_damage} to 3.5
			#Increase damage due to Power Enchantment
			if level of power of slot 17 of the player's current inventory is more than or equal to 1:
				set {_damage} to {_damage} * (1.25 * (level of power of slot 17 of the player's current inventory + 1))
		#Magic (About to get messy)
		else if slot 17 of the player's current inventory is a blaze rod:
			if 7th line of the lore of the player's tool contains "Ember":
				add 3 to {_damage}
			else if 7th line of the lore of the player's tool contains "Spark":
				add 6 to {_damage}
			else if 7th line of the lore of the player's tool contains "Frost":
				add 2 to {_damage}
			else if 7th line of the lore of the player's tool contains "Gust":
				add 3 to {_damage}
			else if 7th line of the lore of the player's tool contains "Fire":
				add 5 to {_damage}
			else if 7th line of the lore of the player's tool contains "Thunder":
				add 8 to {_damage}
			else if 7th line of the lore of the player's tool contains "Hail":
				add 3 to {_damage}
			else if 7th line of the lore of the player's tool contains "Wind":
				add 4.5 to {_damage}
			else if 7th line of the lore of the player's tool contains "Elfire":
				add 9 to {_damage}
			else if 7th line of the lore of the player's tool contains "Thoron":
				add 12 to {_damage}
			else if 7th line of the lore of the player's tool contains "Blizzard":
				add 4.5 to {_damage}
			else if 7th line of the lore of the player's tool contains "Tornado":
				add 5.5 to {_damage}
			else if 7th line of the lore of the player's tool contains "Bolganone":
				add 13 to {_damage}
			else if 7th line of the lore of the player's tool contains "Aurora":
				add 14.5 to {_damage}
			else if 7th line of the lore of the player's tool contains "Nosferatu":
				add 3.5 to {_damage}
			else if 7th line of the lore of the player's tool contains "Light":
				add 4.5 to {_damage}
			else if 7th line of the lore of the player's tool contains "Spellblade":
				add floor((({strbuff.%player%} / 2) + ({defbuff.%player%} / 2) + ({sklbuff.%player%} / 2) + ({spdbuff.%player%} / 2) + ({resbuff.%player%} / 2)) ^ 0.75) to {_damage}
			else if 7th line of the lore of the player's tool contains "Forseti":
				add 7.5 to {_damage}
			else if 7th line of the lore of the player's tool contains "Naga":
				add 10 to {_damage}
			else if 7th line of the lore of the player's tool contains "Loptous":
				add 10 to {_damage}
			else if 7th line of the lore of the player's tool contains "Stone":
				add 1.5 to {_damage}
			else if 7th line of the lore of the player's tool contains "Rescue":
				set {_NullDamage} to true
			else if 7th line of the lore of the player's tool contains "Slipgate":
				set {_NullDamage} to true
			else if 7th line of the lore of the player's tool contains "Silence":
				add 1.5 to {_damage}
			else if 7th line of the lore of the player's tool contains "Thief":
				add 1.5 to {_damage}
			#Check 8th line
			if 8th line of the lore of the player's tool contains "Ember":
				add 3 to {_damage}
			else if 8th line of the lore of the player's tool contains "Spark":
				add 6 to {_damage}
			else if 8th line of the lore of the player's tool contains "Frost":
				add 2 to {_damage}
			else if 8th line of the lore of the player's tool contains "Gust":
				add 3 to {_damage}
			else if 8th line of the lore of the player's tool contains "Fire":
				add 5 to {_damage}
			else if 8th line of the lore of the player's tool contains "Thunder":
				add 8 to {_damage}
			else if 8th line of the lore of the player's tool contains "Hail":
				add 3 to {_damage}
			else if 8th line of the lore of the player's tool contains "Wind":
				add 4.5 to {_damage}
			else if 8th line of the lore of the player's tool contains "Elfire":
				add 9 to {_damage}
			else if 8th line of the lore of the player's tool contains "Thoron":
				add 12 to {_damage}
			else if 8th line of the lore of the player's tool contains "Blizzard":
				add 4.5 to {_damage}
			else if 8th line of the lore of the player's tool contains "Tornado":
				add 5.5 to {_damage}
			else if 8th line of the lore of the player's tool contains "Bolganone":
				add 13 to {_damage}
			else if 8th line of the lore of the player's tool contains "Aurora":
				add 14.5 to {_damage}
			else if 8th line of the lore of the player's tool contains "Nosferatu":
				add 3.5 to {_damage}
			else if 8th line of the lore of the player's tool contains "Light":
				add 4.5 to {_damage}
			else if 8th line of the lore of the player's tool contains "Spellblade":
				add floor((({strbuff.%player%} / 2) + ({defbuff.%player%} / 2) + ({sklbuff.%player%} / 2) + ({spdbuff.%player%} / 2) + ({resbuff.%player%} / 2)) ^ 0.75) to {_damage}
			else if 8th line of the lore of the player's tool contains "Forseti":
				add 7.5 to {_damage}
			else if 8th line of the lore of the player's tool contains "Naga":
				add 10 to {_damage}
			else if 8th line of the lore of the player's tool contains "Loptous":
				add 10 to {_damage}
			else if 8th line of the lore of the player's tool contains "Stone":
				add 1.5 to {_damage}
			else if 8th line of the lore of the player's tool contains "Rescue":
				set {_NullDamage} to true
			else if 8th line of the lore of the player's tool contains "Slipgate":
				set {_NullDamage} to true
			else if 8th line of the lore of the player's tool contains "Silence":
				add 1.5 to {_damage}
			else if 8th line of the lore of the player's tool contains "Thief":
				add 1.5 to {_damage}
		#Weapon Ranks & Critical Chance
		#Swords
		if slot 17 of the player's current inventory is any sword:
			if {weapongrade.%player%::swords} is "<gold><bold>S":
				add 5 to {_damage}
			else if {weapongrade.%player%::swords} is "A":
				add 4 to {_damage}
				add 1 to {_maxDamage}
			else if {weapongrade.%player%::swords} is "B":
				add 3 to {_damage}
				add 2 to {_maxDamage}
			else if {weapongrade.%player%::swords} is "C":
				add 2 to {_damage}
				add 3 to {_maxDamage}
			else if {weapongrade.%player%::swords} is "D":
				add 1 to {_damage}
				add 4 to {_maxDamage}
			set {sd.calcCritChance.%player%} to floor(({skl.%player%} + {sklbuff.%player%} + ({weaponrank.%player%::swords} ^ 0.35)) ^ 0.9)
			set {sd.calcMaxCritChance.%player%} to floor(({sklcap.%player%} + ({weaponrank.%player%::swords} ^ 0.35)) ^ 0.9)
			add {_damage} to {_maxdamage}
		#Axes
		else if slot 17 of the player's current inventory is any axe:
			if {weapongrade.%player%::axes} is "<gold><bold>S":
				add 5 to {_damage}
			else if {weapongrade.%player%::axes} is "A":
				add 4 to {_damage}
				add 1 to {_maxDamage}
			else if {weapongrade.%player%::axes} is "B":
				add 3 to {_damage}
				add 2 to {_maxDamage}
			else if {weapongrade.%player%::axes} is "C":
				add 2 to {_damage}
				add 3 to {_maxDamage}
			else if {weapongrade.%player%::axes} is "D":
				add 1 to {_damage}
				add 4 to {_maxDamage}
			set {sd.calcCritChance.%player%} to floor(({skl.%player%} + {sklbuff.%player%} + ({weaponrank.%player%::axes} ^ 0.35)) ^ 0.9)
			set {sd.calcMaxCritChance.%player%} to floor(({sklcap.%player%} + ({weaponrank.%player%::axes} ^ 0.35)) ^ 0.9)
			add {_damage} to {_maxdamage}
		#Lances
		if slot 17 of the player's current inventory is any shovel:
			if {weapongrade.%player%::lances} is "<gold><bold>S":
				add 5 to {_damage}
			else if {weapongrade.%player%::lances} is "A":
				add 4 to {_damage}
				add 1 to {_maxDamage}
			else if {weapongrade.%player%::lances} is "B":
				add 3 to {_damage}
				add 2 to {_maxDamage}
			else if {weapongrade.%player%::lances} is "C":
				add 2 to {_damage}
				add 3 to {_maxDamage}
			else if {weapongrade.%player%::lances} is "D":
				add 1 to {_damage}
				add 4 to {_maxDamage}
			set {sd.calcCritChance.%player%} to floor(({skl.%player%} + {sklbuff.%player%} + ({weaponrank.%player%::lances} ^ 0.35)) ^ 0.9)
			set {sd.calcMaxCritChance.%player%} to floor(({sklcap.%player%} + ({weaponrank.%player%::lances} ^ 0.35)) ^ 0.9)
			add {_damage} to {_maxdamage}
		#Bows
		if slot 17 of the player's current inventory is a bow:
			if {weapongrade.%player%::bows} is "<gold><bold>S":
				add 5 to {_damage}
			else if {weapongrade.%player%::bows} is "A":
				add 4 to {_damage}
				add 1 to {_maxDamage}
			else if {weapongrade.%player%::bows} is "B":
				add 3 to {_damage}
				add 2 to {_maxDamage}
			else if {weapongrade.%player%::bows} is "C":
				add 2 to {_damage}
				add 3 to {_maxDamage}
			else if {weapongrade.%player%::bows} is "D":
				add 1 to {_damage}
				add 4 to {_maxDamage}
			set {sd.calcCritChance.%player%} to floor(({skl.%player%} + {sklbuff.%player%} + ({weaponrank.%player%::bows} ^ 0.35)) ^ 0.9)
			set {sd.calcMaxCritChance.%player%} to floor(({sklcap.%player%} + ({weaponrank.%player%::bows} ^ 0.35)) ^ 0.9)
			add {_damage} to {_maxdamage}
		#Magic + Tomes
		if slot 17 of the player's current inventory is a book:
			set {_magic} to true
		else if slot 17 of the player's current inventory is a blaze rod:
			set {_magic} to true
		if {_magic} is true:
			if {weapongrade.%player%::magic} is "<gold><bold>S":
				add 5 to {_damage}
			else if {weapongrade.%player%::magic} is "A":
				add 4 to {_damage}
				add 1 to {_maxDamage}
			else if {weapongrade.%player%::magic} is "B":
				add 3 to {_damage}
				add 2 to {_maxDamage}
			else if {weapongrade.%player%::magic} is "C":
				add 2 to {_damage}
				add 3 to {_maxDamage}
			else if {weapongrade.%player%::magic} is "D":
				add 1 to {_damage}
				add 4 to {_maxDamage}
			set {sd.calcCritChance.%player%} to floor(({skl.%player%} + {sklbuff.%player%} + ({weaponrank.%player%::magic} ^ 0.35)) ^ 0.9)
			set {sd.calcMaxCritChance.%player%} to floor(({sklcap.%player%} + ({weaponrank.%player%::magic} ^ 0.35)) ^ 0.9)
			add {_damage} to {_maxdamage}
		#Sacred Treasures
		if the name of slot 17 of the player's current inventory is "<gold><bold>Mystletainn":
			add 2 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Folkvangr":
			add 2 to {_damage}
			add 3 to {_maxDamage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Tyrfing":
			add 2 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Fensalir":
			add 2 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Durandal":
			add 1 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Unique":
				add 20 to {_strbuff}
				add 20 to {_sklbuff}
				if {_damage} is more than 4.5:
					add {_damage} * 0.5 to {_crushing}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Kindled-Fire Sword":
			add 1 to {_braveEffectReps}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Mercurius":
			add 2 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Hauteclere":
			add 2 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Gradivus":
			add 2 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Basilikos":
			add 2.5 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Devil Axe":
			add 4.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Unique":
				add 6 to {_skillsdamage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Crusader's Lance":
			add 4 to {_damage}
			set {_CLHealthMult} to true
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Lunar Bow":
			add 1.5 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Balder Side Sword":
			add 1.5 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Ragnell":
			add 4 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Unique":
				add 2 to {_skillsdamage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Yamato":
			add 1.5 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Meisterschwert":
			set {_ReinhardtBrave} to true
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Dire Thunder":
			set {_ReinhardtBrave} to true
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Mystletainn":
			add 2 to {_damage}
			add 10 to {_sklbuff}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Unique":
				add 15 to {_strbuff}
				add 15 to {_sklbuff}
				add 15 to {_defbuff}
				add 15 to {_resbuff}
				add 15 to {_spdbuff}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Rex Hasta":
			if line 6 of the lore of slot 17 of the player's current inventory contains "Unique":
				add 2 to {_maxdamage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Falchion":
			add 3 to {_damage}
			add 6 to {_maxdamage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Binding Blade":
			add 2 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Parthia":
			add 1.5 to {_damage}
			if the 6th line of the lore of the player's tool contains "Unique":
				add 5 to {_skillsDamage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Armads":
			add 3 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Siegmund":
			add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Unique":
				set {_SiegmundBrave} to true
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Sieglinde":
			add 2.5 to {_damage}
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Light Brand":
			add 1 to {_damage}
		#Return Base Damage
		if {_magic} is true:
			add ({res.%player%} + {resbuff.%player%} + {_resbuff}) / 5 to {_damage}
		else:
			add ({str.%player%} + {strbuff.%player%} + {_strbuff}) / 5 to {_damage}
		set {sd.calcBaseDamage.%player%} to {_damage}
		add {_skillsDamage} to {_damage}
		#Skills Bonuses
		#Boost Skills
		#Flame Boost
		if the 2nd line of the lore of slot 17 of the player's current inventory contains "Flame Boost":
			add 15 to {strbuff.%player%}
			add 15 to {spdbuff.%player%}
			add 15 to {sklbuff.%player%}
			wait 1.5 seconds
			subtract 15 from {strbuff.%player%}
			subtract 15 from {spdbuff.%player%}
			subtract 15 from {sklbuff.%player%}
		#Aqua Boost
		if the 2nd line of the lore of slot 17 of the player's current inventory contains "Aqua Boost":
			add 15 to {resbuff.%player%}
			add 15 to {spdbuff.%player%}
			add 15 to {sklbuff.%player%}
			wait 1.5 seconds
			subtract 15 from {resbuff.%player%}
			subtract 15 from {spdbuff.%player%}
			subtract 15 from {sklbuff.%player%}
		if the 6th line of the lore of slot 17 of the player's current inventory contains "Reinforced":
			add 1.5 to {_skillsdamage}
		else if the 6th line of the lore of slot 17 of the player's current inventory contains "Crushing":
			if {_damage} is more than 4.5:
				add ({_damage} * 0.33) to {_crushing}
				if {_crushing} is more than 33:
					set {_crushing} to 33
		if the name of slot 17 of the player's current inventory is "<gold><bold>Basilikos":
			set {_damage} to {_damage} * 1.5
		if the 1st line of the lore of slot 17 of the player's current inventory contains "Flashing Blade":
			add 5 to {_damage}
			add 9 to {_maxDamage}
		else if the 1st line of the lore of slot 17 of the player's current inventory contains "Heavy Blade":
			add 5 to {_Damage}
			add 9 to {_maxDamage}
		else if the 1st line of the lore of slot 17 of the player's current inventory contains "Life and Death":
			set {_damage} to {_damage} * 1.5
		else if the 1st line of the lore of slot 17 of the player's current inventory contains "Fury":
			add 3 to {_damage}
		if the 2nd line of the lore of slot 17 of the player's current inventory contains "Desperation":
			add {_damage} to {_maxDamage}
		else if the 2nd line of the lore of slot 17 of the player's current inventory contains "Brave Blade":
			subtract 7 from {_spdbuff}
			add ({_damage} - 1.5) to {_maxDamage}
		else if the 2nd line of the lore of slot 17 of the player's current inventory contains "Sabotage Defense":
			set {_damage} to {_damage} * 1.25
		#Perks Bonuses
		set {_sklcheck} to checkSlots(player,"Sword Specialist")
		if {_sklcheck} is 1:
			if slot 17 of the player's current inventory is any sword:
				set {_damage} to {_damage} * 1.25
		set {_sklcheck} to checkSlots(player,"Heavy Draw")
		if {_sklcheck} is 1:
			if slot 17 of the player's current inventory is a bow:
				add 1.5 to {_damage}
		set {_sklcheck} to checkSlots(player,"Double Lion")
		if {_sklcheck} is 1:
			if slot 17 of the player's current inventory is a bow:
				set {_DoubleLion} to true
				add {_damage} to {_damage}
		#Ethreal Grip
		if the 4th line of the lore of slot 17 of the player's current inventory contains "Ethreal Grip":
			set {_damage} to {_damage} * 0.5
		#Rings
		loop all items in the player's inventory:
			if the name of the loop-item contains "Pursuit Ring":
				add ({_damage} * 0.5) to {_maxDamage}
			else if the name of the loop-item contains "Prayer Ring":
				add {_damage} to {_maxDamage}
		set {sd.calcSkillsDamage.%player%} to {_damage}
		#Special Skills
		#Radiant Aether (Weapon Specific)
		if the name of slot 17 of the player's current inventory is "<gold><bold>Ragnell":
			set {sd.calcWeaponSpecial.%player%} to "Radiant Aether"
			set {sd.calcWeaponOdds.%player%} to simulateSpecial(player, 0.6, 65)
			set {sd.calcWeaponMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.6,65)
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Eclipse (Weapon Specific)
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Alondite":
			set {sd.calcWeaponSpecial.%player%} to "Eclipse"
			set {sd.calcWeaponOdds.%player%} to simulateSpecial(player, 0.65, 50)
			set {sd.calcWeaponMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.65,50)
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Luna (Lunar Bow)
		else if the name of slot 17 of the player's current inventory is "<gold><bold>Lunar Bow":
			set {sd.calcWeaponSpecial.%player%} to "Luna (Lunar Bow)"
			set {sd.calcWeaponOdds.%player%} to simulateSpecial(player, 0.75, 70)
			set {sd.calcWeaponMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.75,70)
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Astra
		if the 5th line of the lore of slot 17 of the player's current inventory contains "Astra":
			set {sd.calcSpecial.%player%} to "Astra"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.65, 50)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.65,50)
			set {_specialProc} to true
			set {_damage} to {_damage} * 3
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Glimmer
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Glimmer":
			set {sd.calcSpecial.%player%} to "Glimmer"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.9, 70)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.9,70)
			set {_damage} to {_damage} * 1.5
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Blazing Light
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Blazing Light":
			set {sd.calcSpecial.%player%} to "Blazing Light"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.7, 50)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.7,50)
			set {_damage} to {_damage} * 1.25
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Growing Light
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Growing Light":
			set {sd.calcSpecial.%player%} to "Growing Light"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.7, 50)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.7,50)
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Luna
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Luna":
			set {sd.calcSpecial.%player%} to "Luna"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.75, 70)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.75,70)
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Moonbow
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Moonbow":
			set {sd.calcSpecial.%player%} to "Moonbow"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.85, 80)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.85,80)
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Sol
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Sol":
			set {sd.calcSpecial.%player%} to "Sol"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.7, 70)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.7,70)
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Aether
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Aether":
			set {sd.calcSpecial.%player%} to "Aether"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.55, 65)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.55,65)
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Subdue
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Subdue":
			set {sd.calcSpecial.%player%} to "Subdue"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.65, 50)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.65,50)
			add 10 to {_damage}
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Retribution
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Retribution":
			set {sd.calcSpecial.%player%} to "Retribution"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.675, 70)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.675,70)
			add (player's maximum health / 2) to {_maxDamage}
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Ignis
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Ignis":
			set {sd.calcSpecial.%player%} to "Ignis"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.7, 50)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.7,50)
			add (({def.%player%} + {defbuff.%player%} + {_defbuff}) / 2) ^ 0.8 to {_damage}
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Dragon Fang
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Dragon Fang":
			set {sd.calcSpecial.%player%} to "Dragon Fang"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.7, 50)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.7,50)
			add (({str.%player%} + {strbuff.%player%} + {_strbuff}) / 2) ^ 0.8 to {_damage}
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Glacies
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Glacies":
			set {sd.calcSpecial.%player%} to "Glacies"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.7, 50)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.7,50)
			add (({res.%player%} + {resbuff.%player%} + {_resbuff}) / 2) ^ 0.8 to {_damage}
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		#Rising Wind
		else if the 5th line of the lore of slot 17 of the player's current inventory contains "Rising Wind":
			set {sd.calcSpecial.%player%} to "Rising Wind"
			set {sd.calcOdds.%player%} to simulateSpecial(player, 0.7, 50)
			set {sd.calcMaxOdds.%player%} to simulateSpecialOvercharge(player,{_crushing},0.7,50)
			add (({spd.%player%} + {spdbuff.%player%} + {_spdbuff}) / 2) ^ 0.8 to {_damage}
			set {_specialProc} to true
			if the 2nd line of the lore of slot 17 of the player's current inventory contains "Wrath":
				add 2.5 to {_damage}
			if the 6th line of the lore of slot 17 of the player's current inventory contains "Koenig":
				add 2.5 to {_damage}
		set {sd.calcSpecialDamage.%player%} to {_damage}
		set {sd.calcMaxDamage.%player%} to ({_damage} + {_maxDamage}) * 2
		set {sd.calcPlayerDoubleRange.%player%} to {spd.%player%} + {spdbuff.%player%} + {_spdbuff} - 5
		set {sd.calcFoeDoubleRange.%player%} to {spd.%player%} + {spdbuff.%player%} + {_spdbuff} + 5