#Crafting recipes for promotion items
on load:
	register new shaped recipe for nether star named "<gold><bold>Trainee's Enrollment" with lore "Used to return higher classes to humble origins." using iron block, iron block, iron block, gold block, redstone block, gold block, iron block, iron block, iron block
	register new shaped recipe for nether star named "<gold><bold>Journey's Crest" with lore "Used to promote Journeymen to a higher class." using iron block, iron block, iron block, gold block, diamond, gold block, iron block, iron block, iron block
	register new shaped recipe for nether star named "<gold><bold>Warrior's Proof" with lore "Used to ascend 2nd tier classes to a higher tier." using gold block, gold block, gold block, gold block, diamond block, gold block, gold block, gold block, gold block

command /ctoggle <number>:
	trigger:
		if arg 1 is 1:
			set {ctoggle.%player%} to 1
			send "<gold>Classes enabled!"
		else:
			set {ctoggle.%player%} to 0
			set the player's maximum health to 10
			send "<gold>Classes disabled!"


#MARKER - First-Time Setup

#Perform first-time setup
on join:
	if {class.%player%} is not set:
		set the player's level to 1
		set {lvl.%player%} to 1
		set {ctoggle.%player%} to 1
		set {generation.%player%} to 1
		set {class.%player%} to "Freelancer"
		set {weapongrade.%player%::swords} to "E"
		set {weapongrade.%player%::lances} to "E"
		set {weapongrade.%player%::axes} to "E"
		set {weapongrade.%player%::bows} to "E"
		set {weapongrade.%player%::magic} to "-"
		set {weapongrade.%player%::staves} to "-"
		set {badLevelQuote.%player%} to "..?"
		set {avgLevelQuote.%player%} to "..."
		set {goodLevelQuote.%player%} to "..!"
		set {maxLevelQuote.%player%} to "..."
		set {promotionQuote.%player%} to "..!!"
		set {skillquote1.%player%} to "..!"
		set {skillquote2.%player%} to "..."
		set {skillquote3.%player%} to "..!"
		set {skillquote4.%player%} to "..!!!"
		set {lowHPQuote.%player%} to "...!"
		set {healedQuote.%player%} to "..."
		set {mediumHPQuote.%player%} to "..."
		set {downedQuote.%player%} to "..!"
		set {allyDownedQuote.%player%} to "..!"
		set {enemyDefeated1.%player%} to "..."
		set {enemyDefeated2.%player%} to "..!"
		set {bossDefeated1.%player%} to "...!"
		set {bossDefeated2.%player%} to "..!"
		set {deathQuote.%player%} to "..?"
		set {allyNeedHealing.%player%} to "..."
		set {allyDeathQuote.%player%} to "..."
		set {allyHardcoreDeathQuote.%player%} to "..."
		set {allyEnemyDefeated1.%player%} to "..!"
		set {allyEnemyDefeated2.%player%} to "..?"
		set {allyEnemyDefeated3.%player%} to "..."
		set {allyHurtLarge1.%player%} to "..?"
		set {allyHurtLarge2.%player%} to "..?!"
		#0 = Male, 1 = Female
		set {sex.%player%} to 0
	#if {hasCrest.%player%} is not set:
	#	give nether star named "<gold><bold>Journey's Crest" with lore "Used to promote Journeymen to a higher class." to player
	#	set {hasCrest.%player%} to 1
	strike lightning effect at the player
	play 40 (wool break with speed 1) at the player
	play 40 (lapis break with speed 1) at the player
		
#MARKER - Config Menu
		
#Menu Layers:
#0-0: Initial Setup
#0-1: Reclass Optional Setup
#1-0: Main Config Menu
#1-1: HP Config
#1-2: STR Config
#1-3: DEF Config
#1-4: SKL Config
#1-5: SPD Config
#1-6: MAG Config
#1-7: Presets
#1-8: Preferred Weapon
#2-0: Ring Selection
#2-1: Difficulty Select
#2-2: Elite Mode Toggle
#2-3: Gen 1 Class Select

command /charsetup [<number=0>] [<number=0>]:
	trigger:
		if arg 1 is 0:
			if arg 2 is 0:
				set {csetup_pts.%player%} to 240
				set {pts_MAG.%player%} to 10
				set {pts_HP.%player%} to 100
				set {pts_STR.%player%} to 10
				set {pts_DEF.%player%} to 10
				set {pts_SPD.%player%} to 10
				set {pts_SKL.%player%} to 10
				make player execute command "/charsetup 1 0"
			else if arg 2 is 1:
				set {csetup_pts.%player%} to ({generation.%player%} * 120) + 120
				set {pts_MAG.%player%} to 10
				set {pts_HP.%player%} to 100
				set {pts_STR.%player%} to 10
				set {pts_DEF.%player%} to 10
				set {pts_SPD.%player%} to 10
				set {pts_SKL.%player%} to 10
				make player execute command "/charsetup 1 0"
		if arg 1 is 1:
			if arg 2 is 0:
				open chest with 2 rows named "<gold><bold>Character Configuration" for the player
				set slot 0 of the player's current inventory to green wool named "<green><bold>HP" with lore "<white>Vitality.", "<white>2 points of HP grants 1 additional heart of health.", "<white>HP has a minimum investment of 100 points."
				set slot 1 of the player's current inventory to green wool named "<green><bold>STR" with lore "<white>Strength of attacks.", "<white>Every 5 points of STR increases damage dealt by 1 heart."
				set slot 2 of the player's current inventory to green wool named "<green><bold>DEF" with lore "<white>Resilience to attacks.", "<white>Every 5 points of DEF reduces damage suffered by 1 heart."
				set slot 3 of the player's current inventory to green wool named "<green><bold>SKL" with lore "<white>Adeptness with weapons.", "<white>Influences how frequently Special Skills activate."
				set slot 4 of the player's current inventory to green wool named "<green><bold>SPD" with lore "<white>Speed of movement.", "<white>Having 15 more SPD than your foe grants 2x damage during combat.", "<white>Having enough speed grants a permanent movement boost."
				set slot 5 of the player's current inventory to green wool named "<green><bold>MAG" with lore "<white>Adeptness with magic.", "<white>Magical attacks calculate damage using this stat."
				set slot 6 of the player's current inventory to 1 hopper named "<green><bold>Reset Points" with lore "<white>Clears all allocated points."
				set slot 7 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
				set slot 8 of the player's current inventory to 1 book named "<white>Click a stat to adjust your proficiency in it." with lore "<white>10 points = +5%% growth rate,", "<white>+3 to stat cap,", "<white>+1 to base amount.", "<white>Each stat must have at least 10 points.", "<white>Your class will further adjust your proficiency."
				set slot 9 of the player's current inventory to 1 chest named "<light yellow><bold>Presets" with lore "<white>Automatically allocate points based on your desired class."
				if {sex.%player%} is 1:
					set slot 10 of the player's current inventory to 1 totem of undying named "<bold>Gender: Male" with lore "<white>Select which pronouns NPC's will refer to you by.", "<white>NOTE: Your gender will not impact your ability to support other players."
				else:
					set slot 10 of the player's current inventory to 1 totem of undying named "<bold>Gender: Female" with lore "<white>Select which pronouns NPC's will refer to you by.", "<white>NOTE: Your gender will not impact your ability to support other players."
				set slot 11 of the player's current inventory to 1 iron sword named "<green>Preferred Weapon" with lore "<white>Specialize in a particular weapon type.", "<white>Your chosen weapon type recieves bonus damage and critical chance."
				if {drenable.%player%} is 1:
					set slot 12 of the player's current inventory to 1 green wool named "<green>Dodge Rolling" with lore "<white>Allows you to perform invincible rolls by double-tapping the sneak key.", "<white>Dodge Rolling is currently enabled."
				else:
					set slot 12 of the player's current inventory to 1 red wool named "<red>Dodge Rolling" with lore "<white>Allows you to perform invincible rolls by double-tapping the sneak key.", "<white>Dodge Rolling is currently disabled."
				set slot 13 of the player's current inventory to 1 eye of ender named "<purple>Difficulty" with lore "<white>Fine-tune how difficult the game will be."
				if {realism.%player%} is 1:
					set slot 14 of the player's current inventory to 1 water bottle named "<light blue>Realism: Enabled" with lore "<white>Makes survival more difficult by adding new mechanics.", "<white>Hunger depletes faster and is harder to replenish.", "<white>Thirst must be quenched occasionally.", "<white>Becoming too hot or cold can lead to death."
				else:
					set slot 14 of the player's current inventory to 1 water bottle named "<light blue>Realism: Disabled" with lore "<white>Makes survival more difficult by adding new mechanics.", "<white>Hunger depletes faster and is harder to replenish.", "<white>Thirst must be quenched occasionally.", "<white>Becoming too hot or cold can lead to death."
				if {tips.%player%} is 1:
					set slot 15 of the player's current inventory to 1 book named "<light yellow>Hints: Enabled" with lore "<white>Prints periodic tips to the chat."
				else:
					set slot 15 of the player's current inventory to 1 obsidian named "<light yellow>Hints: Disabled" with lore "<white>Prints periodic tips to the chat."
				if {farewells.%player%} is 1:
					set slot 16 of the player's current inventory to 1 potion of healing named "<light green>Assist Type" with lore "<light blue>Assist Type: Bleedout", "<white>Upon taking mortal damage, you can be revived by another player for 15 seconds.", "<white>If no-one comes to your aid, you will die normally."
				else if {bhealth.%player%} is 1:
					set slot 16 of the player's current inventory to 1 potion of healing named "<light green>Assist Type" with lore "<light blue>Assist Type: Last Stand", "<white>While above 1/2 heart:", "<white>Attacks that would normally kill you will be survived with 1/2 heart.", "<white>After activating, Last Stand needs 30 seconds to recharge."
				else:
					set slot 16 of the player's current inventory to 1 potion of healing named "<light green>Assist Type" with lore "<white>Click to cycle between Bleedout, Last Stand, or no assists.", "<white>Assist Type: None"
				if {csetup_pts.%player%} is 0:
					set slot 17 of the player's current inventory to 1 emerald named "<gold><bold>Confirm Allocations" with lore "<white>Clicking this will confirm your point allocations.", "<white>You may reallocate your points later."
			else if arg 2 is 1:
				open chest with 1 row named "<gold><bold>HP Configuration" for the player
				set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back" with lore "<white>Return to the previous menu."
				set slot 2 of the player's current inventory to 1 red wool named "<bold>Remove 10 Points"
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>HP" with lore "<white>Points Invested:", "<white>%{pts_HP.%player%}%"
				set slot 6 of the player's current inventory to 1 green wool named "<bold>Add 10 Points"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
			else if arg 2 is 2:
				open chest with 1 row named "<gold><bold>STR Configuration" for the player
				set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back" with lore "<white>Return to the previous menu."
				set slot 2 of the player's current inventory to 1 red wool named "<bold>Remove 10 Points"
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>STR" with lore "<white>Points Invested:", "<white>%{pts_STR.%player%}%"
				set slot 6 of the player's current inventory to 1 green wool named "<bold>Add 10 Points"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
			else if arg 2 is 3:
				open chest with 1 row named "<gold><bold>DEF Configuration" for the player
				set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back" with lore "<white>Return to the previous menu."
				set slot 2 of the player's current inventory to 1 red wool named "<bold>Remove 10 Points"
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>DEF" with lore "<white>Points Invested:", "<white>%{pts_DEF.%player%}%"
				set slot 6 of the player's current inventory to 1 green wool named "<bold>Add 10 Points"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
			else if arg 2 is 4:
				open chest with 1 row named "<gold><bold>SKL Configuration" for the player
				set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back" with lore "<white>Return to the previous menu."
				set slot 2 of the player's current inventory to 1 red wool named "<bold>Remove 10 Points"
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>SKL" with lore "<white>Points Invested:", "<white>%{pts_SKL.%player%}%"
				set slot 6 of the player's current inventory to 1 green wool named "<bold>Add 10 Points"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
			else if arg 2 is 5:
				open chest with 1 row named "<gold><bold>SPD Configuration" for the player
				set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back" with lore "<white>Return to the previous menu."
				set slot 2 of the player's current inventory to 1 red wool named "<bold>Remove 10 Points"
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>SPD" with lore "<white>Points Invested:", "<white>%{pts_SPD.%player%}%"
				set slot 6 of the player's current inventory to 1 green wool named "<bold>Add 10 Points"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
			else if arg 2 is 6:
				open chest with 1 row named "<gold><bold>MAG Configuration" for the player
				set slot 0 of the player's current inventory to 1 red glass pane named "<bold>Go Back" with lore "<white>Return to the previous menu."
				set slot 2 of the player's current inventory to 1 red wool named "<bold>Remove 10 Points"
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>MAG" with lore "<white>Points Invested:", "<white>%{pts_MAG.%player%}%"
				set slot 6 of the player's current inventory to 1 green wool named "<bold>Add 10 Points"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
			else if arg 2 is 8:
				open chest with 1 row named "<gold><bold>Preferred Weapon" for the player
				set slot 0 of the player's current inventory to 1 iron sword named "<bold>Swords" with lore "<white>A classic weapon with unmatched versatility.", "<white>The best at crowd control."
				set slot 1 of the player's current inventory to 1 iron axe named "<bold>Axes" with lore "<white>A slow, but powerful single-hit weapon.", "<white>Highest single-target damage."
				set slot 2 of the player's current inventory to 1 iron shovel named "<bold>Lances" with lore "<white>A low damage, but versatile melee and ranged weapon.", "<white>Can be thrown with right-click."
				set slot 3 of the player's current inventory to 1 bow named "<bold>Bows" with lore "<white>A classic weapon for ranged combat.", "<white>Well-balanced accuracy, range, and ease of use."
				set slot 4 of the player's current inventory to 1 blaze rod named "<bold>Magic" with lore "<white>Arcane spells with a variety of effects.", "<white>Highy-damaging, but with long cooldowns.","<white>Requires specific classes to wield."
				set slot 5 of the player's current inventory to 1 iron hoe named "<bold>Staves" with lore "<white>Magical staves with healing properties.", "<white>Cannot deal damage, but instead heals allies.","<white>Only Clerics may wield these."
				if {prfWeaponType.%player%} is 0:
					set slot 7 of the player's current inventory to 1 iron sword named "<gold>Your Preferred Weapon: Swords"
				else if {prfWeaponType.%player%} is 1:
					set slot 7 of the player's current inventory to 1 iron axe named "<gold>Your Preferred Weapon: Axes"
				else if {prfWeaponType.%player%} is 2:
					set slot 7 of the player's current inventory to 1 iron shovel named "<gold>Your Preferred Weapon: Lances"
				else if {prfWeaponType.%player%} is 3:
					set slot 7 of the player's current inventory to 1 bow named "<gold>Your Preferred Weapon: Bows"
				else if {prfWeaponType.%player%} is 4:
					set slot 7 of the player's current inventory to 1 blaze rod named "<gold>Your Preferred Weapon: Magic"
				else if {prfWeaponType.%player%} is 5:
					set slot 7 of the player's current inventory to 1 iron hoe named "<gold>Your Preferred Weapon: Staves"
				set slot 8 of the player's current inventory to 1 red glass pane named "<bold>Go Back"
		if arg 1 is 2:
			if arg 2 is 0:
				open chest with 2 rows named "<gold><bold>Select a ring." for the player
				set slot 0 of the player's current inventory to 1 music disc far named "<light green><bold>Life Ring" with lore "<white>While in your inventory:", "<light green>Recover 10%% of your max HP every 15 seconds."
				set slot 1 of the player's current inventory to 1 music disc wait named "<light blue><bold>Elite Ring" with lore "<white>While in your inventory:", "<light blue>Gain bonus experience for slaying monsters."
				set slot 2 of the player's current inventory to 1 music disc 13 named "<yellow><bold>Thief Ring" with lore "<white>While in your inventory:", "<yellow>Slain monsters have a chance to drop extra money."
				set slot 3 of the player's current inventory to 1 music disc mall named "<light purple><bold>Return Ring" with lore "<white>While in your inventory:", "<light purple>Teleport to a custom location.", "<light purple>Hold Sneak and Right-click to set the warp destination.", "<light purple>Right-click without sneaking to warp."
				set slot 4 of the player's current inventory to 1 music disc wait named "<light cyan><bold>Speed Ring" with lore "<white>While in your inventory:", "<light cyan>Grants Swiftness 2."
				set slot 5 of the player's current inventory to 1 music disc chirp named "<light red><bold>Power Ring" with lore "<white>While in your inventory:", "<light green>Grants Strength 2."
				set slot 6 of the player's current inventory to 1 music disc strad named "<white><bold>Shield Ring" with lore "<white>While in your inventory:", "<white>Grants Resistance 2."
				set slot 7 of the player's current inventory to 1 music disc 13 named "<orange><bold>Prayer Ring" with lore "<white>While in your inventory:", "<orange>Attacks while below 50%% health will always be critical hits."
				set slot 8 of the player's current inventory to 1 music disc cat named "<green><bold>Pursuit Ring" with lore "<white>While in your inventory:", "<green>Automatically perform a follow-up attack in combat.", "<green>Auto follow-ups deal 50%% less damage."
			else if arg 2 is 1:
				open chest with 2 rows named "<gold><bold>Select Difficulty" for the player
				set slot 0 of the player's current inventory to 1 book named "<gold>Difficulty Modes" with lore "<white>This row of modes selects your core difficulty.", "<white>This will tweak damage dealt/recieved,", "<white>and determine how much bonus EXP/Gold you can recieve."
				set slot 1 of the player's current inventory to 1 wooden sword named "<light green>Relaxed" with lore "<white>A laid-back mode for casual play.", "<white><bold>Damage dealt increased by 1.5x.", "<white><bold>Damage received reduced by 0.5x."
				set slot 2 of the player's current inventory to 1 stone sword named "<light gray>Normal" with lore "<white>The default Minecraft difficulty."
				set slot 3 of the player's current inventory to 1 iron sword named "<light red>Hard" with lore "<white>Recommended for fast and responsive gameplay.", "<white><bold>Damage dealt decreased by 0.5x.", "<white><bold>Damage received increased by 1.5x.", "<gold>Bonus EXP and Gold will be earned!"
				set slot 4 of the player's current inventory to 1 gold sword named "<red>Lunatic" with lore "<white>Recommended only for masters of combat and survival.", "<white><bold>Damage dealt decreased by 0.25x.", "<white><bold>Damage received increased by 3x.", "<gold>Bonus EXP and Gold will be earned!"
				set slot 5 of the player's current inventory to 1 diamond sword named "<purple>Infernal" with lore "<white>Your skills will be pushed to their absolute limits.", "<white><bold>Damage dealt decreased by 0.25x.", "<white><bold>Damage received increased by 5x.", "<gold>Bonus EXP and Gold will be earned!"
				if {perdiff.%player%} is 0:
					set slot 8 of the player's current inventory to 1 book named "<light green>Difficulty Selected: Relaxed"
				else if {perdiff.%player%} is 2:
					set slot 8 of the player's current inventory to 1 book named "<light gray>Difficulty Selected: Normal"
				else if {perdiff.%player%} is 3:
					set slot 8 of the player's current inventory to 1 book named "<light red>Difficulty Selected: Hard"
				else if {perdiff.%player%} is 4:
					set slot 8 of the player's current inventory to 1 book named "<red>Difficulty Selected: Lunatic"
				else if {perdiff.%player%} is 5:
					set slot 8 of the player's current inventory to 1 book named "<purple>Difficulty Selected: Infernal"
				if {generation.%player%} is more than 1:
					set slot 9 of the player's current inventory to 1 book named "<gold>Difficulty Modifiers" with lore "<white>This row contains toggleable modifiers to spice up your play.", "<white>Some toggles may be incompatible with others."
					set slot 16 of the player's current inventory to 1 book named "<gold>Active Toggles"
					if {thraciamode.%player%} is true:
						set slot 10 of the player's current inventory to 1 emerald block named "<light yellow>Thracian" with lore "<white>A toggleable mode that adds a hidden Avoid stat, allowing units to dodge attacks."
						set the 1st line of the lore of slot 16 of the player's current inventory to "<light yellow>Thracian: Enabled"
					else:
						set slot 10 of the player's current inventory to 1 gold sword named "<light yellow>Thracian" with lore "<white>A toggleable mode that adds a hidden Avoid stat, allowing units to dodge attacks."
				if {mqComplete.%player%} is 1:
					if {legholyknightmode.%player%} is true:
						set slot 11 of the player's current inventory to 1 emerald block named "<gold><bold>Legendary Holy Knight" with lore "<white>Enemies' levels are increased by +10.", "<white>All monsters have a 25%% chance to split into two more monsters when killed."
						set the 2nd line of the lore of slot 16 of the player's current inventory to "<gold>Legendary Holy Knight: Enabled"
					else:
						set slot 11 of the player's current inventory to 1 diamond sword of sharpness 10 named "<gold><bold>Legendary Holy Knight" with lore "<white>Enemies' levels are increased by +10.", "<white>All monsters have a 25%% chance to split into two more monsters when killed."
					if {allwillrotmode.%player%} is true:
						set slot 12 of the player's current inventory to 1 emerald block named "<purple><bold>All Will Rot" with lore "<white>Spawned monsters will be automatically upgraded to their Purgia-class counterparts."
						set the 3rd line of the lore of slot 16 of the player's current inventory to "<purple>All Will Rot: Enabled"
					else:
						set slot 12 of the player's current inventory to 1 fire charge named "<purple><bold>All Will Rot" with lore "<white>Spawned monsters will be automatically upgraded to their Purgia-class counterparts."
					if {reversalmode.%player%} is true:
						set slot 13 of the player's current inventory to 1 emerald block named "<purple><bold>Reversal" with lore "<white>All monsters gain a hidden Vantage perk."
						set the 4th line of the lore of slot 16 of the player's current inventory to "<purple>Reversal: Enabled"
					else:
						set slot 13 of the player's current inventory to 1 fishing rod named "<purple><bold>Reversal" with lore "<white>All monsters gain a hidden Vantage perk."
					if {nogrowths.%player%} is true:
						set slot 14 of the player's current inventory to 1 emerald block named "<light green><bold>0%% Growths" with lore "<white>Growth Rates for all stats will be set to 0%%."
						set the 5th line of the lore of slot 16 of the player's current inventory to "<light green>0%% Growths: Enabled"
					else:
						set slot 14 of the player's current inventory to 1 barrier named "<light green><bold>0%% Growths" with lore "<white>Growth Rates for all stats will be set to 0%%."
					if {negativegrowths.%player%} is true:
						set slot 15 of the player's current inventory to 1 emerald block named "<light blue><bold>Negative Growths" with lore "<white>Growth Rates will be inverted.","<white>Stats will DECREASE when they would normally increase.","<white>Promotions and stat-boosting items are unaffected."
						set the 5th line of the lore of slot 16 of the player's current inventory to "<light blue>Negative Growths: Enabled"
					else:
						set slot 15 of the player's current inventory to 1 stick named "<light blue><bold>Negative Growths" with lore "<white>Growth Rates will be inverted.","<white>Stats will DECREASE when they would normally increase.","<white>Promotions and stat-boosting items are unaffected."
				set slot 17 of the player's current inventory to 1 red glass pane named "<white><bold>Go Back"
			else if arg 2 is 2:
				open chest with 1 row named "<gold><bold>Elite Mode Toggle" for the player
				set slot 0 of the player's current inventory to 1 book named "<light blue>Information" with lore "<white>Elite mode boosts XP gained for kills.", "<white>If you feel that level-ups are too slow,", "<white>enable Elite Mode.", "<white>Click the wool to toggle Elite Mode."
				if {elitemode.%player%} is not set:
					set slot 4 of the player's current inventory to 1 red wool named "<light red>Elite Mode" with lore "<light red>Elite mode is currently OFF."
				else:
					set slot 4 of the player's current inventory to 1 blue wool named "<light blue>Elite Mode" with lore "<light blue>Elite mode is currently ON."
				if {generation.%player%} is not 1:
					set slot 8 of the player's current inventory to 1 green glass pane named "<light green>Confirm Character" with lore "<light green>Finishes all required character setup."
				else:
					set slot 8 of the player's current inventory to 1 green glass pane named "<light green>Select Class" with lore "<light green>Select your class, adjusting stat growths and weapon proficiency."
			else if arg 2 is 3:
				open chest with 1 row named "<gold><bold>Select Class" for the player
				set slot 0 of the player's current inventory to 1 nether star named "<gold>Mercenary" with lore "<white>A well-balanced infantry class.", "<light blue>Boons: None", "<light red>Banes: None"
				set slot 1 of the player's current inventory to 1 nether star named "<gold>Knight" with lore "<white>A slow, but sturdy infantry class.", "<light blue>Boons: HP, DEF", "<light red>Banes: SPD, MAG"
				set slot 2 of the player's current inventory to 1 nether star named "<gold>Bladesman" with lore "<white>Quick-footed infantry with a focus on evasion.", "<light blue>Boons: SPD, SKL", "<light red>Banes: DEF, MAG"
				set slot 3 of the player's current inventory to 1 nether star named "<gold>Fighter" with lore "<white>Strong-armed infantry with devastating blows.", "<light blue>Boons: STR, HP", "<light red>Banes: SKL, SPD"
				set slot 4 of the player's current inventory to 1 nether star named "<gold>Mage" with lore "<white>Magic wielders utilizing wands and tomes.", "<light blue>Boons: MAG, SKL", "<light red>Banes: DEF, STR"
				set slot 5 of the player's current inventory to 1 nether star named "<gold>Cleric" with lore "<white>Noncombatants wielding staves to heal the injured.", "<light blue>Boons: MAG, HP", "<light red>Banes: DEF, SPD, STR"
				set slot 6 of the player's current inventory to 1 nether star named "<gold>Archer" with lore "<white>An infantry class with a focus on ranged mastery.", "<light blue>Boons: DEF", "<light red>Banes: SKL"
				set slot 7 of the player's current inventory to 1 nether star named "<gold>Cavalier" with lore "<white>A well-balanced horse riding class.", "<light blue>Boons: None", "<light red>Banes: None"
				set slot 8 of the player's current inventory to 1 green glass pane named "<light green>Confirm Character" with lore "<light green>Finishes all required character setup."

#MARKER - Character Config				

on inventory click:
	#Selecting a Ring
	if the name of the player's current inventory is "<gold><bold>Select a ring.":
		cancel event
		if the name of the clicked item contains "Ring":
			give clicked item to the player
			make player execute command "/charsetup 2 2"
	else if the name of the player's current inventory is "<gold><bold>Select an heirloom.":
		cancel event
		if the name of the clicked item contains "<light blue><bold>":
			give clicked item to the player
			give 1 leather helmet to the player
			give 1 leather chestplate to the player
			give 1 leather leggings to the player
			give 1 leather boots to the player
			make player execute command "/charsetup 2 2"
	else if the name of the player's current inventory is "<gold><bold>Elite Mode Toggle":
		cancel event
		if the name of the clicked item contains "Elite Mode":
			if {elitemode.%player%} is not set:
				set {elitemode.%player%} to true
				set slot 4 of the player's current inventory to 1 blue wool named "<light blue>Elite Mode" with lore "<light blue>Elite mode is currently ON."
			else:
				clear {elitemode.%player%}
				set slot 4 of the player's current inventory to 1 red wool named "<light red>Elite Mode" with lore "<light red>Elite mode is currently OFF."
		else if the name of the clicked item contains "Select Class":
			make player execute command "/charsetup 2 3"
		else if the name of the clicked item is "<light green>Confirm Character":
			close the player's inventory
			set {pts_HP.%player%} to ({pts_HP.%player%} / 2)
			set {pts_STR.%player%} to ({pts_STR.%player%} / 2)
			set {pts_DEF.%player%} to ({pts_DEF.%player%} / 2)
			set {pts_SKL.%player%} to ({pts_SKL.%player%} / 2)
			set {pts_SPD.%player%} to ({pts_SPD.%player%} / 2)
			set {pts_MAG.%player%} to ({pts_MAG.%player%} / 2)
			set {hpcap.%player%} to (({pts_HP.%player%} / 5) * 3)
			set {strcap.%player%} to (({pts_STR.%player%} / 5) * 4)
			set {defcap.%player%} to (({pts_DEF.%player%} / 5) * 4)
			set {sklcap.%player%} to (({pts_SKL.%player%} / 5) * 4)
			set {spdcap.%player%} to (({pts_SPD.%player%} / 5) * 4)
			set {rescap.%player%} to (({pts_MAG.%player%} / 5) * 4)
			set {hp.%player%} to ({pts_HP.%player%} / 5)
			set {str.%player%} to ({pts_STR.%player%} / 5)
			set {def.%player%} to ({pts_DEF.%player%} / 5)
			set {skl.%player%} to ({pts_SKL.%player%} / 5)
			set {spd.%player%} to ({pts_SPD.%player%} / 5)
			set {res.%player%} to ({pts_MAG.%player%} / 5)
			set {promotionready.%player%} to 1
			make player execute command "/class promote %{class.%player%}%"
	else if the name of the player's current inventory is "<gold><bold>Character Configuration":
		cancel event
		#Stats
		if the name of the clicked item contains "HP":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			make player execute command "/charsetup 1 1"
		else if the name of the clicked item contains "STR":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			make player execute command "/charsetup 1 2"
		else if the name of the clicked item contains "DEF":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			make player execute command "/charsetup 1 3"
		else if the name of the clicked item contains "SKL":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			make player execute command "/charsetup 1 4"
		else if the name of the clicked item contains "SPD":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			make player execute command "/charsetup 1 5"
		else if the name of the clicked item contains "MAG":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			make player execute command "/charsetup 1 6"
		else if the name of the clicked item is "<green><bold>Reset Points":
			play sound "ui.button.click" with volume 0.25 and pitch 1 at the player for the player
			play sound "entity.zombie_villager.cure" with volume 0.5 and pitch 1 at the player for the player
			set {csetup_pts.%player%} to ({generation.%player%} * 120) + 120
			set {pts_MAG.%player%} to 10
			set {pts_HP.%player%} to 100
			set {pts_STR.%player%} to 10
			set {pts_DEF.%player%} to 10
			set {pts_SPD.%player%} to 10
			set {pts_SKL.%player%} to 10
			set slot 7 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
		#Confirm
		else if the name of the clicked item contains "Confirm":
			make player execute command "/charsetup 2 0"
		#Difficulty
		else if the name of the clicked item contains "Difficulty":
			make player execute command "/charsetup 2 1"
		#Gender
		else if the name of the clicked item is "<bold>Gender: Male":
			set {sex.%player%} to 0
			set slot 10 of the player's current inventory to 1 totem of undying named "<bold>Gender: Female" with lore "<white>Select which pronouns NPC's will refer to you by.", "<white>NOTE: Your gender will not impact your ability to support other players."
			play sound "ui.button.click" with volume 0.25 and pitch 1 at the player for the player
		else if the name of the clicked item is "<bold>Gender: Female":
			set {sex.%player%} to 1
			set slot 10 of the player's current inventory to 1 totem of undying named "<bold>Gender: Male" with lore "<white>Select which pronouns NPC's will refer to you by.", "<white>NOTE: Your gender will not impact your ability to support other players."
			play sound "ui.button.click" with volume 0.25 and pitch 1 at the player for the player
		#Point Presets
		else if the name of the clicked item is "<light yellow><bold>Presets":
			play sound "ui.button.click" with volume 0.25 and pitch 1 at the player for the player
			make player execute command "/charsetup 1 7"
		#PRF Weapon
		else if the name of the clicked item contains "Preferred Weapon":
			play sound "ui.button.click" with volume 0.25 and pitch 1 at the player for the player
			make player execute command "/charsetup 1 8"
		#Dodge Roll
		else if the name of the clicked item contains "Dodge Rolling":
			play sound "ui.button.click" with volume 0.25 and pitch 1 at the player for the player
			if {drenable.%player%} is 1:
				clear {dr.%player%}
				set slot 12 of the player's current inventory to 1 red wool named "<red>Dodge Rolling" with lore "<white>Allows you to perform invincible rolls by double-tapping the sneak key.", "<white>Dodge Rolling is currently disabled."
			else:
				set {drenable.%player%} to 1
				set slot 12 of the player's current inventory to 1 green wool named "<green>Dodge Rolling" with lore "<white>Allows you to perform invincible rolls by double-tapping the sneak key.", "<white>Dodge Rolling is currently enabled."
		#Realism
		else if the name of the clicked item is "<light blue>Realism: Disabled":
			play sound "ui.button.click" with volume 0.25 and pitch 1 at the player for the player
			set {realism.%player%} to 1
			set slot 14 of the player's current inventory to 1 water bottle named "<light blue>Realism: Enabled" with lore "<white>Makes survival more difficult by adding new mechanics.", "<white>Hunger depletes faster and is harder to replenish.", "<white>Thirst must be quenched occasionally.", "<white>Becoming too hot or cold can lead to death."
		else if the name of the clicked item is "<light blue>Realism: Enabled":
			play sound "ui.button.click" with volume 0.25 and pitch 1 at the player for the player
			clear {realism.%player%}
			set slot 14 of the player's current inventory to 1 water bottle named "<light blue>Realism: Disabled" with lore "<white>Makes survival more difficult by adding new mechanics.", "<white>Hunger depletes faster and is harder to replenish.", "<white>Thirst must be quenched occasionally.", "<white>Becoming too hot or cold can lead to death."
		#Hints
		else if the name of the clicked item is "<light yellow>Hints: Enabled":
			play sound "ui.button.click" with volume 0.25 and pitch 1 at the player for the player
			clear {tips.%player%}
			set slot 15 of the player's current inventory to 1 obsidian named "<light yellow>Hints: Disabled" with lore "<white>Prints periodic tips to the chat."
		else if the name of the clicked item is "<light yellow>Hints: Disabled":
			play sound "ui.button.click" with volume 0.25 and pitch 1 at the player for the player
			set {tips.%player%} to 1
			set slot 15 of the player's current inventory to 1 book named "<light yellow>Hints: Enabled" with lore "<white>Prints periodic tips to the chat."
		#Assist Type
		else if the name of the clicked item is "<light green>Assist Type":
			play sound "ui.button.click" with volume 0.25 and pitch 1 at the player for the player
			if {bhealth.%player%} is not set:
				if {farewells.%player%} is not set:
					set {farewells.%player%} to 1
					set slot 16 of the player's current inventory to 1 potion of healing named "<light green>Assist Type" with lore "<light blue>Assist Type: Bleedout", "<white>Upon taking mortal damage, you can be revived by another player for 15 seconds.", "<white>If no-one comes to your aid, you will die normally."
				else:
					clear {farewells.%player%}
					set {bhealth.%player%} to 1
					set slot 16 of the player's current inventory to 1 potion of healing named "<light green>Assist Type" with lore "<light blue>Assist Type: Last Stand", "<white>While above 1/2 heart:", "<white>Attacks that would normally kill you will be survived with 1/2 heart.", "<white>After activating, Last Stand needs 30 seconds to recharge."
			else:
				clear {bhealth.%player%}
				clear {farewells.%player%}
				set slot 16 of the player's current inventory to 1 potion of healing named "<light green>Assist Type" with lore "<white>Click to cycle between Bleedout, Last Stand, or no assists.", "<white>Assist Type: None"
	#PRF Weapon
	else if the name of the player's current inventory is "<gold><bold>Preferred Weapon":
		cancel event
		if the name of the clicked item contains "Swords":
			set {prfWeaponType.%player%} to 0
		else if the name of the clicked item contains "Axes":
			set {prfWeaponType.%player%} to 1
		else if the name of the clicked item contains "Lances":
			set {prfWeaponType.%player%} to 2
		else if the name of the clicked item contains "Bows":
			set {prfWeaponType.%player%} to 3
		else if the name of the clicked item contains "Magic":
			set {prfWeaponType.%player%} to 4
		else if the name of the clicked item contains "Staves":
			set {prfWeaponType.%player%} to 5
		else if the name of the clicked item contains "Go Back":
			make player execute command "/charsetup 1 0"
	#Difficulty
	else if the name of the player's current inventory is "<gold><bold>Select Difficulty":
		cancel event
		play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
		if the name of the clicked item contains "Relaxed":
			set {perdiff.%player%} to 0
			make player execute command "/charsetup 2 1"
		else if the name of the clicked item contains "Normal":
			set {perdiff.%player%} to 2
			make player execute command "/charsetup 2 1"
		else if the name of the clicked item contains "Hard":
			set {perdiff.%player%} to 3
			make player execute command "/charsetup 2 1"
		else if the name of the clicked item contains "Lunatic":
			set {perdiff.%player%} to 4
			make player execute command "/charsetup 2 1"
		else if the name of the clicked item contains "Infernal":
			set {perdiff.%player%} to 5
			make player execute command "/charsetup 2 1"
		else if the name of the clicked item contains "Thracian":
			if {thraciamode.%player%} is not set:
				set {thraciamode.%player%} to true
				set slot 10 of the player's current inventory to 1 emerald block named "<light yellow>Thracian" with lore "<white>A toggleable mode that adds a hidden Avoid stat, allowing units to dodge attacks."
			else:
				set slot 10 of the player's current inventory to 1 gold sword named "<light yellow>Thracian" with lore "<white>A toggleable mode that adds a hidden Avoid stat, allowing units to dodge attacks."
				clear {thraciamode.%player%}
			make player execute command "/charsetup 2 1"
		else if the name of the clicked item contains "Holy Knight":
			if {legholyknightmode.%player%} is not set:
				set {legholyknightmode.%Player%} to true
			else:
				set slot 11 of the player's current inventory to 1 emerald block named "<gold><bold>Legendary Holy Knight" with lore "<white>Enemies' levels are increased by +10.", "<white>All monsters have a 25%% chance to split into two more monsters when killed."
				clear {legholyknightmode.%player%}
			make player execute command "/charsetup 2 1"
		else if the name of the clicked item contains "Rot":
			if {allwillrotmode.%player%} is not set:
				set {allwillrotmode.%player%} to true
				set slot 12 of the player's current inventory to 1 emerald block named "<purple><bold>All Will Rot" with lore "<white>Spawned monsters will be automatically upgraded to their Purgia-class counterparts."
			else:
				set slot 12 of the player's current inventory to 1 fire charge named "<purple><bold>All Will Rot" with lore "<white>Spawned monsters will be automatically upgraded to their Purgia-class counterparts."
				clear {allwillrotmode.%player%}
			make player execute command "/charsetup 2 1"
		else if the name of the clicked item contains "Reversal":
			if {reversalmode.%player%} is not set:
				set {reversalmode.%player%} to true
				set slot 13 of the player's current inventory to 1 emerald block named "<purple><bold>Reversal" with lore "<white>All monsters gain a hidden Vantage perk."
			else:
				clear {reversalmode.%player%}
				set slot 13 of the player's current inventory to 1 fishing rod named "<purple><bold>Reversal" with lore "<white>All monsters gain a hidden Vantage perk."
			make player execute command "/charsetup 2 1"
		else if the name of the clicked item contains "Go Back":	
			make player execute command "/charsetup 1 0"
	#HP Config
	else if the name of the player's current inventory is "<gold><bold>HP Configuration":
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/charsetup 1 0"
		else if the name of the clicked item is "<bold>Remove 10 Points":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			if {pts_HP.%player%} is more than 100:
				subtract 10 from {pts_HP.%player%}
				add 10 to {csetup_pts.%player%}
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>HP" with lore "<white>Points Invested:", "<white>%{pts_HP.%player%}%"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
		else if the name of the clicked item is "<bold>Add 10 Points":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			if {csetup_pts.%player%} is more than or equal to 10:
				subtract 10 from {csetup_pts.%player%}
				add 10 to {pts_HP.%player%}
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>HP" with lore "<white>Points Invested:", "<white>%{pts_HP.%player%}%"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
		cancel event
	#STR Config
	else if the name of the player's current inventory is "<gold><bold>STR Configuration":
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/charsetup 1 0"
			cancel event
		else if the name of the clicked item is "<bold>Remove 10 Points":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			if {pts_STR.%player%} is more than 10:
				subtract 10 from {pts_STR.%player%}
				add 10 to {csetup_pts.%player%}
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>STR" with lore "<white>Points Invested:", "<white>%{pts_STR.%player%}%"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
		else if the name of the clicked item is "<bold>Add 10 Points":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			if {csetup_pts.%player%} is more than or equal to 10:
				subtract 10 from {csetup_pts.%player%}
				add 10 to {pts_STR.%player%}
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>STR" with lore "<white>Points Invested:", "<white>%{pts_STR.%player%}%"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
		cancel event
	#DEF Config
	else if the name of the player's current inventory is "<gold><bold>DEF Configuration":
		cancel event
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/charsetup 1 0"
		else if the name of the clicked item is "<bold>Remove 10 Points":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			if {pts_DEF.%player%} is more than 10:
				subtract 10 from {pts_DEF.%player%}
				add 10 to {csetup_pts.%player%}
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>DEF" with lore "<white>Points Invested:", "<white>%{pts_DEF.%player%}%"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
		else if the name of the clicked item is "<bold>Add 10 Points":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			if {csetup_pts.%player%} is more than or equal to 10:
				subtract 10 from {csetup_pts.%player%}
				add 10 to {pts_DEF.%player%}
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>DEF" with lore "<white>Points Invested:", "<white>%{pts_DEF.%player%}%"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
	#SKL Config
	else if the name of the player's current inventory is "<gold><bold>SKL Configuration":
		cancel event
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/charsetup 1 0"
		else if the name of the clicked item is "<bold>Remove 10 Points":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			if {pts_SKL.%player%} is more than 10:
				subtract 10 from {pts_SKL.%player%}
				add 10 to {csetup_pts.%player%}
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>SKL" with lore "<white>Points Invested:", "<white>%{pts_SKL.%player%}%"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
		else if the name of the clicked item is "<bold>Add 10 Points":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			if {csetup_pts.%player%} is more than or equal to 10:
				subtract 10 from {csetup_pts.%player%}
				add 10 to {pts_SKL.%player%}
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>SKL" with lore "<white>Points Invested:", "<white>%{pts_SKL.%player%}%"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
	#SPD Config
	else if the name of the player's current inventory is "<gold><bold>SPD Configuration":
		cancel event
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/charsetup 1 0"
		else if the name of the clicked item is "<bold>Remove 10 Points":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			if {pts_SPD.%player%} is more than 10:
				subtract 10 from {pts_SPD.%player%}
				add 10 to {csetup_pts.%player%}
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>SPD" with lore "<white>Points Invested:", "<white>%{pts_SPD.%player%}%"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
		else if the name of the clicked item is "<bold>Add 10 Points":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			if {csetup_pts.%player%} is more than or equal to 10:
				subtract 10 from {csetup_pts.%player%}
				add 10 to {pts_SPD.%player%}
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>SPD" with lore "<white>Points Invested:", "<white>%{pts_SPD.%player%}%"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
	#MAG Config
	else if the name of the player's current inventory is "<gold><bold>MAG Configuration":
		cancel event
		if the name of the clicked item is "<bold>Go Back":
			make player execute command "/charsetup 1 0"
		else if the name of the clicked item is "<bold>Remove 10 Points":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			if {pts_MAG.%player%} is more than 10:
				subtract 10 from {pts_MAG.%player%}
				add 10 to {csetup_pts.%player%}
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>MAG" with lore "<white>Points Invested:", "<white>%{pts_MAG.%player%}%"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
		else if the name of the clicked item is "<bold>Add 10 Points":
			play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
			if {csetup_pts.%player%} is more than or equal to 10:
				subtract 10 from {csetup_pts.%player%}
				add 10 to {pts_MAG.%player%}
				set slot 4 of the player's current inventory to 1 emerald named "<white><bold>MAG" with lore "<white>Points Invested:", "<white>%{pts_MAG.%player%}%"
				set slot 8 of the player's current inventory to 1 diamond named "<white><bold>Points to spend:" with lore "<gold><bold>%{csetup_pts.%player%}%"
	#Class Selecting
	else if the name of the player's current inventory is "<gold><bold>Select Class":
		play sound "ui.button.click" with volume 1 and pitch 1 at the player for the player
		cancel event
		if the name of the clicked item contains "Mercenary":
			set {class.%player%} to "Mercenary"
		else if the name of the clicked item contains "Knight":
			set {class.%player%} to "Knight"
		else if the name of the clicked item contains "Bladesman":
			set {class.%player%} to "Bladesman"
		else if the name of the clicked item contains "Fighter":
			set {class.%player%} to "Fighter"
		else if the name of the clicked item contains "Mage":
			set {class.%player%} to "Mage"
		else if the name of the clicked item contains "Cleric":
			set {class.%player%} to "Cleric"
		else if the name of the clicked item contains "Archer":
			set {class.%player%} to "Archer"
		else if the name of the clicked item contains "Cavalier":
			set {class.%player%} to "Cavalier"
		else if the name of the clicked item is "<light green>Confirm Character":
			close the player's inventory
			set {pts_HP.%player%} to ({pts_HP.%player%} / 2)
			set {pts_STR.%player%} to ({pts_STR.%player%} / 2)
			set {pts_DEF.%player%} to ({pts_DEF.%player%} / 2)
			set {pts_SKL.%player%} to ({pts_SKL.%player%} / 2)
			set {pts_SPD.%player%} to ({pts_SPD.%player%} / 2)
			set {pts_MAG.%player%} to ({pts_MAG.%player%} / 2)
			set {hpcap.%player%} to (({pts_HP.%player%} / 5) * 3)
			set {strcap.%player%} to (({pts_STR.%player%} / 5) * 4)
			set {defcap.%player%} to (({pts_DEF.%player%} / 5) * 4)
			set {sklcap.%player%} to (({pts_SKL.%player%} / 5) * 4)
			set {spdcap.%player%} to (({pts_SPD.%player%} / 5) * 4)
			set {rescap.%player%} to (({pts_MAG.%player%} / 5) * 4)
			set {hp.%player%} to ({pts_HP.%player%} / 5)
			set {str.%player%} to ({pts_STR.%player%} / 5)
			set {def.%player%} to ({pts_DEF.%player%} / 5)
			set {skl.%player%} to ({pts_SKL.%player%} / 5)
			set {spd.%player%} to ({pts_SPD.%player%} / 5)
			set {res.%player%} to ({pts_MAG.%player%} / 5)
			set {promotionready.%player%} to 1
			make player execute command "/class promote %{class.%player%}%"
		
#MARKER - Cosmetics


#Cosmetics:
#arg 1: 0 = help, 1 = add, 2 = remove
#arg 2: type of quote, 1 = level-up, 2 = skill activation, 3 = character name
#arg 3: slot			
command /cosmetics [<number=0>] [<number=0>] [<number=0>]:
	aliases: /quotes
	trigger:
		if arg 1 is 0:
			send "<run command:/cosmetics 1 1><yellow>Click here to configure level-up quotes."
			send "<run command:/cosmetics 1 2><light green>Click here to configure skill activation quotes."
			send "<run command:/cosmetics 1 4><light blue>Click here to configure context-sensitive quotes."
			send "<run command:/cosmetics 1 3><gold>Click here to change your character's name."
			send "<run command:/cosmetics 4><light purple>Click here to select a premade set of quotes."
		else if arg 1 is 1:
			if arg 2 is 1:
				send "<light green>Click a slot shown here and send a message in chat to change the quote."
				send "<light green>Level-up quotes:"
				send "<run command:/cosmetics 3 1 1><light green>Poor level-up (1 stat up): %{badLevelQuote.%player%}%"
				send "<run command:/cosmetics 3 1 2><light green>Average level-up (2-4 stats up): %{avgLevelQuote.%player%}%"
				send "<run command:/cosmetics 3 1 3><light green>Good level-up (5-6 stats up): %{goodLevelQuote.%player%}%"
				send "<run command:/cosmetics 3 1 4><light green>Max Potential (only a few more stat ups): %{maxLevelQuote.%player%}%"
				send "<run command:/cosmetics 3 1 5><light green>Promotion (Using a crest): %{promotionQuote.%player%}%"
				send "<run command:/cosmetics><light blue>Return to main set-up"
			else if arg 2 is 2:
				send "<yellow>Click a slot shown here and send a message in chat to change the quote."
				send "<yellow>Skill Activation quotes (sent to both you and your foe):"
				send "<run command:/cosmetics 3 2 1><yellow>Slot 1: %{skillquote1.%player%}%"
				send "<run command:/cosmetics 3 2 2><yellow>Slot 2: %{skillquote2.%player%}%"
				send "<run command:/cosmetics 3 2 3><yellow>Slot 3: %{skillquote3.%player%}%"
				send "<run command:/cosmetics 3 2 4><yellow>Slot 4: %{skillquote4.%player%}%"
				send "<run command:/cosmetics><light blue>Return to main set-up"
			else if arg 2 is 3:
				send "<gold>Type in a new name for your character in chat."
				send "<gold>You can add colours using standard colour codes."
				set {editName.%player%} to true
			else if arg 2 is 4:
				send "<run command:/cosmetics 1 5><light blue>Player health quotes"
				send "<run command:/cosmetics 1 6><light blue>Ally health responses"
				send "<run command:/cosmetics 1 7><light blue>Player victory quotes"
				send "<run command:/cosmetics 1 8><light blue>Ally victory responses"
				send "<run command:/cosmetics><light blue>Return to main set-up"
			else if arg 2 is 5:
				send "<light blue>Player health quotes (click to edit):"
				send "<run command:/cosmetics 3 3 1><light blue>Low HP: ""%{lowHPQuote.%player%}%"""
				send "<run command:/cosmetics 3 3 2><light blue>Medium HP: ""%{mediumHPQuote.%player%}%"""
				send "<run command:/cosmetics 3 3 3><light blue>Downed: ""%{downedQuote.%player%}%"""
				send "<run command:/cosmetics 3 3 4><light blue>Death: ""%{deathQuote.%player%}%"""
				send "<run command:/cosmetics 3 3 5><light blue>Healed by ally: ""%{healedQuote.%player%}%"""
				send "<run command:/cosmetics 1 4><cyan>Go Back"
			else if arg 2 is 6:
				send "<light blue>Ally health responses (click to edit):"
				send "<run command:/cosmetics 3 3 6><light blue>Ally hurt: ""%{allyHurtLarge1.%player%}%"""
				send "<run command:/cosmetics 3 3 7><light blue>Ally hurt: ""%{allyHurtLarge2.%player%}%"""
				send "<run command:/cosmetics 3 3 8><light blue>Ally needs healing: ""%{allyNeedHealing.%player%}%"""
				send "<run command:/cosmetics 3 3 9><light blue>Ally dies: ""%{allyDeathQuote.%player%}%"""
				send "<run command:/cosmetics 3 3 10><light blue>Ally dies (hardcore): ""%{allyHardcoreDeathQuote.%player%}%"""
				send "<run command:/cosmetics 3 3 11><light blue>Picking up downed ally: ""%{allyDownedQuote.%player%}%"""
				send "<run command:/cosmetics><cyan>Go Back"
			else if arg 2 is 7:
				send "<light blue>Player victory quotes (click to edit):"
				send "<run command:/cosmetics 3 3 12><light blue>Enemy defeated: ""%{enemyDefeated1.%player%}%"""
				send "<run command:/cosmetics 3 3 13><light blue>Enemy defeated: ""%{enemyDefeated2.%player%}%"""
				send "<run command:/cosmetics 3 3 14><light blue>Boss defeated: ""%{bossDefeated1.%player%}%"""
				send "<run command:/cosmetics 3 3 15><light blue>Boss defeated: ""%{bossDefeated2.%player%}%"""
				send "<run command:/cosmetics 1 4><cyan>Go Back"
			else if arg 2 is 8:
				send "<light blue>Ally victory responses (click to edit):"
				send "<run command:/cosmetics 3 3 16><light blue>Ally defeats enemy: ""%{allyEnemyDefeated1.%player%}%"""
				send "<run command:/cosmetics 3 3 17><light blue>Ally defeats enemy: ""%{allyEnemyDefeated2.%player%}%"""
				send "<run command:/cosmetics 3 3 18><light blue>Ally defeats enemy: ""%{allyEnemyDefeated3.%player%}%"""
				send "<run command:/cosmetics 1 4><cyan>Go Back"
		else if arg 1 is 3:
			if arg 2 is 1:
				set {editLevelQuote%arg 3%.%player%} to true
				send "<light green>Type in the new quote now."
			else if arg 2 is 2:
				set {editSkillQuote%arg 3%.%player%} to true
				send "<yellow>Type in the new quote now."
			else if arg 2 is 3:
				set {editCSQuote%arg 3%.%player%} to true
				send "<light blue>Type in the new quote now."
		else if arg 1 is 4:
			send "<light purple>Quote Presets:"
			send "<run command:/cosmetics 5 1><light purple>Gray"
			send "<run command:/cosmetics 5 2><light purple>Alm"
			send "<run command:/cosmetics 5 5><light purple>Greil"
			send "<run command:/cosmetics 5 6><light purple>Reinhardt"
			send "<run command:/cosmetics 5 7><light purple>Lukas"
			send "<run command:/cosmetics 5 11><light purple>Leif"
			send "<run command:/cosmetics 5 3><light purple>Genny"
			send "<run command:/cosmetics 5 4><light purple>Clair"
			send "<run command:/cosmetics 5 8><light purple>Celica"
			send "<run command:/cosmetics 5 9><light purple>Faye"
			send "<run command:/cosmetics 5 10><light purple>Katarina"
			send "<run command:/cosmetics 5 12><light green>Silent"
			send "<run command:/cosmetics><light blue>Go Back"
		else if arg 1 is 5:
			if arg 2 is 1:
				if arg 3 is 1:
					set {badLevelQuote.%player%} to "Uh, what was THAT?"
					set {avgLevelQuote.%player%} to "This'll do. I guess."
					set {goodLevelQuote.%player%} to "Lady luck smiles on me... Thanks, lady!"
					set {maxLevelQuote.%player%} to "Can't ask for more than this."
					set {promotionQuote.%player%} to "Welp, here goes nothing."
					set {skillquote1.%player%} to "Aaaand, we're done!"
					set {skillquote2.%player%} to "Come at me, fools!"
					set {skillquote3.%player%} to "Bye now!"
					set {skillquote4.%player%} to "Sorry!"
					set {lowHPQuote.%player%} to "I'm ready to keel over here..."
					set {healedQuote.%player%} to "Hey, thanks!"
					set {mediumHPQuote.%player%} to "Nothing serious... Just keep going."
					set {downedQuote.%player%} to "It's not too... Ow. Okay, yeah that hurts. Someone mind helping me out?"
					set {allyDownedQuote.%player%} to "What're you doing? Get up!"
					set {enemyDefeated1.%player%} to "It's hard being this good."
					set {enemyDefeated2.%player%} to "Well, look at me go!"
					set {bossDefeated1.%player%} to "Hey, can the next fight be less... painful?"
					set {bossDefeated2.%player%} to "Heh, look who's still standing!"
					set {deathQuote.%player%} to "Why must the good men die... so young..."
					set {allyNeedHealing.%player%} to "Hey, heal before you're dead, yeah?"
					set {allyDeathQuote.%player%} to "Even I can't find a bright side to this..."
					set {allyHardcoreDeathQuote.%player%} to "You idiot... What were you thinking...?!"
					set {allyEnemyDefeated1.%player%} to "Hey, stop hoggin' all the fun!"
					set {allyEnemyDefeated2.%player%} to "Well, lookie there!"
					set {allyEnemyDefeated3.%player%} to "Man, look at you go!"
					set {allyHurtLarge1.%player%} to "You alright there?"
					set {allyHurtLarge2.%player%} to "Hey, careful!"
					send "<run command:/cosmetics><light blue>Preset applied. Click here to return to main set-up"
				else:
					send "<light purple>Quote preset: Gray"
					send "<light purple>Samples:"
					send "<light purple>Bad Level-up: ""Uh, what was THAT?"""
					send "<light purple>Good Level-up: ""Lady luck smiles on me... Thanks, lady!"""
					send "<light purple>Skill activation 1: ""Aaaand, we're done!"""
					send "<light purple>Skill activation 2: ""Come at me, fools!"""
					send "<light purple>Low HP warning: ""I'm ready to keel over here..."""
					send "<run command:/cosmetics 5 1 1><light green>Apply preset"
					send "<run command:/cosmetics><light blue>Return to main set-up"
			if arg 2 is 2:
				if arg 3 is 1:
					set {badLevelQuote.%player%} to "Huh? ...Just my imagination I guess."
					set {avgLevelQuote.%player%} to "I can tell I'm getting stronger."
					set {goodLevelQuote.%player%} to "It's almost as if someone's watching over me..."
					set {maxLevelQuote.%player%} to "Well, there's not much else I can work on."
					set {promotionQuote.%player%} to "Now I'll show them what I can really do."
					set {skillquote1.%player%} to "This is how it's done!"
					set {skillquote2.%player%} to "This ends here!"
					set {skillquote3.%player%} to "Take this!"
					set {skillquote4.%player%} to "It's over!"
					set {lowHPQuote.%player%} to "This is tough..."
					set {healedQuote.%player%} to "Thank you."
					set {mediumHPQuote.%player%} to "I can do this..."
					set {downedQuote.%player%} to "Any more and I become a liability... I need some help..."
					set {allyDownedQuote.%player%} to "Stay focused, all right?"
					set {enemyDefeated1.%player%} to "That should do it!"
					set {enemyDefeated2.%player%} to "There we go!"
					set {bossDefeated1.%player%} to "That was a fine victory."
					set {bossDefeated2.%player%} to "This is my strength."
					set {deathQuote.%player%} to "No... not when we were... so close..."
					set {allyNeedHealing.%player%} to "You'd better heal."
					set {allyDeathQuote.%player%} to "Wha...?! No, no! Not you..!"
					set {allyHardcoreDeathQuote.%player%} to "I knew there would be sacrifices, but..."
					set {allyEnemyDefeated1.%player%} to "You did it again!"
					set {allyEnemyDefeated2.%player%} to "You really are amazing."
					set {allyEnemyDefeated3.%player%} to "I'm proud to know you!"
					set {allyHurtLarge1.%player%} to "Hey. Focus."
					set {allyHurtLarge2.%player%} to "You need to be careful."
					send "<run command:/cosmetics><light blue>Preset applied. Click here to return to main set-up"
				else:
					send "<light purple>Quote preset: Alm"
					send "<light purple>Samples:"
					send "<light purple>Bad Level-up: ""Huh? ...Just my imagination I guess."""
					send "<light purple>Good Level-up: ""I can tell I'm getting stronger."""
					send "<light purple>Skill activation 1: ""This is how it's done!"""
					send "<light purple>Skill activation 2: ""This ends here!"""
					send "<light purple>Low HP warning: ""This is tough..."""
					send "<run command:/cosmetics 5 2 1><light green>Apply preset"
					send "<run command:/cosmetics><light blue>Return to main set-up"
			if arg 2 is 5:
				if arg 3 is 1:
					set {badLevelQuote.%player%} to "Whoops. Sorry about that."
					set {avgLevelQuote.%player%} to "Getting back into the swing of things..."
					set {goodLevelQuote.%player%} to "Everyone's watching. I have to give 'em a show."
					set {maxLevelQuote.%player%} to "Looks like I've reached my peak."
					set {promotionQuote.%player%} to "A lot's expected of me. I'd better deliver."
					set {skillquote1.%player%} to "I'll start us off."
					set {skillquote2.%player%} to "I need to survive."
					set {skillquote3.%player%} to "I like your resolve."
					set {skillquote4.%player%} to "Here's a gift."
					set {lowHPQuote.%player%} to "Haven't felt like this... in a long time."
					set {healedQuote.%player%} to "Thanks."
					set {mediumHPQuote.%player%} to "I've still got plenty left in me."
					set {downedQuote.%player%} to "I'm faltering... If someone could help me out..."
					set {allyDownedQuote.%player%} to "Don't push yourself too hard, now."
					set {enemyDefeated1.%player%} to "There we go."
					set {enemyDefeated2.%player%} to "Done."
					set {bossDefeated1.%player%} to "Well fought."
					set {bossDefeated2.%player%} to "Looks like more training was needed."
					set {deathQuote.%player%} to "I can do no more..."
					set {allyNeedHealing.%player%} to "You should get healing."
					set {allyDeathQuote.%player%} to "What?! You can't die like this..!"
					set {allyHardcoreDeathQuote.%player%} to "I'm sorry. I should've done more for you..."
					set {allyEnemyDefeated1.%player%} to "I'm proud of you."
					set {allyEnemyDefeated2.%player%} to "Well, well."
					set {allyEnemyDefeated3.%player%} to "Well done."
					set {allyHurtLarge1.%player%} to "Keep your chin up."
					set {allyHurtLarge2.%player%} to "Back away. Let me take care of this."
					send "<run command:/cosmetics><light blue>Preset applied. Click here to return to main set-up"
				else:
					send "<light purple>Quote preset: Greil"
					send "<light purple>Samples:"
					send "<light purple>Bad Level-up: ""Whoops. Sorry about that."""
					send "<light purple>Good Level-up: ""Everyone's watching. I have to give 'em a show."""
					send "<light purple>Skill activation 1: ""I'll start us off."""
					send "<light purple>Skill activation 2: ""I need to survive."""
					send "<light purple>Low HP warning: ""Haven't felt like this... in a long time."""
					send "<run command:/cosmetics 5 5 1><light green>Apply preset"
					send "<run command:/cosmetics><light blue>Return to main set-up"
			if arg 2 is 3:
				if arg 3 is 1:
					set {badLevelQuote.%player%} to "...Huh?"
					set {avgLevelQuote.%player%} to "I think I'm getting stronger?"
					set {goodLevelQuote.%player%} to "I did pretty good, right?"
					set {maxLevelQuote.%player%} to "I'm ready to roll!"
					set {promotionQuote.%player%} to "Please, offer me guidance..."
					set {skillquote1.%player%} to "I... do not... like you!"
					set {skillquote2.%player%} to "Now I'm angry!"
					set {skillquote3.%player%} to "Sorry!"
					set {skillquote4.%player%} to "You need to move!"
					set {lowHPQuote.%player%} to "I-I'll try my best..."
					set {healedQuote.%player%} to "I really needed that!"
					set {mediumHPQuote.%player%} to "Okay, I got this."
					set {downedQuote.%player%} to "This... this is too much... Can someone help me?"
					set {allyDownedQuote.%player%} to "Cheer up!"
					set {enemyDefeated1.%player%} to "Like this?"
					set {enemyDefeated2.%player%} to "Yah!"
					set {bossDefeated1.%player%} to "Hehe... I did pretty good, right?"
					set {bossDefeated2.%player%} to "No one likes a bully!"
					set {deathQuote.%player%} to "Oof... that hurts... Is this...goodbye?"
					set {allyNeedHealing.%player%} to "You need to be healed..."
					set {allyDeathQuote.%player%} to "No, please! Don't go yet..!"
					set {allyHardcoreDeathQuote.%player%} to "No..! I hate this..."
					set {allyEnemyDefeated1.%player%} to "Watch my back, okay?"
					set {allyEnemyDefeated2.%player%} to "You're amazing!"
					set {allyEnemyDefeated3.%player%} to "Wow! You're really strong, huh?"
					set {allyHurtLarge1.%player%} to "Watch out!"
					set {allyHurtLarge2.%player%} to "Please be careful..."
					send "<run command:/cosmetics><light blue>Preset applied. Click here to return to main set-up"
				else:
					send "<light purple>Quote preset: Genny"
					send "<light purple>Samples:"
					send "<light purple>Bad Level-up: ""...Huh?"""
					send "<light purple>Good Level-up: ""I did pretty good, right?"""
					send "<light purple>Skill activation 1: ""I... do not... like you!"""
					send "<light purple>Skill activation 2: ""You need to move!"""
					send "<light purple>Low HP warning: ""I-I'll try my best..."""
					send "<run command:/cosmetics 5 3 1><light green>Apply preset"
					send "<run command:/cosmetics><light blue>Return to main set-up"
			if arg 2 is 4:
				if arg 3 is 1:
					set {badLevelQuote.%player%} to "I felt...something. But it wasn't anything to pen home about."
					set {avgLevelQuote.%player%} to "Next time, I insist my growths improve."
					set {goodLevelQuote.%player%} to "Fate and fortune smile upon me!"
					set {maxLevelQuote.%player%} to "Have you ever seen such physical perfection?"
					set {promotionQuote.%player%} to "If this is the life I shall lead..."
					set {skillquote1.%player%} to "You should be honored."
					set {skillquote2.%player%} to "On your knees!"
					set {skillquote3.%player%} to "You brute!"
					set {skillquote4.%player%} to "Too late!"
					set {lowHPQuote.%player%} to "If we must..."
					set {healedQuote.%player%} to "Why, thank you."
					set {mediumHPQuote.%player%} to "Shall we, then?."
					set {downedQuote.%player%} to "How careless of me... I require aid..."
					set {allyDownedQuote.%player%} to "I insist we do better."
					set {enemyDefeated1.%player%} to "May I?"
					set {enemyDefeated2.%player%} to "Begone!"
					set {bossDefeated1.%player%} to "I hope you were all watching."
					set {bossDefeated2.%player%} to "A glorious victory."
					set {deathQuote.%player%} to "I may have pushed myself... too hard..."
					set {allyNeedHealing.%player%} to "You must heal."
					set {allyDeathQuote.%player%} to "What? No...! No, no!"
					set {allyHardcoreDeathQuote.%player%} to "Already, the victory feels... hollow."
					set {allyEnemyDefeated1.%player%} to "Does nothing stop you?"
					set {allyEnemyDefeated2.%player%} to "That was marvelous!"
					set {allyEnemyDefeated3.%player%} to "We're lucky to have you."
					set {allyHurtLarge1.%player%} to "You must not fail us."
					set {allyHurtLarge2.%player%} to "Shameful..."
					send "<run command:/cosmetics><light blue>Preset applied. Click here to return to main set-up"
				else:
					send "<light purple>Quote preset: Clair"
					send "<light purple>Samples:"
					send "<light purple>Bad Level-up: ""I  felt...something. But it wasn't anything to pen home about."""
					send "<light purple>Good Level-up: ""Fate and fortune smile upon me!"""
					send "<light purple>Skill activation 1: ""On your knees!"""
					send "<light purple>Skill activation 2: ""You should be honored."""
					send "<light purple>Low HP warning: ""If we must..."""
					send "<run command:/cosmetics 5 4 1><light green>Apply preset"
					send "<run command:/cosmetics><light blue>Return to main set-up"
			if arg 2 is 8:
				if arg 3 is 1:
					set {badLevelQuote.%player%} to "Hmm? I could've sworn I felt something..."
					set {avgLevelQuote.%player%} to "Just a little more progress each day..."
					set {goodLevelQuote.%player%} to "My skills on the battlefield are improving."
					set {maxLevelQuote.%player%} to "May this strength be enough to keep my friends safe."
					set {promotionQuote.%player%} to "I'll do whatever is needed."
					set {skillquote1.%player%} to "This is a fight I cannot lose!"
					set {skillquote2.%player%} to "I'm not about to stop here!"
					set {skillquote3.%player%} to "Grant me strength!"
					set {skillquote4.%player%} to "It's over!"
					set {lowHPQuote.%player%} to "Ngh... Gods protect me..."
					set {healedQuote.%player%} to "Much appreciated."
					set {mediumHPQuote.%player%} to "I'm all right."
					set {downedQuote.%player%} to "I feel I've reached my limits... I need help..."
					set {allyDownedQuote.%player%} to "Are you alright?"
					set {enemyDefeated1.%player%} to "How's THIS?"
					set {enemyDefeated2.%player%} to "Move!"
					set {bossDefeated1.%player%} to "I won't ask forgiveness."
					set {bossDefeated2.%player%} to "I fight to protect what is dear."
					set {deathQuote.%player%} to "In the end, I couldn't save anyone... I'm so sorry..."
					set {allyNeedHealing.%player%} to "You'd best take care of those wounds."
					set {allyDeathQuote.%player%} to "Wha... No! No, please! You have to live...!"
					set {allyHardcoreDeathQuote.%player%} to "We must continue, no matter the cost."
					set {allyEnemyDefeated1.%player%} to "Excellent!"
					set {allyEnemyDefeated2.%player%} to "I'm happy you're on my side."
					set {allyEnemyDefeated3.%player%} to "I can only envy your strength!"
					set {allyHurtLarge1.%player%} to "You have to stay strong."
					set {allyHurtLarge2.%player%} to "You're not finished yet, stay with us!"
					send "<run command:/cosmetics><light blue>Preset applied. Click here to return to main set-up"
				else:
					send "<light purple>Quote preset: Celica"
					send "<light purple>Samples:"
					send "<light purple>Bad Level-up: ""Hmm? I could've sworn I felt something..."""
					send "<light purple>Good Level-up: ""My skills on the battlefield are improving."""
					send "<light purple>Skill activation 1: ""This is a fight I cannot lose!"""
					send "<light purple>Skill activation 2: ""I'm not about to stop here!"""
					send "<light purple>Low HP warning: ""Ngh... Gods protect me..."""
					send "<run command:/cosmetics 5 8 1><light green>Apply preset"
					send "<run command:/cosmetics><light blue>Return to main set-up"
			if arg 2 is 9:
				if arg 3 is 1:
					set {badLevelQuote.%player%} to "Hmm... I thought I felt something."
					set {avgLevelQuote.%player%} to "Just a little more progress each day..."
					set {goodLevelQuote.%player%} to "It's nice to get stronger."
					set {maxLevelQuote.%player%} to "I don't need any more muscles, thanks."
					set {promotionQuote.%player%} to "I'll grow however I can to keep everyone safe."
					set {skillquote1.%player%} to "Don't test me!"
					set {skillquote2.%player%} to "Wrong move!"
					set {skillquote3.%player%} to "I've had it!"
					set {skillquote4.%player%} to "No more!"
					set {lowHPQuote.%player%} to "U-uhm... all right..."
					set {healedQuote.%player%} to "You're too kind."
					set {mediumHPQuote.%player%} to "I'm still ready to go!"
					set {downedQuote.%player%} to "Oh... I'm so sorry... I need help..."
					set {allyDownedQuote.%player%} to "We all make mistakes."
					set {enemyDefeated1.%player%} to "Gotcha!"
					set {enemyDefeated2.%player%} to "Step aside!"
					set {bossDefeated1.%player%} to "I was taught by the best."
					set {bossDefeated2.%player%} to "Did you see that, everyone?"
					set {deathQuote.%player%} to "E-everyone... I..."
					set {allyNeedHealing.%player%} to "You'd better do something about those wounds."
					set {allyDeathQuote.%player%} to "Oh, no! Don't go yet, please!"
					set {allyHardcoreDeathQuote.%player%} to "This is horrible..."
					set {allyEnemyDefeated1.%player%} to "Incredible!"
					set {allyEnemyDefeated2.%player%} to "That got their attention."
					set {allyEnemyDefeated3.%player%} to "You're a model to follow."
					set {allyHurtLarge1.%player%} to "Don't push yourself too hard."
					set {allyHurtLarge2.%player%} to "Try and be more careful, OK?"
					send "<run command:/cosmetics><light blue>Preset applied. Click here to return to main set-up"
				else:
					send "<light purple>Quote preset: Faye"
					send "<light purple>Samples:"
					send "<light purple>Bad Level-up: ""Hmm... I thought I felt something."""
					send "<light purple>Good Level-up: ""It's nice to get stronger."""
					send "<light purple>Skill activation 1: ""I've had it!"""
					send "<light purple>Skill activation 2: ""No more!"""
					send "<light purple>Low HP warning: ""U-uhm... all right..."""
					send "<run command:/cosmetics 5 9 1><light green>Apply preset"
					send "<run command:/cosmetics><light blue>Return to main set-up"
			if arg 2 is 6:
				if arg 3 is 1:
					set {badLevelQuote.%player%} to "Such a failing. Am I losing my conviction?"
					set {avgLevelQuote.%player%} to "At this rate, I may achieve what I must."
					set {goodLevelQuote.%player%} to "Better than expected. I should always focus this much."
					set {maxLevelQuote.%player%} to "My will is strong. I promise excellent results."
					set {promotionQuote.%player%} to "This is an honor. I pledge to prevail in battle."
					set {skillquote1.%player%} to "I'll show you how it's done!"
					set {skillquote2.%player%} to "Forward, now!"
					set {skillquote3.%player%} to "You will back down."
					set {skillquote4.%player%} to "This must be fate."
					set {lowHPQuote.%player%} to "Their strength is... extraordinary..."
					set {healedQuote.%player%} to "You have my gratitude."
					set {mediumHPQuote.%player%} to "I am far from finished. What is our plan?"
					set {downedQuote.%player%} to "Such a failing... I require assistance..."
					set {allyDownedQuote.%player%} to "I will remain with you as long as I can."
					set {enemyDefeated1.%player%} to "Excuse me."
					set {enemyDefeated2.%player%} to "Forgive me."
					set {bossDefeated1.%player%} to "Our forces are unstoppable."
					set {bossDefeated2.%player%} to "Our tactics have brought us a decisive victory."
					set {deathQuote.%player%} to "My... regrets..."
					set {allyNeedHealing.%player%} to "I advise you to seek aid."
					set {allyDeathQuote.%player%} to "I beg you... give me a chance to reclaim my honor..."
					set {allyHardcoreDeathQuote.%player%} to "My dear friend... I have failed you utterly..."
					set {allyEnemyDefeated1.%player%} to "Your strategems are... extraordinary."
					set {allyEnemyDefeated2.%player%} to "You have become rather formidable."
					set {allyEnemyDefeated3.%player%} to "As long as we have you, there is little chance we will be defeated."
					set {allyHurtLarge1.%player%} to "Guard your health, we cannot afford to lose you."
					set {allyHurtLarge2.%player%} to "Please, stay close to me. I will protect you from further harm."
					send "<run command:/cosmetics><light blue>Preset applied. Click here to return to main set-up"
				else:
					send "<light purple>Quote preset: Reinhardt"
					send "<light purple>Samples:"
					send "<light purple>Bad Level-up: ""Such a failing. Am I losing my conviction?"""
					send "<light purple>Good Level-up: ""Better than expected. I should always focus this much."""
					send "<light purple>Skill activation 1: ""I'll show you how it's done!"""
					send "<light purple>Skill activation 2: ""You will back down."""
					send "<light purple>Low HP warning: ""Their strength is... extraordinary..."""
					send "<run command:/cosmetics 5 6 1><light green>Apply preset"
					send "<run command:/cosmetics><light blue>Return to main set-up"
			if arg 2 is 7:
				if arg 3 is 1:
					set {badLevelQuote.%player%} to "How dissapointing. I must refocus my efforts..."
					set {avgLevelQuote.%player%} to "Respectable gains, but there is still more to be done."
					set {goodLevelQuote.%player%} to "I'm finally reaching my stride... Hopefully my tactics can follow suit."
					set {maxLevelQuote.%player%} to "So I've reached my peak... Now I can contribute fully."
					set {promotionQuote.%player%} to "Ever forward, with ever greater courage!"
					set {skillquote1.%player%} to "Just as planned!"
					set {skillquote2.%player%} to "You've made your last mistake!"
					set {skillquote3.%player%} to "I refuse to yield!"
					set {skillquote4.%player%} to "Everything's fallen into place!"
					set {lowHPQuote.%player%} to "I-its... part of the plan..."
					set {healedQuote.%player%} to "My gratitude."
					set {mediumHPQuote.%player%} to "The wounds are minimal... The plan will still work..."
					set {downedQuote.%player%} to "Gah! Such a mis-step... I require aid..."
					set {allyDownedQuote.%player%} to "Do not blame yourself. This was a mistake on my part."
					set {enemyDefeated1.%player%} to "And so the pawn falls."
					set {enemyDefeated2.%player%} to "Checkmate."
					set {bossDefeated1.%player%} to "The battle is won. Well done, everyone."
					set {bossDefeated2.%player%} to "I must admit, even I did not expect such an outcome..."
					set {deathQuote.%player%} to "How could this...! My regrets... everyone..."
					set {allyNeedHealing.%player%} to "You must be healed."
					set {allyDeathQuote.%player%} to "No..! This wasn't a part of the plan..!"
					set {allyHardcoreDeathQuote.%player%} to "I... I'm so ashamed of myself... How could I have made such a grevious mistake..?"
					set {allyEnemyDefeated1.%player%} to "Excellently done!"
					set {allyEnemyDefeated2.%player%} to "Impressive!"
					set {allyEnemyDefeated3.%player%} to "I hadn't planned for that... well done!"
					set {allyHurtLarge1.%player%} to "Be careful! We cannot afford to lose you now!"
					set {allyHurtLarge2.%player%} to "Stay behind me! I will not allow you to die under my command!"
					send "<run command:/cosmetics><light blue>Preset applied. Click here to return to main set-up"
				else:
					send "<light purple>Quote preset: Lukas"
					send "<light purple>Samples:"
					send "<light purple>Bad Level-up: ""How dissapointing. I must refocus my efforts..."""
					send "<light purple>Good Level-up: ""I'm finally reaching my stride... Hopefully my tactics can follow suit."""
					send "<light purple>Skill activation 1: ""You've made your last mistake!"""
					send "<light purple>Skill activation 2: ""Just as planned!"""
					send "<light purple>Low HP warning: ""I-its... part of the plan..."""
					send "<run command:/cosmetics 5 7 1><light green>Apply preset"
					send "<run command:/cosmetics><light blue>Return to main set-up"
			if arg 2 is 10:
				if arg 3 is 1:
					set {badLevelQuote.%player%} to "What? I fought that hard for THIS?"
					set {avgLevelQuote.%player%} to "Hehe... Look at me go!"
					set {goodLevelQuote.%player%} to "Ha! Looks like I've got even more comin' up!"
					set {maxLevelQuote.%player%} to "Wow... it's amazing how far I've come!"
					set {promotionQuote.%player%} to "Stand aside, everyone!"
					set {skillquote1.%player%} to "Caught ya napping!"
					set {skillquote2.%player%} to "Comin' through!"
					set {skillquote3.%player%} to "Time to shine!"
					set {skillquote4.%player%} to "Kaboom!"
					set {lowHPQuote.%player%} to "I've still got a little left in me..."
					set {healedQuote.%player%} to "Aww, thanks!"
					set {mediumHPQuote.%player%} to "This is nothing! Let me at 'em!"
					set {downedQuote.%player%} to "Ow, ow, ow... That one hurt... Could I get some help?"
					set {allyDownedQuote.%player%} to "Hey, it happens to the best of us, right?"
					set {enemyDefeated1.%player%} to "Gotcha!"
					set {enemyDefeated2.%player%} to "Down and out!"
					set {bossDefeated1.%player%} to "Nobody's a match for us!"
					set {bossDefeated2.%player%} to "That... was... awesome! Can we do that again?"
					set {deathQuote.%player%} to "I-I went a little... too hard... Sorry guys..."
					set {allyNeedHealing.%player%} to "That looks rough, you might want to get it healed."
					set {allyDeathQuote.%player%} to "Hey..! You can't go like that, what about the group?!"
					set {allyHardcoreDeathQuote.%player%} to "Oh gods, I... I can't believe this is happening..."
					set {allyEnemyDefeated1.%player%} to "Hey, not bad!"
					set {allyEnemyDefeated2.%player%} to "That was cool!"
					set {allyEnemyDefeated3.%player%} to "Keep it up!"
					set {allyHurtLarge1.%player%} to "Careful, these guys are tough!"
					set {allyHurtLarge2.%player%} to "Don't worry, I'll get 'em for you!"
					send "<run command:/cosmetics><light blue>Preset applied. Click here to return to main set-up"
				else:
					send "<light purple>Quote preset: Katarina"
					send "<light purple>Samples:"
					send "<light purple>Bad Level-up: ""What? I fought that hard for THIS?"""
					send "<light purple>Good Level-up: ""Ha! Looks like I've got even more comin' up!"""
					send "<light purple>Skill activation 1: ""Caught ya napping!"""
					send "<light purple>Skill activation 2: ""Kaboom!"""
					send "<light purple>Low HP warning: ""I've still got a little left in me..."""
					send "<run command:/cosmetics 5 10 1><light green>Apply preset"
					send "<run command:/cosmetics><light blue>Return to main set-up"
			if arg 2 is 11:
				if arg 3 is 1:
					set {badLevelQuote.%player%} to "This can't be it. It can't!"
					set {avgLevelQuote.%player%} to "Good! I'm getting stronger."
					set {goodLevelQuote.%player%} to "With strength like this, I'll be able to protect everyone!"
					set {maxLevelQuote.%player%} to "I must become stronger. Much stronger."
					set {promotionQuote.%player%} to "You don't get strong overnight. I've got to keep on inching forwards..."
					set {skillquote1.%player%} to "Whatever it takes!"
					set {skillquote2.%player%} to "This is MY fight!"
					set {skillquote3.%player%} to "Your villany ends here!"
					set {skillquote4.%player%} to "This is it!"
					set {lowHPQuote.%player%} to "So fatigued... But I can't just give up now..."
					set {healedQuote.%player%} to "Thank you! I'll do everything I can to make it up to you."
					set {mediumHPQuote.%player%} to "I have to keep fighting..."
					set {downedQuote.%player%} to "Grrgh... I'm still not strong enough... I need help..."
					set {allyDownedQuote.%player%} to "I won't let you sacrifice your life for mine. You're coming with us, no matter what!"
					set {enemyDefeated1.%player%} to "Victory!"
					set {enemyDefeated2.%player%} to "I will take my homeland back!"
					set {bossDefeated1.%player%} to "We've prevailed! I knew we could do it!"
					set {bossDefeated2.%player%} to "This is our land, not yours!"
					set {deathQuote.%player%} to "I... failed us all..."
					set {allyNeedHealing.%player%} to "You need to get healed, right now!"
					set {allyDeathQuote.%player%} to "..."
					set {allyHardcoreDeathQuote.%player%} to "Rrgh..! I wasn't strong enough to protect anyone..."
					set {allyEnemyDefeated1.%player%} to "I need to pay more attention to you!"
					set {allyEnemyDefeated2.%player%} to "There's a lot I can learn from you."
					set {allyEnemyDefeated3.%player%} to "If we keep on fighting together, there's no battle we can't win!"
					set {allyHurtLarge1.%player%} to "Don't overdo it!"
					set {allyHurtLarge2.%player%} to "I'm coming to help you, just hold on!"
					send "<run command:/cosmetics><light blue>Preset applied. Click here to return to main set-up"
				else:
					send "<light purple>Quote preset: Leif"
					send "<light purple>Samples:"
					send "<light purple>Bad Level-up: ""This can't be it. It can't!"""
					send "<light purple>Good Level-up: ""With strength like this, I'll be able to protect everyone!"""
					send "<light purple>Skill activation 1: ""This is MY fight!"""
					send "<light purple>Skill activation 2: ""Your villany ends here!"""
					send "<light purple>Low HP warning: ""So fatigued... But I can't just give up now..."""
					send "<run command:/cosmetics 5 11 1><light green>Apply preset"
					send "<run command:/cosmetics><light blue>Return to main set-up"
			if arg 2 is 12:
				if arg 3 is 1:
					set {badLevelQuote.%player%} to "..?"
					set {avgLevelQuote.%player%} to "..."
					set {goodLevelQuote.%player%} to ".!"
					set {maxLevelQuote.%player%} to "..."
					set {promotionQuote.%player%} to "..!!"
					set {skillquote1.%player%} to "..!"
					set {skillquote2.%player%} to "..."
					set {skillquote3.%player%} to "..!"
					set {skillquote4.%player%} to "..!!!"
					set {lowHPQuote.%player%} to "...!"
					set {healedQuote.%player%} to "..."
					set {mediumHPQuote.%player%} to "..."
					set {downedQuote.%player%} to "..!"
					set {allyDownedQuote.%player%} to "..!"
					set {enemyDefeated1.%player%} to "..."
					set {enemyDefeated2.%player%} to "..!"
					set {bossDefeated1.%player%} to "...!"
					set {bossDefeated2.%player%} to "..!"
					set {deathQuote.%player%} to "..?"
					set {allyNeedHealing.%player%} to "..."
					set {allyDeathQuote.%player%} to "..."
					set {allyHardcoreDeathQuote.%player%} to "..."
					set {allyEnemyDefeated1.%player%} to "..!"
					set {allyEnemyDefeated2.%player%} to "..?"
					set {allyEnemyDefeated3.%player%} to "..."
					set {allyHurtLarge1.%player%} to "..?"
					set {allyHurtLarge2.%player%} to "..?!"
				else:
					send "<light purple>Quote preset: Silent"
					send "<light purple>This option silences your quotes, replacing them with simple punctuation."
					send "<run command:/cosmetics 5 12 1><light green>Apply Preset"
					send "<run command:/cosmetics><light blue>Return to main set-up"

on chat:
	if {editName.%player%} is true:
		set the player's display name to the chat message
		set the player's tablist name to the chat message
		cancel event
		send "<yellow>Changed your character's name to %chat message%!"
		clear {editName.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editSkillQuote1.%player%} is true:
		set {skillquote1.%player%} to the chat message
		cancel event
		send "<yellow>Changed slot 1 to ""%chat message%""!"
		clear {editSkillQuote1.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editSkillQuote2.%player%} is true:
		set {skillquote2.%player%} to the chat message
		cancel event
		send "<yellow>Changed slot 2 to ""%chat message%""!"
		clear {editSkillQuote2.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editSkillQuote3.%player%} is true:
		set {skillquote3.%player%} to the chat message
		cancel event
		send "<yellow>Changed slot 3 to ""%chat message%""!"
		clear {editSkillQuote3.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editSkillQuote4.%player%} is true:
		set {skillquote4.%player%} to the chat message
		cancel event
		send "<yellow>Changed slot 4 to ""%chat message%""!"
		clear {editSkillQuote4.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editLevelQuote1.%player%} is true:
		set {badLevelQuote.%player%} to the chat message
		cancel event
		send "<light green>Changed your poor level-up quote to ""%chat message%""!"
		clear {editLevelQuote1.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editLevelQuote2.%player%} is true:
		set {avgLevelQuote.%player%} to the chat message
		cancel event
		send "<light green>Changed your average level-up quote to ""%chat message%""!"
		clear {editLevelQuote2.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editLevelQuote3.%player%} is true:
		set {goodLevelQuote.%player%} to the chat message
		cancel event
		send "<light green>Changed your good level-up quote to ""%chat message%""!"
		clear {editLevelQuote3.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editLevelQuote4.%player%} is true:
		set {maxLevelQuote.%player%} to the chat message
		cancel event
		send "<light green>Changed your max potential quote to ""%chat message%""!"
		clear {editLevelQuote4.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editLevelQuote5.%player%} is true:
		set {promotionQuote.%player%} to the chat message
		cancel event
		send "<light green>Changed your promotion quote to ""%chat message%""!"
		clear {editLevelQuote5.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote1.%player%} is true:
		set {lowHPQuote.%player%} to the chat message
		cancel event
		send "<light blue>Changed your low HP quote to ""%chat message%""!"
		clear {editCSQuote1.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote2.%player%} is true:
		set {mediumHPQuote.%player%} to the chat message
		cancel event
		send "<light blue>Changed your medium HP quote to ""%chat message%""!"
		clear {editCSQuote2.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote3.%player%} is true:
		set {downedQuote.%player%} to the chat message
		cancel event
		send "<light blue>Changed your downed quote to ""%chat message%""!"
		clear {editCSQuote3.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote4.%player%} is true:
		set {deathQuote.%player%} to the chat message
		cancel event
		send "<light blue>Changed your death quote to ""%chat message%""!"
		clear {editCSQuote4.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote5.%player%} is true:
		set {healedQuote.%player%} to the chat message
		cancel event
		send "<light blue>Changed your healed by ally quote to ""%chat message%""!"
		clear {editCSQuote5.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote6.%player%} is true:
		set {allyHurtLarge1.%player%} to the chat message
		cancel event
		send "<light blue>Changed your Ally hurt response to ""%chat message%""!"
		clear {editCSQuote6.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote7.%player%} is true:
		set {allyHurtLarge2.%player%} to the chat message
		cancel event
		send "<light blue>Changed your Ally hurt response to ""%chat message%""!"
		clear {editCSQuote7.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote8.%player%} is true:
		set {allyNeedHealing.%player%} to the chat message
		cancel event
		send "<light blue>Changed your Ally needs healing response to ""%chat message%""!"
		clear {editCSQuote8.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote9.%player%} is true:
		set {allyDeathQuote.%player%} to the chat message
		cancel event
		send "<light blue>Changed your Ally death response to ""%chat message%""!"
		clear {editCSQuote9.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote10.%player%} is true:
		set {allyHardcoreDeathQuote.%player%} to the chat message
		cancel event
		send "<light blue>Changed your Ally death (hardcore) response to ""%chat message%""!"
		clear {editCSQuote10.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote11.%player%} is true:
		set {allyDownedQuote.%player%} to the chat message
		cancel event
		send "<light blue>Changed your Ally revival response to ""%chat message%""!"
		clear {editCSQuote11.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote12.%player%} is true:
		set {enemyDefeated1.%player%} to the chat message
		cancel event
		send "<light blue>Changed your enemy defeated quote to ""%chat message%""!"
		clear {editCSQuote12.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote13.%player%} is true:
		set {enemyDefeated2.%player%} to the chat message
		cancel event
		send "<light blue>Changed your enemy defeated quote to ""%chat message%""!"
		clear {editCSQuote13.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote14.%player%} is true:
		set {bossDefeated1.%player%} to the chat message
		cancel event
		send "<light blue>Changed your boss defeated quote to ""%chat message%""!"
		clear {editCSQuote14.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote15.%player%} is true:
		set {bossDefeated2.%player%} to the chat message
		cancel event
		send "<light blue>Changed your boss defeated quote to ""%chat message%""!"
		clear {editCSQuote15.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote16.%player%} is true:
		set {allyEnemyDefeated1.%player%} to the chat message
		cancel event
		send "<light blue>Changed your ally victory response to ""%chat message%""!"
		clear {editCSQuote16.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote17.%player%} is true:
		set {allyEnemyDefeated2.%player%} to the chat message
		cancel event
		send "<light blue>Changed your ally victory response to ""%chat message%""!"
		clear {editCSQuote17.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
	else if {editCSQuote18.%player%} is true:
		set {allyEnemyDefeated3.%player%} to the chat message
		cancel event
		send "<light blue>Changed your ally victory response to ""%chat message%""!"
		clear {editCSQuote18.%player%}
		send "<run command:/cosmetics><light blue>Click here to return to the main set-up menu."
		
#MARKER - Character Info
		
command /cstats [<offlineplayer=%player%>] [<number=1>]:
	description: Check your or someone else's classes statistics.
	usage: /cstats (player) (page)
	aliases: /cinfo, /c, /class, /seestats
	executable by: players, console
	trigger:
		if {class.%arg 1%} is not set:
			send "<red>Could not find classes data for that player. Please check your spelling and try again. The player may also have disabled classes for their character."
		else:
			send "<gold><bold>%arg 1%: Level %{lvl.%arg 1%}% %{class.%arg 1%}%"
			if arg 2 is 1:
				#Calculate BST
				set {_bstcap.%arg 1%} to ({strcap.%arg 1%} + {defcap.%arg 1%} + {sklcap.%arg 1%} + {spdcap.%arg 1%} + {rescap.%arg 1%} + {hpcap.%arg 1%})
				set {bst.%arg 1%} to ({str.%arg 1%} + {def.%arg 1%} + {skl.%arg 1%} + {spd.%arg 1%} + {res.%arg 1%} + {hp.%arg 1%})
				#HP Readout
				if {hp.%arg 1%} is equal to {hpcap.%arg 1%}:
					send "<yellow><bold>Max HP: %{hp.%arg 1%}% + %{hpbuff.%arg 1%}% | Cap: %{hpcap.%arg 1%}% | Growth Rate: %{hpgrowth.%arg 1%}%"
				else:
					send "Max HP: %{hp.%arg 1%}% + %{hpbuff.%arg 1%}% | Cap: %{hpcap.%arg 1%}% | Growth Rate: %{hpgrowth.%arg 1%}%"
				#STR Readout
				if {str.%arg 1%} is equal to {strcap.%arg 1%}:
					send "<yellow><bold>Strength: %{str.%arg 1%}% + %{strbuff.%arg 1%}% | Cap: %{strcap.%arg 1%}% | Growth Rate: %{strgrowth.%arg 1%}%"
				else:
					send "Strength: %{str.%arg 1%}% + %{strbuff.%arg 1%}% | Cap: %{strcap.%arg 1%}% | Growth Rate: %{strgrowth.%arg 1%}%"
				#DEF Readout
				if {def.%arg 1%} is equal to {defcap.%arg 1%}:
					send "<yellow><bold>Defense: %{def.%arg 1%}% + %{defbuff.%arg 1%}% | Cap: %{defcap.%arg 1%}% | Growth Rate: %{defgrowth.%arg 1%}%"
				else:
					send "Defense: %{def.%arg 1%}% + %{defbuff.%arg 1%}% | Cap: %{defcap.%arg 1%}% | Growth Rate: %{defgrowth.%arg 1%}%"
				#SKL Readout
				if {skl.%arg 1%} is equal to {sklcap.%arg 1%}:
					send "<yellow><bold>Skill: %{skl.%arg 1%}% + %{sklbuff.%arg 1%}% | Cap: %{sklcap.%arg 1%}% | Growth Rate: %{sklgrowth.%arg 1%}%"
				else:
					send "Skill: %{skl.%arg 1%}% + %{sklbuff.%arg 1%}% | Cap: %{sklcap.%arg 1%}% | Growth Rate: %{sklgrowth.%arg 1%}%"
				#SPD Readout
				if {spd.%arg 1%} is equal to {spdcap.%arg 1%}:
					send "<yellow><bold>Speed: %{spd.%arg 1%}% + %{spdbuff.%arg 1%}% | Cap: %{spdcap.%arg 1%}% | Growth Rate: %{spdgrowth.%arg 1%}%"
				else:
					send "Speed: %{spd.%arg 1%}% + %{spdbuff.%arg 1%}% | Cap: %{spdcap.%arg 1%}% | Growth Rate: %{spdgrowth.%arg 1%}%"
				#MAG Readout
				if {res.%arg 1%} is equal to {rescap.%arg 1%}:
					send "<yellow><bold>Magic: %{res.%arg 1%}% + %{resbuff.%arg 1%}% | Cap: %{rescap.%arg 1%}% | Growth Rate: %{maggrowth.%arg 1%}%"
				else:
					send "Magic: %{res.%arg 1%}% + %{resbuff.%arg 1%}% | Cap: %{rescap.%arg 1%}% | Growth Rate: %{maggrowth.%arg 1%}%"
				send "BST: %{bst.%arg 1%}% (Max: %{_bstcap.%arg 1%}%)"
				send "<run command:/cstats %arg 1% 2><gold>Next Page"
			else if arg 2 is 2:
				if {perdiff.%arg 1%} is 0:
					set {_diff} to "<green>Relaxed"
				else if {perdiff.%arg 1%} is 1:
					set {_diff} to "<light green>Easy"
				else if {perdiff.%arg 1%} is 2:
					set {_diff} to "Normal"
				else if {perdiff.%arg 1%} is 3:
					set {_diff} to "<light red>Hard"
				else if {perdiff.%arg 1%} is 4:
					set {_diff} to "<light purple>Lunatic"
				else if {perdiff.%arg 1%} is 5:
					set {_diff} to "<purple><bold>Infernal"
				else if {perdiff.%arg 1%} is 6:
					set {_diff} to "<light yellow>Thracian"
				else if {perdiff.%arg 1%} is 7:
					set {_diff} to "<light yellow><bold>Lunatic (Thracian)"
				else if {perdiff.%arg 1%} is 8:
					set {_diff} to "<gold><bold>Infernal (Thracian)"
				send "Difficulty Modifier: %{_diff}%"
				send "Times Reclassed: %{reclassed.%arg 1%}%"
				send "Blocks Mined: %{blocksmined.%arg 1%}%"
				send "Tools Broken: %{toolbreaktally.%arg 1%}%"
				send "Fall Damage Taken: %{slfalltotal.%arg 1%}%"
				send "Promotion Tier: %{promoted.%arg 1%}%"
				send "<run command:/cstats %arg 1% 3><gold>Next Page"
				send "<run command:/cstats %arg 1% 1><gold>Previous Page"
			else if arg 2 is 3:
				send "<bold>%arg 1%'s perks:"
				send "Perks Unlocked: %{skillstotal.%arg 1%}%"
				send "Perk Slot 1: %{skillslot1.%arg 1%}%"
				send "Perk Slot 2: %{skillslot2.%arg 1%}%"
				send "Perk Slot 3: %{skillslot3.%arg 1%}%"
				send "Perk Slot 4: %{skillslot4.%arg 1%}%"
				send "Perk Slot 5: %{skillslot5.%arg 1%}%"
				send "<run command:/cstats %arg 1% 4><gold>Next Page"
				send "<run command:/cstats %arg 1% 2><gold>Previous Page"
			else if arg 2 is 4:
				if {party.%arg 1%} is not set:
					send "<bold>%arg 1% is not a member of a group."
				else:
					loop {%{party.%player%}%.members::*}:
						add 1 to {_members}
					if {%{party.%arg 1%}%.needInvite} is 1:
						set {_nI} to "True"
					else:
						set {_nI} to "False"
					send "<bold>%arg 1%'s Group:"
					send "Group: %{party.%arg 1%}%"
					send "Members: %{_members}%"
					send "Invite Needed: %{_nI}%"
				send "<run command:/cstats %arg 1% 5><gold>Next Page"
				send "<run command:/cstats %arg 1% 3><gold>Previous Page"
			else if arg 2 is 5:
				send "<gold><bold>%arg 1%'s Weapon Ranks"
				send "Swords: %{weapongrade.%arg 1%::swords}% | Points: %{weaponrank.%arg 1%::swords}%"
				send "Lances: %{weapongrade.%arg 1%::lances}% | Points: %{weaponrank.%arg 1%::lances}%"
				send "Axes: %{weapongrade.%arg 1%::axes}% | Points: %{weaponrank.%arg 1%::axes}%"
				send "Bows: %{weapongrade.%arg 1%::bows}% | Points: %{weaponrank.%arg 1%::bows}%"
				send "Magic: %{weapongrade.%arg 1%::magic}% | Points: %{weaponrank.%arg 1%::magic}%"
				send "Staves: %{weapongrade.%arg 1%::staves}% | Points: %{weaponrank.%arg 1%::staves}%"
				send "<run command:/cstats %arg 1% 6><gold>Next Page"
				send "<run command:/cstats %arg 1% 4><gold>Previous Page"
			else if arg 2 is 6:
				send "<gold><bold>%arg 1%'s Misc. Records"
				send "Hours played: %{hoursplayed.%arg 1%}%"
				send "Combat Victories: %{kills.%arg 1%}%"
				send "Deaths: %{deaths.%arg 1%}%"
				send "Most Damage Dealt in One Hit: %{highestdamage.%arg 1%}%"
				send "Most Damage Taken in One Hit: %{highestsuffered.%arg 1%}%"
				send "<run command:/cstats %arg 1% 5><gold>Previous Page"
				
				
#MARKER - Promotion Items


on right-click with nether star:
	if {lvl.%player%} is more than 9:
		if the name of the event-item is "<gold><bold>Journey's Crest":
			send "<gold>You may now promote into the following classes. Please click on one to learn about that class. Click the button that appears beneath the class's information to promote."
			play sound "entity.player.levelup" with volume 2 and pitch 2 at player for player
			spawn firework at the player
			wait 1 second
			set {promotionready.%player%} to 1
			if {promoted.%player%} is 0:
				delete player's held item
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Knight><light blue>Knight"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Cavalier><light blue>Cavalier"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Bladesman><light blue>Bladesman"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Fighter><light blue>Fighter"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Mercenary><light blue>Mercenary"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Cleric><light blue>Cleric"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Mage><light blue>Mage"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Archer><light blue>Archer"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Gunslinger><light blue>Gunslinger"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Devil Hunter><light blue>Devil Hunter"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Strategist><light blue>Strategist"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Survivor><light blue>Survivor"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 1 at player for player
				send "<run command:/class help Dragonborn><light blue>Dragonborn"
			else:
				send "<red>You must be a Journeyman to use a Journey's Crest."
		else if the name of the event-item is "<gold><bold>Warrior's Proof":
			if {promoted.%player%} is 1:
				delete player's held item
				set {promotionready.%player%} to 1
				send "<run command:/class promote %{class.%player%}%1><gold>You may now promote into a higher-tier version of your current class. Please click here to confirm promotion."
			else if {promoted.%player%} is 2:
				delete player's held item
				set {promotionready.%player%} to 1
				send "<run command:/class promote %{class.%player%}%><gold>You may now promote into a higher-tier version of your current class. Please click here to confirm promotion."
			else if {promoted.%player%} is more than 2:
				delete player's held item
				set {promotionready.%player%} to 1
				if {class.%player%} is "Junior Lord":
					send "<run command:/class promote Junior Lord><gold>You may now promote into a higher-tier version of your current class. Please click here to confirm promotion."
				else:
					send "<run command:/class promote Overclass><gold>You may now Overclass to increase all stat caps by 15. Click here to begin Overclassing."				
			else:
				send "<red>You must be promoted to use a Warrior's Proof."
		else if the name of the event-item is "<gold><bold>Trainee's Enrollment":
			delete player's held item
			set {promotionready.%player%} to 1
			send "<gold>You may now reclass into a Journeyman. Optionally, you may reallocate your stat points. Click YES if you would like to reallocate your stat points. Click NO to keep your allocations."
			send "<run command:/charsetup 0 1><green>YES (This will reset your stats.)"
			send "<run command:/class promote Journeyman_Reclass><red>NO (You will retain your stats.)"
	else:
		send "<red>You lack enough experience to promote. You must be at least level 10 to promote."
				
				
#MARKER - Promotion Handler


command /class <text> [<text="Journeyman">]:
	description: Learn about the available classes.
	usage: /class help
	executable by: players
	trigger:
		send "<gold><bold>~~~~~~Classes~~~~~~"
		if arg 1 is "help":
			#send "<gold>Current Class: %{class.%player%}%"
			if arg 2 is "Journeyman":
				send "Journeymen are your average traveller, skilled in all manners of combat and survival. Highly versatile and able to adapt to any situation. However, this also keeps them from excelling in any one area in particular."
				send "Class-Specific Skill: <red>None"
				send "Maximum Health: <yellow>Average"
				send "Movement Speed: <yellow>Average"
				send "Damage Resistance: <yellow>Average"
				send "Attack Power: <yellow>Average"
				send "Skill: <yellow>Average"
				set {promotiontype.%player%} to "Journeyman"
			else if arg 2 is "Knight":
				send "Knights are strong and tough. Able to absorb the mightiest of blows, Knights are perfect for defence. Their poor speed and weak retaliation keeps them off the front lines. Unable to ride mounts."
				send "Class-Specific Skill: <light blue>Unbreakable: You cannot be debuffed."
				send "Maximum Health: <green>Exceptional"
				send "Movement Speed: <red>Poor"
				send "Damage Resistance: <green>Exceptional"
				send "Attack Power: <light red>Below-Average"
				send "Skill: <light red>Below-Average"
				set {promotiontype.%player%} to "Knight"
			else if arg 2 is "Cavalier":
				send "Cavaliers are mounted horsemen with solid fundamentals of swordplay. They charge fiercely into battle upon a trusted steed. Not quite as deadly if their mount is slain."
				send "Class-Specific Skill: <light blue>Taming Mastery: All animals you tame recieve permanent stat increases."
				send "Maximum Health: <yellow>Average"
				send "Movement Speed: <yellow>Average"
				send "Damage Resistance: <yellow>Average"
				send "Attack Power: <yellow>Average"
				send "Skill: <light green>Above-Average"
				set {promotiontype.%player%} to "Cavalier"
			else if arg 2 is "Bladesman":
				send "Bladesmen have devoted their lives to the sword, delivering staggeringly fast attacks with incredible skill. However, they are incredibly fragile to physical attacks."
				send "Class-Specific Skill: <light blue>Light Feet: Dodge rolling costs nothing."
				send "Maximum Health: <light red>Below-Average"
				send "Movement Speed: <green>Exceptional"
				send "Damage Resistance: <light red>Below-Average"
				send "Attack Power: <light red>Below-Average"
				send "Skill: <green>Exceptional"
				set {promotiontype.%player%} to "Bladesman"
			else if arg 2 is "Fighter":
				send "Axemen are incredibly handy with an axe. They deliver devastating blows that can smash even the strongest of armour. However, they can be somewhat sluggish and clumsy."
				send "Class-Specific Skill: <light blue>Gamble: Grants STR +60, but attacks can miss."
				send "Maximum Health: <light green>Above-Average"
				send "Movement Speed: <light red>Below-Average"
				send "Damage Resistance: <yellow>Average"
				send "Attack Power: <light green>Above-Average"
				send "Skill: <red>Poor"
				set {promotiontype.%player%} to "Fighter"
			else if arg 2 is "Mercenary":
				send "Mercenaries are the ascended form of Journeymen. Still sharp as ever in all types of combat, the Mercenary also gains slightly more skill and physical bulk."
				send "Class-Specific Skill: <light blue>Awakening: A surge of energy increases all stats in a pinch."
				send "Maximum Health: <green>Above-Average"
				send "Movement Speed: <yellow>Average"
				send "Damage Resistance: <yellow>Average"
				send "Attack Power: <yellow>Average"
				send "Skill: <light green>Above-Average"
				set {promotiontype.%player%} to "Mercenary"
			else if arg 2 is "Archer":
				send "Archers specialize in ranged combat. Their above average defences lend themselves well to bow duels, but are weak in close-quarters combat."
				send "Class-Specific Skill: <light blue>Quick Draw: Arrows fire instantly, but travel less distance."
				send "Maximum Health: <yellow>Average"
				send "Movement Speed: <yellow>Average"
				send "Damage Resistance: <light green>Above-Average"
				send "Attack Power: <light red>Below-Average"
				send "Skill: <light red>Below-Average"
				set {promotiontype.%player%} to "Archer"
			else if arg 2 is "Strategist":
				send "Strategists are highly versatile fighters familiar with all manners of combat. They can wield any weapon necessary to secure victory for their comrades."
				send "Class-Specific Skill: <light blue>Rally Strength: Right-Click an ally to grant them Strength 1 for 60 seconds."
				send "Maximum Health: <yellow>Average"
				send "Movement Speed: <yellow>Average"
				send "Damage Resistance: <yellow>Average"
				send "Attack Power: <yellow>Average"
				send "Skill: <yellow>Average"
				set {promotiontype.%player%} to "Strategist"
			else if arg 2 is "Gunslinger":
				send "Gunslingers are fast-footed tricksters posessing superb skills with all manners of firearms. Their speed and skill make them hard to pin down, even in close quarters."
				send "Class-Specific Skill: <light blue>Fast Fingers: Halves the reload time of all firearms."
				send "Maximum Health: <yellow>Average"
				send "Movement Speed: <light green>Above-Average"
				send "Damage Resistance: <light-red>Below-Average"
				send "Attack Power: <yellow>Average"
				send "Skill: <light green>Above-Average"
				set {promotiontype.%player%} to "Gunslinger"
			else if arg 2 is "Devil Hunter":
				send "Devil Hunters are high-flying and stylish masters of both ranged and melee combat. While their defences are rather lacking, they make up for it with lightning-fast and stylish combo attacks."
				send "Class-Specific Skill: <light blue>Air Hike: Perform wall jumps by left-clicking a wall while in contact with it."
				send "Maximum Health: <red>Poor"
				send "Movement Speed: <green>Exceptional"
				send "Damage Resistance: <red>Poor"
				send "Attack Power: <light red>Below-Average"
				send "Skill: <green>Exceptional"
				set {promotiontype.%player%} to "Devil Hunter"
			else if arg 2 is "Dragonborn":
				send "A near-extinct race with the blood of dragons. They possess power beyond that of normal humans, but can only use it for a limited time."
				send "Class-Specific Skill: <light blue>Hoard: Gain bonus money equal to your MAG at the start of every new day."
				send "Maximum Health: <yellow>Average"
				send "Movement Speed: <yellow>Average"
				send "Damage Resistance: <yellow>Average"
				send "Attack Power: <green>Exceptional"
				send "Skill: <yellow>Average"
				set {promotiontype.%player%} to "Dragonborn"
			else if arg 2 is "Survivor":
				send "Survivors are focused only on their own well-being. Foregoing any more combat talent than necessary, they focus on craftsmanship and retriving resources quickly and efficiently."
				send "Class-Specific Skill: <light blue>Scavenger: Ores have a chance to drop extra ore pieces when broken."
				send "Maximum Health: <yellow>Average"
				send "Movement Speed: <yellow>Average"
				send "Damage Resistance: <yellow>Average"
				send "Attack Power: <yellow>Average"
				send "Skill: <yellow>Average"
				set {promotiontype.%player%} to "Survivor"
			else if arg 2 is "Cleric":
				send "Clerics are helpful healers that wield a variety of staves. While they may not be able to use typical weapons, the staves clerics carry can heal your wounded. Take one with you, and you'll be very glad you did."
				send "Class-Specific Skill: <light blue>Live to Serve: When healing a player, you heal the same amount of health as your patient."
				send "Maximum Health: <green>Above-Average"
				send "Movement Speed: <light red>Below-Average"
				send "Damage Resistance: <light-red>Below-Average"
				send "Attack Power: <red>Poor"
				send "Skill: <light red>Below-Average"
				send "Magic: <green>Exceptional"
				set {promotiontype.%player%} to "Cleric"
			else if arg 2 is "Mage":
				send "Mages are spellcasters that can wield a large variety of powerful magics. They can combine multiple elements to create unique effects on the world."
				send "Class-Specific Skill: <light blue>Magic Ward: Halves cooldown of any magical abilities."
				send "Maximum Health: <green>Above-Average"
				send "Movement Speed: <yellow>Average"
				send "Damage Resistance: <light-red>Below-Average"
				send "Phyiscal Power: <red>Poor"
				send "Skill: <yellow>Average"
				send "Magic: <green>Exceptional"
				set {promotiontype.%player%} to "Mage"
			if {promotionready.%player%} is 1:
				send "<run command:/class promote %{promotiontype.%player%}%><gold>Promote to this class? (Click here to confirm promotion)"
		else if arg 1 is "reset":
			send "<gold><bold>You have two options for resetting data:"
			set {promotionready.%player%} to 1
			send "<run command:/class promote Reset>- Reset class stats to their defaults, but keep personal records."
			send "<run command:/class hardreset>- Wipe all personal classes data, including personal records."
			send "Please click your selection."
		else if arg 1 is "hardreset":
			send "<gold>Cleared all class-related data for your current character."
			set the player's level to 1
			set {lvl.%player%} to 1
			set {class.%player%} to "Journeyman"
			set {str.%player%} to 0
			set {def.%player%} to 0
			set {skl.%player%} to 0
			set {spd.%player%} to 0
			set {res.%player%} to 0
			set {hp.%player%} to 10
			set {skl.%player%} to 10
			set {strcap.%player%} to 15
			set {defcap.%player%} to 15
			set {hpcap.%player%} to 40
			set {sklcap.%player%} to 30
			set {spdcap.%player%} to 15
			set {rescap.%player%} to 15
			set {lvlcap.%player%} to 30
			set {promoted.%player%} to 0
			set {skillstotal.%player%} to 0
			set {reclasses.%player%} to 0
			set {deaths.%player%} to 0
			set {lvl.%player%} to 1		
		else if arg 1 is "promote":
			if {promotionready.%player%} is 1:
				send "<gold>Promoting! You may now close the chat."
				set {promotionready.%player%} to 0
				strike lightning effect at the player
				wait 1 second
				strike lightning effect at the player
				wait 0.45 second
				strike lightning effect at the player
				wait 1 second
				set {_pitch} to 0.6
				set {_oldstr.%player%} to {str.%player%}
				set {_olddef.%player%} to {def.%player%}
				set {_oldhp.%player%} to {hp.%player%}
				set {_oldskl.%player%} to {skl.%player%}
				set {_oldspd.%player%} to {spd.%player%}
				set {_oldres.%player%} to {res.%player%}
				loop 10 times:
					play mob spawner flames at the player
					play magical critical hit at the player
					play smoke at the player
					play sound "entity.experience_orb.pickup" with volume 2 and pitch {_pitch} at player for player
					wait 0.3 seconds
					spawn firework at player
					add .2 to {_pitch}
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 2 at player for player
				if arg 2 is "Journeyman_Reclass":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 30
					set {strgrowth.%player%} to {pts_STR.%player%} + 30
					set {defgrowth.%player%} to {pts_DEF.%player%} + 30
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 30
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 30
					set {maggrowth.%player%} to {pts_MAG.%player%} + 30
					make player execute command "/grantskill 0 Paragon"
					set {class.%player%} to "Journeyman"
					add 1 to {reclassed.%player%}
					send "<gold><bold>Promoted to a Journeyman!"
				if arg 2 is "Journeyman":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 30
					set {strgrowth.%player%} to {pts_STR.%player%} + 30
					set {defgrowth.%player%} to {pts_DEF.%player%} + 30
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 30
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 30
					set {maggrowth.%player%} to {pts_MAG.%player%} + 30
					set the player's level to 1
					set {lvl.%player%} to 1
					make player execute command "/qstart"
					set {class.%player%} to "Journeyman"
					add 1 to {reclassed.%player%}
					send "<gold><bold>Promoted to a Journeyman!"
				else if arg 2 is "Knight":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 50
					set {strgrowth.%player%} to {pts_STR.%player%} + 15
					set {defgrowth.%player%} to {pts_DEF.%player%} + 60
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 15
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 10
					set {maggrowth.%player%} to {pts_MAG.%player%} + 5
					add 25 to {hpcap.%player%}
					add 7 to {strcap.%player%}
					add 30 to {defcap.%player%}
					add 7 to {sklcap.%player%}
					add 5 to {spdcap.%player%}
					add 2 to {rescap.%player%}
					add 4 to {str.%player%}
					add 8 to {def.%player%}
					add 12 to {hp.%player%}
					add 2 to {skl.%player%}
					add 4 to {spd.%player%}
					add 2 to {res.%player%}
					set {class.%player%} to "Knight"
					make player execute command "/grantskill 0 Unbreakable"
					send "<gold><bold>Promoted to a Knight!"
				else if arg 2 is "Cavalier":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 35
					set {strgrowth.%player%} to {pts_STR.%player%} + 25
					set {defgrowth.%player%} to {pts_DEF.%player%} + 25
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 25
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 20
					set {maggrowth.%player%} to {pts_MAG.%player%} + 25
					add 17 to {hpcap.%player%}
					add 12 to {strcap.%player%}
					add 10 to {defcap.%player%}
					add 15 to {sklcap.%player%}
					add 10 to {spdcap.%player%}
					add 12 to {rescap.%player%}
					add 6 to {str.%player%}
					add 4 to {def.%player%}
					add 4 to {spd.%player%}
					add 4 to {res.%player%}
					add 4 to {hp.%player%}
					add 6 to {skl.%player%}
					make player execute command "/grantskill 0 Mount"
					set {class.%player%} to "Cavalier"
					send "<gold><bold>Promoted to a Cavalier!"
				else if arg 2 is "Bladesman":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 15
					set {strgrowth.%player%} to {pts_STR.%player%} + 25
					set {defgrowth.%player%} to {pts_DEF.%player%} + 10
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 40
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 50
					set {maggrowth.%player%} to {pts_MAG.%player%} + 10
					add 7 to {hpcap.%player%}
					add 12 to {strcap.%player%}
					add 5 to {defcap.%player%}
					add 20 to {sklcap.%player%}
					add 25 to {spdcap.%player%}
					add 5 to {rescap.%player%}
					add 2 to {str.%player%}
					add 2 to {def.%player%}
					add 8 to {spd.%player%}
					add 2 to {res.%player%}
					add 4 to {hp.%player%}
					add 8 to {skl.%player%}
					make player execute command "/grantskill 0 Light Feet"
					set {class.%player%} to "Bladesman"
					send "<gold><bold>Promoted to a Bladesman!"
				else if arg 2 is "Fighter":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 45
					set {strgrowth.%player%} to {pts_STR.%player%} + 40
					set {defgrowth.%player%} to {pts_DEF.%player%} + 30
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 15
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 15
					set {maggrowth.%player%} to {pts_MAG.%player%} + 5
					add 22 to {hpcap.%player%}
					add 20 to {strcap.%player%}
					add 15 to {defcap.%player%}
					add 7 to {sklcap.%player%}
					add 7 to {spdcap.%player%}
					add 2 to {rescap.%player%}
					add 9 to {str.%player%}
					add 4 to {def.%player%}
					add 4 to {spd.%player%}
					add 4 to {res.%player%}
					add 8 to {hp.%player%}
					add 6 to {skl.%player%}
					set {class.%player%} to "Fighter"
					make player execute command "/grantskill 0 Gamble"
					send "<gold><bold>Promoted to an Fighter!"
				else if arg 2 is "Mercenary":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 25
					set {strgrowth.%player%} to {pts_STR.%player%} + 25
					set {defgrowth.%player%} to {pts_DEF.%player%} + 25
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 25
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 25
					set {maggrowth.%player%} to {pts_MAG.%player%} + 25
					add 12 to {hpcap.%player%}
					add 12 to {strcap.%player%}
					add 12 to {defcap.%player%}
					add 12 to {sklcap.%player%}
					add 12 to {spdcap.%player%}
					add 12 to {rescap.%player%}
					add 5 to {str.%player%}
					add 5 to {def.%player%}
					add 5 to {spd.%player%}
					add 5 to {res.%player%}
					add 5 to {hp.%player%}
					add 5 to {skl.%player%}
					set {class.%player%} to "Mercenary"
					make player execute command "/grantskill 0 Awakening"
					send "<gold><bold>Promoted to a Mercenary!"
				else if arg 2 is "Cleric":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 40
					set {strgrowth.%player%} to {pts_STR.%player%} + 15
					set {defgrowth.%player%} to {pts_DEF.%player%} + 20
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 15
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 15
					set {maggrowth.%player%} to {pts_MAG.%player%} + 45
					add 20 to {hpcap.%player%}
					add 7 to {strcap.%player%}
					add 10 to {defcap.%player%}
					add 7 to {sklcap.%player%}
					add 7 to {spdcap.%player%}
					add 22 to {rescap.%player%}
					add 4 to {str.%player%}
					add 4 to {def.%player%}
					add 4 to {spd.%player%}
					add 8 to {res.%player%}
					add 4 to {hp.%player%}
					add 4 to {skl.%player%}
					set {class.%player%} to "Cleric"
					make player execute command "/grantskill 0 Live to Serve"
					send "<gold><bold>Promoted to a Cleric!"
				else if arg 2 is "Mage":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 35
					set {strgrowth.%player%} to {pts_STR.%player%} + 5
					set {defgrowth.%player%} to {pts_DEF.%player%} + 15
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 25
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 20
					set {maggrowth.%player%} to {pts_MAG.%player%} + 50
					add 17 to {hpcap.%player%}
					add 3 to {strcap.%player%}
					add 7 to {defcap.%player%}
					add 12 to {sklcap.%player%}
					add 10 to {spdcap.%player%}
					add 25 to {rescap.%player%}
					add 3 to {str.%player%}
					add 3 to {def.%player%}
					add 4 to {spd.%player%}
					add 8 to {res.%player%}
					add 4 to {hp.%player%}
					add 3 to {skl.%player%}
					set {class.%player%} to "Mage"
					make player execute command "/grantskill 0 Magic Ward"
					drop 1 blaze rod named "<yellow><bold>Magic Wand" at the player
					send "<gold><bold>Promoted to a Mage!"
				else if arg 2 is "Archer":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 35
					set {strgrowth.%player%} to {pts_STR.%player%} + 35
					set {defgrowth.%player%} to {pts_DEF.%player%} + 25
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 25
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 20
					set {maggrowth.%player%} to {pts_MAG.%player%} + 10
					add 17 to {hpcap.%player%}
					add 17 to {strcap.%player%}
					add 12 to {defcap.%player%}
					add 12 to {sklcap.%player%}
					add 10 to {spdcap.%player%}
					add 5 to {rescap.%player%}
					add 5 to {str.%player%}
					add 4 to {def.%player%}
					add 4 to {spd.%player%}
					add 6 to {res.%player%}
					add 3 to {hp.%player%}
					add 3 to {skl.%player%}
					set {class.%player%} to "Archer"
					make player execute command "/grantskill 0 Quick Draw"
					send "<gold><bold>Promoted to an Archer!"
				else if arg 2 is "Strategist":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 30
					set {strgrowth.%player%} to {pts_STR.%player%} + 20
					set {defgrowth.%player%} to {pts_DEF.%player%} + 30
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 20
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 20
					set {maggrowth.%player%} to {pts_MAG.%player%} + 30
					add 15 to {hpcap.%player%}
					add 10 to {strcap.%player%}
					add 15 to {defcap.%player%}
					add 10 to {sklcap.%player%}
					add 10 to {spdcap.%player%}
					add 15 to {rescap.%player%}
					add 2 to {str.%player%}
					add 3 to {def.%player%}
					add 2 to {spd.%player%}
					add 4 to {res.%player%}
					add 4 to {hp.%player%}
					add 3 to {skl.%player%}
					set {class.%player%} to "Strategist"
					make player execute command "/grantskill 0 Rally Strength"
					send "<gold><bold>Promoted to a Strategist!"
				else if arg 2 is "Gunslinger":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 30
					set {strgrowth.%player%} to {pts_STR.%player%} + 25
					set {defgrowth.%player%} to {pts_DEF.%player%} + 15
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 30
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 35
					set {maggrowth.%player%} to {pts_MAG.%player%} + 15
					add 15 to {hpcap.%player%}
					add 12 to {strcap.%player%}
					add 7 to {defcap.%player%}
					add 15 to {sklcap.%player%}
					add 17 to {spdcap.%player%}
					add 12 to {rescap.%player%}
					add 4 to {str.%player%}
					add 4 to {def.%player%}
					add 6 to {spd.%player%}
					add 4 to {res.%player%}
					add 6 to {hp.%player%}
					add 4 to {skl.%player%}
					set {class.%player%} to "Gunslinger"
					make player execute command "/grantskill 0 Fast Fingers"
					send "<gold><bold>Promoted to a Gunslinger!"
				else if arg 2 is "Devil Hunter":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 20
					set {strgrowth.%player%} to {pts_STR.%player%} + 30
					set {defgrowth.%player%} to {pts_DEF.%player%} + 10
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 50
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 30
					set {maggrowth.%player%} to {pts_MAG.%player%} + 10
					add 10 to {hpcap.%player%}
					add 15 to {strcap.%player%}
					add 5 to {defcap.%player%}
					add 25 to {sklcap.%player%}
					add 15 to {spdcap.%player%}
					add 5 to {rescap.%player%}
					add 3 to {str.%player%}
					add 7 to {spd.%player%}
					add 7 to {skl.%player%}
					add 1 to {def.%player%}
					add 1 to {res.%player%}
					add 2 to {hp.%player%}
					set {class.%player%} to "Devil Hunter"
					make player execute command "/grantskill 0 Combo System"
					make player execute command "/grantskill 0 Air Hike"
					send "<gold><bold>Promoted to a Devil Hunter!"
				else if arg 2 is "Dragonborn":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 35
					set {strgrowth.%player%} to {pts_STR.%player%} + 10
					set {defgrowth.%player%} to {pts_DEF.%player%} + 35
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 20
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 15
					set {maggrowth.%player%} to {pts_MAG.%player%} + 35
					add 17 to {hpcap.%player%}
					add 5 to {strcap.%player%}
					add 17 to {defcap.%player%}
					add 10 to {sklcap.%player%}
					add 7 to {spdcap.%player%}
					add 17 to {rescap.%player%}
					add 6 to {str.%player%}
					add 6 to {def.%player%}
					add 6 to {spd.%player%}
					add 6 to {res.%player%}
					add 6 to {hp.%player%}
					add 6 to {skl.%player%}
					set {class.%player%} to "Dragonborn"
					make player execute command "/grantskill 0 Hoard"
					send "<gold><bold>Promoted to a Dragonborn!"
				else if arg 2 is "Survivor":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 20
					set {strgrowth.%player%} to {pts_STR.%player%} + 20
					set {defgrowth.%player%} to {pts_DEF.%player%} + 20
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 20
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 20
					set {maggrowth.%player%} to {pts_MAG.%player%} + 20
					add 10 to {hpcap.%player%}
					add 10 to {strcap.%player%}
					add 10 to {defcap.%player%}
					add 10 to {sklcap.%player%}
					add 10 to {spdcap.%player%}
					add 10 to {rescap.%player%}
					add 2 to {str.%player%}
					add 2 to {def.%player%}
					add 2 to {spd.%player%}
					add 2 to {res.%player%}
					add 2 to {hp.%player%}
					add 2 to {skl.%player%}
					set {class.%player%} to "Survivor"
					make player execute command "/grantskill 0 Scavenger"
					send "<gold><bold>Promoted to a Survivor!"
				else if arg 2 is "Survivor1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 15
					set {strgrowth.%player%} to {pts_STR.%player%} + 15
					set {defgrowth.%player%} to {pts_DEF.%player%} + 15
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 15
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 15
					set {maggrowth.%player%} to {pts_MAG.%player%} + 15
					add 7 to {hpcap.%player%}
					add 7 to {strcap.%player%}
					add 7 to {defcap.%player%}
					add 7 to {sklcap.%player%}
					add 7 to {spdcap.%player%}
					add 7 to {rescap.%player%}
					add 2 to {str.%player%}
					add 2 to {def.%player%}
					add 2 to {spd.%player%}
					add 2 to {res.%player%}
					add 2 to {hp.%player%}
					add 2 to {skl.%player%}
					set {class.%player%} to "Builder"
					make player execute command "/grantskill 0 Efficiency"
					send "<gold><bold>Promoted to a Builder!"
				else if arg 2 is "Archer1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 30
					set {strgrowth.%player%} to {pts_STR.%player%} + 35
					set {defgrowth.%player%} to {pts_DEF.%player%} + 25
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 25
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 15
					set {maggrowth.%player%} to {pts_MAG.%player%} + 10
					add 15 to {hpcap.%player%}
					add 17 to {strcap.%player%}
					add 12 to {defcap.%player%}
					add 12 to {sklcap.%player%}
					add 7 to {spdcap.%player%}
					add 5 to {rescap.%player%}
					add 5 to {str.%player%}
					add 4 to {def.%player%}
					add 4 to {spd.%player%}
					add 6 to {res.%player%}
					add 3 to {hp.%player%}
					add 3 to {skl.%player%}
					set {class.%player%} to "Ranger"
					make player execute command "/grantskill 0 True Shot"
					send "<gold><bold>Promoted to a Ranger!"
				else if arg 2 is "Strategist1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 30
					set {strgrowth.%player%} to {pts_STR.%player%} + 15
					set {defgrowth.%player%} to {pts_DEF.%player%} + 30
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 20
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 15
					set {maggrowth.%player%} to {pts_MAG.%player%} + 30
					add 15 to {hpcap.%player%}
					add 7 to {strcap.%player%}
					add 15 to {defcap.%player%}
					add 10 to {sklcap.%player%}
					add 7 to {spdcap.%player%}
					add 15 to {rescap.%player%}
					add 3 to {str.%player%}
					add 3 to {def.%player%}
					add 3 to {spd.%player%}
					add 3 to {res.%player%}
					add 6 to {hp.%player%}
					add 3 to {skl.%player%}
					set {class.%player%} to "Tactician"
					make player execute command "/grantskill 0 Rally Speed"
					send "<gold><bold>Promoted to a Tactician!"
				else if arg 2 is "Gunslinger1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 30
					set {strgrowth.%player%} to {pts_STR.%player%} + 20
					set {defgrowth.%player%} to {pts_DEF.%player%} + 15
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 30
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 30
					set {maggrowth.%player%} to {pts_MAG.%player%} + 15
					add 15 to {hpcap.%player%}
					add 10 to {strcap.%player%}
					add 7 to {defcap.%player%}
					add 15 to {sklcap.%player%}
					add 15 to {spdcap.%player%}
					add 12 to {rescap.%player%}
					add 4 to {str.%player%}
					add 4 to {def.%player%}
					add 6 to {spd.%player%}
					add 4 to {res.%player%}
					add 6 to {hp.%player%}
					add 4 to {skl.%player%}
					set {class.%player%} to "Rifleman"
					make player execute command "/grantskill 0 Controlled Shot"
					send "<gold><bold>Promoted to a Rifleman!"
				else if arg 2 is "Devil Hunter1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 20
					set {strgrowth.%player%} to {pts_STR.%player%} + 30
					set {defgrowth.%player%} to {pts_DEF.%player%} + 10
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 50
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 30
					set {maggrowth.%player%} to {pts_MAG.%player%} + 10
					add 10 to {hpcap.%player%}
					add 15 to {strcap.%player%}
					add 5 to {defcap.%player%}
					add 25 to {sklcap.%player%}
					add 15 to {spdcap.%player%}
					add 5 to {rescap.%player%}
					add 3 to {str.%player%}
					add 10 to {spd.%player%}
					add 10 to {skl.%player%}
					set {class.%player%} to "Angel Slayer"
					make player execute command "/grantskill 0 Witch Time"
					make player execute command "/grantskill 0 Light Feet"
					send "<gold><bold>Promoted to an Angel Slayer!"
				else if arg 2 is "Mage1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 30
					set {strgrowth.%player%} to {pts_STR.%player%} + 5
					set {defgrowth.%player%} to {pts_DEF.%player%} + 15
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 20
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 20
					set {maggrowth.%player%} to {pts_MAG.%player%} + 50
					add 15 to {hpcap.%player%}
					add 3 to {strcap.%player%}
					add 7 to {defcap.%player%}
					add 10 to {sklcap.%player%}
					add 10 to {spdcap.%player%}
					add 25 to {rescap.%player%}
					add 3 to {str.%player%}
					add 3 to {def.%player%}
					add 4 to {spd.%player%}
					add 8 to {res.%player%}
					add 4 to {hp.%player%}
					add 3 to {skl.%player%}
					set {class.%player%} to "Sorcerer"
					make player execute command "/grantskill 0 Elder Knowledge"
					drop 1 blaze rod named "<yellow><bold>Magic Wand" at the player
					send "<gold><bold>Promoted to a Sorcerer!"
				else if arg 2 is "Knight1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 45
					set {strgrowth.%player%} to {pts_STR.%player%} + 15
					set {defgrowth.%player%} to {pts_DEF.%player%} + 50
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 15
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 10
					set {maggrowth.%player%} to {pts_MAG.%player%} + 5
					add 22 to {hpcap.%player%}
					add 7 to {strcap.%player%}
					add 25 to {defcap.%player%}
					add 7 to {sklcap.%player%}
					add 5 to {spdcap.%player%}
					add 2 to {rescap.%player%}
					add 2 to {str.%player%}
					add 8 to {def.%player%}
					add 1 to {spd.%player%}
					add 1 to {res.%player%}
					add 12 to {hp.%player%}
					add 2 to {skl.%player%}
					set {class.%player%} to "General"
					make player execute command "/grantskill 0 Fortress Defender"
					send "<gold><bold>Promoted to a General!"
				else if arg 2 is "Cavalier1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 30
					set {strgrowth.%player%} to {pts_STR.%player%} + 25
					set {defgrowth.%player%} to {pts_DEF.%player%} + 20
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 30
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 20
					set {maggrowth.%player%} to {pts_MAG.%player%} + 20
					add 15 to {hpcap.%player%}
					add 12 to {strcap.%player%}
					add 10 to {defcap.%player%}
					add 15 to {sklcap.%player%}
					add 10 to {spdcap.%player%}
					add 10 to {rescap.%player%}
					add 6 to {str.%player%}
					add 4 to {def.%player%}
					add 4 to {spd.%player%}
					add 5 to {res.%player%}
					add 4 to {hp.%player%}
					add 6 to {skl.%player%}
					set {class.%player%} to "Paladin"
					make player execute command "/grantskill 0 Canto"
					send "<gold><bold>Promoted to a Paladin!"
				else if arg 2 is "Bladesman1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 10
					set {strgrowth.%player%} to {pts_STR.%player%} + 25
					set {defgrowth.%player%} to {pts_DEF.%player%} + 10
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 40
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 50
					set {maggrowth.%player%} to {pts_MAG.%player%} + 5
					add 5 to {hpcap.%player%}
					add 12 to {strcap.%player%}
					add 5 to {defcap.%player%}
					add 20 to {sklcap.%player%}
					add 25 to {spdcap.%player%}
					add 2 to {rescap.%player%}
					add 2 to {str.%player%}
					add 2 to {def.%player%}
					add 6 to {spd.%player%}
					add 2 to {res.%player%}
					add 4 to {hp.%player%}
					add 8 to {skl.%player%}
					apply swiftness 1 to the player for 999 days
					set {class.%player%} to "Myrmidon"
					make player execute command "/grantskill 0 Life and Death"
					send "<gold><bold>Promoted to a Myrmidon!"
				else if arg 2 is "Fighter1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 40
					set {strgrowth.%player%} to {pts_STR.%player%} + 40
					set {defgrowth.%player%} to {pts_DEF.%player%} + 30
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 10
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 15
					set {maggrowth.%player%} to {pts_MAG.%player%} + 5
					add 20 to {hpcap.%player%}
					add 20 to {strcap.%player%}
					add 15 to {defcap.%player%}
					add 5 to {sklcap.%player%}
					add 7 to {spdcap.%player%}
					add 2 to {rescap.%player%}
					add 6 to {str.%player%}
					add 4 to {def.%player%}
					add 2 to {spd.%player%}
					add 1 to {res.%player%}
					add 8 to {hp.%player%}
					add 1 to {skl.%player%}
					set {class.%player%} to "Barbarian"
					make player execute command "/grantskill 0 Crushing Offense"
					send "<gold><bold>Promoted to a Barbarian!"
				else if arg 2 is "Mercenary1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 20
					set {strgrowth.%player%} to {pts_STR.%player%} + 25
					set {defgrowth.%player%} to {pts_DEF.%player%} + 25
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 25
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 20
					set {maggrowth.%player%} to {pts_MAG.%player%} + 25
					add 10 to {hpcap.%player%}
					add 12 to {strcap.%player%}
					add 12 to {defcap.%player%}
					add 12 to {sklcap.%player%}
					add 10 to {spdcap.%player%}
					add 12 to {rescap.%player%}
					add 6 to {str.%player%}
					add 6 to {def.%player%}
					add 6 to {spd.%player%}
					add 6 to {res.%player%}
					add 6 to {hp.%player%}
					add 6 to {skl.%player%}
					set {class.%player%} to "Hero"
					make player execute command "/grantskill 0 Double Lion"
					send "<gold><bold>Promoted to a Hero!"
				else if arg 2 is "Cleric1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 40
					set {strgrowth.%player%} to {pts_STR.%player%} + 10
					set {defgrowth.%player%} to {pts_DEF.%player%} + 15
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 15
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 15
					set {maggrowth.%player%} to {pts_MAG.%player%} + 45
					add 20 to {hpcap.%player%}
					add 5 to {strcap.%player%}
					add 7 to {defcap.%player%}
					add 7 to {sklcap.%player%}
					add 7 to {spdcap.%player%}
					add 22 to {rescap.%player%}
					add 1 to {str.%player%}
					add 3 to {def.%player%}
					add 3 to {spd.%player%}
					add 7 to {res.%player%}
					add 6 to {hp.%player%}
					add 3 to {skl.%player%}
					set {class.%player%} to "Bishop"
					make player execute command "/grantskill 0 Miracle"
					send "<gold><bold>Promoted to a Bishop!"
				else if arg 2 is "Dragonborn1":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 30
					set {strgrowth.%player%} to {pts_STR.%player%} + 10
					set {defgrowth.%player%} to {pts_DEF.%player%} + 35
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 15
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 10
					set {maggrowth.%player%} to {pts_MAG.%player%} + 30
					add 15 to {hpcap.%player%}
					add 5 to {strcap.%player%}
					add 17 to {defcap.%player%}
					add 7 to {sklcap.%player%}
					add 5 to {spdcap.%player%}
					add 15 to {rescap.%player%}
					add 1 to {str.%player%}
					add 4 to {def.%player%}
					add 1 to {spd.%player%}
					add 3 to {res.%player%}
					add 3 to {hp.%player%}
					add 1 to {skl.%player%}
					set {class.%player%} to "Manakete"
					make player execute command "/grantskill 0 Flight"
					send "<gold><bold>Promoted to a Manakete!"
				else if arg 2 is "Builder":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 10
					set {strgrowth.%player%} to {pts_STR.%player%} + 10
					set {defgrowth.%player%} to {pts_DEF.%player%} + 10
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 10
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 10
					set {maggrowth.%player%} to {pts_MAG.%player%} + 10
					add 5 to {hpcap.%player%}
					add 5 to {strcap.%player%}
					add 5 to {defcap.%player%}
					add 5 to {sklcap.%player%}
					add 5 to {spdcap.%player%}
					add 5 to {rescap.%player%}
					add 2 to {str.%player%}
					add 2 to {def.%player%}
					add 2 to {spd.%player%}
					add 2 to {res.%player%}
					add 2 to {hp.%player%}
					add 2 to {skl.%player%}
					set {class.%player%} to "Craftsman"
					make player execute command "/grantskill 0 Craftsmanship"
					send "<gold><bold>Promoted to a Craftsman!"
				else if arg 2 is "Ranger":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 25
					set {strgrowth.%player%} to {pts_STR.%player%} + 30
					set {defgrowth.%player%} to {pts_DEF.%player%} + 25
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 25
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 15
					set {maggrowth.%player%} to {pts_MAG.%player%} + 10
					add 12 to {hpcap.%player%}
					add 15 to {strcap.%player%}
					add 12 to {defcap.%player%}
					add 12 to {sklcap.%player%}
					add 7 to {spdcap.%player%}
					add 5 to {rescap.%player%}
					add 5 to {str.%player%}
					add 4 to {def.%player%}
					add 4 to {spd.%player%}
					add 6 to {res.%player%}
					add 3 to {hp.%player%}
					add 3 to {skl.%player%}
					set {class.%player%} to "Sniper"
					make player execute command "/grantskill 0 Heavy Draw"
					send "<gold><bold>Promoted to a Sniper!"
				else if arg 2 is "Tactician":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 25
					set {strgrowth.%player%} to {pts_STR.%player%} + 15
					set {defgrowth.%player%} to {pts_DEF.%player%} + 30
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 15
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 15
					set {maggrowth.%player%} to {pts_MAG.%player%} + 30
					add 12 to {hpcap.%player%}
					add 7 to {strcap.%player%}
					add 15 to {defcap.%player%}
					add 7 to {sklcap.%player%}
					add 7 to {spdcap.%player%}
					add 15 to {rescap.%player%}
					add 4 to {str.%player%}
					add 4 to {def.%player%}
					add 4 to {spd.%player%}
					add 4 to {res.%player%}
					add 6 to {hp.%player%}
					add 4 to {skl.%player%}
					set {class.%player%} to "Grandmaster"
					make player execute command "/grantskill 0 Rally Resistance"
					make player execute command "/grantskill 0 Spectrum +10"
					send "<gold><bold>Promoted to a Grandmaster!"
				else if arg 2 is "Rifleman":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 25
					set {strgrowth.%player%} to {pts_STR.%player%} + 20
					set {defgrowth.%player%} to {pts_DEF.%player%} + 10
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 30
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 30
					set {maggrowth.%player%} to {pts_MAG.%player%} + 15
					add 12 to {hpcap.%player%}
					add 10 to {strcap.%player%}
					add 5 to {defcap.%player%}
					add 15 to {sklcap.%player%}
					add 15 to {spdcap.%player%}
					add 12 to {rescap.%player%}
					add 4 to {str.%player%}
					add 3 to {def.%player%}
					add 7 to {spd.%player%}
					add 3 to {res.%player%}
					add 4 to {hp.%player%}
					add 7 to {skl.%player%}
					set {class.%player%} to "Doom Slayer"
					make player execute command "/grantskill 0 Resourceful"
					send "<gold><bold>Promoted to a Doom Slayer!"
				else if arg 2 is "Angel Slayer":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 20
					set {strgrowth.%player%} to {pts_STR.%player%} + 30
					set {defgrowth.%player%} to {pts_DEF.%player%} + 10
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 50
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 30
					set {maggrowth.%player%} to {pts_MAG.%player%} + 10
					add 10 to {hpcap.%player%}
					add 15 to {strcap.%player%}
					add 5 to {defcap.%player%}
					add 25 to {sklcap.%player%}
					add 15 to {spdcap.%player%}
					add 5 to {rescap.%player%}
					add 5 to {str.%player%}
					add 15 to {spd.%player%}
					add 10 to {skl.%player%}
					set {class.%player%} to "Platinum Star"
					make player execute command "/grantskill 0 Devil Trigger"
					make player execute command "/grantskill 0 Umbran Climax"
					send "<gold><bold>Promoted to a Platinum Star!"
				else if arg 2 is "General":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 40
					set {strgrowth.%player%} to {pts_STR.%player%} + 15
					set {defgrowth.%player%} to {pts_DEF.%player%} + 45
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 15
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 5
					set {maggrowth.%player%} to {pts_MAG.%player%} + 5
					add 40 to {hpcap.%player%}
					add 7 to {strcap.%player%}
					add 22 to {defcap.%player%}
					add 7 to {sklcap.%player%}
					add 2 to {spdcap.%player%}
					add 2 to {rescap.%player%}
					add 4 to {str.%player%}
					add 10 to {def.%player%}
					add 1 to {spd.%player%}
					add 1 to {res.%player%}
					add 20 to {hp.%player%}
					add 4 to {skl.%player%}
					make player execute command "/grantskill 0 Guard"
					set {class.%player%} to "Chieftain"
					send "<gold><bold>Promoted to a Chieftain!"
				else if arg 2 is "Paladin":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 30
					set {strgrowth.%player%} to {pts_STR.%player%} + 20
					set {defgrowth.%player%} to {pts_DEF.%player%} + 15
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 30
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 20
					set {maggrowth.%player%} to {pts_MAG.%player%} + 20
					add 15 to {hpcap.%player%}
					add 10 to {strcap.%player%}
					add 7 to {defcap.%player%}
					add 15 to {sklcap.%player%}
					add 10 to {spdcap.%player%}
					add 10 to {rescap.%player%}
					add 10 to {str.%player%}
					add 6 to {def.%player%}
					add 5 to {spd.%player%}
					add 5 to {res.%player%}
					add 6 to {hp.%player%}
					add 10 to {skl.%player%}
					set {class.%player%} to "Crusader"
					make player execute command "/grantskill 0 Crusader's Blood"
					make player execute command "/grantskill 0 Crusader's Ward"
					send "<gold><bold>Promoted to a Crusader!"
				else if arg 2 is "Myrmidon":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 10
					set {strgrowth.%player%} to {pts_STR.%player%} + 20
					set {defgrowth.%player%} to {pts_DEF.%player%} + 5
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 40
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 50
					set {maggrowth.%player%} to {pts_MAG.%player%} + 5
					add 5 to {hpcap.%player%}
					add 10 to {strcap.%player%}
					add 2 to {defcap.%player%}
					add 20 to {sklcap.%player%}
					add 25 to {spdcap.%player%}
					add 2 to {rescap.%player%}
					add 4 to {str.%player%}
					add 4 to {def.%player%}
					add 12 to {spd.%player%}
					add 4 to {res.%player%}
					add 4 to {hp.%player%}
					add 16 to {skl.%player%}
					make player execute command "/grantskill 0 Vantage"
					set {class.%player%} to "Swordmaster"
					send "<gold><bold>Promoted to a Swordmaster!"
				else if arg 2 is "Barbarian":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 40
					set {strgrowth.%player%} to {pts_STR.%player%} + 40
					set {defgrowth.%player%} to {pts_DEF.%player%} + 25
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 10
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 10
					set {maggrowth.%player%} to {pts_MAG.%player%} + 5
					add 20 to {hpcap.%player%}
					add 20 to {strcap.%player%}
					add 12 to {defcap.%player%}
					add 5 to {sklcap.%player%}
					add 5 to {spdcap.%player%}
					add 2 to {rescap.%player%}
					add 10 to {str.%player%}
					add 6 to {def.%player%}
					add 4 to {spd.%player%}
					add 2 to {res.%player%}
					add 7 to {hp.%player%}
					add 1 to {skl.%player%}
					set {slow1.%player%} to 1
					set {class.%player%} to "Warrior"
					make player execute command "/grantskill 0 STR +20"
					send "<gold><bold>Promoted to a Warrior!"
				else if arg 2 is "Hero":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 20
					set {strgrowth.%player%} to {pts_STR.%player%} + 25
					set {defgrowth.%player%} to {pts_DEF.%player%} + 20
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 25
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 20
					set {maggrowth.%player%} to {pts_MAG.%player%} + 20
					add 10 to {hpcap.%player%}
					add 10 to {strcap.%player%}
					add 12 to {defcap.%player%}
					add 12 to {sklcap.%player%}
					add 10 to {spdcap.%player%}
					add 10 to {rescap.%player%}
					add 6 to {str.%player%}
					add 6 to {def.%player%}
					add 6 to {spd.%player%}
					add 6 to {res.%player%}
					add 6 to {hp.%player%}
					add 6 to {skl.%player%}
					set {class.%player%} to "Junior Lord"
					make player execute command "/grantskill 0 Lord's Blood"
					send "<gold><bold>Promoted to a Junior Lord!"
				else if arg 2 is "Sorcerer":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 25
					set {strgrowth.%player%} to {pts_STR.%player%} + 5
					set {defgrowth.%player%} to {pts_DEF.%player%} + 15
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 20
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 20
					set {maggrowth.%player%} to {pts_MAG.%player%} + 45
					add 12 to {hpcap.%player%}
					add 3 to {strcap.%player%}
					add 7 to {defcap.%player%}
					add 10 to {sklcap.%player%}
					add 10 to {spdcap.%player%}
					add 22 to {rescap.%player%}
					add 2 to {str.%player%}
					add 3 to {def.%player%}
					add 5 to {spd.%player%}
					add 8 to {res.%player%}
					add 5 to {hp.%player%}
					add 3 to {skl.%player%}
					set {class.%player%} to "Archwizard"
					make player execute command "/grantskill 0 Brazen Spectrum"
					drop 1 blaze rod named "<yellow><bold>Magic Wand" at the player
					send "<gold><bold>Promoted to an Archwizard!"
				else if arg 2 is "Manakete":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 25
					set {strgrowth.%player%} to {pts_STR.%player%} + 10
					set {defgrowth.%player%} to {pts_DEF.%player%} + 30
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 15
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 10
					set {maggrowth.%player%} to {pts_MAG.%player%} + 25
					add 12 to {hpcap.%player%}
					add 5 to {strcap.%player%}
					add 15 to {defcap.%player%}
					add 7 to {sklcap.%player%}
					add 5 to {spdcap.%player%}
					add 12 to {rescap.%player%}
					add 2 to {str.%player%}
					add 2 to {def.%player%}
					add 2 to {spd.%player%}
					add 2 to {res.%player%}
					add 2 to {hp.%player%}
					add 2 to {skl.%player%}
					set {class.%player%} to "Divine Dragon"
					make player execute command "/grantskill 0 Draconic Rage"
					send "<gold><bold>Promoted to a Divine Dragon!"
				else if arg 2 is "Junior Lord":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 20
					set {strgrowth.%player%} to {pts_STR.%player%} + 20
					set {defgrowth.%player%} to {pts_DEF.%player%} + 20
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 20
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 20
					set {maggrowth.%player%} to {pts_MAG.%player%} + 20
					add 10 to {hpcap.%player%}
					add 10 to {strcap.%player%}
					add 10 to {defcap.%player%}
					add 10 to {sklcap.%player%}
					add 10 to {spdcap.%player%}
					add 10 to {rescap.%player%}
					add 6 to {str.%player%}
					add 6 to {def.%player%}
					add 6 to {spd.%player%}
					add 6 to {res.%player%}
					add 6 to {hp.%player%}
					add 6 to {skl.%player%}
					set {class.%player%} to "Lord"
					make player execute command "/grantskill 0 Rightful King"
					send "<gold><bold>Promoted to a Lord!"
				else if arg 2 is "Bishop":
					set {hpgrowth.%player%} to {pts_HP.%player%} + 35
					set {strgrowth.%player%} to {pts_STR.%player%} + 10
					set {defgrowth.%player%} to {pts_DEF.%player%} + 15
					set {sklgrowth.%player%} to {pts_SKL.%player%} + 15
					set {spdgrowth.%player%} to {pts_SPD.%player%} + 10
					set {maggrowth.%player%} to {pts_MAG.%player%} + 45
					add 17 to {hpcap.%player%}
					add 5 to {strcap.%player%}
					add 7 to {defcap.%player%}
					add 7 to {sklcap.%player%}
					add 5 to {spdcap.%player%}
					add 22 to {rescap.%player%}
					add 1 to {str.%player%}
					add 2 to {def.%player%}
					add 2 to {spd.%player%}
					add 10 to {res.%player%}
					add 6 to {hp.%player%}
					add 2 to {skl.%player%}
					set {class.%player%} to "Sage"
					make player execute command "/grantskill 0 Wrathful Staff"
					send "<gold><bold>Promoted to a Sage!"
				else if arg 2 is "Overclass":
					add 15 to {strcap.%player%}
					add 2 to {str.%player%}
					add 15 to {defcap.%player%}
					add 2 to {def.%player%}
					add 15 to {spdcap.%player%}
					add 2 to {spd.%player%}
					add 15 to {rescap.%player%}
					add 2 to {res.%player%}
					add 20 to {hpcap.%player%}
					add 2 to {hp.%player%}
					add 15 to {sklcap.%player%}
					add 2 to {skl.%player%}
					send "<gold><bold>Overclass complete!"
				else if arg 2 is "cancel":
					set {promotionready.%player%} to 0
				set {lvlcap.%player%} to {lvl.%player%} + 30
				add 1 to {promoted.%player%}
				if {class.%player%} is "Journeyman":
					set {promoted.%player%} to 0
				if {str.%player%} is more than {strcap.%player%}:
					set {str.%player%} to {strcap.%player%}
				if {def.%player%} is more than {defcap.%player%}:
					set {def.%player%} to {defcap.%player%}
				if {skl.%player%} is more than {sklcap.%player%}:
					set {skl.%player%} to {sklcap.%player%}
				if {hp.%player%} is more than {hpcap.%player%}:
					set {hp.%player%} to {hpcap.%player%}
				if {spd.%player%} is more than {spdcap.%player%}:
					set {spd.%player%} to {spdcap.%player%}
				if {res.%player%} is more than {rescap.%player%}:
					set {res.%player%} to {rescap.%player%}
				wait 0.4 seconds
				send title "<gold><bold>--==Class Up!==--" with subtitle "<gold>%{class.%player%}%" to player for 3 seconds with fade in 0.5 second and fade out 1 seconds
				play sound "entity.player.levelup" with volume 2 and pitch 1 at player for player
				play 10 (mob spawner flames with speed 1) at the player
				play 50 (magical critical hit with speed 0) at the player
				play 50 (smoke with speed 0) at the player
				strike lightning effect at the player
				if arg 2 is "Overclass":
					broadcast "<gold>%player's name% has Overclassed!"
				else if arg 2 is "Reset":
					broadcast "<gold>%player's name% has reset their stats."
				else:
					broadcast "<gold>%player's name% has promoted to %{class.%player%}%!"
				wait 2 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 0.8 at player for player
				send "Strength: %{_oldstr.%player%}% --> %{str.%player%}%"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 0.8 at player for player
				send "Defense: %{_olddef.%player%}% --> %{def.%player%}%"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 0.8 at player for player
				send "Skill: %{_oldskl.%player%}% --> %{skl.%player%}%"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 0.8 at player for player
				send "Speed: %{_oldspd.%player%}% --> %{spd.%player%}%"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 0.8 at player for player
				send "Magic: %{_oldres.%player%}% --> %{res.%player%}%"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 0.8 at player for player
				send "Health: %{_oldhp.%player%}% --> %{hp.%player%}%"
				set the player's maximum health to ({hp.%player%} / 2) + ({hpbuff.%player%} / 2)
				make player say "%{promotionQuote.%player%}%"
			else:
				send "You may only promote through use of the Journey's Crest or Warrior's Proof."
				
#MARKER - Level-Up Handler


on level change:
	if player is alive:
		if player's level is more than {lvl.%player%}:
			if {lvl.%player%} is less than {lvlcap.%player%}:
				play sound "entity.player.levelup" with volume 2 and pitch 1 at player for player
				#send "<gold>Level Up!"
				set {_oldstr.%player%} to {str.%player%}
				set {_olddef.%player%} to {def.%player%}
				set {_oldhp.%player%} to {hp.%player%}
				set {_oldskl.%player%} to {skl.%player%}
				set {_oldspd.%player%} to {spd.%player%}
				set {_oldres.%player%} to {res.%player%}
				if player's level is more than {lvlcap.%player%}:
					set player's level to {lvlcap.%player%}
				loop (player's level - {lvl.%player%}) times:
					add 1 to {lvl.%player%}
					#HP Growths
					if {hpgrowth.%player%} is more than 100:
						set {_growthtemp} to {hpgrowth.%player%}
						while {_growthtemp} is more than 100:
							add 1 to {hp.%player%}
							subtract 100 from {_growthtemp}
						chance of {_growthtemp}%:
							add 1 to {hp.%player%}
					else:
						chance of {hpgrowth.%player%}:
							add 1 to {hp.%player%}
					#STR Growths
					if {strgrowth.%player%} is more than 100:
						set {_growthtemp} to {strgrowth.%player%}
						while {_growthtemp} is more than 100:
							add 1 to {str.%player%}
							subtract 100 from {_growthtemp}
						chance of {_growthtemp}%:
							add 1 to {str.%player%}
					else:
						chance of {strgrowth.%player%}:
							add 1 to {str.%player%}
					#DEF Growths
					if {defgrowth.%player%} is more than 100:
						set {_growthtemp} to {defgrowth.%player%}
						while {_growthtemp} is more than 100:
							add 1 to {def.%player%}
							subtract 100 from {_growthtemp}
						chance of {_growthtemp}%:
							add 1 to {def.%player%}
					else:
						chance of {defgrowth.%player%}:
							add 1 to {def.%player%}
					#SKL Growths
					if {sklgrowth.%player%} is more than 100:
						set {_growthtemp} to {defgrowth.%player%}
						while {_growthtemp} is more than 100:
							add 1 to {skl.%player%}
							subtract 100 from {_growthtemp}
						chance of {_growthtemp}%:
							add 1 to {skl.%player%}
					else:
						chance of {sklgrowth.%player%}:
							add 1 to {skl.%player%}
					#SPD Growths
					if {spdgrowth.%player%} is more than 100:
						set {_growthtemp} to {spdgrowth.%player%}
						while {_growthtemp} is more than 100:
							add 1 to {spd.%player%}
							subtract 100 from {_growthtemp}
						chance of {_growthtemp}%:
							add 1 to {spd.%player%}
					else:
						chance of {spdgrowth.%player%}:
							add 1 to {spd.%player%}
					#MAG Growths
					if {maggrowth.%player%} is more than 100:
						set {_growthtemp} to {maggrowth.%player%}
						while {_growthtemp} is more than 100:
							add 1 to {res.%player%}
							subtract 100 from {_growthtemp}
						chance of {_growthtemp}%:
							add 1 to {res.%player%}
					else:
						chance of {maggrowth.%player%}:
							add 1 to {res.%player%}
					#Limit growths to stat caps
					if {str.%player%} is more than {strcap.%player%}:
						set {str.%player%} to {strcap.%player%}
					if {def.%player%} is more than {defcap.%player%}:
						set {def.%player%} to {defcap.%player%}
					if {hp.%player%} is more than {hpcap.%player%}:
						set {hp.%player%} to {hpcap.%player%}
					if {skl.%player%} is more than {sklcap.%player%}:
						set {skl.%player%} to {sklcap.%player%}
					if {spd.%player%} is more than {spdcap.%player%}:
						set {spd.%player%} to {spdcap.%player%}
					if {res.%player%} is more than {rescap.%player%}:
						set {res.%player%} to {rescap.%player%}
				send title "<gold><bold>---===Level Up!===---" with subtitle "<bold>Level: %{lvl.%player%}%" to player for 2 seconds with fade in 0.25 second and fade out 0.5 seconds
				wait 2 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 0.8 at player for player
				send "Strength: %{_oldstr.%player%}% --> %{str.%player%}%"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 0.8 at player for player
				send "Defense: %{_olddef.%player%}% --> %{def.%player%}%"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 0.8 at player for player
				send "Skill: %{_oldskl.%player%}% --> %{skl.%player%}%"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 0.8 at player for player
				send "Speed: %{_oldspd.%player%}% --> %{spd.%player%}%"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 0.8 at player for player
				send "Magic: %{_oldres.%player%}% --> %{res.%player%}%"
				wait 0.4 seconds
				play sound "entity.experience_orb.pickup" with volume 2 and pitch 0.8 at player for player
				send "Health: %{_oldhp.%player%}% --> %{hp.%player%}%"
				wait 0.4 seconds
				set the player's maximum health to ({hp.%player%} / 2) + ({hpbuff.%player%} / 2)
				wait 0.6 seconds
				set {_oldbst} to {bst.%player%}
				set {bst.%player%} to ({str.%player%} + {def.%player%} + {skl.%player%} + {spd.%player%} + {res.%player%} + {hp.%player%})
				set {bstcap.%player%} to ({strcap.%player%} + {defcap.%player%} + {sklcap.%player%} + {spdcap.%player%} + {rescap.%player%} + {hpcap.%player%})
				if {bstcap.%player%} - {bst.%player%} is less than 10:
					make player say "%{maxLevelQuote.%player%}%"
				else if {bst.%player%} - {_oldbst} is less than 2:
					make player say "%{badLevelQuote.%player%}%"
				else if {bst.%player%} - {_oldbst} is less than 5:
					make player say "%{avgLevelQuote.%player%}%"
				else:
					make player say "%{goodLevelQuote.%player%}%"
				#Renewal at LVL 10+
				if {lvl.%player%} is more than 9:
					if {Renewal.%player%} is not set:
						make player execute command "/grantskill 0 Renewal"
				#Restock at LVL 15+
				if {lvl.%player%} is more than 14:
					if {Restock.%player%} is not set:
						make player execute command "/grantskill 0 Restock"
				#HP +5 at LVL 1
				if {lvl.%player%} is more than 0:
					if {HP +5.%player%} is not set:
						make player execute command "/grantskill 0 HP +5"
				#STR +5 at LVL 3
				if {lvl.%player%} is more than 2:
					if {STR +5.%player%} is not set:
						make player execute command "/grantskill 0 STR +5"
				#DEF +5 at LVL 5
				if {lvl.%player%} is more than 4:
					if {DEF +5.%player%} is not set:
						make player execute command "/grantskill 0 DEF +5"
				#SKL +5 at LVL 7
				if {lvl.%player%} is more than 6:
					if {SKL +5.%player%} is not set:
						make player execute command "/grantskill 0 SKL +5"
				#SPD +5 at LVL 9
				if {lvl.%player%} is more than 8:
					if {SPD +5.%player%} is not set:
						make player execute command "/grantskill 0 SPD +5"
				#RES +5 at LVL 11
				if {lvl.%player%} is more than 10:
					if {MAG +5.%player%} is not set:
						make player execute command "/grantskill 0 MAG +5"
				#High Jumper at LVL 13
				if {lvl.%player%} is more than 12:
					if {High Jumper.%player%} is not set:
						make player execute command "/grantskill 0 High Jumper"
				#Brazen MAG at LVL 15
				if {lvl.%player%} is more than 14:
					if {Brazen MAG.%player%} is not set:
						make player execute command "/grantskill 0 Brazen MAG"
				#Brazen SKL at LVL 20
				if {lvl.%player%} is more than 19:
					if {Brazen SKL.%player%} is not set:
						make player execute command "/grantskill 0 Brazen SKL"
				#Brazen DEF at LVL 25
				if {lvl.%player%} is more than 24:
					if {Brazen DEF.%player%} is not set:
						make player execute command "/grantskill 0 Brazen DEF"
				#Brazen SPD at LVL 30
				if {lvl.%player%} is more than 29:
					if {Brazen SPD.%player%} is not set:
						make player execute command "/grantskill 0 Brazen SPD"
				#Brazen STR at LVL 35
				if {lvl.%player%} is more than 34:
					if {Brazen STR.%player%} is not set:
						make player execute command "/grantskill 0 Brazen STR"
				#Ranged Specialist at LVL 48:
				if {lvl.%player%} is more than 47:
					if {Ranged Specialist.%player%} is not set:
						make player execute command "/grantskill 0 Ranged Specialist"
				#Lance Specialist at LVL 55:
				if {lvl.%player%} is more than 54:
					if {Lance Specialist.%player%} is not set:
						make player execute command "/grantskill 0 Lance Specialist"
				#Axe Specialist at LVL 60:
				if {lvl.%player%} is more than 59:
					if {Axe Specialist.%player%} is not set:
						make player execute command "/grantskill 0 Axe Specialist"
				#Sword Specialist at LVL 65:
				if {lvl.%player%} is more than 64:
					if {Sword Specialist.%player%} is not set:
						make player execute command "/grantskill 0 Sword Specialist"
				#Mystic Boost at LVL 70
				if {lvl.%player%} is more than 69:
					if {Mystic Boost.%player%} is not set:
						make player execute command "/grantskill 0 Mystic Boost"
				#Nihl at LVL 75
				if {lvl.%player%} is more than 74:
					if {Nihl.%player%} is not set:
						make player execute command "/grantskill 0 Nihl"
				#Sacred Boost at LVL 80
				if {lvl.%player%} is more than 79:
					if {Sacred Boost.%player%} is not set:
						make player execute command "/grantskill 0 Sacred Boost"
				#Fire spell at LVL 12
				set {_isMagical} to checkClass(player)
				if {_isMagical} is 1:
					if {lvl.%player%} is more than 11:
						if {Fire.%player%} is not set:
							make player execute command "/grantskill 0 Fire"
					if {lvl.%player%} is more than 14:
						if {Hail.%player%} is not set:
							make player execute command "/grantskill 0 Hail"
					if {lvl.%player%} is more than 17:
						if {Thunder.%player%} is not set:
							make player execute command "/grantskill 0 Thunder"
					if {lvl.%player%} is more than 20:
						if {Wind.%player%} is not set:
							make player execute command "/grantskill 0 Wind"
					if {lvl.%player%} is more than 23:
						if {Elfire.%player%} is not set:
							make player execute command "/grantskill 0 Elfire"
					if {lvl.%player%} is more than 26:
						if {Blizzard.%player%} is not set:
							make player execute command "/grantskill 0 Blizzard"
					if {lvl.%player%} is more than 29:
						if {Thoron.%player%} is not set:
							make player execute command "/grantskill 0 Thoron"
					if {lvl.%player%} is more than 32:
						if {Tornado.%player%} is not set:
							make player execute command "/grantskill 0 Tornado"
					if {lvl.%player%} is more than 35:
						if {Bolganone.%player%} is not set:
							make player execute command "/grantskill 0 Bolganone"
					if {lvl.%player%} is more than 38:
						if {Aurora.%player%} is not set:
							make player execute command "/grantskill 0 Aurora"
					if {lvl.%player%} is more than 41:
						if {Nosferatu.%player%} is not set:
							make player execute command "/grantskill 0 Nosferatu"
					if {lvl.%player%} is more than 44:
						if {Light.%player%} is not set:
							make player execute command "/grantskill 0 Light"
					if {lvl.%player%} is more than 47:
						if {Thief.%player%} is not set:
							make player execute command "/grantskill 0 Thief"
					if {lvl.%player%} is more than 21:
						if {Silence.%player%} is not set:
							make player execute command "/grantskill 0 Silence"
					if {lvl.%player%} is more than 51:
						if {Naga.%player%} is not set:
							make player execute command "/grantskill 0 Naga"
					if {lvl.%player%} is more than 55:
						if {Loptous.%player%} is not set:
							make player execute command "/grantskill 0 Loptous"
					if {lvl.%player%} is more than 33:
						if {Silence.%player%} is not set:
							make player execute command "/grantskill 0 Slipgate"
					if {lvl.%player%} is more than 37:
						if {Silence.%player%} is not set:
							make player execute command "/grantskill 0 Rescue"
					if {lvl.%player%} is more than 60:
						if {Spellblade.%player%} is not set:
							make player execute command "/grantskill 0 Spellblade"
					if {lvl.%player%} is more than 51:
						if {Stone.%player%} is not set:
							make player execute command "/grantskill 0 Stone"
					if {lvl.%player%} is more than 54:
						if {Forseti.%player%} is not set:
							make player execute command "/grantskill 0 Forseti"
					
							
#MARKER - Respawn & Misc. Handler
on heal:
	if {spd.%player%} is more than 125:
		remove swiftness from the player
		apply swiftness 5 to the player for 1 day
	else if {spd.%player%} is more than 100:
		remove swiftness from the player
		apply swiftness 4 to the player for 1 day
	else if {spd.%player%} is more than 75:
		remove swiftness from the player
		apply swiftness 3 to the player for 1 day
	else if {spd.%player%} is more than 50:
		remove swiftness from the player
		apply swiftness 2 to the player for 1 day
	else if {spd.%player%} is more than 25:
		remove swiftness from the player
		apply swiftness 1 to the player for 1 day

on respawn:
	if {spd.%player%} is more than 25:
		remove swiftness from the player
		apply swiftness 1 to the player for 1 day
	else if {spd.%player%} is more than 50:
		remove swiftness from the player
		apply swiftness 2 to the player for 1 day
	else if {spd.%player%} is more than 75:
		remove swiftness from the player
		apply swiftness 3 to the player for 1 day
	else if {spd.%player%} is more than 100:
		remove swiftness from the player
		apply swiftness 4 to the player for 1 day
	else if {spd.%player%} is more than 125:
		remove swiftness from the player
		apply swiftness 5 to the player for 1 day

on death:
	add 1 to {kills.%attacker%}
		
on death of a player:
	if victim is not npc:
		add 1 to {deaths.%victim%}
		set {lastDeath.%player%} to the victim's location
		spawn 1 zombie at the victim's location
		set {_xpLost} to ceil(victim's level ^ 0.35)
		make victim execute command "/xp -%{_xpLost}%l"
		send "<light red>You lost %{_xpLost}% xp levels..." to the victim
		
every hour:
	loop all players:
		add 1 to {hoursplayed.%loop-player%}