Enable economy: true
Item resale value (percentage): 5
Procedurally Generated Loot:
  Lowest shop item tier: 1
  Highest shop item tier: 5
Currency name: Elite Coins
Shop name: EliteMobs Shop
Custom shop name: EliteMobs Custom Shop
Reroll button location for EliteMobs Shops: 4
Valid chest slots for EliteMobs Shop:
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47
- 48
- 49
- 50
- 51
- 52
- 53
Valid chest slots for EliteMobs Custom Shop:
- 9
- 10
- 11
- 12
- 13
- 14
- 15
- 16
- 17
- 18
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 26
- 27
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 35
- 36
- 37
- 38
- 39
- 40
- 41
- 42
- 43
- 44
- 45
- 46
- 47
- 48
- 49
- 50
- 51
- 52
- 53
Sell shop name: EliteMobs Sell Menu
Sell shop info slot: 8
Sell shop info item name: '&cWarning!'
Sell shop info item lore:
- '&cYou can only sell special'
- '&cElite Mobs drops in this'
- '&cshop! These should have'
- '&ca value on their lore.'
Sell shop cancel slot: 27
Sell shop cancel name: '&4Cancel'
Sell shop cancel lore:
- '&cCancel sale!'
Sell shop confirm slot: 35
Sell shop confirm name: '&2Confirm sale!'
Sell shop confirm lore:
- '&aSell items for'
- '&a$currency_amount $currency_name'
Valid chest slots for EliteMobs Sell Shop:
- 19
- 20
- 21
- 22
- 23
- 24
- 25
- 28
- 29
- 30
- 31
- 32
- 33
- 34
- 37
- 38
- 39
- 40
- 41
- 42
- 43
Material worth:
  DIAMOND_AXE: 13.0
  DIAMOND_BARDING: 13.0
  DIAMOND_BLOCK: 13.0
  DIAMOND_BOOTS: 13.0
  DIAMOND_CHESTPLATE: 13.0
  DIAMOND_HELMET: 13.0
  DIAMOND_HOE: 13.0
  DIAMOND_LEGGINGS: 13.0
  DIAMOND_ORE: 13.0
  DIAMOND_PICKAXE: 13.0
  DIAMOND_SPADE: 13.0
  DIAMOND_SWORD: 13.0
  IRON_AXE: 12.0
  IRON_BARDING: 12.0
  IRON_BLOCK: 12.0
  IRON_BOOTS: 12.0
  IRON_CHESTPLATE: 12.0
  IRON_HELMET: 12.0
  IRON_HOE: 12.0
  IRON_INGOT: 12.0
  IRON_LEGGINGS: 12.0
  IRON_NUGGET: 12.0
  IRON_ORE: 12.0
  IRON_PICKAXE: 12.0
  IRON_SPADE: 12.0
  IRON_SWORD: 12.0
  SHIELD: 12.0
  BOW: 12.0
  CHAINMAIL_BOOTS: 11.0
  CHAINMAIL_CHESTPLATE: 11.0
  CHAINMAIL_HELMET: 11.0
  CHAINMAIL_LEGGINGS: 11.0
  STONE_SWORD: 11.0
  STONE_AXE: 11.0
  STONE_PICKAXE: 11.0
  STONE_SPADE: 11.0
  GOLD_AXE: 10.0
  GOLD_BARDING: 10.0
  GOLD_BLOCK: 10.0
  GOLD_BOOTS: 10.0
  GOLD_CHESTPLATE: 10.0
  GOLD_HELMET: 10.0
  GOLD_HOE: 10.0
  GOLD_INGOT: 10.0
  GOLD_LEGGINGS: 10.0
  GOLD_NUGGET: 10.0
  GOLD_ORE: 10.0
  GOLD_PICKAXE: 10.0
  GOLD_SPADE: 10.0
  GOLD_SWORD: 10.0
  GOLDEN_APPLE: 10.0
  GOLDEN_CARROT: 10.0
  LEATHER_BOOTS: 10.0
  LEATHER_CHESTPLATE: 10.0
  LEATHER_HELMET: 10.0
  LEATHER_LEGGINGS: 10.0
  WOOD_SWORD: 10.0
  WOOD_AXE: 10.0
  WOOD_PICKAXE: 10.0
  WOOD_HOE: 10.0
  OTHER: 1
Enchantment worth:
  ARROW_DAMAGE: 13.0
  ARROW_FIRE: 6.5
  ARROW_INFINITE: 6.5
  ARROW_KNOCKBACK: 6.5
  BINDING_CURSE: -1
  DAMAGE_ALL: 13.0
  DAMAGE_ARTHROPODS: 6.5
  DAMAGE_UNDEAD: 6.5
  DEPTH_STRIDER: 1
  DIG_SPEED: 13.0
  DURABILITY: 13.0
  FIRE_ASPECT: 6.5
  FROST_WALKER: 1
  KNOCKBACK: 6.5
  LOOT_BONUS_BLOCKS: 13.0
  LOOT_BONUS_MOBS: 6.5
  LUCK: 1
  LURE: 1
  MENDING: 26.0
  OXYGEN: 1
  PROTECTION_ENVIRONMENTAL: 13.0
  PROTECTION_EXPLOSIONS: 6.5
  PROTECTION_FALL: 6.5
  PROTECTION_FIRE: 6.5
  PROTECTION_PROJECTILE: 13.0
  SILK_TOUCH: 13.0
  SWEEPING_EDGE: 13.0
  THORNS: 13.0
  VANISHING_CURSE: -1
  WATER_WORKER: 1
Potion effect worth:
  ABSORPTION: 130.0
  BLINDNESS: 65.0
  CONFUSION: 65.0
  DAMAGE_RESISTANCE: 130.0
  FAST_DIGGING: 130.0
  FIRE_RESISTANCE: 65.0
  GLOWING: 10
  HARM: 130.0
  HEAL: 130.0
  HEALTH_BOOST: 130.0
  HUNGER: 10
  INCREASE_DAMAGE: 130.0
  INVISIBILITY: 65.0
  JUMP: 65.0
  LEVITATION: 65.0
  LUCK: 10
  NIGHT_VISION: 10
  POISON: 65.0
  REGENERATION: 130.0
  SATURATION_NAME: 65.0
  SLOW: 65.0
  SLOW_DIGGING: 10
  SPEED: 65.0
  UNLUCK: 10
  WATER_BREATHING: 10
  WEAKNESS: 130.0
  WITHER: 65.0
